### ISSUE TITLE
NavigationMenuSample Crashes When Clicking Hamburger Menu

### ISSUE THREAD

**Issue by scottkuhl** [Microsoft/Windows-universal-samples#10]
This is the error message when you select the hamburger menu in the NavigationMenuSample app.

Message = "The text associated with this error code could not be found.\r\n\r\nA TargetPropertyPath for a Style Setter cannot specify an explicit Target object. [Line: 55 Position: 49]"

**Comment by micahl** [comment]
Should now be fixed by 664e4916e43d85d019f37d6f070549df8e140385
