### ISSUE TITLE
ResizeAppView does not work on hololens

### ISSUE THREAD

**Issue by KKica** [Microsoft/Windows-universal-samples#1008]
The resizing does not work on HoloLens. I have used this code to test.

```
private void ResizeView_Click(object sender, RoutedEventArgs e)
        {
            var view = ApplicationView.GetForCurrentView();
            for(int i = 300; i < 1000; i++)
            {
                for(int j = 200; j < 1000; j++)
                {
                    if (view.TryResizeView(new Size { Width = i, Height = j }))
                    {
                        rootPage.NotifyUser("Resizing to "+i.ToString()+" \u00D7 "+j.ToString(), NotifyType.StatusMessage);
                        return;
                        // The SizeChanged event will be raised when the resize is complete.
                    }
                }
            }
           
           
                // The system does not support resizing, or the provided size is out of range.
                rootPage.NotifyUser("Failed to resize view", NotifyType.ErrorMessage);
            
        }
```

**Comment by oldnewthing** [comment]
Can you be more specific what you mean by "does not work"? Does the app crash? Does the call to `TryResizeView` return `true` but no actual resize occurs? Does the call to `TryResizeView` return false and no resize occurs? If it returns false and no resize occurs, then the API is behaving as designed. (Are you saying "HoloLens should support programmatic resizing"? That's a feature request.)

**Comment by KKica** [comment]
It returns false. I did not know that it did not support Hololens. If that is the case, then I will close the issue.

**Comment by oldnewthing** [comment]
I don't know what HoloLens is expected to do. But the API is behaving as designed.

**Comment by KKica** [comment]
The app can be resized manually in Hololens, and if that API works in a system that does support programmatic resizing, and the method always returns false, then i think there is a bug (that is why I opened this issue), or there should be a known issue for the sample:  "This is UWP API, but it does not work (yet) on Hololens"

**Comment by oldnewthing** [comment]
I asked the HoloLens people, and they said that it is by design that TryResizeView does not do anything on HoloLens. HoloLens runs 2D apps in a slate, and the app cannot resize the slate.

**Comment by orazio3** [comment]
Antartide, scoperti antichi continenti sotto i ghiacci 
Scoperti i resti di antichi continenti perduti sotto i ghiacci dell'Antartide. Li ha visti il satellite europeo Goce, che dal 2009 al 2013 ha studiato la gravità terrestre. Sono almeno tre frammenti, i più antichi dei quali potrebbero avere un'età compresa tra un miliardo e 550 milioni di anni, e potrebbero aiutare a capire il comportamento dei ghiacciai antartici.

La scoperta è stata pubblicata sulla rivista Scientific Reports, e si deve all'Università tedesca di Kiel e al British Antarctic Survey (Bas). Una scoperta che parla anche un po'italiano grazie a Fausto Ferraccioli, a capo del gruppo di geologia e geofisica del Bas.
Combinando le misure della missione dell'Agenzia Spaziale Europea con le informazioni fornite dalle onde sismiche, che permettono di radiografare l'interno della Terra, i ricercatori sono riusciti a ottenere una mappa 3D delle placche continentali, che ha aperto una finestra sulle profondità del pianeta, ma soprattutto dell'Antartide.

"Queste immagini stanno rivoluzionando la nostra capacità di studiare il continente meno conosciuto" spiega Ferraccioli. "Sotto l'Antartide orientale vediamo un emozionante mosaico di frammenti di continenti perduti, che rivelano somiglianze e differenze tra la crosta sotto l'Antartide e gli altri continenti, a cui i frammenti erano uniti fino a 160 milioni di anni fa".
