### ISSUE TITLE
webAccount.username always null

### ISSUE THREAD

**Issue by LaurentTermeau** [Microsoft/Windows-universal-samples#101]
In the WebAccountManagement sample, the scenario "login with default Microsoft Account" seems to login ok, but the webAccount.userName is always null. 
Also, when,extending the scope with wl.emails in,addition,to wl.basics, no emails information is available.
Would This ne because I run,the code from a Windows 10 build 10240 included in,a,professional domain ? Or is This due to annoter reason ?
Laurent

**Comment by msftchcamp** [comment]
Normally you would use the token gained from the RequestTokenAsync with the Live APIs (https://msdn.microsoft.com/en-us/library/hh243641.aspx) but right now there is not a LiveSDK for Universal Windows Apps. It is coming, but for now the only way is to use OAUTH. (https://msdn.microsoft.com/en-us/library/hh243647.aspx)

**Comment by ryanwinter** [comment]
So is the UWP LiveSDK still coming?

**Comment by msftchcamp** [comment]
There is going to be a set of new SDKs that replaces what the LiveSDK used to do pre UWP. (https://github.com/liveservices/LiveSDK-for-Windows/issues/58) But the logic is still the same, get a token from RequestTokenAsync and use it with these APIs.
