### ISSUE TITLE
SimpleCommunication sample doesn't use powers of 2 for flags

### ISSUE THREAD

**Issue by axilesoft** [Microsoft/Windows-universal-samples#1010]
https://github.com/Microsoft/Windows-universal-samples/blob/fe8567faf2efdea3672c2ba642ba7b925ff6467e/Samples/SimpleCommunication/common/MediaExtensions/Microsoft.Samples.SimpleCommunication/StspDefs.h#L64

Why the StspSampleFlags flag values are default enum value {0,1,2,3,4,5,6}, should it be {1,2,4,8,16,32,64} ?

**Comment by oldnewthing** [comment]
Yeah that does look wrong. Let me see what the feature team says.

**Comment by oldnewthing** [comment]
Feature team agrees. Fix will be in the next update. Thanks for reporting.
