### ISSUE TITLE
SplashScreen sample: extendedSplashImage not showing at right position on xbox

### ISSUE THREAD

**Issue by HppZ** [Microsoft/Windows-universal-samples#1011]

**Comment by oldnewthing** [comment]
I've asked the feature team to investigate.

**Comment by HppZ** [comment]
I am wondering why SplashScreen behaves different on Desktop / Mobile / Xbox, and you have to do `if (Windows.Foundation.Metadata.ApiInformation.IsTypePresent("Windows.Phone.UI.Input.HardwareButtons"))`. that even does not work on Xbox. It is strange that we have to deal with SplashScreen separately on different plateforms.

**Comment by HppZ** [comment]
any further information available, please?

**Comment by oldnewthing** [comment]
The feature team has decided not to fix this issue.
