### ISSUE TITLE
ThemeShadow is missing from the SDK

### ISSUE THREAD

**Issue by chungweileong94** [Microsoft/Windows-universal-samples#1013]
I can't actually use the `ThemeShadow` in the latest SDK (and the latest Windows 10 (RS5)), I try to follow the [documentation](https://docs.microsoft.com/en-us/windows/uwp/design/layout/depth-shadow#themeshadow), but nothing helps.

**Comment by oldnewthing** [comment]
This is not a question about any sample in this repo. You can open a support case with our Developer Support team:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
