### ISSUE TITLE
Xaml Internal Error error WMC9999: Sequence contains no elements

### ISSUE THREAD

**Issue by dumbledad** [Microsoft/Windows-universal-samples#1018]
When I try to build the WebSocket sample I get the build error

> 1>C:\Program Files (x86)\Windows Kits\10\bin\10.0.17134.0\XamlCompiler\Microsoft.Windows.UI.Xaml.Common.targets(375,5): Xaml Internal Error error WMC9999: Sequence contains no elements

**Comment by oldnewthing** [comment]
Please be more specific which version of the sample you are using, which language, which platform, which configuration. I cannot reproduce the problem with win10-1803 WebSocket C++ Debug x86, or with win10-1803 WebSocket C# Release x64.
