### ISSUE TITLE
BluetoothLE BackgroundTask

### ISSUE THREAD

**Issue by RuslanSCH** [Microsoft/Windows-universal-samples#102]
Exeption: 
"Access is denied. Your App does not have permission to use Bluetooth in the background. Make sure you have declared the Task Type 'bluetooth' in your manifest."

This exeption was trow for BluetoothAdvertisement SampleProject, same for my testProject.
AppManifest following:

![manifestforgithub](https://cloud.githubusercontent.com/assets/12908437/9022034/2746fc3a-3864-11e5-8212-2df4c5379e11.PNG)

**Comment by lisaong** [comment]
The issue no longer repros with the RTM push of the samples. To test on mobile device, you may need to wait until the next mobile flight update of 10240 or higher. This sample also won't work on the emulator.  It requires a real Bluetooth radio. 

Thanks for the feedback, the readme.md has been updated.

**Comment by tendimsol** [comment]
Access is denied... build 10512
