### ISSUE TITLE
Family purchases

### ISSUE THREAD

**Issue by vonlar** [Microsoft/Windows-universal-samples#1022]
How do I get a hold of the team that controls the Windows Store?  There should be a setting that I can share a purchase with the Family.  I should also be able to control whether or not my Windows Universal app can be shared with the Family.

**Comment by oldnewthing** [comment]
One option is to open a support case with our Developer Support team:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.

Another option is to open a Feedback Hub feature request.
