### ISSUE TITLE
PosPrinter Crashed 

### ISSUE THREAD

**Issue by lion77pnh** [Microsoft/Windows-universal-samples#1023]
Hi my problem crashed choose my PosPrinter80 
Model my printer xprinter px80c

**Comment by TerryWarwick** [comment]
@lion77pnh, we are going to need more details that this to help you.  Please reactivate with additional details and we can try to assist.

**Comment by lion77pnh** [comment]
I download sample code posprinter, compile run program my windows  10 x64 1803.
Find print, okey 2 print and 1 print chouse and crashed model my printer XP-Q260NL
http://poskeytech.com/html/80mm-Series/67.html

**Comment by TerryWarwick** [comment]
We have found deficiencies is some OPOS service objects and a fix is available.  Please make sure to go to Settings - Update & Security - Windows Update and make sure that you have applied all updates available. Once you have applied all available updates then try the sample again and let us know if you continue to experience this issue.

**Comment by lion77pnh** [comment]
Update last version 1803 
Don't new update 
[https://imgur.com/a/5rz9ss6](url)

**Comment by TerryWarwick** [comment]
KB4467682 is a cumulative update for release 1803 which contains fixes and security updates. According to the image this update has not been applied to the system yet, but it is almost ready.  Please apply the update once Windows Update completes the download and staging.  You will see an Install Now button or under the Start - Power menu you will see an option to Update and Restart.

**Comment by TerryWarwick** [comment]
Closing due to lack of response with assumption that installing KB4467682 solved the problem.  Please re-open this thread if that is not true.
