### ISSUE TITLE
This project is incompatible with the current edition of Visual Studio

### ISSUE THREAD

**Issue by Jaifroid** [Microsoft/Windows-universal-samples#1024]
This looks like the same error as #729 , but that was closed as unreproducible. I am attempting to open `ShareSource.sln` (directory `Samples\ShareSource\js`) in latest Visual Studio Community 2017 (15.8.9), and I get "This project is incompatible with the current edition of Visual Studio". This is a standard install Visual Studio Community, which is kept fully up to date.

**Comment by oldnewthing** [comment]
I still cannot reproduce the problem on my Visual Studio 15.8.9 system, though that is not running Community edition. I also was able to load the project on Visual Studio Community 15.9.3 and Visual Studio Community 15.9.4.

![image](https://user-images.githubusercontent.com/12550607/49961460-906fe780-fec7-11e8-833e-5de7ef728061.png)

**Comment by Jaifroid** [comment]
Well, it's still happening to me...
![image](https://user-images.githubusercontent.com/4304337/49967683-7f50c600-ff1b-11e8-89f2-14b5dc950a13.png)

**Comment by oldnewthing** [comment]
Did you remember to install JavaScript UWP support?

**Comment by Jaifroid** [comment]
Yes. I use this install of Visual Studio to develop and create store packages for a JavaScript UWP app (Kiwix JS Windows). However, I will try to install Visual Studio Community 15.9.4 (or whatever the latest version is) and report back if the issue persists.

**Comment by oldnewthing** [comment]
I will do the same. Let me know what install options you selected. Also, what version of Windows you are installing onto (so I will get the same version).
