### ISSUE TITLE
Issue with connecting Non Surface Device Via WifiDirect

### ISSUE THREAD

**Issue by sml0820** [Microsoft/Windows-universal-samples#103]
I am trying to connect two devices via WiFi direct using the Sample WiFi direct code. One device is a surface 3 running Windows 10 and the other is a Samsung tablet (also tried tv) running android (the Samsung devices can easily connect with each other, so I know it is not the hardware). For the two primary devices, they are able to see each other to connect. I am sending a connection request from the Samsung to the Windows 10 device. The below code gives the error:

Connect operation failed: AsyncBehaviorError: Status is 'error', but getResults did not return an error

My impression is that this line is run but then fails to continue Windows.Devices.WiFiDirect.WiFiDirectDevice.fromIdAsync(deviceId, connectionParams).then(

The relevant code is below: 
```
function OnConnectionRequested(e) {
               var connectionRequest = e.getConnectionRequest();

        WinJS.log && WinJS.log("Connecting to " + connectionRequest.deviceInformation.name + "...", "sample", "status");

        var connectionParams = new Windows.Devices.WiFiDirect.WiFiDirectConnectionParameters();
        connectionParams.groupOwnerIntent = parseInt(txtGOIntent.value.toString());

        var deviceId = connectionRequest.deviceInformation.id;
```
// device id comes back equaling: "WiFiDirect#26:4B:03:36:49:C6_PendingRequest"

``` 


       Windows.Devices.WiFiDirect.WiFiDirectDevice.fromIdAsync(deviceId).then(
    function (wfdDevice) {
        //this code never gets run
    },
    function (err) {
        WinJS.log && WinJS.log("Connect operation failed: " + err.toString(), "sample", "error");
        return;
    });
    }'
```

My best guess is that there is something wrong with the format of the id of the device and/or completing the call for fromIdAsync. However when I put the line regarding fromIdAsync and store it in a variable, it returns an object, meaning it is not null.  One additional point is that I have tried passing all values 0-7 to account for different device types https://msdn.microsoft.com/en-us/library/windows/apps/windows.devices.enumeration.deviceinformationkind such as Windows.Devices.WiFiDirect.WiFiDirectDevice.fromIdAsync(deviceId, connectionParams, 0)

I am at a loss on how to debug this anymore.

However, of the 100 or so times I have tried, it worked for like 3 in the row, but stopped working when I restarted the program.  Any help would be greatly appreciated.

**Comment by vmhatre** [comment]
Taking this offline with sml0820.

**Comment by lancecontreras** [comment]
I'm having the same issue trying to connect an android device to a UWP app. How did you resolve this?
