### ISSUE TITLE
AdvancedCasting - ProjectionManager to miracast device, automatically enable inputs

### ISSUE THREAD

**Issue by papakaliati** [Microsoft/Windows-universal-samples#1030]
Is there a way, after using ProjectionManager to connect to a Miracast device, to enable the "Allow input from a keyboard or mouse connected to this display" option? 
I am trying to use the Miracast device as the only monitor of the system.

**Comment by oldnewthing** [comment]
This isn't a question about a sample in this repo, but rather a question about the platform. You can open a support case with our Developer Support team:

1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
