### ISSUE TITLE
Barcode Scanner C# Project missing files

### ISSUE THREAD

**Issue by AlmaJensen** [Microsoft/Windows-universal-samples#1032]
When I load the barcode scanner C# sample project and try to build it I get an error that the App.Xaml file is missing.  Looking in file explorer I can't find it there either.

**Comment by oldnewthing** [comment]
Make sure you followed [the instructions under "Build the Sample"](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/BarcodeScanner).

> If you download the samples ZIP, be sure to unzip the entire archive, not just the folder with the sample you want to build.

My guess is that you didn't unzip the entire archive.
