### ISSUE TITLE
C# Projection Sample missing files

### ISSUE THREAD

**Issue by MathewLC** [Microsoft/Windows-universal-samples#1037]
I see that with the link https://code.msdn.microsoft.com/Projection-sample-526b3c1d/ i can see the file MainPage.xaml and App.xaml but the more update files that is in here is missing. Plese can you update the sample?

**Comment by oldnewthing** [comment]
The files are in the SharedContent directory.

* [MainPage.xaml](https://github.com/Microsoft/Windows-universal-samples/blob/master/SharedContent/cs/MainPage.xaml)
* [App.xaml](https://github.com/Microsoft/Windows-universal-samples/blob/master/SharedContent/xaml/App.xaml)

As noted [in the README](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/Projection/README.md):

> **Note:** This sample is part of a large collection of UWP feature samples. If you are unfamiliar with Git and GitHub, you can download the entire collection as a [ZIP file](https://github.com/Microsoft/Windows-universal-samples/archive/master.zip), but **be sure to unzip everything to access shared dependencies.**
