### ISSUE TITLE
Exception thrown in DWriteLineSpacingModes

### ISSUE THREAD

**Issue by PeterCon** [Microsoft/Windows-universal-samples#1041]
When the DWriteLineSpacingModes sample is run, an invalid argument exception is thrown at line 259 of TextLayoutImageSource.cpp:

    DX::ThrowIfFailed(
        sisNative->BeginDraw(updateRectNative, &surface, &offset)
        );

Exception thrown at 0x73BE1812 in DWriteLineSpacingModes.exe: Microsoft C++ exception: Platform::InvalidArgumentException ^ at memory location 0x03CBBFF4. HRESULT:0x80070057 The parameter is incorrect.
WinRT information: The parameter is incorrect.

The calling context begins in the MainPage::OnNavigatedTo() method, when the initial scenario is selected.

I know that this sample used to work. I'm running on 1803 (build 17134.472 -- I had to retarget the project to 17134 for it to deploy).

**Comment by oldnewthing** [comment]
I've asked the feature team to investigate. The bug occurs because the sample tries to draw a 0x0 rectangle:

    // Create a new TextLayoutImageSource based on the text layout, have 
    // it draw, and then use it as the source for the XAML image element.
    m_textLayoutImageSource = ref new TextLayoutImageSource(
        m_textLayout,
        static_cast<uint32>(floor(TextLayoutImage->ActualWidth)),
        static_cast<uint32>(floor(TextLayoutImage->ActualHeight))
        );

It's using the `TextLayoutImage->ActualWidth` and `ActualHeight` prior to a layout pass, so the width and height haven't been calculated yet.

**Comment by oldnewthing** [comment]
Sample should be using `Height` and `Width` rather than `ActualHeight` and `ActualWidth`. Fix coming in next refresh.
