### ISSUE TITLE
[Question] Dropdown Shadow

### ISSUE THREAD

**Issue by HppZ** [Microsoft/Windows-universal-samples#1042]
How to create dropdown shadow effect for Text using Direct2d?
here is what I found: [https://docs.microsoft.com/en-us/windows/desktop/direct2d/effects-overview#building-effect-graphs](url)

there seems to be no other documentation on docs.com, so I decided to create a issue here. hope you can help me. THANKS!

**Comment by oldnewthing** [comment]
Sorry, this is for reporting issues with the samples included in the repo, not for general developer support. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
