### ISSUE TITLE
[Question] DirectComposition & UWP

### ISSUE THREAD

**Issue by HppZ** [Microsoft/Windows-universal-samples#1043]
Can I use DirectComposition API in Windows Runtime Component written in C++ for UWP project?
or
How to use Direct2d API to do animations like moving a text alone X axis? I use SetTransform and DrawTextLayout to update the text position 60 FPS, but looks not very good. DirectComposition seems to be a better choice for animating, but it does not support UWP, right?

**Comment by oldnewthing** [comment]
Sorry, this is for reporting issues with the samples included in the repo, not for general developer support. (Noting that there is a Composition sample in this repo that can get you started with DirectComposition if that's what you want.) You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
