### ISSUE TITLE
windows 桌面应用调用windows10 calendar 往系统日历里面写入新的事件提醒

### ISSUE THREAD

**Issue by cg200776** [Microsoft/Windows-universal-samples#1044]
如题 ，请问我们需要使用哪个API
![image](https://user-images.githubusercontent.com/26522289/50837105-c9e82580-1395-11e9-9d22-765e9fc45f1b.png)

**Comment by oldnewthing** [comment]
I think you're looking for the [Appointments](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/Appointments) sample.
