### ISSUE TITLE
will the Bluetooth (ble) sample have a c++ version? 

### ISSUE THREAD

**Issue by vivopcz** [Microsoft/Windows-universal-samples#1046]
c# can't be using in my project

**Comment by oldnewthing** [comment]
You can translate C# to C++, it's not that hard, especially now that we have `co_await`.

**Comment by oldnewthing** [comment]
Okay, [I ported it for you](https://github.com/Microsoft/Windows-universal-samples/releases/tag/v8.0.0). Like I said, not hard. A literal translation of the C# sample.
