### ISSUE TITLE
Could you please add a C++ sample for MultipleViews?

### ISSUE THREAD

**Issue by dingsheng999** [Microsoft/Windows-universal-samples#1048]
I tried myself following the document below by converting the C# codes to C++/CX but not successful. It will be really nice if Microsoft can provide a C++ sample. It's not necessarily official and comprehensive. I will only need a demo that can work. I searched all over the internet but cannot find a C++ version for MultipleViews. Thanks a lot.
https://docs.microsoft.com/en-us/windows/uwp/design/layout/show-multiple-views

**Comment by dingsheng999** [comment]
I found a Windows 8.1 sample as below in C++
https://code.msdn.microsoft.com/windowsapps/Multiple-Views-Sample-2582fcf3
Is there a reason why only C# is included for the multiple-view sample?

**Comment by Gavin-Williams** [comment]
We can submit missing samples where C# or C++ has no coverage can't we?

**Comment by dingsheng999** [comment]
Among a few apps I know in Microsoft Store, 2 apps are developed using C++, 123 Photo Viewer and ACG player.
DirectX games and Apps are typically developed with C++.
The popular game engine Unreal uses C++. Cryengine also uses C++.

**Comment by dingsheng999** [comment]
It's been more than 3 years since the release of Windows 10. Why does not Microsoft add the missing C++ samples which were used to be in Windows 8.1 samples? Most of the old code should just work in UWP. It is not a lot of work but will certainly help those C++ developers. What priority does Microsoft give for C++?

**Comment by oldnewthing** [comment]
I [ported the sample to C++](https://github.com/Microsoft/Windows-universal-samples/releases/tag/v8.0.0). It's not hard, just tedious. A literal translation of the C# sample.

**Comment by dingsheng999** [comment]
Thanks a lot for your work! Hope Microsoft has more engineers like you to contribute more to the community!

**Comment by oldnewthing** [comment]
It really was just a literal translation. Was the problem that you didn't understand enough C# to translate it yourself?

**Comment by dingsheng999** [comment]
Honestly I use C++ much more often than C#. As you know, usually UWP developers are much more familiar with C#. But for image/graphics/video/algorithm developers this may not be the case. Developers from other platforms may not be familiar with C# either. But Microsoft provides most documentations and samples using C#.

I develop UWP apps using C++/CX rather than C++/WinRT. Usually I just translate codes from C# documentations and samples to C++/CX. But for the multiple view sample, I could not make it work after quite a few hours trying to translate. So I asked the question in this thread. To me, the Windows 8.1 C++/CX multiple view sample and the C# multiple view sample differ really a lot. I felt really frustrated until I finally found a C++/CX sample in Windows 8.1. I could not find a C++ multiple view sample for UWP so I thought there was none in Windows 8.1 either. Fortunately, the code in Windows 8.1 also works in UWP. Some C++/WinRT features are not supported in earlier versions of Windows and I have to maintain the compatibility so I stick to C++/CX. It took me a while to learn C++/CX and for now I have no reason to migrate to C++/WinRT.

While it is nice that UWP supports development using a few different languages, it's a pity not enough documents and samples are provided. Some old samples were just discarded for unknown reasons. I have been following Microsoft store since the year 2012 and I feel glad to see many improvements since then, but the progress is much slower than I expected. A few things are in my wish list.
1) More resources working on sample codes and documentations. As it is difficult to develop a great app, it is also difficult to create great samples and documentations. It will be really great if multiple languages are supported. Everybody knows that developers are important for the success of a digital store platform, but it appears not many resources are working in the development community. At least multiple language documentations and samples should be supported.
2) For some application showcase demos, I hope the support is continuous. Some demos are really nice such as the Hilo photo sample, but suddenly it appears no one in Microsoft remembers it anymore.
3) Smooth Microsoft Store download experiences. Quite often users complains to me they cannot download successfully. 

Thanks again for your help. I wish Microsoft could take actions just as quick as you are. I was surprised to see your new samples so soon.

**Comment by oldnewthing** [comment]
Thanks very much for your description of the problem. I can bring this to my management to try to get better support for samples.
