### ISSUE TITLE
How can I print the stroke of the InkCanvas

### ISSUE THREAD

**Issue by Javier118** [Microsoft/Windows-universal-samples#1053]
if what I do is make a stroke in the InkCanvas which would be the best option for the stroke print, in this case is not an image

**Comment by oldnewthing** [comment]
This appears to be a question about the platform, not a question about the sample. You can open a support case with our Developer Support team:

1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.

**Comment by James-the-Tech** [comment]
The printing option is available via Visual Studio coding.
