### ISSUE TITLE
BackgroundTransfer sample never unregisters the background tasks

### ISSUE THREAD

**Issue by nbevans** [Microsoft/Windows-universal-samples#1054]
https://github.com/Microsoft/Windows-universal-samples/blob/master/Samples/BackgroundTransfer/cs/Tasks/CompletionGroupTask.cs

The sample provides no guidance on how to handle unregistering the background tasks for the completion groups.

It seems to be also undocumented by the MSDN docs for background transfer completion groups.

As far as I can see the only plausible way to do this, to not leak background task registrations for each completion group, is to have the background task unregister itself when it receives the completion group trigger. But that doesn't cover potential leaks if the background task were to never be triggered - i.e. a stuck download.

**Comment by Diego-Perez-Botero** [comment]
@nbevans - Thanks for bringing this up! The IBackgroundTrigger exposed via [BackgroundTransferCompletionGroup.Trigger](https://docs.microsoft.com/en-us/uwp/api/windows.networking.backgroundtransfer.backgroundtransfercompletiongroup.trigger#Windows_Networking_BackgroundTransfer_BackgroundTransferCompletionGroup_Trigger
) is configured such that "[OneShot ](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.background.systemtrigger.oneshot) == **true**". Therefore, the background task is automatically unregistered by the Broker Infrastructure as soon as the task gets triggered.

You can validate this behavior by looking at the `Get-AppBackgroundTask -PackageFamilyName Microsoft.SDKSamples.BackgroundTransfer.CS_8wekyb3d8bbwe` output when running Scenario 4 of the BackgroundTransfer SDK sample. Before the completion group task is triggered, Tasks.CompletionGroupTask is listed as one of the entry points. Post-trigger, the Tasks.CompletionGroupTask entry point is nowhere to be found.

Lastly, app developers shouldn't worry about a "stuck download" scenario. The BackgroundTransfer component has well-defined retry/timeout logic that shouldn't allow for that scenario to arise.

**Comment by Diego-Perez-Botero** [comment]
We will update the MSDN docs and the SDK sample to contain the information above.

**Comment by nbevans** [comment]
Thanks that is useful - and nice to know the docs will be improved.

However the reason for this question was because we are indeed seeing "stuck downloads" as a result of the BackgroundTransferCompletionGroup sometimes not being triggered for completed downloads. For example if we start two DownloadOperation's, with different completion groups, and cancel the first DownloadOperation - then the second DownloadOperation never receives its BackgroundTransferCompletionGroup trigger. We can reproduce this consistently. We have ruled out as much as we can, with still a few more tricks to try, but are fast running out of ideas and starting to think it is a bug in UWP (famous last words!)

If it matters, we are using a shared TransferGroup set to Parallel.

Thanks

**Comment by Diego-Perez-Botero** [comment]
As far as the "stuck downloads" issue goes, do you have a repro app (e.g., modified SDK sample) and/or detailed repro steps for us to investigate it internally and get back to you?

Thanks!

**Comment by viperri** [comment]
Nathan, I haven't been able to reproduce your issue. My attempt is on this [branch](https://github.com/viperri/Windows-universal-samples/tree/bt-download-cancel-repro), where I modified scenario 4 of the BackgroundTransfer sample app so that it just creates two download operations with different completion groups and then immediately cancels the first.

With this modified scenario, I saw two toast notifications, which means the second DownloadOperation had received its trigger.

Could you please take a look at my attempt and see whether it accurately reflects your scenario?

**Comment by oldnewthing** [comment]
Please reopen if you have something to share.
