### ISSUE TITLE
App keeps crashing during certification when using Microsoft Advertising SDK for XAML

### ISSUE THREAD

**Issue by ac-lap** [Microsoft/Windows-universal-samples#1055]
In my already published app, I tried adding ADs using “Microsoft Advertising SDK for XAML” (tried adding reference via both NuGet and msi). On my dev machine both debug and release builds work fine, even .appxbundle created as part of packaging works as expected, but the app always crashes at launch for the reviewer when submitted for review (.appxupload file).

In the past I had similar issue with Microsoft Store Services SDK, where the Feedback hub launched perfectly fine in both debug and release builds, but once published to store, the API would fail with "Method 'StoreServicesFeedbackLauncher.IsSupported()' was not included in compilation, but was referenced in HomePage.<feedback_tapped>d__23.MoveNext(). There may have been a missing assembly.". The issue is still not fixed for me.

I suspect both the problems have same underlying cause, as both are framework packages, debug/release build works fine, but fails in the store published app.

Note: The app is a Desktop Bridge app. There is a UWP app which communicates with a win32 exe. The call to launch Feedback hub or Ads are in the UWP app.

Following are the max and min supported versions of my project-

```
<TargetPlatformVersion Condition=" '$(TargetPlatformVersion)' == '' ">10.0.17134.0</TargetPlatformVersion>
<TargetPlatformMinVersion>10.0.14393.0</TargetPlatformMinVersion>
```

I also tried adding following entries in the rd.xml file hoping to fix any reflection related issue, but no luck
   
```
<Type Name="Microsoft.Advertising" Dynamic="Required All"/>   
<Type Name="Microsoft.Advertising.WinRT.UI" Dynamic="Required All"/>
   
<Namespace Name="Microsoft.Advertising" Serialize="All"/>   
<Namespace Name="Microsoft.Advertising.WinRT.UI" Serialize="All"/>
```
It has been over a week now and I am not able to fix the issue. Any help would be really appreciated.

**Comment by oldnewthing** [comment]
This is not an issue with a sample in this repo. You can open a support case with our Developer Support team:

1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
