### ISSUE TITLE
MIDI sample app hangs on exit

### ISSUE THREAD

**Issue by IgorX2** [Microsoft/Windows-universal-samples#1056]
The MIDI sample app hangs on exit. The app cannot be redeployed from Visual Studio. Further, the process cannot be terminated from command line or from the Task Manager (where it is shown to have only one thread and two handles).

This occurs for simpler examples that use MIDI, as suggested in the related post: [MIDI freezes apps on exit](https://github.com/MicrosoftDocs/windows-uwp/issues/1424).

Steps to reproduce:
1) Compile the MIDI example
2) Run the example and try anything
3) Close the app window or attempt to break through the Visual Studio debugger
4) Observe the app hang indefinitely

**Comment by oldnewthing** [comment]
I cannot reproduce this problem.

* I ran the MIDI sample from VS, compiling for x86.
* From Scenario 1, I clicked "Microsoft GS Wavetable Synth" in the OUTPUT section.
* The sample displayed identification information.
* From there, I went to scenario 3, selected the "Microsoft GS Wavetable Synth" output device.
* I set the Message Type to "Note On", Channel to 4, Note to 64, and Velocity to 64.
* I clicked Send.
* A note was played.
* From Visual Studio, I clicked the Pause button. The app paused. I clicked the Continue button to resume.
* In the app, I clicked the X button to close the window.
* The app terminated normally. "The program '[14774] MIDI.exe' has exited with code 1 (0x1).
* Visual Studio exits debugging mode.
* Task Manager confirms that the app is no longer running.

Visual Studio Community 2017 version 15.9.4, running on Windows 10 Version 1809.
