### ISSUE TITLE
EnterpriseDataProtection sample does not compile with SDK 17763

### ISSUE THREAD

**Issue by tschan** [Microsoft/Windows-universal-samples#1057]
Hello,

trying to build the sample EnterpriseDataProtection without any changes after checkout with target and min version set to "Windows 10, version 1809 (10.0; Build 17763)" and Windows 10 SDK 10.0.17763.0 installed on the machine (Windows 10, Version 1809) results in the following build errors / warnings:

> Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not find SDK "WindowsMobile, Version=10.0.17763.0".	Tasks			
Error		Could not find SDK "WindowsMobile, Version=10.0.17763.0".	EnterpriseDataProtection			
Warning		The referenced component 'Microsoft Mobile Extension SDK for Universal App Platform' could not be found.	Tasks			
Warning		The referenced component 'Windows Mobile Extensions for the UWP' could not be found.	EnterpriseDataProtection			
Warning		Could not find SDK "WindowsMobile, Version=10.0.17763.0".	EnterpriseDataProtection			
Warning	IDE0006	Error encountered while loading the project. Some project features, such as full solution analysis for the failed project and projects that depend on it, have been disabled.	EnterpriseDataProtection		1	Active
Warning		Cannot resolve Assembly or Windows Metadata file 'D:\Visual Studio Repos\Windows-universal-samples\Samples\EnterpriseDataProtection\cs\Tasks\bin\x64\Debug\Tasks.winmd'	EnterpriseDataProtection	D:\Visual Studio Repos\Windows-universal-samples\Samples\EnterpriseDataProtection\cs\EnterpriseDataProtection.csproj		

Are there any additional setup steps necessary not mentioned in the readme?

**Comment by oldnewthing** [comment]
Works for me. Was able to build it on two different machines. Have you tried reinstalling the 17763 SDK?

**Comment by oldnewthing** [comment]
The Mobile and Desktop extensions are supposed to be installed automatically when you install the SDK. Try installing the SDK standalone rather than from Visual Studio installer.
