### ISSUE TITLE
MIDI sample app hangs on exit when MIDI keyboard is connected

### ISSUE THREAD

**Issue by IgorX2** [Microsoft/Windows-universal-samples#1058]
The MIDI sample app hangs on exit. The app cannot be redeployed from Visual Studio. Further, the process cannot be terminated from command line or from the Task Manager (where it is shown to have only one thread and two handles).
This occurs for simpler examples that use MIDI, as suggested in the related post: [MIDI freezes apps on exit](https://github.com/MicrosoftDocs/windows-uwp/issues/1424).

Steps to reproduce:

1. Compile the MIDI example
2. Connect a MIDI input device (keyboard)
3. Run the example and try reading messages from the keyboard
4. Close the app window or attempt to break through the Visual Studio debugger
5. Observe the app hang indefinitely

This is an expansion of the previous issue, which was closed: [MIDI sample app hangs on exit](https://github.com/Microsoft/Windows-universal-samples/issues/1056).

**Comment by oldnewthing** [comment]
This appears to be a platform issue, not an issue with the sample. You can open a support case with our Developer Support team:

1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
