### ISSUE TITLE
Issue for NavigationMenu sample

### ISSUE THREAD

**Issue by KiritoStudio** [Microsoft/Windows-universal-samples#106]
Issue reproduced like the following below:

1. Add a Tapped event to the LandingPage with the code "this.Frame.Navigate(typeof(BasicPage));   "
2. Add a Tapped event to the BasicPage with the code "this.Frame.GoBack();"
3. Keep the App open with SplitView = Overlay
4. Tapped to BasicPage and back, and System.NullReferenceException will throw:
   at NavigationMenuSample.Controls.NavMenuListView.SetSelectedItem(ListViewItem item)
   at NavigationMenuSample.AppShell.OnNavigatingToPage(Object sender, NavigatingCancelEventArgs e)

And I found the code
 "var container = (ListViewItem)NavMenuList.ContainerFromItem(item);" 
in AppShell.OnNavigatingToPage and container value is null, and I don't understand why.

**Comment by samschiferl** [comment]
Thank you for your feedback on this issue regarding a NullReferenceException when adding Tapped events that navigate between pages. We have looked into this issue and were unable to reproduce the problem you found. Please provide us with some more information regarding the issue so we can investigate further: 
- Does this occur only occur if the SplitView is in Overlay? 
- Where did you place the Tapped events in the LandingPage and the BasicPage?
- What are the specific steps once you have opened the app to get this error?

**Comment by oldnewthing** [comment]
Closed due to lack of response.
