### ISSUE TITLE
Projection sample - secondaryview.html references WinJS.js

### ISSUE THREAD

**Issue by samjross** [microsoft/Windows-universal-samples#1060]
In the projection sample, [this file](https://github.com/Microsoft/Windows-universal-samples/blob/master/Samples/Projection/js/html/secondaryView.html) includes a link to /Microsoft.WinJS.4.0/js/WinJS.js. There is no such file in the project. I believe /Microsoft.WinJS.4.0/js/base.js is the file meant to be linked, which is in the project.

**Comment by oldnewthing** [comment]
Fixed in next update.
