### ISSUE TITLE
UWP calendardatepicker showing neighbor months  

### ISSUE THREAD

**Issue by shrutidutt** [Microsoft/Windows-universal-samples#1061]
Please see the question as posted on stackoverflow - 
(https://stackoverflow.com/questions/54627507/uwp-calendardatepicker-showing-march-when-mindate-is-set-to-11th-feb)

**Comment by oldnewthing** [comment]
This appears to a problem with the control itself, not with any sample in this repo. (And there is no sample in this repo that uses a CalendarDatePicker as far as I recall.)
