### ISSUE TITLE
Casting video or image content to a device always mirrors the desktop

### ISSUE THREAD

**Issue by CobraCalle** [Microsoft/Windows-universal-samples#1065]
Sorry I had to reopen e new issue for that, because no one answers to my comments after the previous issue was closed. I think we have a serious issue here and that the answer to the previous issue is simply not true.

Casting ANY type of content to ANY type of device (Miracast AND DLNA) ALWAYS results in Windows starting to mirror the desktop. This cannot be the expected result.

Even the MyTube!-App cannot cast videos to another device and this has definitely been working.

I've tested this on three different machines with the different type of remote devices (MS Wireless Display Adapter, Connect App, and Samsung TV (DLNA))… with always the same result: Windows starts to mirror the desktop.

Pleas have a look at this (you can use the samples from this repository)… I think the whole media casting functionality of Windows is broken on the newest builds.

Thanks

**Comment by oldnewthing** [comment]
This is really a platform question, not a samples question. (Unless you're suggesting that there's a bug in the sample?)

You can open a support case with the Developer Support team:

1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.

**Comment by oldnewthing** [comment]
(In the meantime, as a courtesy to you, I'll go back and ask the feature team.)
