### ISSUE TITLE
Example of Cash Drawer (Purchasable)

### ISSUE THREAD

**Issue by BaileyMillerSSI** [Microsoft/Windows-universal-samples#1069]
I was interested in creating a sample POS application using Raspberry Pi and the Cash Drawer / PosPrinter sample. I was wondering if a link could be provided of an example Cash Drawer that was used during development.

**Comment by oldnewthing** [comment]
I don't understand the question. The CashDrawer sample is [here](https://github.com/Microsoft/Windows-universal-samples/blob/master/Samples/CashDrawer/) but you probably knew that.

**Comment by BaileyMillerSSI** [comment]
I am looking to purchase a physical cash drawer to use with this sample. What do I need?

**Comment by oldnewthing** [comment]
[This page](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/pos-device-support) documents the devices which are supported.
