### ISSUE TITLE
DPIScaling project missing XAML

### ISSUE THREAD

**Issue by JakeFe** [Microsoft/Windows-universal-samples#107]
The DPIScaling project is missing both the Scenario1.xaml and Scenario2.xaml files

**Comment by oldnewthing** [comment]
Yup. Sorry. Contents will appear at our next refresh. (If you're in a hurry, you can grab them from the old repo.)
* [Scenario1.xaml](https://github.com/oldnewthing/Windows-universal-samples/blob/master/scaling/cs/scenario1.xaml)
* [Scenario2.xaml](https://github.com/oldnewthing/Windows-universal-samples/blob/master/scaling/cs/scenario2.xaml)
