### ISSUE TITLE
Alljoyn doesnt works in Windows version 1809

### ISSUE THREAD

**Issue by harish-dsrc** [Microsoft/Windows-universal-samples#1072]

**Comment by oldnewthing** [comment]
You seem to be reporting an issue with the platform, not with the sample. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:

1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
