### ISSUE TITLE
How to read sensor data from the Hololens for head tracking?

### ISSUE THREAD

**Issue by alexwmy** [Microsoft/Windows-universal-samples#1074]
I am trying to record the head movement when audience is watching the playback of 360 degree video. Could you share some information on how to fetch sensor data in your 360videoplayback samples? Thank you very much

**Comment by oldnewthing** [comment]
This appears to be a question about the platform, not the sample. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:

1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
