### ISSUE TITLE
How to resolve nuget issues of Advertising JS project

### ISSUE THREAD

**Issue by serenavisualon** [microsoft/Windows-universal-samples#1076]
I download the latest whole sample package, open the js project in "Windows-universal-samples\Samples\Advertising\js", rebuild it then got these errors:
Severity	Code	Description	Project	File	Line	Suppression State
Error		NuGet Package restore failed for project Advertising: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.. Please see Error List window for detailed warnings and errors.				
Error		This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is packages\Microsoft.Advertising.JS.10.1705.16001\build\Microsoft.Advertising.JS.targets.	Advertising	F:\Windows-universal-samples\Samples\Advertising\js\Advertising.jsproj	137	

I add "https://api.nuget.org/v3/index.json" into the NuGet Package Sources before.

I do not modify anything in the sample project.

Thanks!

**Comment by oldnewthing** [comment]
As the error message says, the path is too long. Download into a directory with a shorter name.
