### ISSUE TITLE
GroupStyle.Panel does not work

### ISSUE THREAD

**Issue by HppZ** [Microsoft/Windows-universal-samples#1077]

**Comment by oldnewthing** [comment]
Can you be more specific? Which sample is exhibiting the problem?

**Comment by HppZ** [comment]
I just figured it out：
GroupStyle.Panel does not work when set ItemsWrapGrid to GridView.ItemsPanel.

why is that? 👀

**Comment by oldnewthing** [comment]
Which sample are you referring to? I can't find any sample that uses GroupStyle.Panel.

**Comment by HppZ** [comment]
No, there is no  sample that uses GroupStyle.Panel in this repo. It is just a XAML bug I found. I was wondering if you could help summit this bug to XAML Team.

**Comment by oldnewthing** [comment]
If you want help with XAML, you can open a support case with the Developer Support team on http://aka.ms/storesupport. If you want to report a bug, you can use Feedback Hub (use the Developer Platform category).

I'll take this one for you, but in the future, please use the existing feedback channels.

**Comment by HppZ** [comment]
All right, THANKS!

**Comment by oldnewthing** [comment]
The team acknowledges that this is a known limitation. In the future, you can submit XAML issues on https://aka.ms/winui

**Comment by HppZ** [comment]
Great, thanks for helping me!
finally have a place to submit XAML issues.
