### ISSUE TITLE
Support for Bing Map Offline Caching and Rendering [Satellite, Street]

### ISSUE THREAD

**Issue by jkriba** [Microsoft/Windows-universal-samples#1079]
Hi,
  We are currently exploring the technical options for integrating a Real Time Map component for our Enterprise Application which is built on UWP. 

  We do have use cases around typical Map Control and various other user operations such as Zoom, Object Overlaying, Triggering function through objects,  Navigate and so on. But we really need the maps to be working offline when there was no internet connection available temporarily.

  This is a critical Field scenario where we can't have complete control over the internet connection. 

Does Bing Map API service support offline caching of Map data at least to some extent and is there any other possible mechanisms available for the same ? We could not able to find appropriate information on the official documentations. Please let us know, thanks

Regards
JK

**Comment by oldnewthing** [comment]
This isn't a question about a sample in this repo. You can open a support case with our Developer Support team:

1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
