### ISSUE TITLE
not able to run SimpleImaging on Phone

### ISSUE THREAD

**Issue by rcroeder** [Microsoft/Windows-universal-samples#108]
This is desiged to run on the phone but i cannot get it to run since the current version of phones is 10166 and the samples need 10240. Any ideas to make the samples work?

Severity	Code	Description	Project	File	Line
Error		Error : DEP3321 : To deploy this application, your deployment target should be running Windows Universal Runtime version 10.0.10240.0 or higher. You currently are running version 10.0.10166.0. Please update your OS, or change your deployment target to a device with the appropriate version.	SimpleImaging

**Comment by DavidGoll** [comment]
You can hand-edit the package.appxmanifest file to have the version running on your phone (10166 is safe).

**Comment by AdamBraden** [comment]
Yes, the samples were all built to target the RTM version of the SDK.  You can run against emulator until the next Phone flight.

**Comment by rcroeder** [comment]
David,

 

Had to modify the cdproj to set min version to 10166, but that appears to allow me back in. Thank you
