### ISSUE TITLE
MediaImport doesn't work for many iOS and Android devices

### ISSUE THREAD

**Issue by keungk** [microsoft/Windows-universal-samples#1080]
Depending on which iOS or Android phone I connect, especially with large libraries, the MediaImport will return 0 items, or take a very time to return a fraction of photos on the device. Is this down to newer versions of iOS and Android?

**Comment by oldnewthing** [comment]
This appears to be a question about the feature itself, not a question about the sample. You can follow the instructions on [Windows developer support](https://developer.microsoft.com/en-us/windows/support/) for support options. (Click "Forums and community".)
