### ISSUE TITLE
WiFiDirect sample failed in Win10 1809

### ISSUE THREAD

**Issue by michaelguo** [microsoft/Windows-universal-samples#1081]
I use the sample connect between two Win10 1809 notebook, after pairing the PIN, the advertiser report that connection request from DESKTOP-9A037Q2 was declined, and the connector report an exception: An attempt was made to access a socket in a way forbidden by its access permissions.
But form the explorer's network view the two PCs could discover each other and also could access both share folders correctly.

**Comment by jseba** [comment]
I believe this is a misconfiguration of the capabilities in the application manifest. If you change the line

`<Capability Name="internetClient" />`

to

`<Capability Name="internetClientServer" />`

in the Package.appxmanifest for the sample you are using (cpp, cs, js) and rebuild, then it should work.

**Comment by michaelguo** [comment]
@jseba, you are right, it worked, thanks.
