### ISSUE TITLE
BarcodeScannerInfo

### ISSUE THREAD

**Issue by lailaberiou** [microsoft/Windows-universal-samples#1084]
Hello, i would like to know what's in this file, so i can use BarcodeScannerInfo, thanks 
```
<Page.Resources>
       <CollectionViewSource x:Name="ScannerListSource"/>
    </Page.Resources>
```

**Comment by oldnewthing** [comment]
Not sure what you're asking. The ScannerListSource's data source is set [here](https://github.com/microsoft/Windows-universal-samples/blob/7c7832e1f144e4fc836603fd70e1352024a5fe1a/Samples/BarcodeScanner/cs/Scenario5_DisplayingBarcodePreview.xaml.cs#L57):

```
 ScannerListSource.Source = barcodeScanners;
```
