### ISSUE TITLE
Projection  Unable to deploy

### ISSUE THREAD

**Issue by h0730303779** [Microsoft/Windows-universal-samples#1086]
DEP6957: Failed to connect to device "127.0.0.1" using "Universal Authentication". Please verify that the correct remote authentication mode is specified in the project debug settings

OS :          10.0.17134  Build 17134

What is the reason?

**Comment by oldnewthing** [comment]
This is an issue with Visual Studio, not with the samples.  You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:

1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.

**Comment by AmadeusW** [comment]
Visual Studio has a quirk to set the ARM configuration by default. 
Set your configuration to match your device, e.g. x64
![image](https://user-images.githubusercontent.com/1673956/70207377-76827280-16df-11ea-8403-6f4814e8f4e7.png)

**Comment by h0730303779** [comment]
> Visual Studio has a quirk to set the ARM configuration by default.
> Set your configuration to match your device, e.g. x64
> ![image](https://user-images.githubusercontent.com/1673956/70207377-76827280-16df-11ea-8403-6f4814e8f4e7.png)

Later I did the same. Thank you for deepening my memory
