### ISSUE TITLE
Obtain After unattended

### ISSUE THREAD

**Issue by h0730303779** [Microsoft/Windows-universal-samples#1088]
Hello, please ask

I need to detect 10 minutes on the UWP APP. After unattended, close some view.

I didn't find related example.. Can you help me?

.I am using the Window API now. 

```
[DllImport("user32.dll")]
private static extern bool GetLastInputInfo(ref LASTINPUTINFO plii);

LASTINPUTINFO vLastInputInfo = new LASTINPUTINFO();
vLastInputInfo.cbSize = Marshal.SizeOf(vLastInputInfo);
              
if (!GetLastInputInfo(ref vLastInputInfo))
   return 0;
else
   return Environment.TickCount - (long)vLastInputInfo.dwTime;
```

**Comment by oldnewthing** [comment]
This isn't a question about a sample in this repo. You can open a support case with our Developer Support team:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.

It's not clear what you're asking for. If you want to wait 10 minutes, you can use a timer. It's not clear what `GetLastInputInfo` has to do with waiting 10 minutes.
