### ISSUE TITLE
Windows.Devices.PointofService

### ISSUE THREAD

**Issue by DirkRoelandt** [Microsoft/Windows-universal-samples#109]
App builds & runs but I'm struggling to understand the workings i.e. the interaction with "driver".

It always crashes during the find and claim at statement : 

DeviceInformationCollection deviceCollection = await DeviceInformation.FindAllAsync(PosPrinter.GetDeviceSelector());

I’m wondering does one still needs OPOS drivers, etc… for this new namespace ?
Why is this not mentioned in item ?
How should it be properly installed other software/driver to avoid above issue ?

KR.

**Comment by TerryWarwick** [comment]
Hello Dirk,

I am sorry to hear that the sample is not working for you.  Our implementation for UWP communicates with the printer via ESC/POS and does not require any additional drivers.  

We have recently refreshed our documentation on MSDN to provide more helpful information about the PointOfService namespace.

https://msdn.microsoft.com/en-us/library/windows/apps/mt426652.aspx

POSPrinting #117 appears to have more information about your environment, so we'll focus on assisting you there.

Terry Warwick
Microsoft
