### ISSUE TITLE
WASAPI audio loopback capabilities

### ISSUE THREAD

**Issue by mancoast** [Microsoft/Windows-universal-samples#1090]
Greetings!

I am working on a music visualizer using UWP.  When building a win32 app, I am able to successfully input WASAPI audio loopback as referenced from this document: https://docs.microsoft.com/en-us/windows/desktop/coreaudio/loopback-recording

Now with UWP (for Xbox), I have modified the WindowsAudioSession project to include the GetDefaultAudioRenderId for ActivateAudioInterfaceAsync and the AUDCLNT_STREAMFLAGS_LOOPBACK flag for m_AudioClient->Initialize.  The debugger shows E_ACCESSDENIED General access denied error.  Any thoughts on how to proceed here for Xbox platform?

Thanks,
mancoast

![image](https://user-images.githubusercontent.com/7040493/56508130-68d20100-64f1-11e9-8788-a6c17a1b70a0.png)
![image](https://user-images.githubusercontent.com/7040493/56508139-712a3c00-64f1-11e9-985b-53e5c3fd8416.png)

**Comment by oldnewthing** [comment]
This is not an issue with the sample itself, but with your modifications to the sample. You can open a support case with our Developer Support team who can further help with the problem you are experiencing.:

1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.

**Comment by mancoast** [comment]
This is for open-source project, so unfortunately I do not have a subscription for Windows developer support. Do you know any where else I can communicate and collaborate with others about this topic?

**Comment by oldnewthing** [comment]
Maybe the developer forums? https://social.msdn.microsoft.com/Forums/
