### ISSUE TITLE
App.g.i.cs missing

### ISSUE THREAD

**Issue by nikolap3** [Microsoft/Windows-universal-samples#1091]
Yesterday i downloaded the samples and tried starting the WiFiDirect sample, but it needed a windows update which was available in VS 2019, then after freshly installing VS 2019 i opened the solution,and noticed the output from "IntelliSense" was saying "[Failure] Could not find file '(directory of solution)\obj\ARM\Debug\App.g.i.cs'.'"
Trying to ignore the problem i clicked build, and after a few hours and a few tries more, i decided its time to get some help.
The sample files and VS itself is all freshly installed, so im assuming theres no update. Im running VS on a Win10 machine.

**Comment by oldnewthing** [comment]
That file is created as part of the build. So if the build gets stuck, that's the thing to investigate.

**Comment by nikolap3** [comment]
Not quite sure what was the issue, but after telling VS to redownload all nugget packages, i checking the files that were created after the first build noticed there was a file named "App.g.cs", so i renamed it to App.g.i.cs and restarted the build. This time it succeed.
