### ISSUE TITLE
UWP Com Server

### ISSUE THREAD

**Issue by Pinox** [microsoft/Windows-universal-samples#1092]
please enhance the existing sample apps with an example of a UWP Com server.

Searching the net I could not find anything specific to UWP, most recommendations are to use a desktop bridge that is not viable when you want to publish a pure UWP app to the store.

I would like to link the Excel RTD function directly to the Com component in a UWP app.

Is this even possible in current UWP or is this something that is going to work better when .net core 3.0 supports UWP ?

**Comment by AdamBraden** [comment]
When you say you want a pure UWP, what are you looking for? UWP can create Runtime Components that use a different activation path (RoActivateInstance) than COM (CoCreateInstance), so no it is not possible to implement a COM server directly in UWP.

However, with PackagedCOM you can include an OOP COM component in your package, and place the class registrations in the manifest, and then submit this package to the Store. This still gives you the clean install and uninstall provided by msix packaging.  For more information, refer to:
https://blogs.windows.com/buildingapps/2017/04/13/com-server-ole-document-support-desktop-bridge/

Adam
