### ISSUE TITLE
POS Printer Claim fails on 1809

### ISSUE THREAD

**Issue by nsandeep87** [microsoft/Windows-universal-samples#1095]
Hi,

We are using HP-RP 9 with POSPrinter. We are currently on windows 10 1809(Security update KB4487044). The HP opos driver ( OPOS support for HP printers) version is 1.14.1.12. The same printer works fine on 1803. Can you please let me know a solution for this issue

Regards,
Sandeep

**Comment by oldnewthing** [comment]
This is not an issue with the sample. It's a question about device support. You can open a support case with our Developer Support team:

1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
