### ISSUE TITLE
GeneratorIncrementalLoadingClass  & layout cycle exception

### ISSUE THREAD

**Issue by HppZ** [microsoft/Windows-universal-samples#1097]
using GeneratorIncrementalLoadingClass class (in mediaImport sample) with a big maxcount leads to layout cycle exception.

code: https://github.com/HppZ/IncrementalLoadingBUG

**Comment by oldnewthing** [comment]
Dup of [https://github.com/microsoft/microsoft-ui-xaml/issues/723](the issue you filed in the XAML repo).
