### ISSUE TITLE
How to connect to Windows 10 Wifi direct sample from IPhone

### ISSUE THREAD

**Issue by soshogoh** [microsoft/Windows-universal-samples#1099]
When connect to Windows 10 Wifi direct sample from IPhone.
The Windows 10 started Advertisement with success.
From IPhone, selected the Win10 pc an connect, the Password input needed.  
What is the password should be?

Thanks

**Comment by oldnewthing** [comment]
This doesn't appear to be a question about the sample, but rather how the OS works. You can open a support case with the Developer Support team:

1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
