### ISSUE TITLE
Not able to access the Word Document on my system using the UWP application

### ISSUE THREAD

**Issue by rajasandeep17** [microsoft/Windows-universal-samples#1103]
I am trying to edit a existing Word document using the UWP app (Universal Windows). But for some reason I am getting "File does not exist" error.

I have tried using the below code to access the word document:
using(WordprocessingDocument wordDoc = WordprocessingDocument.Open("C:\\Users\\Public\\Desktop\\Doc1.docx", true))
{

}

I am getting the below error:
System.IO.FileNotFoundException: 'Could not find document'

I have checked there are no typos in the file path. The same code(above specified) is working when I implement it on a normal Winforms code.

**Comment by oldnewthing** [comment]
This is not an issue with a sample in this repo. You can open a support case with our Developer Support team:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.

(My guess is that your app doesn't have access to that folder. Try using a FileOpenPicker.)
