### ISSUE TITLE
[help]Is there any tutorial for how to use ESim manager API?

### ISSUE THREAD

**Issue by novrain** [microsoft/Windows-universal-samples#1104]
I'm trying to us ESim API, and I follow this help:

[ESimManager Class
](https://docs.microsoft.com/en-us/uwp/api/windows.networking.networkoperators.esimmanager)
and add the custom capability required in this help: 

[Custom capabilities
](https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations#custom-capabilities)

`
<Package xmlns="http://schemas.microsoft.com/appx/manifest/foundation/windows10" 

xmlns:mp="http://schemas.microsoft.com/appx/2014/phone/manifest" 

xmlns:uap="http://schemas.microsoft.com/appx/manifest/uap/windows10" 

xmlns:r="http://schemas.microsoft.com/appx/manifest/foundation/windows10/restrictedcapabilities" 

xmlns:uap4="http://schemas.microsoft.com/appx/manifest/uap/windows10/4" 

IgnorableNamespaces="uap mp r">

.....

  <Capabilities>

    <r:Capability Name="cellularDeviceIdentity" />

    <r:Capability Name="cellularDeviceControl" />

    <r:Capability Name="cellularMessaging" />

    <uap4:CustomCapability Name="Microsoft.eSIMManagement_8wekyb3d8bbwe"/>

  </Capabilities>

</Package>
`

but when I run this uwp, I got this error:

`
DEP0700: Registration of the app failed. [0x80073CF6] Error 0x80070002: The system was unable to register the windows.capability extension when preparing to process the request: The system cannot find the file specified.
`

Does this capability must be authoriazed ?

Anyone can help me? Thank you so much.

**Comment by oldnewthing** [comment]
This is not a question about a sample in this repo. You can open a support case with our Developer Support team for assistance.
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.

**Comment by novrain** [comment]
Ok, thank you for your help.

**Comment by MarcelWinkelEBF** [comment]
> Ok, thank you for your help.

Hi, I know it's a long time ago but could you maybe let me know if you got it running and if so how? Thanks :)
