### ISSUE TITLE
Altimeter sample

### ISSUE THREAD

**Issue by bjthomson** [microsoft/Windows-universal-samples#1105]
I'm obviously missing something. 

The only way I can think of to determine altitude would be some kind of pressure sensor. Fair enough, when I run the sample, it says it cant find a device - there isn't one on my machine. What I'm struggling with is how to install sensors and tell windows about them. There needs to be a driver of some sort, I've seen Windows.Devices.Gpio.GpioProvider - been there done that left a comment. 

How do we go about creating real-world devices & providers if we're not low-level bit bashers? (I am an ex-bit basher, long in the past)

**Comment by oldnewthing** [comment]
This is not a question about the sample itself. The sample shows how to use an altimeter assuming you have one. [Installing an altimeter](https://docs.microsoft.com/en-us/windows-hardware/drivers/sensors/introduction-to-the-sensor-and-location-platform-in-windows) is out of scope of the sample.

You can open a support case with our Developer Support team for assistance.

1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.

**Comment by bjthomson** [comment]
Thank you for the link to installing an altimeter. I would never have found that (and I thought I was quite good at Bingling for MS docs)

**Comment by bjthomson** [comment]
I appreciate this is closed, but for the benefit of any other searchers, the link points to pages regarding windows 8 drivers. The GPS driver sample for Windows 8 is obsolete, there is a different GNSS sample for windows 10. Also the "setting up your development environment" section refers to a Sharks cove development board, which is deprecated, and only available until stock is used up.
