### ISSUE TITLE
[1903-Xbox] Creating a WebP BitmapDecoder fails on Xbox with System.Exception: The component initialization has failed.

### ISSUE THREAD

**Issue by Ryken100** [microsoft/Windows-universal-samples#1106]
Creating a WebP BitmapDecoder on Xbox targeting version 1903 using `BitmapDecoder.CreateAsync(BitmapDecoder.WebPDecoderId, IRandomAccessStream)` fails with `System.Exception: The component initialization has failed. (Exception from HRESULT: 0x88982F8B)`.

Additionally, creating setting a WebP as the stream source of a BitmapImage on Xbox using `BitmapImage.SetSourceAsync(IRandomAccessStream)` fails with the error message `E_NETWORK_ERROR` in the `BitmapImage.ImageFailed` event, even with a locally stored file.

On desktop, creating a WebP BitmapDecoder and BitmapImage both work correctly.

Repro can be found [here](https://github.com/microsoft/Windows-universal-samples/files/3243481/WebPRepro.zip). The repro attempts to create both a WebP BitmapDecoder and BitmapImage, and shows success or failure for both via TextBlock, including exception/error info.

**Comment by oldnewthing** [comment]
This is not an issue with a sample in this repo. can open a support case with our Developer Support team:  
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
