### ISSUE TITLE
Logging sample file rollover before reaches a size of 256MB

### ISSUE THREAD

**Issue by luyaok** [microsoft/Windows-universal-samples#1107]
Code sample: https://github.com/microsoft/Windows-universal-samples/tree/master/Samples/Logging

I found the the following in code sample: https://github.com/microsoft/Windows-universal-samples/blob/master/Samples/Logging/cs/FileLoggingSessionScenario.cs#L173

/// This handler is called by the FileLoggingSession instance when a log
/// file reaches a size of **256MB.**

All log files for me are about 265 KB, it can't reach the 256 MB even if I write the large enough data like the sample Scenario3 does.

Can you have a check? Thanks.

**Comment by oldnewthing** [comment]
Might simply be a typo. Will check with feature team.

**Comment by oldnewthing** [comment]
Yup, just a typo. [The MSDN documentation correctly says 256KB](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.diagnostics.fileloggingsession).
