### ISSUE TITLE
CameraGetPreviewFrame leaks memory on every click

### ISSUE THREAD

**Issue by stephenstarkie** [microsoft/Windows-universal-samples#1108]
I have been running code based on the CameraGetPreviewFrame cs sample and found a memory leak - I have found that if you click the Show Frame button the _mediaCapture.GetPreviewFrameAsync leaks memory (simply watch the Process Memory view in VS Diagnostic Tools - we isolated it to this by cutting out other code) every time it is called by pressing the GetPreviewFrameAsync button.

**Comment by stephenstarkie** [comment]
I have also asked on StackOverflow; https://stackoverflow.com/questions/56647650/how-to-fix-memory-leak-in-getpreviewframeasync

It may be a bug introduced in Window 10 1903 as I can't repeat it on my desktop PC running Windows 10 1809

**Comment by oldnewthing** [comment]
I asked the feature team to determine whether this is a sample bug or an OS bug. If an OS bug, then it's not an issue for this repo.

**Comment by stephenstarkie** [comment]
Thanks @oldnewthing. While this may well be an issue with the OS rather than the sample, the bug does break the sample and therefore lead developers to using code that won't work properly.  Could the sample be updated to use code that does work?  I understand that using the API https://docs.microsoft.com/en-us/uwp/api/windows.media.capture.frames.mediaframereader might work instead, and am in the process of trying this myself (so can't yet confirm this).  Are there other ways the sample could be modified to make it work, or is Microsoft's intention that developer's should still use this API (when it works again)?

**Comment by oldnewthing** [comment]
Feature team confirms the bug and reports that a fix is in the pipeline. So the sample will stop leaking once the fix goes out. I cannot give an ETA.

**Comment by stephenstarkie** [comment]
I can now confirm that the MediaFrameReader API is a good workaround for this problem
