### ISSUE TITLE
UWP WinJS Advertising example shut down with 'Access violation' 1073741819 (0x0000005)

### ISSUE THREAD

**Issue by creakosta** [microsoft/Windows-universal-samples#1109]
App shut down when interstitial or banner ads is called, video ad is working fine.
App shut down without errors, but in output log in Visual Studio I see:

_The program '[12568] WWAHost.exe" has exited with code -1073741819 (0x0000005) 'Access violation'_  

I use Visual Studio 2017, App target version SDK 10.0.17763.0, Microsoft Ads SDK 10.1807.9.0

I tried to use Visual Studio 2015 and old version of Ads SDK, but I get the same result.

Here post on MSDN: 
[https://social.msdn.microsoft.com/Forums/windowsapps/en-US/0b5b9742-2511-40e4-b1fb-4599fd972e4d/uwpwinjs-app-shutdown-with-access-violation-after-updating-microsoft-ads-sdk-to-last-version?forum=aiasd](https://social.msdn.microsoft.com/Forums/windowsapps/en-US/0b5b9742-2511-40e4-b1fb-4599fd972e4d/uwpwinjs-app-shutdown-with-access-violation-after-updating-microsoft-ads-sdk-to-last-version?forum=aiasd)

**Comment by oldnewthing** [comment]
This sounds like an issue with the Advertising SDK, which is not part of Windows. The advertising sample is hosted here as a courtesy to the advertising team, but they are the ones who support it. Sorry, can't help you here. Should we just remove the sample?
