### ISSUE TITLE
Examples using SQLite?

### ISSUE THREAD

**Issue by SMavr** [Microsoft/Windows-universal-samples#111]
Could you add some examples using sqlite? 

The problem is that migrating from RC to RTM, I am getting sqlite3.dll not found error when I run my UWP on mobile (Emulator or Device). On Local machine works prefectly.

**Comment by RuslanSCH** [comment]
Hi SMavr, however i know, Microsoft dont implement SQLite. I using SQLite.WinRT for UWP (NugetPackage). Try it it.

**Comment by SMavr** [comment]
Hi RuslanSCH, 
  I found the solution. Just overwriting the sqlite3.dll.
http://stackoverflow.com/questions/31851012/unable-to-load-dll-sqlite3-in-universal-windows-app-running-on-mobile

**Comment by dotMorten** [comment]
Now that SQLite does ship with 10586, can we reopen this? @AdamBraden
