### ISSUE TITLE
2017 references instead of 2019

### ISSUE THREAD

**Issue by Damag3d** [microsoft/Windows-universal-samples#1114]
Windows-universal-samples/SharedContent/Templates/InstallSDKTemplates.cmd uses 2017 Visual Studio reference instead of 2019

**Comment by oldnewthing** [comment]
I haven't upgraded the repo to VS 2019 yet. Note that the main readme still says 2017.

**Comment by Damag3d** [comment]
Managed to solve it quickly by changing the paths in CMD.

**Comment by oldnewthing** [comment]
Fixed in next update.
