### ISSUE TITLE
Face detector and face tracker are unreliable

### ISSUE THREAD

**Issue by Damag3d** [microsoft/Windows-universal-samples#1115]
I tried Windows Camera app and Face detector/face tracker samples - took some time till I found that they actually work. Windows Camera app works pretty well even on my old model of LifeCam Cinema. However these samples though look similar to camera app provide different results. I guess camera app does some tweaking dynamically (exposure management...) - it would be nice to see how it can be done in this sample.

**Comment by oldnewthing** [comment]
The sample shows the basics of how to use the UWP APIs. Custom face recognition (using means other than the UWP face detector) are out scope for the sample. if you feel that the system-provided face detector is inadequate, you can submit feedback about the platform itself through Feedback Hub or the forums. The sample is limited to what the API provides.
