### ISSUE TITLE
Lost ability to build store package after addintion SDKReference

### ISSUE THREAD

**Issue by artall64** [Microsoft/Windows-universal-samples#112]
I add two SDKReference to my project:

`<SDKReference Include="WindowsDesktop, Version=10.0.10240.0">`
`<Name>Windows Desktop Extensions for the UWP</Name>`
`</SDKReference>`

`<SDKReference Include="WindowsMobile, Version=10.0.10240.0">`
`    <Name>Windows Mobile Extensions for the UWP</Name>`
`</SDKReference>`

You can find same references in some samples for example in LockScreenApps.csproj

After that, I lost ability to build store package. I got next error message when trying to build package to upload to the store:

LOGGERBASEDEXECTASK : ILC error ILC1004: Directory 'C:\Program Files (x86)\Windows Kits\10\References\Windows.UI.Xaml.HostingHostingContract\1.0.0.0' passed to argument 'externalReferencePath' does not exist.

And actually this dir really does not exist. But exist another one:
Windows.UI.Xaml.Hosting.HostingContract  - exist in my system
Windows.UI.Xaml.HostingHostingContract   - VS2015 try to find

The difference that VS2015 try find HostingHostingContrac without dot inside:
HostingHostingContrac
Hosting.HostingContract

**Comment by AdamBraden** [comment]
This is not a problem with the sample, please follow up with this known issue:
https://social.msdn.microsoft.com/Forums/en-US/2887e169-348d-4d97-a359-aee413b5fa26/rtm-known-issue-release-configuration-fails-to-build-on-using-desktop-and-mobile-extension-sdks-in?forum=Win10SDKToolsIssues
