### ISSUE TITLE
Windows printing issue seen when x-web-view is dismissed

### ISSUE THREAD

**Issue by nsandeep87** [microsoft/Windows-universal-samples#1120]
I am using a windows UWP cordova app. I am trying with the Printer sample provided in this repo (/samples/Printing/js)

In order  to print from the UWP app, we use  Windows.Graphics.Printing.PrintManager.showPrintUIAsync();

We also need to use x-ms-webview, for other purposes.
           wv = document.createElement('x-ms-webview');
           wv.id = "test145";
           document.body.appendChild(wv);
 I destroy the x-ms-webview from DOM using javascript API, 
        document.getElementById("test145").remove();

After destroying the webview, the Printer API fails. It throws the error

Unhandled exception at line 357, column 1 in res://edgehtml.dll/preview.js​
​0x8000ffff - JavaScript runtime error: Unexpected call to method or property access.​

Is there any workaround/fix for this

**Comment by oldnewthing** [comment]
This doesn't appear to be a question about a sample in this repo. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
