### ISSUE TITLE
Prevent ListViewItem from being focused but the children still receive focus

### ISSUE THREAD

**Issue by AMaini503** [microsoft/Windows-universal-samples#1123]
Hi,

Usually, the focus flow in a listviewitem is that the container receives the focus first and then, the items within it receive focus subsequently.

**I want to override this behavior s.t. the container doesn't receive focus but the items within it do when navigated to/from.** 

I did some research on my own but can't figure out the solution yet. The reason I can't any other control is because I want to bind the listview to an IObservable. Other layout controls don't offer the functionality of binding an item source.

I have tried adding the "GotFocus" handler to pass on the focus from ListViewItem to its children, but it's considerably slow as I can see the focus actually moving around.

**Comment by oldnewthing** [comment]
The issue you are running into is not about a sample un this repo. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:

1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
