### ISSUE TITLE
BackgroundDownloadProgress.TotalBytesToReceive is always zero in Build 1903

### ISSUE THREAD

**Issue by velocitysystems** [microsoft/Windows-universal-samples#1125]
### Description
When using the BackgroundTransfer API in Windows 10 Build 1903, `BackgroundDownloadProgress.TotalBytesToReceive` is always zero.

This means you cannot determine the progress of a download operation.

### Steps to Reproduce

1. Download and run the BackgroundTransfer sample.
2. Observe the log output _"Transferred bytes: x of 0"_

### Expected Behavior
`TotalBytesToReceive` should not be zero.

### Actual Behavior
`TotalBytesToReceive` is always zero on Windows 10 Build 1903.

### Basic Information

- Version with issue:
- Last known good version: Windows 10 Build 1809

Reported on the Windows Developer Feedback forum:
https://wpdev.uservoice.com/forums/110705-universal-windows-platform/suggestions/38253688-backgrounddownloadprogress-totalbytestoreceive-is

**Comment by DavidGoll** [comment]
Thanks for the detailed report. This is a known issue that will be fixed in a future update.

**Comment by ThomasPe** [comment]
Since the UserVoice is no longer being used and I can't see any issue related to this in https://github.com/MicrosoftDocs/windows-uwp/issues I was wondering if this has been addressed? 
I'm still seeing TotalBytesToReceive being 0 despite the content-length header being set on the server (double-checked using Postman). 
Should I be opening a new issue in the windows-uwp repo?

**Comment by PeterSmithRedmond** [comment]
Good news! We have a fix, and it will be part of the next windows. If you’re on an insider build, you should already have the fix as of mid-September.

Peter Smith
PM for the Network Developer Experience team

**Comment by ThomasPe** [comment]
Do you know with what Build this fix has shipped?

**Comment by oldnewthing** [comment]
(FYI, https://github.com/MicrosoftDocs/windows-uwp/issues is for reporting issues with the docs, not issues with the platform.)
