### ISSUE TITLE
Unknown type 'ScenarioBindingConverter' in XML namespace 

### ISSUE THREAD

**Issue by alexey-zhel** [microsoft/Windows-universal-samples#1128]
I cannot compile KeyCredentialManager project in Visual Studio 2019. Getting following error message:

Severity	Code	Description	Project	File	Line	Suppression State
Error		Unknown type 'ScenarioBindingConverter' in XML namespace 'using:SDKTemplate'	KeyCredentialManager	C:\Samples\Samples\KeyCredentialManager\cs\MainPage.xaml	24

**Comment by oldnewthing** [comment]
Thanks for the report. Fixed in the next update.
