### ISSUE TITLE
Setting MediaPlayerElement.TransportControls.IsCompactOverlayEnabled gives exception

### ISSUE THREAD

**Issue by marufbd** [microsoft/Windows-universal-samples#1132]
Uwp app 
Target version: 1809.
Min version: Fall creators update.

Dev machine:
OS Version: 1709
OS Build: 16299.1268

My code:
```
_player=new MediaPlayer();
MediaPlayerElement mediaElement = new MediaPlayerElement
{
	TransportControls =
	{
		IsSeekBarVisible = false
	}
};

mediaElement.SetMediaPlayer(_player);
mediaElement.AutoPlay = true;

//exception happens on this line, without it everything works fine
mediaElement.TransportControls.IsCompactOverlayEnabled = true;

```

Exception:
`System.InvalidCastException: 'Unable to cast object of type 'Windows.UI.Xaml.Controls.MediaTransportControls' to type 'Windows.UI.Xaml.Controls.IMediaTransportControls4'.'`

**Comment by hupo376787** [comment]
try
`await Dispatcher.RunAsync(CoreDispatcherPriority.Normal, () =>
                        {
                            mediaElement.TransportControls.IsCompactOverlayEnabled = true;
                        });`

**Comment by marufbd** [comment]
@hupo376787 have you tried this.

For me still same exception, nothing changed.

**Comment by oldnewthing** [comment]
IsCompactOverlayEnabled is [documented as](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.mediatransportcontrols.iscompactoverlayenabled#Windows_UI_Xaml_Controls_MediaTransportControls_IsCompactOverlayEnabled)


Device family | Windows 10, version 1803 (introduced v10.0.17134.0)
-- | --
API contract | Windows.Foundation.UniversalApiContract (introduced v6

Fall Creators Update is 1709, which is too old.

Note also that this is not a question about a sample in this repo, so I'm closing it as off topic. 

You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:

1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
