### ISSUE TITLE
update readme.md in XamlCloudFontIntegration?

### ISSUE THREAD

**Issue by sam9116** [microsoft/Windows-universal-samples#1135]
your link is broken, I think its called Guidelines for fonts
[https://msdn.microsoft.com/library/windows/apps/hh700394.aspx](https://msdn.microsoft.com/library/windows/apps/hh700394.aspx)

**Comment by oldnewthing** [comment]
Thanks. New link appears to be https://docs.microsoft.com/windows/uwp/design/style/typography
