### ISSUE TITLE
KWSApo not work on 19H1

### ISSUE THREAD

**Issue by vingo555** [microsoft/Windows-universal-samples#1137]
1. I compiled and register the KWSApo (audio\sysvad\APO\KWSApo) manually and verified the APO dll file in my latest 19H1 window 
2. The window OS version is “Version 1903”, OS build 18382.295
3. After the  APO dll is loaded, the audio engine will call function "CKWSApoEFX::Initialize" in the function, it will try to achieve interleave audio format information.  the codes are : 
`
  
        ::ZeroMemory(&ksPinProperty, sizeof(ksPinProperty));
        ksPinProperty.Property.Set    = KSPROPSETID_InterleavedAudio; 
        ksPinProperty.Property.Id     = KSPROPERTY_INTERLEAVEDAUDIO_FORMATINFORMATION;       
        ksPinProperty.Property.Flags  = KSPROPERTY_TYPE_GET;
        ksPinProperty.PinId           = myPartId & 0x0000ffff;

        ::ZeroMemory(&m_FormatInfo, sizeof(m_FormatInfo));

        hr = spKsControl->KsProperty(&(ksPinProperty.Property), sizeof(ksPinProperty), &m_FormatInfo, sizeof(m_FormatInfo), &cbReturned)`

    the invocation will return error code "0x80070492" and the error message is : "The property set specified does not exist on the object."

**Comment by oldnewthing** [comment]
This does not appear to be an issue with a sample in this repo. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
