### ISSUE TITLE
BluetoothLE CPPwinrt doesn't build

### ISSUE THREAD

**Issue by mkardan** [microsoft/Windows-universal-samples#1138]
Hi there,

I am trying to build the BluetoothLE cppwinrt solution/project in Visual Studio 16.2.3 but the sample doesn't build - C# project does work though- It fails with loads of syntax errors/missing types etc - attached- I have also added "microsoft.windows.cppwinrt.2.0.190730.2.nupkg" to my visual studio nupkg.

Cheers,
Kard-Anne

[cppwinrt_errors.txt](https://github.com/microsoft/Windows-universal-samples/files/3558853/cppwinrt_errors.txt)

**Comment by oldnewthing** [comment]
I think you have an outdated version of the XAML compiler. Make sure you're using the one in 10.0.18362.0.
