### ISSUE TITLE
UISettings.ColorValuesChanged and accent colors

### ISSUE THREAD

**Issue by veccie** [Microsoft/Windows-universal-samples#114]
I can only find one example where UISettings is used: XamlTransform3DAnimations, but I have a question regarding UISettings.ColorValuesChanged.

I was hoping that I could use this event to detect when a user changes the accent color under personalization settings, but nothing happens.

I know that system brushes like {ThemeResource SystemAccentColor} updates automatically, but I want to be able to use the accent variations, that you can get from UISettings.GetColorValue(UIColorType). For example UIColorType.AccentLight3 or UIColorType.AccentDark3.

Is it possible to detect accent color changes from C# code?

Or are there equivalent system color brushes that corresponds to the ones in UIColorType?

**Comment by veccie** [comment]
Ok, so the ColorValuesChanged event does work. Kind of. It's just very inconsistent and unreliable to say the least.

Some times it works, some times it doesn't and often it's delayed by a lot and suddenly triggers after you've clicked around in Windows 10 desktop. Start menu and Action Center seems to trigger it after a while, though I'm not certain, because it's very inconsistent.

This does sound more of OS/Framework issue and I apologize for posting here, but does anyone know of this behavior? Or maybe can point me to where I can report it?

**Comment by AdamBraden** [comment]
This issue is not sample specific and is more relevant for the forums, please post Q&A type questions here: 
https://social.msdn.microsoft.com/Forums/windowsapps/en-US/home?forum=wpdevelop
