### ISSUE TITLE
 The type or namespace name 'HttpRequestResult' could not be found MicrosoftPassport 

### ISSUE THREAD

**Issue by lukedukeus** [microsoft/Windows-universal-samples#1141]
Noob here: Im seeing these two errrors on a fresh install of vs2017, and cant figure out what to do. Can anyone help?
<img width="1126" alt="wut" src="https://user-images.githubusercontent.com/23089287/65479741-a3ebae00-de5c-11e9-83b9-97dd0d3075ac.PNG">

**Comment by oldnewthing** [comment]
The master branch requires the latest SDK, which is 18362. I bet you are using 17763.

I'm surprised Visual Studio didn't warn you about this. The project is marked

```
    <TargetPlatformVersion>10.0.18362.0</TargetPlatformVersion>
    <TargetPlatformMinVersion>10.0.18362.0</TargetPlatformMinVersion>
```
