### ISSUE TITLE
Issue with WiFi Direct API

### ISSUE THREAD

**Issue by rauthan009** [microsoft/Windows-universal-samples#1143]
I tried the sample solution on my devices, 
After clicking on the connect button, connection prompt requires is opened on both devices, but after clicking Accept, the "Advertiser" device shows error stating Connection declined from the "Connector " device
![connectionError](https://user-images.githubusercontent.com/47236365/66116787-fb261700-e5f0-11e9-9ea0-f18385f16379.PNG)

**Comment by rauthan009** [comment]
After running the app in release mode instead of debug mode, The issue was resolved

**Comment by rauthan009** [comment]
The app works in release mode, but not on every device, so are there any detailed docs on the WIFI Direct to read more about the usage

**Comment by oldnewthing** [comment]
This looks like a problem with the platform, not with the sample. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
