### ISSUE TITLE
MiracastReceiver stream corrupts after few seconds / minutes

### ISSUE THREAD

**Issue by Titaye** [microsoft/Windows-universal-samples#1145]
Playing with MiracastReceiver.
Everything works fine at first. Then later the video stream is corrupted.
Can you put a working sample of frame processing of the MiracastReceiver ?
Here is mine. FrameServerImage is an Image from my Xaml

``` 
 public sealed partial class MainPage : Page
    {
        private MiracastReceiver receiver;
        private MiracastReceiverSession session;
        private MediaPlayer mp;
        private CanvasImageSource canvasImageSource;
        private SoftwareBitmap frameServerDest;
        private MiracastReceiverConnection connection;

        public MainPage()
        {
            this.InitializeComponent();

            this.Loaded += MainPage_Loaded;
        }

        private void Receiver_StatusChanged(MiracastReceiver sender, object args)
        {
            Debug.WriteLine(receiver.GetStatus().ListeningStatus);
        }

        private void MainPage_Loaded(object sender, RoutedEventArgs e)
        {
            receiver = new MiracastReceiver();
            receiver.StatusChanged += Receiver_StatusChanged;
            var settings = receiver.GetDefaultSettings();
            settings.AuthorizationMethod = MiracastReceiverAuthorizationMethod.None;
            receiver.DisconnectAllAndApplySettings(settings);

            session = receiver.CreateSession(CoreApplication.MainView);
            session.AllowConnectionTakeover = true;

            session.ConnectionCreated += Session_ConnectionCreated;
            session.MediaSourceCreated += Session_MediaSourceCreated;
            session.Start();
        }

        private void Session_ConnectionCreated(MiracastReceiverSession sender, MiracastReceiverConnectionCreatedEventArgs args)
        {
            connection = args.Connection;
        }

        private void Session_MediaSourceCreated(MiracastReceiverSession sender, MiracastReceiverMediaSourceCreatedEventArgs args)
        {
            mp = new MediaPlayer();
            mp.VideoFrameAvailable += Mp_VideoFrameAvailable;
            mp.AutoPlay = true;
            mp.IsVideoFrameServerEnabled = true;
            mp.Source = args.MediaSource;
            //me.SetPlaybackSource(args.MediaSource);
        }

        private async void Mp_VideoFrameAvailable(MediaPlayer sender, object args)
        {
            CanvasDevice canvasDevice = CanvasDevice.GetSharedDevice();

            await Dispatcher.RunAsync(Windows.UI.Core.CoreDispatcherPriority.Normal, () =>
            {
                if (frameServerDest == null)
                {
                    // FrameServerImage in this example is a XAML image control
                    frameServerDest = new SoftwareBitmap(BitmapPixelFormat.Rgba8, 1920, 1080, BitmapAlphaMode.Ignore);
                }
                if (canvasImageSource == null)
                {
                    canvasImageSource = new CanvasImageSource(canvasDevice, 1920, 1080, DisplayInformation.GetForCurrentView().LogicalDpi);
                    FrameServerImage.Source = canvasImageSource;
                }

                using (CanvasBitmap inputBitmap = CanvasBitmap.CreateFromSoftwareBitmap(canvasDevice, frameServerDest))
                using (CanvasDrawingSession ds = canvasImageSource.CreateDrawingSession(Windows.UI.Colors.Transparent))
                {

                    mp.CopyFrameToVideoSurface(inputBitmap);
                    ds.DrawImage(inputBitmap);
                }
            });
        }
    }
```

**Comment by aklemets** [comment]
There is one issue with your sample code. You need to enable real-time playback on the MediaPlayer. Like this:
**mp.RealTimePlayback = true;**

I tried your sample code and without this setting, the MediaPlayer seemed to get stuck in buffering state. Only a few video frames were shown, and then the video froze.
Then I set RealTimePlayback to true and it worked fine. I tested by projecting a video from a laptop for 10 minutes. No video corruption was seen during those 10 minutes.

As the transmitter device I used a Surface Pro 6. I also tried transmitting from an older model Samsung Galaxy Tab tablet, and there was no video corruption using that device either. My receiver device is a HP workstation (desktop PC) with an Intel Wi-Fi adapter and an AMD graphics card.

**Comment by Titaye** [comment]
Thx, I'll try this.
I've also reproduced the case with a simple mediaelement so I think the real-time property is not the issue.

**Comment by Titaye** [comment]
I tried in my repro app. 
With a mediaelement consuming the source, I can reproduce the issue:  https://1drv.ms/v/s!AtqD0WEoWhS3l_10l0B9GR_NcW1onQ?e=fUo1vV
I've put a MediaElement in xaml. removed `mp.Source = args.MediaSource;` and put `me.SetPlaybackSource(args.MediaSource);`
The stream is ok few seconds. I let my phone without touching it 5 to 10 seconds, then the frames are corrupted.

But, no corruption so far with the RealTimePlayback property and the MediaPlayer.

**Comment by oldnewthing** [comment]
This is not a question about the samples itself. It's really a question about how to write your own program that uses the platform APIs. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
