### ISSUE TITLE
Buttons in File Picker are not bound to their event hanlders

### ISSUE THREAD

**Issue by sibarsoumi** [microsoft/Windows-universal-samples#1149]
The attribute "Click" in the tags of the buttons in the XAML files in [FilePicker](https://github.com/microsoft/Windows-universal-samples/blob/master/Samples/FilePicker) are missing so the buttons are not linked correctly to their corresponding event hanlders in the code-behind files.
Therefore, the buttons do not work.

**Comment by dts350z** [comment]
I tried this on two different windows 10 machines and found the scenario 1 & 2 buttons do nothing while the scenario 5, "open a file" button does work. 

I am only looking at the cpp versions.

**Comment by cindychen0204** [comment]
I love solve the problem but I can not make a pull request

**Comment by oldnewthing** [comment]
Oops sorry. fixed in next update.
