### ISSUE TITLE
C# version ResizeAppView does not compile with VS 2015 14.0.23107

### ISSUE THREAD

**Issue by svenvandevelde** [Microsoft/Windows-universal-samples#115]
Downloaded the Windows Universal Samples Master ZIP file on 03/08/2015.

Some applications are not compiling, f.e. the ResizeAppView application.

Doing a build on the local machine in x86 mode. Get the following errors and warnings:

**Warning		The parent file, 'Scenario1_Basic.xaml', for file 'Scenario1_Basic.xaml.cs' cannot be found in the project file.	ResizeAppView		
Warning		The parent file, 'Scenario2_Launch.xaml', for file 'Scenario2_Launch.xaml.cs' cannot be found in the project file.	ResizeAppView		
Error		Could not find a part of the path 'C:\Users\vandeves\Documents\Samples\ResizeAppView\shared\Scenario1_Basic.xaml'.	ResizeAppView		
Warning		The system cannot find the path specified. (Exception from HRESULT: 0x80070003)	ResizeAppView		
Error	CS1061	'Scenario1_Basic' does not contain a definition for 'InitializeComponent' and no extension method 'InitializeComponent' accepting a first argument of type 'Scenario1_Basic' could be found (are you missing a using directive or an assembly reference?)	ResizeAppView	C:\Users\vandeves\Documents\Samples\ResizeAppView\cs\Scenario1_Basic.xaml.cs	28
Error	CS0103	The name 'SetMinimumSize' does not exist in the current context	ResizeAppView	C:\Users\vandeves\Documents\Samples\ResizeAppView\cs\Scenario1_Basic.xaml.cs	62
Error	CS0103	The name 'ReportViewWidth' does not exist in the current context	ResizeAppView	C:\Users\vandeves\Documents\Samples\ResizeAppView\cs\Scenario1_Basic.xaml.cs	82
Error	CS0103	The name 'ReportViewHeight' does not exist in the current context	ResizeAppView	C:\Users\vandeves\Documents\Samples\ResizeAppView\cs\Scenario1_Basic.xaml.cs	83
Error	CS1061	'Scenario2_Launch' does not contain a definition for 'InitializeComponent' and no extension method 'InitializeComponent' accepting a first argument of type 'Scenario2_Launch' could be found (are you missing a using directive or an assembly reference?)	ResizeAppView	C:\Users\vandeves\Documents\Samples\ResizeAppView\cs\Scenario2_Launch.xaml.cs	23
Error	CS0103	The name 'LaunchAtSize' does not exist in the current context	ResizeAppView	C:\Users\vandeves\Documents\Samples\ResizeAppView\cs\Scenario2_Launch.xaml.cs	24
Error	CS0103	The name 'LaunchAtSize' does not exist in the current context	ResizeAppView	C:\Users\vandeves\Documents\Samples\ResizeAppView\cs\Scenario2_Launch.xaml.cs	32
Error	CS1061	'App' does not contain a definition for 'InitializeComponent' and no extension method 'InitializeComponent' accepting a first argument of type 'App' could be found (are you missing a using directive or an assembly reference?)	ResizeAppView	C:\Users\vandeves\Documents\SharedContent\cs\App.xaml.cs	34
Error	CS1061	'MainPage' does not contain a definition for 'InitializeComponent' and no extension method 'InitializeComponent' accepting a first argument of type 'MainPage' could be found (are you missing a using directive or an assembly reference?)	ResizeAppView	C:\Users\vandeves\Documents\SharedContent\cs\MainPage.xaml.cs	33
Error	CS0103	The name 'SampleTitle' does not exist in the current context	ResizeAppView	C:\Users\vandeves\Documents\SharedContent\cs\MainPage.xaml.cs	38
Error	CS0103	The name 'ScenarioControl' does not exist in the current context	ResizeAppView	C:\Users\vandeves\Documents\SharedContent\cs\MainPage.xaml.cs	44
Error	CS0103	The name 'ScenarioControl' does not exist in the current context	ResizeAppView	C:\Users\vandeves\Documents\SharedContent\cs\MainPage.xaml.cs	47
Error	CS0103	The name 'ScenarioControl' does not exist in the current context	ResizeAppView	C:\Users\vandeves\Documents\SharedContent\cs\MainPage.xaml.cs	51
Error	CS0103	The name 'ScenarioFrame' does not exist in the current context	ResizeAppView	C:\Users\vandeves\Documents\SharedContent\cs\MainPage.xaml.cs	70
Error	CS0103	The name 'Splitter' does not exist in the current context	ResizeAppView	C:\Users\vandeves\Documents\SharedContent\cs\MainPage.xaml.cs	73
Error	CS0103	The name 'StatusBorder' does not exist in the current context	ResizeAppView	C:\Users\vandeves\Documents\SharedContent\cs\MainPage.xaml.cs	93
Error	CS0103	The name 'StatusBorder' does not exist in the current context	ResizeAppView	C:\Users\vandeves\Documents\SharedContent\cs\MainPage.xaml.cs	96
Error	CS0103	The name 'StatusBlock' does not exist in the current context	ResizeAppView	C:\Users\vandeves\Documents\SharedContent\cs\MainPage.xaml.cs	99
Error	CS0103	The name 'StatusBorder' does not exist in the current context	ResizeAppView	C:\Users\vandeves\Documents\SharedContent\cs\MainPage.xaml.cs	102
Error	CS0103	The name 'StatusBlock' does not exist in the current context	ResizeAppView	C:\Users\vandeves\Documents\SharedContent\cs\MainPage.xaml.cs	102
Error	CS0103	The name 'StatusBlock' does not exist in the current context	ResizeAppView	C:\Users\vandeves\Documents\SharedContent\cs\MainPage.xaml.cs	103
Error	CS0103	The name 'StatusBorder' does not exist in the current context	ResizeAppView	C:\Users\vandeves\Documents\SharedContent\cs\MainPage.xaml.cs	105
Error	CS0103	The name 'StatusPanel' does not exist in the current context	ResizeAppView	C:\Users\vandeves\Documents\SharedContent\cs\MainPage.xaml.cs	106
Error	CS0103	The name 'StatusBorder' does not exist in the current context	ResizeAppView	C:\Users\vandeves\Documents\SharedContent\cs\MainPage.xaml.cs	110
Error	CS0103	The name 'StatusPanel' does not exist in the current context	ResizeAppView	C:\Users\vandeves\Documents\SharedContent\cs\MainPage.xaml.cs	111
Error	CS0103	The name 'Splitter' does not exist in the current context	ResizeAppView	C:\Users\vandeves\Documents\SharedContent\cs\MainPage.xaml.cs	122
Error	CS0103	The name 'Splitter' does not exist in the current context	ResizeAppView	C:\Users\vandeves\Documents\SharedContent\cs\MainPage.xaml.cs	122**

**Comment by charlespetzold** [comment]
More succinctly, the ResizeAppView is missing a Shared folder and two XAML file.

**Comment by oldnewthing** [comment]
Sorry. You can grab the two XAML files from [here](https://github.com/oldnewthing/Windows-universal-samples/tree/master/ResizeView/cs). We'll get this fixed in the next refresh. Thanks for reporting.
