### ISSUE TITLE
Enhance my vb windows forms app to act as share target (VS 2017 CE)

### ISSUE THREAD

**Issue by wewa168** [microsoft/Windows-universal-samples#1151]

**Comment by wewa168** [comment]
I try to follow the ShareTarget cs sample and enhance my vb windows forms app to act as share target.
However, the issue is when I try to override OnShareTargetActivated there is error. From the cs sample there is an App class inherit from Windows.UI.Xaml.Application.
Is it possible to override OnShareTargetActivated  in vb windows forms app? or this is supported only in Xaml project?
Thanks

**Comment by oldnewthing** [comment]
This isn't really a question about the samples in the repo, but rather a question about writing a non-UWP app that implements a UWP contract. This is a question about the desktop bridge, not the UWP samples repo.
