### ISSUE TITLE
How can I see the URL that gets the 3D points for the 3d aerial view city models?

### ISSUE THREAD

**Issue by sebmooreaz** [microsoft/Windows-universal-samples#1153]
Hello,

I have been able to launch the mapcontrol sample using the c++ template.
And I have been searching through all the files but I can't find how the 3d vectors are dowloaded, is it an http get request? or a rest service? Geoservice WFS?

I am trying to port the map control to Unreal engine.

Thank you

**Comment by oldnewthing** [comment]
This is not a question about the sample. It appears to be a question about how to reuse the service from your own custom app. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
