### ISSUE TITLE
The bluetooth ble publisher is two slow! 

### ISSUE THREAD

**Issue by jiangxincode** [microsoft/Windows-universal-samples#1154]
When i use the interface about bluetooth ble, there are some problems:
https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.advertisement

1. When I invoke publisher.start, i must wait many seconds before windows really sends the bluetooth broadcast
2. Everytime i invoke publisher.start, the mac address will be changed. Is there some methods to avoid the auto Mac change?

**Comment by oldnewthing** [comment]
This appears to be a question about the platform, not about the sample. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
