### ISSUE TITLE
BluetoothAdvertisement - Watcher - How to unsubscribe from/filter out devices that were already received?

### ISSUE THREAD

**Issue by alangoes** [microsoft/Windows-universal-samples#1155]
Hi there,

Is there a way to unsubscribe from/filter out devices that were already received by the watcher? 

For example: 

1. The BluetoothLEAdvertisementWatcher is started by the method Start()
2. Received event is triggered by a device and calls method OnAdvertisementReceived that will handle the event.
3. After handling the event, it filters out this device somehow and then the watcher received event will no longer be triggered by this device until the watcher is stopped.

Is there a way to achieve this?

I have checked the use of BluetoothLEAdvertisementFilter, but it seems you can only filter devices that match a certain criteria, not the other way round. In this case, I want to filter out already processed device(s) that match a certain criteria i.e. To no longer receive advertisements from a device with certain UUID, Major and Minor.

Thanks

**Comment by oldnewthing** [comment]
This is a question about the platform, not about the sample. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:

1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
