### ISSUE TITLE
Many errors encontered when opened a project.(resolved)

### ISSUE THREAD

**Issue by sharpbladepan** [Microsoft/Windows-universal-samples#116]
Opened AppUIBasics solution, but a lot errors encountered. The first is:

Severity	Code	Description	Project	File	Line
Error	CS0246	The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)	AppUIBasics	C:\Users\peter\AppData\Local\Temp\.NETCore,Version=v5.0.AssemblyAttributes.cs	2

**Comment by oldnewthing** [comment]
You will get errors like this if you haven't done a Build. The Build step resolves the NuGet dependencies.

**Comment by sharpbladepan** [comment]
![fail info](https://cloud.githubusercontent.com/assets/3395150/9150580/23aef8d4-3e13-11e5-9733-cf7e1c02b67d.png)

I get this when make a building. :-(

**Comment by sharpbladepan** [comment]
Got following errors when make a building. (Already set 'Solution Platforms' to x64)
My network is fine, for Visual Studio can get updating without any problem.

![fail info-2](https://cloud.githubusercontent.com/assets/3395150/9150948/85772efa-3e23-11e5-90a3-552458dd37f0.png)
![fail info](https://cloud.githubusercontent.com/assets/3395150/9150950/8b2eede2-3e23-11e5-999d-1a7ef110b5e9.png)

**Comment by sharpbladepan** [comment]
After referred to the thread "Examples do not seem to build anymore #104" and tried for a while, finally succeeded to build it.
Create a new UWP project, copy the project.lock.json file into the directory of sample, them building is OK.

![cool](https://cloud.githubusercontent.com/assets/3395150/9151108/480621f6-3e29-11e5-848e-e37456e6a6d1.png)

Really cool!
