### ISSUE TITLE
RadioManager: Cannot set radio state of Mobile Broadband device. DeniedBySystem

### ISSUE THREAD

**Issue by yeongbin-jo** [microsoft/Windows-universal-samples#1165]
```
        public RadioModel(Radio radio, UIElement parent)
        {
            this.radio = radio;
            // Controlling the mobile broadband radio requires a restricted capability.
            this.isEnabled = (radio.Kind != RadioKind.MobileBroadband);
            this.parent = parent;
            this.radio.StateChanged += Radio_StateChanged;
        }
```

In this source code, restricted capabilities are required to control MobileBroadband.

```
    <Capabilities>
        <Capability Name="internetClient" />
        <DeviceCapability Name="radios" />
    </Capabilities>
```

This app already has "capabilities" for "radios". What does "restricted capability" means and what configuration do I need to get it?

**Comment by oldnewthing** [comment]
Fixed in next refresh.

**Comment by kachalkov** [comment]
we need control Radio Power for Mobile Broadband, but we are keep getting denied even with cellularDeviceControl capability, can you provide manifest example which should work?

**Comment by oldnewthing** [comment]
This sounds like a platform issue, not a sample issue. You can follow the instructions on [Windows developer support](https://developer.microsoft.com/en-us/windows/support/) for support options. (Click "Forums and community".)
