### ISSUE TITLE
MapControl Pin binding/rendering on low zoom level

### ISSUE THREAD

**Issue by graiSoft1982** [microsoft/Windows-universal-samples#1166]
When load a many of elypse with data bind on low zoom level wont load any item. When zooming in-out, on some zome level the map load any pin item. Some item loaded and som wont load on same low zoome level. 
https://youtu.be/ovkCAL1u92U

**Comment by oldnewthing** [comment]
This appears to be an issue with the control itself, not with the sample. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
