### ISSUE TITLE
How can I use one of the cpp sample with Unreal engine?

### ISSUE THREAD

**Issue by sebmooreaz** [microsoft/Windows-universal-samples#1170]
Hello, thank you for providing these samples.

But without documentation about the integrations, how can I use them with my workflow?
I am using Unreal engine, so I'm using cpp.

It would be nice to have like even just one example showing how to use for example "file picker" cpp sample with Unreal engine.
And same for Unity cs. 

Thank you.

**Comment by oldnewthing** [comment]
The C++/WinRT code samples can be used in any C++ app. C++/WinRT is a standard-conformant library for Windows Runtime objects. There is also a 3DPrintingFromUnity sample that shows Unity integration.
