### ISSUE TITLE
XAML data chain-binding issue

### ISSUE THREAD

**Issue by milindm2** [microsoft/Windows-universal-samples#1173]
I am working on a UWP application and i have created a custom `Date Picker control` and a custom `Time Picker control` which are child to a parent custom `Date-Time Picker Control`. The parent control has a property called `SelectedDateTime` which is the combination of the selection from two child controls. This property is binded correctly to child's properties in a two-way fashion but updating child's property does not update the parent' property.

**Comment by oldnewthing** [comment]
This is not a question about a sample in this repo. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.

Alternatively, you can ask the question on StackOverflow.  Use the tags `uwp` and `xaml`.
