### ISSUE TITLE
C++/WinRT project template is broken

### ISSUE THREAD

**Issue by fghzxm** [microsoft/Windows-universal-samples#1179]
The C++/WinRT project template is broken in at least 2 spots:
1. `/SharedContent/Templates/UWPSDKSampleCPP/UWPSDKSampleCPP.vstemplate` references nonexistent and apparently unneeded `Scenario{1,2}_ShortName.idl`, but fails to reference `Project.idl`;
2. Even if 1. is addressed, when building a project generated by that template `MainPage.g.cpp` is reported missing.

I'm not quite familiar with C++/WinRT for UWP apps, and have been trying to fix it myself in vain.

**Comment by oldnewthing** [comment]
Oops, sorry. Don't use those templates for your own UWP apps. Use [the ones that come with C++/WinRT](https://marketplace.visualstudio.com/items?itemName=CppWinRTTeam.cppwinrt101804264). These are templates for new samples in this repo, which are unusually-structured to minimize repo size.

**Comment by brodybits** [comment]
Is that information documented somewhere?

**Comment by oldnewthing** [comment]
I'll update the installer batch file so it reminds you that these are for developing new samples, not for developing UWP apps in general. In other words, the intended audience for the batch file is people who contribute new samples to this repo.

**Comment by fghzxm** [comment]
I am aware that the templates in this repo is for creation of samples only.  I do mean that I encounter difficulty when I try to create and build a new _sample_.  (I must have stated the problem in an inappropriate tone. 🌚)

**Comment by oldnewthing** [comment]
Sorry I misunderstood your remark. Why are you trying to create a new sample? As a general rule, samples come from the feature team.

**Comment by fghzxm** [comment]
I'm just playing around with this repo, seeing if I can port some samples from CX to C++/WinRT by myself.  However, new projects that I created from the template, as described in `SharedContent/Templates/README.md`, always fail to build on my computer.  I do believe that indicates some problems with the C++/WinRT template that may not reproduce themselves on your computer.

**Comment by oldnewthing** [comment]
Okay, fixed templates coming in next refresh. Thanks for pointing them out.
