### ISSUE TITLE
FTP & UDP file upload & download samples ??

### ISSUE THREAD

**Issue by deepsidhu1313** [Microsoft/Windows-universal-samples#118]
I think newbie developers like me can use FTP & UDP file upload & download samples to learn app development for windows.

Thanks :)

**Comment by DavidGoll** [comment]
The DatagramSocket sample illustrates UDP. While there isn't an explicit FTP sample, you can start with the StreamSocket sample (which illustrates TCP) over which you can implement the FTP protocol.
Another option for FTP is to use the BackgroundTransfer API, which supports FTP (as well as HTTP) under the covers.

**Comment by deepsidhu1313** [comment]
@DavidGoll Thanks for the Udp Hint. Actually i am newbie to C#, i have some experience with JAVA. trying my hands on Windows App development. I tried Http example today but unable to find Ftp with backgroundtransfer api. Can you please point me in the direction for Ftp (via link or some sample code)??

Also just for curiosity i have a udp socket server in Java. Will i be able to communicate with it using C#??
 

Thanks!! :smiley:

**Comment by DavidGoll** [comment]
FTP is specified via the scheme portion of the URI you supply as the download or upload target for BackgroundTransfer (e.g., **ftp:**//xxx.yyy.com).

Yes, your C# DatagramSocket app will be able to communicate with your UDP socket server. As far as the server is concerned, it's just receiving packets on a UDP port... it doesn't know how they were sent. Make sure your firewall (if any) allows connections over the port(s) you choose to use.

**Comment by deepsidhu1313** [comment]
@DavidGoll Thank You Sir!! For your valuable time and guidance.

**Comment by deepsidhu1313** [comment]
@DavidGoll  is there any api to get signal strength of network and wifi (in dbm's)??

**Comment by DavidGoll** [comment]
Sorry, that level of detail is not available for a UWP app.

**Comment by deepsidhu1313** [comment]
Thanks. There is one more thing when i try to run this code from my app. It says unauthorized exception thrown. But Sample app is executing same code smoothly. 

try
            { var modem = MobileBroadbandModem.GetDefault();
                IMEI = modem.DeviceInformation.MobileEquipmentId;
                MANUF = modem.DeviceInformation.Manufacturer;
                MODEL = modem.DeviceInformation.Model;
                Debug.WriteLine("Imei " + IMEI+" MANUF: "+MANUF+" MODEL: "+MODEL);
            } catch (Exception e) {
            }

Any Help ??

Still learning the way Windows app works. :smile:

**Comment by DavidGoll** [comment]
This functionality is only available to mobile operator apps and Windows Store apps given privileged access by mobile network operators. For more information, see [Mobile Broadband: Windows Store device apps](https://msdn.microsoft.com/en-us/library/windows/hardware/Dn247051.aspx).

**Comment by oldnewthing** [comment]
Please do not reuse issues for multiple unrelated problems. If you have a new problem, then create a new issue. Note also that the special prerequisites for `MobileBroadbandModem` are listed [in the sample's README](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/MobileBroadband).

**Comment by deepsidhu1313** [comment]
i am developing this app for Mobile operators, so how can i get the privilege ? @oldnewthing apologies . :)

**Comment by oldnewthing** [comment]
Please open a new issue. Your comments are off topic for this issue.

**Comment by deepsidhu1313** [comment]
Apologies and Thanks :)

**Comment by deepsidhu1313** [comment]
@DavidGoll Hey sorry to comment here again, but i'm facing a problem can you point me in right direction ??? Related to Ftp

https://stackoverflow.com/questions/32380715/c-sharp-ftp-upload-in-windows-10-universal-app

**Comment by DavidGoll** [comment]
Answered on StackOverflow.
