### ISSUE TITLE
QUESTION: Is it not possible to have a UWP app on a Windows 10 system log to the windows event log?

### ISSUE THREAD

**Issue by hooligan495** [microsoft/Windows-universal-samples#1185]
I'm currently using NLog in my UWP app to log to a file.  But I'd like to be able to log certain errors to the Windows Event Log.  Due to the sandboxing nature of UWP is this just not possible?

**Comment by oldnewthing** [comment]
This is a question about the OS itself, not about the samples. (There is a [Logging](https://github.com/microsoft/Windows-universal-samples/tree/master/Samples/Logging) sample for generating custom ETLs.)
