### ISSUE TITLE
Server is not working, but clients seems to be.

### ISSUE THREAD

**Issue by saramonteiro** [microsoft/Windows-universal-samples#1186]
Hi, 
I am trying the BLE samples. When trying the first client sample (Discover Servers), it successfully starts enumerating, but when I selected the Server sample the following message came up:

"There is no Bluetooth Device, or the default Bluetooth Device cannot act as a Bluetooth Server".

Can you help me figure out what is happening?

**Comment by oldnewthing** [comment]
This doesn't appear to be reporting a bug in the sample, but rather an issue with the platform.

You can go to the [UWP developer forums](https://docs.microsoft.com/answers/topics/uwp.html) or post your question to [StackOverflow](https://stackoverflow.com/) with the uwp tag.
