### ISSUE TITLE
CameraFaceDetection app min-size& max-size will exit on 19041 OS version(20H1)

### ISSUE THREAD

**Issue by lthemep** [microsoft/Windows-universal-samples#1188]
CameraFaceDetection app min-size& max-size will exit directly on 20H1, seems all camera app have same issue.

**Comment by oldnewthing** [comment]
Can you elaborate on what you mean? I don't understand what "CameraFaceDetection app min-size& max-size will exit directly on 20H1" means. Is it that if you resize the app to its minimum or maximum size, the app crashes? Or are you referring to the MinDetectableFaceSize and MaxDetectableFaceSize properties?
