### ISSUE TITLE
What Situation of 'Can not copy Closuer Class Field' ? 

### ISSUE THREAD

**Issue by LocketGoma** [microsoft/Windows-universal-samples#1190]
(Sorry using Translator and poor language.)

![주석 2020-04-21 191029](https://user-images.githubusercontent.com/16269328/79854132-f21d5b80-8403-11ea-921a-41b5d97be7a6.png)

'MoveLookController Class' In Simple3DGameDX Code package, 797 and 826 lines

That lines make error message :: (Maybe) "Can not copy "MoveLookController ^" Closure class field from "MoveLookController ^*" lambda capture variable. "

1. Why catch this error? is not Serious error?

2. Why Build Success even thought has (Compile level) Error?

Please Check and answer my questions. thanks.

**Comment by LocketGoma** [comment]
Property Option : 
1. Platform version : 10.0.1.18362.0
2. Windows Version : 1909
3. VS version : 2019 v142

**Comment by oldnewthing** [comment]
These are code analysis errors, not compiler errors. It looks like code analysis doesn't understand C++/CX. We are gradually converting our C++/CX samples to C++/WinRT to avoid this and other C++/CX issues.
