### ISSUE TITLE
Web authentication broker sample textbox error.

### ISSUE THREAD

**Issue by luiscalv** [microsoft/Windows-universal-samples#1192]
Web authentication broker cpp samples on both scenarios https://github.com/microsoft/Windows-universal-samples/tree/master/Samples/WebAuthenticationBroker/cpp:

1. Connect to Google Services
- App Client ID text box is not completely visible, you can't see what you are writing.
![image](https://user-images.githubusercontent.com/64035722/80147739-d1bae180-8568-11ea-8365-0268fd39e36b.png)

2. Connect to Facebook Services
- App ID text box is not completely visible, you can't see what you are writing.
- Site URL text box is not completely visible, you can't see what you are writing.
![image](https://user-images.githubusercontent.com/64035722/80147766-daabb300-8568-11ea-89fc-458c2b0833d5.png)

**Comment by oldnewthing** [comment]
Is this the C# version, the C++ version, or both?

**Comment by oldnewthing** [comment]
Fixed in next refresh.
