### ISSUE TITLE
BluetoothLEUniversal example(BluetoothLE) cannot run in win10-V1909

### ISSUE THREAD

**Issue by dvt0551** [microsoft/Windows-universal-samples#1193]
I CAN RUN IN VS2019 FOR THIS example but when release version can not run,no any message display,help me.

**Comment by oldnewthing** [comment]
I'm having trouble understanding this issue. I take it you are talking about the BluetoothLE sample, but it's not clear whether you are building Release x64 or Release x86. And what do you mean when you say that no message is displayed? Are you talking about messages displayed inside the VS output window? Or do you mean that no window is created for the app?

**Comment by dvt0551** [comment]
in vs2019 ，i can run this example，but when I issue debug or release execute-code，this execute-code cannot run （cannot display app-windows ，process abort）。help me。my windows versions is win-10 1909.
thank you very much。
tongliangyong
2020.04.30





发自我的iPhone


------------------ Original ------------------

**Comment by dvt0551** [comment]
I find I can start it in windows-menu，but cannot run in bin/release/BluetoothLEUniversal.exe,how run in command-line? thank you.

**Comment by oldnewthing** [comment]
Running UWP apps from the command line require [additional manifest entries](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap5-appexecutionalias). This doesn't appear to be a question about the sample itself any more. These samples were not designed for command line use.
