### ISSUE TITLE
Doesn't Even Compile -- Links are 404

### ISSUE THREAD

**Issue by 0x6c6565** [microsoft/Windows-universal-samples#1194]
Microsoft, so...

Your links on your own github landing page don't work.
Your project doesn't even compile and run in your own IDE for 2019.

These are the only micro$oft examples I can find by searching with your own search engine.

**Comment by oldnewthing** [comment]
It's just one person (me) running this repo. Please be specific which links don't work and which projects don't compile.

**Comment by 0x6c6565** [comment]
I guess then, @oldnewthing, that typing a response and then immediately closing the issue is much less than a productive solution, yes?

**Comment by 0x6c6565** [comment]
Here's one of your links that 404s @oldnewthing 
https://github.com/microsoft/Windows-universal-samples/tree/master/Samples/Simple3DGameDX

**Comment by 0x6c6565** [comment]
Possibly, @oldnewthing since you can see that your link doesn't work, the issue should be reopened, no?

**Comment by oldnewthing** [comment]
Link works fine for me.

![image](https://user-images.githubusercontent.com/12550607/80530995-b9730a00-894e-11ea-8397-55037e4cdb8e.png)

**Comment by oldnewthing** [comment]
(I closed the issue pending further information, with the expectation that you would reopen when you provided that information.)

**Comment by 0x6c6565** [comment]
The link is on that page that doesn't work:

https://docs.microsoft.com/en-us/windows/uwp/gaming/tutorial--create-your-first-metro-style-directx-game?redirectedfrom=MSDN

**Comment by 0x6c6565** [comment]
![image](https://user-images.githubusercontent.com/7025798/80531951-6a869e00-8969-11ea-8e5b-f7b6679291a4.png)

**Comment by oldnewthing** [comment]
Okay, now I see the broken link you're referring to. I'll see where it went to.

**Comment by oldnewthing** [comment]
A little web searching says that the page moved here: https://docs.microsoft.com/en-us/windows/uwp/gaming/tutorial--create-your-first-uwp-directx-game?view=vs-2019

**Comment by oldnewthing** [comment]
Fixed in next refresh.

**Comment by 0x6c6565** [comment]
Thank you, @oldnewthing
