### ISSUE TITLE
AudioGraph API FrameOutputNode

### ISSUE THREAD

**Issue by erksch** [microsoft/Windows-universal-samples#1196]
Hey there!

I was missing something in the examples for the Audio Graph API that is really important for me and I can't figure out how to do this.

When I connect an `AudioFileInputNode` with an `AudioFrameOutputNode`, I am able to the read frame data with this code:
```C#
AudioBuffer buffer = frame.LockBuffer(AudioBufferAccessMode.Read);
IMemoryBufferReference reference = buffer.CreateReference();
((IMemoryBufferByteAccess)reference).GetBuffer(out byte* dataInBytes, out uint capacityInBytes);
float* dataInFloats = (float*)dataInBytes;
```  
As I learned from [this stackoverflow answer](https://stackoverflow.com/a/35026378/8170620), the bytes that read into the buffer have to be considered as bytes of floats. But how do I get the actual byte data of a file that I opened with the graph from these floats?
 
For example, I read a WAV with PCM 16000Hz, 16 bit mono and the raw bytes of that wav are shorts:
```
0 0 | 255 255 | 254 255 | 255 255 | 255 255 | 254 255 | 253 255 | 252 255 ...
``` 
But the buffer of AudioFrameOutputNode reads the following bytes:
```
0 0 0 0 | 0 0 0 184 | 0 0 128 184 | 0 0 0 184 ...
```
which I assume are floats.
But the question is how do I get the actual raw shorts from these floats?
Is there some type of conversion I can use?
As you can see in the example, the sample `255 255` in shorts seems to map to sample `0 0 0 184` in float. What's the magic behind that?

**Comment by PeterSmithRedmond** [comment]
Have you tried using the DataReader? It's designed to convert buffers of bytes (and also streams) and read the values as floats, ints, and so on. Note that you should set the "endian" property to the needed value (network default is big endian, but some formats use little endian. And some, weirdly, use both)

**Comment by Zofware** [comment]
@erksch are you doing this in the context of a `IBasicAudioEffect`? If so, what happens if you change your `SupportedEncodingProperties` from `MediaEncodingSubtypes.Float` (as in [the example](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/custom-audio-effects#supportedencodingproperties-property)) to `MediaEncodingSubtypes.PCM` instead? I've only ever used floating-point samples in my audio effects but perhaps specifying PCM or another of the subtypes might work. Not sure.

**Comment by erksch** [comment]
@Zofware Nope, I am not using any effects. But I set the graph's and output node's encoding properties properly to PCM 16000Hz 16 Bit Mono like this:
```C#
var encoding = MediaEncodingProfile.CreateWav(AudioEncodingQuality.Auto);
encoding.Audio = AudioEncodingProperties.CreatePcm(16000, 1, 16);
var settings = new AudioGraphSettings(AudioRenderCategory.Speech);
settings.EncodingProperties = encoding.Audio;

var result = await AudioGraph.CreateAsync(settings);
var graph = result.Graph;

var localFolder = Windows.Storage.ApplicationData.Current.LocalFolder;
StorageFile file = await localFolder.GetFileAsync("my-16kHz-16bit-mono-audio.wav");
var fileInputNodeResult = await graph.CreateFileInputNodeAsync(file);
var fileInputNode = fileInputNodeResult.FileInputNode;

fileInputNode.FileCompleted += async (AudioFileInputNode sender, object args) => { graph.Stop(); };

frameOutputNode = graph.CreateFrameOutputNode(encoding.Audio);
fileInputNode.AddOutgoingConnection(frameOutputNode);
graph.QuantumStarted += AudioGraph_QuantumStarted;

graph.Start();
```

**Comment by erksch** [comment]
@PeterSmithRedmond I don't quite understand, how should I use the DataReader insight of the Quantum callback to convert floats to shorts? I know that I can easily read the shorts from the file itself  with a BinaryReader like this:
```C#
FileStream f = new FileStream(file, FileMode.Open);
BinaryReader br = new BinaryReader(f);
br.ReadBytes(44); // Skip bytes until the actual data starts
var shorts = new shorts[length];
for (int i = 0; i < length; i++) {
    shorts[i] = br.ReadInt16();
} 
```
But I specificly want to use the Audio Graph API for loading my file and providing me the bytes.

**Comment by erksch** [comment]
@PeterSmithRedmond But how would I use the DataReader class to read from the buffer? I see there is a method `DataReader.FromBuffer(IBuffer)`, but how do I convert an `Windows.Media.AudioBuffer` to an `Windows.Storage.Streams.IBuffer`. Can you provide example code?

**Comment by oldnewthing** [comment]
Buffer.CreateCopyFromMemoryBuffer will convert an IMemoryBuffer (which AudioBuffer implements) to a Buffer (which is an IBuffer). Not the most efficient way since it makes a copy. Why are you averse to using BitConverter.ToSingle?

**Comment by erksch** [comment]
I want to convert the floats to shorts, not the other way around.
The Audio Graph API reads samples as floats although they are actually shorts in the audio.

**Comment by oldnewthing** [comment]
The page you linked says "the data range for each sample is from -1 to 1", so presumably -1.0f corresponds to 0 and +1.0f corresponds to 65535.

**Comment by erksch** [comment]
Ah now I get it! It's just a scale conversion. Thank you so much.
But I have to say this is not really clear from the docs or the samples.

**Comment by oldnewthing** [comment]
The sample does show that [it's an array of floats](https://github.com/microsoft/Windows-universal-samples/blob/f7e40961bbbb2d61f20d6c5c1cf91fa9bc2b533b/Samples/AudioCreation/cs/CustomEffect/CustomEffect.cs#L95). If the original format wasn't an array of floats, then there is naturally a format conversion. The nature of the format conversion depends on the format. In your specific example, the conversion was linear. Other formats can be more complicated (such as u-law). It's really out of the scope of the documentation to show how to convert every possible format. You need to apply your understanding of the format. I guess the documentation could say "The buffer is in the form of an array of samples. Each sample is a series of IEEE single-precision floating point values in a linear range from `-1.0` to `+1.0`, one value per channel." It's then up to you to understand how your format converts to that format.

**Comment by BRB2000** [comment]
I have a question that is quite closely related to this one. I have connected an input node to a FrameOutputNode. Reading the data from the outputnode, I get values >1.0 / -1.0 . Is this to be expected when connecting a microphone to a FrameOutputNode, or is there an error in my code?
`            using (Windows.Media.AudioBuffer buffer = frame.LockBuffer(Windows.Media.AudioBufferAccessMode.Write))
            using (IMemoryBufferReference reference = buffer.CreateReference())
            {
                byte* dataInBytes;
                uint capacityInBytes;
                float* dataInFloat;

                // Get the buffer from the AudioFrame
                ((IMemoryBufferByteAccess)reference).GetBuffer(out dataInBytes, out capacityInBytes);
                int numBytes = (int)capacityInBytes;
                int numFloats = numBytes / sizeof(float);
                dataInFloat = (float*)dataInBytes;
                short[] pcm = new short[numFloats];
                for (int i = 0; i < numFloats; i ++)
                {
                    float sample = dataInFloat[i];
                    short convertedSample = Convert.ToInt16((65535 * sample - 1) / 2);
                    pcm[i] = convertedSample;
                }
            }
        }`

**Comment by Zofware** [comment]
If you're receiving `float` samples known to be in the range [-1.0f, 1.0f] inclusive, your conversion to `Int16` should probably be something like `Convert.ToInt16(sample * 32767.0f)`. That would give you signed integer sample values in the range [-32767, 32767] inclusive. If you're concerned about out-of-bounds input samples then you might need to add a clamp to limit the input range to +/-1.0f inclusive.

**Comment by BRB2000** [comment]
Thank you very much for your reply. Is there any guaranteed range of the floats coming out of the FrameOutputNode? If I configure Graph to use 16 bit samples like so:
`        private void CreateFrameOutputNode()
        {
              frameOutputNode = audioGraph.CreateFrameOutputNode(Windows.Media.MediaProperties.AudioEncodingProperties.CreatePcm(8000, 1, 16));
          //   frameOutputNode = audioGraph.CreateFrameOutputNode();
            audioGraph.QuantumStarted += AudioGraph_QuantumStarted;
        }`, that would mean that in general, a short should suffice to represent the sample, or am I missing something?

**Comment by BRB2000** [comment]
In other words: how do I know what range I get from my FrameOutputNode? I'm kinda lost on this one. Thank you very much in advance.

**Comment by Zofware** [comment]
I have limited experience here, but every audio graph I've ever set up seems to pass `float` samples around regardless of how I configure the encoding properties. Sorry I can't be of more help here!
