### ISSUE TITLE
SmartCard sample SmartCardReader.CardAdded is never called

### ISSUE THREAD

**Issue by jozefizso** [microsoft/Windows-universal-samples#1198]
When I want to use `CardAdded` event to detect when a SmartCard was inserted into the SC reader, UWP does not fire the event.

Sample code:

```cs
        private async void Page_Loaded(object sender, RoutedEventArgs e)
        {
            string selector = SmartCardReader.GetDeviceSelector();
            DeviceInformationCollection devices = await DeviceInformation.FindAllAsync(selector);

            foreach (DeviceInformation device in devices)
            {
                SmartCardReader reader = await SmartCardReader.FromIdAsync(device.Id);
                reader.CardAdded += Reader_CardAdded;
                reader.CardRemoved += Reader_CardRemoved;

                // retaining reader instances does not work either
                // retain.Add(reader);
            }

            ItemListView.ItemsSource = cardItems;
        }
```

**Comment by oldnewthing** [comment]
This code doesn't appear in any of the samples in this repo. It appears to be code in your own project. You can follow the instructions on [Windows developer support](https://developer.microsoft.com/en-us/windows/support/) for support options. (Click "Forums and community".)

**Comment by jozefizso** [comment]
Thanks for nothing. 🖕🖕🖕

**Comment by oldnewthing** [comment]
This is for filling issues about the samples in this repo. It is not a general developer support forum. See the links above for developer support options.
