### ISSUE TITLE
how to get rssi for LEbuletooth

### ISSUE THREAD

**Issue by dvt0551** [microsoft/Windows-universal-samples#1199]
I cannnot find api to get LEbluetooth, how to get ?

**Comment by oldnewthing** [comment]
This appears to be a question about the feature itself, not a question about the sample. You can follow the instructions on [Windows developer support](https://developer.microsoft.com/en-us/windows/support/) for support options. (Click "Forums and community".)

**Comment by oldnewthing** [comment]
(A little searching reveals [the BluetoothLEAdvertisementReceivedEventArgs.RawSignalStrengthInDBm property](https://docs.microsoft.com/en-us/uwp/api/Windows.Devices.Bluetooth.Advertisement.BluetoothLEAdvertisementReceivedEventArgs.RawSignalStrengthInDBm?view=winrt-18362). Note that I don't know anything about Bluetooth. I just did some searching. For support, please use the developer support channel.)

**Comment by dvt0551** [comment]
thank you



发自我的iPhone


------------------ Original ------------------
