### ISSUE TITLE
BackgroundAudio Sample Fail to play audio

### ISSUE THREAD

**Issue by cwesterlund** [Microsoft/Windows-universal-samples#12]
Can't play an audio file when running against Local Machine or Simulator.
Running against WP Emulator works though.

Failing in **StartBackgroundAudioTask** in **Scenario1.xaml.cs** on the following line:
```C#
bool result = backgroundAudioTaskStarted.WaitOne(10000);
```
The result is always false.

Running on Windows 10 Pro Insider Preview 10074 (Visual Studio 2015 RC)

**Comment by aarononeal** [comment]
Hi Christian, thanks for reporting this. I suspect it's due to an issue with the background task not starting up on x86 architectures in that Windows 10 build. Do you have an x64 machine you can target to confirm whether it works there?

**Comment by cwesterlund** [comment]
Hi Aaron, yes it works when I change target to x64. 
Thanks!

**Comment by cwesterlund** [comment]
Hi again Aaron, can't get my own project to work.
Not even on WP emulator. There is'nt an issue with the background task not starting up on VB.NET projects?

**Comment by aarononeal** [comment]
Great! Thanks for confirming x64 worked in the sample. Support for x86 on x64 is on the way.

Language shouldn't make a difference. Can you tell me more about your VB project configuration? Did you convert it to a Windows Universal project? Check also that you updated your Package.appxmanifest file to include the required task extensions.

```
      <Extensions>
        <Extension Category="windows.backgroundTasks" EntryPoint="BackgroundAudioTask.MyBackgroundAudioTask">
          <BackgroundTasks>
            <Task Type="audio" />
          </BackgroundTasks>
        </Extension>
      </Extensions>
```

**Comment by cwesterlund** [comment]
Created a Windows Universal Solution from scratch on 10.0.10030.0
I then installed Visual Studio 2015 RC and changed to 10.0.10069.0

When I debug the sample, I run it, put a breakpoint in CastsBackgroundAudioTask.Run method and suspend the app through Lifecycle Events which will put me in the Run method of the background task.
If I do the same in my project nothing happens when I suspend the App. The background task is never invoked.

Here are the Projects: 
CASTS_BACKGROUNDAUDIO (Windows Runtime Component)
Assembly name: CASTS_BACKGROUNDAUDIO
Default namespace: CASTS_BACKGROUNDAUDIO
Background task class: CastsBackgroundAudioTask

CASTS_UAP (APP)
Has reference to CASTS_BACKGROUNDAUDIO project
Package.appxmanifest:
```xml
<Extensions>
  <Extension Category="windows.backgroundTasks" EntryPoint="CASTS_BACKGROUNDAUDIO.CastsBackgroundAudioTask">
    <BackgroundTasks>
      <Task Type="audio" />
    </BackgroundTasks>
  </Extension>
</Extensions>
```

Don't know what can be the problem, I hade a Silverlight App previously which I could make work.
Thanks for the help!

**Comment by cwesterlund** [comment]
I created a new solution with only the basics, tried to suspend the app for it to break in the Run method but nothing. The solution is here: http://1drv.ms/1F8fGIV

**Comment by cwesterlund** [comment]
Strange, when I suspend the sample now it will not break in the Run method. 
What is triggering the Background task to Run?

**Comment by cwesterlund** [comment]
Got it to work!
Had to create a new solution and projects.
Don't know why it didn't work with my previous solution, I used the same code.

**Comment by aarononeal** [comment]
Yay! There may have been some project template changes between 10030 and 10069 that just creating a new project resolved. Glad to hear that worked for you!
