### ISSUE TITLE
Account removed with report App Security 10.2

### ISSUE THREAD

**Issue by tejaat1995** [microsoft/Windows-universal-samples#1204]
Hello All,

Can anyone help me with this? I tried to create a UWP application using BackgroundDownloader API and tried to publish. But My account got removed from Partner Center with report **App  Security 10.2** .

Not able to publish another new app. I am getting **Access Restricted** error.

Thanks in advance.

**Comment by oldnewthing** [comment]
This does not appear to be an issue with a sample in this repo. You can follow the instructions on [Windows developer support](https://developer.microsoft.com/en-us/windows/support/) for support options. (Click "Forums and community".)
