### ISSUE TITLE
Custom Windows.Gaming.Input IGameController/ICustomGameControllerFactory example

### ISSUE THREAD

**Issue by DJm00n** [microsoft/Windows-universal-samples#1205]
While [Windows.Gaming.Input.IGameController](https://docs.microsoft.com//uwp/api/windows.gaming.input.igamecontroller) docs says:

>This interface exists mainly to support extensibility for game controllers, which allows OEMs (Original Equipment Manufacturers) to publish WinRT (Windows Runtime) classes that provide rich access to their device's features, while integrating into the underlying game controller device enumeration framework

I see no real example of such custom game controller. Specifically I interested in custom HID controller example that could create HID vibration reports even if device is not announcing vibration via its HID descriptor (common case). Haptics just cannot be used with `RawGameController` in this case.

C++/WinRT is preferred. :)

**Comment by DJm00n** [comment]
I checked Sony DualShock 4 and Google Stadia controllers - they just `RawGameController.SimpleHapticsControllers` and `RawGameController.ForceFeedbackMotors` are just empty in these cases. :(

**Comment by oldnewthing** [comment]
This appears to be a question about how the feature is implemented in the operating system, not a question about a sample in this repo. You can follow the instructions on [Windows developer support](https://developer.microsoft.com/en-us/windows/support/) for support options. (Click "Forums and community".)

**Comment by DJm00n** [comment]
I thought that for such cases I need to implement a custom `Windows.Gaming.Input IGameController`/`ICustomGameControllerFactory`. Isn't it?

**Comment by oldnewthing** [comment]
You're asking the wrong team. This is the samples team. We support the samples, not the operating system.
