### ISSUE TITLE
Deploy Samples on Windows 10 iot

### ISSUE THREAD

**Issue by Laslous** [Microsoft/Windows-universal-samples#121]
Hi Guys and thank you for all this samples.
Is it possible to deploy this samples on windows 10 iot since they are UWP applications?
I try to do it (Splashscreen app) on PI2 but i have this error:

	Error : DEP0700 : Registration of the app failed. Windows cannot install package Microsoft.SDKSamples.SplashScreen.CS because this package depends on another package that could not be found. This package requires minimum version 1.0.0.0 of framework Microsoft.NET.Native.RunTime.1.0 published by CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US to install. Provide the framework along with this package. (0x80073cf3)	SplashScreen		

Thank you for your help

**Comment by bfjelds** [comment]
UWP applications should work on Windows 10 IoT with a few caveats:

* APIs that are implemented in the Desktop or Mobile extensions will generate ClassNotFoundExceptions
* There are some APIs that haven't been implemented yet on IoT (for details, see http://ms-iot.github.io/content/en-US/win10/UnavailableApis.htm)

In the SplashScreen sample, it looks like you can enable yourself for IoT by removing this line from Package.appxmanifest:

    <PackageDependency Name="Microsoft.NET.Native.RunTime.1.0" MinVersion="1.0.0.0" Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US" />

For more details about IoT, check out: https://dev.windows.com/en-us/iot
