### ISSUE TITLE
DisplayOrientation UWP sample doesn't work on Surface Book unless I'm in Tablet Mode

### ISSUE THREAD

**Issue by Tam66662** [microsoft/Windows-universal-samples#1212]
I have a Surface Book, running Windows 10 version 1909 (Build 18363).  When I downloaded and installed the [DisplayOrientation](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/DisplayOrientation) UWP sample, it would not lock the orientation unless I was in Tablet mode.

No where in the documentation does it say that this sample only runs in Tablet mode.  Is this a bug, or is this just missing info from the sample?

Any help would be greatly appreciated.

**Comment by oldnewthing** [comment]
I have asked the feature team to investigate.

**Comment by oldnewthing** [comment]
Feature team confirms that orientation locking is not respected in overlapped mode. The orientation properties are all suggestions, and the OS can apply its own rules to when those suggestions are honored.
