### ISSUE TITLE
SMS send and receive sample does not work

### ISSUE THREAD

**Issue by hatasum** [Microsoft/Windows-universal-samples#122]
The sample seems not work.
I have try to create a metadata and privilege this sample app, but it also not work. 
Error still is : Access is Denied
Is there someone have the same experience?

**Comment by swatika** [comment]
Is this issue happening on desktop or phone? Does your device is developer unlocked?
https://msdn.microsoft.com/library/windows/apps/xaml/dn706236.aspx

**Comment by hatasum** [comment]
Hi, thanks for your reply.
The test is on desktop, and developer mode is enable.

**Comment by swatika** [comment]
For new SMS APIs, you don't need metadata. It is based on restricted capability model. Can you confirm that your mobile broadband device is plugged in? Also, can you tell me which API is throwing access denied?

**Comment by hatasum** [comment]
Hi Swatika,
In SendTextMessage.xaml.cs :
device = SmsDevice2.GetDefault();
It will throw :"Access is denied".
And the mobile broadband device is indeed plugged in because it is success to connect internet.

**Comment by swatika** [comment]
Can you check that in your package appx manifest ""cellularMessaging" capability is defined?

**Comment by hatasum** [comment]
Do you mean <r:Capability Name="cellularMessaging" />?
I try to change <uap:Capability Name="cellularMessaging" />, but it can't build success.
It isn't defined on namespace "uap", is it right?

**Comment by hatasum** [comment]
After windows update and reboot, the sample is working and success to send message.
I think maybe have some hotfix to lucky solve the issue. I will check it later.
Thanks for your help.
