### ISSUE TITLE
Python example for CreateAsync(Guid) method usage in GattServiceProvider Namespace

### ISSUE THREAD

**Issue by pbvinoth** [microsoft/Windows-universal-samples#1222]
We are using the python/winrt module to interact with windows runtime apis. We want to create the gatt service using the Windows.Devices.Bluetooth.GenericAttributeProfile Namespace, we have method called createAsync which will create the gatt service below is the example usage that we are using.

import winrt.windows.devices.bluetooth.genericattributeprofile as wdbgatt

result = await gatt_service.create_async(uuid.uuid1())

The create_async method will be taking guid as argument.
when we are running the code we are receiving error as "NotImplemented".

Could someone help me to resolve the issue?

**Comment by oldnewthing** [comment]
This appears to be a question about the feature itself, not a question about the sample. You can follow the instructions on [Windows developer support](https://developer.microsoft.com/en-us/windows/support/) for support options. (Click "Forums and community".)
