### ISSUE TITLE
XamlDragAndDrop not dropping

### ISSUE THREAD

**Issue by Jockey4her** [microsoft/Windows-universal-samples#1224]
I used the blank UWP template in Visual Studio and tried to Allow Drop on the main grid, added an event handler to Drop and ran it.  It never fired... (yes I used a background color) So I tried your master-sample example here and it did not fire either.  

Some events fire like DragStart, but not DragCompleted, or Drop.

What's the deal? I need to write an app and drop a bunch of files on it and grab their names and all that as fileArgs.

**Comment by oldnewthing** [comment]
I just re-ran the XamlDragDrop sample and all three scenarios seem to be working. Breakpoints on `Scenario1_ListView.TargetListView_Drop`, `Scenario2_DragUICustomization.TargetTextBox_Drop`, and `Scenario3_StartDragAsync.DropBorder_Drop` are all hit when the item is dropped.

If you continue to encounter problems with the sample, please be more specific what is not working.
