### ISSUE TITLE
Missing sample for Windows.ApplicationModel.Lockscreen API

### ISSUE THREAD

**Issue by RatikKapoor** [microsoft/Windows-universal-samples#1228]
Hi, firstly thank you for maintaining this repo. I used it very frequently when I was initially learning UWP and still reference back to it often. There is a requirement for the app I am developing to be able to run complex functionality before user logon and without the context of a user. Our entire solution is in UWP as we heavily depend on some WinRT components. It seems Windows.ApplicationModel.Lockscreen is ideal for our use however it's not well documented anywhere and I couldn't find any samples. I think the addition of a sample for this API would be greatly beneficial. 

I can see from #726 and #239 that this was requested a while back as well but I couldn't find anything in the repo. Any help here would be greatly appreciate and thank you for your time!

**Comment by oldnewthing** [comment]
These APIs are not available for general use, so they are not covered by this repo, sorry. (And they won't help you in your case anyway. Lock screens are for when a user is logged on and the screen is locked. If nobody is logged on, then you have the Logon screen, not a Lock Screen.)

**Comment by RatikKapoor** [comment]
Great, thanks for clarifying that difference! I will look into other solutions then! Thank you!
