### ISSUE TITLE
BluetoothLEDevice.FromIdAsync must be run on the UI thread.

### ISSUE THREAD

**Issue by JonathanNorton** [microsoft/Windows-universal-samples#1236]
https://github.com/microsoft/Windows-universal-samples/blob/a58c5d9b84456196889edb1f4a6e844c7a729b8b/Samples/BluetoothLE/cs/Scenario2_Client.xaml.cs#L103-L113

Is there any guarantee that BluetoothLEDevice.FromIdAsync() on line 113 is being executed on the  UI thread? I see there there is an await call on line 103 that could move execution off the UI thread. Acording to the comment on line 112, BluetoothLEDevice.FromIdAsync() must be called on the UI thread; I, however, dont see any mention of this in the official documention for that method:

https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.bluetoothledevice.fromidasync?view=winrt-19041#Windows_Devices_Bluetooth_BluetoothLEDevice_FromIdAsync_System_String_

**Comment by JonathanNorton** [comment]
I've found the documentation that confirms that FromIdAsync must be run on the ui thread:
https://docs.microsoft.com/en-gb/windows/uwp/devices-sensors/gatt-client

**Comment by oldnewthing** [comment]
In C#, the await statement resumes in the same UI context. Since this is a Click handler, line 103 starts on the UI thread. And since await preserves UI context, the await ends on the UI thread as well. I'll add documentation notes about the UI thread requirement.

**Comment by cay7man** [comment]
Is this true for CustomDevice as well? FromIdAsync when called from a BackgroundTask appears to timeout.  If it is not a limitation, any logs that might be helpful to understand the root cause?
