### ISSUE TITLE
It's not possible to have two GattServiceProviders in the same application

### ISSUE THREAD

**Issue by buildYourOwnGolfSimulator** [microsoft/Windows-universal-samples#1241]
Only the first one advertised can be connected to.
I create two different GattServiceProviders, with several characteristics each, and calls StartAdvertising for both.
Using LightBlue on my phone I can see both services, and their characteristics (even though only the first characteristic will show the "User Description" I have specified for it, so another bug there). Only the service published first can be connected to. I tried this by just reversing the order they are advertised.
This is on a Win10 machine, Intel NUC Skull Canyon.

**Comment by oldnewthing** [comment]
This appears to be an issue with your own program, not with the sample program in this repo. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
