### ISSUE TITLE
BluetoothLEAdvertisementPublisher not working at all

### ISSUE THREAD

**Issue by buildYourOwnGolfSimulator** [microsoft/Windows-universal-samples#1242]
I've tried that sample and it doesn't report any issues, but there is just not anything seen from e.g. LightBlue.
I can use GattServiceProvider on the other hand. This is on a Win10, Intel NUC Skull Canyon machine.
I would prefer if it would work since it's the only place where a LocalName can be specified. GattServiceProvider uses the NetBIOS/DnsHostName and can't be changed. I would prefer having the Computer Name since it keeps casing and isn't truncated.

**Comment by oldnewthing** [comment]
I've asked the feature team to determine whether this is a bug in the sample or a bug in the platform. (If it's a bug in the platform, then it's not a sample issue.)

**Comment by mtbeaver** [comment]
Two things:
1. First, advertising the Local Name is not allowed via the BluetoothLEAdvertisementPublisher to prevent confusing the pairing process on various platforms.  An exception should have been thrown when you attempted to Start the publisher, so I am curious what version of Windows you are running this.
2. On the topic of the GattServiceProvider, it does not actually use the NetBIOS/DNS name, but rather the result from IOCTL_BTH_GET_LOCAL_INFO.  This allows the Settings page to be consistent with the name we advertise over LE and BR/EDR.  The name can be configured though.  One way is to open Device Manager, Right Click on the Bluetooth Radio, select the Advanced Tab, and choose a new name in the text box.  You will need to restart the system for this to take effect globally.  Afterwards, the system will be discoverable with that new name when using the GattServiceProvider.
