### ISSUE TITLE
Basic Media Casting not working on HoloLens

### ISSUE THREAD

**Issue by travelhawk** [microsoft/Windows-universal-samples#1243]
I tried to use the media casting on the HoloLens. When I call the api I get the following Exception:

"MiracastTest.exe" (CoreCLR: CoreCLR_UWP_Domain):
Ausnahme ausgelöst: "System.Exception" in Assembly-CSharp.dll
The request is not supported. (Exception from HRESULT: 0x80070032)

**Comment by oldnewthing** [comment]
There is no sample in this repo called MiracastTest that I can find. This appears to be a problem with a program that you wrote, not a sample in this repo. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.

**Comment by travelhawk** [comment]
As mentioned, I called the media casting api from Windows.Media.Casting (same as the "BasicMediaCasting" sample). The program I wrote is a minimal test program. It's definitely not a specific problem, but a generic problem. All calls to Windows.Media.Casting are FAILING(!) when I deploy it to the **HoloLens**.

I should have shared the code with you:
`
using System;
using UnityEngine;
using Windows.Devices.Enumeration;
using Windows.Media.Casting;

public class MiracastConnector : MonoBehaviour {

    private DeviceWatcher watcher;

    void Start() {
        string filter = CastingDevice.GetDeviceSelector(CastingPlaybackTypes.Video); // Exception: Request not supported!!!!
        watcher = DeviceInformation.CreateWatcher(filter);
        watcher.Added += OnWatcherAdded;
        watcher.Start();
    }

    private void OnWatcherAdded(DeviceWatcher sender, DeviceInformation deviceInfo)
    {
        CastingDevice device = await CastingDevice.FromIdAsync(deviceInfo.Id); // Exception: Request not supported!!!
        CastingConnection connection = device.CreateCastingConnection();
        connection.ErrorOccurred += OnConnectionErrorOccurred;
        connection.StateChanged += OnConnectionStateChanged;     
    }

}
`

**Comment by oldnewthing** [comment]
Since this is a generic problem, it is not a samples issue.
