### ISSUE TITLE
Arguments called in wrong order

### ISSUE THREAD

**Issue by mattark** [microsoft/Windows-universal-samples#1247]
**Which sample are you reporting a bug in?**

SimpleCommunications

**Describe the bug**

Problem with line of code in CaptureDevice,cs.

CaptureDevice.StartRecordingAsync calls a StspMediaSinkProxy method 'InitializeAsync' with parameters in the wrong order.

As presented, line is: var mfExtension = await mediaSink.InitializeAsync(encodingProfile.Audio, encodingProfile.Video);
Should be: var mfExtension = await mediaSink.InitializeAsync(encodingProfile.Video, encodingProfile.Audio);

**To Reproduce**

Code actually works as presented, but I think it takes longer to Initialize.  

**Expected behavior**

**Screenshots**

**Configuration**

* Language/architecture/flavor: (example: C++/WinRT x64 Debug)
* Windows platform and build number: (example: Desktop build 18362.)

* Visual Studio version: (example: 16.6.5; get this value from Help.About.)

**Additional context**

**Comment by oldnewthing** [comment]
This is just a typo in the header file. The implementation and callers all use Video/Audio. But the prototype in the header has them swapped. The code is actually correct, which is why it works as presented. I'll fix the header.

**Comment by oldnewthing** [comment]
Fixed in v10.0.3
