### ISSUE TITLE
folder enumeration ignores files with long path/file names

### ISSUE THREAD

**Issue by imthewiseguy** [microsoft/Windows-universal-samples#1248]
I wrote a program that enumerates music files by album

`var folder = KnownFolders.MusicLibrary;
                StorageFolderQueryResult queryResult =
        folder.CreateFolderQuery(CommonFolderQuery.GroupByAlbum);
                IReadOnlyList<StorageFolder> folderList =
        await queryResult.GetFoldersAsync();
//folderItem is the album folder
                foreach (var folderItem in folderList)
                {GetSongs(folderitem)`

`ObservableCollection<Song> songs = new ObservableCollection<Song>();
            var files = await folderItem.GetFilesAsync();`

One "album folder has two mp3 files in the folder but "files.Count" reported only 1. I went into Windows Explorer and shortened the file name (from "C:\Users\Admin\Music\Amazon Music\Joji\Nectar [Explicit]\11 – Pretty Boy (feat. Lil Yachty)[Explicit].mp3" to "11 - Pretty Boy") and ran the code again, and this time the app recognized the file and reported that "files.Count = 2."

Is there a file name length or file path length limitation in the Windows.Storage API?

**Comment by oldnewthing** [comment]
This appears to be a question about the OS itself, not a question about a sample in this repo. You can follow the instructions on [Windows developer support](https://developer.microsoft.com/en-us/windows/support/) for support options. (Click "Forums and community".)
