### ISSUE TITLE
XamlBind sample binds slider that can go to 0 to FontSize, crashes

### ISSUE THREAD

**Issue by MattGal** [Microsoft/Windows-universal-samples#125]
See Samples\XamlBind\cs\OtherBindings.xaml, possibly other places.

This has 

    <Slider Grid.Row="1" Grid.Column="1" Value="{x:Bind Model.IntPropertyDP, Mode=TwoWay, Converter={StaticResource IntToDouble}}" Minimum="0" Maximum="100" />

but also 

    <TextBlock Grid.Row="3" Text="Text and FontSize are both bound"/>
    <TextBlock Grid.Row="3" Grid.Column="1" Text="{x:Bind LocalTextBox.Text, Mode=OneWay}" FontSize="{x:Bind Model.IntPropWithINPC, Mode=OneWay}" />

... meaning whenever users slide the slider to the left, the app crashes. 

Can either fix this quick and dirty (make the slider's value never be 0) or write a special "minimum value" converter that sets a value to a specific value (say 1) if it drops too low (say, 0).

**Comment by oldnewthing** [comment]
Thanks for the fix. You should see it in [the most recent update](https://github.com/Microsoft/Windows-universal-samples/releases/tag/v1.0.3).
