### ISSUE TITLE
UWP SerialDevice Unpredictable Read Behavior

### ISSUE THREAD

**Issue by DChirico** [microsoft/Windows-universal-samples#1251]
(reposted)
The UWP SerialDevice class currently only allows you to set "ReadTimeout", which under the hood, sets the
"ReadIntervalTimeout" of the actual serial device ([](https://docs.microsoft.com/enus/windows/desktop/api/winbase/ns-winbase-_commtimeouts)). There are two other timeout values which dramatically affect the read operations behavior: 
1) ReadTotalTimeoutMultiplier 
2) ReadTotalTimeoutConstant.

The UWP SerialDevice class does not allow the user to set these two other read timeout values, and even
worse, the UWP SerialDevice class does not set these two other timeout values to known values when the
serial device is opened. This means that the two other timeout values will be whatever default value the serial
driver uses, or worse still, whatever value some serial port application happened to set these two values to be
when the other application was last executed.

The overall effect of this is that your UWP application's serial device read behavior is undefined and cannot
reliably be used. For example, if these two other timeout values happen to be set one way, then a read
operation may block forever waiting on the first byte of data to be read, but if the other timeout values
happen to be set a different way, then the read operation may return immediately, with no data read at all.
Currently, a UWP application cannot control this behavior, and the behavior will be different across different
serial ports, and even perhaps different every time the UWP application is executed.
The UWP SerialDevice class either needs to
1. Allow the user to set these two other read timeout values (preferred), OR
2. Initialize these two other timeout values to known values when the serial device is opened.

**Comment by oldnewthing** [comment]
This appears to be a feature request for the OS itself, not a feature request fort the sample. This sounds like a feature request suitable for the Project Reunion project, which is about bringing UWP and Win32 APIs closer together.
