### ISSUE TITLE
It is 2020 and MicrosoftPassport (aka) Hello samples are 2015 - Good luck!

### ISSUE THREAD

**Issue by laultman** [microsoft/Windows-universal-samples#1252]
MicrosoftPassport. 

Example: ResizeAppView

**Describe the bug**
Simple, samples don't work out of the box. Takes hours just to get it to build.

**To Reproduce**
Download, extract, open in VS 2019 16.7.5

**Expected behavior**
Would have expected something that works and actually demonstrates using modern cloud authentication. When I saw the code I didn't expect anything.

**Screenshots**

**Configuration**

* Language/architecture/flavor: (example: C++/WinRT x64 Debug)
* Windows platform and build number: (example: Desktop build 18362.)

* Visual Studio version: (example: 16.6.5; get this value from Help.About.)

**Additional context**

**Comment by oldnewthing** [comment]
I can't repro. I loaded up the MicrosoftPassport sample into VS 2019 16.7.4. Pressed Ctrl+Shift+B. Seven seconds later, built completed. Hit F5, sample is running.

![image](https://user-images.githubusercontent.com/12550607/95699100-7654dc80-0bf8-11eb-95b8-93966a67710b.png)

Please provide more details of your configuration.
