### ISSUE TITLE
Washed out colors when transcoding from BT.601 color profile

### ISSUE THREAD

**Issue by tahnik** [microsoft/Windows-universal-samples#1257]
**Which sample are you reporting a bug in?**

Example: MediaTranscoding

**Describe the bug**
When converting a video which has a color profile of BT.601, the converted video has a washed out color like the following:

![image](https://user-images.githubusercontent.com/9964210/97487950-7f161400-1955-11eb-9004-a6bd473a8845.png)

**To Reproduce**
Open the example in Visual studio. Select a mp4 file that has a color profile of BT.601. Click transcode.

**Expected behavior**
The transcoded video should have the correct colors

**Screenshots**
Added above.

* Language/architecture/flavor: UWP
* Windows platform and build number: 19041.572

* Visual Studio version: 16.7.6

**Additional context**
Here is the mediainfo of the file that I am transcoding:

```
Video
ID                          : 1
Format                      : AVC
Format/Info                 : Advanced Video Codec
Format profile              : High@L5.2
Format settings             : CABAC / 3 Ref Frames
Format settings, CABAC      : Yes
Format settings, Reference  : 3 frames
Format settings, GOP        : M=1, N=30
Codec ID                    : avc1
Codec ID/Info               : Advanced Video Coding
Duration                    : 17 s 601 ms
Bit rate                    : 44.2 Mb/s
Width                       : 3 440 pixels
Height                      : 1 440 pixels
Display aspect ratio        : 2.40:1
Frame rate mode             : Variable
Frame rate                  : 60.000 FPS
Minimum frame rate          : 57.107 FPS
Maximum frame rate          : 64.562 FPS
Standard                    : PAL
Color space                 : YUV
Chroma subsampling          : 4:2:0
Bit depth                   : 8 bits
Scan type                   : Progressive
Bits/(Pixel*Frame)          : 0.149
Stream size                 : 92.7 MiB (100%)
Title                       : VideoHandle
Encoded date                : UTC 2020-10-22 19:35:24
Tagged date                 : UTC 2020-10-22 19:35:24
Color range                 : Limited
Color primaries             : BT.601 NTSC
Transfer characteristics    : BT.470 System M
Matrix coefficients         : BT.601
mdhd_Duration               : 17601
Codec configuration box     : avcC
```

**Comment by tahnik** [comment]
Looks like it could be a similar issue to this: https://stackoverflow.com/questions/55220280/washed-out-colors-color-range-issue-with-amd-h264-encoder-mft. So I have tried the following in the app:

```
profile.Video.Properties[Guid.Parse("3e23d450-2c75-4d25-a00e-b91670d12327")] = 2;
```

Essentially setting `MF_MT_YUV_MATRIX` to `MFVideoTransferMatrix_BT601`. But it did not make a difference.

**Comment by oldnewthing** [comment]
This appears to be a question about the feature itself, not a question about the sample. You can follow the instructions on [Windows developer support](https://developer.microsoft.com/en-us/windows/support/) for support options. (Click "Forums and community".)
