### ISSUE TITLE
The UWP API Package.InstalledLocation.Path takes too much time on Windows 10.19041.572

### ISSUE THREAD

**Issue by sfoslund** [microsoft/Windows-universal-samples#1258]
---
**Issue moved from dotnet/sdk#14335**
- Please respond to @mingtong.

---

_From @mingtong on Tuesday, October 27, 2020 3:23:27 AM_

OS version: 2004,
build number: 19041.572

When I call this API on one of the mentioned Windows 10, it takes about 4~5 seconds.
But it doesn't reproduce on my own Windows 10(same build same version).

Any one have ran into this issue?

**Comment by sfoslund** [comment]
Not sure if this is the correct repo or not, please help redirect if not.

**Comment by oldnewthing** [comment]
This appears to be a question about the feature itself, not a question about the sample. You can follow the instructions on [Windows developer support](https://developer.microsoft.com/en-us/windows/support/) for support options. (Click "Forums and community".)
