### ISSUE TITLE
MapControl sample crashes at startup

### ISSUE THREAD

**Issue by mattiferg** [microsoft/Windows-universal-samples#1259]
This is the map control sample.
Commit hash 1ad51db378ef34fb35078e3ddd4cf94cb717d6eb
No changes from committed source.
Visual Studio 2019 v16.7.3
Windows 10 build 18363.1198

The app, built in debug mode starts and then immediately the app crashes. There is an option to attach a debugger, but it fails to connect to anything.

I suspect this might be a problem with the mapping control, since if I remove it from the Xaml then I can launch the app without this issue.

The Windows log reports the following:-

Faulting application name: MapControlSample.exe, version: 1.0.0.0, time stamp: 0x5bb6a248
Faulting module name: ucrtbase.dll, version: 10.0.18362.1110, time stamp: 0xb4cacc38
Exception code: 0xc0000409
Fault offset: 0x000000000006dace
Faulting process ID: 0x3a98
Faulting application start time: 0x01d6bcca61154993
Faulting application path: C:\Development\OSS\Github\Microsoft\Windows-universal-samples\Samples\MapControl\cs\bin\x64\Debug\AppX\MapControlSample.exe
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
Report ID: f0fc79e9-e723-4923-a894-3ae7b4a83bd1
Faulting package full name: Microsoft.SDKSamples.MapControlSample.CS_1.0.0.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App

**Comment by Kaliumhexacyanoferrat** [comment]
This seems to be a general issue with the `MapControl`. The following minimal UWP example will reproduce the crash:

```
<Page
    x:Class="MapCrash.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:maps="using:Windows.UI.Xaml.Controls.Maps">

    <maps:MapControl />

</Page>
```

The issue does not occur if we are in airplane mode, so this seems to be related to the response sent by the Microsoft servers. Is there a bug tracker for the UWP component itself that we can use?

**Comment by BobbyCannon** [comment]
This is a HUGE problem for me and my company. Our app which has been stable for months is now crashing on startup. We really need someone on this ASAP.

**Comment by BobbyCannon** [comment]
// Works
await Map.TrySetViewAsync(new Geopoint(location));

// All these fails if I try to use any overload on TrySetViewAsync
await Map.TrySetViewAsync(new Geopoint(location), request.View.Zoom);
await Map.TrySetViewAsync(new Geopoint(location, AltitudeReferenceSystem.Terrain), request.View.Zoom, request.View.CameraHeading, request.View.CameraPitch, request.Animation);

I also get the issue when manually zooming the app
![image](https://user-images.githubusercontent.com/840590/99400774-65615000-28b5-11eb-9c4e-e0d4ed264103.png)

**Comment by BobbyCannon** [comment]
I have verified that going offline the MapControl will not exception. I also noticed that going offline allows everything to work but the moment you come back online the MapControl will exception.

**Comment by oldnewthing** [comment]
This appears to be a question about the feature itself, not a question about the sample. You can follow the instructions on [Windows developer support](https://developer.microsoft.com/en-us/windows/support/) for support options. (Click "Forums and community".)

(I will informally alert the feature team, but going through developer support will make sure the issue is tracked.)

**Comment by BobbyCannon** [comment]
See also https://github.com/microsoft/microsoft-ui-xaml/issues/3614

**Comment by oldnewthing** [comment]
Team has informed me that the issue has been fixed on the server.
