### ISSUE TITLE
SplashScreen sample doesn't work

### ISSUE THREAD

**Issue by shinsenai** [Microsoft/Windows-universal-samples#126]
The SplashScreen sample doesn't seem to work, the extended splash images are not placed in the right position and do not have the right size, on a PC/tablet the image blows up to cover the entire screen. There seem to be something wrong with the use of Viewbox (rather than Canvas as it was in W81) and there seem to be some logical errors, for example in ExtendedSplash.xaml.cs lines 82-83 the Viewbox.HeightProperty is set twice and the values used to set it don't seem correct (why X and Y? They are not the size of the SplashScreen Rect object). I've tried to modify it, but the Viewbox always acts funny. Of course it can be just me not understanding how Viewbox works, sorry for that. It works with Canvas, though.

**Comment by shinsenai** [comment]
Hi, I've proposed some modifications with Pull Request #134. Cheers.

**Comment by oldnewthing** [comment]
Thanks for the fix. You should see it in [the most recent update](https://github.com/Microsoft/Windows-universal-samples/releases/tag/v1.0.3).
