### ISSUE TITLE
Credential picker Unity3D HoloLens

### ISSUE THREAD

**Issue by mehdikhadir** [microsoft/Windows-universal-samples#1266]
Hello,

First of all sorry if this is not the right type of ticket. I would like to thank you for the different samples and their documentation, they are really helpful to me.

I would like to know if it's possible and if so how I could call 
Windows.Security.Credentials.UI.CredentialPicker.PickAsync(credPickerOptions);
from a Unity3D application.

I have tried to run the Credential picker sample Visual Studio solution on a HoloLens 2 and it worked fine, popping up the credential picker. Then I've tried to use that code inside "#if ENABLE_WINMD_SUPPORT" tags in my Unity project but couldn't make it work. I have tried to use Unity 2019.4.11f1 with IL2CPP scripting backend and Unity 2018.4.21 with .NET as scripting backend, but none of these worked. I either get "Exception of type 'System.Exception' was thrown." or "Element not found. (Exception from HRESULT: 0x80070490)" when calling CredentialPicker.PickAsync(credPickerOptions).

Is what I am trying to do even possible? I have seen in this documentation that something similar could be possible with Unity but don't really know how to achieve this: https://docs.microsoft.com/en-us/hololens/hololens-identity#enterprise-and-other-authentication

Thanks in advance for your help!

Best,
Mehdi

**Comment by oldnewthing** [comment]
This appears to be a question about the OS itself, not a question about the sample. You can follow the instructions on [Windows developer support](https://developer.microsoft.com/en-us/windows/support/) for support options. (Click "Forums and community".)
