### ISSUE TITLE
Dotnet cli template

### ISSUE THREAD

**Issue by jcbritobr** [microsoft/Windows-universal-samples#1267]
There is a problematic issue for people who uses visual studio core build new applications using dotne cli (as dotnet core or dotnet 5) and dont want to use visual studio. I think we need a template to use in cli like ```dotnet new uwp```

**Comment by oldnewthing** [comment]
The samples require Visual Studio. You are welcome to read the sample source code without Visual Studio, but the projects are intended to build in Visual Studio. You are of course welcome to use whatever IDE you wish for your own programs.
