### ISSUE TITLE
Is there any way to run UWP apps in MAC and Linux ?

### ISSUE THREAD

**Issue by ayankumaar** [microsoft/Windows-universal-samples#1271]
I am planning to develop a cross platform app written using UWP. I know it will run fine in Windows 10. Is it possible to run it in MAC and Linux ?

**Comment by pekatete** [comment]
https://platform.uno/

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by oldnewthing** [comment]
This is not a question about any of the samples in this repo.
