### ISSUE TITLE
Publisher Cache Folder

### ISSUE THREAD

**Issue by JuandreG** [microsoft/Windows-universal-samples#1273]
How would I navigate the WebView to a html page that is in a Publisher Cache folder?

I would like to share this html file across multiple UWP applications with the same publisher so this is probably where one would put the file but I don't know the Uri that points to that folder. If I use the path to the page in the Publisher Cache folder then I get some HRESULT exception with no details as to why it failed.

Help would be greatly appreciated.

**Comment by oldnewthing** [comment]
This appears to be a question about the feature itself, not a question about the sample. You can follow the instructions on [Windows developer support](https://developer.microsoft.com/en-us/windows/support/) for support options. (Click "Forums and community".)

(I don't know if this is the best way, but one way is to create a stream from the file, and then navigate to the stream.)
