### ISSUE TITLE
Input field (appears to be in blackstripes when typing) on System keyboard

### ISSUE THREAD

**Issue by Nag13arjun** [microsoft/Windows-universal-samples#1274]
Hello,

I am new to the UWP application. I have scenario of adding input field in immersive view for an application. 

Which sample are you reporting a bug in?
CustomEditControl

Describe the bug
Black stripe appears on the input field on the system keyboard, when trying to give input to the textbox.
Can be clearly seen in the image.

Expected behavior
Input text field should display the letters typed in on the system keyboard

Screenshots
![Bug](https://user-images.githubusercontent.com/46887361/106117640-836bec00-6153-11eb-8f03-4f0a83e2125a.PNG)

Configuration

* Language/architecture/flavor: C# (in the actual application I want it work on winrt/c++)
* Windows platform and build number: Desktop build 18362
* Visual Studio version:16.8.4

Additional context
Any suggestions to set input text field without focus elements would be much appreciated (idea was to use the textfield on the system keyboard itself as input field but i am sure if it's possible).

**Comment by oldnewthing** [comment]
This appears to be a question about the OS-provided keyboard, not the sample. You can follow the instructions on [Windows developer support](https://developer.microsoft.com/en-us/windows/support/) for support options. (Click "Forums and community".)
