### ISSUE TITLE
Single File Picker reading the selected file as stream 

### ISSUE THREAD

**Issue by jan-tosovsky-cz** [microsoft/Windows-universal-samples#1278]
**Which sample are you requesting a feature to be added to?**

FilePicker: update current Single File Picker so it actually access the file content

**Describe the feature**
The current [example](https://github.com/microsoft/Windows-universal-samples/blob/master/Samples/FilePicker/cs/Scenario1_SingleFile.xaml.cs) states the picked file has read/write access, but it is not tested as just file name is used:
```
// Application now has read/write access to the picked file
OutputTextBlock.Text = "Picked photo: " + file.Name;
```
However, when using direct access I am getting famous `UnauthorizedAccessException`:
```
using (FileStream fileStream = new FileStream(file.Path, FileMode.Open))
```
That exception is thrown regardless the file location: in Downloads, Documents or arbitrary folder on C:\ drive.
I suppose there is something what needs to be tweaked, but it is not clear from the original example.

**Comment by oldnewthing** [comment]
The FileAccess sample shows how to read from a file. See Scenario 5.
