### ISSUE TITLE
Default ActivitySensor returning null

### ISSUE THREAD

**Issue by igrali** [Microsoft/Windows-universal-samples#128]
Default ActivitySensor is returning null on devices that previously supported SensorCore, such as Lumia 630 (on latest build, 10512). 

    await ActivitySensor.GetDefaultAsync();

Why is that happening? I can see in Motion settings that the motion data is turned on and the Activity Sensor C# Sample is registered to access motion (and is allowed to do so).

Thanks!

**Comment by micche** [comment]
Hi Igrali,

ActivitySensor is not supported on the Lumia 630 going forward. Please look out for the upcoming updates to the emulator to provide support of ActivitySensor and Pedometer!

Please let us know if you have any questions.

Thanks!
-Michael
