### ISSUE TITLE
DeviceWatcher not firing events reliably

### ISSUE THREAD

**Issue by BRB2000** [microsoft/Windows-universal-samples#1283]
**Which sample are you reporting a bug in?**

DeviceEnumerationAndPairing

**Describe the bug**
The DeviceWatcher is not updating correctly in some cases in the example. If "all" is cosen in section 2 (device watcher), certain HID-Devices are not registered. Sometimes, even storage devices are not recognized as well. There seems to be a huge inconsistency. I came across this, as on my development machine, the device watcher for a manufacturer-defined hid device works fine, but when remote-debugging the app, no event is risen by the device watcher after the first enumeration is complete, even though I've subscribed to every single event it offeres ;)

**To Reproduce**
Run the example and plug in / unplug different devices while having "all" selected for the device watcher. This should already yield inconsistent results.

**Expected behavior**
Devicewatcher should reflect all changes reliably.

**Screenshots**

**Configuration**

* Language/architecture/flavor: C# UWP
* Windows platform and build number: Windows 10 Pro 20H2 19042.867 x86-64
* Visual Studio version: Microsoft Visual Studio Community 2019 Version 16.9.1

**Comment by oldnewthing** [comment]
This appears to be a question about the feature itself, not a question about the sample. You can follow the instructions on [Windows developer support](https://developer.microsoft.com/en-us/windows/support/) for support options. (Click "Forums and community".)
