### ISSUE TITLE
Missing App.xaml.cs and Mainpage.xaml.cs in SpeechRecognitionAndSynthesis sample

### ISSUE THREAD

**Issue by ali-h2010** [microsoft/Windows-universal-samples#1289]
**Which sample are you reporting a bug in?**

SpeechRecognitionAndSynthesis

**Describe the bug**
Missing App.xaml.cs and Mainpage.xaml.cs in SpeechRecognitionAndSynthesis sample. The files are not in repository and VS complain about them missing once i load the solution from the cs folder.

**To Reproduce**
1. Download the solution or check the repo in GitHub
2. load the solution in VS 2019

**Expected behavior**
Solution should load all required files but there are files missing "MainPage.cs" and "App.cs"

**Comment by ali-h2010** [comment]
Apparently, i should have downloaded the whole repo to get the shared files instead of downloading a specific sample

**Comment by oldnewthing** [comment]
Yup. Right at the top of the README. You don't have to download the whole repo. There is also a premade zip that contains everything needed for just this sample. See first link below.

> **Note:** This sample is part of a large collection of UWP feature samples. You can download this sample as a standalone ZIP file [from docs.microsoft.com](https://docs.microsoft.com/samples/microsoft/windows-universal-samples/speechrecognitionandsynthesis/), or you can download the entire collection as a single [ZIP file](https://github.com/Microsoft/Windows-universal-samples/archive/master.zip), but be sure to unzip everything to access shared dependencies. For more info on working with the ZIP file, the samples collection, and GitHub, see [Get the UWP samples from GitHub](https://aka.ms/ovu2uq). For more samples, see the [Samples portal](https://aka.ms/winsamples) on the Windows Dev Center.
