### ISSUE TITLE
Emterprisedataprotection sample code not working

### ISSUE THREAD

**Issue by wtam** [Microsoft/Windows-universal-samples#129]
The restricted capability of the enterprise policy seems   not recognized.

**Comment by oldnewthing** [comment]
I've asked the feature team to investigate.

**Comment by oldnewthing** [comment]
Having the restricted capability is just one prerequisite for the EnterpriseDataProtection sample. You also have to [deploy an enterprise policy that lists the sample as a "privileged app"](https://technet.microsoft.com/en-us/library/dn985838%28v=vs.85%29.aspx).
