### ISSUE TITLE
BluetoothAdvertisement - unable to get advertised value/message

### ISSUE THREAD

**Issue by Fabricio-Valerio** [microsoft/Windows-universal-samples#1290]
**Which sample are you reporting a bug in?**

BluetoothAdvertisement

**Describe the bug**
I'm advertising a message(string) using an ESP32, but I'm unable to read the characteristic value using eventArgs.Advertisement.DataSections and eventArgs.Advertisement.ManufacturerData. My message seems to never be received.

**To Reproduce**
1. Advertise a characteristic using any example of ESP 32 BLE Arduino
2. Try to get the data (value) of the characteristic using BluetoothAdvertisement
3. Check that the message or value isn't present in BluetoothLEAdvertisementReceivedEventArgs 

**Expected behavior**
The message or value being present in BluetoothLEAdvertisementReceivedEventArgs, so it can be retrieved by the application and used in the C# program

**Configuration**

* Language/architecture/flavor: (example: C#/Windows10 x64 Debug)

* Visual Studio version: 19

**Comment by oldnewthing** [comment]
This appears to be a question about the feature itself, not a question about the sample. You can follow the instructions on [Windows developer support](https://developer.microsoft.com/en-us/windows/support/) for support options. (Click "Forums and community".)
