### ISSUE TITLE
How to properly disconnect bluetooth device?

### ISSUE THREAD

**Issue by JanNepras** [microsoft/Windows-universal-samples#1292]
**Which sample are you reporting a bug in?**

Example: BluetoothLE

**Describe the bug**
I have an issue with disconnecting bluetooth device. I can successfully connect to device and then write value to characteristic. This works fine and it was tested. When I disconnect the bluetooth device the connection is still active. 

To disconnect bluetooth device I followed this method in sample project:
https://github.com/microsoft/Windows-universal-samples/blob/b1cb20f191d3fd99ce89df50c5b7d1a6e2382c01/Samples/BluetoothLE/cs/Scenario2_Client.xaml.cs#L78

Plus I dispose all services:

```
var services = await bluetoothLeDevice.GetGattServicesAsync();
foreach(var service in services.Services)
{
   service?.Session?.Dispose();
   service?.Dispose();
}
```

Could you tell what I have to do in order to close the connection? Or could you please update the sample project? Thank you.

**To Reproduce**
1. Connect bluetooth button in the sample project
2. Disconnect the device

**Expected behavior**
The bluetooth device should be disconnected between the app.

**Screenshots**
NA

**Configuration**

* Language/architecture/flavor: C#
* Windows platform and build number: build 16299

**Additional context**
[Similar stackoverflow post.](https://stackoverflow.com/questions/47702584/bluetooth-le-device-cannot-disconnect-in-win-10-iot-uwp-application)

**Comment by JanNepras** [comment]
I am also adding the code how I do write to characteristic:

```
bluetoothLeDevice = await BluetoothLEDevice.FromIdAsync(rootPage.SelectedBleDeviceId);
var services = await bluetoothLeDevice.GetGattServicesAsync();
var service = services.Services.Where(s => s.Uuid.Equals(VSNGattServiceGuid)).First();
var characteristics = await service.GetCharacteristicsAsync();
var characteristic = characteristics.Characteristics.Where(ch => ch.Uuid.Equals(VerificationCharacteristicGuid)).First();

var writer = new DataWriter();

writer.WriteByte(0x80);
writer.WriteByte(0xBE);
writer.WriteByte(0xF5);
writer.WriteByte(0xAC);
writer.WriteByte(0xFF);

await characteristic.WriteValueAsync(writer.DetachBuffer());
```

Do you have to do something special to dispose write characteristic? If so could you please update sample and documentation for [all of these](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.genericattributeprofile.gattcharacteristicproperties?view=winrt-19041)?

**Comment by angela-yan** [comment]
Null the Characteristics list (Unsubscribe if necessary)
Dispose Service.
Null the Service
Dispose BluetoothLEDevice
Null BluetoothLEDevice

**Comment by lapaz17** [comment]
Any progress in this issue? I'm trying the same thing.

**Comment by aboutZZ** [comment]
Any updates?

**Comment by oldnewthing** [comment]
It looks like you're reporting a problem in your own app, not in the sample. The feature teams do not monitor the samples repos for OS questions. You can follow the instructions on [Windows developer support](https://developer.microsoft.com/en-us/windows/support/) for support options. (Click "Microsoft Q&A".)
