### ISSUE TITLE
Windows 10 version 1909, 2004, 20H2 cannot connect to paired BLE Gatt Server on Android Tablet

### ISSUE THREAD

**Issue by angela-yan** [microsoft/Windows-universal-samples#1293]
**Which sample are you reporting a bug in?**

Bluetooth LE Explorer

**Describe the bug**
We have a project that creates a WPF application to pair and communicate with a BLE Gatt Server on an Android tablet. This BLE Gatt Server will create custom BLE Service with custom BLE Characteristics. We found that on Win 10 version 1809 (OS Build 17763), there is no issue. But from Win 10 version 1909 (OS Build 18363) onwards (version 1909, 2004, 20H2), the same WPF application is not able to, or is very difficult to even connect to the same BLE Gatt Server on the Android tablet.

And we actually observe the exact same issue with Microsoft’s own application and Android sample application as well.

**To Reproduce**
**Test System:**

1. Windows 10 laptops: Version 1809, 1909, 2004, 20H2
2. Android tablet Samsung Galaxy Tab S7 (SM-T870). Android version 11. Security patch level: 1 April 2021 or 1 March 2021, OR
Android tablet Samsung Galaxy Tab S6 Lite. Android version 11. Security patch level: 1 March 2021, OR
Huawei Matepad Pro (MRX-W29). Android version 10. Security patch level: 1 March 2021
 

**Test setup:**

1. Download Bluetooth LE Explorer from Windows store on Win 10 system version 1809 and Win 10 system version 1909.
2. Download the attached sample Android BLE Gatt server APK to the Android tablet. Or you can build using the sample Gatt Server source code from here https://github.com/androidthings/sample-bluetooth-le-gattserver.
 

**Steps to repro:**

1. Ensure Wifi and Bluetooth are turned on the Samsung Tablet and Window 10 laptop.
2. Install attached APK on the Samsung Tablet.
3. Pair the Android device with Windows using Windows Bluetooth Setting page, wait for ‘Device is ready’ prompt to be displayed by Windows.
4. Launch Bluetooth LE Explorer on Windows and click ‘Start’ button.
5. Wait for the device enumeration to finish, or click 'Stop' once the Android tablet is shown, and click on the Samsung device to connect to it.

**Expected behavior**
- Expect LE Explorer is able to successfully connect to device and display all the Servers and Characteristic and Characteristic values

**Actual behavior**
- On Win 10 system version 1809 (Build 17763) :
Bluetooth LE Explorer is able to successfully connect to device and display all the Servers and Characteristic and Characteristic values
![1809 BLE Explorer can connect to Android tablet](https://user-images.githubusercontent.com/67552681/117798128-6337e700-b283-11eb-9c4e-60b23748457a.png)
- On Win 10 system version 1909 (Build 18363), 2004 (Build 19041), 20H2(Build 19042):
Bluetooth LE Explorer is stuck at the ‘Connecting’ page (we waited for 6 mins and it still get stuck), OR unable to connect and show ‘Device unreachable’ error.
![1909 BLE Explorer stuck at connecting page](https://user-images.githubusercontent.com/67552681/117798258-88c4f080-b283-11eb-9f67-c4d2515a568d.png)
![1909 BLE Explorer unable to connect and show Device Unreachable error](https://user-images.githubusercontent.com/67552681/117798272-8d89a480-b283-11eb-86bb-e6a365fec35e.png)

**Configuration**

* Language/architecture/flavor: (example: WPF/UWP x64 Debug)
* Windows platform and build number: (example: Windows 10 Laptop build 18363, 19041, 19042.)
* Visual Studio version: (example: 16.9.0)

**Microsoft APIs used:**
Similar to Bluetooth LE Explorer, our WPF app is also using BLE WinRT APIs from [here](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/gatt-client) (through the help of [Microsoft.Windows.SDK.Contracts](https://www.nuget.org/packages/Microsoft.Windows.SDK.Contracts/10.0.19041.1) Nuget package). Upon debugging, we found that on Win 10 version 1909, the following APIs will either never return the result to the application (hence the stuck on ‘Connecting’ page for Bluetooth LE Explorer), or returns “Device Unreachable” error or “No communication is allowed” error. 
[BluetoothLEDevice.GetGattServicesAsync](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.bluetoothledevice.getgattservicesasync?view=winrt-19041)
[GattDeviceService.GetCharacteristicsAsync](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.genericattributeprofile.gattdeviceservice.getcharacteristicsasync?view=winrt-19041)
[GattCharacteristic.ReadValueAsync](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.genericattributeprofile.gattcharacteristic.readvalueasync?view=winrt-19041)

The same API errors have been observed on Bluetooth LE Explorer as well when we download the Bluetooth LE Explorer Source code from MSDN gallery.

**Additional context**
1.    We already tried the registry method [here](https://social.msdn.microsoft.com/Forums/en-US/58da3fdb-a0e1-4161-8af3-778b6839f4e1/bluetooth-bluetoothledevicefromidasync-does-not-complete-on-10015063?forum=wdk) but it doesn’t help.
2.	For almost all the BLE APIs in MSDN documentation, it seems like the API only claim support for Win 10 version 1809 (Build 17763), and version 2004 (Build 19041). There is no mentioning of version 2004 (Build 18363) and version 20H2 (Build 19042). Is this intended? It would means that those APIs are not supported on version 2004 and 20H2 platform?
https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.bluetoothledevice.getgattservicesasync?view=winrt-19041
![temp](https://user-images.githubusercontent.com/67552681/117799827-1f45e180-b285-11eb-9ae6-0c5eb033d3bd.jpg)

4 Bluetooth ETL trace using WPR is attached. Traces are capture from Win 1809 and 1909, using BLE Explorer + Simple Gatt Server, and our own WPF App + own Android APK respectively.
[BT Trace.zip](https://github.com/microsoft/Windows-universal-samples/files/6458533/BT.Trace.zip)

Sample Android Simple Gatt Server APK used in the test
[simple-gatt-server-encrypted.zip](https://github.com/microsoft/Windows-universal-samples/files/6458554/simple-gatt-server-encrypted.zip)

**Comment by oldnewthing** [comment]
This appears to be a question about the feature itself, not a question about the sample. You can follow the instructions on [Windows developer support](https://developer.microsoft.com/en-us/windows/support/) for support options. (Click "Forums and community".)
