### ISSUE TITLE
winrt cpp Iot-Gpio  Scenario2_Listen.cpp  line 55 missing  valueChangedEventToken = listenPin.ValueChanged(.....);

### ISSUE THREAD

**Issue by Hoenscher** [microsoft/Windows-universal-samples#1294]
**Which sample are you reporting a bug in?**

IoT-GPIO

**Describe the bug**
At [line 55 of Scenario2_Listen.cpp](https://github.com/microsoft/Windows-universal-samples/blob/f7bec1640bc2b773f02f102d13c12c04833a6c0e/Samples/IoT-GPIO/cppwinrt/Scenario2_Listen.cpp#L55), the ValueChanged event token is not saved, even though it is used later to unregister. Should be assigned to `valueChangedEventToken`.

**Configuration**

* C++/WinRT all configurations

**Comment by oldnewthing** [comment]
Fixed in v10.0.3
