### ISSUE TITLE
BluetoothLEAdvertisementPublisher not able to set BluetoothLEAdvertisement.Flags

### ISSUE THREAD

**Issue by si-moon** [microsoft/Windows-universal-samples#1296]
It is not possible to use the setter of the BluetoothLEAdvertisement.Flags to set important advertising flags when using the BluetoothLEAdvertisementPublisher for advertising.
This limits the function for using devices for custom advertising scenarios.

Would be nice if there is a hint or if the implementation would function properly for the Publisher role. 

https://docs.microsoft.com/de-de/uwp/api/windows.devices.bluetooth.advertisement.bluetoothleadvertisement.flags

**Comment by alvaroyecla** [comment]
Any update on this?

**Comment by oldnewthing** [comment]
This appears to be a question about the feature itself, not a question about the sample. You can follow the instructions on [Windows developer support](https://developer.microsoft.com/en-us/windows/support/) for support options. (Click "Forums and community".)
