### ISSUE TITLE
BluetoothLE: Concurrent connection not working 

### ISSUE THREAD

**Issue by amiramin476** [microsoft/Windows-universal-samples#1297]
Hi,

Starting from BluetoothLE sample, I am trying to create a simple application which can simultaneous connect to multiple BLE devices (in-house) from Windows application. We had it working in the older UWP application few years ago. However, I am unable to get is working now. I created simple application with 2 buttons where clicking each button tries to connect to a BLE device with a specific MAC address (MAC known for our test devices).

The test application using following two APIs:
```
var bleDevice = BluetoothLEDevice.FromBluetoothAddressAsync
bleDevice.GetGattServicesAsync
```

Above API works fine for the first device only. And bleDevice.GetGattServicesAsync retrun 'Unreachable'

**Connection 1:**
17:50:02.2 -> 90:fd:9f:6e:14:81 	Disconnected 	Allowed 	BluetoothLE#BluetoothLE48:a4:72:5c:37:f7-90:fd:9f:6e:14:81
17:50:02.5 -> 90:fd:9f:6e:14:81 bleDevice.GetGattServicesAsync gattResult Success
service uuid: 00001801-0000-1000-8000-00805f9b34fb
service uuid: 00001800-0000-1000-8000-00805f9b34fb
service uuid: 0000180a-0000-1000-8000-00805f9b34fb
service uuid: 1175491a-c1db-40b1-93a2-243ab94d343e

**Connection 2 (2 seconds later than 1st)**
17:50:04.3 -> 90:fd:9f:4c:b0:c6 	Disconnected 	Allowed 	BluetoothLE#BluetoothLE48:a4:72:5c:37:f7-90:fd:9f:4c:b0:c6
17:50:12.0 -> 90:fd:9f:4c:b0:c6 bleDevice.GetGattServicesAsync gattResult Unreachable

Rarely simultaneous connections do work but they don't most of the time. 
[MainPage.xaml.cs.txt](https://github.com/microsoft/Windows-universal-samples/files/6570307/MainPage.xaml.cs.txt)

Am I missing some configuration or this functionality isn't supported anymore. I have attached the source code file (changed extension to txt to allow the attachment)

Thanks

**Comment by oldnewthing** [comment]
This appears to be a question about the feature itself, not a question about the sample. You can follow the instructions on [Windows developer support](https://developer.microsoft.com/en-us/windows/support/) for support options. (Click "Forums and community".)
