### ISSUE TITLE
 sample

### ISSUE THREAD

**Issue by amir4zh** [microsoft/Windows-universal-samples#1298]
**Which sample are you reporting a bug in?**

Example: ResizeAppView

**Describe the bug**
Include links to specific lines of code where you think the bug is.
(Click the line number, then click the "..." and select "Copy permalink.")
If not sure, at least include a link to the scenario where the problem is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Configuration**

* Language/architecture/flavor: (example: C++/WinRT x64 Debug)
* Windows platform and build number: (example: Desktop build 18362.)

* Visual Studio version: (example: 16.6.5; get this value from Help.About.)

**Additional context**

**Comment by oldnewthing** [comment]
Template not filled out.
