### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by amir4zh** [microsoft/Windows-universal-samples#1299]
**Which sample are you requesting a feature to be added to?**

Example: ResizeAppView (or say "New sample" to suggest a new sample)

Note that this is for suggesting a new sample or suggesting an update to an existing sample. To request features to be added to the operating system, use [Feedback Hub]( https://aka.ms/feedback-hub/support).

**Describe the feature**
A clear and concise description of the desired feature to be demonstrated by a sample.

Example: Show how to use the MapElementsLayer class to organize elements into layers on the MapControl.

**Comment by oldnewthing** [comment]
Template not filled out.
