### ISSUE TITLE
Documentation for SerialArduino sample is missing

### ISSUE THREAD

**Issue by TheRealBard** [microsoft/Windows-universal-samples#1303]
**Which sample are you requesting a feature to be added to?**

SerialArduino

Note that this is for suggesting a new sample or suggesting an update to an existing sample. To request features to be added to the operating system, use [Feedback Hub]( https://aka.ms/feedback-hub/support).

**Describe the feature**
The author of this Windows code sample needs to provide documentation about the functionality.  Because there isn't any here.  This code was written for some specific device which communicates using a serial port called an Arduino apparently, but if someone wanted to use Windows to communicate to one of the 100Billion other serial microcontrollers in the universe, it might be a good starting point?

The code should explain what it does.  "This app opens some serial port X, and expect to here this string.. Y, and then it responds with Z.  

Windows SDKs are supposed to be generic examples with many uses. not some single use, single device, single OS, with no documentation brick.  Its like they wrote if for their kid's class and somehow it got approved to be in an SDK master sample...

**Comment by oldnewthing** [comment]
As it says in the README, the SerialArduino sample is specifically for communicating with an Arduino device. It's a special-purpose sample for a very popular hobbyist device. For general serial communication, use the CustomSerialDeviceAccess sample.,
