### ISSUE TITLE
Broken links on Readme

### ISSUE THREAD

**Issue by CasualCoder** [microsoft/Windows-universal-samples#1304]
This links to download the entire 'Samples' project as a ZIP file are returning a 404.

![image](https://user-images.githubusercontent.com/3767445/124344515-0834c780-dc16-11eb-80a0-5f20aeeb5b9f.png)

**Comment by Sudouble** [comment]
The download link is still not working right now. Hope this will be fixed soon.

**Comment by oldnewthing** [comment]
Thanks. Fix going out today.
