### ISSUE TITLE
Drag and Drop not working in WP 10 emulator

### ISSUE THREAD

**Issue by gcoleman0828** [Microsoft/Windows-universal-samples#131]
Tried getting this sample to work in the Windows phone 10 emulator and it acts as if it does not know any drag events. it just highlights the text or list items. Should this work on the phone too?

**Comment by oldnewthing** [comment]
I checked with the feature team. Phone support for drag and drop is not yet as strong as desktop. The functionality is basically the same as on Windows 8.1: You can drag/drop items within a listview, and any UI element can be a drop target, but you don't get dragging to another process or drag customization.

**Comment by gcoleman0828** [comment]
Interesting. Do you know if there will be support for this in the future? It seems like something that would be a great feature add to compete with animations in IPhone and the like. Also, do you know of any examples out there that I can use that demonstrates what drag-ability exists for the phone? None of the ones in your example work at all. Including the list view. I have tried a few in the past that say they work, but don't.

**Comment by oldnewthing** [comment]
We hope to bring full drag/drop support to Phone eventually, but it's not there yet. I don't know why the Windows 8.1 drag/drop features are not working. Will check with the feature team.

**Comment by oldnewthing** [comment]
Okay, by experimenting, I found that I can do drag/drop in the listview. You have to press and hold on the item for a while, and then it becomes draggable.

**Comment by gcoleman0828** [comment]
Weird. Ok I'll have try that tomorrow. Is there a timer to it or something? Maybe a different event? This is really something I'm asked about a bit from customers  in regards to my apps and the windows phone in general why drag and drop isn't used more. If it doesn't work well, that is probably why. Hopefully this works because it has been frustrating to get this working. You would think if you can do it on a WP live tile, it should be able to be done in apps as well.

**Comment by oldnewthing** [comment]
Note that you have to press and hold on WP live tiles too, before you can go into drag/drop mode.

**Comment by samschiferl** [comment]
Thank you for your feedback on this issue regarding the drag and drop events on the Windows 10 emulator. As Raymond mentioned at this time we don't support a full-fledged drag and drop feature for Windows 10. However, Windows 10 does continue to support the Windows Phone 8.1 drag and drop feature. Thanks again for your comment, I will now consider this issue closed.

**Comment by gcoleman0828** [comment]
Sam, Thank you. Sorry for the delay, but I was just wondering if there is a future for supporting Phone dragging

**Comment by samschiferl** [comment]
We have been actively discussing it for a future release, however we don't have a specific timetable for when it would be added. Your feedback is helpful for us to make prioritization decisions - please keep it coming!

**Comment by abdu292** [comment]
Any update on this? The drag & drop (especially scenario 2) appears to be critical for my project at the moment. However the samples are still not working on Phone device and Phone emulators (though all are working well on desktop).
Could you help us with this functionality on Phone devices at the earliest? Thanks a ton.

**Comment by robppug** [comment]
I think this issue should be re-opened as it still does not work!

https://social.msdn.microsoft.com/Forums/en-US/2df672ed-865c-42a9-a77e-ad8bdfa518fe/uwpfall-creators-update-drag-and-drop?forum=WindowsIoT#1515c916-1b60-4559-87fc-268877dc2ea7
