### ISSUE TITLE
Miracast projection and switch to second screen only - sample

### ISSUE THREAD

**Issue by TorstenKannler** [microsoft/Windows-universal-samples#1310]
Hi there,
under Win 10 I would like to use the projection function programmatically.
**My goal is to establish a connection with a Miracast adapter out of an UWP APP 
and then switch to the "second monitor only" with my entire desktop.**
Manually processing these steps works fine and should be the desired result.

I m dealing with projection example and use
await ProjectionManager.StartProjectingAsync (...)

But this does not seem to be the correct approach.

_Can you provide a new sample to demonstrate how to archieve my goal?_

Thanks in advance,
Torsten

**Comment by oldnewthing** [comment]
I don't believe UWP apps can switch to "second monitor only" configuration. You can follow the instructions on [Windows developer support](https://developer.microsoft.com/en-us/windows/support/) for support options, maybe see if other people have ideas. (Click "Forums and community".)
