### ISSUE TITLE
Receiving a message tht is more than 20 bytes

### ISSUE THREAD

**Issue by rgjkeizer** [microsoft/Windows-universal-samples#1312]
I am using the BluetoohLE sample. There I found out that this example only has a receive buffer of 20 bytes.

But the message that I am expecting is 34 bytes long. So when I check the receive buffer It only consistits of the last 14 bytes. Because I saw tht the buffer.capacity is 20.

Is there any way to increase the receive buffer?

I can't change how the message gets send from the client.

**Comment by oldnewthing** [comment]
This appears to be a question about the feature itself, not a question about the sample. You can follow the instructions on [Windows developer support](https://developer.microsoft.com/en-us/windows/support/) for support options. (Click "Forums and community".)
