### ISSUE TITLE
 Not getting notification during enable/disable the airplane mode (Radio Sate change)using C++/Winrt

### ISSUE THREAD

**Issue by priyankajigalur** [microsoft/Windows-universal-samples#1313]
```
void Radio_StateChanged(Radio const& sender,
                        winrt::Windows::Foundation::IInspectable const& args) {
    printf("\t Radio_StateChanged \n");
}
    
void radio_register_function() {
	IVectorView<MobileBroadbandRadioStateChange> RadioStateChanges();
	auto radio = Radio::GetRadiosAsync().get();
	for (Radio const& r : radio) {
		if (r.Kind() == RadioKind::Bluetooth)
		{
			r.StateChanged(&Radio_StateChanged);
			if (r.State() == RadioState::Off)
			{				
				r.SetStateAsync(RadioState::On);
				break;
			}
			else if (r.State()==RadioState::On)
			{
				r.SetStateAsync(RadioState::Off);
				break;
			}
		}	
	}
}

```
I'm not getting notification when I try to enable/disable the airplane mode (Radio Sate change) using windows setting. Will I get the async notification  whenever it changes it's radio state. Is r.SetStateAsync() should be called in order to call r.StateChanged(). Can anyone please suggest where I'm going wrong so that I'll get the notification whenever radio state is changed. I'm writing the code using C++/WinRT

**Comment by oldnewthing** [comment]
This is not a question about the RadioManager sample in this repo. You can get help by following these steps:
 
1. Visit https://developer.microsoft.com/en-us/windows/support/
2. Under the “Forum & community" section, look under "UWP apps & games" or "Desktop applications", depending on which type of app you are writing, for support options.
