### ISSUE TITLE
PenHapics CppWinRT causes Windows to Blue Screen

### ISSUE THREAD

**Issue by techjogger** [microsoft/Windows-universal-samples#1316]
The CppWinRT PenHaptics  sample causes Windows to Blue Screen on 21H1

In addition, the C# PenHaptics Sample crashes on startup following the same instructions. 

**To Reproduce**
1. Change minium SDK to 10.0.18362.0 
2. Install on device running 21H1
3. Tap randomly with Stylus

**Comment by oldnewthing** [comment]
The sample requires new APIs in 22000, so lowering the minimum SDK to 18362 will result in an app that crashes. This is called out in the README:

> # System requirements
>
> **Client**: Windows 11

**Comment by techjogger** [comment]
Where is the best place to report that an API is crashing Windows?

**Comment by techjogger** [comment]
Ok great! Thanks for the help

Cheers,
Miles
________________________________
