### ISSUE TITLE
Buffer size

### ISSUE THREAD

**Issue by rgjkeizer** [microsoft/Windows-universal-samples#1318]
I am using the BluetoothLE repository but i am running into a problem.

Is it possible to increase the size of the receive buffer? it size now is 20 bytes long. But when i receive data longer than 20 bytes then the array gets cleared and overwritten.

Anybody a solution for this problem

**Comment by oldnewthing** [comment]
Can you be specific which sample you are reporting a bug in? Also, it sounds like you are trying to add a feature to the sample (making the receive buffer bigger), not reporting a bug. I'll close for now, but reopen when you provide additional information.
