### ISSUE TITLE
WiFiDirect has references to missing files (cppwinrt)

### ISSUE THREAD

**Issue by TheMrJukes** [microsoft/Windows-universal-samples#1319]
**Which sample are you reporting a bug in?**

WiFiDirect

**Describe the bug**
The cppwinrt project references "..\shared\ConnectionSettingsPanel.xaml" "..\shared\Scenario1_Advertiser.xaml" and "..\shared\Scenario1_Connector.xaml" but those files don't exist.

**To Reproduce**
Open cppwinrt\WiFiDirect.sln
Try to compile

**Expected behavior**
It compiles

**Additional context**
Copying the .xaml files from the cs directory to a new shared directory works

**Comment by oldnewthing** [comment]
Fixed in v10.0.3
