### ISSUE TITLE
Missing file: ImageContentTask.props

### ISSUE THREAD

**Issue by TooManyDots** [microsoft/Windows-universal-samples#1320]
**Which sample are you reporting a bug in?**
Simple3DGameDX

**Describe the bug**
Trying to compile I get:
error MSB4019: The imported project "C:\Common7\IDE\Extensions\Microsoft\VsGraphics\ImageContentTask.props" was not found.

**To Reproduce**
1. Click Build > Build Solution.

**Expected behavior**
A compiling program and that all required files are bundled in the zip.

**Screenshots**
![image](https://user-images.githubusercontent.com/35289254/137303849-c3cc23df-42aa-405f-912f-16b7f556719f.png)

**Configuration**
x64
Microsoft Visual Studio Community 2019 Version 16.8.3

**Comment by oldnewthing** [comment]
Thanks. Fix is available in ad9a0c4def222aaf044e51f8ee0939911cb58471 v13.0.4

**Comment by oldnewthing** [comment]
Oops, wrong issue.

**Comment by oldnewthing** [comment]
The error is coming from this line.

```xml
<Import Project="$(VSINSTALLDIR)\Common7\IDE\Extensions\Microsoft\VsGraphics\ImageContentTask.props" /> 
```

From the error output, it appears that your `VSINSTALLDIR` is `C:`. I doubt, however, that you installed VS into the root directory. This looks like a VS configuration error.

**Comment by halflifefan** [comment]
Not sure if it's reasonable to reopen this but I have the same problem on DWriteColorGlyph. I tried defining VSINSTALLDIR manually, but there wasn't even an output directory, and some other error popped up...
