### ISSUE TITLE
AudioGraph Frequency HELP

### ISSUE THREAD

**Issue by ArturRod** [microsoft/Windows-universal-samples#1322]
Hello, I am new to this, I am trying to get the frequency that is heard through the myrophone in a thread but I do not get this frequency.
I am applying the method:
![imagen](https://user-images.githubusercontent.com/86238895/139699498-794d777c-dff1-4597-8cfa-ee4043120372.png)

It's for a music project, any idea how to get the frequency in hertz?

**Comment by oldnewthing** [comment]
This appears to be a question about the feature itself, not a question about the sample. You can follow the instructions on [Windows developer support](https://developer.microsoft.com/en-us/windows/support/) for support options. (Click "Forums and community".)
