### ISSUE TITLE
read_stream is no longer a valid scope for facebook

### ISSUE THREAD

**Issue by randyram-at-ms** [microsoft/Windows-universal-samples#1323]
**Which sample are you reporting a bug in?**

Example: WebAuthenticationBroker

**Describe the bug**
read_stream is no longer a valid scope for the facebook oauth login, see https://developers.facebook.com/docs/permissions/reference

I changed it to public_profile and it worked.

**Comment by oldnewthing** [comment]
I used `email` since that makes it align with the C# sample. Thanks.
