### ISSUE TITLE
What does "^" mean in the app?

### ISSUE THREAD

**Issue by CodingDogzxg** [microsoft/Windows-universal-samples#1327]
In the Windows Simple Ink project, I saw many ^ marks were used.
I am confused. What does "^" mean? Is it equivalent to "&"?
Does it mean a reference?
`
InkStrokeContainer^ Scenario9::GetCurrentStrokesView(DateTime time) {

    auto inkStrokeContainer = ref new InkStrokeContainer();
    for (auto stroke : strokesToReplay) {

        InkStroke^ s = GetPartialStroke(stroke, time);
        if (s) {

            inkStrokeContainer->AddStroke(s);
        }
    }
    return inkStrokeContainer;
}`

What's more, I would like to transmit the strokes via socket. Is there any way to get all the strokes and transmit them via socket?

**Comment by oldnewthing** [comment]
The `^` is part of the [C++/CX language extension](https://docs.microsoft.com/en-us/cpp/cppcx/visual-c-language-reference-c-cx?view=msvc-170) for Windows Runtime classes. Sorry I haven't had a chance to port the app to C++/WinRT yet.

**Comment by CodingDogzxg** [comment]
Got it,  thank you.

**Comment by CodingDogzxg** [comment]
> The `^` is part of the [C++/CX language extension](https://docs.microsoft.com/en-us/cpp/cppcx/visual-c-language-reference-c-cx?view=msvc-170) for Windows Runtime classes. Sorry I haven't had a chance to port the app to C++/WinRT yet.

Got it, thank you!
