### ISSUE TITLE
How to cast char* to IVectorView<InkStroke^>^?

### ISSUE THREAD

**Issue by CodingDogzxg** [microsoft/Windows-universal-samples#1332]
Scenario: exchange stroke date between apps running on different devices by using TCP connection.
After I cast IVectorView<InkStroke^>^ to char * to transmit to the server part, what should I do to cast it back from char *?
![image](https://user-images.githubusercontent.com/49633098/145703123-0498e39e-5d99-4ef3-9651-5ff32d0190e2.png)
memcpy() doesn't work.
static_cast doesn't support IVectorView<InkStroke^>^.
Can you give me any advice that I can fix this problem?

**Comment by CodingDogzxg** [comment]
Now I give up sending Strokes rather than a single stroke. But we cannot initialize an InkStroke instance. How can I build up an empty InkStroke?

**Comment by oldnewthing** [comment]
This appears to be a question about the feature itself, not a question about any of the samples. You can follow the instructions on [Windows developer support](https://developer.microsoft.com/en-us/windows/support/) for support options. (Click "Forums and community".)

**Comment by oldnewthing** [comment]
It looks like the InkStrokeContainer.SaveAsync and LoadAsync methods are what you're looking for.

**Comment by CodingDogzxg** [comment]
> It looks like the InkStrokeContainer.SaveAsync and LoadAsync methods are what you're looking for.

Sure thing, I've thought about that and passed it because transmit a .gif file wastes bandwidth a lot since it send many redundant information. (The server part is designed to show one stroke a time. The client part's send method will be triggered by stroke collected events.)
Any way, this should be a practicable way to solve that. Thank you.
