### ISSUE TITLE
Continous speech recognition 

### ISSUE THREAD

**Issue by CSharpTeoMan911** [microsoft/Windows-universal-samples#1334]
Sample:

https://github.com/microsoft/Windows-universal-samples

App:  uwp speech recognition example 

Bug:
Because you are a developer that works at Microsoft I want to address a pressing issue related to uwp's continous speech recognition. This problem isn't related to the code that is contained within the sample, but rather an API and speech recognition engine problem. The continous speech recognition stops suddenly and it doesn't start again. This isn't a local problem, I've tested the uwp continuous speech recognition on multiple systems with multiple architectures. I tried to test the source of the problem by using tail recursion, timers and conditional tail recursion in order to force the speech recognition engine to start again if a problem occurs, but surprisingly, still doesn't work. I know that the uwp's speech recognition engine stops if the app goes in the background and I ensured, that the test app doesn't deactivate, but the speech recognition engine still stops. The only function that works from the uwp's speech recognition engine is the non-continous speech recognition. If you'll think that I initiated the speech recognition wrong.... believe me, I didn't. I even used using statements and condional statements with which I manually 
De-allocate the speech recognition engine from the memory and reinitiate it if it shutting down, it will still not stay activated.

**Comment by oldnewthing** [comment]
Sorry, this repo is for the samples, not for general Windows developer support. You can follow the instructions on [Windows developer support](https://developer.microsoft.com/en-us/windows/support/) for support options. (Click "Forums and community".)
