### ISSUE TITLE
Sample C application using nmake

### ISSUE THREAD

**Issue by nicowilliams** [microsoft/Windows-universal-samples#1335]
**Describe the feature**

I'm trying to update a codebase to use Windows 10 SDKs w/ VS 2019 in Appveyor.  This codebase used to use `SetEnv.cmd` and the `nmake`.  Try as I might I can't figure out what replaces `SetEnv.cmd` in newer SDKs.

**Comment by oldnewthing** [comment]
This is not a question about any sample in this repo.
