### ISSUE TITLE
Combo Box focus bug.

### ISSUE THREAD

**Issue by CodingDogzxg** [microsoft/Windows-universal-samples#1337]
There is a toolbar with a combo box(with input enabled) in my app sample. When I click the blank area of the toolbar, the combo box will be unfocused. This is what we want.
Given that I have an ink stroke area below the toolbar, when I try to draw something, the combo box will remain the focus state. Is there any way to trigger the unfocus event of a combo box?

**Comment by oldnewthing** [comment]
This does not appear to be a question about a sample in this repo. You can follow the instructions on [Windows developer support](https://developer.microsoft.com/en-us/windows/support/) for support options. (Click "Microsoft Q&A".)

**Comment by CodingDogzxg** [comment]
Not helping at all, but thanks.
