### ISSUE TITLE
how to get Esim EID？

### ISSUE THREAD

**Issue by liangchaoqin** [microsoft/Windows-universal-samples#1340]
In the [ESim.Eid Property](https://docs.microsoft.com/en-us/uwp/api/windows.networking.networkoperators.esim.eid?view=winrt-22000) show that this functionality is available only to mobile operator apps and UWP apps given privileged access by mobile network operators.

How to  be a mobile network operator?

**Comment by oldnewthing** [comment]
This appears to be a question about the feature itself, not a question about the sample. You can follow the instructions on [Windows developer support](https://developer.microsoft.com/en-us/windows/support/) for support options. (Click "Forums and community".)

But the way to be a mobile network operator is to be a company like Verizon or T-Mobile.
