### ISSUE TITLE
multiple issues with the BluetoothLE->cppwinrt sample

### ISSUE THREAD

**Issue by jshroff** [microsoft/Windows-universal-samples#1341]
1. It seems we need to reference DeviceCapability Name="bluetooth" in the Package.appxmanifest
2. CharacteristicList_SelectionChanged() references serviceList so it crashes the app

Does microsoft even test these samples before releasing??

**Comment by oldnewthing** [comment]
Sorry. I just cranked through and translated them from C# to C++/WinRT. I am not a subject matter expert. I just did a blind translation of the C# sample written by the BT team. Fix in 5/25 release.
