### ISSUE TITLE
Roaming data not working for ApplicationData sample.

### ISSUE THREAD

**Issue by keithnicholson** [microsoft/Windows-universal-samples#1343]
**Which sample are you reporting a bug in?**

ApplicationData

**Describe the bug**
I am executing the ApplicationDataSample and the Roaming does not seem to be working between two machines.  Will this work in Debug mode in Visual Studio?  Do I have to publish the app via the store for the OS to sync?  Maybe I am impatient, but what is the rough expectation for timing between syncs?

**To Reproduce**
1. Download sample repos to two machines
2. Open the ApplicationData (C# version) solution
3. Open in Visual Studio 2022 on Machine A
4. Debug solution
5. Select "6) Roaming: HighPriority"
6. Increment value to "3"
7. Open in Visual Studio 2002 on Machine B
8. Debug solution
9. Select "6) Roaming: HighPriority"
10. I expect to see "3", but I see another "0"

**Expected behavior**

**Screenshots**

**Configuration**

* Language/architecture/flavor: c#
* Windows platform and build number: Machine A 22000 & Machine B 1904.  Signed in both with a Microsoft Account

* Visual Studio version: VS 2022 - Signed in with an O365 account on both IDEs.  I also tried a standard Microsoft Account.

**Additional context**

**Comment by oldnewthing** [comment]
In [November 2019](https://github.com/MicrosoftDocs/windows-itpro-docs/commit/b05958e5a97461b58d097e5ae1a91314b6419b93#diff-7668ed69d3ecca28bb014338a035a870712485fbeca542af05ca90280754bf2dR35), Microsoft announced that the RoamingFolder API [will be removed in the future](https://docs.microsoft.com/en-us/windows/apps/design/app-settings/store-and-retrieve-app-data#roaming-data), That removal finally occurred in 22000. I will update the documentation and remove the scenario from the sample.

**Comment by keithnicholson** [comment]
Guess the future is upon us.  Too bad, it was an intriguing idea without needing to put the plumbing together with API's, security, and our own databases.
