### ISSUE TITLE
Get formatting (ie tabs and spaces) from Windows OCR

### ISSUE THREAD

**Issue by karam-khanna** [microsoft/Windows-universal-samples#1352]
**Which sample are you requesting a feature to be added to?**
winrt::OCR

**Describe the feature**
I'm struggling how to figure out how to capture tabs and whitespace properly. I'm working in cpp/winrt and am getting an OCR result, and can access individual lines, but don't know how to preserve those tabs. I'd appreciate any help on how solve this

**Comment by oldnewthing** [comment]
The OCR engine produces lines, and each line is broken into Words. So you can just collect the words together (with a space in between). If you want to get fancy, you can try to infer tabs from the amount of space between words. But this is beyond the purpose of the sample, which is the gather the words.
