### ISSUE TITLE
How to get the APIs to work with Unity?

### ISSUE THREAD

**Issue by LunaWu0000** [microsoft/Windows-universal-samples#1365]
**Which sample are you requesting a feature to be added to?**

Geolocation

**Describe the feature**
I tried to create a .dll file from the geolocation API, but it isn’t working well with unity (api compatibility .net standard). It says the .dll file targets at .net core. Has anyone had the same problem here? Or any suggestions from the team?

**Comment by oldnewthing** [comment]
This isn't really a feature of the Geolocation sample. It's a general problem about building C# code that can be used from Unity, not specific to the Geolocation sample. You may want to ask on a Unity site, or you can follow the instructions on [Windows developer support](https://developer.microsoft.com/en-us/windows/support/) for support options. (Click "Forums and community".)
