### ISSUE TITLE
Adding a Rfcomm serial device to a Bluetooth adapter

### ISSUE THREAD

**Issue by NilsHoyer** [microsoft/Windows-universal-samples#1369]
I'm not sure, if I get an answer here. But I searched several hours until now, and on stackoverflow.com, nobody answered me.

I'm trying to communicate via Rfcomm over Bluetooth with the serial port. To do this, I need to get the Rfcomm device. But with the following way, I don't get it (after adding the needed capabilities to the Package.appxmanifest file):

    var devices = await DeviceInformation.FindAllAsync(RfcommDeviceService.GetDeviceSelector(RfcommServiceId.SerialPort));

... after, I executed the [MyPhoneExplorer](https://www.fjsoft.at/) app, I get the Rfcomm device on the same way, described before. It's named with "MyPhoneExplorer". So, this app created the Rfcomm serial device anyhow. I want to do this, too.

How can I create the Rfcomm serial device?

PS
Sorry to bother you ... 🙄

**Comment by oldnewthing** [comment]
The code you posted does not appear to exist in this repo. It appears to be code from one of your own projects. You can follow the instructions on [Windows developer support](https://developer.microsoft.com/en-us/windows/support/) for support options. (Click "Forums and community".)

**Comment by NilsHoyer** [comment]
Thank you for your ignorance.
