### ISSUE TITLE
Live tile update issue: drag/drop needed in start menu to see updated content

### ISSUE THREAD

**Issue by japf** [Microsoft/Windows-universal-samples#137]
I'm having a hard time with a bug regarding live tile. I can reproduce problem in the SecondaryTiles sample in this repro.

- introduce a static int value in the SecondaryTileNotification page
- combine this value to the text shown on the tile, and use this value for the badge
- increment the value when a live tile or badge notification is sent

This works well until I keep the original tile name. If I change the id of the secondary tile for something else (in SampleConfiguration.cs) it no longer works. Only badge notification are shown. The content of the live tile keeps unchanged UNTIL the tile is moved on the start menu.

The only workaround I found so far is to remove the badge notification but that's not an option for my app... Any idea ? I can provide sample code in a forked repo if that helps.

**Comment by japf** [comment]
@AdamBraden any chance you had a chance to take a look at this ? Windows 10 users of my app are seeing the issue too and so far I don't know how to fix it :-(

**Comment by anbare** [comment]
Got a repro - changing the ID of the secondary tile isn't necessary, the three bulleted points are sufficient to cause the repro.

Investigating further...

**Comment by japf** [comment]
Thanks for the update @anbare looking forward what you find out and if a workaround is available. The only one I could come up with is to remove badge notification from the app :-(

**Comment by japf** [comment]
@anbare any update on this issue ? Thank you very much :-)

**Comment by anbare** [comment]
The devs are working on fixing it, the fix should be available in TH2 when they're done with it. But that means your users won't have the fix until TH2 is publically released.

Temporarily removing the badge might be the best solution for now if the tile notification is more critical than the badge for your app.

**Comment by japf** [comment]
Thanks for the quick update ! The Windows 10 version of my app will go live without badge notification until TH2 is out :-)

**Comment by anbare** [comment]
Hey Japf, I'm happy to report that the dev team fixed this bug!

The fix will hit public users with the release of TH2. If you're an Insider, the fix was added at build 10552, so any build after that will have the fix.

**Comment by japf** [comment]
Great news, thanks for the update :-)

**Comment by HppZ** [comment]
Seems your problem has been solved, then you should close this issue.
