### ISSUE TITLE
Can Bluetooth low energy use MTU?

### ISSUE THREAD

**Issue by wch66** [microsoft/Windows-universal-samples#1372]
Hello! 
Using Windows development Bluetooth tools to interact with Bluetooth low energy devices for data interaction, can I interact with MTU to complete the interaction of large data packets?

**Comment by oldnewthing** [comment]
This appears to be a question about the feature itself, not a question about the sample. You can follow the instructions on [Windows developer support](https://developer.microsoft.com/en-us/windows/support/) for support options. (Click "Microsot Q&A".)
