### ISSUE TITLE
More Sample Code for WinUI3 desktop app, not UWP.

### ISSUE THREAD

**Issue by ifgotmoney** [microsoft/Windows-universal-samples#1374]
### **Which sample are you requesting a feature to be added to?**
Could we have more examples for using WinUI3 with C++/WinRT for Desktop APPs?
Currently most of them are wrote for UWP, not for desktop apps. It's very difficult for beginners to start in WinUI3 with C++/WinRT for desktop APPs.

For this sample "LowLatencyInput", I have tried 1 month to convert the sample code to Desktop APP version but always failure in debug. a lot of errors such as "read access violation". no idea what wrong with the conversion. 

### **Describe the feature**
Provide more examples for using DirectX with SwapChainPanel in C++/WinRT for Desktop APPs.
Provide a version of the sample code "LowLatencyInput" in C++/WinRT for Desktop APPs, not for UWP APPs

**Comment by oldnewthing** [comment]
Sorry, this repo is for UWP apps.

**Comment by mediaexplorer74** [comment]
> Sorry, this repo is for UWP apps.

Hi. I noticed that your repo has many branches. One braunch hase very strange name : Windows 10 future version - February 2019 Update. OldNewThing, please look ahead, 2023 year is going... =) And, in/at autumn 2017 Microsoft cancelled Windows 10 Mobile, so UWP and "One Core philosophy" is only myth at now... sorry.

**Comment by oldnewthing** [comment]
You might have noticed that that commit was made in 2019. At the time of the commit, the next version of Windows 10 didn't have a name.
