### ISSUE TITLE
WebAuthenticationBroker sample for google no longer works

### ISSUE THREAD

**Issue by MartinRichards23** [microsoft/Windows-universal-samples#1376]
The Google WebAuthenticationBroker [sample](https://github.com/microsoft/Windows-universal-samples/blob/main/Samples/WebAuthenticationBroker/cs/Scenario4_Google.xaml.cs) no longer works as Google have deprecated the flow that it uses (i.e. the redirect url urn:ietf:wg:oauth:2.0:oob), as described [here](https://developers.googleblog.com/2022/02/making-oauth-flows-safer.html).

**Comment by oldnewthing** [comment]
Thanks. I've notified the responsible team.

**Comment by oldnewthing** [comment]
Fixed in [Release v15.0.0.1](https://github.com/microsoft/Windows-universal-samples/releases/tag/v15.0.0.1).
