### ISSUE TITLE
Executable for Personalization

### ISSUE THREAD

**Issue by JoeBrunsTR** [microsoft/Windows-universal-samples#1378]
Any chance you could provide a compiled version of the Lock Screen Personalization git collection you have?

**Comment by oldnewthing** [comment]
The purpose of the samples is to demonstrate the code. If you want compiled binaries, you can compile them yourself following the instructions in the README.

**Comment by JoeBrunsTR** [comment]
Unfortunately I do not have a copy of the paid for Visual Studio.

**Comment by oldnewthing** [comment]
Visual Studio Community is free. But you don't have to use Visual Studio. You can use whatever toolchain you intend to write your programs in.
