### ISSUE TITLE
Some of these samples are missing core components.

### ISSUE THREAD

**Issue by GuildOfCalamity** [microsoft/Windows-universal-samples#1387]
**Which sample are you reporting a bug in?**

Example: AnimationMetrics

**Describe the bug**
When compiling the App.xaml and App.xaml.cs file are not present. Many other files are missing also, such as the PNG assets.

**To Reproduce**
1. Open the AnimationMetrics sample for C# in VS2022
2. Just try to compile it.... I dare you.
3. Scratch head in bewilderment as to how someone released this.

* Language/architecture/flavor: C#
* Windows platform: Windows 10
* Visual Studio version: Version 17.6.0 Preview 7.0

**Comment by GuildOfCalamity** [comment]
Apparently all of the samples share a common App.xaml which is located in a separate parent folder... this is a horrible design and makes none of the projects portable or sharable.

**Comment by oldnewthing** [comment]
Each sample links to a self-contained ZIP file that contains all the dependencies.

**Comment by GuildOfCalamity** [comment]
@oldnewthing I can understand the repeatability issue for the projects, but these samples do not work out of the box as advertised. The pathing in the project wants the shared resources to be here: `C:\SharedContent` which is problematic. I did not see any references to a self-contained archive.

**Comment by mediaexplorer74** [comment]
> Apparently all of the samples share a common App.xaml which is located in a separate parent folder... this is a horrible design and makes none of the projects portable or sharable.

You're right ("gigabyte in size" mention is ok). But some automation tool + instruction needed for partial sample deploying ("separation/decomposition from all samples"?)

**Comment by oldnewthing** [comment]
The samples look for SharedContent in any parent directory. Doesn't have to be the root.
```xml
<SharedContentDir>$([MSBuild]::GetDirectoryNameOfFileAbove($(MSBuildThisFileDirectory), LICENSE))\SharedContent</SharedContentDir>
```

If you want a sparse repo, then enable the `/*` directory, the `/SharedContent` subtree, and the `/Samples/YourDesiredSample/` subtree.

If you want to filter even more tightly to a specific language, then you want to enable `/*`, `/SharedContent`, `/Samples/YourDesiredSample/shared`, and `/Samples/YourDesiredSample/language`. (Though I haven't tested this last version.)

If you just want ready-to-build samples, then download the ZIP. It packages the SharedContent directory automatically.

The instructions for partial deployment are in the README under "[Using the Samples](https://github.com/microsoft/Windows-universal-samples/#using-the-samples)".

**Comment by mediaexplorer74** [comment]
> If you just want ready-to-build samples, then download the ZIP. It packages the SharedContent directory automatically.
> The instructions for partial deployment are in the README under "[Using the Samples](https://github.com/microsoft/Windows-universal-samples/#using-the-samples)".

Great. Thank you for quick and nice answers to my strange ideas =)

Special thank you for the stale branch "win10-1507", because of very userful things for some Win10Mobile retroman :)
+ fresh "dev" branch is very cool because of feeling that UWP is long-year-live thing! 💯 
Best,
MediaExplorer
