### ISSUE TITLE
XAML disigner tells you to upgrade Windows?

### ISSUE THREAD

**Issue by GuildOfCalamity** [microsoft/Windows-universal-samples#1388]
**Which sample are you reporting a bug in?**

Example: Logging

**Describe the bug**
The XAML designer lies about needing Win11 just to work properly. I have adjusted the **Targeting** versions.

**To Reproduce**
1. Open any of the UWP sample in VS2022 on a Win10 machine.
2. Open a XAML page.

**Expected behavior**
The designer to work normally.

**Screenshots**
![image](https://github.com/microsoft/Windows-universal-samples/assets/81915293/ea14aec3-2ecf-4d52-bf5c-a91a29e2cc98)

**Configuration**
* Language/architecture/flavor: C#
* Windows platform and build number: Win10
* Visual Studio version: 17.6.0 Preview 7.0

**Comment by oldnewthing** [comment]
This is by design. All the samples in the repo target the same SDK, so that you don't run around installing seven different SDKs, some of which are hard to find because they are so old.

**Comment by GuildOfCalamity** [comment]
@oldnewthing So is this the latest and correct Win10 branch?
[win10-2004](https://github.com/microsoft/Windows-universal-samples/tree/win10-2004)
