### ISSUE TITLE
 Designe-Issus in the Navigation-Sample

### ISSUE THREAD

**Issue by MysticEmpires** [Microsoft/Windows-universal-samples#139]
There are some Designe-Issus on the Navigation-Sample

1. If i resize the from the 720 VisualState to the small VisualState back to 720. The margin on the PageHeader is to big (0,0,48,48 instand of 0,0,0,0). This get fixed if u toogle the Hamburger-Button.
2. if u change the DisplayMode on 720 VisualState to Compact and the IsPaneOpen. The PageHeader is Missing the 0,0,48,48. This get also fixed if u toogle the Hamburger-Button.

I thing there are some placed the "CheckTogglePaneButtonSizeChanged" should be called.

**Comment by oldnewthing** [comment]
This will be fixed in our next refresh. Thanks for reporting it.
