### ISSUE TITLE
AppUIBasics crashes when you run it

### ISSUE THREAD

**Issue by acoles88** [Microsoft/Windows-universal-samples#14]
Just compile and run.  XAML exception Line 93, position 57

**Comment by vinoselv** [comment]
Yes, the exception detail is>

Message	"A TargetPropertyPath for a Style Setter cannot specify an explicit Target object. [Line: 93 Position: 57]"	

Please fix the issue as this is the most important project to learn all the basic controls

**Comment by mikehenderlight** [comment]
Fixed.
