### ISSUE TITLE
Remote debugging fails on a remote computer in a local network

### ISSUE THREAD

**Issue by Padanian** [Microsoft/Windows-universal-samples#140]
Error   Unforeseen event in activity "WireUpCoreRuntime".
System.IO.FileNotFoundException: file not found 'D:\Users\Alex\Documents\Visual Studio 2015\Repos\Windows-universal-samples\Samples\StreamSocket\cs\bin\x86\Debug\Core\$targetnametoken$.exe'.
Nome file: 'D:\Users\Alex\Documents\Visual Studio 2015\Repos\Windows-universal-samples\Samples\StreamSocket\cs\bin\x86\Debug\Core\$targetnametoken$.exe'
   in System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   in System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   in System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   in Microsoft.Build.Net.CoreRuntimeTask.WireUpCoreRuntime.InternalExecute()
   in Microsoft.Build.Net.CoreRuntimeTask.WireUpCoreRuntime.Execute()
   in Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   in Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext() StreamSocket            Compilazione

**Comment by oldnewthing** [comment]
Which sample are you seeing this with? This doesn't sound like a samples issue; it sounds like a Visual Studio issue.

**Comment by Padanian** [comment]
Streamsocket. Any other sample I tried works. The issue here is "$targetnametoken$.exe". I think there should be the .exe filename in place of $targetnametoken$ .Like a placeholder that doesn't get replaced...

**Comment by DavidGoll** [comment]
You are correct. This will be fixed in the next refresh.

**Comment by DavidGoll** [comment]
I take that back, all samples specify $targetnametoken$.exe in their package.appxmanifest files. So, something else is going on.

**Comment by Padanian** [comment]
I'll do more testing in a couple of days, when I'll able to remotely debug it.
Thanks for the time being.

**Comment by oldnewthing** [comment]
Closing old issues.
