### ISSUE TITLE
A lot of projects are outdated

### ISSUE THREAD

**Issue by halflifefan** [microsoft/Windows-universal-samples#1409]
**Which sample are you reporting a bug in?**
DWriteColorGlyph

**Describe the bug**
Similarly to #1320, it said I was missing ImageContentTask.props. I tried defining VSINSTALLDIR, but then I realized that the project configuration was completely empty: there's no output directory, no nothing. Configuration warnings and errors pop up.

**To Reproduce**
Open this project in the latest Visual Studio Community, I guess

**Expected behavior**
A fully ready sample project just like most of the other samples here

**Screenshots**
![image](https://github.com/microsoft/Windows-universal-samples/assets/37071910/ef7af5da-00bf-4261-a5d3-373878d75468)

**Configuration**
Visual Studio version: Community 17.9.5

**Additional context**
Seems to happen to other samples

**Comment by mszczes** [comment]
How did you manage to fix it?
