### ISSUE TITLE
The CameraResolution project cannot obtain the H264 format of the usb camera

### ISSUE THREAD

**Issue by kuangbianxiaopengyou** [microsoft/Windows-universal-samples#1413]
**Which sample are you reporting a bug in?**

Example: CameraResolution

**Describe the bug**
The CameraResolution project cannot obtain the H264 format of the usb camera.

**Comment by oldnewthing** [comment]
This doesn't appear to be an issue with the sample. It just reports what GetAvailableMediaStreamProperties returns. If GetAvailableMediaStreamProperties doesn't return H264, that's a platform issue, not a sample issue.
