### ISSUE TITLE
Compass / Magnotometer 

### ISSUE THREAD

**Issue by rcroeder** [Microsoft/Windows-universal-samples#142]
HeadingTrueNorth  and HeadingMagneticNorth cannot be the same value. This was taken from the SF Bay Area which has a magnetic declination of 13D44M. This was taken on a Lumia 920 running 10512 firmware 3051.50009.1425.2001 hardware version 6.0.0.1. 

![compassissue](https://cloud.githubusercontent.com/assets/2488299/9427062/b0981000-491c-11e5-94a2-976f2940c044.jpg)

**Comment by lisaong** [comment]
Thanks for the comment. When location is not available, the declination defaults to 0 degrees, which is what you are seeing. Can you check if the 920 is able to get location?

**Comment by rcroeder** [comment]
Thank you for the input. The 920 does not have a sim card, but I am able to get location. The app Raw Compass data and Jack of all Tools apps both are able to show Mag north and true north. This appears to be only in the Universal App that is not getting the location. Interesting, are you indicating that the Magnotometer relies on the GPS/AGPS, and if so dos it need to be running? I know that the 920 lacks SensorCore which does do a background GPS, but that does not explain why the old app are correctly getting the right data and the sample app here is not.

**Comment by micche** [comment]
Hi Rcroeder, 

I am able to retrieve Magnetic North and True North using the Universal **SensorInfo** App (published on the Windows Store) with Location and WIFI enabled on my Surface 3 Pro. Please let me know if you are still running into this issue. Which Universal App were you seeing this on BTW?

Thanks!
