### ISSUE TITLE
Keydown event fires twice. 

### ISSUE THREAD

**Issue by JuniperPhoton** [Microsoft/Windows-universal-samples#143]
Hope this issue to be fixed.

**Comment by AdamBraden** [comment]
Can you clarify which sample you are seeing this behavior?

**Comment by JuniperPhoton** [comment]
No such specified sample. You can add a handler to TextBox's Keydown Event and you will find that once you press the key, the event fires twice.

**Comment by AdamBraden** [comment]
Unfortunately, I do not reproduce this error.  There is a known issue about the enter key firing twice when the Enter key is pressed.  
https://social.msdn.microsoft.com/Forums/en-US/734d6c7a-8da2-48c6-9b3d-fa868b4dfb1d/c-textbox-keydown-triggered-twice-in-metro-applications?forum=winappswithcsharp

However, the Windows Universal Samples repo is specifically about samples issues and not for general Q&A or non-samples bugs.  If you still reproduce the behavior for all key presses, I recommend you post your code (XAML and cs)  in the Developing Universal Windows app forum:
https://social.msdn.microsoft.com/Forums/windowsapps/en-US/home?forum=wpdevelop
