### ISSUE TITLE
Logging sample - Read logs

### ISSUE THREAD

**Issue by Nicothekrug** [Microsoft/Windows-universal-samples#146]
Hi,

How do you read logs generated from the Logging sample ? I tried numerous tools inclulding WPA, and none of them is capable of giving me back the logged datas. I can see events, but no more. Is there any manifest/extra work/properties to manipulate in order to have access to log content ?

Thank you,

**Comment by oldnewthing** [comment]
I've asked the feature team to respond.

**Comment by oldnewthing** [comment]
Details on how to get the information are [in comments in the source code](https://github.com/Microsoft/Windows-universal-samples/blob/ad44f9b846b7064a0dd6eca8b0b7a453902e4a22/Samples/Logging/cs/LoggingChannelScenario.cs#L24):

> You can collect the events generated by this method with xperf or another ETL controller tool. To collect these events in an ETL file:
> * `xperf -start MySession -f MyFile.etl -on 4bd2826e-54a1-4ba9-bf63-92b73ea1ac4a`
> * (run the sample and click the "Windows 8.1 behavior" button)
> `xperf -stop MySession`
>
> After collecting the ETL file, you can decode the trace using xperf, wpa, or tracerpt. For example, to decode MyFile.etl with tracerpt:
>
> * `tracerpt MyFile.etl`
> * (generates dumpfile.xml)
>
> Note that decoding TraceLogging events requires Windows 10. Earlier versions of Windows can only reliably decode the simple (manifest-based) events.
>
> If a LoggingChannel is created using the 1-parameter constructor, it will use Windows 8.1 semantics:
> - The channel's ETW Id is always "4bd2826e-54a1-4ba9-bf63-92b73ea1ac4a".
> - The channel's ETW Name is always "Microsoft-Windows-Diagnostics-LoggingChannel".
> - A LoggingChannelName field containing the Channel Name is automatically added to each event.
> - Simple events will be written using manifested-event encoding.
>
> Note that complex events can be written even when using Windows 8.1 mode. Complex events always use TraceLogging encoding.

I'll add a note in the README pointing to these details.
