### ISSUE TITLE
Background Audio Player with HLS?

### ISSUE THREAD

**Issue by MarkDHarris** [Microsoft/Windows-universal-samples#147]
Hi,

	I am trying to modify the Background Audio sample so that it can successfully play HLS (.m3u8) streams.  It almost seems as simple as just adding the url to the songlist initialization in the scenario1.xaml file but doing so leads to a strange crash.  (I have tried updating the CreatePlaybackList method to use an AdaptiveMediaSource for the HLS url rather than just a MediaSource but this has not helped.)

	The repro is that if I add an HLS URL to the existing list of ring tones (doesn’t seem to matter which position), its fine and it plays the HLS stream if that was the first one selected.  But then the app is in a strange mode where selecting the last item in the list (no matter what the last item is) immediately leads to an access violation and app crash or selected a middle of the list item once or twice also leads to this crash.  

For example: ” The program '[24600] Windows.Media.BackgroundPlayback.exe' has exited with code -1073741819 (0xc0000005) 'Access violation'.”  I’ve traced this down to the TrackChanged event but I can’t tell what’s really going wrong.

	Is there any example code of how to correctly play HLS streams?

**Comment by aarononeal** [comment]
Mark, thanks for the report. My understanding is that either of the approaches you tried should work. We will try to reproduce this to see what's happening.

**Comment by aarononeal** [comment]
@MarkDHarris We're not able to reproduce this yet. Would you be able to provide us with a stack trace or point us at the HLS test content you're using?

**Comment by MarkDHarris** [comment]
I have tried 2 different .m3u8 streams and they both experience the same issue:

- http://bbnmedia-lh.akamaihd.net/i/BibleBroadcasting_Englishios@87472/master.m3u8
- http://wms.shared.streamshow.it/telesanremo/telesanremo/playlist.m3u8


Here is a step by step list of two different ways to repro the same problem by starting with the sample code.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1)	Clone https://github.com/Microsoft/Windows-universal-samples.git

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2)	Open C:\PROJECTS\Windows-universal-samples\Samples\BackgroundAudio\cs\BackgroundAudio.sln



**REPRO #1**


&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;3)	Insert following code at line #116 in C:\PROJECTS\Windows-universal-samples\Samples\BackgroundAudio\cs\BackgroundAudio\Scenario1.xaml.cs.

    var song3 = new SongModel();
    song3.Title = "BBN Radio";
    song3.MediaUri = new Uri("http://bbnmedia-lh.akamaihd.net/i/BibleBroadcasting_Englishios@87472/master.m3u8");
    song3.AlbumArtUri = new Uri("ms-appx:///Assets/Media/Ring02.jpg");  
    playlistView.Songs.Add(song3);
    
    var song4 = new SongModel();
    song4.Title = "Sample2";
    song4.MediaUri = new Uri("http://wms.shared.streamshow.it/telesanremo/telesanremo/playlist.m3u8");
    song4.AlbumArtUri = new Uri("ms-appx:///Assets/Media/Ring02.jpg");
    playlistView.Songs.Add(song4);

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;4)	Set to build x64 and run.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;5)	In the sample app, select the BBN Radio item from the list to start playback.  It plays successfully, however, when you then select one of the other items in the list – sometimes immediately… sometimes after selecting and changing the playing item several times -  it will result in a crash of the background process.  The only info I can obtain is from the debug output in VS:

    The program '[13576] Windows.Media.BackgroundPlayback.exe' has exited with code -1073741819 (0xc0000005) 'Access violation'.
    Exception thrown: 'System.Exception' in BackgroundAudio.exe
    The program '[12376] BackgroundAudio.exe: Program Trace' has exited with code 0 (0x0).
    The program '[12376] BackgroundAudio.exe' has exited with code -1 (0xffffffff).


The foreground app responds slightly differently from time to time but the crash in the background seems to manifest itself as this (I think it’s the foreground app trying to talk to the background app which no longer exists):

    The RPC server is unavailable. (Exception from HRESULT: 0x800706BA)
       at Windows.Media.Playback.BackgroundMediaPlayer.get_Current()
       at BackgroundAudio.Scenario1.RemoveMediaPlayerEventHandlers()
       at BackgroundAudio.Scenario1.ForegroundApp_Suspending(Object sender, SuspendingEventArgs e)



**REPRO #2**
(This is more representative of my problem because I only want to use the streaming media source in my app... I included the first repro to show minimal changes to the sample code.)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;3) Comment / disable the code which adds all the items to the song list except for the BBN Radio item that was added in REPRO #1.  (i.e. comment song1, song2, song 4, and the gapless code.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;4) Build and run the code.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;5) The app itself runs fine but when the BBN Radio item is selected for playback **AND** when it is the only item in the list - it immediately crashes with what I think is the same access violation in the background process..

The debugger output is somewhat chatty about what I think are non-relevant things but the final few lines are:

    trackid
    value found http://bbnmedia-lh.akamaihd.net/i/BibleBroadcasting_Englishios@87472/master.m3u8
    position
    value found 00:00:00
    StartPlayback: Switching to track 0
    The program '[4468] Windows.Media.BackgroundPlayback.exe' has exited with code -1073741819 (0xc0000005) 'Access violation'.



Which seems to be the same access violation from REPRO #1.


This repro’s for me 100% of the time and is blocking me from proceeding with my app.  Am I doing something incorrect?



I have even tried modifying the background task to use the AdaptiveMediaSource object thinking it was more appropriate or necessary.  (BTW - I'm not certain if I'm using it correctly or understand why it exists if it is not necessary... but in any case, it seems to suffer the same problem.)

I won’t paste all the necessary changes, but as an example… I modified the CreatePlaybackList function to use the async/await pattern so that I could try this:

     foreach (var song in songs)
     {
         if (song.MediaUri.ToString().StartsWith("http"))
         {
              AdaptiveMediaSourceCreationResult result =
                  await AdaptiveMediaSource.CreateFromUriAsync(song.MediaUri);

              if (result.Status == AdaptiveMediaSourceCreationStatus.Success)
              {
                  var mediaSource = MediaSource.CreateFromAdaptiveMediaSource(result.MediaSource);
                  mediaSource.CustomProperties[TrackIdKey] = song.MediaUri;
                  mediaSource.CustomProperties[TitleKey] = song.Title;
                  mediaSource.CustomProperties[AlbumArtKey] = song.AlbumArtUri;

                  playbackList.Items.Add(new MediaPlaybackItem(mediaSource));
              }
          }
          else
          {
               var source = MediaSource.CreateFromUri(song.MediaUri);
               source.CustomProperties[TrackIdKey] = song.MediaUri;
               source.CustomProperties[TitleKey] = song.Title;
               source.CustomProperties[AlbumArtKey] = song.AlbumArtUri;

               playbackList.Items.Add(new MediaPlaybackItem(source));
          }

There were several other modifications necessary to make this work but after all this was done, I verified the same access violation issue was occurring.

Please let me know if this is enough info for you to repro.  If not, I can zip and send the entire solution.

Thanks for your help,
Mark

**Comment by aarononeal** [comment]
@MarkDHarris Thank you for these details! We have confirmed the first repro and have a platform fix prepared. Unfortunately, there is no known workaround that will allow you to use an adaptive media source in a multi-item playlist until that fix is published.

For the second repro, we're still investigating that one to see if it's related or a separate problem.

**Comment by aarononeal** [comment]
Sorry about the inconvenience. The platform fix on the way should address both problems. Thank you for reporting it to us.
