### ISSUE TITLE
Taskbar & Jumplists?

### ISSUE THREAD

**Issue by mikecann** [Microsoft/Windows-universal-samples#150]
Is there any samples that go in to how to set the progress bar in the taskbar or how to manage jumplists?

**Comment by oldnewthing** [comment]
That functionality is not yet available to Universal apps, sorry.

**Comment by mauricew** [comment]
Well since th2 supports it, there should be a JumpList sample.

**Comment by oldnewthing** [comment]
Coming soon. Watch this space!

**Comment by mikecann** [comment]
Excellent!

On 14 November 2015 at 04:01, Raymond Chen <notifications@github.com> wrote:

> Coming soon. Watch this space!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Microsoft/Windows-universal-samples/issues/150#issuecomment-156542417>
> .
>



-- 
*Mike Cann*
http://www.mikecann.co.uk/
@mikeysee <http://www.twitter.com/mikeysee>

**Comment by mikecann** [comment]
@oldnewthing is there any API for progress status on the Taskbar?

**Comment by oldnewthing** [comment]
Not yet.

**Comment by mikecann** [comment]
Did build announce and new features which may enable progress bars in the taskbar in UWA?
