### ISSUE TITLE
Universal VOIP application - Questions and Issues

### ISSUE THREAD

**Issue by mruf** [Microsoft/Windows-universal-samples#152]
We are currently in the process of migrating our WP8.0 VOIP application to Windows 10 / UWP.
The UWP voip sample you provided is a great help with migrating the "phone" version from WP8 to Windows 10.

We do however have a few issues/questions on how to support VOIP on other devices (desktops, tablets, etc):
- Does the two-process architecture (UI process and out-of-process server) still apply for non-phone devices? I would assume so since applications should run the same on all platforms.
- How does Windows handle a VOIP app's life cycle on non-phone devices since there's no VoipCallCoordinator to tell Windows that a VOIP call is active so that the background process is kept alive? Will an app ever be suspended when running on a desktop?
- We've modified the VOIP sample slightly so that it runs on non-phone devices. The sample works fine as long as it is in the foreground. If the app is manually minimized by using the minimize button on the window the audio and microphone stop working. Once the app is put back in the foreground the audio and mic start working again. This is unusable for a VOIP app on the desktop since the user might minimize the app during a call. Can there be something done about that?

Thanks in advance.

**Comment by mruf** [comment]
Regarding the last point (audio/mic stop working when the app is minimized on a desktop), we've tried to work around the issue by using ExtendedExecutionSession/ExtendedExecutionForegroundSession but that didn't help.
This is currently the biggest pain point for us. Any pointers are greatly appreciated.

**Comment by degoh** [comment]
I apologize for the delay in response.

1. Yes, the two-process architecture applies to non-phone devices.
2.With the latest insider build for win10, add the following to the appxmanifest: <uap:Extension Category="windows.voipCall"></uap:Extension> 
3. This is a high priority item on our list that we will be addressing

I hope this helps!

**Comment by mruf** [comment]
Thank you for the response.
By adding uap:Extension do you mean adding the  voip AppService as uap:Extension element to the manifest file?

Do you have an estimate when or in which build the sound/mic issue will be fixed?

**Comment by degoh** [comment]
Yes. Adding it to the manifest.
I believe that we are currently in the middle of validation for that fix so it should be released in one of the newer builds fairly soon.

**Comment by Jeethan-Menezes** [comment]
Is the Sound/mic issue resolved in 10.0.10586

**Comment by oldnewthing** [comment]
Closing old topic - doesn't appear to be sample-related.
