### ISSUE TITLE
Accelerometer Shake events are not working 

### ISSUE THREAD

**Issue by pallammadhukar** [Microsoft/Windows-universal-samples#153]
Hi,

I have downloaded the Accelerometer sample and run on both Windows 10 Tablet (Dell Latitude STDE) & Windows 10 Phone[OS Version: 10.0.512.0] (Lumia 730 ). I have seen Shake event is not working.

I have debug the code and observed Accelerometer.Shaken event is not received. Please help me.

Thanks.

**Comment by lisaong** [comment]
Thanks for your question. Shake is currently not supported on Windows 10. We are looking into supporting this in future releases.
