### ISSUE TITLE
Cortana Voice Command Sample inconsistent behavior

### ISSUE THREAD

**Issue by hexate** [Microsoft/Windows-universal-samples#156]
The sample for Cortana interaction does not behave consistently in my testing. Initially it seems to work, but in Debug output, the backgroundTaskHost.exe always exits with code 1 (0x1). Is that normal?

After a few successful commands, debug output randomly shows that the task is cancelled, and Cortana sends the request to the web browser.

Testing on a Windows 10 laptop.

**Comment by anpilley** [comment]
Hey hexate,
The exit code for the backgroundTaskHost.exe is normal. As long as you end your session in Cortana with ReportSuccessAsync or ReportFailureAsync, and you call Complete() on the service deferral, it should be fine. 

However, we have recently have determined that using <CommandName> Adventure Works , </CommandName> in our sample was leading to less reliable behavior, as the comma being included was causing Cortana to expect a hard pause in the phrase it hears, which can lead to unreliable behavior such as you're seeing once users start being more comfortable with the phrase they're saying.

It's been recommended to us that we use <AppName> instead, without a comma. You can see an example in the c++ sample [here](https://github.com/Microsoft/Windows-universal-samples/blob/master/Samples/CortanaVoiceCommand/cpp/AdventureWorks/adventureworkscommands.xml), and we'll be updating the other two samples next week (I just ran out of time to fix it for this week's update, unfortunately).

Try changing the CommandName to AppName without a comma, and see how you go, it should hopefully improve the reliability of your voice commands.
