### ISSUE TITLE
Navigation menu Sample crash

### ISSUE THREAD

**Issue by acoles88** [Microsoft/Windows-universal-samples#16]
Press on the hamburger menu, it asserts out:
Exception = {"The text associated with this error code could not be found.\r\n\r\nA TargetPropertyPath for a Style Setter cannot specify an explicit Target object. [Line: 55 Position: 49]"}

**Comment by micahl** [comment]
This should have been fixed by 664e4916e43d85d019f37d6f070549df8e140385.  Can you check if you have that fix in your drop of the sample?

**Comment by acoles88** [comment]
Just checked via file compare, I do have the most up to date source code.  I did notice that you did fix the problem (I didn’t report this) where the page header was overlapping on top of the hamburger menu when the window was resized.  However not matter what size the window is, I press the hamburger menu, I assert out.

**Comment by micahl** [comment]
Ok.  Using the VisualState.Setters in a control template applied as part of a style on the hamburger toggle button was causing an issue.  Change 82bba56abf8cf294b05ec9a5089b0e8bfde2c279 should resolve it.
