### ISSUE TITLE
Designe-Issus in the Navigation-Sample  #2

### ISSUE THREAD

**Issue by MysticEmpires** [Microsoft/Windows-universal-samples#160]
Ok https://github.com/Microsoft/Windows-universal-samples/issues/139 is fixed :) 

BUT if u..
- Open the Sample in the Phone Emulator
- Rotate the Phone to the left _(Rotate to right is ok^^)_
- Open and Close the Hamburger-Menu

..u can see there is a big space between the hamburguer button and the title. This is because the **rect** variable is set to _44,0,48,48_ instant of _0,0,48,48_.

So it looks like the **TransformBounds** add the _44_ to the left because of the Statusbar at the left side. So i think the problem here is the **CheckTogglePaneButtonSizeChanged** and explicitly the **TransformBounds**.

If i change line _281_ to:

``` cs
var rect = new Rect(0, 0, this.TogglePaneButton.ActualWidth, this.TogglePaneButton.ActualHeight);
```

All worked well. But i don't know if the **TransformBounds** is needed in some other cases.

Greetings
Alex

**Comment by vsriram11** [comment]
XamlNavigation sample is deprecated because we released a NavigationView control with samples in the XAML Controls Gallery app (XamlUIBasics sample).

**Comment by oldnewthing** [comment]
The XamlNavigation sample has already been deleted in the "dev" branch. Deletion coming soon to the master branch.
