### ISSUE TITLE
Continuous Dictation Example in SpeechAndTTS.sln is broken

### ISSUE THREAD

**Issue by hexate** [Microsoft/Windows-universal-samples#161]
The continuous dictation example withing the SpeechAndTTS.sln is broken. Clicking on the 'Dictate' button doesn't seem to start the continuous recognition session.

speechRecognizer.State remains Idle, so clicking the button again doesn't do anything. Trying to 'Dictate' again causes an exception because the state of the object is bad for some reason.

Steps to Repro:
Click on '7) Continuous Dictation'
Click 'Dictate'
Click 'Stop Dictate'
Click 'Dictate'

**Comment by anpilley** [comment]
Hey, can you mention which programming language you're using? all of them have subtle variations that may affect any issues if I need to reproduce them.

The continuous dictation scenario relies on connectivity to the bing dictation service, so there can be a small amount of time for it to begin continuous recognition as that connection is established, and if something delays it, you might not get feedback for a short period of time. How long are you waiting before clicking 'Stop'?

Does the predefined dictation (the one-shot short message dictation) scenario work or does that exhibit similar behavior for you?

**Comment by oldnewthing** [comment]
Closed due to inactivity.
