### ISSUE TITLE
Building AppUIBasics, and other samples fails with 2 errors

### ISSUE THREAD

**Issue by sgmon** [Microsoft/Windows-universal-samples#162]
### Environment
Windows 10
VS 2015 Community Edition

### Steps to Reproduce
1. Open AppUIBasics solution
2. Rebuild solution
3. Get 2 errors on build
    * Type universe cannot resolve assembly: System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
    * Cannot resolve Assembly or Windows Metadata file 'System.Runtime.dll'	AppUIBasics
4. Note: The same issues occurs for several other sample solutions that were opened.

### Workaround
1. Create a new C# project for UWP and copy all artifacts from the original AppUIBasics C# project and everything builds and the generated executable runs.

**Comment by oldnewthing** [comment]
I just did a fresh install of Community Edition and opened the AppUIBasics project and it built and ran. So maybe there is something peculiar to your configuration that is causing the problem. Type resolution problems suggest to me that there was a problem fetching the NuGet packages.

**Comment by sgmon** [comment]
Found an update for NuGet Package Manager for Visual Studio and upgrade from version 3.1.60717.741 to 3.1.60724.766. Still was getting the same error. I will continue looking. Thanks.

**Comment by Integ** [comment]
Maybe your network has some problem.
I just connect my vpn, and solve the problem.

**Comment by oldnewthing** [comment]
Closing old issues.
