### ISSUE TITLE
XamlListView -> TapOnTheEdge sample problems

### ISSUE THREAD

**Issue by Syn-McJ** [microsoft/Windows-universal-samples#164]
Several problems with this samlpe, specifically with <b>EdgeTappedListView</b> class:
1. <b>ShowVisual</b> method failes with <b>ArgumentException</b> if item template for <b>EdgeTappedListView</b> doesn't contain any row definitions. Reason is in this code:
   
   ```
   if (panel is Grid)
   {
       this.visualIndicator.SetValue(Grid.RowSpanProperty, (panel as Grid).RowDefinitions.Count);
   }
   ```
   
   which tries to set <b>Grid.RowSpanProperty</b> to zero.
2. Each tap on edge expands item height if there is any top or bottom <b>Padding</b> set for root grid of item template, e.g.:
   
   ```
   <DataTemplate x:Name="ContactListViewTemplate" x:DataType="data:Contact">
       <Grid Padding="0 5 0 5">
           <Grid.RowDefinitions>
           ...
   ```
3. Tap on edge does not garantee that tapped item will be selected after setting <b>ListViewSelectionMode</b> to <b>Multiple</b>. Sometimes <b>EdgeTappedListView</b> goes to selection mode with check boxes all been clear, which kind of contrary with idea that it should come back to normal mode after deselecting all items. You can reproduce this behavior by tapping different area in bounds of <b>HIT_TARGET</b>.

**Comment by oldnewthing** [comment]
Feature team has chosen to resolve as "Won't fix". You are welcome to try to fix it yourself.
