### ISSUE TITLE
Typescript typings for Windows.Media.SpeechSynthesis

### ISSUE THREAD

**Issue by ericdes** [Microsoft/Windows-universal-samples#165]
It would be nice to have the typings to use Typescript for the Windows.Media.SpeechSynthesis / Recognition.

Thank you!

**Comment by carllosalva5424** [comment]
NED FIX M'Y HELP AND SPÉCIALITÉ TO ACCOMPLIE YOU WORK AND MAKE THIS CHANGE AND ÉDUCATION MORE HELP PROJETS LIKE THIS IS WHY IM HERE TO HELP WORLD PROJECTEURS OK YOU HELP ME. PLESS

**Comment by carllosalva5424** [comment]
MANY ARRIMAGE TO YOU ALL I CARE FOR YOU COUNTRY YOU BEE OR SPÉCIALITÉ CHANGÉ AND HOPE AND MAKE THIS PERMANENT M'Y CONCERNENT TO YOU ALL I CARE ABOUT US ALL BE SA DE ON WEB PAGES IS M'Y INVESTIGATION AND FIND TOGHETER À SOLUTION

**Comment by oldnewthing** [comment]
That's not really within the scope of the UWP samples repo.
