### ISSUE TITLE
XamlNavigation sample failed to run in release mode on phone emulator

### ISSUE THREAD

**Issue by lploumen** [Microsoft/Windows-universal-samples#166]
The XamlNavigation sample works fine using Local mode in debug and release configuration.
It also works fine on phone emulator in debug configuration.
When compiled to release (native), the sample doesn't run on phone emulator and on real device.
It always brings this exception :

Unhandled exception at 0x68E489E7 (Windows.UI.Xaml.dll) in NavigationMenuSample.exe: 0xC000027B: An application-internal exception has occurred (parameters: 0x037AB748, 0x00000004).

**Comment by arangas** [comment]
I've tried reproducing this using Visual Studio 2015 Update 3 and Mobile Emulator 10586 against the current master branch and haven't had any problems with Release mode.

![xamlnavphone](https://cloud.githubusercontent.com/assets/132198/16898880/0731c588-4c2c-11e6-9456-eff3feb8ef96.png)

![xamlnavphone2](https://cloud.githubusercontent.com/assets/132198/16898881/0b2c1990-4c2c-11e6-965c-8cf90357d9c5.png)

![xamlnavvs](https://cloud.githubusercontent.com/assets/132198/16898882/0db9b5d2-4c2c-11e6-8a7f-e6034a360e76.png)
