### ISSUE TITLE
Background download/upload 

### ISSUE THREAD

**Issue by ahmadpirani** [Microsoft/Windows-universal-samples#168]
I found one issue each with background downloader and uploader.

The downloaded files are always corrupted. I made few of my onedrive files downloadable by public with Urls. However, all of them, be it image, docx or even text file, were corrupt on download. I guess the headers are not properly downloaded. I am not sure.

The upload never happens. I made one of m onedriver folders uploadable to all. I tried uploading files to that folder, nothing happens.

**Comment by oldnewthing** [comment]
This is an old issue. Are you still experiencing the problem? If so, I will reopen.
