### ISSUE TITLE
0x80004001 in Speech recognition and synthesis sample

### ISSUE THREAD

**Issue by elgeneral** [Microsoft/Windows-universal-samples#169]
When i download the sample "SpeechRecognitionAndSynthesis" and try to run the javascript-version in VS2015 on a Windows Azure Virtual Computer based on the catalogue item "Visual Studio Enterprise 2015 RC with Universal Windows Tools"
i get the following error:
"Exception is about to be caught by JavaScript library code at line 17, column 13 in ms-appx://microsoft.sdksamples.speechandtts.js/js/scenario1_SynthesizeText.js
0x80004001 - JavaScript runtime error: Not implemented"

The code in that line is 
         audio = new Audio();

**Comment by anpilley** [comment]
Just to clarify, when you say:
Windows Azure Virtual Computer based on the catalogue item "Visual Studio Enterprise 2015 RC with Universal Windows Tools"
are you referring to creating a VM in Azure based on this image, that's using the windows 10 preview image with build 10074 on it? 

Why aren't you using an image with the final release of Visual studio 2015 that's based on the final Windows 10 release? (build 10240)

**Comment by anpilley** [comment]
Digging a little further, it looks like the VM images used in Azure use Enteprise-N SKUs, which doesn't ship with media player (from memory). I'm running a few tests now, but it's possible that that also results in the audio tag failing to initialize. I'm not sure if there's an alternate path to rendering audio playback on an enterprise-N sku, but we can definitely handle the failure more gracefully.

**Comment by anpilley** [comment]
Okay, confirmed. Enterprise-N skus throw an error when creating the Audio tag. Unfortunately, the speech recognition parts of the sample are likely to fail with similar errors, because we use the media playback components to test if the microphone is available and we have access to it (although speech recognition itself works fine).

**Comment by elgeneral** [comment]
I have installed the Media Feature Pack for N and KN versions of Windows 10 ( from https://www.microsoft.com/en-US/download/details.aspx?id=48231 ) in the Azure VM and i can confirm that has resolved the issue i have been facing!

Thanks for your swift response!

**Comment by anpilley** [comment]
I figured that'd help. I'll update the samples to ensure they don't crash in this scenario and add a note to the readme stating that the samples require media playback to work (but the synthesis and recognition APIs themselves technically do not require it to work)
