### ISSUE TITLE
Navigation Menu sample crash when using the keyboard

### ISSUE THREAD

**Issue by acoles88** [Microsoft/Windows-universal-samples#17]
Not sure if this is just a bug with the beta.  Run the app and press an arrow key.  FocusManager.TryMoveFocus throws an exception --  'System.ArgumentException'

**Comment by micahl** [comment]
It's a bug with TryMoveFocus in the beta that has been fixed in more recent builds.  The sample has been updated as part of 5c0aa623b4356e96759d901b8b432b3e744204bf to use a workaround.  It uses FindNextFocusableElement and then explicitly calls Focus.
