### ISSUE TITLE
Issue when suspending and resuming the background audio sample

### ISSUE THREAD

**Issue by ribas1a3** [Microsoft/Windows-universal-samples#171]
I tried using the background audio sample.
But when I suspend the app and resume it more than 2 times the app crashes.
Sorry I'm not able to give more details about the crash.

**Comment by aarononeal** [comment]
Sorry for the trouble. There are a couple known issues in the sample right now and we're preparing an update to address them. If you can provide a callstack at the time of the crash I may be able to offer a workaround in the meantime, otherwise please stay tuned for a future update.
