### ISSUE TITLE
BooleanToVisibilityConverter incorrect code class

### ISSUE THREAD

**Issue by alexeygritsenko** [Microsoft/Windows-universal-samples#172]
The Convert method is written incorrectly. So he returns Visibility.Collapsed for any enter value.
Shame. He replaced temporarily:
```
 return (Boolean.Parse(value.ToString())) ? Visibility.Visible : Visibility.Collapsed;
```

**Comment by oldnewthing** [comment]
The existing code seems to work fine. I see it returning `Visibility.Visible` if the incoming `value` is `true`. This happens when you open the navigation pane and expand an item.
