### ISSUE TITLE
Web Account Management Unclear

### ISSUE THREAD

**Issue by silverdollarsoftware** [Microsoft/Windows-universal-samples#173]
It's unclear where to obtain the Azure AD credentials from the Azure AD portal. Please provide documentation on where to source the constant strings that appear to be required. There does not appear to be any documentation specifying how to populate those constant strings!

**Comment by tjones0808** [comment]
hi @silverdollarsoftware, check out this link if you havent already figured it out. https://code.msdn.microsoft.com/Windows-Hello-Active-99c01648
