### ISSUE TITLE
WiFiDirect sample does not work on Windows 10 IoT Core

### ISSUE THREAD

**Issue by charlehsin** [Microsoft/Windows-universal-samples#174]
Scenario 1:

For IoT Core, 
       I boot the IoT Core with WiFi dongle plugged in.

For Win 10 Enterprise, 
       I run the sample codes here https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/WiFiDirect . When I search for WiFiDirect devices, I can see “MinWinpc”.  It looks that the IoT Core is starting some WiFiDirect service automatically. I verified that it is my Minnowboard Max.
       If I try to connect my Win 10 Enterprise to IoT Core, I get a prompt to enter “PIN” to start pairing. Normally, such PIN should be shown on the IoT Core part, so that I can use it and enter it on Win 10 Enterprise….. However, IoT Core still shows the normal start-up app. So I cannot connect.

Scenario 2:

For IoT Core, 
I boot the IoT Core with WiFi dongle plugged in. 
Then I remotely start the WiFiDirect sample app https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/WiFiDirect. I start to advertise my device.

For Win 10 Enterprise, 
        I run the sample codes here https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/WiFiDirect . When I search for WiFiDirect devices, I can see “MinWinpc”.  If I try to connect my Win 10 Enterprise to IoT Core, I get a prompt to enter “PIN” to start pairing. 
        At this time, An error shows on the WiFiDirect app on the IoT Core side. The error is “Connect operation threw an exception: The specified module could not be found. (Exception from HRESULT: 0x8007007E)”. And it failed at OnConnectionRequested() function in Scenario1_Advertiser.xaml.cs file, and at the following line:
                Var messageDialog = new MessageDialog(“XXXXXXXX” + XXXXX).
        If I hard-coded the user agreement and tried by-pass the MessageDialog part and run the sample app on IoT Core again and tried the same scenario, I got another Exception when the same function tried to run this line
                tcsWiFiDirectDevice.SetResult(await WiFiDirectDevice.FromIdAsync(connectionRequest.DeviceInformation.Id, connectionParams));
        The error is
                FromIdAsync task threw an exception: System.Exception: Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG))

**Comment by anpilley** [comment]
Hey, The IoT team have their own GitHub sample set you may want to look at [here](https://github.com/ms-iot/samples). I don't believe they support the full set of windows universal APIs yet, so there may well be components of the win10/winphone universal samples that fail to run on IoT for the time being. I'd also double-check the supported hardware list for wifi dongles [here](http://ms-iot.github.io/content/en-US/win10/SupportedInterfaces.htm#WiFi-Dongles)

**Comment by charlehsin** [comment]
Yes. It is the supported WiFi Dongle.... Over the IoT Core samples, there is WiFiDirect sample. So I guess that WiFiDirect APIs are not supported on IoT Core yet?

**Comment by anpilley** [comment]
Questions about support of particular features on IoT should probably be directed to the IoT team (they have an [MSDN forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=WindowsIoT&filter=alltypes&sort=lastpostdesc) ). If you can replicate the failures you're seeing with just two win10 PCs and not using IoT, then that's a different avenue for investigation too.

**Comment by charlehsin** [comment]
Ok. I will mark this as closed.
