### ISSUE TITLE
WiFiDirect sample: Hang after PIN entered..

### ISSUE THREAD

**Issue by charlehsin** [Microsoft/Windows-universal-samples#175]
I have 2 Win 10 Enterprise 64 bits machine. Both running the WiFiDirect samples, using Visual Studio 2015 RTM.

One is advertising, and one is connecting.

After I got the PIN from the advertising computer, I entered the PIN on the connecting computer.
Then it just hang.... I did not get any messages/indications about they are connected..

1 machine is using Net-DYN 802.11n WiFi dongle.
1 machine is using Intel Centrino Advance-N6205.

**Comment by GauravC12** [comment]
I am trying to connect app on two devices (one W10 phone and one Laptop) but unfortunately I always land into issue no matter if It is WiFi Direct or RFCOMM. I am facing the problem stated above, with UI hanging after the PIN is entered. Eventually I receive time out exception on the second device and "a few exceptions" as mentioned in the app on first device. I also sometime receive "Element Not Found" exception which is rather confusing.

**Comment by oldnewthing** [comment]
This is an old issue. If you are still experiencing this problem, comment and I will reopen.
