### ISSUE TITLE
F# Code Samples?

### ISSUE THREAD

**Issue by cdrnet** [Microsoft/Windows-universal-samples#177]
Thanks for putting these samples together, even in multiple languages. Any chance we can get some of them in F# as well?

**Comment by NumberByColors** [comment]
@cdrnet There isn't support for writing Universal Windows apps with F#, yet. First step is finishing the .NET Native compiler so it supports the IL generated for F# code (tail calls, deeply nested generic types, etc.). This is in progress, but there's lots of work left to do...

Once support exists, what kinds of Windows apps do you want to build with F#?
