### ISSUE TITLE
filepicker - Save a File demo doesn't work on mobile

### ISSUE THREAD

**Issue by x3haloed** [Microsoft/Windows-universal-samples#18]
Steps to reproduce:

1) Start a debug session of the latest version of the filepicker demo in the phone emulator, running Windows version 10.0.12552.70.
2) Tap "4) Save a file" in the navigation menu
3) Tap the "Save file button"
4) Observe that the OutputTextBlock text immediately reads "Operation cancelled."

**Comment by arunjeetsinghms** [comment]
This has been identified as a bug with the emulator that might already have been fixed. We're confirming that. In the meantime, if you have access to a physical device the last Windows Phone build we shipped via the Windows Insider program (10080) should work with that sample. I just tried this on a device running 10080 myself and tapping Save File brought up a picker with "This Device" and my SD card as options.

**Comment by x3haloed** [comment]
Okay, I understand. Thank you!
