### ISSUE TITLE
Background Audio Sample Issue

### ISSUE THREAD

**Issue by LtCmdrKeene** [Microsoft/Windows-universal-samples#180]
The BackgroundAudio sample will build and run, but clicking on a audio sample in the app causes a 10 second freeze followed by the exception:

```javascript
throw new Exception("Background Audio Task didn't start in expected time");
```

I'm testing this out this unmodified sample on a Surface Pro 3, Windows 10 RTM running VS 2015 Pro.

**Comment by aarononeal** [comment]
Can you tell me what build architecture of Windows you're running on the Surface Pro 3 and what architecture you're targeting in VS? There was an early platform bug where running different architectures (x32 on x64) didn't work but this should have been addressed. 

Can you also try extending the timeout in the sample code to 20 seconds to see if that makes a difference?

**Comment by LtCmdrKeene** [comment]
Surface is running x64 flavor of Windows 10 (RTM build). I'm targeting x86 in VS but both had the same failure.

But now as I go to run it, it works on both of them.  I had previously rebooted several times, opened and closed this project a half-dozen times, but now it's great. I haven't a first clue as to why. Sorry for the trouble!
