### ISSUE TITLE
Projection Sample causes 100% UI thread utilization

### ISSUE THREAD

**Issue by brreitme** [Microsoft/Windows-universal-samples#181]
On Windows 10 and VS 2015 launch the Projection Sample with Debug -> Start Diagnostic tools without debugging. (Choose CPU and timeline)

As soon as you launch the projection you will see the UI thread utilization go to 100% and stay there until the projection is closed. I cant figure out how to get a decent frame rate when projection is enabled because of this.

![uithread](https://cloud.githubusercontent.com/assets/12140397/10300576/fd7ba63e-6bbd-11e5-8ba1-0f70bb793ec0.jpg)

**Comment by brreitme** [comment]
This seems to only happen with the C# version.

**Comment by sparkyish** [comment]
Any update on this? The issue still seems to be present. Thank you!

**Comment by srdjanjovcic** [comment]
I investigated this issue, and it does not repro in Visual Studio 2017
