### ISSUE TITLE
namespace System didn´t find it

### ISSUE THREAD

**Issue by johnnyps16** [Microsoft/Windows-universal-samples#182]
Hello, I have this problem with every namespace of System like:

using System;
using System.Collections.Generic;
using System,Threading.Tasks;
etc..

But it just happen when open a project from Windows-Universal.samples.
When I create a new project everything is alright and don´t get this error message of not found

Actually when I tried, for example, debug the Blinky project on my raspberry 2 with Windows 10 IoT I have not troubles running it, it just shows up as error on Visual Studio 2015 but doesn´t avoid the debug.

Looking into other issues i found that i just have to add some references but when I try it i cant find any reference option. Unless I have to search them at first. But in the space of Assemblies->Frameworks is in empty.

The problem is that this doesn´t me look real erros if I want to modify the project.

**Comment by oldnewthing** [comment]
Try cleaning and rebuilding. The references are supposed to be pulled down by NuGet.

**Comment by oldnewthing** [comment]
Did cleaning and rebuilding fix the problem?

**Comment by gardavis** [comment]
I have the same issue with the System reference missing on the samples. Attaching one sample's VS2015 screenshot. Clean and recompile did not help.

Thanks,
Gary Davis

![screenshot-win10sampleserror](https://cloud.githubusercontent.com/assets/2693330/10717917/0cbfb33c-7b3c-11e5-8d3f-ba3bdaeeee79.jpg)

**Comment by oldnewthing** [comment]
Hm, works for me. The only difference I can see is that mine has a reference to `Microsoft.NETCore.UniversalWindowsPlatform`. That gets inserted from the `project.json` at build time. Looks like it's not working for you. I can't explain. Sounds like a VS problem. ![untitled](https://cloud.githubusercontent.com/assets/12550607/10721629/33cfbdfa-7b64-11e5-8323-6b2c6c3cae86.png)

**Comment by jerrak0s** [comment]
I had some of those errors. Be careful for the shared folder and the structure of projects. Enter projects inside samples folder

![capture](https://cloud.githubusercontent.com/assets/3514710/10722981/d67f0312-7bbe-11e5-8aa1-e9dd0d422771.PNG)

**Comment by oldnewthing** [comment]
True, you have to grab the entire git repo (not just the one directory for the sample you are interested in) because the samples use links to conserve disk space. This is called out on the samples home page

> [**Reminder**](https://github.com/Microsoft/Windows-universal-samples/): If you unzip individual samples, they will not build due to references to other portions of the ZIP file that were not unzipped. You must unzip the entire archive if you intend to build the samples.

and is reiterated in each sample:

> [**Build the sample**](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/BasicInput)
> 1.If you download the samples ZIP, be sure to unzip the entire archive, not just the folder with the sample you want to build.

**Comment by gardavis** [comment]
Yes, initially, I did extract just the one sample and compiling it failed with the missing System DLL reference. I then unzipped the entire archive file and tried again with the same problem. The shared files are correctly linked (none are DLLs or references).

I will try manually adding the reference you pointed out. There may be something screwy with my VS2015 install. I do notice a problem trying to load Win 8.1 projects and it complains that some SDK was missing and leaves the project unloaded. So I've been using VS2013 for those.

Thanks for your comments.

**Comment by oldnewthing** [comment]
I would recommend a full purge of the directory (get rid of the `project.json.lock` and other related stuff), make sure you start with a clean slate.

**Comment by oldnewthing** [comment]
Grasping at straws: Do you have your target set to "Any CPU" by any chance? Try switching to x86 or x64.

**Comment by gardavis** [comment]
I did try changing it. I think it started as ARM and then I switched to x64. It did not help.

**Comment by jerrak0s** [comment]
Did you try rebuilding solution?

**Comment by gardavis** [comment]
Rebuilding did not help. I then tried a repair of VS 2105 and it still did not help. I tried adding a reference and saw this: "no framework assemblies were found on the machine"  . For the UWP, there were references to add but not the one shown above (Microsoft.NETCore.UniversalWindowsPlatform).

**Comment by gardavis** [comment]
I found a solution to getting the missing reference back from:

http://stackoverflow.com/questions/32607616/visual-studio-2015-c-sharp-windows-universal-app-missing-assembly-reference/32607617#32607617

In my case, NuGet said the Microsoft.NETCore.UniversalWindowsPlatform was already installed. The above post said to install it. I then did an uninstall followed by an install and the missing reference was back.

I compared the initial folder with the one after the install and found that the difference was that there was a ProjectLock.json file following the install.

A bit faster way to avoid the uninstall, just remove the Microsoft.NETCore.UniversalWindowsPlatform dependency from project.json and refresth the NuGet installed packages and you won't see it as installed anymore. Then search for the package and install it. If there are multiple projects in the sample solution as in RfcommChat, do this for all the projects that need it.

I am not sure why this is required, at least for me. When I tried a blank UWP new solution/project, it created and compiled just fine with the NETCore installed and referenced.

**Comment by devkhan** [comment]
I was facing the same problem, but restoring the packages solved the problem.

I think this should be closed now.

**Comment by JohnVisioMVP** [comment]
The issue may be due to the fact that the samples were created with an older version of Microsoft.NetCore.UniversalWindowsPlatform than is installed on your machine. I had the same issues, selected References from the Solution Explorer, right clicked and selected Manage Nuget and updated the reference. Everything then was error free.

**Comment by masums** [comment]
At vs 2017RC showing same error.
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0234	The type or namespace name 'Identity' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)	TestApp.UWP	C:\Users\Masum\documents\visual studio 2017\Projects\TestApp\TestApp\ViewModel\LoginViewModel.cs	11	Active

**Comment by Eubur** [comment]
after trying to run project (by clicking green Debug button) issues resolved

**Comment by DongMyongJong** [comment]
In my case, this problem is solved by update NuGet packages. The type of my project is SAP. First, right click the UWP project and select the context menu item "Manage NuGet Packages...". Next, select Updates tab and update Microsoft.NetCore.UniversalWindows and Xamarin.Forms packages. Finally, these packages  is added to References of UWP project and is successfully solved this problem.

**Comment by tensarflow** [comment]
For me updating the NuGet Package Microsoft.NETCore.UniversalWindowsPlatform solved the problem, too.
