### ISSUE TITLE
Wide tile not updating UWP apps windows 10 mobile

### ISSUE THREAD

**Issue by winitwindowsphone8** [Microsoft/Windows-universal-samples#183]
I am facing problem in updating wide live tile while switching from Square Tile to Wide Tile in windows universal app development. It is working fine in windows surface and Desktop but coming to phone it is not updating Wide tile could any one please help me? By default Wide Tile is working fine for us but when we change it from Square Tile to wide tile it is not working in emulator.
Sample Code

TileUpdateManager.CreateTileUpdaterForApplication().EnableNotificationQueue(true); TileUpdateManager.CreateTileUpdaterForApplication().Clear();
var _tileXml = TileUpdateManager.GetTemplateContent(TileTemplateType.TileSquare150x150PeekImageAndText03); var tileImage = _tileXml.GetElementsByTagName("image")[0] as Windows.Data.Xml.Dom.XmlElement; tileImage.SetAttribute("src", "ms-appx:///Assets/Logo.png"); var tileText1 = _tileXml.GetElementsByTagName("text"); (tileText1[0] as Windows.Data.Xml.Dom.XmlElement).InnerText = "Title"; (tileText1[1] as Windows.Data.Xml.Dom.XmlElement).InnerText = "Hello"; (tileText1[2] as Windows.Data.Xml.Dom.XmlElement).InnerText = "Hii"; (tileText1[3] as Windows.Data.Xml.Dom.XmlElement).InnerText = "World"; var tileNotification = new TileNotification(_tileXml); TileUpdateManager.CreateTileUpdaterForApplication().Update(tileNotification);
var tileXml = TileUpdateManager.GetTemplateContent(TileTemplateType.TileWide310x150SmallImageAndText02); var widetileImage = tileXml.GetElementsByTagName("image")[0] as Windows.Data.Xml.Dom.XmlElement; widetileImage.SetAttribute("src", "ms-appx:///Assets/Logo 48x48.scale-200.png"); var WidetileText = tileXml.GetElementsByTagName("text"); (WidetileText[0] as Windows.Data.Xml.Dom.XmlElement).InnerText ="Title"; (WidetileText[1] as Windows.Data.Xml.Dom.XmlElement).InnerText = "Wide"; (WidetileText[2] as Windows.Data.Xml.Dom.XmlElement).InnerText = "Tile"; (WidetileText[3] as Windows.Data.Xml.Dom.XmlElement).InnerText = "displaying"; (WidetileText[4] as Windows.Data.Xml.Dom.XmlElement).InnerText = "hii"; TileUpdateManager.CreateTileUpdaterForApplication().Update(new TileNotification(tileXml));
Thanks
Winit windows team

**Comment by anbare** [comment]
Dupe question that was already answered on MSDN: https://social.msdn.microsoft.com/Forums/windowsapps/en-US/2624c8de-5036-4f55-ac69-d73b4227c563/uwpwide-tile-not-updating-uwp-apps-windows-10-mobile?forum=wpdevelop
