### ISSUE TITLE
SmsSendAndReceive example has differences between readme and MSDN doc 

### ISSUE THREAD

**Issue by dpierangeli** [Microsoft/Windows-universal-samples#184]
In the readme of that example is said that the MessageChat is a special permission but in the MSDN link it says that is a general permission.

Also there is al link to the Windows.Devices.Sms, but in the linked document it says that "This is not the recommended API if you are developing an alternative to the built-in messaging app. Instead, you should use the Windows.AppModel.Chat API for developing messaging apps. "

Maybe the example was not updated for windows 10?

**Comment by DelfCo** [comment]
The readme is correct, and I've filed an internal documentation bug to get the permissions page on MSDN corrected. 

The documentation for Windows.Devices.Sms is correct. The API in that namespace is a low-level API intended for use by mobile operators that push information to apps on devices by using SMS to send data. (For example, an MO might send an SMS to their voicemail app, to indicate the current number of unheard voice mails.) Such messages aren't visible to the end user. This sample shows the mobile operator's developers how to send those messages.

The Windows.AppModel.Chat API is the high level API that aggregates messages for device users, and it's the proper way to do SMS (and other message types) for end users. Note that the Chat API is also controlled by a special permission.
