### ISSUE TITLE
About Gridview  question,

### ISSUE THREAD

**Issue by superbderrick** [Microsoft/Windows-universal-samples#186]
Hi, I am making a simple Girdapp using Windows-universal-samplecode(Listview part).
How can I  change  Gridview shape When I changed source data  that relative to Gridview  during Runtime? 
Regarding to Sample code, When page create It seems to setup  data to make gridview.
like this 
    public SimpleGridViewSample()
        {
            this.InitializeComponent();
            ContactsCVS.Source = Contact.GetContactsGrouped(250);
        }

 When I change to  data , it didn't change Gridvew figure on the page 
It seem to need method to update gridview or source for make gridview.

Like this ,
forexample.
    private void AppBarPlayButton_Click(object sender, RoutedEventArgs e)
        {
            ContactsCVS.Source = Contact.GetContactsGrouped(12);
           
           Do I have to call added methods? 
           Example.,
            ContactsCVS.. view( )????
            ContactsCVS...()?????
        }

Thanks You
Derrick

**Comment by oldnewthing** [comment]
The issue you are running into is not about a broken sample and requires additional debugging to further isolate the problem you are experiencing. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
