### ISSUE TITLE
About Touch keyboard

### ISSUE THREAD

**Issue by waterfall531** [Microsoft/Windows-universal-samples#187]
I try use Javascript to make APP,but I can't let Keyboard show it up.

Plz

**Comment by oldnewthing** [comment]
Are you referring to the TouchKeyboard sample? There is no JavaScript version of that sample.

**Comment by waterfall531** [comment]
yep, But I still need it at Javascript.
Maybe u give me some suggest.

**Comment by oldnewthing** [comment]
Sorry, I thought you were saying that you had a problem with the (nonexistent) JS TouchKeyboard sample. For JS, the keyboard appears automatically when focus goes onto an `<input>` element.

**Comment by waterfall531** [comment]
So ,if it <input> that

that is my code
form>
input type="email" id="email">
input type="password" id="password">
input type="text" id="activationCode">
form>
it is not work ,sorry

**Comment by oldnewthing** [comment]
I checked with the feature team. You have to be running Insider build 10565 or higher to see the keyboard come up. You also have to be in Tablet mode, and you cannot have a physical keyboard attached.

**Comment by waterfall531** [comment]
Sorry to bother you!
that's is my mistake.
Thx a lot

**Comment by oldnewthing** [comment]
No need to apologize. You didn't make a mistake. Good to know things are straightened out.
