### ISSUE TITLE
Error when opening AppWebviewComm example

### ISSUE THREAD

**Issue by bwarner34** [Microsoft/Windows-universal-samples#188]
When I run the WebView solution and navigate to example 10 regarding communication between the Webview and the app, I get an immediate "No such interface supported" error when the script code tries to call checkPrimesInRange.  I can see the method defined in Intellisense, but calling it always leads to this error.

**Comment by oldnewthing** [comment]
Okay, I see what's wrong. Fixing this is going to be tricky.

**Comment by oldnewthing** [comment]
This was fixed in [v1.0.27](https://github.com/Microsoft/Windows-universal-samples/releases/v1.0.27)
