### ISSUE TITLE
ChatMessageNotificationTriggerDetails appxmanifest issue

### ISSUE THREAD

**Issue by badplanet** [Microsoft/Windows-universal-samples#189]
For Tony Pendolino:

Hey Tony,

 I am trying to intercept SMS messages in the background using the example at:

https://msdn.microsoft.com/en-us/library/windows/apps/windows.applicationmodel.chat.chatmessagenotificationtriggerdetails.aspx?f=255&MSPPError=-2147217396

I can't get the following to work in vs appxmanifest

Extension Category=”windows.backgroundTasks” Entry-Point=”Tasks.ExampleBackgroundTask"
  BackgroundTasks
    Task Type=”chatMessageNotification"
    Task Type=”systemEvent"
 BackgroundTask
Extension

VS doesn't like:

 Task Type=”chatMessageNotification”

Do you have any suggestions what I should use?

Sorry I had to remove the greater than and less than characters to get examples to show example...

 Thanks,
 Greg

**Comment by oldnewthing** [comment]
As noted on the other thread, you need to say `<uap:Task Type="chatMessageNotification"/>` with the `uap` namespace prefix on the `Task` element.

**Comment by badplanet** [comment]
oldnewthing - Thank you very much!! VS does not complain now!!! I need to get testing....
