### ISSUE TITLE
VoIP - CPU and RAM restriction

### ISSUE THREAD

**Issue by mbencer** [Microsoft/Windows-universal-samples#190]
Where I can find information about CPU and RAM restrictions VoIP application which is run in background? I've done some tests and results are following: any CPU restriction, 200 MB RAM in foreground and additionally +20 MB in background (1GB RAM phone, for 512 MB RAM phone: 120 MB in foreground and +20 MB in background). Have somebody some official information about it ?

**Comment by oldnewthing** [comment]
This isn't a problem with a broken sample. You can open a support case with our Developer Support team. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
