### ISSUE TITLE
XamlPullToRefresh sample exception on release build

### ISSUE THREAD

**Issue by BradStevenson** [Microsoft/Windows-universal-samples#191]
When running the XamlPullToRefresh in release mode on 10565 (desktop).

App crashes as soon as list is scrolled over -
Unhandled exception at 0x7523797E (combase.dll) in XamlPullToRefresh.exe: 0xC000027B: An application-internal exception has occurred (parameters: 0x0A5D3470, 0x00000002).

Then -
Unhandled exception at 0x75237817 (combase.dll) in XamlPullToRefresh.exe: 0xC0000602:  A fail fast exception occurred. Exception handlers will not be invoked and the process will be terminated immediately.

**Comment by oldnewthing** [comment]
Pull-to-refresh is [now a built-in control](https://github.com/Microsoft/Windows-universal-samples/tree/v6.0.2/Samples/XamlUIBasics/cs/AppUIBasics/ControlPages/PullToRefreshPage.xaml), so the XamlPullToRefresh sample is obsolete and has been deleted in the dev branch.
