### ISSUE TITLE
Basic media Casting media ended event not fired on mobile

### ISSUE THREAD

**Issue by RagBuster** [Microsoft/Windows-universal-samples#192]
I am finding that the basic media casting example which I slightly modified to allow file types mp3 so I could select songs does not fire a media element ended event when casting to my Denon receiver. 
The media element fires if not connected to anything but does not if connected and casting. Running the same code on win 10 desktop works fine either way.
Is this a known issue?
My repro package : https://www.dropbox.com/s/p832ylfowt0oel4/BasicMediaCasting.zip?dl=0
Perform test 1, select a song and cast to dlna device, media element ended event never gets called.

**Comment by RagBuster** [comment]
Can anyone investigate this as I am still having this issue, hoped that the new SDK and possibly the new phone builds would have corrected it but it is still broken.

**Comment by aarononeal** [comment]
Sorry we haven't gotten back to you with an answer yet. I've reached out to the casting team for an update.

**Comment by RagBuster** [comment]
Any update yet? still no recognition of the problem or a fix. Is there a direct channel to post feedback too for these kind of problems?

**Comment by aarononeal** [comment]
I have reached out to the casting team again and asked them to respond directly. Casting does take a separate code path so it is entirely possible there is a platform bug to address here.

**Comment by aarononeal** [comment]
We are preparing new samples to address this issue.
