### ISSUE TITLE
PhoneCallOriginDataRequestTriggerDetails what is the trigger for this?

### ISSUE THREAD

**Issue by badplanet** [Microsoft/Windows-universal-samples#193]
I understand how PhoneCallOriginDataRequestTriggerDetails id used in the background but I cannot figure out what the trigger is for this class. I tried PhoneCallOriginDataRequestTrigger but that does not work.

Any help is greatly appreciated.....

**Comment by oldnewthing** [comment]
`new PhoneTrigger(PhoneTriggerType.CallOriginDataRequested)` is the trigger.

**Comment by badplanet** [comment]
oldnewthing - Thank you. I am amazed by your detailed knowledge of these APIs.

**Comment by soroshsabz** [comment]
ITNOA

Hi, what is meaning of CallOriginDataRequest and when it trigger?

**Comment by oldnewthing** [comment]
See the CallerID sample.
