### ISSUE TITLE
VoIP - New VoIP APIs failed in pc with the preview version

### ISSUE THREAD

**Issue by jeslat** [Microsoft/Windows-universal-samples#194]
We are developing a universal VoIP app with the new APIs. Starting with the example provided here, we have developed the phone version successfully and it works fine. The problem has started when we have tried to run the same in PC. 

To be sure about the problem we have used the VoIP example changing the next things:
- We've changed the version and the minimum version to 10.0.10563.0 to use the preview version of the SDK.
- We've removed the phone contract checks to be able to run it in PC.
- We've removed the Windows Mobile Extensions for the UWP because if the VoIP APIs are available for all the platforms it isn't necessary.

The application compiles but when we run it an exception is thrown when we call to `await vCC.ReserveCallResourcesAsync(Current.RtcCallTaskName);` in `VccCallHelper.cs` or when we try to call to `RequestNewOutgoingCall` or `RequestNewIncomingCall`. The exception is 
```
System.Exception
Element not found. (Exception from HRESULT: 0x80070490)
```

Do we have to use different APIs in PC? Are these APIs not available yet in the preview version of Windows 10?

Thanks in advance

**Comment by degoh** [comment]
Do you have the version number of the preview you have?

The APIs are currently available for use for phone development only.  We are in the process of adding these APIs to Desktop with future updates to Windows 10. I apologize for any inconvenience caused.

**Comment by jeslat** [comment]
I'm using the build 10565 to run the application. I expected that these APIs were already available in desktop in this version but if not, I'll wait for future releases.

Thanks for the answer

**Comment by iband** [comment]
Are there any updates on this? I have Windows 10.0.17134.1 and get the same error.
