### ISSUE TITLE
Can NOT run the sample (mediaimport) in Visual Studio 2015 on Windows 10 build 10565

### ISSUE THREAD

**Issue by HppZ** [Microsoft/Windows-universal-samples#195]
can not resolve assembly system runtime...and many many other errors

**Comment by oldnewthing** [comment]
Is this a runtime error or a build error? The dependent assemblies are installed by NuGet. Try cleaning the project, then rebuilding it. I was able to build the MediaImport sample clean on my machine and run it. The deploy step should say something like "Instalilng missing frameworks."

**Comment by jerrak0s** [comment]
I had the same issue. Be careful for the shared folder and the structure of projects. Enter projects inside samples folder
![capture](https://cloud.githubusercontent.com/assets/3514710/10722823/158e3e58-7bbd-11e5-9e7d-88a037d541cd.PNG)

**Comment by oldnewthing** [comment]
Please confirm that you unzipped the entire samples repo. (Rather than unzipping just the sample you are interested in.)

**Comment by mfe-** [comment]
Hi, I have the same Issue with all samples. I unzipped the entire zip file. When i open any solution of the sample i get errors like:
Error	CS0246	The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)	BarcodeScanner	C:\[...]\.NETCore,Version=v5.0.AssemblyAttributes.cs	2
I think there is the Microsoft.NETCore.UniversalWindowsPlatform Reference missing. How can I add it?
![ref missing](https://cloud.githubusercontent.com/assets/3492683/10964575/45259380-83a8-11e5-9c17-a60d090486e7.png)

**Comment by mfe-** [comment]
Hey, again me :) I solved the problem with the missing assembly reference with this guide:
https://github.com/Windows-XAML/Template10/wiki

**Comment by oldnewthing** [comment]
Looks like the problem is solved.
