### ISSUE TITLE
Sample  for Bluetooth Printer Integration for Windows App Store using C#

### ISSUE THREAD

**Issue by sandeepmsandy** [Microsoft/Windows-universal-samples#198]
Hi Sir,

Please update on Sample  for Bluetooth Printer Integration for Windows App Store using C#

With Regards,
Sandeep M

**Comment by oldnewthing** [comment]
I've asked the feature team to investigate.

**Comment by AlperTheGreat** [comment]
Hi,
There is no separate API for BT printers. You can install a BT printer to Windows. The printer will be listed as an available option to your app.
Thanks
