### ISSUE TITLE
Missing support/api for video calling in a VoIP app

### ISSUE THREAD

**Issue by mruf** [Microsoft/Windows-universal-samples#199]
For the video calling part of our voip app for WP8 we used MediaStreamer and MediaStreamerFactory in the Microsoft.Phone.Media namespace. In the background process we created a MediaStreamer instance through the factory which we could then access from the ui process using a uri. This uri could then be plugged into a media element as the source of the video stream. 

As of Windows 10 this API does not seem to exist anymore. What options are available to provide a video stream from the background process of a voip app to the ui process?

The voip sample for WP8 also showed the video calling part. Unfortunately the Windows 10 voip sample is currently audio only.

**Comment by Vanhara** [comment]
Hello, I am also joining this issue. In current API there is classes for capturing and playing video on screen (directly from object not from stream/buffer etc.) and from/to file. But no similar approach like WASAPI is missing (I didn't find it). 
Thanks

**Comment by oldnewthing** [comment]
This isn't a question about a sample, but rather is a question about OS functionality. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
