### ISSUE TITLE
need Javascript samples.

### ISSUE THREAD

**Issue by SteveALee** [Microsoft/Windows-universal-samples#2]

**Comment by AdamBraden** [comment]
They are on their way.  In an effort to be more transparent, this was just an early drop from teams to go with the first Developer Preview.  Expect more at //build, and the rest by RTM.

**Comment by SteveALee** [comment]
Great, And I guess a new book edition from Kraig Brockschmidt? :)

**Comment by limefrogyank** [comment]
And do them in typescript since WinJS is written in typescript now :)
