### ISSUE TITLE
General comments

### ISSUE THREAD

**Issue by rcroeder** [Microsoft/Windows-universal-samples#20]
Nice start. Basic navigation on the samples i have tried appears to have the same flaw. Using Lumia 630 with latest build from the week of 5/5/2015. The flaws are as follow, back button no longer navigates between pages on phone, i understand that there is no back button on the desktop/tablet but it breaks a consistant feature of Windows phone from 7.0

Second, when starting the any app, pressing the link such as 1) Do this, . the pages disappears, i have to recall it by the hamburger menu then it works fine. I will have a look at these in the next couple of days.

Is there going to be a forum/discussion area on app design? I noticed in the latest release, the sizes of the tiles have changed slightly of the start page.

**Comment by AdamBraden** [comment]
The sample template uses a new flyout menu - it is not a separate page.
General discussion on Windows App development can be directed to this forum:
https://social.msdn.microsoft.com/Forums/en-US/home?forum=wpdevelop&filter=alltypes&sort=lastpostdesc
