### ISSUE TITLE
Error "security status not satisfied", SW1 = "69", SW2 = "82", when running restore of Mifare Classic.

### ISSUE THREAD

**Issue by DiegoSousa** [Microsoft/Windows-universal-samples#200]
I'm trying to use a restore command using the lib PcscSdk but I'm just getting a response 6982 - security status not satisfied.

What should I do?

The command was used:

FF C2 00 03 0E
            0C A1                 // decrement 
            80 01 05             // block 5 and 
            80 01 06             // restore to block 6 
            81 04 01 00 00 00   // value = 1

As demonstrated in: http://www.pcscworkgroup.com/specifications/files/pcsc3_v2.01.09_amd1.pdf

The increment, decrement, write and read, they are working perfectly.

I appreciate any help.

**Comment by oldnewthing** [comment]
This appears to be a problem with your own program, not a problem in the Nfc sample. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
* Visit http://aka.ms/storesupport and sign-in with your Microsoft account.
* Under the “App Development” section choose the appropriate type – such as Building apps and games, and then choose from the Problem type/Category to get engaged through a formal support channel.
