### ISSUE TITLE
WebAuthenticationBroker.AuthenticateAsync method, used in Windows Phone 8.0, is not supported. 

### ISSUE THREAD

**Issue by dengere** [Microsoft/Windows-universal-samples#204]
Hi,
ooauth2 library document 
https://developers.google.com/api-client-library/dotnet/guide/aaa_oauth
tells that "The Windows Phone 8.1 authentication API is not compatible with the Windows Phone 8.0 authentication API. The WebAuthenticationBroker.AuthenticateAsync method, used in Windows Phone 8.0, is not supported anymore. Starting with Windows 8.1, Microsoft supports several AndContinue methods, one of them is WebAuthenticationBroker.AuthenticateAndContinue."

sample used WebAuthenticationBroker.AuthenticateAsync could you please update?

**Comment by msftchcamp** [comment]
Thank you for your feedback. This was true for 8/8.1 but for Windows 10 Universal Apps this is not anymore. Please refer to the requirements on the API documentation:

https://msdn.microsoft.com/en-us/library/windows/apps/br212067.aspx
