### ISSUE TITLE
XamlDragAndDrop doesn't work on Phone Device or Emulator

### ISSUE THREAD

**Issue by abdu292** [Microsoft/Windows-universal-samples#205]
The drag and drop (Scenario 2 and 3) are not working on Windows Phone or Windows Phone Emulator.
I am not talking about a full-fledged  drag and drop, however I am expecting the very basic drag & drop to work on UWP Phones (Scenario 2 for example).
It is kind of critical for my project. Any help on the resolution? Thanks.

**Comment by benznest** [comment]
I have the same problem. it does not work on Windows 10 mobile both emulator and actual device but it still work on Windows 10 local machine x86 x64.

**Comment by strangelimey** [comment]
I see the same issue.
Drag-drop only works for ListView and GridView on windows 10 mobile device and emulator.

Is this a bug or by design?

**Comment by mandia1204** [comment]
Hi, I have the same issue.

do you have a workaround for this?

**Comment by abdu292** [comment]
@mandia1204 Not yet. It looks like untouched so far.

I am not sure how we windows developers can make Windows Phone a success if they don't address the issues for us. This issue was created almost an year ago.

**Comment by LazyGepid** [comment]
I'm finding that drag & drop doesn't seem to be working on Mobile.  After banging my head trying to figure out what hidden "gotcha" I overlooked, I find that.  WHAT'S GOING ON!  Why isn't drag & drop working?  Hello?!

**Comment by oldnewthing** [comment]
Yup, Drag/Drop on Phone works only in ListView and GridView.
