### ISSUE TITLE
Complex Ink sample needed in C#

### ISSUE THREAD

**Issue by halocameo** [Microsoft/Windows-universal-samples#206]
Need a C# version of the Complex Ink sample located at https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/ComplexInk

**Comment by kellylawson** [comment]
I'd also like to see this if possible.

**Comment by FranciszMicrosoft** [comment]
Duly noted.  It's on our backlog and I'm hoping to release one later this year.

**Comment by halocameo** [comment]
I don't think this should be closed until this is completed. Just a promise of doing something in the future is not enough to close an open issue. Please reopen it!

**Comment by LtCmdrKeene** [comment]
It's not an issue of something that needs "fixed'.  nothing is broken.

**Comment by ganeshmahajan1985** [comment]
Hi @FranciszMicrosoft , Any updates on this ?

**Comment by daljit97** [comment]
Would be very interested in this as well. Also it would be nice if a sample using Win2d could be provided.

**Comment by James-the-Tech** [comment]
In Microsoft Visual Studio, it has to have code from here in Gethub to be completed as a hand drawn project and enable the OS to follow your pen drawn lines, boxes, circles.

https://docs.microsoft.com/en-us/windows/uwp/design/input/ink-walkthrough
