### ISSUE TITLE
PrintSample (Oct '15) kills WiFi on phone build 10581

### ISSUE THREAD

**Issue by GeraldMaffeo** [Microsoft/Windows-universal-samples#207]
Consistently happens on 2 different phones (Lumia 920 and Lumia 635). a few seconds after the basic scenario print dialog opens and immediately after preview page  is rendered (although that may not be directly related.) 

Settings | Network Wi-Fi toggle pops dialog saying "Can't do this right now - Try again in a little while..." I have to restart the phone to get WiFi back.

This is locking my UWP app testing :(

**Comment by oldnewthing** [comment]
This sounds like a platform bug, not a samples bug.

**Comment by GeraldMaffeo** [comment]
I agree, but I couldn’t find a decent place to report it – none of the categories seemed to fit. And since the official PrintSample breaks it, I figured that’s a good starting point J

 

Are you the same Raymond I knew years ago on the shell team?  I was responsible for the no-hangs program at that time? I’ve been retired from Microsoft for 6 years now. Having fun developing apps.

 

Gerald

**Comment by oldnewthing** [comment]
Hey, Gerald, yes I remember you. Maybe http://aka.ms/storesupport will be able to direct you better. Good luck with the apps.
