### ISSUE TITLE
Setting new window's title on Phone - MultipleViews Sample

### ISSUE THREAD

**Issue by konradkalemba** [Microsoft/Windows-universal-samples#208]
Hi, I had deployed "MultipleViews" solution to my phone and then I tried to create new window. Everything was okay until I set title and it didn't update. In phone's system switcher all this app's windows are titled the same. Is (or will be) there a way to set own title of new window on Windows 10 Mobile?

 ![wp_ss_20151106_0001 1](https://cloud.githubusercontent.com/assets/8682104/10984569/90323654-841a-11e5-9195-50afbfaf7d75.png)

**Comment by oldnewthing** [comment]
Sorry about that. The feature team is looking at addressing this in a future version of Windows. Today, all of your app windows will have the same title on Phone. Again, our apologies.

**Comment by konradkalemba** [comment]
No problem! Thanks for the reply. :) By the 'future version of Windows' you meant new build or something bigger like 'Threshold 2' if I can ask?

**Comment by oldnewthing** [comment]
I don't think they've decided yet.
