### ISSUE TITLE
Picture of the running sample would be really usefull

### ISSUE THREAD

**Issue by sebagomez** [Microsoft/Windows-universal-samples#209]
I find myself many times downloading and executing samples to see they have what I need, and most of the time a small screenshot of the sample would have be good enough.
So, what do you guys think of having and image of the sample in the read.me file of the sample?

I could send a couple of PR from what I have

**Comment by oldnewthing** [comment]
The samples are mostly text, so a small screen shot would give you tiny text that you can't read, which doesn't really help. Also, the samples typically have multiple scenarios, and a screen shot per scenario quickly gets out of hand. In general, we try to avoid putting images in the repo to keep the repo size down.
