### ISSUE TITLE
VoIP Sample doesn't work after update Windows 10 Mobile

### ISSUE THREAD

**Issue by mbencer** [Microsoft/Windows-universal-samples#210]
Hello! When I update my phones to new version of Windows 10 Mobile (a week ago) VoIP sample stop work correctly. The problem is in the place when ReserveCallResourcesAsync method is called (ResourcesNotAvailable is returned all the time). Have somebody idea how to resolve this problem?

**Comment by jeslat** [comment]
I have the same problem, with 10.0.10581.0 the example of VoIP doesn't work. Some kernel exceptions are thrown and the voip host dead.

**Comment by Maksim-Khobat** [comment]
The issue remains in 10.0.10586 build.

**Comment by mruf** [comment]
Same issue here. After updating our phones and SDK to 10.0.10586 we also receive the "Element not found" exception mentioned by jeslat when calling any API function on the VoipCallCoordinator.

**Comment by abdulhs** [comment]
You need to make following changes in the sample in order to make it work with latest release:
1- Add ``` <uap:Extension Category="windows.voipCall"></uap:Extension> ``` under ```  <Extensions>  ``` to Package.appxmanifest under Voip folder.

* Code snippet

```XML
     <Extensions> 
         <uap:Extension Category="windows.voipCall"></uap:Extension> 
         <Extension Category="windows.backgroundTasks" EntryPoint="VoipTasks.CallRtcTask"> 
           <BackgroundTasks ServerName="VoipHost"> 
             <Task Type="systemEvent" /> 
           </BackgroundTasks> 
         </Extension> 
         <uap:Extension Category="windows.appService" EntryPoint="VoipTasks.AppService"> 
           <uap:AppService Name="VoipTasks.AppService" ServerName="VoipHost" /> 
         </uap:Extension> 
       </Extensions> 
```

2- since now VCC api are supported on desktop replace "Windows.Phone.PhoneContract" VoipCallHelper.cs  under Voip\Helpers\  with "Windows.ApplicationModel.Calls.CallsVoipContract"

**Comment by mruf** [comment]
Thanks abdulhs, that fixed the problem.

**Comment by jeslat** [comment]
Thank you @abdulhs for the answer
