### ISSUE TITLE
POS printing

### ISSUE THREAD

**Issue by GregorSpagnolo** [Microsoft/Windows-universal-samples#212]
The issue is more or less the same as pointed out here:
https://github.com/Microsoft/Windows-universal-samples/issues/117#issuecomment-156569294

I have two printers:
1 EPSON TM-T20II USB 
1 OCPP-M05 Bluetooth + USB 

non of the listed printers is working with PosPrinter Class.  Details are explained in post under issue 117. 
Or is there a list of supported devices for PosPrinter Class?

**Comment by atastrumf** [comment]
Have you found any solutions? I am also trying to figure this out, but it seems there is just no way of making this work..

**Comment by TerryWarwick** [comment]
Gregor,

Please refer to the Windows.Devices.PointOfService documentation for POSPrinter on MSDN for details about the supported devices.  This initial release of POSPrinter Classes does not support USB connected POSPrinters. We hope to introduce this support at some point in the future, but for now you will need to use a network or Bluetooth from the supported devices list.

https://msdn.microsoft.com/en-us/library/windows/apps/mt426652.aspx

The article states the following:

>Device support
Windows supports the ability to print to network and Bluetooth connected receipt printers using the Epson ESC/POS printer control language. For more information on ESC/POS, see Epson ESC/POS with formatting.
.
While the classes, enumerations, and interfaces exposed in the API support receipt printer, slip printer as well as journal printer, the driver interface only supports receipt printer. Attempting to use slip printer or journal printer at this time will return a status of not implemented. 
.
Support is currently limited to the Network and Bluetooth device models listed in the tables below. USB connected printers are currently not supported. Please check back for additional support to be added in the future. 
.
Stationary POS printers (Network, Bluetooth)
Manufacturer    Model(s)
Epson TM-T88V, TM-T70, TM-T20, TM-U220 
.
Mobile POS printers (Bluetooth)
Manufacturer    Model(s)
Epson Mobilink P20 (TM-P20), Mobilink P60 (TM-P60), Mobilink P80 (TM-P80)  

Terry Warwick
Microsoft
