### ISSUE TITLE
Background Task Sample no JS version

### ISSUE THREAD

**Issue by cthedot** [Microsoft/Windows-universal-samples#214]
README claims it should work for JS apps but no Javascript version found :(

This issue is actually for quite a few samples. Is Javascript not a preferred development language anymore? Documentation also lacks quite a bit in that department...

Thanks!

**Comment by oldnewthing** [comment]
Sorry, the bottom half of the READMEs are boilerplate. We still care about JavaScript, though specific feature teams may not have the time to write samples in all three languages, so they tend to pick C# first and hope to get to the rest later.

**Comment by AngelMunoz** [comment]
@oldnewthing Hello There, I know Old Thread, may you be able to point me where is the best place to request/give feedback about javascript samples?

**Comment by oldnewthing** [comment]
if you have feedback about the samples themselves, then this is the right place. if the feedback is about platform support for JavaScript (e.g. "feature X doesn't work in JavaScript") then that goes to the Developer Support forums. Hope that clarifies.
