### ISSUE TITLE
Background audio samples don't bind the taskbar live preview media controls

### ISSUE THREAD

**Issue by mfycan** [Microsoft/Windows-universal-samples#216]
I've tested the background audio C# and VB samples and none of them bind the media controls on the taskbar app live preview. They are disabled. Is there a way to implement it?

I'm on Threshold 2 RTM.

Screenshot: https://gyazo.com/e4efbd4f401c0c242d0b16c2931e41c2

**Comment by mfycan** [comment]
I've tried that but the SMTC from the background audio gets overrided by the foreground app one once i set .isEnabled = true. So I need to have the same implementation on both background and foreground?

**Comment by aarononeal** [comment]
Yes, that's the current way around the platform limitation we're working to improve.

**Comment by mfycan** [comment]
Thank you!

**Comment by aarononeal** [comment]
You're welcome. Sorry for the extra step. We're evaluating some changes to the views that should make this easier in the future.

**Comment by hig-ag** [comment]
I don't know how the workaround works. I can't use the taskbar SystemMediaTransportControls and the volume SystemMediaTransportControls at the same time. How did you solved it?

**Comment by mfycan** [comment]
At the time I asked the question, I didn't try the workaround because I gave up on the implementation anyway. Only now I got back to the same implementation and tried the workaround aarononeal confirmed. It doesn't work properly and may cause unexpected behavior. I guess we'll have to wait for redstone update.
