### ISSUE TITLE
HTML Wrapper refreshes unnecessarily when app opens again

### ISSUE THREAD

**Issue by matthiasg** [Microsoft/Windows-universal-samples#218]
I just wrapped my HTML app with a universal html app. sadly it seems every time i click the app it re-navigates to the Start Page instead of just showing the app again.

1) Start the app fresh
2) Loads the HTML app
3) Navigate around
4) Go to start screen in windows phone
5) Click on app again
6) App opens with last screen and then REDIRECTS to start page again, causing a full reload

**Comment by dpierangeli** [comment]
If you use the multitasking to return to your app there is also the refresh?

**Comment by oldnewthing** [comment]
This is not a question about a particular sample. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
