### ISSUE TITLE
Enterprise data protection sample question

### ISSUE THREAD

**Issue by Yurijj** [Microsoft/Windows-universal-samples#220]
Hello,

Just looking for code sample about Enterprise data protection (Windows-universal-samples/Samples/EnterpriseDataProtection/), scenario 4:
"An app wants to roam its protected file to other devices.In order to do so, it must check if the file’s protection can be roamed.The app calls **GetProtectionInfoAsync** on the file to retrieve this information."

Have a question regarding to the Windows-universal-samples/Samples/EnterpriseDataProtection/cs/Scenario4_FilePMgr.xaml.cs,  row#81  **private async void CreateFileAndProtect()** method.

```
await FileProtectionManager.ProtectAsync(m_file, Scenario1.m_enterpriseId);
procInfo =  await FileProtectionManager.GetProtectionInfoAsync(m_file);
```

As a result I have procInfo as:

```
Identity = "onmicrosoft.com"
IsRoamable = false
Status = Protected
```

So, does it means that I can't roam protected file to other device? Why "IsRoamable **= false**"? How  can I protect my file and roam it to other devices (ProtectAsync method has no any additional parameters)?

Will be very appropriated for any help or answers.

**Comment by oldnewthing** [comment]
This isn't a question about a sample, but rather a question about the underlying API. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
