### ISSUE TITLE
BarcodeScanner bind or update data to mobile/browser

### ISSUE THREAD

**Issue by patagoniahiker** [Microsoft/Windows-universal-samples#221]
Hi the scanner sample is very focused to honeywell, this should be more generic since the application is universal :)

1.  Can you please tell me how to raise, capture and send the event to a) **the browser text box** b) ajax or **webservice call**.
2.  How can this be adapted to generic scanners that worked in previous *generic keyboard wedge* scenarios.

**Comment by oldnewthing** [comment]
I don't see anything Honeywell-specific in the BarcodeScanner sample, but maybe I'm missing it. Care to point it out?

You can adapt the `onDataReceived` method in `scenario1_BasicFunctionality.js`. The sample just puts it in some `TD` elements, but you are welcome to put it in an `INPUT` element or send it via ajax to a back-end server. Just take the `args.report` and send it wherever you like.

**Comment by jason69sinclaire** [comment]
Sorry Raymond Chen I'm in hospital 🏥 one or two of the patients have been saying they were updating it why ill never no iv no idea wot theve been doing but they are niot aloud there own phone 📱

Sent from my Windows Phone
________________________________

**Comment by patagoniahiker** [comment]
Hi, trying this in a couple of browsers it sometimes puts values/goes to the URL bar, and other times it does not target the input box correctly.

1.    I tried to put a `barcode-scanner-class` on the div element and tried to tell it to target that as a textbox or list box. I was unable to modify this sample to target that element.
2.   This is a windows sample, I would like it to target a simple windows (ASP MVC) Controller Action as target for a quick lookup for either `single mode` or `batch mode`, where the user is scanning one code and looking up/submit or a back/inventory mode. Can you please add some guidance on how to do this, not just *adapt* suggestions, but a sample please.
3.   The HID spec is sometime virtual with wireless scanner, how can I detect this if its wife, will I still query the usb devices list? and will this device acquire/exclusive only work in IE or Chrome also? Currently the ActiveX version is very cloogy! And I would like to get a generric scanner working.

thanks

**Comment by oldnewthing** [comment]
I think there is some confusion here.  These samples are for the Windows Universal App platform. They are for standalone apps, not for use in Web pages.

**Comment by patagoniahiker** [comment]
Can you please correct me, from the MS build conference and the samples they demo's they said the same can work inside windows 10 apps, JS/HTML and browser, please tell me, is this not correct?

Do these names spaces not work in windows 10 EDGE, IE,

**Comment by oldnewthing** [comment]
WinJS works in Windows 10 apps as well as in browsers. WinRT works in Windows 10 apps, but not in browsers.

**Comment by patagoniahiker** [comment]
ok, in win 10, I can get access to the user device in opera but not firefox?

**Comment by oldnewthing** [comment]
This sample is for demonstrating how to access the bar code scanner from a Windows Store universal app. If you want to access the bar code scanner from a Web browser, you'll have to ask the people who support that Web browser (in your case, the Opera folks).
