### ISSUE TITLE
How to set playlist for background media in JavaScript?

### ISSUE THREAD

**Issue by lucienimmink** [Microsoft/Windows-universal-samples#224]
I'm trying to rewrite the demo code in JavaScript and setting the source for 1 item in the backgroundmediaplayer works, but the following code
// Assign the list to the player
BackgroundMediaPlayer.Current.Source = playbackList;
is undoable in JavaScript so it seems.
Setting
mediaPlayer.source = mediaPlaybackList
with mediaPlaybackList being a Windows.Media.Playback.MediaPlaybackList always results in a 'No such interface supported' error. the old syntax using setMediaSource gives the same error

**Comment by aarononeal** [comment]
Hi, you need to use URL.createObjectURL(). Please see the VideoPlayback sample Scenario 5 here:

https://github.com/Microsoft/Windows-universal-samples/blob/master/Samples/VideoPlayback/js/js/scenario5.js

**Comment by lucienimmink** [comment]
mediaPlayer.src = URL.createObjectURL(mediaPlaybackList, { oneTimeOnly: true });
with mediaPlayer being a Windows.Media.Playback.BackgroundMediaPlayer.current.

src is not a known property; after setting the src and calling .play() the player does nothing.
mediaPlaybackList.moveNext() results in an error: 'the request is invalid in the current state'
as if the mediaplayer is not running / the playlist is inactive; please advice

**Comment by oldnewthing** [comment]
it looks like you aren't asking a question about the samples. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose the appropriate type – such as Building apps and games, and then choose from the Problem type/Category to get engaged through a formal support channel

**Comment by aarononeal** [comment]
lucienimmink--

I forgot you were trying to get this working in the background whereas the video sample shows how to do it in the foreground using an HTML5 video element (which has a src property).

You do need to use `BackgroundMediaPlayer.Current.Source = playlist` but you can only set this from your background process, not your foreground process.

Have you rewritten the entire background process in JS? It is possible to do that as far as I know, but we do not have a sample for this since it is not commonly done.

**Comment by lucienimmink** [comment]
Think I found out how to handle this: All Background related functions have to be in the item declared as start page for the background audio in the manifest.
Thanks for all the hints Aaron. Without you I had given up already since the documentation is quite vague on this subject and no demos exist.

**Comment by aarononeal** [comment]
I am glad to hear with that you were able to get it working! I appreciate the feedback and we'll revisit whether to extend our doc and sample coverage for this case.
