### ISSUE TITLE
About TitleBar

### ISSUE THREAD

**Issue by HppZ** [Microsoft/Windows-universal-samples#225]
In the TitleBar project, SampleConfiguration.cs, The comments at line 42 " Make the main page's content a child of the title bar, and make the title bar the new page content."   Why should we do this?
Thanks!

**Comment by oldnewthing** [comment]
So that the title bar appears at the top of the content.

**Comment by HppZ** [comment]
Ok, thank you! But I got another issue using cumstom TitleBar ：sometimes  I can not drag my application using mouse or finger, I have to minimize the app, and maximize it, and it works. But I do not know what is wrong.

**Comment by oldnewthing** [comment]
Does the problem also occur in the sample? It sounds like this is an OS problem, not a problem with the app.

**Comment by JohnnyWestlake** [comment]
A definite OS problem is that the mouse pointer icon to drag the window size up and down alongside the top edge of the window never shows up when you draw to the top of the title bar (although clicking a dragging still actually does resize, even if there is no hint). Rather annoying bug.

**Comment by oldnewthing** [comment]
Yes, the resize cursor issue is a known OS bug. Sorry.
