### ISSUE TITLE
Can't open the MapControl sample project

### ISSUE THREAD

**Issue by irealva** [Microsoft/Windows-universal-samples#226]
Hi, I can't seem to open the MapControl sample project in Visual Studio. I get an error that says "project failed to load". Within the solution explorer I see an error that reads "The project requires user input. Reload the project for more information". I'm new to Visual Studio - what could be going on?

All the other samples load correctly for me.And  I'm using Visual Studio 2015.

**Comment by oldnewthing** [comment]
I cannot reproduce the problem with Visual Studio 2015 Community version 14.0.23107.0 (i.e., Update 10). The MapControl sample opens and builds just fine.
