### ISSUE TITLE
Cash Drawer sample not working

### ISSUE THREAD

**Issue by SamJSchoenberg** [Microsoft/Windows-universal-samples#227]
I am unable to get the cash drawer sample to work.  I have a cash drawer hooked up to the register and I am able to get it to open with the manufacturer's testing software, but from the sample, CashDrawer.GetDefaultAsync() is returning null every time.  

Any ideas on getting this to work?  Is there anything I should be checking?

**Comment by TerryWarwick** [comment]
Sam,

Please refer to the Windows.Devices.PointOfService documentation on MSDN regarding the devices supported and connectivity required to use the CashDrawer sample.

https://msdn.microsoft.com/en-us/library/windows/apps/mt426650.aspx

> Device support
Connection directly to the cash drawer can be made over the network or through Bluetooth, depending on the capabilities of the cash drawer unit. Additionally, cash drawers that don’t have network or Bluetooth capabilities can be connected via the DK port on a supported POS printer, or the Star Micronics DK-AirCash accessory. At this time, there is no support for cash drawers connected via USB or serial port. 

This initial release of the Windows.Devices.PointOfService for CashDrawer does not support hardwire of the cashdrawer to the PC.  We currently so support connection of the cashdrawer through the DK port on a network or Bluetooth POSPrinter, but again, this initial release does not support USB connected POSPrinters.

Terry Warwick
Microsoft

**Comment by SamJSchoenberg** [comment]
@TerryWarwick It's connected directly to the register through a DK port, **not** a USB port

**Comment by TerryWarwick** [comment]
Sam,

As the device support section in our MSDN documentation for Windows.Devices.PointOfService.CashDrawer states, we support Bluetooth, network attached, and cash drawers connected to the DK port on supported POSPrinters.  Supported POSPrinters include ESC/POS (primarily Epson at this point in time) that are either Bluetooth or network attached.  We currently do not support cash drawers or posprinters that are directly attached to the PC either via USB, Serial or DK port.

Terry Warwick
Microsoft
