### ISSUE TITLE
Bluetooth Rfcomm Chat C# sample not working

### ISSUE THREAD

**Issue by FlxLee** [Microsoft/Windows-universal-samples#228]
I tried to download the latest RfcommChat sample and deployed it to 2 laptop that are bluetooth-capable and the BT pairing is done each other. The OS version of both laptop is TH2(10586). After that, I executed Bluetooth Rfcomm Chat C# sample in both side. After that I selected  "Foreground Chat Server" and pressed "Start Listening" in a laptop, and "Chat Client", "Run" in another laptop. But, the client app can not find any RfcommDeviceService instance. The chatServiceDeviceCollection.Count is always 0. I tried to find the RfcommService using DeviceWatcher same as prior version of DeviceEnumerationCs but I couldn't. Can you let me know what I missed?

**Comment by kpathakota** [comment]
Unfortunately, for that version of the sample, the pairing must be done AFTER you have started the Foreground chat server and pressed "Start Listening".  

In Win10 anniversary update, you have the ability to query for services dynamically so this works better (just use the dev branch of the sample with the latest insider preview and SDK).
