### ISSUE TITLE
I am getting this error in VS2015.  There is a missing project subtype. Subtype: '{A5A43C5B-DE2A-4C0C-9213-0A381AF9435A}' is unsupported by this installation.

### ISSUE THREAD

**Issue by maxmin88** [Microsoft/Windows-universal-samples#229]
Full error. I tried to open 2 samples with similar errors.

C:\Users\Robert\Documents\Visual Studio 2015\Projects\Samples\UWP-samples-master\Samples\CashDrawer\cs\CashDrawer.csproj : error  : The project file 'C:\Users\Robert\Documents\Visual Studio 2015\Projects\Samples\UWP-samples-master\Samples\CashDrawer\cs\CashDrawer.csproj' cannot be opened.

There is a missing project subtype.
Subtype: '{A5A43C5B-DE2A-4C0C-9213-0A381AF9435A}' is unsupported by this installation.

**Comment by oldnewthing** [comment]
Did you remember to install the latest Windows SDK?

**Comment by maxmin88** [comment]
I did. Some of the sample worked and some didn't

**Comment by LienertD** [comment]
Did you manage to fix this problem, maxmin88? I'm having the same error in VS2013...

**Comment by maxmin88** [comment]
Hi,  I am not seeing the problem now. In the beginning I was only having problems with certain examples, not all of them. I am currently using the Tiles and Notifications example and it is working no problem.  I haven't tried other samples recently.  I upgraded to VS 2015 Update 1. This may have fixed it or I am only using a sample that is OK....

**Comment by nzmike99** [comment]
I am getting this as well. I have installed VS2015 CTP2 and the Windows 10 SDK (1.3 CTP v10.0.10586) but when I try to create a UWP project or open any of the samples I get the exact same error.... has anyone had this or solved it?   Or is my entire VS2015 install foobar'd?

I have tried a repair on the "Windows Software Development Kit - Windows 10.0.10586.15" which was successful but no change - still can't create or load any UWP projects.

The other thing I've noticed is that I go into VS and go into About the following say tehy a reinstalled but I can't see the UWP which is I guess why it won't work - does this mean I need to completely uninstall and reinstall VS 2015?  If so, why did everything appear to install without issue?

Installed Products:
Microsoft Visual Studio Community 2015 CTP
Version 14.0.25008.00 Update 2 CTP
Microsoft .NET Framework
Version 4.6.01038

Installed Version: Community

Visual Basic 2015 CTP   00322-20000-00000-AA327
Microsoft Visual Basic 2015 CTP

Visual C# 2015 CTP   00322-20000-00000-AA327
Microsoft Visual C# 2015 CTP

Visual C++ 2015 CTP   00322-20000-00000-AA327
Microsoft Visual C++ 2015 CTP

Windows Phone SDK 8.0 - ENU   00322-20000-00000-AA327
Windows Phone SDK 8.0 - ENU

Application Insights Tools for Visual Studio Package   1.0
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015.1 (Beta8)   14.1.11106.0
ASP.NET and Web Tools 2015.1 (Beta8)

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.30624.0
For additional information, visit http://www.asp.net/

Common Azure Tools   1.7
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

CommonEditorPackage Extension   1.0
CommonEditorPackage Visual Stuido Extension Detailed Info

GitHub.VisualStudio   1.0
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

JavaScript Project System   2.0
JavaScript Project System

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

NuGet Package Manager   3.4.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Data Tools   14.0.60127.0
Microsoft SQL Server Data Tools

TypeScript   1.8.0.0
TypeScript tools for Visual Studio

Visual Studio Tools for Apache Cordova   Update 5
Visual Studio Tools for Apache Cordova

Xamarin   3.11.837.0 (f10676f)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin.Android   5.1.5.3 (f98871a95a479f6d71b3067b7e5834d41fcb2118)
Visual Studio plugin to enable development for Xamarin.Android.

Xamarin.iOS   8.10.4.0 (6db87c53c073f4af2f5247fb738a27ea08c094fd)
Visual Studio extension to enable development for Xamarin.iOS.

Xamarin.iOS Unified Migration   1.0
Automated migration for Xamarin iOS Classic projects to Unified

Xamarin.TestCloud.Integration   1.0
Early preview of Xamarin Test Cloud integration

**Comment by ScarlettCode** [comment]
Any update on this?

**Comment by oldnewthing** [comment]
The OP says [the problem is fixed](https://github.com/Microsoft/Windows-universal-samples/issues/229#issuecomment-167347012).

**Comment by DavidEGrayson** [comment]
For anyone else coming across this thread: note that "Visual Studio 2015" is a pretty ambiguous term.

* Visual Studio Express 2015 for Desktop will _not_ work; it doesn't support Universal apps.
* Visual Studio Express 2015 for Windows 10 will work.  As of 2016-08-16 at 3pm, you can find this version at https://www.visualstudio.com/en-us/products/visual-studio-express-vs.aspx in the gray-colored "Express Editions" section.
