### ISSUE TITLE
Barcode scanner in SSP mode

### ISSUE THREAD

**Issue by ericdes** [Microsoft/Windows-universal-samples#232]
Hello,

The UWP sample for a barcode scanner only finds USB.HDI devices. 

What device capabilities should I declare for a barcode scanner in SPP mode with Bluetooth? Although this possibility has been listed on this document https://msdn.microsoft.com/en-us/library/windows/apps/mt426649.aspx, I still don't understand how I should declare the device. 

Any information would be Welcome!

**Comment by TerryWarwick** [comment]
Ericdes,

Please refer to the Windows.Devices.PointOfService documentation on MSDN regarding the devices supported by our BarcodeScanner classes.

https://msdn.microsoft.com/en-us/library/windows/apps/mt426649.aspx

> Bluetooth
Serial Port Protocol (SPP) – Simple Serial Interface (SSI)
Windows supports SPP-SSI based Bluetooth barcode scanners.
.
Manufacturer   Model(s)
Socket Mobile CHS 7Ci, CHS 7Di, CHS 7Mi, CHS 7Pi, CHS 8Ci, CHS 8Qi 

Please try first pairing your scanner (only the above Socket Mobile scanners are supported at this point in time) by choosing Start - Settings - Devices - Connected Devices - Add a device.  Note, you need to use Connected Devices to initiate the pairing of Barcode Scanners as opposed to Bluetooth.  Once connected, you will see a Barcode Scanner icon associated with the device.

After the scanner is connected then try running the sample application.

Terry Warwick
Microsoft
