### ISSUE TITLE
 Something wrong in project ContextMenu !

### ISSUE THREAD

**Issue by HppZ** [Microsoft/Windows-universal-samples#233]
Something wrong in project ContextMenu !
![default](https://cloud.githubusercontent.com/assets/12285582/11620990/adf9f4d8-9cf2-11e5-930b-418f06b9830b.png)

by the way : Can PopupMenu support sub items?

**Comment by oldnewthing** [comment]
Okay, this is a bug in the `GetTextboxSelectionRect` helper function. The line

> return new Rect(x, dx, y, dy);

should be

> return new Rect(x, y, dx, dy);

Second question: PopupMenu does not support subitems. If you want a fancy menu, use the XAML Flyout control.

**Comment by oldnewthing** [comment]
Fix went public in https://github.com/Microsoft/Windows-universal-samples/releases/tag/v2.0.5
