### ISSUE TITLE
Custom grainy line drawing sample in complex ink

### ISSUE THREAD

**Issue by kellylawson** [Microsoft/Windows-universal-samples#234]
Hi,

Thanks for all the great samples!  I'm trying to create a pen that will allow me to draw a line with texture, something like a pencil on rough paper.  I'd also like to be able to colorize that line, and vary the saturation of the color based on pressure.

At present I am trying to use a BitmapBrush with a partially transparent grayscale png of a texture, and repeating the bitmap of the texture as the pen moves.  I'm not sure how to colorize the bitmap, or even if this approach makes sense.

It would be very helpful to have another pen in the Complex Ink sample that displayed more extensive customization of the line drawn for the strokes.  There are no good tutorials other than this sample that I can find on the subject.

**Comment by FranciszMicrosoft** [comment]
Hi Kelly, we are well aware of this scenario and is working on exposing more custom line drawing functionality in the platform.  Today there's basically no way for an app to customize wetink (the ink that's rendered before you lift the pen off screen) rendering, and you get either the solid "ballpoint pen" look or the semi-transparent "highlighter" look.  Our plan is to allow apps to customize this in the future, like specifying a shader function.

If you can live with wetink and dryink (rendered after you lift the pen) look different, you can have InkPresenter draw the wetink in a color/pen that approximates the pen you want, then render the dryink yourself through CustomDry (covered in ComplexInk sample).  This gives you the option of using BitmapBrush to render the dry ink, and you can even dry the ink strokes to SwapChainPanel and draw using DX.  One caveat with this approach is you won't be able to use the same smoothing algorithm wetink is using, so the dried stroke may look blocky.  This is another area where we plan to expose more customization functionality, so apps that decides to draw wetink their own way can still benefit from ink stroke modeling provided by DirectInk.

Thank you for the comments and suggestion, and feel free to email us at DirectInk@microsoft.com.  I'm much more prompt at responding to that alias :)
