### ISSUE TITLE
desktop-style MenuFlyout

### ISSUE THREAD

**Issue by HppZ** [Microsoft/Windows-universal-samples#235]
This sample creates a desktop-style context menu, but when I right-click on Windows10 Desktop or TaskBar, there is no animation which is ugly. So how to remove that from MenuFlyout?

**Comment by oldnewthing** [comment]
Can you be more specific which sample you are referring to?

**Comment by HppZ** [comment]
I mean the project : Context Menu(Xaml), I want the menu to show up like right-click on the Windows desktop without the animation like scrolling.

**Comment by oldnewthing** [comment]
This doesn't appear to be a bug in the sample. The animations for MenuFlyout can be customized the same way as any other XAML animation. [This Web page](http://igrali.com/2015/02/02/menuflyout-flip-animation-windows-phone-winrt/) has an example.

If you need further assistance customizing the animation, you can open a support case with our Developer Support team. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose the appropriate type – such as Building apps and games, and then choose from the Problem type/Category to get engaged through a formal support channel
