### ISSUE TITLE
"Out-of-process component authoring sample" does not working on Windows Phone (10)

### ISSUE THREAD

**Issue by Alexey-Bogomolov** [Microsoft/Windows-universal-samples#237]
Hello. 
The OOPServer sample (https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/WRLOutOfProcessWinRTComponent) cannot create out-of-proc server  when runned on Windows Phone (10).
I got next log during rt-component creation:

'Microsoft.SDKSamples.Kitchen.exe' (Win32): Loaded 'U:\SharedData\PhoneTools\AppxLayouts\Microsoft.SDKSamples.WrlOutOfProcessComponent.CSVS.Release_ARM.alexey.bogomolov\Microsoft.SDKSamples.Kitchen.exe'. Skipped loading symbols. Module is native, and native debugging is currently disabled.
'Microsoft.SDKSamples.Kitchen.exe' (Win32): Loaded 'C:\Windows\System32\ntdll.dll'. Skipped loading symbols. Module is native, and native debugging is currently disabled.
'Microsoft.SDKSamples.Kitchen.exe' (Win32): Loaded 'C:\Windows\System32\KernelBase.dll'. Skipped loading symbols. Module is native, and native debugging is currently disabled.
'Microsoft.SDKSamples.Kitchen.exe' (Win32): Loaded 'C:\Windows\System32\combase.dll'. Skipped loading symbols. Module is native, and native debugging is currently disabled.
'Microsoft.SDKSamples.Kitchen.exe' (Win32): Loaded 'C:\Windows\System32\msvcrt.dll'. Skipped loading symbols. Module is native, and native debugging is currently disabled.
'Microsoft.SDKSamples.Kitchen.exe' (Win32): Loaded 'C:\Windows\System32\rpcrt4.dll'. Skipped loading symbols. Module is native, and native debugging is currently disabled.
'Microsoft.SDKSamples.Kitchen.exe' (Win32): Loaded 'C:\Windows\System32\kernel32legacy.dll'. Skipped loading symbols. Module is native, and native debugging is currently disabled.
'Microsoft.SDKSamples.Kitchen.exe' (Win32): Loaded 'C:\Windows\System32\bcryptprimitives.dll'. Skipped loading symbols. Module is native, and native debugging is currently disabled.
The thread 0x1794 has exited with code -1073741515 (0xc0000135).
The program '[0xC5C] Microsoft.SDKSamples.Kitchen.exe' has exited with code -1073741515 (0xc0000135) 'A dependent dll was not found'.
Exception thrown: 'System.Runtime.InteropServices.COMException' in System.Private.Interop.dll
An exception of type 'System.Runtime.InteropServices.COMException' occurred in System.Private.Interop.dll but was not handled in user code
Additional information: Server execution failed (Excep_FromHResult 0x80080005)

What wrong with dependencies in this sample?

**Comment by Maksim-Khobat** [comment]
BTW, the sample works fine on desktop, is it a WinPhone limitation or a bug?

**Comment by smeenai** [comment]
Removing the `AdditionalDependencies` from `WRLOutOfProcessWinRTComponent_server.vcxproj` seems to do the trick.

**Comment by Maksim-Khobat** [comment]
Right, the latest sample works fine.

**Comment by oldnewthing** [comment]
This was fixed in [v1.0.14](https://github.com/Microsoft/Windows-universal-samples/releases/tag/v1.0.14) for Windows 10 RTM and [v2.0.3](https://github.com/Microsoft/Windows-universal-samples/releases/tag/v2.0.3) for Windows 10 version 1511.
