### ISSUE TITLE
ArgumentException when encrypting data using an ECC CryptographicKey 

### ISSUE THREAD

**Issue by RafaelYousuf** [Microsoft/Windows-universal-samples#238]
I'm trying to implement an encryption algorithm using the new ECC curves that were added in the UWP framework, but I didn't find any code example on the internet and I'm having an hard time trying to come up with something that actually works.

Here's what I have so far:

'private static byte[] ConvertHexToBytesArray(String hexString)
{
    IBuffer hexBuffer = CryptographicBuffer.DecodeFromHexString(hexString);
    return ConvertBufferToBytes(hexBuffer);
}

protected static IBuffer ConvertBytesToBuffer(byte[] value)
{
    return CryptographicBuffer.CreateFromByteArray(value);
}

protected static byte[] ConvertBufferToBytes(IBuffer buffer)
{
    byte[] result;
    CryptographicBuffer.CopyToByteArray(buffer, out result);
    return result;
}

protected static byte[] ConvertStringToBytes(String value)
{
    byte[] result;
    CryptographicBuffer.CopyToByteArray(CryptographicBuffer.ConvertStringToBinary(value, BinaryStringEncoding.Utf8), out result);
    return result;
}

protected static String ConvertBytesToString(byte[] value)
{
    return Encoding.UTF8.GetString(value, 0, value.Length);
}

public static void Test()
{
    // Get the key
    AsymmetricKeyAlgorithmProvider a = AsymmetricKeyAlgorithmProvider.OpenAlgorithm(AsymmetricAlgorithmNames.EcdsaSha512);
    CryptographicKey key = a.CreateKeyPairWithCurveName(EccCurveNames.NistP521);

    // Get the IV array
    const String IV = "FF7234783740D47159A23C432341324F";
    byte[] IVArray = ConvertHexToBytesArray(IV);
    IBuffer IVBuffer = ConvertBytesToBuffer(IVArray);

    // Get the data to encrypt
    String test = "Some random text to encrypt";
    byte[] testBytes = ConvertStringToBytes(test);
    IBuffer testBuffer = ConvertBytesToBuffer(testBytes);

    /* Encrypt the data
    * ====================
    * This line actually throws an ArgumentException */        
    IBuffer encrypted = CryptographicEngine.Encrypt(key, testBuffer, IVBuffer);

    // Decrypt it back
    IBuffer decrypted = CryptographicEngine.Decrypt(key, encrypted, IVBuffer);

    // Get the decrypted String
    byte[] result = ConvertBufferToBytes(decrypted);
    String plainText = ConvertBytesToString(result);
    Debug.WriteLine($"Decrypted: {plainText}");
}'

It looks like there are no guides or samples on how to use this.

PS: the exception message is: Value does not fall within the expected range

Thank you.

**Comment by andrew7webb** [comment]
Perhaps KeyAlgorithmNames.Ecdh256  would work better, as AsymmetricAlgorithmNames.EcdsaSha512 is  a signing algorithm, not encryption.

**Comment by oldnewthing** [comment]
This issue doesn't appear to be regarding an existing sample. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account

2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
