### ISSUE TITLE
Communication blocking and filtering sample- Cannot read message on MessageReceivedTask

### ISSUE THREAD

**Issue by ibilbao** [Microsoft/Windows-universal-samples#240]
I'm testing the application and when I get an sms and the MessageReceivedTask Background Task is triggered I cannot get any information about the message
  ChatMessageReader msgReader = msgStore.GetMessageReader(TimeSpan.FromSeconds(1));
            var msgList = await msgReader.ReadBatchAsync();

```
        foreach (ChatMessage msg in msgList)
```

there is not ChatMessage in msgList.
There also no details on triggerdetails

**Comment by oldnewthing** [comment]
To read the contents of messages as they arrive, you use the ChatMessageReceivedNotificationTrigger. Communication blocking is for managing the list of blocked numbers, not for reading messages.
