### ISSUE TITLE
Memory leak in master/detail sample

### ISSUE THREAD

**Issue by Andrea485** [Microsoft/Windows-universal-samples#241]
I used this sample with the sample of hamburger menu, when you switch between the view master / detail and another view there is a memory leak caused by ContentPresenter, changing with ContentControl I solved the problem.

**Comment by ChrisGuzak** [comment]
can you be more specific about what you change? consider providing a pull request.

**Comment by Andrea485** [comment]
I created a simple application with navigation menu hamburger, I have two views:
the first view is a simple calendar with week view, and the second view is the master / detail.
Now if I view the master / detail I go in the other view, it generates a memory leak, from 40 MB up to 250 MB asale.
I tried to change in MasterView the control ContentPresenter with ContentControl and the memory leak no longer occurs.

**Comment by oldnewthing** [comment]
Please include your solution so we can apply it to the sample.

**Comment by oldnewthing** [comment]
I've asked the feature team to investigate.

**Comment by oldnewthing** [comment]
Feature team has deprecated the XamlNavigation navigation; navigation is now demonstrated in the XamlUIBasics sample, with the new NavigationView control.
