### ISSUE TITLE
Device Enumeration Sample: Enumerate Snapshot or Enumerate & Watch, Bluetooth LE (paired) or Bluetooth (paired) -> Exception

### ISSUE THREAD

**Issue by bc3tech** [Microsoft/Windows-universal-samples#246]
"The Parameter is Incorrect" exception as soon as you click `Find`

Running on Mobile 10586.36

Seems like it could be similar/related to #170

**Comment by bc3tech** [comment]
[Per AQS doco](https://msdn.microsoft.com/en-us/library/windows/apps/mt187356.aspx?f=255&MSPPError=-2147217396), there isn't a ProtocolId Filter for Bluetooth:
![Screenshot of doco table](http://content.screencast.com/users/bc3tech/folders/Snagit/media/e17a7103-c708-486a-abbb-485615814d0d/12.18.2015-11.16.png)

Yet the sample injects one:
`"System.Devices.DevObjectType:=5 AND System.Devices.Aep.ProtocolId:=\"{E0CBF06C-CD8B-4647-BB8A-263B43F0F974}\" AND (System.Devices.Aep.IsPaired:=System.StructuredQueryType.Boolean#True OR System.Devices.Aep.Bluetooth.IssueInquiry:=System.StructuredQueryType.Boolean#False)"`

I believe this is the error.

**Comment by vidager** [comment]
Yes, Bluetooth query should be enabled in the 10586 release or later.  I will follow up on getting the MSDN doc page updated. You should be able to manually build your own Device Selectors (AQS strings) using the Bluetooth[LE] protocol ids. 

As for the exception, I will look into it.  Can you provide the following details:  1) Which phone you're using, and 2) In the sample project properties under the Application tab, double check the Target and Min versions.  It's very possible you're hitting an issue that was just recently fixed on build 14295+ (https://blogs.windows.com/windowsexperience/2016/03/25/announcing-windows-10-insider-preview-build-14295-for-pc-and-mobile/). 

Thanks,
Ben

**Comment by bc3tech** [comment]
this is a super old issue. I can tell you at the time I was running whatever the current Fast Ring Mobile Insider build was, and the devices were both a Lumia Icon and Lumia 640.

**Comment by vidager** [comment]
I apologize for the delayed response.  Let me know if you see the issue again. I did get the MSDN page updated, so the Bluetooth and Bluetooth LE protocol GUIDs are now available for building custom selectors.  Thanks!
