### ISSUE TITLE
 How to use google maps on windows universal apps?

### ISSUE THREAD

**Issue by PuthNeng** [Microsoft/Windows-universal-samples#251]
Hi Sir,
I am new developer windows universal apps. I want to know about google maps on uwp. I want to developer app to have relationship with maps and I see the bing maps but on bing maps don't have address some where such as Cambodia country I see name province only. So I want to you help me.
You can show or guy me. How to use google maps on windows universal apps? And I hope so you help me.
Thank advance.
NengStyle007

**Comment by jerrak0s** [comment]
You can use google maps with HTML/JS  UWP API. Google for more. 
http://www.codeproject.com/Tips/857981/Google-Maps-API-on-Windows-Store-App

**Comment by oldnewthing** [comment]
This does not appear to be a question about a sample that doesn't work. You can open a support case with our Developer Support team who can try to help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.

**Comment by PuthNeng** [comment]
Hi sir. @jerrak0s 
If you can build the small sample for google map UWP. And What I thing is that about memory for device such as : Mobile (Nokia Lumia 630,Nokia Lumia 920 AT&T it is very small memory for run maps. So I don't know how to use google map with UWP? If you can help me. 
Thank you advance.

**Comment by PuthNeng** [comment]
Hi sir. @oldnewthing 
You guide me sign-in with Microsoft account but when I'm sign-in I see two combobox in app development for choose the problem type and categories. But I don't see the resolution. 

But however. I thank you so much and I hope you tell me about resolution it.

**Comment by oldnewthing** [comment]
After you select the Problem Type and Category, click the button that says "Start request".

**Comment by NGame1** [comment]
If you want to use Google maps in UWP C# app you can use this project 
https://github.com/NGame1/UWPGmaps.SDK
Or this NuGet package : 
https://www.nuget.org/packages/GMapsUWPSDK
If you want to use NuGet package please use latest versions and also send me your feedback and submit issues to help me make it even better .
Regards

**Comment by rbrundritt** [comment]
@NGame1 both of those projects violate the terms of use of the MapControl and also Google Maps terms of use.

**Comment by NGame1** [comment]
@rbrundritt If you have better way please let me know

**Comment by rbrundritt** [comment]
The better approach is to have Google Map their own UWP control.
