### ISSUE TITLE
NormalizedAnchorPoint don't work in MapControl

### ISSUE THREAD

**Issue by boodoolak** [Microsoft/Windows-universal-samples#252]
if use maps:MapItemsControl.ItemTemplate, NormalizedAnchorPoint don't work.
If use without MapItemsControl - work correctly.

**Comment by myshiftzz** [comment]
I had no problems with NormalizedAnchorPoint in MapItemsControl.ItemTemplate

 

                    <maps:MapItemsControl x:Name="mapItems" ItemsSource="{Binding penNumberText}">

                           <maps:MapItemsControl.ItemTemplate>

                                 <DataTemplate>

                                        <Border Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">

                                               <TextBlock x:Name="mapTextBlock" Text="{Binding PenNumber}" 

                                                        FontSize="12" 

                                                        maps:MapControl.Location="{Binding Location}"

                                                        maps:MapControl.NormalizedAnchorPoint="{Binding NormalizedAnchorPoint}">

                                               </TextBlock>

                                        </Border>

                                 </DataTemplate>

                           </maps:MapItemsControl.ItemTemplate>

                    </maps:MapItemsControl>

**Comment by boodoolak** [comment]
Example from official MapControl sample.
In scenario 3 I added NormalizedAnchorPoint binding.

public class PointOfInterest
    {
        public PointOfInterest()
        {
            this.MoreInfo = "At a glance info info about this Point of interest";
            this.NormalizedAnchorPoint = new Point(0.5, 1);
        }
        public string DisplayName { get; set; }
        public Geopoint Location { get; set; }
        public Uri ImageSourceUri { get; set; }
        public string MoreInfo { get; set; }
        public Point NormalizedAnchorPoint { get; set; }
    }

<DataTemplate>
                                    <Button  x:Name="mapItemButton" Click="mapItemButton_Click" Background="Transparent">
                                        <StackPanel>
                                            <Border Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
                                                <TextBlock Text="{Binding DisplayName}"/>
                                            </Border>
                                            <Image Source="{Binding ImageSourceUri}"
                                               maps:MapControl.Location="{Binding Location}" 
                                               maps:MapControl.NormalizedAnchorPoint="{Binding Point}" >
                                                <Image.Transitions>
                                                    <TransitionCollection>
                                                        <EntranceThemeTransition/>
                                                    </TransitionCollection>
          
                                      </Image.Transitions>
                                            </Image>
                                        </StackPanel>
                                    </Button>
                                </DataTemplate>

Screenshots before zooming
![mapcontrol c sample 2015-12-24 18 21 58](https://cloud.githubusercontent.com/assets/3179176/11996015/de3cbf46-aa6b-11e5-8b6d-b01440b79ce9.png)

 and after:
![mapcontrol c sample 2015-12-24 18 22 11 png - photos 2015-12-24 18 27 23](https://cloud.githubusercontent.com/assets/3179176/11996023/15213280-aa6c-11e5-9117-c8a20f447f66.png)

the image should not move when zooming

**Comment by myshiftzz** [comment]
I experienced the same thing. I do not like that behavior as well. But, I do not think NormalizedAnchorPoint controls that behavior. I could be wrong though.   MapIcons seem to behave differently based on whether the map is 2D or 3D. Is it an Altitude issue?

David Blackburn

**Comment by boodoolak** [comment]
NormalizedAnchorPoint is work correctly for me if don't use MapItemsControl. I don't use 3d.

This example is work correctly on 2d map:
    
    <Maps:MapControl 
        Center="{Binding MapCenter, Mode=TwoWay}"
        <Grid 
            Maps:MapControl.Location="{Binding MapCenter}"
            Maps:MapControl.NormalizedAnchorPoint="0.5,1">
            <Image Source="/Assets/Images/GeoPointerA.png"></Image>
        </Grid>
     </Maps:MapControl>

Why NormalizedAnchorPoint  don't work with MapItemsControl? Is it bug?

**Comment by JimGalasyn** [comment]
Also, the points of interest drift around in 3D view, so it's seems like a bug in MapItemsControl.

**Comment by myshiftzz** [comment]
I agree. Bug.

**Comment by JeanCollas** [comment]
It seems to work when binding but not when written static in xaml.
However it is a design element, not content, so it should not require binding...

**Comment by oldnewthing** [comment]
This issue is not with the sample itself, but rather with extending the sample. It will require additional debugging to further isolate the problem you are experiencing. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account.
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.

**Comment by amittyagi-sus** [comment]
Hi guys,

It's not MapControl issue. by default It render icon to right bottom of point .you need to set offset.
for ex. If MapIcon Image Height =40 and Width= 40 then set margin -20,0,0,-40. try it you will see changes.
