### ISSUE TITLE
Background audio AccessViolation when playing certain MP3 files inside a MediaPlaybackList

### ISSUE THREAD

**Issue by jorticus** [Microsoft/Windows-universal-samples#255]
BackgroundMediaPlayer crashes with an AccessViolation (in mfcore.dll) when playing certain MP3 files, but only when inside a `MediaPlaybackList`. It does not happen if I set `BackgroundMediaPlayer.Current.Source` directly (no `MediaPlaybackList`), and only happens with some files. These files play fine in every other media player, including Groove.

Stacktrace:

    msvcrt.dll!00007ffbf44e3d60()
    mfcore.dll!00007ffbc5d374a3()
    mfcore.dll!00007ffbc5d371e6()
    mfcore.dll!00007ffbc5d36548()
    mfcore.dll!00007ffbc5bed8a2()
    mfcore.dll!00007ffbc5bed67a()
    mfcore.dll!00007ffbc5bedd5a()
    mfcore.dll!00007ffbc5becadd()
    RTWorkQ.dll!00007ffbe3f02521()
    ntdll.dll!00007ffbf6697ed5()
    ntdll.dll!00007ffbf666667d()
    kernel32.dll!00007ffbf64064a2()
    ntdll.dll!00007ffbf669eca4()

I'm running the latest RS insider build

**Comment by aarononeal** [comment]
Can you provide a link to a file that reproduces this so we can test? Alternatively, I can provide instructions next week for how to collect logs that may help us diagnose further.

**Comment by aarononeal** [comment]
To start with, while you are debugging a process in Visual Studio, you can save a dump file when the debugger has stopped at an exception or at a breakpoint. Choose Debug, Save Dump As and select Minidump with Heap (the default).

**Comment by jorticus** [comment]
Thanks for the instructions, I've uploaded a crash dump here: [Windows.Media.BackgroundPlayback.dmp](https://onedrive.live.com/redir?resid=E2F0BDD705CB27B3!11140&authkey=!AJgSr9F_wZDILkE&ithint=file%2cdmp) (100MB)

And here's a sample MP3 that crashes: [crash.mp3](https://onedrive.live.com/redir?resid=E2F0BDD705CB27B3!11139&authkey=!AOIEiKHXIHdM8qk&ithint=file%2cmp3) (I've truncated the file to 127KB, but the behaviour is identical)

**Comment by JohnnyWestlake** [comment]
Worth noting I get AccessViolations using MediaPlaybackItem's created from URI in the background task using *any* media file not included in the application package (i.e, the file path was obtained via a search query on the user's Music Library)

**Comment by aarononeal** [comment]
Thanks for the data on this. There appear to be a couple issues at play and the team is investigating.

**Comment by aarononeal** [comment]
We believe we have addressed this in a future platform update. Thanks for the reports.
