### ISSUE TITLE
Playlists sample can not be delpoyed to phone emulator

### ISSUE THREAD

**Issue by axilesoft** [Microsoft/Windows-universal-samples#256]
Can I use playlist in a UWP project ? 
I noticed that it set  TargetDeviceFamily Name="Windows.Desktop" , do I have to set this to only run on desktop when I use the desktop extension?
Can I check this api contract at runtime?

**Comment by aarononeal** [comment]
Sorry, for Win10 this is a desktop only API. There is an example here for how to check API contracts at runtime:

https://blogs.windows.com/buildingapps/2015/09/15/dynamically-detecting-features-with-api-contracts-10-by-10/

However, if you have your own playlist serialization mechanism you can still use `MediaPlaybackList` at runtime to play it.
