### ISSUE TITLE
Does Windows-universal-samples require the original UWP SDK (10.0.10240)

### ISSUE THREAD

**Issue by GeorgeJoy** [Microsoft/Windows-universal-samples#259]
I have Visual Studio 2015 Update 1, which comes with Universal Windows App Development Tools and includes "Tools (1.2) and Windows 10 SDK (10.0.10586). But when I try to open a UWP sample cloned from GitHub.com/Microsoft/Windows-universal-samples, I get an error saying I need to install the windows 10 SDK (10.0.10240). Why do the samples not work with the newer SDK? I'd prefer to not install the older SDK side-by-side to avoid confusion.

**Comment by wpbest** [comment]
You should be able to select the 10.0.10240 in your project settings.

**Comment by GeorgeJoy** [comment]
Thank you for the suggestion. I changed the following line in the .csproj of the sample:
<TargetPlatformVersion>10.0.10240.0</TargetPlatformVersion>
to
<TargetPlatformVersion>10.0.10586.0</TargetPlatformVersion>

This seems to work. Not sure if there's an easier way.

**Comment by oldnewthing** [comment]
I bumped all the versions to 10586 so there's no dependency on 10240 any more.
