### ISSUE TITLE
AppUIBasics -- A TargetPropertyPath for a Style Setter cannot specify an explicit Target object. 

### ISSUE THREAD

**Issue by juanfranblanco** [Microsoft/Windows-universal-samples#26]
The styles @ app.xaml crashed the application with this error
A TargetPropertyPath for a Style Setter cannot specify an explicit Target object. 
Example at [Line: 85 Position: 57]

Solution comment out these type of setters:
 <Setter Target="RootGrid.Background" Value="{ThemeResource SystemControlHighlightBaseMediumLowBrush}" />

Building on x86 - local

**Comment by mikehenderlight** [comment]
This was fixed a while back, please make sure you are running version 10127 of the OS and that you have pulled down the latest code for the sample.
