### ISSUE TITLE
The Data virtualization sample is too slow

### ISSUE THREAD

**Issue by HppZ** [Microsoft/Windows-universal-samples#260]
But Photos in Windows 10 is really fast (load pictures), how to be that fast?

**Comment by HppZ** [comment]
Does IItemsRangeInfo support CollectionViewSource? I want to use this interface with grouped data, but it does not report the change, please help!

**Comment by samsp** [comment]
The photo's app is much smarter about how it reads the data from the filesystem, and I think may have its own thumbnail cache and DB so it can pivot based on different queries. The data virtualization aspect of the sample is definitely not intended to be a best case demonstration of how to write a photo viewer.
