### ISSUE TITLE
Print example - dummy image added when not overflowing

### ISSUE THREAD

**Issue by Depechie** [Microsoft/Windows-universal-samples#261]
When using the Print example, the 4th scenario, we get an extra image on the printed result if the page is small enough not to overflow.
That image is not there when multiple pages are printed.
Test1 pdf is correct ( with overflowing )
Test2 pdf has the image

Is this correct behaviour for that example?

Also the print preview is not correct, we don't see the footer when there is no overflowing, and the extra image is aligned on top instead of the bottom as seen in the result.
Cfr screenshot attachment for that.

![screenshot 13](https://cloud.githubusercontent.com/assets/351693/12216424/01e8213e-b6e1-11e5-9104-03d7188f5bdd.png)

[PrintSample_Scenario04_test1.pdf](https://github.com/Microsoft/Windows-universal-samples/files/83664/PrintSample_Scenario04_test1.pdf)
[PrintSample_Scenario04_test2.pdf](https://github.com/Microsoft/Windows-universal-samples/files/83665/PrintSample_Scenario04_test2.pdf)

**Comment by Depechie** [comment]
Also putting a ItemsControl in a <InlineUIContainer> inside a Paragraph will result in the page no longer overflowing

**Comment by oldnewthing** [comment]
I've asked the feature team to investigate.

**Comment by oldnewthing** [comment]
A fix is coming in the next update. Thanks for reporting the problem.
