### ISSUE TITLE
ApplicationData MainPage RelativePanel for the Status notification has an XAML error

### ISSUE THREAD

**Issue by mkerryfuller** [Microsoft/Windows-universal-samples#262]
Cannot add content to an object of type Splitview.

The relative panel where the Status Notification on the Main Page is, shows an error.

**Comment by cloudsling** [comment]
I have the same question (in fact I can success deploy) ,but if you add <SplitView.Content></SplitView.Content> surrounded it will be ok.

**Comment by oldnewthing** [comment]
I am unable to reproduce this error. I get warnings about "The parent file … cannot be found in the project file", which is due to the trick we use to save space (file linkage). And two "A project cannot have more than one link to the same file." But nothing about the SplitView.
