### ISSUE TITLE
AllJoyn/ProducerExperiences fails to launch if compiled for x84 on a x64 machine.

### ISSUE THREAD

**Issue by GiitHuub** [Microsoft/Windows-universal-samples#263]
Clicking  "Launch" on either scenario will give a status of "Disconnected from the AllJoyn bus attachment with AllJoyn status: 0x1004".  0x1004 is ER_AUTH_FAIL.  If the AllJoynAuthenticationMechanism is changed to None the scenarios will launch.   Workaround is to compile x64 on a x64 machine.

**Comment by rajat-rastogi** [comment]
Sorry you are hitting this issue. This appears to be a bug in the AllJoyn platform and is being tracked here - [ASACORE-2741](https://jira.allseenalliance.org/browse/ASACORE-2741). As a workaround, please uninstall the sample app and re-deploy the sample in the desired configuration.
