### ISSUE TITLE
Get frame from camera when it is available with event

### ISSUE THREAD

**Issue by krishnan-unni** [Microsoft/Windows-universal-samples#264]
Hi is there a way where we can hook into an event so that we can handle when a new frame is available from camera and process it? I know there is a mediacaptute.getpreviewframeasync function but its kind of a polling for a frame every time rather than get notified also it is not efficient.

**Comment by oldnewthing** [comment]
This is not a question about a specific sample, but rather a question about what features are available in the Windows runtime. You can open a support case with our Developer Support team. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
