### ISSUE TITLE
App crash after printing on PrintManager - Object invoked has disconnected from its clients

### ISSUE THREAD

**Issue by ThanawutZiios** [Microsoft/Windows-universal-samples#265]
Hi,
My app is the POS app that use Windows 10 Hosted Web App.
The system need to print a receipt so I use Windows.Graphics.Printing.PrintManager to print it
and since it need to print a content which come from difference url so I use $get to return HTML that need to print and put into document like this

![image](https://cloud.githubusercontent.com/assets/16663332/12258909/bf40279e-b944-11e5-878d-266746b80176.png)

After run it, the print preview is shown correctly and able to be printed, but after the printout complete the application crash.
This is what it throw out from system
![image](https://cloud.githubusercontent.com/assets/16663332/12259005/3d50d4b2-b945-11e5-9f3c-df57e4b9c3f4.png)

This is the code from preview.js that creates the error
![image](https://cloud.githubusercontent.com/assets/16663332/12259037/760c51be-b945-11e5-8af8-96415e78957a.png)

Is it a correct way to set another page content to print? or what else should I need to setup?

Thank you,
Thanawut Naetisoonthon

**Comment by oldnewthing** [comment]
The issue you are running into appears to be outside the scope of a broken sample and requires additional debugging to further isolate the problem you are experiencing. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.

**Comment by blowsie** [comment]
I get this error when calling `window.print()` inside a window that has been opened via `window.open`
