### ISSUE TITLE
COMException in CameraResolution sample on PreviewSettings page

### ISSUE THREAD

**Issue by mkstephenson** [Microsoft/Windows-universal-samples#266]
When attempting to change the resolution of the preview stream on the Change camera preview settings page in the CameraResolution sample, a COMException is thrown with the following message "The data specified for the media type is invalid, inconsistent, or not supported by this object.".
This occurs on line 82 in Scenario1_PreviewSettings.xaml.cs (observed in commit cef5343).
Tested on the 10.0.10240.0 emulator, the 10.0.10586.0 emulator as well as a 10.0.10586.63 Lumia 930.

**Comment by oldnewthing** [comment]
Thanks for reporting the problem. This is a typo in the C# sample. On [line 92](https://github.com/Microsoft/Windows-universal-samples/blob/v2.0.2/Samples/CameraResolution/cs/Scenario1_PreviewSettings.xaml.cs#L92) change `MediaStreamType.VideoRecord` to `MediaStreamType.VideoPreview`. i'll get the fix pushed into the repo soon, but that's the fix you're going to see.
