### ISSUE TITLE
Windows Audio not working in Mobile

### ISSUE THREAD

**Issue by sushil-arora** [Microsoft/Windows-universal-samples#267]
Hi

I am trying to run the Windows Audio from timer trigger class.
Sound is played in Windows x64 architecture but in arm no sound gets played.
Also, when I debug on windowsphone, sound is played. Can anybody help me.

**Comment by aarononeal** [comment]
Background audio is not supported from a timer task. Please see the background audio sample for how it is supported.

https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/BackgroundAudio

**Comment by sushil-arora** [comment]
Hi aaroneal, there are 2 samples of uwp, background audio and windows audio.
Are both of them not supported from background task.
Can you specify any sample uwp where audio can be played from a timer task.

**Comment by aarononeal** [comment]
Neither is supported from a timer task. The background audio sample shows the supported approach for playing background audio. If you can share more about why you need to use either WindowsAudio/WASAPI or a timer task I maybe able to advise better.

**Comment by sushil-arora** [comment]
I need to play audio from a background task for my voip application when the app is suspended or is in foreground. When the app is suspended, the sockettrigger would get activated on receiving an incoming call. From there, audio needs to be played till call gets disconnected. Thats where I was trying to use either WASAPI or background audio sample app to play the audio from the background task only.
Can you advise on how my approach should be?

**Comment by aarononeal** [comment]
The only task that can play audio is the background audio task so you need to read the socket from that task, but I don't know how to do the hand off. I'll ask around to see if anyone has an idea.

**Comment by aarononeal** [comment]
Unfortunately I've been unable to find any way to hand off the socket. Normally you could use one of these techniques:
https://msdn.microsoft.com/en-us/library/windows/apps/mt617016.aspx

But, that requires hosting another task in the same process as the background audio task and currently there is no way to do that.

That means you have to start your socket connection from the background audio task, you cannot hand it off from the foreground app that is in another process.

We are looking at ways to improve this in future releases.
