### ISSUE TITLE
[BackgroundAudioTask Sample] Why remove handlers when App suspends?

### ISSUE THREAD

**Issue by StefanFabian** [Microsoft/Windows-universal-samples#269]
Hey,

Is there any particular reason why the handlers get removed when the App suspends?
What would happen if you don't remove them?

Kind Regards,
Stefan

**Comment by Amrykid** [comment]
I would have thought that it was because it could cause memory leaks and cause your application to get terminated quicker due to memory constraints.

**Comment by oldnewthing** [comment]
If the app is suspended, it cannot respond to the events immediately. The events will buffer up, and then when the app resumes, all the events will get spit out at once. This will overwhelm the app with stale information. This can cause the app to try to react to things that happened a long time ago, display error messages for things that aren't applicable any more, etc. Better is simply to turn off the faucet.

**Comment by StefanFabian** [comment]
Thank's for the information!

**Comment by aarononeal** [comment]
If I remember correctly there is one more thing that is particular to background audio, which is that a background task can sometimes be canceled while an app is suspended. If that happens then when the app resumes the foreground may get a different proxy the next time it calls BackgroundMediaPlayer.Current and so events might fire for a stale instance. There is a picture of the architecture in this document that may be helpful.

https://msdn.microsoft.com/en-us/library/windows/apps/mt282140.aspx

There were are also cases in the past where the process lifetime manager would terminate a suspended foreground application if a background task sent messages to it and that is one of the reasons the sample goes out of its way to track the state of the foreground application through isolated storage.
