### ISSUE TITLE
cortanavcds crashes in any other locale then en-US

### ISSUE THREAD

**Issue by tomaszpolanski** [Microsoft/Windows-universal-samples#27]
TripStore.cs parses date using US format, but still uses default locale.

Parse the date using US locale:  DateTime.Parse("05/05/2015", new CultureInfo("en-US"))

**Comment by anpilley** [comment]
Hey, With the update to the master branch a few days ago, this issue should be resolved. Date handling has been adjusted to initialize without using parsing, and date handling within the xml file has been improved to be locale agnostic. (You may want to uninstall and reinstall the app in case an older data file is left over, i didn't implement any upgrade code).

Date entry in the UI should use your own locale for converting dates (ie, if your region customarily uses YYYY-MM-DD, that should work) and it should use your locale's date formatting when providing text to cortana.

**Comment by tomaszpolanski** [comment]
Great, thanks.
