### ISSUE TITLE
[Geolocation sample] Cordova plugin

### ISSUE THREAD

**Issue by napcat** [Microsoft/Windows-universal-samples#270]
Hello,

There's no cordova plugin for background geolocation and it's a must have plugin for some type of apps (sport/tracking apps, etc).

I notice there's a sample Geolocation project written in c# and javascript, where a background task is running and sending the user location. 

Is it possible to easily convert this sample to a cordova plugin, so it can be used in the windows (windows 10 universal) cordova platform?

For a windows 10 universal app, build from cordova windows platforma, could the plugin be in C#, or it must be JS (since the cordova project created is a universal JS project)?

Unfortunately, I don't have experience building cordova plugins, but I can learn and help, if anyone is interested in doing this.

**Comment by oldnewthing** [comment]
The question is about extending a sample and not about the sample itself. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
