### ISSUE TITLE
Example for BackButton (VB) - files missing

### ISSUE THREAD

**Issue by adufres** [Microsoft/Windows-universal-samples#273]
Some files are missing in this example...
Assemblyinfo.vb
App.xaml
MainPage.xaml
Senario1.xaml
SecondaryPage,xaml

**Comment by oldnewthing** [comment]
These files are incorporated via `<Link>` directives in the project file.This is called out [in the main README](https://github.com/Microsoft/Windows-universal-samples/#using-the-samples):

>Be sure to unzip the entire archive, and not just individual samples. The samples all depend on the SharedContent folder in the archive.

It's repeated [in the BackButton README](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/BackButton#build-the-sample)

> If you download the samples ZIP, be sure to unzip the entire archive, not just the folder with the sample you want to build.

**Comment by adufres** [comment]
Dear Chen,

Thanks for your answer and help

Yes I got the point and I found the way to get this example properly in Visual Studio 2015.

 

But as you can see (print screen) I get an error message when I try to click on Mainpage.xaml. (VB)

 

Error message for RelativePanel in xaml code.  “Impossible to add content to Splitview the object type”

 

I can run the project without any error message but not possible to see Mainpage.xaml.

 

It’s my first discover with Visual Studio 2015 and Universal dev.

 

Best Regards

 

Armand

 

 

 



 

De : Raymond Chen [mailto:notifications@github.com] 
Envoyé : dimanche, 17 janvier 2016 20:14
À : Microsoft/Windows-universal-samples <Windows-universal-samples@noreply.github.com>
Cc : adufres <adufres@hotmail.ch>
Objet : Re: [Windows-universal-samples] Example for BackButton (VB) - files missing (#273)

 

These files are incorporated via <Link> directives in the project file.This is called out in the main README <https://github.com/Microsoft/Windows-universal-samples/#using-the-samples> :

Be sure to unzip the entire archive, and not just individual samples. The samples all depend on the SharedContent folder in the archive.

It's repeated in the BackButton README <https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/BackButton#build-the-sample> 

If you download the samples ZIP, be sure to unzip the entire archive, not just the folder with the sample you want to build.
