### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by Gr8Gatsby** [Microsoft/Windows-universal-samples#275]
This Sample ReadMe.md: https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/BluetoothRfcommChat

Has a broken link: https://github.com/Microsoft/Windows-universal-samples/blob/master/Samples/DeviceEnumeration this goes to a 404 page

**Comment by oldnewthing** [comment]
Fixed in v2.0.4
