### ISSUE TITLE
Not sure how to signout with WebAuthenticationCoreManager 

### ISSUE THREAD

**Issue by tjones0808** [Microsoft/Windows-universal-samples#277]
I keep calling the SignOutAsync() method on the WebAccount i'm signed in with..but everytime I return to my login screen and recall the RequestTokenAsync method...it keeps finding the account i signed out of and silently signing in... how do i clear the ad cache and completely signout and popup the signin window again?

**Comment by oldnewthing** [comment]
This does not appear to be a question about a sample in this repo. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
