### ISSUE TITLE
back button examples

### ISSUE THREAD

**Issue by slycoderr** [Microsoft/Windows-universal-samples#28]
Are there any examples that use the hardware back button on windows mobile and the back button in tablet mode?

**Comment by rkarman** [comment]
Working on it... :)

In the meantime, the event you want to hook up to is Windows.UI.Core.SystemNavigationManager.GetForCurrentView().BackRequested

And a rudimentary event handler would look something like this:
private void App_BackRequested(object sender, BackRequestedEventArgs e)
{
    Frame rootFrame = Window.Current.Content as Frame;
    if (rootFrame == null)
        return;
    if (rootFrame.CanGoBack)
    {
        e.Handled = true;
        rootFrame.GoBack();
    }
}

The BackRequested event is universal so this handler will work for both the mobile back button and the one in tablet mode.

**Comment by oldnewthing** [comment]
A [BackButton sample](../tree/master/Samples/BackButton) has been added in 4968d97b7ecc92a8772796ae79e703c78012ac68
