### ISSUE TITLE
Windows -Univrsal- App POS Printer Issue

### ISSUE THREAD

**Issue by rizwankhandeveloper** [Microsoft/Windows-universal-samples#280]
Hi,
I have installed driver of Epson TM-T88IV receipt printer, which is working fine if send text to printer from notepad.

but when I am creating a Universal Windows project and access this printer using references of
Windows.Devices.PointOfService;

and I am using following code to access the printer

await DeviceInformation.FindAllAsync(PosPrinter.GetDeviceSelector());

then   PosPrinter.GetDeviceSelector() return null
did not find printer

can you please help me, if I am missing anything

Thanks
Rizwan

**Comment by ThanawutZiios** [comment]
Hello,

I think Epson TM-T88IV is not in supported list, also USB connected printer is not support as well.
https://msdn.microsoft.com/en-us/library/windows/apps/mt426652.aspx

**Comment by rizwankhandeveloper** [comment]
HI ThanawutZiios,



Thanks for your response, it means Serial connected printer will work


and also all other POS devices like scanner, card reader USB connected not work instead of  Serial connected will work




Thanks

Rizwan






________________________________

**Comment by TerryWarwick** [comment]
Rizwan,

Please refer to the Windows.Devices.PointOfService documentation for POSPrinter, Barcode Scanner, Magnetic Stripe Reader and Cash Drawer on MSDN for specific devices and connectivity supported for the specific device type: 

https://msdn.microsoft.com/en-us/library/windows/apps/windows.devices.pointofservice.aspx

POSPrinter for instance states the following:

>Device support
Windows supports the ability to print to network and Bluetooth connected receipt printers using the Epson ESC/POS printer control language. For more information on ESC/POS, see Epson ESC/POS with formatting.
.
While the classes, enumerations, and interfaces exposed in the API support receipt printer, slip printer as well as journal printer, the driver interface only supports receipt printer. Attempting to use slip printer or journal printer at this time will return a status of not implemented. 
.
Support is currently limited to the Network and Bluetooth device models listed in the tables below. USB connected printers are currently not supported. Please check back for additional support to be added in the future. 
.
Stationary POS printers (Network, Bluetooth)
Manufacturer  Model(s)
Epson TM-T88V, TM-T70, TM-T20, TM-U220 
.
Mobile POS printers (Bluetooth)
Manufacturer   Model(s)
Epson Mobilink P20 (TM-P20), Mobilink P60 (TM-P60), Mobilink P80 (TM-P80)  

Terry Warwick
Microsoft

**Comment by noumanullah** [comment]
Hi Terry Warwick,

If we convert the USB interface of Epson TM-U675 printer with Network Interface will it work with `Windows.Devices.PointOfService.PosPrinter.getDeviceSelector()` ?

Thanks,
Nouman

**Comment by TerryWarwick** [comment]
Nouman,

The Epson TM-U675 should work just fine as a Receipt Printer if you swap the USB interface with a Network interface module.  Do make sure that you hang onto that USB interface as we are planning to support USB connectivity in the future.  At present, our implementation will only support the Receipt station of this printer.  POSPrinterCapabilities will report that Slip is not available.

We do not have discovery support for this specific model so you cannot use getDeviceSelector().  You should use FromIdAsync directly using details from our [Out of Band Pairing ](https://msdn.microsoft.com/en-us/windows/uwp/devices-sensors/out-of-band-pairing)article and treat this printer as a Generic ESC/POS network printer rather than an Epson network printer.

Hope this works out for you.

Terry Warwick
Microsoft

**Comment by noumanullah** [comment]
Thanks @TerryWarwick for the quick response, I'll try the solution you provided when I got the network interface module installed.

-Nouman

**Comment by rutvij43** [comment]
Hi, I am trying to discover and connect TM-T88V Epson printer, but Printer is not discovered. I even tried filter with PosConnectionTypes.IP as my printer is connected in LAN but even that is not working.
I have printer IP and port setup. Is there is any way I could discover and connect using IP and port number?

Thanks,
RP
