### ISSUE TITLE
Speech recognition and synthesis sample doesn't work when deployed on IoT version 10.0.10586

### ISSUE THREAD

**Issue by rudeshko** [Microsoft/Windows-universal-samples#281]
On the newest version of Windows IoT, the Speech recognition and synthesis sample stopped working. Continuous dictation (number 7 in the menu), goes Idle right away once I press "Dictate" button.
Microphone permission is on, and everything stayed the same from the 10.0.10240 release which worked perfect.

Note that it only doesn't work when deployed to Minnow Board or Dragon Board, but works locally on the Windows PC.

Any idea on what could cause that? I've tested multiple times and when I revert back to 10.0.10240 it starts working again, but it doesn't work on the newest release.

Thanks

**Comment by anphel31** [comment]
Can you share which specific microphone you have been using?

**Comment by anpilley** [comment]
This is working for me on the 1607 Anniversary update on a raspberry Pi 3 (using a Microsoft LifeChat LX-3000 headset for a microphone). I don't have a Minnow Board or Dragon Board to test, unfortunately.
