### ISSUE TITLE
smalltile-sdk.png must be 44x44 pixels to generate app package.

### ISSUE THREAD

**Issue by akanakia** [Microsoft/Windows-universal-samples#283]
If users want to test samples by generating an application package of solution first then the smalltile-sdk.png image size throws an error in the application package generation process as it is 30x30 pixels instead of being 44x44 pixels (which is the default required icon size). Please rescale this image.

**Comment by cedricbellec** [comment]
Same issue for me

**Comment by WP-tim** [comment]
I too had to correct the file size

**Comment by paleozogt** [comment]
+1

**Comment by oldnewthing** [comment]
Fixed in latest update. Sorry it took so long.
