### ISSUE TITLE
XamlNavigation\NavigationMenu Windows Platform sample doesn't have a design-time preview

### ISSUE THREAD

**Issue by rickengle** [Microsoft/Windows-universal-samples#284]
The XamlNavigation\NavigationMenu sample's SplitView menu on AppShell.xaml only renders at runtime.    In the design-view in VS 2015 I can see the hamburger menu/togglebutton but no content from the icons and menu item labels.

Anyone know if this is a bug or this implementation doesn't provide a design-time view?

Thanks,
 Rick

**Comment by YuliKl** [comment]
@rickengle, thank you for your feedback. The navigation items are created in code-behind and added at run time. It's expected that the items are not available in design view.
