### ISSUE TITLE
BarcodeScanner.cs Migration Problem

### ISSUE THREAD

**Issue by lotzi11** [Microsoft/Windows-universal-samples#285]
I tried to load the Barcode Scanner solution, but wasn't able to load it because the BarcodeScanner.cs was unsupported. I also get the following message:

> BarcodeScanner.csproj: The application which this project type is based on was not found. Please try this link for further information: http://go.microsoft.com/fwlink/?LinkID=299083&projecttype=A5A43C5B-DE2A-4C0C-9213-0A381AF9435A

 Any idea how to fix this?

**Comment by tjones0808** [comment]
loaded up and works fine for me on windows 10 and vs 2015

**Comment by lotzi11** [comment]
Do you have any ideas on what could lead to my issue?

**Comment by tjones0808** [comment]
take a look at the csproj file...maybe min supported version problem?

**Comment by lotzi11** [comment]
I'm running it on VS 2015 and Windows 10. I don't know what I could be missing

**Comment by lotzi11** [comment]
So I did an update on VS 2015, and I am now getting the following error

> Windows-universal-samples-master\Samples\BarcodeScanner\cs\BarcodeScanner.csproj : error  : Root element is missing.

**Comment by oldnewthing** [comment]
I cannot reproduce the problem. Can you do a `git checkout -- BarcodeScanner.csproj` to make sure your local copy didn't get corrupted? If you still have the problem, share the corrupted `BarcodeScanner.csproj` file here.
