### ISSUE TITLE
CallerID - Error in Package.appxmanifest

### ISSUE THREAD

**Issue by simema** [Microsoft/Windows-universal-samples#286]
When trying to associate the app with the store it fails with "the app manifest is invalid".
The line that fails is mobile:Extension Category="windows.phoneCallOriginProvider"

That line is needed to let the user select which phone call origin application is used.
https://msdn.microsoft.com/en-us/windows.applicationmodel.calls.provider.phonecalloriginmanager.showphonecalloriginsettingsui

How do I submit a CallerID app to the store?

**Comment by oldnewthing** [comment]
The issue you are running into is about submitting an app to the Store and not about a broken sample. You can open a support case with our Developer Support team:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel

**Comment by pphadke** [comment]
Actually, if you just add the "mobile" to the IgnorableNamespaces attribute in the <Package> element, then Visual Studio will not thrown the compile error.

**Comment by simema** [comment]
Thank you pphadke! That solved it!
