### ISSUE TITLE
Microsoft Passport Concern

### ISSUE THREAD

**Issue by mohitemji** [Microsoft/Windows-universal-samples#287]
Hi,

I am trying to use Microsoft Passport sample that is in the repository. I am able to register user using Windows Hello (Passport Pin). But during retrieval, that is when I sign out and try to sign in again, it throws me a exception in "RequestSignAsync" method.

What can be possible solution? Am I missing any required step?

**Comment by rajenki** [comment]
Can you share some more details on the exception you're getting? Thanks!

**Comment by mohitemji** [comment]
I get a null reference exception saying parameter: source is null

Sent from Outlook Mobile




On Tue, Feb 2, 2016 at 12:02 PM -0800, "Rajen Kishna" <notifications@github.com> wrote:





Can you share some more details on the exception you're getting? Thanks!

---

**Comment by rajenki** [comment]
Couple of questions:

1. What build of Windows 10 are you using and did you change the target version for the project at all?
2. What line of code exactly do you get the Exception on?
3. Have you tried this on another machine (or have the ability to)?

**Comment by mohitemji** [comment]
Hi..
Let me explain you the scenario:
Am trying to use the sample and run it on my system.
There are few queries that I would like to confirm/ clarified as follows:1. Will an internet connection is required for this? Since server is running locally, I feel internet is not required, kindly confirm.2. Do we need to have biometric/iris data on the system? That is, will I be able to run this sample if I don't have biometrics sensors or Real sense camera?3. Server challenge part is the one where I get exception. Do I need to write any extra code/logic like cryptography or anything else?
With Best Regards,Mohith
Sent from Outlook Mobile




On Tue, Feb 2, 2016 at 12:02 PM -0800, "Rajen Kishna" <notifications@github.com> wrote:





Can you share some more details on the exception you're getting? Thanks!

---

**Comment by mohitemji** [comment]
Hi,
1. Am trying with the latest build of Windows 10. Target version i modified accordingly.
2. When call returns from ServerChallege part to RequestSignAsync , there I get the exception .
3. Ya I did try on multiple machines, same issue.
With Best Regards,Mohith.

Sent from Outlook Mobile

    _____________________________

**Comment by rajenki** [comment]
As for your questions above:

1. An internet connection is not required to run the sample, as the server is indeed run locally, like you stated
2. You don't need to have any special hardware that supports Windows Hello to make this work. At a minimum, you can use the PIN that you set up when enabling Microsoft Passport through the Windows Settings screen
3. The sample should work out of the box, so no extra code should have to be written to make it work

As for your error: it's extremely hard to help if I don't have the exact line of code that the exception occurs one. Can you share the exact line of code, please, and have you tried debugging to see if the jsonChallenge actually contains a challenge that was passed from the server?

**Comment by oldnewthing** [comment]
> Target version i modified accordingly.

What did you change the target version for? The sample as written targets 10586 and runs only on 10586 (and crashes if you run it on 10240). If you change the target to 10240, then the sample will crash on 10586.

**Comment by oldnewthing** [comment]
Closing due to no response.
