### ISSUE TITLE
None of the sample files will build?

### ISSUE THREAD

**Issue by Onjay** [Microsoft/Windows-universal-samples#288]
I've followed the instructions, and downloaded the entire file, checked the unblock zip option, but I'm getting this error plus 1780 more:
Severity	Code	Description	Project	File	Line	Source	Suppression State
Error	CS1061	'App' does not contain a definition for 'InitializeComponent' and no extension method 'InitializeComponent' accepting a first argument of type 'App' could be found (are you missing a using directive or an assembly reference?)	FileAccess	F:\Windows-universal-samples-master\Windows-universal-samples-master\SharedContent\cs\App.xaml.cs	34	IntelliSense	Active

**Comment by ravennasoftware** [comment]
You're probably missing the "Shared Content" folder. From what I can tell you need to download/clone the entire enlistment. The moment you copy a single project somewhere outside the enlistment, it breaks. That's my hunch.

**Comment by oldnewthing** [comment]
That's correct. This is called out in the master README as well as in each sample's individual README.

**Comment by Onjay** [comment]
It turns out that the problem was with a setting that I had set for the NuGet Package Manager. Checking "Allow NuGet to download missing packages" fixed the problem.

Found the answer here: https://github.com/Microsoft/Windows-universal-samples/issues/162
