### ISSUE TITLE
Play Song in background

### ISSUE THREAD

**Issue by ramtinak** [Microsoft/Windows-universal-samples#289]
How can I play a single music in background on win 10 uwp? I don't need any playlist I just wanna play a music from different links (one at the same time) for a reason I Can't add a playlist because the app gets link from internet and plays online. 

Thanks

**Comment by aarononeal** [comment]
The BackgroundAudio sample shows how to play audio in the background:
https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/BackgroundAudio

You do not have to use a playlist, just set a single MediaPlaybackItem.

**Comment by RaminMT** [comment]
Hi
Excuses asking here, Can you please guide me on how to do the same on WP 8.1?

tnx

**Comment by aarononeal** [comment]
It works similarly.
https://code.msdn.microsoft.com/windowsapps/BackgroundAudio-63bbc319
