### ISSUE TITLE
Question : Barcode reader via camera for phone ?

### ISSUE THREAD

**Issue by sgo13** [Microsoft/Windows-universal-samples#290]
Hi,

Is there a sample that shows how to read / scan a barcode via camera.
I'd like to scan barcode with a Phone device, so I can't use PointOfService library.
I read maybe I should use ZXing library, do you have any clue about this ?

Thank you for your help.

**Comment by oldnewthing** [comment]
The issue you are running into not about a broken sample. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel
