### ISSUE TITLE
AdvancedCasting - Disconnecting 5-Multi-View Media Application causes exception in 10.0.10586

### ISSUE THREAD

**Issue by jasoncgould** [Microsoft/Windows-universal-samples#291]
Package.appxmanifest shows MaxVersionTested as 10.0.10240.0 which works correctly in that version.

"The application called an interface that was marshalled for a different thread. 0x8001010E" occurs when disconnecting from a receiver using Windows 10.0.10586

**Comment by SuzyQuzy** [comment]
Please look into this, I am having the same issue.

**Comment by aarononeal** [comment]
We are preparing new samples to address this issue.
