### ISSUE TITLE
SpeechRecognitionAndSynthesis recognition "With UI" freezes window on second click

### ISSUE THREAD

**Issue by luiscantero** [Microsoft/Windows-universal-samples#293]
Scenarios 3 to 6 - after clicking to recognize "With UI", it recognizes speech and the pop-up window closes. When clicking on the same button a second time, the pop-up appears again but when it closes, it freezes the main window as though an invisible modal window were covering it. The application then needs to be killed to be closed.

**Comment by anpilley** [comment]
Hey Luiscantero,

The feature team has reproduced the issue and is investigating.

**Comment by anpilley** [comment]
This appears to have been resolved in the 1607 Anniversary update of Windows 10.
