### ISSUE TITLE
listview

### ISSUE THREAD

**Issue by MannusEtten** [Microsoft/Windows-universal-samples#294]
in my current application i have listview with selection=multiple, but i can't set the selected items initally... i can't find anything on the web so apparently i am doing something weird?

**Comment by oldnewthing** [comment]
The issue you are running into is outside the scope of a broken sample and requires additional debugging to further isolate the problem you are experiencing. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
