### ISSUE TITLE
Automatic Language Detection

### ISSUE THREAD

**Issue by skibulk** [Microsoft/Windows-universal-samples#295]
The documentation for [Windows.Media.Ocr](https://msdn.microsoft.com/en-us/library/windows/apps/windows.media.ocr.aspx?f=255&MSPPError=-2147217396) states that a language must be selected prior to image analysis:

> The language is required information for correct text recognition. Every language uses some language-specific resources, so it must be specified in advance

However [Microsoft's Project Oxford Vision OCR](https://www.projectoxford.ai/demo/vision#Ocr) service offers an "auto-detect" language option. I assume the service implements the Windows Media OCR library? How can we atuo-detect languages in a Windows Runtime application?

**Comment by oldnewthing** [comment]
The issue you are running into is outside the scope of a broken sample. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel
