### ISSUE TITLE
Can we set Font types or Font sizes using the POS Printer class for a receipt ?

### ISSUE THREAD

**Issue by snehithvelma** [Microsoft/Windows-universal-samples#296]

**Comment by oldnewthing** [comment]
The issue you are running into is not related to a broken sample. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel
