### ISSUE TITLE
How to place pivot header to bottom

### ISSUE THREAD

**Issue by JurajPupak** [Microsoft/Windows-universal-samples#298]
Is it possible to place pivot header to bottom? In win10 it should be possible. But I cannot find, how. I dont want to edit template of pivot control.

thank you

**Comment by HppZ** [comment]
I think you have to edit the template. BTW, why you don't?

**Comment by JurajPupak** [comment]
I thought, it can be done by setting some property. but it doesn't. I need to edit the template.
