### ISSUE TITLE
Update JS samples to use the newest version of WinJS

### ISSUE THREAD

**Issue by timgreenfield** [Microsoft/Windows-universal-samples#30]
The JS samples all appear to use a build of WinJS 4.0 other than what was shipped with the VS2015 RC. This makes it very difficult to grab the code and toss it in a new JS UWP app without downgrading WinJS.

**Comment by oldnewthing** [comment]
The samples should be compatible with any vaguely recent version of WinJS. The difference between the version used by the samples and the version that went out with VS2015 RC should be insignificant. Can you give an example that doesn't work if you drop it into a new JS UWP app?

**Comment by timgreenfield** [comment]
Thanks for the quick response. The splitview control appears to have a number of breaking changes (which is part of the chrome for all the samples). I've spent most of the day trying to update it but am still struggling.

**Comment by oldnewthing** [comment]
Thanks for identifying the problem. I'll see what I can do.

**Comment by AdamBraden** [comment]
We are determining the best way to resolve this and also minimize the size of the repo on a users machine.  Expect an update at our RTM release.
