### ISSUE TITLE
Speech Synthesizer voice cuts out on Dragonboard

### ISSUE THREAD

**Issue by rudeshko** [Microsoft/Windows-universal-samples#302]
Tried running this sample app in Debug and Release modes on the Dragonboard 410c (ARM architecture) and the sound cuts out, and sometimes restarts. For example I enter "Hello, how are you?", and it says something like "He.. ello, ....Hell .... e you? are you?".

This doesn't happen locally or on Minnowboard that has x86 architecture. Can anyone validate this and at least make a guess on why it might be causing it to behave like this?

**Comment by anpilley** [comment]
Hi Rudeshko,

Sorry about the delay in responding. I didn't have access to a Dragonboard kit to test on, so I had to reach out to the IoT team to take a look. They've looking into this over the past week, it looks like there might be a general problem with Audio output on Dragonboard systems (apparently the background audio sample has the same problem), not specific to the Speech Synthesis sample. We don't have a workaround, but the IoT team is investigating further. I'll try to let you know if anything comes up.

**Comment by anpilley** [comment]
Our investigation reveals that this problem is specific to Dragonboard. Sorry. We have confirmed that the problem doesn’t exist with Raspberry Pi 2, so you might want to consider switching to that board if you're looking to stick to an ARM-based platform.
