### ISSUE TITLE
This seems to be a BUG with GIF playback sample!

### ISSUE THREAD

**Issue by HppZ** [Microsoft/Windows-universal-samples#307]
Set the UriSource property of GifView element in MainPage.xaml to "http://www.gif.im/uploads/allimg/130518/1-13051Q03309.gif", then an exception raised at UpdateImageSource at line 431.

**Comment by HppZ** [comment]
@oldnewthing  Please fix this bug.

**Comment by oldnewthing** [comment]
The feature team is investigating.

**Comment by HppZ** [comment]
Thanks. My friend who knows about Win2D said that it seems to be a bug of Win2D library.

**Comment by HppZ** [comment]
No message, please?

**Comment by oldnewthing** [comment]
A fix is coming. Thank you for your patience.

**Comment by HppZ** [comment]
Thank you!

**Comment by HppZ** [comment]
I fixed it, I know it is not good, but it works for now, and I am still waiting for your fix.

Several changes I made: 
1, some code inside PrepareFrame:
` private void PrepareFrame(byte[] pixels, Rect frameRectangle, Rect disposeRectangle, int frameIndex)`
And:
`if (!disposeRectangle.IsEmpty || frameIndex == 0)
                    {
                        var imageRectangle = new Rect(new Point(), _canvasImageSource.Size);
                        using (drawingSession.CreateLayer(1.0f, imageRectangle))
                        {
                            drawingSession.Clear(Colors.Transparent);
                        }
                    }`

2, some code inside UpdateImageSource:
`using (var drawingSession = _canvasImageSource.CreateDrawingSession(Colors.Transparent))
                    {
                        drawingSession.DrawImage(_accumulationRenderTarget); // Render target has the composed frame
                    }`

**Comment by HppZ** [comment]
But why CreateDrawingSession with a rect parameter failed and threw that exception？

**Comment by oldnewthing** [comment]
Fixed in https://github.com/Microsoft/Windows-universal-samples/releases/tag/v2.0.5
