### ISSUE TITLE
Missing animations and transitions XAML sample

### ISSUE THREAD

**Issue by martinsuchan** [Microsoft/Windows-universal-samples#308]
This is a feature request. Right now there is no proper sample, how to use or modify **animations and transitions** in UWP XAML/C# apps.  
There is only one sample for WinJS animations, but it is no use for me.  

The sample should ideally cover all topics described here:  
https://msdn.microsoft.com/en-us/library/windows/apps/mt187350.aspx

Thanks

**Comment by JasterAtMicrosoft** [comment]
Hi Martin,

Thanks for the feedback! We will look into adding another sample that covers these topics in more detail.

Best,
Jacob
