### ISSUE TITLE
Titlebar bug?

### ISSUE THREAD

**Issue by Linrstudio** [Microsoft/Windows-universal-samples#310]
The event is not triggered and css effect not working:

In the TitleBar JS project,  TitleBar/js/html/customTitleBar.html:

&lt;!DOCTYPE html>
&lt;html xmlns="http://www.w3.org/1999/xhtml">

&lt;head>
    &lt;title>&lt;/title>
    &lt;script src="/js/customTitleBar.js">&lt;/script>
    &lt;style>**a:hover{color:red;}**&lt;/style>
&lt;/head>

&lt;body class="win-type-body">
    &lt;div id="titleBarContent" style="width: 100%; background: darkgreen; overflow: hidden; z-index: 3">
        &lt;i>Custom title bar&lt;/i>
        &lt;a href="#">**this link is no effect on hover**.&lt;/a>
        &lt;button **onclick**="console.log('click event not trigger when click this');">click me&lt;/button>
    &lt;/div>
&lt;/body>
&lt;/html>

**Comment by oldnewthing** [comment]
Controls in the title bar are not supported on JS.
