### ISSUE TITLE
FromIdAsync Threw an exception: system.Exception:element not found for WifiDirect sample

### ISSUE THREAD

**Issue by GauriP** [Microsoft/Windows-universal-samples#311]
I am trying to run the WifiDirect sample and try and connect it to my wifiDirect capable Samsung S6. i can see the Windows 10 NUC Desktop getting enumerated on the samsung but get the above error when i try and accept the connection. The error happens at this code line
`WiFiDirectDevice wfdDevice = await wfdDeviceTask;`

**Comment by Yorchito** [comment]
@GauriP  The sample app is written in such a way to run it at the same time on two different machines that have WiFiDirect capabilities and make then connect to each other. For making it work with another platform (i.e. android device) you should modify the sample in such a way that both sides have the same behavior. What I think is happening here is that after the WFD connection is established, there is a socket connection that needs to be established but the sample cannot find its counterpart from the other side. Hope it helps. Thanks.
