### ISSUE TITLE
Web Account Management Credentials...

### ISSUE THREAD

**Issue by RushNetMx** [Microsoft/Windows-universal-samples#312]
Hello, is unclear where I have to go for receive this, for a single authentication Microsoft account:

const string AccountClientId 
const string StoredAccountKey

And where I have to set the values in the solution, I understand that I have to associate my application whit my developer account, I already do that. Hope somebody can help me, thanks.

**Comment by rgodugu** [comment]
First register a Windows Developer Account at  : https://developer.microsoft.com/en-us/dashboard/registration . you must then register your app which will generate the stored key and client id .

**Comment by oldnewthing** [comment]
This is explained in the [Related topics](https://github.com/Microsoft/Windows-universal-samples/blob/master/Samples/WebAccountManagement/README.md#related-topics). See also #173.
