### ISSUE TITLE
Background Audio Foreground Crash

### ISSUE THREAD

**Issue by dalchal** [Microsoft/Windows-universal-samples#313]
On Desktop, when app is running and playing a song. If is closed and open quickly. Foreground crash

**Comment by Ran-QUAN** [comment]
Removing the `BackgroundMediaPlayer.Shutdown();` call from the handler of the canceled event may solve the problem, which will block the background playback process from exiting.

Information about calling `Shutdown` method when handling canceled event was removed from the updated documentation for windows 10. So I think it's no longer necessary.

**Comment by maxiunlm** [comment]
I had the same issue. Although it solved that problem, when you restart the app quickly this couldn't play any song any more. But of course if you wait for a few seconds, it will correctly play everything.

**Comment by aarononeal** [comment]
Removing Shutdown() on cancel is the correct fix.

For the RPC exception, the MediaPlayer returned by BackgroundMediaPlayer.Current is a proxy and can throw this any time the background task is not running. The way to recover from this is actually to call Shutdown(). Please note how the sample wraps all player access in a CurrentPlayer method that handles this exception by doing that.

**Comment by shoxik** [comment]
I had really big problem to resume my app after user closed app but I solved my problem. Add to onLaunched condition that if app was closed by user than raise ForegroundApp_Suspending; ForegroundApp_Ressuming; and change in IsMyBackgroundTaskRunning method ReadResetSettingValue to ReadSettingValue but you have to add this method of course :)

**Comment by aarononeal** [comment]
Removal of Shutdown() from the cancellation handler is complete and the fix will be in the next refresh. Thanks all for the feedback.
