### ISSUE TITLE
Pivot Tab sample does not fully replicate the First Party UI and UX

### ISSUE THREAD

**Issue by mdtauk** [Microsoft/Windows-universal-samples#314]
A better sample should be included to show how the First Party apps create their tabs with pivots.  Including selected items in Accent Colour, the SelectionHint bar, and the background behind the tabs.

Making this easy to template would benefit all users.

**Comment by oldnewthing** [comment]
This request is out of scope for the UWP Samples repo, which is focused on demonstrating how to use the API correctly, as opposed to restyling it to have a particular look.
