### ISSUE TITLE
App crashing on clicking SystemTransportControl albumart/title

### ISSUE THREAD

**Issue by iamsid** [Microsoft/Windows-universal-samples#315]
When trying to open the application from the SystemMediaTransportControls pop-up (controls that show up when managing volume from keyboard/physical-keys), the app just randomly exits.
I have had this problem in my app's code too. I could not debug it.

This is what output window shows:
**The program '[11872] Windows.Media.BackgroundPlayback.exe' has exited with code 1 (0x1).
The program '[752] BackgroundAudio.exe' has exited with code -1 (0xffffffff).**

**Comment by aarononeal** [comment]
Known issue. Please see https://github.com/Microsoft/Windows-universal-samples/issues/304#issuecomment-188561961.
