### ISSUE TITLE
Cant use System.Net?

### ISSUE THREAD

**Issue by kinger6** [Microsoft/Windows-universal-samples#316]
System.Net seem's to be fine when doing (using System.Net) but i cant access any classes in the namespace.. Anyone have any fix's?

**Comment by oldnewthing** [comment]
This question isn't about any of the samples in this repo. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel
