### ISSUE TITLE
Wasapi data loss

### ISSUE THREAD

**Issue by nehaysingh** [Microsoft/Windows-universal-samples#319]
I have used Wasapi API to play and record audio. I need to frequently start and stop Audio client for capture and render live data. My application is VoIP based.
I have seen an issue. When I play the audio and pause through IAudioClient3 -> Stop() then restart capture  that was already paused through IAudioClient3-> Stop(), there are silence packet for initial 1 to 2 sec volley and then audio gets captured with loss of initial 2 sec audio packet.

But If I continuous do capture stop and start without in between play then there is no issue. 
Any help would be appreciated.

**Comment by oldnewthing** [comment]
The issue you are running into is not a problem with a specific sample. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account

2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
