### ISSUE TITLE
NFC Sample issues

### ISSUE THREAD

**Issue by cyberh0me** [Microsoft/Windows-universal-samples#327]
please could you check your NFC sample, even if i download the complete repository it fails to build (for arm)

Severity	Code	Description	Project	File	Line	Suppression State
Warning	MSB3245	Could not resolve this reference. Could not locate the assembly "Windows.Devices.SmartCards.SmartCardEmulatorContract". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	NfcHceBackgroundTask	C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets	1819	
Error		Metadata file 'D:\src\Microsoft\Windows-universal-samples\Samples\Nfc\ARM\Debug\NfcHceBackgroundTask\NfcHceBackgroundTask.winmd' could not be found	Nfc	D:\src\Microsoft\Windows-universal-samples\Samples\Nfc\Nfc\CSC		
Error	C2039	'SmartCardEmulator': is not a member of 'Windows::Devices::SmartCards' (compiling source file BgTask.cpp)	NfcHceBackgroundTask	d:\src\microsoft\windows-universal-samples\samples\nfc\nfchcebackgroundtask\BgTask.h	42	

may be its possible to provide a "simple" nfc sample which only shows the usage of read and write nfc tags without smartcard and encryption features?

**Comment by akbiggs** [comment]
Also running into this issue after downloading the complete samples .zip, unblocking and loading up the NFC sample .sln

**Comment by akbiggs** [comment]
It seems that the .dll for SmartCardEmulatorContract is only available if you are developing on Windows 10 Mobile -- if you search on [this page](https://msdn.microsoft.com/en-us/windows/uwp/devices-sensors/host-card-emulation) for SmartCardEmulatorContract, you'll see there's a bit where they check to see if that assembly exists to verify that they're on Mobile.

I'm new to the Windows 10 ecosystem though, so I'm not exactly sure what the distinction is. Can I develop Mobile apps even if I'm running Windows 10 Desktop?

**Comment by marklan** [comment]
@akbiggs is right. The SmartCardEmulatorContract is only available in the "Windows Mobile Extensions for the UWP". You can find more information about Extension SDKs for UWP here: https://msdn.microsoft.com/en-us/library/windows/apps/dn609832.aspx#UAP_PlatformCode 

From the build error message, it sounds like Visual Studio isn't finding the SmartCardEmulatorContract winmd file on your computer. Can you search under "C:\Program Files (x86)\Windows Kits\10\References\Windows.Devices.SmartCards.SmartCardEmulatorContract" and see if you can find a file called "Windows.Devices.SmartCards.SmartCardEmulatorContract.winmd"?

Also, under that directory, do you see two directories: "1.0.0.0" and "2.0.0.0"? The issue might be that the Nfc project is targeting the "Windows Mobile Extensions for the UWP" version 10586, but you might have only the version 10240 SDK installed. You can see which version of the Mobile Extensions the project is targeting by right-clicking the Nfc project and by going to Add > Reference. Then go to Universal Windows > Extensions and see what version of the "Windows Mobile Extensions for the UWP" is checked (version 10586 should be checked).

To check what version of the SDK you have installed, go to the Programs and Features control panel and check for "Windows Software Development Kit". If it says "Windows 10.0.10586.15" or "Windows 10.0.10586.212" after "Windows Software Development Kit", then you have the version 10586 SDK installed. If you don't have the version 10586 SDK installed, then you can install it by right-clicking on Visual Studio 2015 in the Programs and Features list, and then click Change. Click Modify, check "Tools for Universal Windows Apps (1.3.2) and Windows SDK (10.0.10586)", and then click Update.

**Comment by oldnewthing** [comment]
Closed due to no response.
