### ISSUE TITLE
XamlAnimatedGif Memory leak in wp

### ISSUE THREAD

**Issue by FgoDt** [Microsoft/Windows-universal-samples#330]
there is Memory leak for arm build, if i use this code in pivotitem one and build for arm. then select pivotitem two there is memory leak .

in my test when  i select pivotitem two and StopAnimation() func use code is ok

**Comment by JasterAtMicrosoft** [comment]
Hi @FgoDt! Sorry for the delay. If possible, could you please provide a small project that demonstrates this issue?

**Comment by FgoDt** [comment]
Hi @JasterAtMicrosoft  project is here https://onedrive.live.com/redir?resid=2E6A88BF23516C0C!111&authkey=!AGvGuYL5pdjJ0z4&ithint=file%2czip just buid for ARM there was memory leak

**Comment by JasterAtMicrosoft** [comment]
Thanks! I can repro the memory leak and have a theory about what is going on. I'll respond to this thread with further updates.

**Comment by oldnewthing** [comment]
Fixed in [v1.0.21](https://github.com/Microsoft/Windows-universal-samples/releases/tag/v1.0.21)
