### ISSUE TITLE
LockScreenApps sample for Windows 10 does not appear in Notification Settings

### ISSUE THREAD

**Issue by PonderThis** [microsoft/Windows-universal-samples#331]
Scenario 1 for the LockScreenApps sample for Windows 10 notes that it needs the user to add it to the lock screen. The button "Go to Notification Settings" successfully brings up Notifications & Settings, and I have both "Show app notifications" and "Show notifications on the lock screen" set to On, but under "Show notifications from these apps" the app does not appear. And therefore, if I ignore that and go to Scenario 2 and attempt to send badge or tile notifications and then check the lock screen, there's nothing there.

FYI, I just redownloaded the full universal sample zip and recompiled the sample and get the same result on both my desktop and tablet.

**Comment by oldnewthing** [comment]
This sample was originally written for Windows 8. I think the relevant setting has moved to Settings, Personalization, Lock screen, Choose apps to show quick status.

**Comment by oldnewthing** [comment]
Fixed in [v8.0.8](https://github.com/microsoft/Windows-universal-samples/releases/tag/v8.0.8). Sorry it took so long.
