### ISSUE TITLE
Windows-universal-samples / Samples / ShareTarget / 

### ISSUE THREAD

**Issue by gregdegruy** [Microsoft/Windows-universal-samples#332]
Will there be a JavaScript implementation of this?

**Comment by hiepxanh** [comment]
@gregdegruy  yeah, it implementing, can you close this issue ?

**Comment by oldnewthing** [comment]
In the meantime, you can refer to [the old Windows 8 sample](https://code.msdn.microsoft.com/windowsapps/Sharing-Content-Target-App-e2689782/view/SourceCode#content), which is available in JavaScript. It probably still works in Windows 10.

**Comment by hiepxanh** [comment]
Thanks god, I cannot search google for any javascript instruction for UWP for windows 10. This is the first time I know the windows 8 have example and full guideline. Why don't they put that line as a reference link to the end of UWP windows 10 document ? that old good example for windows 8 will never ever be index or we can know there's exist if you don't tell me.

**Comment by oldnewthing** [comment]
I will pass this feedback to the feature team. I don't know why they deleted the JavaScript version.

**Comment by hiepxanh** [comment]
Thank you, that so much help from you to support me to rule the UWP world by javascript.

**Comment by Jaifroid** [comment]
FYI @oldnewthing  With the provided settings, the ShareTarget JS sample cannot be built in Visual Studio Community 2017. I get this error:
```
Error	 "10.0.18362.0" is not a supported value for TargetPlatformVersion.
Please change it on the Project Property page.	ShareTarget 
```
I have to change, manually, the target and minimum versions to 10.0.17763.0. Then I can build it.
My VS installer reports VS 2017 is up-to-date, and I have added the latest SDK that is available under "Individual Components" which is 10.0.16299.0.
The samples should be runnable by all clients with a reasonably up-to-date version, and not just "Enterprise" clients (for example), so I suggest lowering the TargetPlatformVersion (and minimum platform version) in this, and probably other, samples for JS.

**Comment by oldnewthing** [comment]
Instructions for installing the 18362 SDK are available [here](https://blogs.windows.com/buildingapps/2019/04/18/start-developing-on-windows-10-may-2019-update-today/#f0omMKljXFKXTWdm.97). All samples in the `master` branch assume the latest SDK.

**Comment by Jaifroid** [comment]
OK, thanks for the detailed explanation @oldnewthing! As this SDK is very new, clearly it hasn't made its way into the installer for VS2017, hence the confusion.
