### ISSUE TITLE
SmsSendAndReceive not work in my app

### ISSUE THREAD

**Issue by vladik1996** [Microsoft/Windows-universal-samples#334]
SmsSendAndReceive sample good work in my phone, but I want use sms receive in my app. 
I have problem with <r:Capability Name="cellularMessaging" />, when I put this in my manifest, I have a error: 

> Validation error. error C00CE014: App manifest validation error: The app manifest must be valid as per schema: Line 42, Column 6, Reason: Element '{http://schemas.microsoft.com/appx/manifest/foundation/windows10/restrictedcapabilities}Capability' is unexpected according to content model of parent element '{http://schemas.microsoft.com/appx/manifest/foundation/windows10}Capabilities'. Expecting: {http://schemas.microsoft.com/appx/manifest/foundation/windows10}DeviceCapability.

Then I'm try   <DeviceCapability Name="cellularMessaging" />, it's code gut compile, but  can't deploy in phone, error:

> Error : DEP0001 : Unexpected Error: Package could not be registered.

**Comment by oldnewthing** [comment]
As you noted, this is not a problem with the SmsSendAndReceive sample. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
