### ISSUE TITLE
Advertising sample - downling link to the Advertising SDK is broken

### ISSUE THREAD

**Issue by edetoc** [Microsoft/Windows-universal-samples#335]
in readme.md / Prerequisites, the url behind "download it here" doesn't work.

**Comment by edetoc** [comment]
correct link seems to be this one now:
https://visualstudiogallery.msdn.microsoft.com/229b7858-2c6a-4073-886e-cbb79e851211

**Comment by oldnewthing** [comment]
Thanks for the report. Looks like a problem on the Advertising team's redirect. I'll let them know.

**Comment by oldnewthing** [comment]
The Advertising team fixed the redirect. Thanks for reporting it.
