### ISSUE TITLE
I can't receiving any data from serial RS232 device  

### ISSUE THREAD

**Issue by thkaw** [Microsoft/Windows-universal-samples#336]
I encounter this problem for few days

Interesting,  If you using https://ms-iot.github.io/content/en-US/win10/samples/SerialSample.htm

You may can work and receiving some data from RS232

but, SAME Logic wrote by me, won't RX anythings... But I can write somethings to RS232 Device.

That is really weird... I don't know why happen this kind of strange things.

I also try sample from https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/CustomSerialDeviceAccess

And for this sample, TX is OK, but RX will stuck at:

`UInt32 bytesRead = await loadAsyncTask;`

There still have data Tx from Device to computer, but seem this line didn't response any data.

I'm using VS 2015 Update1 with W10 10586 
Any idea?

**Comment by thkaw** [comment]
I think problem happen because RS232 Converter Driver,

My RS232 Converter chip is prolific, I try to install old version that from manufacture gave.

And It solve this problem...

I buy another FTDI converter, also work with Windows Buil-in driver.

**Comment by aholeinmyhead** [comment]
Thank you for confirming it is a driver issue
