### ISSUE TITLE
Avoid polling on client to connect (rfcomm)

### ISSUE THREAD

**Issue by fabiocbr75** [Microsoft/Windows-universal-samples#337]
there is a way to be notified when the device is in range of the bluetooth to avoiding polling?
I have client (uwp) and server (iot-uwp) and the only way for the client to detect if is possibile comunicate with the server is a long polling and try to execute the connect api.
I already tried with this events but doesn't work:
chatService.Device.SdpRecordsChanged += Device_SdpRecordsChanged;
chatService.Device.ConnectionStatusChanged += Device_ConnectionStatusChanged;

The only api that ensure that the connection is possibile is:
await chatSocket.ConnectAsync(chatService.ConnectionHostName, chatService.ConnectionServiceName);

but to do that i must run in a polling with a big consume of battery.

Thanks for help.

**Comment by kpathakota** [comment]
A combination of the Advertisement APIs and the socket APIs will probably work pretty well.  Take a look at this sample: https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/BluetoothAdvertisement

**Comment by fabiocbr75** [comment]
Good idea but it's valid only with BLE.
In your opinion are there alternative with bluetooth 2 or 3?

Thanks

**Comment by kpathakota** [comment]
No, those are not power efficient for scanning and you will have to constantly poll.  What is the difficulty with using BLE? Most radios these days are dual mode.

**Comment by fabiocbr75** [comment]
No problem, BLE it's OK.
I would like to use a old hama bluetooth 2.1 Class 1 but i can change with other bluetooth 4.
Thanks for suggestion.

**Comment by DelfCo** [comment]
We recently published a new sample that, among other things, demonstrates turning on the lights in a person's office when their mobile phone gets within Bluetooth range. You might find it helpful.
http://github.com/Microsoft/Windows-appsample-huelightcontroller
