### ISSUE TITLE
Allow using of Binding like a custom markup extension for XAML

### ISSUE THREAD

**Issue by Makeloft** [Microsoft/Windows-universal-samples#338]
Hello, my name is Vladimir
e-mail: makeman@tut.by

I want to suggest range of wonderful improvements for native XAML and related MVVM developing.
Please, see complete source code, for example, "Hello Aero Project" for more details:
https://onedrive.live.com/?cid=c8d6e2f8053ddcfb&id=C8D6E2F8053DDCFB%2123902&authkey=!AMT2QVotfWTReos

Allow using of Binding like a custom markup extension for XAML

There is old lack of native XAML
https://wpdev.uservoice.com/forums/110705-universal-windows-platform/suggestions/7232264-add-markup-extensions-to-and-improve-winrt-xaml

I had seen the new post about custom markup extensions on UWP apps but it is not work at all
https://msdn.microsoft.com/en-us/windows/uwp/xaml-platform/customresource-markup-extension
At first, I install latest version of Visual Studio and try to create custom extension for localization but described in current article way with derive from CustomXamlResourceLoader class doesn't work :(
I still have compiler errors:
Cannot assign 'Localizing' into property 'Text', type must be assignable to 'String'
Type 'local:Localizing' is used like a markup extension but does not derive from MarkupExtension.

Second, please, see ABindingExtension class and read the article about it
http://makeloft.xyz/lessons/xaml/custom-binding-extensions

```
 public abstract class ABindingExtension : Binding, IValueConverter
    {
        protected ABindingExtension()
        {
            Source = Converter = this;
        }

        protected ABindingExtension(object source) // Source, RelativeSource, null for DataContext
        {
            var relativeSource = source as RelativeSource;
            if (relativeSource == null && source != null) Source = source;
            else RelativeSource = relativeSource;
            Converter = this;
        }

        public abstract object Convert(object value, Type targetType, object parameter, CultureInfo culture);

        public virtual object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
        {
            throw new NotImplementedException();
        }
    }

```
This class very good and memory safe alternative for classical MarkupExtension. This approach works even on old Windows Phone Silverlight where is not MarkupExtension class.

I tried to apply this way to UWP but there are two artificial limitations of XAML-parser.

Look at sample

```
    public abstract class ABindingExtension : Binding, IValueConverter
    {
        protected ABindingExtension()
        {
            Source = Converter = this;
        }

        protected ABindingExtension(object source) // Source, RelativeSource, null for DataContext
        {
            var relativeSource = source as RelativeSource;
            if (relativeSource == null && source != null) Source = source;
            else RelativeSource = relativeSource;
            Converter = this;
        }

        public abstract object Convert(object value, Type targetType, object parameter, string culture);

        public virtual object ConvertBack(object value, Type targetType, object parameter, string culture)
        {
            throw new NotImplementedException();
        }
    }

    public class Localizing : ABindingExtension
    {
        public override object Convert(object value, Type targetType, object parameter, string culture)
        {
            return "test"; // return value by key
        }
    }
```

For example
```
<Control>
   <Control.DataContext> // is object
      <Localizing/>             // called Convert method like expected!
   <Control.DataContext>
</Control>
```

output => Works fine! 
But

```
<TextBlock>
   <TextBlock.Text> // is string
      <Lokalizing/>
   <TextBlock.Text>
</TextBlock>
```

output => Cannot assign 'Localizing' into property 'Text', type must be assignable to 'String'

Also
`<Control DataContext="{local:Localizing}"/>`

output => Type 'local:Localizing' is used like a markup extension but does not derive from MarkupExtension.

Pease, check this artificial limitaions for Bindings becouse all works fine, but only XAML-preprocessor get errors!

P.S. May be you will be interested by SwichConverter and some other power improvements for XAML and MVVM

```
<Grid.Resources>
    <SwitchConverter x:Key="NumberSwitchConverter" Default="Hello">
        <Case Key="0" Value="Zero"/>
        <Case Key="1" Value="One"/>
    </SwitchConverter>
</Grid.Resources>
<TextBlock Text="{Binding Number, Converter={StaticResource NumberSwitchConverter}}"/>
```

Number==0 => out: Zero
Number==1 => out: One
Number==2 => out: Hello

Please, see code samples and Aero Framework library
https://onedrive.live.com/?authkey=%21AMT2QVotfWTReos&cid=C8D6E2F8053DDCFB&id=C8D6E2F8053DDCFB%2123902&parId=C8D6E2F8053DDCFB%2123896&action=locate

Thanks!Allow using of Binding like a custom markup extension for XAML

There is old lack of native XAML
https://wpdev.uservoice.com/forums/110705-universal-windows-platform/suggestions/7232264-add-markup-extensions-to-and-improve-winrt-xaml

I had seen the new post about custom markup extensions on UWP apps but it is not work at all
https://msdn.microsoft.com/en-us/windows/uwp/xaml-platform/customresource-markup-extension
At first, I install latest version of Visual Studio and try to create custom extension for localization but described in your article way with derive from CustomXamlResourceLoader class doesn't work :(
I still have compiler errors:
Cannot assign 'Localizing' into property 'Text', type must be assignable to 'String'
Type 'local:Localizing' is used like a markup extension but does not derive from MarkupExtension.

Second, please, see ABindingExtension class and read the article about it
http://makeloft.xyz/lessons/xaml/custom-binding-extensions

```
 public abstract class ABindingExtension : Binding, IValueConverter
    {
        protected ABindingExtension()
        {
            Source = Converter = this;
        }

        protected ABindingExtension(object source) // Source, RelativeSource, null for DataContext
        {
            var relativeSource = source as RelativeSource;
            if (relativeSource == null && source != null) Source = source;
            else RelativeSource = relativeSource;
            Converter = this;
        }

        public abstract object Convert(object value, Type targetType, object parameter, CultureInfo culture);

        public virtual object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
        {
            throw new NotImplementedException();
        }
    }

```
This class very good and memory safe alternative for classical MarkupExtension. This approach works even on old Windows Phone Silverlight where is not MarkupExtension class.

I tried to apply this way to UWP but there are two artificial limitations of XAML-parser.

Look at sample

```
    public abstract class ABindingExtension : Binding, IValueConverter
    {
        protected ABindingExtension()
        {
            Source = Converter = this;
        }

        protected ABindingExtension(object source) // Source, RelativeSource, null for DataContext
        {
            var relativeSource = source as RelativeSource;
            if (relativeSource == null && source != null) Source = source;
            else RelativeSource = relativeSource;
            Converter = this;
        }

        public abstract object Convert(object value, Type targetType, object parameter, string culture);

        public virtual object ConvertBack(object value, Type targetType, object parameter, string culture)
        {
            throw new NotImplementedException();
        }
    }

    public class Localizing : ABindingExtension
    {
        public override object Convert(object value, Type targetType, object parameter, string culture)
        {
            return "test"; // return value by key
        }
    }
```

For example
```
<Control>
   <Control.DataContext> // is object
      <Localizing/>             // called Convert method like expected!
   <Control.DataContext>
</Control>
```

output => Works fine! 
But

```
<TextBlock>
   <TextBlock.Text> // is string
      <Lokalizing/>
   <TextBlock.Text>
</TextBlock>
```

output => Cannot assign 'Localizing' into property 'Text', type must be assignable to 'String'

Also
`<Control DataContext="{local:Localizing}"/>`

output => Type 'local:Localizing' is used like a markup extension but does not derive from MarkupExtension.

Pease, check this artificial limitaions for Bindings becouse all works fine, but only XAML-preprocessor get errors!

P.S. May be you will be interested by SwichConverter and some other power improvements for XAML and MVVM

```
<Grid.Resources>
    <SwitchConverter x:Key="NumberSwitchConverter" Default="Hello">
        <Case Key="0" Value="Zero"/>
        <Case Key="1" Value="One"/>
    </SwitchConverter>
</Grid.Resources>
<TextBlock Text="{Binding Number, Converter={StaticResource NumberSwitchConverter}}"/>
```

Number==0 => out: Zero
Number==1 => out: One
Number==2 => out: Hello

Please, see code samples and Aero Framework library
https://onedrive.live.com/?authkey=%21AMT2QVotfWTReos&cid=C8D6E2F8053DDCFB&id=C8D6E2F8053DDCFB%2123902&parId=C8D6E2F8053DDCFB%2123896&action=locate

Thanks!

**Comment by oldnewthing** [comment]
This isn't an issue with the XAML Binding sample. If you have suggestions for future features, please use [Connect](http://connect.microsoft.com/).

**Comment by Makeloft** [comment]
Hello, Raymond, thank for your reply!  I want suggest to Microsoft complex of XAML-C#-MVVM related improvements.I sure it will be great step up into developing of XAML-platforms. Now all features you can see into source codes (for example HelloAero project)https://onedrive.live.com/redir?resid=C8D6E2F8053DDCFB!23902&authkey=!ADY8mmXQLoDF94Y&ithint=file%2czip There are available documentation on Russian language therehttp://makeloft.xyz/lessons and one article translated into English about Custom Binding Extensionshttp://makeloft.xyz/lessons/xaml/custom-binding-extensions I understand that I can use Connect program, but it is very difficult to describe all concepts through them.And I want find people who make architecture XAML-platform and communicate directly! Raymond, do you know similar persons? Sincerely, Vladimir 06.04.2016, 03:43, "Raymond Chen" <notifications@github.com>:This isn't an issue with the XAML Binding sample. If you have suggestions for future features, please use Connect.—You are receiving this because you authored the thread.Reply to this email directly or view it on GitHub
