### ISSUE TITLE
Windows Hello README broken link

### ISSUE THREAD

**Issue by SergioMorchon** [Microsoft/Windows-universal-samples#339]
From the following sample:
https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/MicrosoftPassport
The link *Microsoft Passport and Windows Hello developer how-to guide* is followed by the download page of Visual Studio, not a guide.

**Comment by oldnewthing** [comment]
Hm, when I follow [the link](http://go.microsoft.com/fwlink/p/?LinkId=522066), it takes me to [Microsoft Passport and Windows Hello](https://msdn.microsoft.com/en-us/windows/uwp/security/microsoft-passport) in MSDN. Are you sure you are clicking the correct link?
