### ISSUE TITLE
Windows Retina scanner

### ISSUE THREAD

**Issue by e3024650** [Microsoft/Windows-universal-samples#341]
Hi All,

Im pretty much new to the windows world, im developing a windows app where i have to make use of retina scanner api for one of my application, can somebody tell me how to use the api and if u have any example of doing it. please share with me.

**Comment by oldnewthing** [comment]
The [Microsoft Passport sample](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/MicrosoftPassport) and [KeyCredentialManager sample](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/KeyCredentialManager) show how to use Windows Hello authentication.

**Comment by e3024650** [comment]
@oldnewthing Thank you so much for sharing above informtion

**Comment by e3024650** [comment]
@oldnewthing  i have couple of questions related to iris scanning process.

1. I need only retina scan feature for my windows app, so do i need to worry about Microsoft Passport
2. Do i need to import the entire sample project into my visual studio 2015 or just Microsoft Passport API is enough ?
3. In the project Samples, i see lot of stuffs listed, i guess they are all different API's, am i ritte ?
4. Is Windows hello part of Microsoft Passport API ?

**Comment by oldnewthing** [comment]
The retina scan is used to access the private key stored in the TPM. You can use that private key for whatever you like; doesn't have to be for remote authentication.
