### ISSUE TITLE
[UWP JS] Audio file is not supported

### ISSUE THREAD

**Issue by Odonno** [Microsoft/Windows-universal-samples#342]
I am trying to use `HTMLAudioElement` component in a Project Westminster application (Windows 10 UWP app) but it seems it does not work.

Indeed, it works perfectly on Windows Desktop but when I try to use the same code on Windows Mobile, I get the error `audio file is not supported`. The file is a *.mp3 file in a distant url.

**Comment by oldnewthing** [comment]
This issue does not appear be related to a sample. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.

**Comment by Odonno** [comment]
Ok thanks... but it costs too much for this kind of bug.

**Comment by clinton05** [comment]
Why doesnt microsoft log the issue on his behalf ??

**Comment by Odonno** [comment]
In my opinion, I think it's a Edge browser bug (I had the same bug when checking on my mobile Edge app).

I can add it to the support backlog of the product but I don't where to add it, is there a place in the Edge org on GitHub (https://github.com/MicrosoftEdge) ?

**Comment by Odonno** [comment]
Ok, I just learned that there is a Microsoft Edge issue tracker (https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/).

I created a new issue here (https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7131025/).
