### ISSUE TITLE
A Navigation Bug in XamlMasterDetail

### ISSUE THREAD

**Issue by Iamnvincible** [microsoft/Windows-universal-samples#343]
I've found there's a navigation bug in XamlMasterDetail.
It would occur if you follow the steps below
1. you are in a `NarrowState` and it is a `DetailPage` 
2. click the back button on the title bar
3. make the window wider till you are in `DefaultState` 
4. narrow the window to `NarrowState`
5. you will see the page navigate to the same page in step 1. 

I think this circumstance is wrong，in step 5 , user expects to navigate to the `NarrowState` which is a `MasterDetailPage` rather than `DetailPage`

If you agree with me, the solution follows

First, change the function `OnBackRequested` in `DetailPage.xaml.cs` like this

```
   private void OnBackRequested()
        {

            var back = Frame.BackStack;
            if (back.Count > 0)
            {
                var entry = back[back.Count - 1];
                back.RemoveAt(back.Count - 1);
                var newentry = new PageStackEntry(entry.SourcePageType, null, entry.NavigationTransitionInfo);
                back.Add(newentry);
            }
            Frame.GoBack(new DrillInNavigationTransitionInfo());
        }
```

second, add an `else`sentence after `if` in `OnNavigatedTo` in `MasterDetailPage.xaml.cs` like this

```
            if (e.Parameter != null)
            {
                // Parameter is item ID
                var id = (int)e.Parameter;
                _lastSelectedItem =
                    items.Where((item) => item.ItemId == id).FirstOrDefault();
            }
           else
            {
                _lastSelectedItem = null;
            }
```

That's all , I hope you can fix this problem.
Thanks.

**Comment by oldnewthing** [comment]
I've asked the feature team to investigate.

**Comment by oldnewthing** [comment]
The feature team has decided not to fix this issue.
