### ISSUE TITLE
Hosting ASP.NET Web API in a Windows Store app

### ISSUE THREAD

**Issue by anjdreas** [Microsoft/Windows-universal-samples#346]
##### Usecase
I have a hosted web app for viewing log files and live log streams. I also want to reuse the server side to host locally in a Windows Store app, but I am not able to add the nugets I need.

Is there a way to achieve this today? 
If not, is it likely to happen?

##### Environment
* Microsoft Visual Studio Community 2015 Version 14.0.25123.00 Update 2
* Microsoft .NET Framework Version 4.6.01038
* NuGet Package Manager   3.4.2
* Visual Studio Tools for Universal Windows Apps   14.0.25123.00
* UWP C# project, target/min version 10.0 10586/10.0 10240

##### Attempt 1) ASP.NET MVC5 OWIN self hosting
Nuget: `Microsoft.AspNet.WebApi.SelfHost`
Microsoft.AspNet.WebApi.SelfHost 5.2.3 is not compatible with UAP,Version=v10.0.

##### Attempt 2) ASP.NET Core 1.0 hosting
Nuget: `Microsoft.AspNetCore.Hosting` (1.0.0-rc1 up to rc3-20533)
I get a bunch of errors, similar to this one:
`System.Console 4.0.0-rc2-23931 provides a compile-time reference assembly for System.Console on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x64.`

Full error log: https://gist.github.com/anjdreas/f4acc70af4ecc868d2beec8f2f0f187a

##### Related
https://github.com/aspnet/Hosting/issues/291

**Comment by oldnewthing** [comment]
This question doesn't appear to be related to any of the samples in this repo. You can open a support case with our Developer Support team for further assistance:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel
