### ISSUE TITLE
Sharing HTML with embedded images does NOT work anymore

### ISSUE THREAD

**Issue by weird-dreams** [Microsoft/Windows-universal-samples#348]
Hi,
I added sharing to my app and referred to this example from Microsoft:
https://msdn.microsoft.com/en-us/library/windows/apps/xaml/hh973055
This is no more working for a UWP app on windows 10 (Build 1151). It worked on Win 8.1 app very well.
I can select the mail app but after selecting the mail account - I see a progress panel and nothing more...
**Seems to be a deadlock in mail app!?**

Here is the code from the official sample:
`private` async void DatatransferManagerDataRequested(DataTransferManager aSender, DataRequestedEventArgs

 aEventArgs)
        {
            DataRequest request = aEventArgs.Request;
            DataRequestDeferral dataRequestDeferral = request.GetDeferral();

```
        request.Data.Properties.Title = "Share Html Example";
        request.Data.Properties.Description =
            "Demonstrates how to share an HTML fragment with a local image.";

        string localImage = "ms-appx:///Assets/Logo.png";
        string htmlExample = "<p>Here is a local image:</br><img src=\"" + localImage + "\"></p>";
        string htmlFormat = HtmlFormatHelper.CreateHtmlFormat(htmlExample);
        request.Data.SetHtmlFormat(htmlFormat);

        // Because the HTML contains a local image, we need to add it to the ResourceMap.
        RandomAccessStreamReference streamRef =
             RandomAccessStreamReference.CreateFromUri(new Uri(localImage));
        request.Data.ResourceMap[localImage] = streamRef;

        dataRequestDeferral.Complete();
    }`
```

**Comment by oldnewthing** [comment]
This appears to be a platform issue, not a sample issue. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
