### ISSUE TITLE
XamlAutoSuggestBox result to Listview

### ISSUE THREAD

**Issue by Telejka** [Microsoft/Windows-universal-samples#350]
Hi! How could I combine your XAML Listview (Master Detail) and XamlAutoSuggestBox samples?
I need to search value through AutoSuggestBox and show results in Listview.

Thank you!

**Comment by oldnewthing** [comment]
The purpose of a sample is to show a single feature. Showing all the ways that features can be combined is not practical for a sample. You can open a support case with our Developer Support team to get assistance on how to develop app.
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel
