### ISSUE TITLE
Simple Communication error

### ISSUE THREAD

**Issue by yenachem** [Microsoft/Windows-universal-samples#351]
I get the message "This project is out date" when I try to build. Then I get errors: 
Metadata file 'C:\Users\*****\Downloads\Windows-universal-samples-master\Windows-universal-samples-master\Samples\SimpleCommunication\cs\Release\Microsoft.Samples.SimpleCommunication\Microsoft.Samples.SimpleCommunication.winmd' could not be found	SimpleCommunication	C:\Users\*****\Downloads\Windows-universal-samples-master\Windows-universal-samples-master\Samples\SimpleCommunication\cs\CSC		
Error	MSB3491	Could not write lines to file "Release\Microsof.dfeea5aa.tlog\Microsoft.Samples.SimpleCommunication.lastbuildstate". The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.	Microsoft.Samples.SimpleCommunication	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets	312

**Comment by oldnewthing** [comment]
The reason is right there in the error message.

> The specified path, file name, or both are too long.

Put the repo in a shorter path. C:\Users**\Downloads\Windows-universal-samples-master\Windows-universal-samples-master is too long.
