### ISSUE TITLE
Sample for Cash Drawer which is connected to a supported POS Printer

### ISSUE THREAD

**Issue by terry-dai** [Microsoft/Windows-universal-samples#352]
I current need to open the cash drawer which is connected to an Epson TM-T88V.

According to the following link 
https://msdn.microsoft.com/en-us/library/windows/apps/mt426650.aspx
in the Remarks section, it says:
>  Additionally, cash drawers that don’t have network or Bluetooth capabilities can be connected via the DK port on a supported POS printer

So I guess I may be able to use PointOfService API.
Do you have a sample using PointOfService API, and will it work on Windows Phone or other device family?

**Comment by oldnewthing** [comment]
There is a [CashDrawer sample](http://go.microsoft.com/fwlink/p/?LinkId=620015).

**Comment by terry-dai** [comment]
Thank you @oldnewthing , but your sample doesn't work.
I mean I tapped "Initialize Drawer" I got an error saying "Cash drawer not fund. Please connect a cash drawer." Apparently, this sample is not for the cash drawer I have.

Like I said earlier, my cash drawer is connected to an Epson TM-T88V printer. 
The Sample code I got works fine. It is using Epson SDK.
The code is actually sending a pulse command to the printer, and the printer opens the cash drawer.

I was wondering, do you have a sample using your PointOfService API which can open this type of cash drawer (connected to a printer)?

**Comment by oldnewthing** [comment]
I guess I didn't understand your original question. Your original question appeared to be "Is there a PointOfService API for cash drawer?" and the answer is "Check the CashDrawer sample for an example."

Your new question appears to be "The sample doesn't work for my cash drawer." It's not immediately clear to me whether this is a problem with the cash drawer or with the sample, but this is not my area of expertise either. I'll ask the CashDrawer people if they have any ideas.

**Comment by mchen-msft** [comment]
How is your TM-T88V connected?  A Network / Bluetooth TM-T88V should work.

We're working on improving the cash drawer sample, which currently makes the assumption that the cash drawer is already paired with the system.  (You should be able to set up a pairing manually from the "Settings" App, "Devices" category, "Connected devices" tab.)  The sample will be updated to use DeviceWatcher with CashDrawer.GetDeviceSelector() to discover cash drawers on the network + Bluetooth.

If you're writing an app right now, do consider using DeviceWatcher to find the cash drawer + using CashDrawer.FromIdAsync() to open it.

**Comment by terry-dai** [comment]
Thanks @oldnewthing and @mchen-msft 
The printer is connected via network connection, whilst the cash drawer is connected to the printer through something like a phone jack.

Anyway, I'll give the DeviceWatcher a go.
