### ISSUE TITLE
how to run JavaScript code from CodeBehind

### ISSUE THREAD

**Issue by iamstudentVN** [Microsoft/Windows-universal-samples#355]
HI!
my application winform can run javascript code but when i port to uwp, i get error API?
so I do not know how to do :(

**Comment by oldnewthing** [comment]
This is not a question about a specific sample. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account.
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
