### ISSUE TITLE
Specify custom paper size / media size for printing

### ISSUE THREAD

**Issue by moshegutman** [Microsoft/Windows-universal-samples#356]
How do you specify a custom paper size for printing in UWP.

In WinForms this was achieved by setting the [PaperSize](https://msdn.microsoft.com/en-us/library/system.drawing.printing.papersize%28v=vs.110%29.aspx) property in the [PageSettings](https://msdn.microsoft.com/en-us/library/system.drawing.printing.pagesettings.papersize%28v=vs.110%29.aspx) class.

Given the following code, it seems like I can only choose `printTask.Options.MediaSize` from the [PrintMediaSize](https://msdn.microsoft.com/en-us/library/windows/apps/windows.graphics.printing.printmediasize) enumeration.

``` csharp
private void PrintMan_PrintTaskRequested(PrintManager sender, PrintTaskRequestedEventArgs e)
{
    PrintTask printTask = null;
    printTask = e.Request.CreatePrintTask("C# Printing SDK Sample", sourceRequested =>
    {

        PrintTaskOptions printTaskOptions = printTask.Options;

        // There is no way to specify a custom page size??
        printTask.Options.MediaSize = PrintMediaSize.NorthAmericaTabloidExtra;
        printTask.Options.Orientation = PrintOrientation.Portrait;

        sourceRequested.SetSource(printDocumentSource);
    });
}
```

We would like to create PDF files in variety of page sizes.

**Comment by oldnewthing** [comment]
This appears to be a question about the platform, not the sample. You can open a support case with our Developer Support team:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
