### ISSUE TITLE
Definition for 'GetAwaiter'

### ISSUE THREAD

**Issue by yalisme** [Microsoft/Windows-universal-samples#357]
I am not able to run the project _BackgroungTask_. I am getting this error:
**Error CS4036	'IAsyncAction' does not contain a definition for 'GetAwaiter' and no extension method 'GetAwaiter' accepting a first argument of type 'IAsyncAction' could be found (are you missing a using directive for 'System'?**

Any idea how to get rid of it?

**Comment by oldnewthing** [comment]
This means that the NuGet package for .NET failed to install. Try clearing your NuGet cache and rebuilding clean.

**Comment by lindexi** [comment]
`Microsoft.NETCore.UniversalWindowsPlatform`

**Comment by hupo376787** [comment]
Very easy:
using System;

**Comment by lindexi** [comment]
@hupo376787  I find to solve nuget is delete packages.

**Comment by hupo376787** [comment]
@lindexi This problem may diff from one to another project.
