### ISSUE TITLE
x:Bind sample fails to build

### ISSUE THREAD

**Issue by mshindal** [Microsoft/Windows-universal-samples#359]
Hi, when I try to build the [x:Bind sample](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/XamlBind) I get this error:
```
CS0103 The name 'DependencyPropertyChanged_Grid1_Children_5__Visibility' does not exist in the current context
```

**Comment by mshindal** [comment]
This is in the generated `OtherBindings.g.cs`.

**Comment by oldnewthing** [comment]
The binding team has confirmed that this is a bug in the XAML compiler that went out in the 14295 SDK. A fix will be available in the next SDK. Sorry for the inconvenience.

**Comment by SoftwareOnSailboats** [comment]
Anything more on this? Still a problem.

**Comment by oldnewthing** [comment]
I've asked the team for their recommendations.

**Comment by oldnewthing** [comment]
Okay, the story is that pne-way and two-way bindings for indexed parameters do not work in builds prior to 14366. I will remove those scenarios for older builds. Thanks for the report. Fix will appear next Wednesday.

**Comment by SoftwareOnSailboats** [comment]
Thank you for the follow up.
