### ISSUE TITLE
Example for Xbox One Media Remote media control buttons?

### ISSUE THREAD

**Issue by mitchcapper** [Microsoft/Windows-universal-samples#364]
The build talk "Building Great Universal Windows Platform (UWP) Apps for Xbox" highlighted to make sure you handle the media control buttons(play, pause, etc) on the xbox one remote correctly. However it doesn't seem they generate key presses and they do not seem to register on Windows.Gaming.Input either.   Technically a whole example isn't really needed but I can't figure out what API to even start looking at. @pag3 was the one speaking about it.

**Comment by aarononeal** [comment]
There are 2 sets of transport controls.

1. **MediaTransportControls**: These are enabled on `MediaElement` and now `MediaPlayerElement` by setting `AreTransportControlsEnabled=true`. You don't need to handle button presses as that happens automatically. You can see the [VideoPlayback sample](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/VideoPlayback) as an example.

2. **SystemMediaTransportControls**: These controls are seen on some devices when using hardware volume buttons, on the lock screen, etc. These controls are created and drawn by the system and not the app. But, the app is responsible for handling button presses and routing the corresponding commands to the player as it may want to introduce custom logic like disabling skip to the next item. See the [SystemMediaTransportControls sample](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/SystemMediaTransportControls). In the Anniversary Update, app integration with SystemMediaTransportControls will not be required as we have introduced a new MediaPlayer and new CommandManager. Button presses will automatically be routed through the CommandManager and update the MediaPlayer directly just like the standard MediaTransportControls.

Hope that helps. Closing this as it's not a sample issue.

**Comment by mitchcapper** [comment]
@aarononeal 
Sorry I was not clear, I am not sure if it can be re-opened or if I should file new.  In the Build 2016 talks they specifically highlight supporting IR devices like: http://www.xbox.com/en-US/xbox-one/accessories/controllers/media-remote

They said native controls should work with it already (but it doesn't seem to be the case) and custom controls should handle the buttons themselves.  However the 6 media buttons (rewind, play/pause, fast forward, skip back, stop ,skip forward) for example don't generate virtualkey events nor as a registered controller so I am not sure how to access them.

**Comment by mitchcapper** [comment]
The other buttons all generate key press events for the record.

**Comment by aarononeal** [comment]
The media buttons should be routing as presses through SystemMediaTransportControls. What happens when you run the sample?

**Comment by mitchcapper** [comment]
I understand sorry for the confusion, I will hook the event on SystemMediaTransportControls and I am sure that will work.
