### ISSUE TITLE
DEP0001 : Unexpected Error: Install failed. Please contact your software vendor. (Exception from HRESULT: 0x80073CF9)

### ISSUE THREAD

**Issue by bagofmice** [Microsoft/Windows-universal-samples#365]
This will happen if an application registry gets stuck on your physical device. Even if you check uninstall/reinstall on the debug pane of the project properties, the message can still occur when using a physical device. To work around this issue, go to the appxmanifest for your project and change the guid. Your device will have some old cruft left on it, but you can now continue to develop and deploy to your device. Hopefully people searching for DEP0001 : Unexpected Error: Install failed. Please contact your software vendor. (Exception from HRESULT: 0x80073CF9) can find this post and use the workaround.

**Comment by wheezerjoe** [comment]
I am having this problem.  I tried changing the GUID, installed and uninstalled several times, restarted phone, restarted PC,  and still get the same error.  Any other ideas out there?
