### ISSUE TITLE
StreamSocket listener

### ISSUE THREAD

**Issue by ThanawutZiios** [Microsoft/Windows-universal-samples#367]
Hi,

I try to create UWP app on javascript that received third party application that will send data via Web Socket 
So I download sample on StreamSocket ( https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/StreamSocket )
The project is work as it should be create a Listener , connect and send data.
however if I move the code that connect and send data to another project and run 2 project , one to be a listener and another project to send data , the one that do send data is throw exception that cannot connect to server. not sure what I did wrong there.

Thank you,
Thanawut

**Comment by oldnewthing** [comment]
The issue you are running into is not about a sample that is not working. As you noted, the sample itself works fine. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
