### ISSUE TITLE
Question about Geolocator.StatusChanged

### ISSUE THREAD

**Issue by kshalnev** [Microsoft/Windows-universal-samples#368]
Hello.
When I subscribe to a Geolocator.StatusChanged event sink, does Geolocator calls back immediately first event with the current status or I need to get actual status through a Geolocator.LocationState property right after subscription on the callback? 
And the same for PositionChanged - does Geolocator calls back immediately after subscription and when location is available?
Thanks.

**Comment by oldnewthing** [comment]
The issue you are running into is not about a sample that is not working. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.

(Though personally, I would explicitly query the status and position. It doesn't hurt and it avoids taking a dependency on implementation.)
