### ISSUE TITLE
Gsm, Telephony sample

### ISSUE THREAD

**Issue by kshalnev** [Microsoft/Windows-universal-samples#369]
Hello
Is there any API to get a telephony info like operator name, network type, signal strength, cell id? 
Thanks.

**Comment by oldnewthing** [comment]
This isn't a question about a sample. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
