### ISSUE TITLE
Current WiFi connection params: SSID, BSSID, RSSI

### ISSUE THREAD

**Issue by kshalnev** [Microsoft/Windows-universal-samples#374]
Hello.
Is it possible to obtain WiFi connection params for the current connection? 
Sample "WiFiScan" shows only how to use ConnectionProfile.ProfileName by the WiFiAdapter. 
As I found, it is easy to get SSID (ConnectionProfile.WlanConnectionProfileDetails.GetConnectedSsid) and number of signal bars (ConnectionProfile.GetSignalBars),
but how to get BSSID and RSSI for the current connection (better is the same data as in WiFiAvailableNetwork class)?
Thanks!

**Comment by cd66312** [comment]
https://msdn.microsoft.com/en-us/library/windows/apps/windows.devices.wifi.wifiavailablenetwork.aspx

**Comment by oldnewthing** [comment]
This isn't really a question about a sample, but rather a question about the API. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
