### ISSUE TITLE
CustomMediaTransportControls Uri has no content

### ISSUE THREAD

**Issue by tstringer** [Microsoft/Windows-universal-samples#375]
It appears as though the Uri in `MainPage.xaml.cs` for the CustomMediaTransportControls solution doesn't have any content when navigated to through either the sample app or the web browser.

[Link the the line of source utilizing this Uri](https://github.com/Microsoft/Windows-universal-samples/blob/master/Samples/XamlCustomMediaTransportControls/cs/MainPage.xaml.cs#L30)

**Comment by aarononeal** [comment]
Thank you for reporting this. I've updated the link for the next refresh.
