### ISSUE TITLE
SystemMediaTransportControls example doesn't seem to work

### ISSUE THREAD

**Issue by mitchcapper** [Microsoft/Windows-universal-samples#376]
I ran the sample in Win10 desktop (surface pro with play/cause on keyboard and volume controls) and on an xbox.  both running build 14295.  I played a file on both, and then hit the play/pause on the surface, or any of the 6 media control buttons on the media remote on the xbox and nothing fired (I added a Debug.WriteLine to the start of systemMediaControls_ButtonPressed and systemMediaControls_PropertyChanged).

On the xbox its hard to get to the file picker button (using the dpad and controls was able to do so however).   Also I hardwired in a sample file rather than using the picker.

In my own app I wasn't able to get the events to fire either.

**Comment by aarononeal** [comment]
Sorry to hear you're having trouble with that sample. We'll take a look tomorrow and get back to you.

**Comment by aarononeal** [comment]
You might also try the BackgroundAudio sample in the meantime which uses SystemMediaTransportControls as well. 14295 is a preview build and not feature complete, so to set expectations, you may need to revert to a release build or wait for the next flight update.

**Comment by mitchcapper** [comment]
@aarononeal  alright figured it out.
It is 100% a 14295 issue, works fine on older builds.

A workaround for 14295 is also possible:
The problem is caused by setting
`systemMediaControls.IsEnabled = false;`
and then setting (or adding handlers) for any of the following:
```
Attaching to: AutoRepeatModeChangeRequested,PlaybackPositionChangeRequested,PlaybackRateChangeRequested
or touching properties like IsPauseEnabled, IsPlayEnabled, etc.
```
Ironically you can attach to certain events (like button pressed) without issue.  I figured maybe attaching to them after enabling the control would fix it, it does not.
The work around is fairly simple, before touching/attaching to those events set IsEnabled=true,  do your work then set it back to false.  This resolves it.

Have not tested on an xbox but assuming it will resolve there too.

**Comment by mitchcapper** [comment]
Also, both on 14295 and 10586 don't seem to actually do anything with timeline information (I don't see a seek bar?) maybe it only responds to rewind/ff controls although I don't know the ID code to simulate those button presses, or maybe it is reserved for future use.

**Comment by aarononeal** [comment]
Thank you! I've just finished testing a recent build and it reproduces there as well. Looks like you've found a good platform regression for us to fix. I'll pass this info along to the team so we can get it corrected in a future flight. 

Regarding timeline properties, we don't currently display it in the system control but it may show on Bluetooth devices and we may update OS controls in the future.
