### ISSUE TITLE
Geolocation Provider

### ISSUE THREAD

**Issue by reneherrero** [Microsoft/Windows-universal-samples#379]
Hi,

Is it possible do develop a custom "Geolocation Provider" (or Location Sensor)?  By that I mean I'm looking for a mechanism to feed data from an external source to the UWP Geolocator.

I'm seeing a "Microsoft Visual Studio Location Simulator Sensor" in my Device Manager, so I'm tempted to think this is possible.

Please forgive if the question hasn't been addressed in the appropriate forum.  Just can't seem to find the right search term for this one. :)

Thanks,

Rene

**Comment by oldnewthing** [comment]
Driver samples are not kept in this repo. You can find [a sample location sensor provider on MSDN](https://msdn.microsoft.com/en-us/library/windows/hardware/hh768273(v=vs.85).aspx). There is also [an entire repo for driver samples](https://github.com/Microsoft/Windows-driver-samples/).
