### ISSUE TITLE
serial device not working on windows 10 phone (Lumia 930, latest winver)

### ISSUE THREAD

**Issue by web-eagle** [Microsoft/Windows-universal-samples#383]
I tested Custom Serial Device access on my Win10 - pc with no issue -recognized external serial device.
Then I compiled the project to my phone and started - start ok, but no device (even when connected over the hub).
Then I took the device off the hub and connected the serial device with an OTG-cable directly to the phone and restarted the app. No devices are recognized.
Any ideas?
Thanks and best regards
Axel

**Comment by oldnewthing** [comment]
Let us know if this is still an active issue.
