### ISSUE TITLE
Landscape orientations

### ISSUE THREAD

**Issue by NorDroN** [Microsoft/Windows-universal-samples#385]
I want my UWP app to support only Landscape orientations, but I have the same problem https://social.msdn.microsoft.com/Forums/windowsapps/en-US/920c9373-a471-4773-a482-0cf19dea6ad1/uwp-orientation-lock-not-working-for-a-uwp-app-on-a-tablet?forum=wpdevelop

I've tried to run this sample ( DisplayOrientation - https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/DisplayOrientation ) on two devices - phone and tablet.
It works fine on phone, but it absolutely doesn't work on tablet.

**Comment by oldnewthing** [comment]
On PC, orientation preferences are respected in tablet mode when the app is the only one on the screen. It doesn't make sense to enforce orientation preferences when there are multiple apps on the screen, because each app may have a different preference.

**Comment by NorDroN** [comment]
I've already run my app on my tablet in 'Tablet Mode'. It doesn't work either. Also, I've tried to run my app in 'Kiosk Mode (Assigned Access mode)' - I've got the same result :( It doesn't work.

**Comment by ringoz** [comment]
Yep, it doesn't work.
Just checked on Surface Pro 3, Windows v1607

**Comment by oldnewthing** [comment]
I just tried it on my Surface 3 and v1703.
