### ISSUE TITLE
Dependency Properties: RegisterReadOnly gone

### ISSUE THREAD

**Issue by reneherrero** [Microsoft/Windows-universal-samples#386]
Hi,

How do we implement read-only dependency properties in UWP?

WPF has DependencyProperty.RegisterReadOnly, but that doesn't seem to be available in UWP.

Any workarounds?

Thanks

**Comment by oldnewthing** [comment]
This is not a question about a sample. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.

**Comment by reneherrero** [comment]
Understood.

I asked because I saw a reference to a read only property called HasLabelValue in this article https://msdn.microsoft.com/en-us/windows/uwp/xaml-platform/custom-dependency-properties

The article is aimed at UWP, but the reference at the bottom of the page points to WP8 code...

Thanks anyways,
