### ISSUE TITLE
Converted Analog Camera not detected in CameraGetPreviewFrame and other Camera samples

### ISSUE THREAD

**Issue by BarendDS** [Microsoft/Windows-universal-samples#387]
Hi there,

I would like to use the samples to show input from an Analog camera which is converted via an ION Audio VIDEO 2 PC MKII Digital Video Converter. For some reason this camera is not detected in any of the camera samples while freeware software can detect this camera and output it in a correct way.
The device is listed in Sound, Video and Game Controllers...
Is there an DeviceCapability that I need to add in the appxmanifest or is what I ask just not possible in UWP Apps?

Any help would be greatly appreciated.
Tx in advance.

**Comment by mike-mo** [comment]
This is something that the driver manufacturer needs to implement.
