### ISSUE TITLE
Task could not find "winmdexp.exe" using the SdkToolsPath "" or the registry key

### ISSUE THREAD

**Issue by elbonito** [Microsoft/Windows-universal-samples#393]
trying to run the voice command example, but get this error when trying to build and deploy

Task could not find "winmdexp.exe" using the SdkToolsPath "" or the registry key "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\NETFXSDK\4.6.1\WinSDK-NetFx40Tools-x86". Make sure the SdkToolsPath is set and the tool exists in the correct processor specific location under the SdkToolsPath and that the Microsoft Windows SDK is installed

**Comment by oldnewthing** [comment]
I'm not getting this problem. I'm guessing you didn't you didn't install the NETFX 4.6.1 Tools when you installed Visual Studio.

**Comment by ajain0395** [comment]
same error how to resolve it ?

**Comment by elbonito** [comment]
hi fixed it by downloading and installing
https://www.microsoft.com/en-us/download/details.aspx?id=49978
