### ISSUE TITLE
Speech Recognition issue on desktop

### ISSUE THREAD

**Issue by chungweileong94** [Microsoft/Windows-universal-samples#394]
The Speech Recognition API seems to having problem on desktop, there is no problem with getting the voice input result, but if I immediately trigger the speech recognize again, the app will most probably "stop working", the app didn't crash or something, not error catch...but seems to stuck in the speech recognition popup (the main app window is not focusable)

PS. the API is working fine on mobile

**Comment by oldnewthing** [comment]
The issue you are running into is not about a sample that is not working. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
