### ISSUE TITLE
Html Editor

### ISSUE THREAD

**Issue by kinju4374** [Microsoft/Windows-universal-samples#395]
Do we have any HTML Editor sample? I want to display HTML Content and then allow HTML formatting options such as Bold, Italic and other similar to what current Outlook app of Microsoft offers. And final output as HTML. Is this possible with any control in Windows 10? I checked RichEditBox  but it support RTF format not HTML.

**Comment by aarononeal** [comment]
You're asking to render HTML, allow WYSIWYG editing, and then export the result to HTML.

Consider using a WebView control and one of the many JavaScript middleware libraries for this purpose. 

Here is a list:
https://www.sitepoint.com/10-best-html-wysiwyg-plugins/
