### ISSUE TITLE
XAMLTreeView ItemsSource

### ISSUE THREAD

**Issue by juanpaexpedite** [Microsoft/Windows-universal-samples#397]
I know it is a preliminary version, I would like to know if the TreeView will support hierarchy when assigning the ItemsSource to a ObservableCollection<TreeNode> or a List<TreeNode> because at the moment it fills with the root node but not with the child nodes. (Making use of RootNode.Add it fills the children of course)

And then, I am interested in this feature to apply the following grouping:

```
<CollectionViewSource x:Key="CategoriesSource" x:Name="CategoriesSource" IsSourceGrouped="True" 
                          Source="{Binding Categories}" ItemsPath="Bookmarks"/>
```

and then:

```
 <tvs:TreeView  x:Name="PersonalTreeView" ItemsSource="{x:Bind CategoriesSource.View}"  IsItemClickEnabled="True" SelectionMode="None">
```

Of course the Bookmarks are not typeof TreeNode, but will be implemented all the logic to support this way of binding soon?

Thank you for the effort.

**Comment by zaalors** [comment]
I think this is the same "bug" as above. I would like to use TreeView using MVVM pattern.
I made to your code the following simple changes.

1/ I added a ViewModel/MainViewModel.cs file to the TreeView C# project;

2/ I added to MainPage.xaml, the following code:

a/ in the header:
xmlns:ViewModel="using:SDKTemplate.ViewModel"

b/ Then below:
    <Page.DataContext>
        <ViewModel:MainViewModel/>
    </Page.DataContext>

3/ I replaced in this same file:
<tvs:TreeView x:Name="sampleTreeView" 
with:
<tvs:TreeView ItemsSource="{Binding RootNode}"

4/ I copied the content of MainPage.xaml.cs to ViewModel/MainViewModel.cs (with light changes) and commented the original (coming back to the default version, i.e. a constructor with this.InitializeComponent() and that's all).

5/ When I ran, I had only the first level of the hierarchy of the tree.

Question:
Am I wrong somewhere, or is there a little bug to correct?
Many thanks.

-------------------
The code of the view model:

using TreeViewControl;

namespace SDKTemplate.ViewModel
{
    public class MainViewModel 
    {
        public TreeNode RootNode { get; set; }

        public MainViewModel()
        {
            RootNode = new TreeNode();

            init();
        }
        
        private void init()
        {
            TreeNode workFolder = CreateFolderNode("Work Documents");
            RootNode.Add(workFolder);

            TreeNode personalFolder = CreateFolderNode("Personal Documents");
            RootNode.Add(personalFolder);

            personalFolder.IsExpanded = true;
            TreeNode remodelFolder = CreateFolderNode("Home Remodel");
            personalFolder.Add(remodelFolder);

            workFolder.Add(CreateFileNode("Feature Functional Spec"));
            workFolder.Add(CreateFileNode("Feature Schedule"));
            workFolder.Add(CreateFileNode("Overall Project Plan"));
            workFolder.Add(CreateFileNode("Feature Resource allocation"));

            remodelFolder.IsExpanded = true;
            remodelFolder.Add(CreateFileNode("Contactor Contact Information"));
            remodelFolder.Add(CreateFileNode("Paint Color Scheme"));
            remodelFolder.Add(CreateFileNode("Flooring woodgrain types"));
            remodelFolder.Add(CreateFileNode("Kitchen cabinet styles"));

            //ContainerContentChanging += SampleTreeView_ContainerContentChanging;
        }

        private static TreeNode CreateFileNode(string name)
        {
            return new TreeNode() { Data = new FileSystemData(name) };
        }

        private static TreeNode CreateFolderNode(string name)
        {
            return new TreeNode() { Data = new FileSystemData(name) { IsFolder = true } };
        }
    }
}

**Comment by juanpaexpedite** [comment]
I have read the whole code about TreeView and it uses internally ItemsSource to generate the nodes of the TreeView, so is not possible to use in that way at the moment.

**Comment by oldnewthing** [comment]
TreeView is on track to being [a standard control](https://github.com/Microsoft/Windows-universal-samples/tree/v6.0.2). Feature requests should go to the product team, not the samples repo.
