### ISSUE TITLE
Please stop encouraging the hamburger button in samples

### ISSUE THREAD

**Issue by mcosmin222** [Microsoft/Windows-universal-samples#398]
All the samples are using hamburger buttons for navigation. This evil button has been plaguing user interactions in windows 10 ever since Microsoft seems to have a teenager girlish crush on it. The button is not suitable for almost none of the examples shown here, and worse, you are encouraging it to be used in the top left corner of the screen, which is hard to access for anyone who is not left handed (that is close to 90% of the world population).

Worst, you encourage it on a freeking desktop application, which should have plenty of room for full blown navigation elements, visible all the time. 

It is OK to have it as "just one more navigation element when it makes sense", but tossing it in the face on inexperienced mobile developers only makes the problem worse.

**Comment by oldnewthing** [comment]
This doesn't appear to be a bug report.
