### ISSUE TITLE
FilePickerContracts. UI Events not firing

### ISSUE THREAD

**Issue by Lazzarus** [Microsoft/Windows-universal-samples#399]
FilePickerContracts sample. 

Click events don't fire within the file picker contract view

To Reproduce 

Click -> PickFile 
Select File Picker Contracts C# Sample as the source/location
Click any option in the list box. OnScenarioSelectionChanged does not fire.

I've also dropped a button on the page  <Button Content="Test" Click="Button_Click"/> and added a breakpoint to the Button_Click method. Its never hit.

This effect both load and save contract dialogs and also my own project.

**Comment by JimGaleForce** [comment]
Hi Lazzarus, 

You can add 
Window.Current.CoreWindow.IsInputEnabled = true;
to the internal void Activate(...) method of the FileSavePicker.xaml.cs (and others) to allow input.

@oldnewthing please assign issue to appropriate team to fix this.

Thanks,

**Comment by sidwarkd** [comment]
Thanks @JimGaleForce for finding this. Another issue I noticed is that with Jim's fix if you choose the "Fail to save a file" option and hit save you see the expected dialog box but after clicking ok the input capture has been lost again. I fixed this by adding the same line of code Jim mentioned after the error dialog is displayed.

**Comment by sidwarkd** [comment]
After some additional testing I also found that if the FilePicker dialog loses focus it also loses the ability to capture input when you come back to it.

**Comment by JimGaleForce** [comment]
@sidwarkd I wonder if that magic line needs to be placed in a GotFocus event handler.

**Comment by sidwarkd** [comment]
@JimGaleForce Funny you mention that because it's exactly what I tried. It worked but there was still just a little bit of quirkiness in that if you switch apps and come back the initial click restores the capture and then you have to click again on an item. Seems like the way the system FilePicker handles the hosted window might be a little weird.

**Comment by Lazzarus** [comment]
Thanks @JimGaleForce. This does appear to solve the issue but I do see the issue @sidwarkd  mentions where switching windows/apps causes the inputs to disable again.

I can work around this by adding 

 Window.Current.Activated += Current_Activated;

and

private void Current_Activated(object sender, Windows.UI.Core.WindowActivatedEventArgs e)
{
Window.Current.CoreWindow.IsInputEnabled = true;
}

**Comment by sidwarkd** [comment]
Nice work @Lazzarus !  Personally I consider this a bug to have to manage the window this much. Seems like the input should be enabled by default.

**Comment by oldnewthing** [comment]
The feature team informs me that they addressed this issue in the Creators Update. Let us know if this issue is still occurring.
