### ISSUE TITLE
Application crashes because of exception 0x80050022

### ISSUE THREAD

**Issue by KalitaAlexey** [Microsoft/Windows-universal-samples#4]
Project: speechandtts
Phone: Lumia 920
OS version: 10.0.12534.56
Exception 0x80050022 occurred on creating SpeechRecognizer.
Also there is no prompt to request permissions.

**Comment by AdamBraden** [comment]
All the samples have been refreshed and updated to match the VS2015 RC announced at //build
Please update your VS and sync your repository to pick up the changes.

**Comment by AdamBraden** [comment]
I see you are on phone, there is not a new phone flight just yet.  you'll need to wait a little longer until that flight is available.
