### ISSUE TITLE
BackgroundAudio. Get access to background task.

### ISSUE THREAD

**Issue by zeusapps** [Microsoft/Windows-universal-samples#400]
Application failed to get access to background audio task when it's closed by user and then restarted from media transport control or from the tile when run of phone.

Besides what about code style? It will be nice to get some separation with UI logic.

**Comment by aarononeal** [comment]
Can you elaborate on what you mean by "failed to get access"? Are you seeing an exception?

On coding style and UI separation, please see our new sample in the dev branch which uses MVVM:
https://github.com/Microsoft/Windows-universal-samples/tree/dev/Samples/BackgroundMediaPlayback

**Comment by zeusapps** [comment]
Yes, actually I've got an exception "Background Audio Task didn't start in expected time" [here](https://github.com/Microsoft/Windows-universal-samples/blob/master/Samples/BackgroundAudio/cs/BackgroundAudio/Scenario1.xaml.cs#L577).

To reproduce:
1. Start the app on phone emulator or device.
2. Start the playback.
3. Manually close the app, background task will still run.
4. Restart the app from system media transport control or tile.
5. Start playback.
6. UI will block, and then exception will fire.

With "failed to get access" I meant the app does not get collaboration with already running background audio process. 

Thanks. New samples look more elegant. They use new API. Do they get back compatibility?

**Comment by aarononeal** [comment]
Thank you for the report! 

Regarding back compatibility, the new approach only works on the Anniversary Update and forward. However, you can create a hybrid application that continues to use the legacy dual process approach on older versions of Windows if needed.

**Comment by zeusapps** [comment]
There is yet another issue. When app and background process are running and press on MediaTransportControl then the background process will be stopped.

By the way in my case I have resolved previously mentioned issue.

**Comment by aarononeal** [comment]
I don't get the exception reported above, but I do see the play button on the custom controls appear to be unresponsive when the foreground app is restarted.

I was not able to reproduce this second issue that you reported. Relaunching the app from the MTC brought the app to the foreground and audio continued to play in the background.

**Comment by zeusapps** [comment]
Yes, play button become unresponsive because of exception described above.

Sorry, i don't mentioned that second issue took place on PC, on WP everything is ok.
To reproduce:
Launch the app on pc;
Start playback;
Open MTC;
Press on singer/song to launch the app;
Playback will be interrupted.

**Comment by aarononeal** [comment]
Thank you for reporting. We believe these were addressed with the Anniversary Update. Please let us know if not.
