### ISSUE TITLE
IsScreenCaptureEnabled

### ISSUE THREAD

**Issue by GregorSpagnolo** [Microsoft/Windows-universal-samples#401]
I created clean project and I tried to put 
`Windows.UI.ViewManagement.ApplicationView.GetForCurrentView().IsScreenCaptureEnabled = false;`
inside Loaded callback of the MainPage and overridden OnNavigatedTo callback. Doing that "freezes" the application and only the splash screen is shown.  

I looked inside project [DisablingScreenCapture](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/DisablingScreenCapture) but if I put same functionally inside MainPage OnNavigatedTo I get the same freeze result. 

@oldnewthing any idea how to fix this? I need to disable screen capture on an application level.

**Comment by viktorot** [comment]
I have the exact same issue.

I've managed to get it working by starting a timer in the `OnNavigatedTo `callback and setting the property to false after 5s. But that solution is far from ideal.

 Any help would be appreciated.

**Comment by oldnewthing** [comment]
The issue you are running into is not about a sample that is not working. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
