### ISSUE TITLE
XamlMasterDetail transition sometimes not running in DetailContentPresenter

### ISSUE THREAD

**Issue by ericdes** [microsoft/Windows-universal-samples#402]
Hi, 

After creating a C# project similar to the sample XamlMasterDetail I found that the DetailContentPresenter was sometimes (and erratically) not running the ContentTransition's EntranceThemeTransition.

I spent hours to find that if the content contains few controls and / or controls not displaying much text, your sample was also failing in the same way.

Try this:
- Comment out the last control in the DetailContentTemplate:

> ```
>             
> ```

Run the sample, and see that the content transition won't run the entrance transition from time to time.

Even further:
- In the ItemsDataSource replace all titles "Item x" with only "x". Run the samples and see that every 3 or 4 item selections the transition will fail to run.

????

**Comment by oldnewthing** [comment]
I've asked the feature team to investigate.

**Comment by oldnewthing** [comment]
The feature team has decided not to fix this issue.
