### ISSUE TITLE
MediaPlayer works minimized but Audiograph does not

### ISSUE THREAD

**Issue by juanpaexpedite** [Microsoft/Windows-universal-samples#403]
I have been using as source for a project the example BackgroundMediaPlayback that uses MediaPlayer in the Scenario1, I have extracted and tested in another project and works minimized but if I replace all about MediaPlayer and I use Audiograph API when I minimize it stops the sound.

It would be great an example in the AudioCreation project with that feature (keep playing Audiograph when minimized or locked), because I cannot achieve that. 

Might be there is another entry required in the capabilities but there is no documentation or example with Audiograph.

Thank you

**Comment by aarononeal** [comment]
This is by design on Windows prior to the Anniversary Update. For the Anniversary Update, this is supported. Please see the BackgroundMediaPlayback sample in the dev branch and the accompanying readme.

**Comment by juanpaexpedite** [comment]
Well that's the version I am using in my computer 14352 rs1 and I thought that using the 14332 SDK was enough to try this functionality with Audiograph. I hope it arrives soon. Thank you

**Comment by aarononeal** [comment]
Sorry, I read that first one too quickly. Let me follow up and get back to you.

**Comment by aarononeal** [comment]
I think the problem might be that if you replaced `MediaPlayer` with `AudioGraph` then the sample will have no implementation of `SystemMediaTransportControls`. This is required for background audio. `MediaPlayer` has a built-in implementation through `MediaPlayer.CommandManager`. See our SystemMediaTransportControls sample for how to implement that, but essentially, you need to enable at minimum the Play and Pause buttons and handle those ButtonPressed events. Please let me know if that works for you.

**Comment by juanpaexpedite** [comment]
Really interesting information, I will take a look and tell, and as always thank you for the patience

**Comment by juanpaexpedite** [comment]
Thank you really a lot, I instance a SystemMediaTransportControls like the example I followed how it is initialized and now when I minimize and even lock the computer the audio still playing like magic. Now I can continue with my app. 

I hope it also works in Mobile because I only have a 1320 and I cannot test that, 

Anyway this can be closed, again thank you for the clue.

**Comment by aarononeal** [comment]
Glad that worked and thanks for letting me know! Yes, this should also work fine on mobile.
