### ISSUE TITLE
AssociationLaunching sample unable to open with Launcher

### ISSUE THREAD

**Issue by FreddyPulikottil** [Microsoft/Windows-universal-samples#406]
The association launching sample is unable to open a pdf file ( image and office files open fine though) on phone(works well on desktop and rt ). It always throws an exception when running without the debugger attached, with the debugger attached it works just fine. Apps that were used to open the files are Adobe Acrobat Reader and Microsoft Edge.
Steps to reproduce : 
1. From the "Launching a file" page click on the "pick and launch" button
2. Select a file from the file picker and click ok.
App shows "File launch failed". This occurs even when the file is not already open in any other app.

**Comment by oldnewthing** [comment]
Phone is no longer under active development.
