### ISSUE TITLE
Audio Category always set to 6 (AudioCategory_GameEffects) when using AudioGraph class

### ISSUE THREAD

**Issue by JPLaude** [Microsoft/Windows-universal-samples#408]
Hi,

I was looking into AudioCreation and AudioCategory samples and I saw a different behavior of both classes (AudioGraph and MediaElement) when trying to set AudioCategory properties of the stream played.
In fact when using ETW on Microsoft_Windows_Audio provider, you can check which 'category' audio engine is using:
GetMixFormat starting on endpoint [{0.0.0.00000000}.{1764586d-288d-48ae-96bd-6929ae98598d}] (**category=6**, raw=False, matchformat=False, connector=0)

When using AudioCreation->File Playback, we can see in code that 'Media' category is used:
            AudioGraphSettings settings = new AudioGraphSettings(AudioRenderCategory.Media);

But in ETW log you see that audio engine selects 'category = 6' which means AudioCategory_GameEffects (from https://msdn.microsoft.com/en-us/library/windows/desktop/hh404178(v=vs.85).aspx). I tried to change audiocategory to any of possible value, I always see in ETW value 6.

When using AudioCategory sample, you can see that 'category' field in ETW log is following the audiocategory set in the Application (I verified each value, it always match)

Is there any parameter missing in AudioGraph use to let Audio Engine to select correct category ?

**Comment by aarononeal** [comment]
Thank you for reporting this. You've just found a platform bug. The value isn't being passed down correctly from AudioGraph into XAudio. We're opening an internal bug to track, and as this isn't an issue with the sample itself, I'll close this report. Unfortunately, there's not a good workaround I can offer at this time, but thank you for letting us know so we can get it addressed.

**Comment by JPLaude** [comment]
I understand, do you have an idea when this will get fixed ? Or any tracking number that allows me to know when this will be fixed ?

**Comment by aarononeal** [comment]
I currently expect this to be fixed for the Anniversary Update.
