### ISSUE TITLE
An exception of type 'System.IO.FileNotFoundException' occurred in mscorlib.ni.dll 

### ISSUE THREAD

**Issue by paulaenterpriseappsuk** [Microsoft/Windows-universal-samples#409]
Hi, 
When I try to implement ContactPicker or Run the Sample Code for Contact Picker given in your repo,
i get the following error:
"An exception of type 'System.IO.FileNotFoundException' occurred in mscorlib.ni.dll "
this happens on this line of code:
`selectedContact = await contactPicker.PickContactsAsync();`

**Comment by oldnewthing** [comment]
This is an old issue. Does it still occur? None of us can reproduce it.
