### ISSUE TITLE
Windows-universal-samples/Samples/XamlMasterDetail/cs/ can't support mode TwoWay ?

### ISSUE THREAD

**Issue by Adaok** [Microsoft/Windows-universal-samples#412]
Hey people !

I'm inspiring the XamlMasterDetails sample for an app, and I have a textbox with a Command bar in my Details. On the MasterDetailsView, binding for Content Presenter seems not working.

I have pass the Content in mode TwoWay and also the textbox and the command in CommandBar. But no binding works.

Content Presenter don't support binding in TwoWay Mode ?

Someone also have this problem ?

**Comment by JasterAtMicrosoft** [comment]
Hi @Adaok,

Thanks for getting in touch! It's hard to tell exactly what's going on based on your description. Could you please provide a code snippet or a small project that demonstrates the issue?

Thanks,
Jake

**Comment by Adaok** [comment]
Hey @JasterAtMicrosoft ! Sorry for this big late !

Here I give you an exemple at this link : [https://codeshare.io/7Aan7](https://codeshare.io/7Aan7
)

In this example, if I pass the Mode in TwoWay for the ContentPresenter, the binding doesn't work and my buttons don't make any action.

I have found a way to cheat but I don't find it clean.

Thanks,
