### ISSUE TITLE
Background media playback not working with streams

### ISSUE THREAD

**Issue by jmvillagra** [Microsoft/Windows-universal-samples#414]
Hi there, 
we have configured our app to use the new backgroundmediaplayback capability and we can't get it working. 
We installed the latest build & sdk, added the required namespace/capabilities, reconfigured the project to use the target/minimum version to 14366 and it doesn't work... the video streams stop when the app gets minimized / suspended.

<Package
  xmlns="http://schemas.microsoft.com/appx/manifest/foundation/windows10"
  xmlns:mp="http://schemas.microsoft.com/appx/2014/phone/manifest"
  xmlns:uap="http://schemas.microsoft.com/appx/manifest/uap/windows10"
  xmlns:uap3="http://schemas.microsoft.com/appx/manifest/uap/windows10/3"
  IgnorableNamespaces="uap uap3 mp">

<Capabilities>
<uap3:Capability Name="backgroundMediaPlayback"/>
<Capability Name="internetClient" />
</Capabilities>

We use the Microsoft.PlayerFramework player to play our streams (hls, smooth streaming). Do we need an updated version of it to support the background media playback?

**Comment by juanpaexpedite** [comment]
Apart of using the  <uap3:Capability Name="backgroundMediaPlayback"/> you have to initialize and configure the properties of an instance of SystemMediaTransportControls in your app like in one of the examples of Universal Windows, that is all the information they gave me for Audiograph and I was able to make it work.

**Comment by jmvillagra** [comment]
Gracias Juan ;)
I found the problem looking at the SystemMediaTransportControls example

// Note: one of the prerequisites for an app to be allowed to play audio while in background,  
// is to enable handling Play and Pause ButtonPressed events from SystemMediaTransportControls. 
systemMediaControls.IsPlayEnabled = true; 
systemMediaControls.IsPauseEnabled = true; 
systemMediaControls.IsStopEnabled = true;

**Comment by juanpaexpedite** [comment]
De nada, 
I didn't want to steal the feeling when you minimize and the sound still playing :).

By any chance can you test that on Mobile, because I only have a Lumia 1320 and at the moment I cannot test on mobile.

**Comment by jmvillagra** [comment]
I can't test it neither, I don't have any mobile with the insider preview on it....
