### ISSUE TITLE
Protocol activation not working

### ISSUE THREAD

**Issue by abelgs1987** [Microsoft/Windows-universal-samples#415]
Hello
I'm facing with a problem trying protocol activation in my UWP (simple Hello world). The thing is that when i launch the app through command window ( start myapp: ), the app remains loading without starting but it launches. Besides, launching the app in a normal way it works perfectly. Am I missing some configuration? I don't know what is the problem. I followed this guide https://msdn.microsoft.com/en-us/windows/uwp/xbox-apps/automate-launching-uwp-apps

I would appreciate any advice.

Many thanks

**Comment by oldnewthing** [comment]
The issue you are running into is not about a sample that is not working. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
