### ISSUE TITLE
WebView doesn't have CS example

### ISSUE THREAD

**Issue by jwettstrom** [Microsoft/Windows-universal-samples#416]
The WebView doesn't have a CS or CPP example. Kind of useless to have a JS sample for a WebView control sample. At minimum there should be a CS sample and the JS sample you could leave or throw out, it is useless anyways.

**Comment by JasterAtMicrosoft** [comment]
The sample is here: https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/XamlWebView.
