### ISSUE TITLE
Is this will be available in Anniversary update?

### ISSUE THREAD

**Issue by butamuh4o** [Microsoft/Windows-universal-samples#419]
Hi there,
I was wonder if this example will be work on Anniversary update: https://github.com/Microsoft/Windows-universal-samples/tree/dev/Samples/BackgroundMediaPlayback ? Or if it not- when will be?

I am trying to make a Background Audio only with JS, like this example. But for now that is not possible.

Sorry if i ask a question not for "issues" category.

Thanks all !!!

**Comment by aarononeal** [comment]
Yes, this sample demonstrates features of the Anniversary Update which you can try now through Windows Insider builds.

**Comment by oldnewthing** [comment]
Are you saying that the sample doesn't work? Can you be more specific what doesn't work? I just built and ran the JS version of the BackgroundMediaPlayback sample on build 14373

**Comment by oldnewthing** [comment]
.
