### ISSUE TITLE
XamlPivot/cs/Scenario3.xaml 

### ISSUE THREAD

**Issue by vincegio** [Microsoft/Windows-universal-samples#420]
Unable to cast object of type 'Microsoft.VisualStudio.DesignTools.Markup.DocumentModel.DocumentCompositeNode' to type 'Windows.UI.Xaml.ResourceDictionary'.	(...) Line 119	<--- Where ResourceDictionary in Grid.Resource begins, in the style. Don't know what to do.

**Comment by oldnewthing** [comment]
I cannot reproduce this problem on the master or dev branch.

```
1>------ Build started: Project: Pivot, Configuration: Debug ARM ------
1>  Pivot -> S:\repos\master\Samples\XamlPivot\cs\bin\ARM\Debug\PivotCS.exe
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```

I don't see a Grid.Resource anywhere near line 119 of Scenario3.xaml.

**Comment by vincegio** [comment]
Hi,
I should've been a tad more clear, but this occurs when I add the code to my own app and page. The mentioned line is 33 on the Scenario3.xaml section

**Comment by oldnewthing** [comment]
Okay, so the issue isn't about the sample itself, but rather how to incorporate the sample into your own app. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
