### ISSUE TITLE
Missing sample for CalendarDatePicker

### ISSUE THREAD

**Issue by martinsuchan** [Microsoft/Windows-universal-samples#422]
There is no sample project covering the [CalendarDatePicker ](https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.xaml.controls.calendardatepicker.aspx) control, it should be added at least to the [XamlUIBasics project](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/XamlUIBasics). 

See this page covering [date and time pickers](https://msdn.microsoft.com/windows/uwp/controls-and-patterns/date-and-time).

**Comment by oldnewthing** [comment]
Yup, finally got added, in the May 2017 Update 2.
