### ISSUE TITLE
BluetoothAdvertisement - Turning Bluetooth off and on will break background mode

### ISSUE THREAD

**Issue by EagleEyeBW** [Microsoft/Windows-universal-samples#423]
After installing/starting the sample app and turning the bluetooth off and on no advertisements are received.
Phone: Lumia 535

**Comment by kpathakota** [comment]
Hi @EagleEyeBW  - could you give me more details? Can you verify the BG task is still active? Any other devices in the area picking up advertisements? Is the foreground version of the sample receiving the ADVs but the background is not?

**Comment by EagleEyeBW** [comment]
Hi @kpathakota sure what do you need?
Yes the tasks is still active. Yes other devices are receiving the bluetooth devices.
Yes the foreground still works but the background is broken.

**Comment by kpathakota** [comment]
Using FieldMedic[edit | edit source]
- Install FieldMedic: http://www.windowsphone.com/en-us/store/app/field-medic/73c58570-d5a7-46f8-b1b2-2a90024fc29c
- Start Logging (Bluetooth is selected by default, but good to double check; if the issue involves Media playback or glitching, please also enable Multimedia-verbose logging).
- Repro the issue, including Connection and even Pairing if possible
- Stop Logging.
- Copy etl/zip and attach to the bug. (FieldMedic-Bluetooth.etl is in directory Computer\Windows Phone\Phone\Documents\Field Medic)

**Comment by chandrakantnitt** [comment]
@kpathakota is there an update ? 

In our application the BLE Publisher changes the ManufacturerData every 5 seconds (for privacy reasons). This is then communicated to the target mobile device over RfComm. The mobile device just changes the ManufacturerData (received over RfComm) then stops and starts the BLE Watcher (is there a better way to make the watcher aware that the ManufacturerData has changed ??). Now when bluetooth is turned off and then on again - then BLE Watcher never starts !

Even we tried to warn user by showing the popup that turning off bluetooth will cause the App to not work properly. But subscribing to the StateChanged of Radio will not work if we do it in foreground app. We tried to put this in the background Task (which triggerer ?). We dont see any background task which is alive where we can subscribe this. 
Also Putting a callback timer within some Background task causes the BGTask to be killed by OS.

Can you tell where should we keep the code where we can subscribe for such changes even when the app is in "not running" state [not suspended]

Any help will be highly appreciated.

**Comment by oldnewthing** [comment]
This is not a question about the sample. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
