### ISSUE TITLE
Sample projects looking for SDK version=10.0.14295

### ISSUE THREAD

**Issue by lbreton** [Microsoft/Windows-universal-samples#424]
Hi,
I'm new to Visual Studio so maybe this is a no brainer but when I try to load any of the samples in VS, I get the message that I need to install the platform Windows 10 SDK (UAP, Version=10.0.14295).  I downloaded and unzipped the entire Samples folder.  I'm guessing my VS cannot find the shared contents but don't know how to resolve the issue.  Any help would be great - Thanks!

**Comment by oldnewthing** [comment]
You can install the 14295 SDK, or easier is to [follow these instructions](https://developer.microsoft.com/en-us/windows/downloads/windows-10-developer-preview?OCID=insider) to update the app to the latest SDK.

**Comment by lbreton** [comment]
I don't believe that is the problem - I have the latest SDK installed (10.0.14383).  The Output box indicates it is looking for some shared projects that it cannot find but I don't know if that is the same problem or a second problem...

**Comment by oldnewthing** [comment]
As noted in every README, you have to unzip the entire thing, not just the Samples folder. The samples have references to content in the SharedContent folder.

**Comment by lbreton** [comment]
Yes, I read that and complied so that is not the problem either.  The entire folder is unzipped but it is still apparently looking for the 14295 SDK for some reason while I have the 14383 SDK installed.

**Comment by juanpaexpedite** [comment]
You always can edit the csproj of a project and  change the following:

     <TargetPlatformVersion>10.0.14366.0</TargetPlatformVersion>
    <TargetPlatformMinVersion>10.0.14366.0</TargetPlatformMinVersion>

Or whatever is the sdk you have (you can get the info creating a new UWP project and get the info from the csproj created)

**Comment by oldnewthing** [comment]
If you don't have the 14295 SDK installed, you can edit the csproj file to change the SDK version. Once the Anniversary Edition is released, the version numbers will be updated in all the samples. But we don't do it right now because it would result in the versions being changed constantly.

**Comment by lbreton** [comment]
Thank you both for the suggestion.  I had already tried that as well but will try it again.  When I did that I got a different error but I can't remember what it was.  I will try it again and report back...

**Comment by lbreton** [comment]
OK, that seems to have worked!  My apparent mistake when I tried it before was that I replaced the "10.0.295.0" target in the samples project file platform reference with 10.0.586.212 rather than "10.0.586.0" for my installed SDK.  In other words, I thought the last ".0" should have been ".212" to match the full specification of my SDK.

Thanks a ton!
Leo

**Comment by lbreton** [comment]
So I got past the errors above with your help.  The current issue is that even though I have the build 14388 SDK installed, the referenced "Microsoft.advertising.xaml" file does not seem to have been installed.  I have read on the Microsoft website that there is (or was) a separate advertising SDK that needs (or needed) to be installed but maybe this is no longer the case?  My question is how do I get the "Microsoft.advertising.xaml" and similar files installed on my system?

Thanks again!

**Comment by oldnewthing** [comment]
As noted in the [README](http://go.microsoft.com/fwlink/p/?LinkId=722924):

> This sample requires the [Microsoft Advertising SDK Libraries for XAML or JavaScript](http://go.microsoft.com/fwlink/?LinkID=619694). [Download it here](http://go.microsoft.com/fwlink/p/?LinkId=518026).
