### ISSUE TITLE
BluetoothAdvertising Sample

### ISSUE THREAD

**Issue by lbreton** [Microsoft/Windows-universal-samples#431]
Hi,
I built the BluetoothAdvertising solution and the program seems to run properly, except it does not seem to recognize my Bluetooth USB dongle.  Where does one tell the program which device to use for advertising or what the Bluetooth radio address is?

Thanks!

**Comment by kpathakota** [comment]
Do you have two radios on the system (one internal and one dongle)? This is an unsupported case and you will likely run into inconsistencies. Only way to definitely tell the OS what radio to use is through DeviceManager (Win + x, m). Disable all radios but one and you will know you've got one available. 

Another possibility is the dongle does not support Bluetooth LE (please make sure the dongle supports BT 4.0 or higher for the sample to work).
