### ISSUE TITLE
There is a bug on Slider control with range -100 to 100

### ISSUE THREAD

**Issue by JuniperPhoton** [Microsoft/Windows-universal-samples#432]
Consider the XAML below:
```
<Slider x:Name="TemperatureSlider"
                            Maximum="100"
                            Minimum="-100"
                            Value="0" />
```
The `Maximum` property value is 100 and the `Minimum` property value is -100, and the default value is 0.  In designer, the Slider control looks normal, like this:

![1](https://cloud.githubusercontent.com/assets/7578386/17125980/21d7620c-532b-11e6-82ee-ed836503244b.png)

However, while running the app,  it looks like this:

![2](https://cloud.githubusercontent.com/assets/7578386/17125990/49caa9ae-532b-11e6-9c0f-351714a16fce.png)

Now if I change the `Maximum` property to 99 or 101, the Slider should look right:

![3](https://cloud.githubusercontent.com/assets/7578386/17126005/722fd748-532b-11e6-8806-8b090dfd2baa.png)

Also, in the first case, if I change the `Maximum` property in code behind or in Live Property Explorer, the Slider will update its UI making it be what it should be.

**Comment by oldnewthing** [comment]
The issue you are running into is not about a sample that is not working. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
