### ISSUE TITLE
Problem compiling Alljoyn Consumer Experience

### ISSUE THREAD

**Issue by tbelqdx** [Microsoft/Windows-universal-samples#439]
Hi,
I am trying to use the Alljoyn consumer Experience but when I try to generate It I have 9 Errors of this type:
`C2525 'com::microsoft::Samples::SecureInterface::AlljoynMessageArgStructure::SetAT' : the parameter 'item' is named value on the basic function and there must be a correspondence in the published implementation` 
This error appears for SecureInterface and Onboarding

Did somebody have the same problem? I don't know how to solve it..
Thank You

**Comment by oldnewthing** [comment]
Fixed in v3.0.4, backported to win10-1507 as v1.0.30 and win10-1511 as v2.0.20.
