### ISSUE TITLE
Problems with Windows-universal-samples-master.zip: BackgroundAudio (won't run on Phone) and BackgroundMediaPlayback (won't run)

### ISSUE THREAD

**Issue by ic2ic2** [Microsoft/Windows-universal-samples#443]
I am trying to access mediafiles on a Windows 10 Phone or stored on a W10 PC disk and tried to samples to see how I can get this working. 

1 However, from the Windows-universal-samples-master.zip, BackgroundAudio won't run a Windows Phone 10. On opening the solution I get:

[Failure] Could not find file 'D:\ccodeSamples\W10Universal\Windows-universal-samples-master\Samples\BackgroundAudio\cs\BackgroundAudio\obj\ARM\Debug\App.g.i.cs'.
[Failure] Could not find file 'D:\ccodeSamples\W10Universal\Windows-universal-samples-master\Samples\BackgroundAudio\cs\BackgroundAudio\obj\ARM\Debug\MainPage.g.i.cs'.

Clean +  Rebuild all helps, but trying to deploy it on a connected W10 Phone results in:

EP0001 : Unexpected Error: -2147009287
The parent file, "Scenario1.xaml, for file "Scenario1.xaml.cs", can not be found in the project file
The parent file, "PlaylistView.xaml, for file "Views\PlaylistView.xaml.cs", can not be found in the project file

What is wrong here? Note: the 2 files which "can not be found" are present and editable from VS!

It does start on an emulator however but doesn't show the right part of the app where it all happens...

2 I downloaded the new sample files published this afternoon and see that BackgroundMediaPlayback superseded this sample. This doesn't work either. First, because it relies on the AnniversaryEdition (build 14393) which I don't have yet and second because it starts with an error of a missing file which I think doesn't disappear if I do have 14393: it searches for "C:\Program Files (x86)\Windows Kits\10\bin\10.0.**14366**.0\XamlCompiler\Microsoft.Windows.UI.Xaml.Common.targets" and as my latest VS update did install this file but (logically) in directory 10.0.**14393**.0 and not 10.0._14366_.0).

Finally, it looks like this sample doesn't compile when targeted 10586 (Unknown type MediaplayerElement and The member Medialist is not recognized). Does that mean that 1 I _must_ have W10 Anniversary to use it and also 2) that when I develop an app with W10 Anniversary, it doesn't run on 10586 or 10240? Or does it?

**Comment by aarononeal** [comment]
The first set of errors sound like a tooling problem or old intermediate files left from an earlier compile. I'll try to reproduce, but if I'm unable, you could try a repair install or we'll need to get you in touch with someone through a support channel. Please also check your sample folder and delete any intermediate directories that were created, like `bin` and `obj`, or do a clean check out from the repo.

The sample UI is also not optimized for mobile screens so most likely when you run on the emulator you need to collapse the left pane by clicking the horizontal bars aka "hamburger" icon and then scroll the right pane into view. Alternatively, run the desktop target so you can see what it's supposed to look like and then optimize for your own app to fit mobile screens.

For the new sample, I don't know why it's still targeting a pre-release, but this is easy to fix. For now, just edit the .csproj file and change the version numbers from 14366 to 14393.

But yes, to use the new sample you need the Anniversary Update. As the sample explains, we have simplified the way developers write background audio applications for new versions of Windows. It's now possible to use a single process architecture that doesn't require the communication overhead of the legacy dual process approach as well as a MediaPlayer that can be attached and detached from UI for background applications.

If you want to target older versions of Windows you can continue to do so using the legacy approach or a combination of both.

**Comment by oldnewthing** [comment]
The "Parent file..." messages are just warnings. They are VS telling you that (due to the way the files are shared to conserve space in the repo), it cannot set up the hierarchy perfectly in the Solution Explorer tab. The actual problem is the -2147009287 aka 0x80073cf9 aka ERROR_INSTALL_FAILED.

I will fix the 14366 problems.

You can go to the win10-1511 branch to get a version of the sample that runs on release 1511.

**Comment by oldnewthing** [comment]
The 14366 problems were fixed in v3.0.12.
