### ISSUE TITLE
SimpleInk Sample

### ISSUE THREAD

**Issue by Noemata** [Microsoft/Windows-universal-samples#444]
When attempting to compile the SimpleInk sample, the following VS2015 Update 3 error comes up during compile:

\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v14.0\8.2\Microsoft.Windows.UI.Xaml.Common.targets(264,5): Xaml Internal Error error WMC9999: Object reference not set to an instance of an object.

The 10.0.14393.0 level SDK has been installed.  I have also had to tweak the project file and change TargetPlatformMinVersion from 10.0.14295.0 to 10.0.10586.0.  Why is there a reference to beta release libs in production level samples?

**Comment by Noemata** [comment]
Resolved the above problem.  InkToolbar is available in the 10.0.14295.0 release of the SDK, but since I never had that release installed, the TargetPlatformMinVersion has to be set to 10.0.14393.0 also since the InkToolbar is not available in the 10.0.10586.0 release of the SDK, hence the rather obscure compile time XAML error.

**Comment by oldnewthing** [comment]
All version numbers should now be bumped from 14295+ to 14393. If you find any that I missed, let me know.
