### ISSUE TITLE
AddImageFeedScenario

### ISSUE THREAD

**Issue by olivernovakovic** [Microsoft/Windows-universal-samples#448]
What is the purpose of this ?
Is this working in Windows 10 ?
...
Important  Using a Really Simple Syndication (RSS) feed as a lock screen image source is not supported on Windows 10. The method returns an expected result, but the lock screen slide show does not work due to changes to the RSS feature in Windows 10.

**Comment by oldnewthing** [comment]
Thanks for spotting this. The feature is not available in Windows 10, and the scenario should be removed from the sample. I'll take care of it.
