### ISSUE TITLE
XamlNavigation: The member "HeaderContent" is not recognized or is not accessible.

### ISSUE THREAD

**Issue by Morgy93** [Microsoft/Windows-universal-samples#450]
Hello,

I was about to check the [XamlNavigation](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/XamlNavigation) while I stumbled across some error on the latest sample within Visual Studio 2015 Community:
<img width="520" alt="vssample" src="https://cloud.githubusercontent.com/assets/7961978/17491384/b21da3f4-5da7-11e6-8890-94b3576b0993.PNG">
This error comes from: https://github.com/Microsoft/Windows-universal-samples/blob/master/Samples/XamlNavigation/shared/BasicSubPage.xaml#L41

**Comment by jerrak0s** [comment]
You must extract `SharedContent` as well as the Sample in order to build it.

**Comment by oldnewthing** [comment]
I can't reproduce this problem with either the C# sample or the C++ sample. Did you clone the repo or merely download the zip? If you downloaded the zip, did you extract the whole thing? As @jerrak0s  noted, there are interdependencies within the zip, so you need to extract SharedContent (and depending on the sample, possibly other directories).

**Comment by Morgy93** [comment]
Well, I thought these samples would be more "standalone".
I cloned the whole repo and opened the sample and it works now - thanks for that!

Closed~

**Comment by oldnewthing** [comment]
An earlier version of the repo did use completely standalone samples, but that made the repo nearly a gigabyte in size. Back in early 2015, we reorganized the repo to shrink it down to around 6 megabytes. This was done by sharing resources between samples. The fact that you need to expand the entire zip is called out on the main README as well as on each sample's README.

> ## Build the sample
> 
> 1. If you download the samples ZIP, be sure to unzip the entire archive, not just the folder with the sample you want to build. 
>
