### ISSUE TITLE
xBindSampleCS wont's compile with Anniversary Update SDK

### ISSUE THREAD

**Issue by martinsuchan** [Microsoft/Windows-universal-samples#451]
I'm trying to compile and run the latest version of xBindSampleCS sample, but it won't complile on Windows 10 Anniversary Update, VS2015 Update 3 with UWP SDK v1.4.1.  

> Error     Invalid binding path 'Display('Hello World', 42, 3.147, x:True)' : Function parameter 'floatArg' is invalid or missmatched  xBindSampleCS   C:\Dev.other\Windows-universal-samples\Samples\XamlBind\cs\Functions.xaml   56  

When I remove that line, I got:

> C:\Program Files (x86)\Windows Kits\10\bin\10.0.14393.0\XamlCompiler\Microsoft.Windows.UI.Xaml.Common.targets(347,5): Xaml Internal Error error WMC9999: Object reference not set to an instance of an object.  
> 
> Error     Object reference not set to an instance of an object.   xBindSampleCS           

Edit: When I git-cleaned the solution the project now compiles with only the line 56 commented.

Not sure, if this is an error in the sample, or the final Anniversary Update SDK is missing some x:Bind features that were available in preview SDKs.

**Comment by juanpaexpedite** [comment]
In my case I change in the csproj both target to:

<TargetPlatformVersion>10.0.14393.0</TargetPlatformVersion>
<TargetPlatformMinVersion>10.0.14393.0</TargetPlatformMinVersion>

Might be that solves the issue. In my machine compiles

**Comment by martinsuchan** [comment]
The TargetPlatformVersion and TargetPlatformMinVersion is already set to the Anniversary Update version number.
When I cleaned the project it compiles only with the one line 56 commented. This one line still needs a fix.

**Comment by juanpaexpedite** [comment]
Oh, I have changed it in several projects, so I thought... my fault.  I can upload the Common.targets file if you want to compare with yours.

**Comment by hannespreishuber** [comment]
same here. After opening visual studio UWP Ann App compiles 1 times, and 2nd time I get this error
C:\Program Files (x86)\Windows Kits\10\bin\10.0.14393.0\XamlCompiler\Microsoft.Windows.UI.Xaml.Common.targets(347,5): Xaml Internal Error error WMC9999:

**Comment by oldnewthing** [comment]
Please try again with the Fall Creators Update. If you are still having this problem, reopen.
