### ISSUE TITLE
ComboBox not working with touch & mouse support that within a flyout that attached to AppBarButton

### ISSUE THREAD

**Issue by chungweileong94** [Microsoft/Windows-universal-samples#453]
In Build 14393(Anniversary Update), the **ComboBox** doesn't seems working with touch & mouse support that within a **Flyout** which attached to **AppBarButton**, it won't trigger the **SelectionChanged** event at all, but only trigger by using keyboard arrow key, I already tested on a few difference devices.

**Comment by YuliKl** [comment]
Add AllowFocusOnInteraction="True" to either the AppBarButton or to the ComboBox.

**Comment by chungweileong94** [comment]
Thank You YuliKl,  it does work for me!
I have tried this before, but I put it to **Flyout**, that why it don't work.
