### ISSUE TITLE
CameraFrames sample runs slow and flickers on HoloLens

### ISSUE THREAD

**Issue by nuernber** [Microsoft/Windows-universal-samples#455]
I just tried the [CameraFrames C# project](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/CameraFrames) on HoloLens and it's running slow and flickers. I've tried [CameraGetPreviewFrame](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/CameraGetPreviewFrame) sample on HoloLens and that one runs perfectly fine; it's not slow at all and does not flicker. Is there any idea why this might be happening on the HoloLens? I haven't tried CameraFrames on a laptop yet, just on the HoloLens.

**Comment by fordacious** [comment]
I am the developer currently working on this sample. Thanks for trying out the CameraFrames sample on the HoloLens and thanks for identifying this issue. We really appreciate the feedback from developers. 

We've successfully reproduced your issue and we are working on a fix. Please keep an eye out for any merges to this branch in the near future.
