### ISSUE TITLE
Access & save desktop drives using fileopenpicker or storagefolder.

### ISSUE THREAD

**Issue by sanjeevgaykwad** [Microsoft/Windows-universal-samples#456]
I  want to get all drive .i.e.(c:,d: etc.) of Desktop without fileopenpicker which is manuallly picks items .i.e.file/folder.
  It will work like System.io.DriveInfo.GetDrives().Also.StorageFolder Gets access Denied Error.

**Comment by oldnewthing** [comment]
UWP apps do not get unrestricted access to drives.
