### ISSUE TITLE
XamlCommanding - Scenario8: DynamicCommandBar has infinite loop

### ISSUE THREAD

**Issue by omscarr** [Microsoft/Windows-universal-samples#458]
Viewing Scenario8 (Demonstration of moving commands from primary to secondary group when screen size changes) in windowed mode causes the app to become unresponsive.  

DynamicCommandBar.MeasureOverride(Size availableSize) gets called over and over again and memory usuage slowly climbs.

Viewing the scenario in a maximized window runs ok.

Tested using Visual Studio 2015 on Windows 10 Aniversary on desktop.

**Comment by oldnewthing** [comment]
This is being tracked as issue #250.
