### ISSUE TITLE
Simple Communication: Hololens

### ISSUE THREAD

**Issue by hereswilson** [Microsoft/Windows-universal-samples#460]
The Hololens is not able to transmit its video stream to a receiving windows 10 computer, but is able to receive video stream from a Windows 10 computer.

**Comment by wguyman** [comment]
Hi Wilson, 

Can you describe a little more what you are trying to do and how you are trying to do it? Are you trying to live stream like the "Live Preview" offered by the Web Portal? https://developer.microsoft.com/en-us/windows/holographic/using_the_windows_device_portal#mixed_reality_capture

Thanks,
Will

**Comment by hereswilson** [comment]
I should have closed this. I was able to get it to work. Now I just need to figure how to get the audio from the stream to be able to be heard in a Unity app.
