### ISSUE TITLE
Easy way to understand Samples

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [Microsoft/Windows-universal-samples#466]
I'm just start leanring to develop. Can you explain how to do step-by-step in a ReadMe file of every sample. Thank you!

**Comment by oldnewthing** [comment]
This question is outside the scope of the samples repo. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
