### ISSUE TITLE
WiFi Direct Error in Start Adv

### ISSUE THREAD

**Issue by sujeet14108** [Microsoft/Windows-universal-samples#467]
![error](https://cloud.githubusercontent.com/assets/9781422/17850999/7ee2693a-687d-11e6-98bd-eefb70bf769b.PNG)
![mml](https://cloud.githubusercontent.com/assets/9781422/17851003/7fe102a6-687d-11e6-8296-81be81681160.PNG)

**Comment by oldnewthing** [comment]
As noted in the README, the C++ sample has yet to be updated.

**Comment by Yorchito** [comment]
@sujeet14108 This looks like it was running the previous version of the project. Have you tried running the latest one? Also run "netsh wlan show wirelesscapabilities" to see if your computer supports WiFiDirect

**Comment by oldnewthing** [comment]
As I noted earlier, the C++ version of the sample has not been updated. Use the C# sample in the meantime.
