### ISSUE TITLE
wifi direct service sample error

### ISSUE THREAD

**Issue by mohammadalijj** [Microsoft/Windows-universal-samples#470]
when i debugging C# sample this error disappear

Error		DEP6200 : Bootstrapping failed. Device cannot be found. 0x89731810: Deployment failed because no Windows Phone was detected. Make sure a phone is connected and powered on.

please help.

**Comment by oldnewthing** [comment]
The issue you are running into is not a samples issue. This appears to be a Visual Studio configuration issue. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.

**Comment by mohammadalijj** [comment]
![photo_2016-08-25_00-11-39](https://cloud.githubusercontent.com/assets/13782890/17945308/87106030-6a58-11e6-9acd-771b296cd479.jpg)

**Comment by mohammadalijj** [comment]
Thanks a lot for your answer , but microsoft not answer me because i'm iranian , can you help me ?

**Comment by oldnewthing** [comment]
Sorry, I can't help you either.

**Comment by mohammadalijj** [comment]
My problem is solved. Thank you so much
