### ISSUE TITLE
Crashing App with Unhandled Exception after Rendering Content Dialog with Image

### ISSUE THREAD

**Issue by tjones0808** [Microsoft/Windows-universal-samples#471]
have an ObservableCollection that I fill with BitmapImages. Once filled I open up a content dialog with a listview and item template with the images set as source. Whenever I open the content dialog with the images I get an unhandled exception that I can't debug and can't get the correct error to.

The only message I get is :

Application-internal exception in Windows.UI.Xaml.dll

followed by a Fail Fast Exception that I can't get any good info on.

Any help is greatly appreciated.

    <ContentDialog` x:Name="ControlsDialog" Style="{StaticResource ContentDialogStyle2}" Grid.Row="1"
        VerticalAlignment="Bottom"
        PrimaryButtonText="Begin"           
        IsPrimaryButtonEnabled="True"
        SecondaryButtonText="Close"
        MinWidth="650"
        MinHeight="300"
        MaxWidth="650" Margin="404,0,363,-422" HorizontalAlignment="Stretch" CanDrag="True" d:LayoutOverrides="Width, LeftPosition, RightPosition">
        <ContentDialog.Transitions>
            <TransitionCollection/>
        </ContentDialog.Transitions>

        <ContentDialog.Title>
            <TextBlock  TextAlignment="Center" FontWeight="SemiBold" Text="2nd Screen Controls"/>
        </ContentDialog.Title>

        <StackPanel Margin="5,0,5,20" MinWidth="500" HorizontalAlignment="Center" Orientation="Vertical">
            
            <ToggleSwitch Header="Show Budget vs Deposit" OnContent="Deposit" OffContent="Budget" Toggled="ToggleBudgetDeposit_Toggled" Margin="40,0,0,0" />            

            <StackPanel Margin="0,20,0,0">
                <TextBlock Text="Plan Image Selection" TextAlignment="Left" HorizontalAlignment="Left" Margin="40,0,0,0" />

                <ListView      
                    ItemsSource="{x:Bind ConcreteDataContext.ImageList, Mode=OneWay}"
                    ItemClick="ChangePlanImage_Click"
                    SelectionMode="None"
                    IsItemClickEnabled="True"
                    ScrollViewer.VerticalScrollBarVisibility="Disabled" 
                    ScrollViewer.HorizontalScrollBarVisibility="Auto"
                    ScrollViewer.HorizontalScrollMode="Enabled"                  
                    ScrollViewer.VerticalScrollMode="Disabled" 
                    ItemContainerStyle="{StaticResource SelectionListViewItemStyle}">
                    <ListView.ItemsPanel>
                        <ItemsPanelTemplate>
                            <StackPanel Background="Transparent" Orientation="Horizontal" />
                        </ItemsPanelTemplate>
                    </ListView.ItemsPanel>
                    <ListView.ItemTemplate >
                        <DataTemplate x:DataType="BitmapImage">
                            <StackPanel>
                                <Image MinWidth="100" MinHeight="100" MaxHeight="150" MaxWidth="150" Margin="5,5,25,5" Source="{x:Bind }" />
                            </StackPanel>
                        </DataTemplate>
                    </ListView.ItemTemplate>
                </ListView>
            </StackPanel>
        </StackPanel>
    </ContentDialog>

**Comment by oldnewthing** [comment]
The issue you are running into is not about a specific sample that is not working. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
