### ISSUE TITLE
Launching UWP APP Without display on Taskbar.

### ISSUE THREAD

**Issue by sanjeevgaykwad** [Microsoft/Windows-universal-samples#473]
Hello Sir,

   I have functionality which is to be done before UWP App Launch.When I use UWP App is Launched on Taskbar, or  is there a way to hide UWP App on Taskbar on Windows 10? I have used Background Activity but it only work Method in Backround Not UWP App.

**Comment by oldnewthing** [comment]
This is a question about the platform, not about a sample. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
