### ISSUE TITLE
Media Player add effect sample

### ISSUE THREAD

**Issue by mcosmin222** [Microsoft/Windows-universal-samples#475]
It would be great if we had a sample demonstrating the usage of MediaPlayer.AddAudioEffect method.

**Comment by aarononeal** [comment]
Thanks for the feedback. We're tracking this internally.

In the meantime, the AudioCreation sample shows how to use effects with AudioGraph and the process is similar.

https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/AudioCreation
