### ISSUE TITLE
Accept VOIP call

### ISSUE THREAD

**Issue by JurajPupak** [Microsoft/Windows-universal-samples#479]
How can I detect, that app is launched from system call screen? I'm programming voip app. I know how to create call etc. If I press Accept on system screen, OnLaunched method is invoked. How can I detect this scenario?

**Comment by oldnewthing** [comment]
This appears to be a question about how to design your application, not a question about a sample. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
