### ISSUE TITLE
FullScreenSample as a Screensaver

### ISSUE THREAD

**Issue by vindberg** [Microsoft/Windows-universal-samples#481]
Hi @oldnewthing, is there a way to turn the fullscreen sample into a screensaver that are installed automatically from the App store?

I just want to create a simple screensaver.

Thanks.

**Comment by oldnewthing** [comment]
The issue you are running into is not about a problem with a sample. You can open a support case with our Developer Support team who can further help with your specific question. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
