### ISSUE TITLE
Altimeter.getDefault() returns an instance even if is no supported

### ISSUE THREAD

**Issue by OrbintSoft** [Microsoft/Windows-universal-samples#483]
Altimeter.getDefault() should returns null if the sensor is no supported.
Bug reproduced on lumia 930 and on PC with windows 10.
https://msdn.microsoft.com/en-us/library/windows/apps/windows.devices.sensors.altimeter.getdefault.aspx?cs-save-lang=1&cs-lang=csharp#code-snippet-1

**Comment by oldnewthing** [comment]
It sounds like you're reporting a platform bug rather than a bug in the sample. I'll notify the sensors team. Thanks for the report.

**Comment by oldnewthing** [comment]
The sensors team confirms this as a bug in the platform. Thanks for reporting it!

**Comment by OrbintSoft** [comment]
Thanks, I didn't know where report it!
There is a way to directly report bugs, related to windows sdk, to sdk team?
Thanks.
