### ISSUE TITLE
SerialDevice.FromIdAsync() throws "The data is invalid. (Exception from HRESULT: 0x8007000D)" after anniversary update

### ISSUE THREAD

**Issue by utpal-patel** [Microsoft/Windows-universal-samples#484]
I had working application with bluetooth serial communication, **After anniversary update** it gives device name "SPP" instead of device name and Application could not able to connect with serial port using same code.

**SerialDevice.FromIdAsync()** Throws _The data is invalid. (Exception from HRESULT: 0x8007000D)_ error.

**Device Id Looks Like : Bluetooth#Bluetootha8:a7:95:87:49:8a-00:12:f3:23:72:6f#RFCOMM:00000000:{00001101-0000-1000-8000-00805f9b34fb}**

```
public async Task<string> InitializeSerialPort(string deviceId)
        {
            try
            {
                SerialPortObject = await SerialDevice.FromIdAsync(deviceId);   //Throws Error

                if (SerialPortObject != null)
                {

                    SerialPortObject.BaudRate = 57600;
                    SerialPortObject.DataBits = 8;
                    SerialPortObject.Parity = SerialParity.None;
                    SerialPortObject.StopBits = SerialStopBitCount.One;
                    SerialPortObject.Handshake = SerialHandshake.None;
                    SerialPortObject.WriteTimeout = TimeSpan.FromMilliseconds(100);
                    SerialPortObject.ReadTimeout = TimeSpan.FromMilliseconds(100);

                    ReadCancellationTokenSource = new CancellationTokenSource();
                    Listen();

                    try
                    {
                        //***********************************************//
                        // Execute Code
                        //***********************************************//

                    }
                    catch (Exception ex)
                    {
                        System.Diagnostics.Debug.WriteLine(ex.ToString());
                    }

               }
                else
                {
                    var status = DeviceAccessInformation.CreateFromId(deviceId).CurrentStatus;

            
                }
            }
            catch (Exception ex)
            {          
                System.Diagnostics.Debug.WriteLine(ex.ToString());
            }
            //}

            return "Can not connect to selected device!!";
        }
```

**Comment by oldnewthing** [comment]
The issue you are running into is not with a sample in this repo. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.

**Comment by utpal-patel** [comment]
Sorry for bothering you more but I can see same line of code in serialarduini Samples/SerialArduino/cs/EventHandlerForDevice.cs

       SerialPortObject = await SerialDevice.FromIdAsync(deviceId);   //Throws Error

I will ask to in Microsoft support for sure but if you confirm any api change in this than it will be great help!!

**Comment by NanovaEnvironmental** [comment]
Hello! I have the same problem. Do you find the solution?  Could you please share it with me?
