### ISSUE TITLE
WebView custom UA

### ISSUE THREAD

**Issue by boodoolak** [Microsoft/Windows-universal-samples#485]
Hello. 
I need set custom User-agent for every request in webview. Please answer me on this question  http://stackoverflow.com/questions/39490430/change-default-user-agent-in-webview-uwp

**Comment by oldnewthing** [comment]
The question you have is not about a sample. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
