### ISSUE TITLE
UI basics (XAML) sample

### ISSUE THREAD

**Issue by MrBluster** [Microsoft/Windows-universal-samples#488]
RichEditBox is saving text color info.   But deletes text colors on focus.  It is very difficult to get information on this topic.   A fix would go a long way to increasing use.   I later found out the problem could be solved by changing the RichEditBox Backgound color to white????   Don't know enough about this to submit a change.

**Comment by oldnewthing** [comment]
This is a known problem with RichEditBox. My understanding is that the RichEditBox template resets the foreground color when it enters the focused visual state, which means that any custom foreground colors get wiped out.

If you want assistance with working around the problem (e.g., retemplating the RichEditBox), you can open a support case with our Developer Support team. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
