### ISSUE TITLE
Error	CS0234: System.Speech / Microsoft.Speech and System.Windows.Media missing

### ISSUE THREAD

**Issue by FonixAgileSolutions** [Microsoft/Windows-universal-samples#489]
Hi.
I got the below errors, I tried to add References from the Assembly / Framework, but nothing is appearing there.
I installed fresh edition of VS comunity 2015 yesterday, on the lates updated Windows 10 build (updated yesterday too)

Error	CS0234	The type or namespace name 'Speech' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)

and

Error	CS0234	The type or namespace name 'Media' does not exist in the namespace 'System.Windows' (are you missing an assembly reference?)

**Comment by oldnewthing** [comment]
Which sample is exhibiting this problem?

**Comment by anpilley** [comment]
Hm, I believe the Microsoft.Speech namespace is used as part of the Microsoft Speech Platform SDK 11 (https://msdn.microsoft.com/en-us/library/dd266409(v=office.14).aspx) which is not what we've used in the UWP Speech sample. The Microsoft Speech Platform SDK 11 API set is targeted at classic win32 c#/c++ applications, and isn't usable in UWP. I believe it's a separate download, not part of any edition of VS2015

**Comment by oldnewthing** [comment]
The issue you are running into is not about a sample in this repo. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.

**Comment by FonixAgileSolutions** [comment]
the [http://aka.ms/storesupport] is a paid support :(
