### ISSUE TITLE
Live DASH is not supported by Adaptive Streaming

### ISSUE THREAD

**Issue by raviolpula** [Microsoft/Windows-universal-samples#494]
Looks like Live DASH is not yet supported by UWP Adaptive Streaming. Any idea when it will be supported?

**Comment by oldnewthing** [comment]
The issue you are running into is a question about the platform, not about the Adaptive Streaming sample. You can open a support case with our Developer Support team who can further help with the question you have. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.

**Comment by raviolpula** [comment]
Thank you for the replay. I have opened a support case as you suggested. I have observed that samples has a "LiveDash" project which supports LIVE DASH through MseStreamSource. Is this the recommended way of supporting LIVE DASH till native SDK supports it?

**Comment by NickDrouin** [comment]
Hi Raviolpula, no, I would not recommend going to production with a sample derived from the LiveDash sample.  It was a 'special case' sample published at the request of a partner to meet a particular need.  It does demonstrate how media segments can be sequenced in MseStreamSource, but it does not implement the usual logic behind live dash players.  
There are a few solutions out there today for live dash, mostly JS player libraries, and libraries produced to support and compliment DASH content creators.  For example, the Azure Media Player compliments Azure Media Services.
I drive the platform investments in adaptive streaming, wrote the sample, and we're working on improvements for the next release.  Ask to be put in contact with me in your support case.

**Comment by raviolpula** [comment]
Thank you. We are developing the UWP App in XAML & C#. Am not sure if we can integrate a JavaScript SDK directly into the UWP app which is developed in XAML & C#.
