### ISSUE TITLE
Background media playback and suspension

### ISSUE THREAD

**Issue by mcosmin222** [Microsoft/Windows-universal-samples#495]
Playback doesn't start after the app is suspended and a play command is given through the system media transport controls.

Steps to reproduce using the background media playback sample:

1. Start playback from foreground UI
2. Let it play a few seconds, pause playback.
3. Suspend application
4. In the system media transport controls, tap the play button.

Playback will not start until the app foreground is resumed. Tested on L830

**Comment by aarononeal** [comment]
How are you initiating suspend and does it resume if you press play more than once? Can you share the build # tested?

If this is the issue I believe it is, there is an OS fix on the way.

**Comment by aarononeal** [comment]
Confirmed, this was an OS regression that was corrected in a recent servicing release--either the one that just went out or one on the way soon.

**Comment by flanker87** [comment]
@aarononeal please explain your answer about this issue. I also encountered this problem during testing of my application. OS version tested 10.0.586.0. Play Button which hosted in SystemMediaTransportControls not respond after 5 minutes (after app suspending) Official Microsoft sample has same behaviour.
It is OS bug? Is there workaround to avoid this wrong behaviour?

**Comment by aarononeal** [comment]
It's an OS bug with no workaround. You have to apply the latest Windows 10 update to your phone to resolve.

**Comment by mcosmin222** [comment]
The bug got fixed a few builds ago.
