### ISSUE TITLE
Camera Barcode Scanner

### ISSUE THREAD

**Issue by albertorivelli** [Microsoft/Windows-universal-samples#498]
this sample does not work. I tried with a PC, a tablet and a Lumia 950. The image is very clear but after I press the software trigger nothing happens. It looks to me this is not implemented at all inside the os.
Also the focus needs to be fixed when automatic focus is not available, I added a button to focus the image on the Lumia 950.
Another problem is that the authorization to use the camera is asked every time the app starts. This is very annoying. I think it should be asked only the first time (like it is for location for example) the user can always turn it off later through the settings. This happens also with Pos printers but not with standard barcode scanners.

**Comment by oldnewthing** [comment]
The team informs me that Camera Barcode Scanner is not supported on Phone. I will update the README.
