### ISSUE TITLE
Detect network changes with SocketActivityTrigger task

### ISSUE THREAD

**Issue by JurajPupak** [Microsoft/Windows-universal-samples#500]
Hi,
I'm confused about network changes using SocketActivityTrigger background task. My VOIP app uses background task of type SocketActivityTrigger. When app is suspending the socket is transferred to socket broker. When app is in foreground, it takes the socket from brokering service. I need to mention, that background task is in-procces, so I handle OnBackgroundActivated callback. What is my problem and what I don't understand:
If the app is suspended (not running) and socket transferred to brokering service, and network connection is 3G/4G and I turn on WiFi, nothing happens (OnBackgroundActivated is not fired). I'd like to switch from 3G to WiFi because of cost data usage. I thought, when I'm using SocketActivityTrigger it always fires with network changes. The same scenario is, when network connection is WiFi and user goes out of WiFi range, it needs to be reconnected to 3G.
I've tried SocketActivityStreamSocket sample and always when I changed network connection, OnBackgroundActivated was fired with reason KeepAliveExpired, always. Is it case KeepAliveExpired the right place, where to put reconnecting logic?
Many thanks

**Comment by oldnewthing** [comment]
This appears to be a question about how to design your application, not a question about a sample. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
