### ISSUE TITLE
VoiP sample doesn't build

### ISSUE THREAD

**Issue by michiproep** [Microsoft/Windows-universal-samples#505]
Hi, when I try to build the VoiP sample, I get
The type or namespace name 'VoipPhoneCall' could not be found (are you missing a using directive or an assembly reference?)

Basically all VoiP*-Types are not available.

I already checked my referenced packages. Versions: 10.0.14393.0

Any ideas? 
Thanks in advance,
Michael

**Comment by oldnewthing** [comment]
Builds okay for me except for manifest issue #770.
