### ISSUE TITLE
need help for  Sample/DeviceLockdownAzureLogin

### ISSUE THREAD

**Issue by a285738349** [Microsoft/Windows-universal-samples#506]
1, 
 <Capabilities>
    <Capability Name="internetClient" />
    <rescap:Capability Name="enterpriseDeviceLockdown" />
  </Capabilities>
 rescap:Capability in Package.appxmanifest is disable....why?

2, i building this sample on the  global::System.Diagnostics.Debugger.Break(); stop working ......

please help!!!

**Comment by oldnewthing** [comment]
I'm sorry, I don't understand your questions. What do you mean when you say that the rescap:Capability is disabled? You showed that it is indeed present in the Package.appxmanifest. And what do you mean by Debugger.Break() stopped working?

**Comment by oldnewthing** [comment]
Closing due to no response.
