### ISSUE TITLE
Bug in UWP: interprets special characters as letters

### ISSUE THREAD

**Issue by MovGP0** [Microsoft/Windows-universal-samples#507]
Hi, 
there is a bug in UWP where special characters are interpreted as letters when using multi layered keyboards like [Neo](https://en.wikipedia.org/wiki/Keyboard_layout#Neo). 

Apparently the `UIElement.KeyUp` and `UIElement.KeyDown` events provide the wrong `VirtualKey` information in the `KeyRoutedEventArgs`. The problem is when using a physical keyboard and also when using the On-Screen-Keyboard. 

The only workaround so far is to write the text in a Win32/WPF application and then Copy&Paste the text into the appropriate fields, which causes a serious security problem when working with critical passwords. It's also a total annoyance when working with data that require handling of lots of special charecters like JSON and XML data. 

When using a non-multi layered layout (ie. IBM layout) the `VirtualKey` information is correct.

**Comment by MovGP0** [comment]
![special character bug](https://cloud.githubusercontent.com/assets/83339/19432500/14f36a40-945d-11e6-817b-78246dae4fab.png)

**Comment by MovGP0** [comment]
![special character bug 2](https://cloud.githubusercontent.com/assets/83339/19432667/eb49d430-945d-11e6-85c7-9ab3018e1c3b.png)

**Comment by oldnewthing** [comment]
This is the UWP samples repo, so issues here are about the samples themselves, not for UWP as a whole. Use the Windows Feedback app to report issues with the platform.

**Comment by MovGP0** [comment]
The Windows Feedback app is not helping. This is the right place for UWP bug reports: 

https://wpdev.uservoice.com/forums/110705-universal-windows-platform/
