### ISSUE TITLE
Task could not find "winmdexp.exe" using the SdkToolsPath "" or the registry key

### ISSUE THREAD

**Issue by thedjnK** [Microsoft/Windows-universal-samples#508]
I had the same problem as reported in this bug report: https://github.com/Microsoft/Windows-universal-samples/issues/393

Yes I installed the SDK when I installed visual studio 2015, and yes the file DOES exist. I installed VS to a different drive using a directory junction. I worked around the issue by creating the registry key HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\NETFXSDK\4.6.1\WinSDK-NetFx40Tools-x86 and setting the value to E:\Applications\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\WinMDExp.exe

However, this should be fixed in your applications so that my manual fix isn't required. I re-ran the suggested installed from that page which stated that the tools were already installed, so I repaired them but it didn't resolve the issue and again there was no HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\NETFXSDK registry key.

**Comment by oldnewthing** [comment]
This appears to be a problem with the SDK itself and not with the samples.
