### ISSUE TITLE
UserInfo sample 

### ISSUE THREAD

**Issue by jerrak0s** [Microsoft/Windows-universal-samples#510]
In [userInfo ](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/UserInfo) sample only firstName and Lastname are returned. The other info return null values.
This is an error that is reported many times in stackoverflow.

http://stackoverflow.com/questions/40179695/uwp-get-the-current-username-to-provide-rights-to-the-user?noredirect=1#comment67647683_40179695

![capture](https://cloud.githubusercontent.com/assets/3514710/19618862/f8417fe4-985e-11e6-88fd-37ab1c2da532.PNG)

**Comment by Goldstrike** [comment]
I meet the same case and this is a problem cause I need to transmit the accountName and the domainName to a WebService...
Do you use a "personal" Windows account or a "professional" Active Directory account?

**Comment by jerrak0s** [comment]
@Goldstrike a personal windows account

**Comment by oldnewthing** [comment]
I've asked the feature team to investigate.

**Comment by oldnewthing** [comment]
The feature team gave me this table that breaks down which properties are supported under what conditions.

Property | Local account   not domain joined | Local account   domain joined | MSA account | AAD account
-- | -- | -- | -- | --
AccountName | Not available | Not available | Not available | Not available
DisplayName | Not available | Not available | Not available | Available if domain joined
DomainName | Not available | Available | Not available | Available
FirstName | Available | Available | Available | Available
GuestHost | Available on XBOX | Available on XBOX | Available on XBOX | Available on XBOX
LastName | Available | Available | Available | Available
PrincipalName | Not available | Available | Not available | Available if domain joined
ProviderName | Not available | Not available | Not available | Not available
SessionInitiationProtocolUri | Not available | Available | Not available | Available if domain joined

We'll work to get this table into the documentation.
