### ISSUE TITLE
Barcode Scanner sample not working with Microsoft Camera Front/Rear

### ISSUE THREAD

**Issue by DirkRoelandt** [Microsoft/Windows-universal-samples#511]
Sample doesn't sees to be working with Microsoft Camera, despite it signals is ready to scan

![image](https://cloud.githubusercontent.com/assets/12224610/19619280/b77b8b58-9863-11e6-87ed-d405ba918bcd.png)

Devices found in device manager : 

![image](https://cloud.githubusercontent.com/assets/12224610/19619294/f8894b1c-9863-11e6-9469-0f3d24dc0364.png)

**Comment by niwrA** [comment]
I've been working with this as well for a while now. It seems to work fantastically well with Auto-Focus cameras, but not at all with Fixed Focus cameras.

**Comment by niwrA** [comment]
I also tried this with the Lumia 950XL and found the same issue there despite that the camera auto-focusses on the barcode perfectly. It works great on my desktop, but can't get it to work on the Lumia 950XL (or a fixed focus laptop camera).

I also opened an issue here: https://social.msdn.microsoft.com/Forums/en-US/d17ecb0c-0af4-4d3c-a783-f322fbbb83f4/camerabarcodescanner-issues?forum=wpdevelop

**Comment by DirkRoelandt** [comment]
This does neither work on Surface Pro 4 (Windows 10.0.14959)

**Comment by oldnewthing** [comment]
The CameraBarcodeScanner sample has been withdrawn.
