### ISSUE TITLE
How can I just list the nearby BluetoothLE devices that can be connected?

### ISSUE THREAD

**Issue by LinJianping** [Microsoft/Windows-universal-samples#513]
The example BluetoothLEClient use the following method to discover BLE devices:
`deviceWatcher =
                    DeviceInformation.CreateWatcher(
                        "(System.Devices.Aep.ProtocolId:=\"{bb7bb05e-5972-42b5-94fc-76eaa7084d49}\")",
                        requestedProperties,
                        DeviceInformationKind.AssociationEndpoint);`
But I found this method will also list the paired devices which is not alive. I want to just list the nearby alive BLE devices which can be paired and connected. Is there any way to achieve this purpose or how can I judge whether a BLE device can be connected?

**Comment by LinJianping** [comment]
I have found the resolution. The AssociationEndpoint device has a property named "System.Devices.Aep.IsPresent" which can demonstrate whether the device can be connected.

**Comment by kpathakota** [comment]
You could also consider [BluetoothLEDevice.GetDeviceSelectorFromPairingState(false)](https://msdn.microsoft.com/en-us/library/windows/apps/windows.devices.bluetooth.bluetoothledevice.getdeviceselectorfrompairingstate.aspx)

**Comment by kpathakota** [comment]
I'm going to close this issue since it's been resolved.
