### ISSUE TITLE
POS Printing USB 

### ISSUE THREAD

**Issue by croccio** [Microsoft/Windows-universal-samples#514]
any news on this? i've an epson tm t20II without ethernet. only serial and usb. How can i print with this? is ther some adapter that i should use or you'll implemeent this?

sorry for post this issue, but i'ts urgetn. can you tell me if it is impossible print with pos from universal app? or i can buy an adapter or it works with serial? thanks

**Comment by antalistvan** [comment]
Impossible.

They don't want to support this.
And they will close this issue as soon as they found your question.

Our plan is, create an out of process not UWP local app wich will communicate with the printer and our UWP app will call this process by rest api.

**Comment by croccio** [comment]
so if i buy epson tmt20II with ethernet this should works?

**Comment by antalistvan** [comment]
https://msdn.microsoft.com/en-us/library/windows/apps/mt426652.aspx

> Support is currently limited to the Network and Bluetooth device models listed in the tables below. USB connected printers are currently not supported.

As I see, the answer is yes.
