### ISSUE TITLE
GattCharacteristic.WriteValueAsync failed causes my UWP APP crashed and disabled my bluetooth

### ISSUE THREAD

**Issue by LinJianping** [Microsoft/Windows-universal-samples#515]
When I execute the sample project BluetoothLEClient, sometimes the method `GattCharacteristic.WriteValueAsync` failed and raised an exception named "The semaphore timeout period has expired.(Exception from HRESULT:0x80070079)" . This exception would cause my my UWP App failed and disable my bluetooth. Does anyone know how I can handle this exception so that my program doesn't crash and my bluetooth doesn't fail?

**Comment by kpathakota** [comment]
The issue you are running into is not a problem in a sample app. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Additionally, if you're running the latest insider builds, please file Feedback via Feedback Hub and the appropriate logging should get collected to allow us to investigate. Make sure to specify the Hardware, Devices and Drivers>Bluetooth path when filing.

**Comment by oldnewthing** [comment]
To open a case with the Developer Support team:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
