### ISSUE TITLE
Crashes on Windows Phone when MSApp.getHtmlPrintDocumentSourceAsync() is called

### ISSUE THREAD

**Issue by jainpiyushb** [Microsoft/Windows-universal-samples#518]
Tried running the ColoringApp sample project to print a document.
I am using Microsoft Lumia 650 updated to OS Build 10.0.14393.321 Version 1607.

After debugging the app looks like it crashes on MSApp.getHtmlPrintDocumentSourceAsync(). 
The object conforming to HtmlPrintDocumentSource is returned successfully on the .then block.

Any ideas on what can be the problem ?

**Comment by oldnewthing** [comment]
Um, I can't find any app called ColoringApp in this repo. Perhaps you're referring to the [Coloring Book App](https://github.com/Microsoft/Windows-appsample-coloringbook)? That app is not part of this repo. You can report your issue in that app's report.

**Comment by jainpiyushb** [comment]
Thanks Raymond. I have tried Printing with the printing sample in this repo and still crashes. Let me open a new issue.

**Comment by jainpiyushb** [comment]
New issue opened https://github.com/Microsoft/Windows-universal-samples/issues/520. Also open an issue https://github.com/Microsoft/Windows-appsample-coloringbook/issues/1 on Coloring Book App.
