### ISSUE TITLE
Add sample for the App Extensions API

### ISSUE THREAD

**Issue by martinsuchan** [Microsoft/Windows-universal-samples#519]
The collection of samples does not contain any sample how to use the new App Extension API, that was shown here:  
https://channel9.msdn.com/Events/Build/2016/B808

This keynot has related sample available here
https://github.com/Microsoft/Build2016-B808-AppExtensibilitySample
but it was not even updated to the Anniversary Update SDK version and needs some maintenance before it actually works.

It would be handy to have out-of-the-box working sample for the **App Extension API** here.

**Comment by oldnewthing** [comment]
I've forwarded your feedback to the AppExtension team. thanks.
