### ISSUE TITLE
Crash on Windows Phone in Printing Sample app when you try to print

### ISSUE THREAD

**Issue by jainpiyushb** [Microsoft/Windows-universal-samples#520]
The app crashes when you try to print with  [Printing JS Sample](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/Printing/js).

Using Microsoft Lumia 650 updated to OS Build 10.0.14393.321 Version 1607.
On debugging it looks like it crashes after the object conforming to HTMLPrintDocumentSource is returned in the then block of MSApp.getHtmlPrintDocumentSourceAsync(document).

Any ideas on what can be the problem ?

**Comment by oldnewthing** [comment]
I've asked the feature team to investigate.

**Comment by oldnewthing** [comment]
The feature team suspects that this is due to fact that the Lumia 650 is a low-memory device.
