### ISSUE TITLE
OCR sample does not Auto-Focus on Lumia 950 XL

### ISSUE THREAD

**Issue by niwrA** [Microsoft/Windows-universal-samples#521]
The OCR sample does not Auto-Focus on Lumia 950 XL making it unuseable there. But it was easily fixed (at least for me as I played around a fair bit these last weeks with similar issues for barcode detection), by adding this in the IsInitialised section of the InitializeCameraAsync()

                  var controller = mediaCapture.VideoDeviceController;

                    if (controller != null && controller.FocusControl != null && controller.FocusControl.Supported)
                    {
                        var focusConfig = new Windows.Media.Devices.FocusSettings();
                        focusConfig.AutoFocusRange = Windows.Media.Devices.AutoFocusRange.Macro;

                        var supportContinuousFocus = controller.FocusControl.SupportedFocusModes.Contains(Windows.Media.Devices.FocusMode.Continuous);
                        var supportAutoFocus = controller.FocusControl.SupportedFocusModes.Contains(Windows.Media.Devices.FocusMode.Auto);

                        if (supportContinuousFocus)
                        {
                            focusConfig.Mode = Windows.Media.Devices.FocusMode.Continuous;
                        }
                        else if (supportAutoFocus)
                        {
                            focusConfig.Mode = Windows.Media.Devices.FocusMode.Auto;
                        }

                        controller.FocusControl.Configure(focusConfig);
                        await controller.FocusControl.FocusAsync();
                    }
                    else
                    {
                        if (controller.Focus.Capabilities.AutoModeSupported)
                        {
                            controller.Focus.TrySetAuto(true);
                        }
                        else
                        {
                            // this device is fixed focus                           
                        }
                    }

I'm sure there are still some improvements possible, but this at least makes the sample work on Windows Mobile smartphones.

**Comment by oldnewthing** [comment]
I've asked the feature team to verify that your fix is good.

**Comment by oldnewthing** [comment]
Thanks for the improvements, but they are outside the scope of the OCR sample, which is to show how to use the OCR features. The sample is not intended to be a complete end-to-end solution for performing OCR from a camera. Those changes are good to have for a real-world OCR app, but they don't fit within the narrow remit of an OCR sample.
