### ISSUE TITLE
Flush needed after writing to stream?

### ISSUE THREAD

**Issue by timgreenfield** [Microsoft/Windows-universal-samples#527]
In your suspend & resume sample, I see that you are not flushing the file stream. Should you or does CopyToAsync automatically perform a flush internally?
https://github.com/Microsoft/Windows-universal-samples/blob/6370138b150ca8a34ff86de376ab6408c5587f5d/Samples/BasicSuspension/cs/Common/SuspensionManager.cs#L94

**Comment by ChrisGuzak** [comment]
It is best practice to not use FlushAsync() given the performance implications (all pending IO is flushed, not just that initiated by your use of the stream). We removed use of FlushAsync() from all of the samples at one point. Generally the IO system will ensure data is written based on the configuration of the storage device. Suspending has nothing to do with flushing... pending IO will be written even if your process is suspended or has been shut down.
