### ISSUE TITLE
SystemMediaTransportControls - UI doesn't show all buttons or timeline

### ISSUE THREAD

**Issue by softworkz** [Microsoft/Windows-universal-samples#537]
I'm on Windows 10 latest release and the SystemMediaTransportControls are not showing buttons like FastForward, Rewind, AutoRepeat etc.

Also the samples are performing updates to the timeline, but I can't see any timeline displayed.

How can I see the timeline and the mentioned buttons? If I implement these features, I would also like to test them.

What am I missing here?

**Comment by aarononeal** [comment]
1. What API are you using to play media?
2. What platform (desktop, phone, Xbox)?
3. What OS build?
4. How are you bringing up the controls?

**Comment by softworkz** [comment]
1. I'm doing my own playback and update the SystemMediaTransportControls information as demonstrated in the javascript portion of the sample SystemMediaTransportControls
2. Tested on desktop and phone emulator
3. Desktop 14393.and latest insider build 14965; Mobile emulator 14393
4. Desktop: Start, Stop, Pause, Skip, Volume buttons on the keyboard and lock screen.
   Mobile: Volume buttons and lock screen
5. Tested both audio and video in all scenarios

**Comment by aarononeal** [comment]
Phone currently has a design limitation that prevents other buttons from showing on these controls unless using a Media Foundation based API, such as MediaPlayer.

I'm not aware of this same limitation existing for desktop, but I've followed up with the team to find out.

**Comment by softworkz** [comment]
And how about the timeline? You created the sample containing code to update the timeline. How did you test this? I never got a timeline displayed. It always looks like this:

![mediacontrols](https://cloud.githubusercontent.com/assets/4985349/20636172/6ee67dc4-b368-11e6-94ad-5d6192b367c9.png)

**Comment by aarononeal** [comment]
Desktop does not have a timeline control. It's only the phone or xbox shell (off the top of my head I don't remember which) that displays it.

**Comment by aarononeal** [comment]
What you're running into here are platform UI differences, not a sample issue, so I'm marking closed. 

We track platform enhancements through a different system and will take your feedback into account.

**Comment by softworkz** [comment]
So you're saying the buttons shown in the screenshot are always exactly those three on Windows Desktop and this cannot be changed through the SystemMediaTransportControls API?

I just wonder that SystemMediaTransportControls is offering all those properties (even for playback speed, AutoRepeatMode button, ShuffleMode button, FastForward, Rewind etc.) while there is no way to test it.

Or are those controls displayed on xbox only?

**Comment by aarononeal** [comment]
> So you're saying the buttons shown in the screenshot are always exactly those three on Windows Desktop and this cannot be changed through the SystemMediaTransportControls API?

Correct. Others are available on Xbox, Bluetooth, SmartGlass.

**Comment by softworkz** [comment]
One last question: You had mentioned "Bluetooth" a while ago in a similar context. What kind of Bluetooth setup scenario are you referring to?

**Comment by aarononeal** [comment]
AVRCP devices like a car stereo provide their own user interface to control playback. So if you pair a phone with one of those then additional features may be available through that device UI.
