### ISSUE TITLE
Changing the contact picker backend to Azure table storage

### ISSUE THREAD

**Issue by varghesep** [Microsoft/Windows-universal-samples#539]
I know that [Contact Picker](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/ContactPicker) integrates with the Windows 10 OS and retrieves the contacts from the OS.

Can I integrate [Contact Picker](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/ContactPicker) with contacts saved in **Office 360** or **Azure Table Storage** or **Azure SQL DB**? My requirements are (1) I will have a web page with a contact picker developed with WinJS (2) the contacts are added and retrieved from Azure table storage or Azure SQL.

**Comment by oldnewthing** [comment]
This is not a samples issue. This is a question about the platform. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
