### ISSUE TITLE
SmartCard c++ sample does not work

### ISSUE THREAD

**Issue by jonitis** [Microsoft/Windows-universal-samples#540]
I tried the c++ sample with external USB smartcard reader and attempt to run scenario 7 - List all smartcards fails with access denied. c# sample works fine because their Package.appxmanifest specifies the "Shared User Certificates" permission. When I set the same permission to c++ sample it fails slightly further with exception "The application called an interface that was marshalled for a different thread.". Is c++ code actually tested/working?

**Comment by oldnewthing** [comment]
I asked the feature team to investigate.

**Comment by oldnewthing** [comment]
Fix will be in the next update. Thanks for reporting it.
