### ISSUE TITLE
PhotoImportSubfolderCreationMode.CreateSubfoldersFromExifDate hangs if exif empty

### ISSUE THREAD

**Issue by pierresa** [Microsoft/Windows-universal-samples#541]
import hangs when PhotoImportSubfolderCreationMode.CreateSubfoldersFromExifDate is selected and exif date is not set (no error message, just hangs)

**Comment by aarononeal** [comment]
Thank you for the report!

Could you post a file that causes the hang? Does it hang the Photos app too?

This would help a lot as metadata bugs can be tricky to reproduce without the actual metadata.

**Comment by pierresa** [comment]
Honestly this is too old for me to remember I submitted that over 2 months ago, sorry doing something else by now. You may close as unreproductable



Pierre

De : Aaron Oneal [mailto:notifications@github.com]
Envoyé : 03 February 2017 21:53
À : Microsoft/Windows-universal-samples <Windows-universal-samples@noreply.github.com>
Cc : pierresa <pierresa@outlook.com>; Author <author@noreply.github.com>
Objet : Re: [Microsoft/Windows-universal-samples] PhotoImportSubfolderCreationMode.CreateSubfoldersFromExifDate hangs if exif empty (#541)


Thank you for the report!

Could you post a file that causes the hang? Does it hang the Photos app too?

This would help a lot as metadata bugs can be tricky to reproduce without the actual metadata.

**Comment by aarononeal** [comment]
We believe we have found the platform bug.

You can import files without EXIF data using PhotoImportSubfolderCreationMode.CreateSubfoldersFromExifDate, but if you happen to have a pair of files, one as a sidecar of the other, and none of them have EXIF data, and you are importing in that mode, something fails.
 
The conditions leading to the bug should be relatively rare in practice. It has to be a JPEG without date taken + a sidecar of some kind. Most devices taking pictures with sidecars are either DSLRs (JPEG+RAW) or smartphones (JPEG+MOV), and they all write the date taken.

Thank you for reporting it and we hope to provide a fix in a future platform update.
