### ISSUE TITLE
High CPU load on ToastNotificationManager.History Clear or Remove

### ISSUE THREAD

**Issue by mnikonov** [Microsoft/Windows-universal-samples#542]
On attempt to execute ToastNotificationManager.History.Clear or Remove API of Notifications sample app freezes on 3-5s. 

I have caught this issue on Surface Pro 4 with i5 process and ARM mobile device. On both of them was installed Windows 10 14393.447. Also I have tried to start several Tasks with Remove method for not existed tag id and Task manager has shown next picture.

![image 1](https://cloud.githubusercontent.com/assets/10001265/20688312/035f4104-b5c9-11e6-9c2b-4032bedaf26e.png)

Maybe you can provide workaround for that? Otherwise this API useless... :(

**Comment by anbare** [comment]
We're unable to repro this issue. Please submit a bug through the Feedback Hub under the category of Start and Action Center -> Performance. Make sure to "Begin monitoring" and then repro the issue, which should capture logs so we can investigate.

Closing this since it isn't a samples bug.

**Comment by boarder2** [comment]
In case someone else comes across this issue in the future, I've submitted feedback which you can upvote here 

feedback-hub:?contextid=205&feedbackid=94983a5a-fb34-4a54-a02d-85b6bc6c5518&form=1&src=2

**Comment by anbare** [comment]
Awesome, we'll have our devs look into the logs and see if we can find anything. We'll let you know if we need additional info.

**Comment by anbare** [comment]
@boarder2 We've fixed this issue in the Creators Update, you should no longer be seeing that CPU load with the upcoming Creators Update. Thanks!

**Comment by boarder2** [comment]
@anbare Excellent. Thanks so much for the follow up!

**Comment by mnikonov** [comment]
@anbare Thanks, waiting for Creators update :)
