### ISSUE TITLE
VideoPlayback not smooth on the phone

### ISSUE THREAD

**Issue by iamstudentVN** [Microsoft/Windows-universal-samples#546]
I use:
`MediaPlayerElement
media.MediaPlayer.Source = MediaSource.CreateFromUri(new Uri(ssss, UriKind.Absolute));`
this is video not smooth and i try:
`media.MediaPlayer.SetUriSource(new Uri(ssss, UriKind.Absolute));`
or MediaElement is smooth

**Comment by aarononeal** [comment]
Thanks for the report. We're investigating whether there is a platform bug. 

Can you share more details? Is there a particular video we can try? Is it local or network playback? What is the OS build number?

**Comment by iamstudentVN** [comment]
MediaSource.CreateFromUri is network, resolution video: 720p and OS build: 10.0.10240.0 to 10.0.14393.0

**Comment by iamstudentVN** [comment]
On the PC it is works well

**Comment by aarononeal** [comment]
Thank you for reporting. We have confirmed this is an OS bug that we expect to fix in a future update.

**Comment by iamstudentVN** [comment]
please inform me, the problem is fix in which build? thanks

**Comment by aarononeal** [comment]
I believe the current Windows Insider build should have the fix.

**Comment by iamstudentVN** [comment]
@aarononeal This is the same when i stream video from uri: MediaElement.SetMediaStreamSource. On PC is smooth and phone is not. My PC using version 15063.138 and Phone 14393.1066
