### ISSUE TITLE
OpenSource Control Microsoft apps

### ISSUE THREAD

**Issue by iamstudentVN** [Microsoft/Windows-universal-samples#547]
Microsoft apps have excellent control. I want use it in my apps. Please offer it as humbeger menu, splitview...
Detail, groove music:

![](https://cloud.githubusercontent.com/assets/12800744/20855891/58d1b610-b936-11e6-8348-171f5d9a6705.png)

![](https://cloud.githubusercontent.com/assets/12800744/20855892/5ac48d44-b936-11e6-8114-c2bbc79a79d9.png)

**Comment by oldnewthing** [comment]
The issue you are running into is not about a sample that is not working. It appears to be a feature request.
