### ISSUE TITLE
ProjectionManager.StartProjectingAsync get “0x80070005 AcessDenied”

### ISSUE THREAD

**Issue by lovemai073** [Microsoft/Windows-universal-samples#548]
we want to develop about “Miracast projection” UWP application
we download sample code form our GitHub project
 when Debug this project using VS2015, click Scenario3 will get an error “0x80070005 AcessDenied”
Scenario3.cs key command is “await ProjectionManager.StartProjectingAsync(rootPage.ProjectionViewPageControl.Id, thisViewId, selectedDisplay);”
In out labs will reproduce this problem
Environment:
Windows10 (1607 build 14393.447), I tried 10586 sometimes can’t reproduce
Visual Studio 2015 Update3 + SDK

Have any idea on this [problem?]
(http://imgur.com/a/9AirC)
Thanks

**Comment by lovemai073** [comment]
This issue very reproduce
Looks like load the driver permissions issues with COM components

**Comment by aarononeal** [comment]
We are preparing new samples to address this issue.
