### ISSUE TITLE
DirectInk Stylus then Touch 

### ISSUE THREAD

**Issue by michael-tactual** [Microsoft/Windows-universal-samples#551]
Hello,

I'm developing a UWP C# application using DirectInk supporting simultaneous stylus and touch drawing. I've based my code on the Microsoft "SimpleInk" sample code. I've set up the InkCanvas/InkPresenter to support pen, touch, and mouse. I've set the configuration to InkPresenterPredefinedConfiguration.SimpleMultiplePointer. And everything works fine except for the case where a stylus touches and starts to draw followed by a finger touch.

The stylus touch down works as expected, but the finger touch down does not - the finger, although recognized by Windows as evidenced by the finger shadow, produces no touch or line. I've confirmed this with the following callbacks:

CoreInkIndependentInputSource.PointerEntering - Callback occurs on the stylus and the finger.
CoreInkIndependentInputSource.PointerPressing - Callback occurs only on the stylus.
CoreWetStrokeUpdateSource - All expected callbacks occur with stylus, no callbacks occur for finger.

What's odd is that other scenarios tested using both stylus and finger work fine:

    Finger touches down first then stylus touches.
    One finger touches down then a second finger touches down.
    One stylus touches down then a second stylus touches down.

Additionally, under the failed case, if the finger is lifted but the stylus remains in contact, any subsequent fingers touches will draw as expected and I receive the expected callbacks. However, if the stylus is lifted then placed back down, then the first finger touch down will again not be drawn.

Is this a known issue or is there some aspect I'm missing? Also, if this is a known issue, is there a workaround on either the PC side or the device side? I can modify the touch and pen device HID reports as needed.

I'm attaching a trimmed down example that exhibits this problem.   This can be built by replacing the corresponding files in the Microsoft "SimpleInk" example.

[Scenario1.zip](https://github.com/Microsoft/Windows-universal-samples/files/651835/Scenario1.zip)

Thanks,
Michael

**Comment by oldnewthing** [comment]
The issue you are running into is not a problem with a sample. You can open a support case with our Developer Support team who can further help with the specific issue you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
