### ISSUE TITLE
How add remind before END date of appointment?

### ISSUE THREAD

**Issue by boodoolak** [Microsoft/Windows-universal-samples#552]
I need add remind about appointment before end date, not start date.
This appointment's creation

    private async void AddFavoriteTenderEndDateToCalendar(MyEvent event)
    {
            var appointment = new Appointment();

            appointment.StartTime = new DateTimeOffset(event.StartDate);

            appointment.Duration = event.EndDate - event.StartDate;

            appointment.Subject = "blahblah";

            appointment.Reminder = TimeSpan.FromDays(1);

            var appointmentId = await AppointmentManager.ShowEditNewAppointmentAsync(appointment);           
    }
Appointment have not property EndTime and instead I calc duration `appointment.Duration = event.EndDate - event.StartDate; `
How can I add reminder before `event.EndDate`?

**Comment by oldnewthing** [comment]
The issue you are running into is not a problem with a sample. You can open a support case with our Developer Support team who can further help with your question. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
