### ISSUE TITLE
Addaptive streaming video laggy

### ISSUE THREAD

**Issue by linhnd** [Microsoft/Windows-universal-samples#553]
Every time I play an DASH or HLS format, the video get lags so much (MediaPlayerElement) (every 2-3s). Everything work fine and smooth with old MediaElement

**Comment by aarononeal** [comment]
What OS version number and platform?

**Comment by linhnd** [comment]
OS 10.0.14393.576/ Lumia 950 XL

**Comment by aarononeal** [comment]
Thank you for reporting. This is a known OS issue fixed in a future update.
