### ISSUE TITLE
Bluetooth Rfcomm Chat C# does not work unless paired

### ISSUE THREAD

**Issue by rdollarhide** [Microsoft/Windows-universal-samples#554]
I have performed a number of tests attempting to connect two devices using this sample where one device is a Win10 laptop and the other a Raspberry Pi3 w/ Win10 IoT Core.  The only way to get the sample to work is to pair the devices prior to running the apps.  There are numerous references to this sample across a range of forums where it is stated that the RFCOMM sample does not require pairing.  This does not appear to be the case.

**Comment by kpathakota** [comment]
Hi @rdollarhide This is currently a known issue w/ IoT (should work between two desktops or a phone and desktop just fine). We are aware of the issue and will respond back when we've got a more complete answer for you.

**Comment by rdollarhide** [comment]
Thank you for keeping me apprised of the issue, @kpathakota.  Hope it doesn't turn out to be a major problem because I really hope to utilize IoT Core on a RPi3 within my system and having that pairless Bluetooth capability with RFCOMM would be ideal.  Thank you again.

**Comment by kpathakota** [comment]
Yes agreed - we are able to repro. Just a matter of chasing down the root cause. Thanks for reporting the issue to us - helps us prioritize.
