### ISSUE TITLE
Multiple views sample ignores size preferences

### ISSUE THREAD

**Issue by erossetto** [Microsoft/Windows-universal-samples#556]
I'm using anniversary edition, I can't manage to specify the size of the new window beign shown, the window always displays with the same size as the parent.

**Comment by galich** [comment]
same problem, i can resize view after it's shown, but that is ugly - first window appears, then it immediately resize.

**Comment by oldnewthing** [comment]
I've asked the feature team to investigate. I think the answer is that the size preferences are respected only in Tablet mode.

**Comment by oldnewthing** [comment]
Tablet Mode is currently the only place where the size preference is respected, and even then, the only value it currently pays attention to is `ViewSizePreference.UseNone`. Most of the values are left over from Windows 8. The values may start doing more in the future, but right now, that's where things are at.
