### ISSUE TITLE
Background Task Synchronization

### ISSUE THREAD

**Issue by softworkz** [Microsoft/Windows-universal-samples#558]
Hi,

I've created a background task that can be triggered in three different ways. Since the registration API allows a single trigger only during task registration, I had to do three task registrations.

The resulting problem is that this can lead to multiple tasks that are executed simultaneously.

The task is implemented in JavaScript and I searched high and low for some reliable mechanism to synchronize multiple background tasks and avoid parallel execution but I couldn't find one.

Do you have any ideas how I can solve this?

**Comment by oldnewthing** [comment]
This appears to be a question about your application and not about a sample. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
