### ISSUE TITLE
MediaPlayer.Play() does not invoke CurrentStateChanged

### ISSUE THREAD

**Issue by iamsid** [Microsoft/Windows-universal-samples#560]
When an app with MediaPlayer (autoplay : false) starts & the MediaPlayer playlist is loaded, **MediaPlayer_CurrentStateChanged** gets invoked to show changing statuses: "Opening" & "Paused".

But, when playback is started with **MediaPlayer.Play()**, MediaPlayer_CurrentStateChanged does not get invoked and the status is stuck at "Paused".
Also, if MediaPlayer's **Playlist.MoveNext()**, **Playlist.MovePrevious()** or **Playlist.MoveTo(_index_)** is called, the state does not change.

I have also observed that in case of Playlist.MoveNext(), if it is called before Play method, state change does get invoked. For other methods, calling before or after Play has not effect.

You can test this behaviour in my app [Music Wall](bit.ly/musicwall). Play few tracks. Close the app. Start the app again. Press "previous". Music playback will start, but the play/pause button is stuck at play.
Now, close the app. Start it again & press next. This time, state change gets invoked correctly because MoveNext is called before Play in the code.

**Comment by aarononeal** [comment]
Thanks for reporting. We think there may be a platform bug here and that it has been fixed in an upcoming release. I'll update when I hear back from the team.

**Comment by aarononeal** [comment]
We believe this is an OS and not a sample bug that has been fixed in the latest Windows 10 flights. Please let us know if you still see this on RS2.
