### ISSUE TITLE
What this control?

### ISSUE THREAD

**Issue by iamstudentVN** [Microsoft/Windows-universal-samples#561]
It so a listbox but it has next arrow
![image](https://cloud.githubusercontent.com/assets/12800744/21514489/34f22434-ccf8-11e6-8667-ffa737f76de2.png)

**Comment by oldnewthing** [comment]
This is not a samples question. You can open a support case with our Developer Support team who can further help with the specific question you have. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
