### ISSUE TITLE
in-app purchase for other account

### ISSUE THREAD

**Issue by iamstudentVN** [Microsoft/Windows-universal-samples#563]
I have use in-app purchase for other account had previously submitted app?

**Comment by oldnewthing** [comment]
This does not appear to be a question about a sample. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
