### ISSUE TITLE
Add AudioFrameOutputNode to AudioCreation input sample, get bizarre behavior

### ISSUE THREAD

**Issue by RobJellinghaus** [Microsoft/Windows-universal-samples#565]
This issue tracks the following pull request:  https://github.com/Microsoft/Windows-universal-samples/pull/564

This PR demonstrates a simple attempt to extend the AudioCreation sample to capture incoming audio data via an AudioFrameOutputNode. I very closely followed the MSDN example code: https://msdn.microsoft.com/en-us/windows/uwp/audio-video-camera/audio-graphs

This code should simply copy the incoming audio data into a byte buffer, overwriting it on each call to the QuantumProcessed callback.

However, when I run the augmented sample, I get very strange and unexpected behavior. Specifically, I get literally over a hundred simultaneous QuantumProcessed callbacks on different threads. Most of them actually have no data in the frame source at all (capacityInBytes is 0, which to my mind should never happen). I cannot understand why the QuantumProcessed event would ever be triggered from multiple parallel threads at all, let alone over 100 of them!

The PR is to provide specific code for someone to look at in reproducing and explaining this very strange and completely blocking issue. As far as I can tell there is no existing UWP sample that actually uses the QuantumProcessed event, so I am not sure if the MSDN sample code above is actually valid. I am working with the latest (November 2016) version of the samples.

**Comment by RobJellinghaus** [comment]
This is with Windows 10 version 1607, OS build 14931.1002 (slow ring).

**Comment by RobJellinghaus** [comment]
After further investigation, it appears that the AudioGraph_QuantumProcessed event is being fired from a thread pool asynchronously.  So the audio graph does not block on the handling of that event.  This means that if you breakpoint in that event handler, the audio thread is still running and will fire hundreds more callback instances into the thread pool.

Moreover, the AudioFrameOutputNode is not synchronized with the QuantumProcessed events at all, so the frame data is very often gone by the time the QuantumProcessed event runs.  In short, the MSDN AudioFrameOutputNode example code literally does not work at all as described.  This is evident from the fact that there is no UWP sample that demonstrates it.

Right now, AudioFrameOutputNode is not actually usable, as there is no reliable way to synchronize on every incoming audio frame.  A possible workaround is to use a custom "no-op" effect, as the effects do appear to have proper synchronization.  But there is no doubt that the MSDN example code does not work as written, and that if a UWP sample had been written to match the MSDN code, it would have caught this problem long ago.  So this issue is really about the lack of an AudioFrameOutputNode code sample in the AudioCreation example, and about the underlying bugs that prevent such an example from working.

**Comment by aarononeal** [comment]
Thank you for the feedback. We are tracking internally and will be reviewing the documentation and this scenario in a future release.
