### ISSUE TITLE
Roaming data not working at all for ApplicationData sample. 

### ISSUE THREAD

**Issue by dpaulino** [Microsoft/Windows-universal-samples#567]
I have deployed the sample on my Surface Pro 4 and my Lumia 950. I followed the in-app instructions for scenario 6 (High priority), but I do not see any syncing of data between my phone and surface. Does this API actually work?

**Comment by oldnewthing** [comment]
I've asked the feature team to investigate.

**Comment by oldnewthing** [comment]
The feature team reports that they are observing roaming between Phone and Desktop on their systems. If you are still not seeing roaming working, please provide additional details.
