### ISSUE TITLE
Skeleton Tracking not working on XBOX

### ISSUE THREAD

**Issue by Vangos** [Microsoft/Windows-universal-samples#568]
The skeleton tracking is not working on XBOX. You can verify this with the CameraStreamCorrelation sample.

MediaFrameSourceKind.Custom is not available on the XBOX. It is available on the PC, though.

The following streams are available on the PC:

- Color
- Depth
- Infrared
- Custom

The following streams are available on the XBOX:

- Color
- Depth
- Infrared

As a result, skeletal tracking apps do not work on the XBOX platform. Are there any plans to support skeleton tracking on the XBOX?

**Comment by Vangos** [comment]
I also noticed something very weird. Even though I'm running the latest version of the XBOX OS (released [December 14, 2016](http://support.xbox.com/en-US/xbox-one/console/system-update-operating-system#0d35d99deef446eab5ee136b58b1038a)), the XBOX says "**October 2016**". You can see that in the screenshot. Notice that the version matches the December version (**10.0.14393.2152**).

![capture](https://cloud.githubusercontent.com/assets/562680/22065803/8323cb94-dd92-11e6-92ca-8c041ca63376.JPG)

The UWP skeletal tracking features were released in November. The latest version says "October". It seems that the latest version of the XBOX is using an older platform Core, with probably older drivers.

**Comment by Vangos** [comment]
Is there an update regarding this significant issue?

**Comment by dbruning** [comment]
+1

**Comment by jorncommentor** [comment]
Any solution to this issue?

**Comment by Vangos** [comment]
@aarononeal Should we expect an XBOX OS update that will fix the issue? Thank you 🥇

**Comment by aarononeal** [comment]
From speaking with the feature owner this is currently unsupported by design on Xbox. I will ask him again to follow up on this thread in case there is any additional info to provide.

**Comment by jorncommentor** [comment]
How are we supposed to get the skeleton data on the XBOX then? Any input on that from the feature owner? Thanks.

**Comment by Vangos** [comment]
@aarononeal Thank you very much for your reply.

It would be nice to have skeleton support in the XBOX again. The true power of Kinect is skeleton tracking.

**Comment by dbruning** [comment]
Agreed. We have a suite of Kinect-based apps that we are investigating moving from WPF to UWP so that they can run on the Xbox - not having skeleton support is a deal-breaker for us. It seems completely arbitrary *not* to have skeleton support, since the API supports it and we know that the Xbox hardware is capable.

**Comment by jorncommentor** [comment]
We are in the exact same situation. We are moving a health/training app from WPF to UWP, to be able to have the training part on XBOX. Without Kinect skeleton data it is not possible. 

What does the XBOX games with Kinect support do? Don't they use the media streams? The skeleton data is available on the platform:
http://www.windowscentral.com/best-kinect-games-xbox-one

Or is it just UWP apps, that can't access it ?

**Comment by Vangos** [comment]
@jorncommentor  I assume these games were developed with the original XBOX XDK. The XDK is available to XBOX ID members. However, Microsoft is suggesting to use UWP instead.

UWP does not support skeleton tracking right now. I think it is a driver issue since I have encountered the exact same behavior in Intel 6th-gen laptops, too.

Hopefully, Microsoft will add skeleton tracking support in the next XBOX OS update.

**Comment by dbruning** [comment]
I've created a uservoice entry from this (@vangos your original wording of this issue was perfect so I've just used your wording directly): https://wpdev.uservoice.com/forums/110705-universal-windows-platform/suggestions/19100656-add-skeleton-tracking-to-xbox-one-uwp-platform

To anyone else - if you come across this issue and would like to see this implemented, please go vote for the uservoice idea.

**Comment by Vangos** [comment]
@oldnewthing Closed the ticket as "Resolved" or as "Wontfix"?

Thanks!

**Comment by oldnewthing** [comment]
Closed as "off topic". This is not a samples issue.

**Comment by salubhai** [comment]
Sir kindly give me code in window store app using kinect v2?
