### ISSUE TITLE
Sensor classes on Windows IoT Core

### ISSUE THREAD

**Issue by arunbharadwaj** [Microsoft/Windows-universal-samples#570]
Hi there,

Thanks for this neat project.

I have difficulty in doing the following: I have a Intel Joule development board running Windows IoT Core. I have a SPI header on the board which exposes spi0 pins. I have the ADXL345 accelerometer connected on this header in SPI mode. When I use your standalone driver at **_Samples/IoT-SPI_**, I am able to read the x,y,z sensor values without any issues. Now I want to use your **_Samples/Accelerometer_** to be able to do the same. When I tried running this program, it gives no indication that the sensor was detected.

Could you please give me some ideas how I should use generic classes like Accelerometer, Barometer, Compass etc to read sensors connected on SPI, I2C headers.

Thanks in advance!
Arun

**Comment by oldnewthing** [comment]
This appears to be a question about creating a custom accelerometer on IoT, which is not within the scope of the current samples. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
