### ISSUE TITLE
Treeview.ScrollIntoView does not work for me

### ISSUE THREAD

**Issue by pierresa** [Microsoft/Windows-universal-samples#572]
I programmatically modify a node. That works. I am able to expand it. Event to change some of its UI elements. When I call ScrollIntoView of the item nothing happens: if the item is out of view it is modified correctly but is not moved into view.

previous treeview had an .ensurevisibility method, this does not exist either.

what am I missing?

**Comment by oldnewthing** [comment]
The issue you are running into appears to be with your own application, not with a sample. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.

**Comment by pierresa** [comment]
Well ... not sure: as far as I understand "treeview" is not a supported control, but a custom control defined in sample

or am I missing something?

**Comment by oldnewthing** [comment]
Oh, sorry. I didn't realize that you were talking about the TreeView control provided in the sample. When you wrote "previous treeview" I assumed you were talking about some other TreeView.

**Comment by oldnewthing** [comment]
I've asked the feature team to investigate.

**Comment by pierresa** [comment]
I do not know if they investigated/fixed it but

**Comment by pierresa** [comment]
I do not know if the investigated and fix it ; anyway I found a way to make it work using something like:
 tree?.ScrollIntoView(node, ScrollIntoViewAlignment.Leading);
