### ISSUE TITLE
LyncClient.GetClient of Lync 2013 SDK is failing as Universal Windows Platform has no support for .Net Remoting

### ISSUE THREAD

**Issue by frajos100** [Microsoft/Windows-universal-samples#575]
LyncClient.GetClient of Lync 2013 SDK is failing as Universal Windows Platform has no support for .Net Remoting. Is there a workaround in Unversal Windows Applications to get the LyncClient object?

**Comment by oldnewthing** [comment]
The issue you are running into is not about a sample. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
