### ISSUE TITLE
CameraStarterKit crash when recording and minimizing the application

### ISSUE THREAD

**Issue by rolandsmeenk** [Microsoft/Windows-universal-samples#576]
When recording a video in the CameraStarterKit app (C#) and then minimizing the app a crash occurs. It looks like MediaCapture is already switched to pause state when the _mediaCapture.StopRecordAsync() is called.

This results in the MediaCapture.Failed event handler to be invoked and eventually results in the termination of the app.
MediaCapture_Failed: (0xC00D3E82) A media source cannot go from the stopped state to the paused state.

**Comment by TrevorDev** [comment]
I reproduced this issue with the public sample. It appears to already be fixed in an internal version which will be pushed to public in the near future.

**Comment by oldnewthing** [comment]
Many updates have occurred in the meantime, presumably this among them.
