### ISSUE TITLE
Sample available for a custom WebAccountProvider?

### ISSUE THREAD

**Issue by fubar-coder** [Microsoft/Windows-universal-samples#577]
There are samples that show how someone can use the `WebAuthenticationCoreManager` to find `WebAccountProvider`s. Is there a sample that shows how to develop your own `WebAccountProvider`?

**Comment by shigasumi** [comment]
Is there any answer to this? I have the same request, and there seems to be literally zero information on how one can actually implement a custom WebAccountProvider, which can work with WebAuthenticationCoreManager, use WebTokenRequest to provision tokens and produce WebAccount instances to populate AccountsSettingsPane. Is this even supported in UWP or the only actually supported scenario is https://login.microsoft.com?

**Comment by oldnewthing** [comment]
I created an item on the team's backlog for this request.

**Comment by waynebaby** [comment]
Just asking, is this still not updated?

**Comment by michael-hawker** [comment]
Last status was posted in #911, I guess something is missing from https://github.com/Microsoft/Windows-universal-samples/tree/main/Samples/WebAccountManagement?
