### ISSUE TITLE
CameraStarterKit in WPF

### ISSUE THREAD

**Issue by Maxima078** [Microsoft/Windows-universal-samples#579]
Hi,

Is there a way to use CamaraStarterKit in WPF ? I could read some UWP API could be used in desktop (WPF) application by editing csproj file and adding the correct runtime dll. Is it safe ? Is it possible for the camera ? The built-in camera ui seems to be my best shot for my needs (I want to take pictures with the flash controller enabled).

Thanks for any hints.

Max.

**Comment by oldnewthing** [comment]
The issue you are running into is not a problem with a sample but is rather a question about how to adapt the sample to your scenario. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
