### ISSUE TITLE
Clock stretching for IoT-I2C

### ISSUE THREAD

**Issue by andyfung** [Microsoft/Windows-universal-samples#580]
I ran the sample IoT-I2C on Raspberry Pi 2 as a master. I used the Read() function to read back data from slave. My slave sometimes is not able to respond quick enough for Read() and it hold the clock low until Rasp got an timeout error. Is there any solution on Rasp such as clock stretching available? Thanks.

**Comment by oldnewthing** [comment]
The issue you are running into is a hardware issue, not a samples issue. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
