### ISSUE TITLE
Midi sample doesn't work on Xbox One.

### ISSUE THREAD

**Issue by Swifter** [Microsoft/Windows-universal-samples#581]
The Midi sample for enumerating devices and sending/receiving midi messages doesn't seem to be able to detect any USB Midi keyboards connected to Xbox One.

The software appears to work, and the midiInputQueryString received fromi MidiInPort.GetDeviceSelector() is 

System.Devices.InterfaceClassGuid:="{504BE32C-CCF6-4D2C-B73F-6F8B3747E22B}" AND System.Devices.InterfaceEnabled:=System.StructuredQueryType.Boolean#True

but the subsequent call to DeviceInformation.FindAllAsync(midiInputQueryString) returns nothing, even though I've tried it with multiple USB Midi keyboards.

What gives?  This is a showstopper for my project.  No Midi connectivity, no Xbox app.

**Comment by oldnewthing** [comment]
According to [UWP features that aren't yet supported on Xbox](https://msdn.microsoft.com/library/windows/apps/mt693377), "device enumeration APIs are not supported." According to [Known issues with UWP on Xbox Developer Program](https://docs.microsoft.com/en-us/windows/uwp/xbox-apps/known-issues), "If you find issues with other APIs, please report them on [the forums](https://go.microsoft.com/fwlink/?linkid=839446)."
