### ISSUE TITLE
How to save/download stream live m3u8

### ISSUE THREAD

**Issue by iamstudentVN** [Microsoft/Windows-universal-samples#582]
I have link stream live and i want save/download it as a video file. how to do it?

**Comment by oldnewthing** [comment]
The issue you are running into is not about a sample. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.

**Comment by aarononeal** [comment]
As a hint, it depends on the format of the live stream. But generally you can use the URI with an API like HttpClient or BackgroundDownloader to read the stream and save it to one or more StorageFiles. Keep in mind some content is encrypted and will not be playable if downloaded.

**Comment by aarononeal** [comment]
Also, m3u8 is a playlist so first you have to download that file and parse it to find the URIs of the linked content.
