### ISSUE TITLE
MIDI sample

### ISSUE THREAD

**Issue by bllittle** [Microsoft/Windows-universal-samples#583]
trying to debug the MIDI samples, I get the following error: 
Severity	Code	Description	Project	File	Line	Suppression State
Error		DEP6200 : Bootstrapping failed. Device cannot be found. 0x89731810: Deployment failed because no Windows Phone was detected. Make sure a phone is connected and powered on.	MIDI			

Why would a MIDI sample be looking for a Windows Phone? 

I've found some recommendations and tried downloading an updated emulator to have something running, but nothing has worked so far. 

Thank you

**Comment by oldnewthing** [comment]
You probably have your CPU architecture set to ARM in the build configuration. Your PC doesn't support ARM, so it needs to deploy to something that does. Change it to x86
