### ISSUE TITLE
Face Detection Sample - camera rotation question

### ISSUE THREAD

**Issue by Liero** [Microsoft/Windows-universal-samples#584]
In the Basic Camera Sample you use CameraRotationHelper class.

Specifically:

    /// <summary>
    /// Uses the current device orientation in space and page orientation on the screen to calculate the rotation
    /// transformation to apply to the controls
    /// </summary>
    private void UpdateButtonOrientation()
    {
        // Rotate the buttons in the UI to match the rotation of the device
        var angle = CameraRotationHelper.ConvertSimpleOrientationToClockwiseDegrees(_rotationHelper.GetUIOrientation());
        var transform = new RotateTransform { Angle = angle };

        PhotoButton.RenderTransform = transform;
        VideoButton.RenderTransform = transform;
     }

and 

    /// <summary>
    /// Gets the current orientation of the UI in relation to the device (when AutoRotationPreferences cannot be honored) and applies a corrective rotation to the preview
    /// </summary>
    private async Task SetPreviewRotationAsync()
    {
        // Only need to update the orientation if the camera is mounted on the device
        if (_externalCamera) return;

        // Add rotation metadata to the preview stream to make sure the aspect ratio / dimensions match when rendering and getting preview frames
        var rotation = _rotationHelper.GetCameraPreviewOrientation();
        var props = _mediaCapture.VideoDeviceController.GetMediaStreamProperties(MediaStreamType.VideoPreview);
        props.Properties.Add(RotationKey, CameraRotationHelper.ConvertSimpleOrientationToClockwiseDegrees(rotation));
        await _mediaCapture.SetEncodingPropertiesAsync(MediaStreamType.VideoPreview, props, null);
    }

However, in CameraFaceDetection sample you use DisplayOrientation only.

In order to calculate the rotation of FaceBoundingBoxes shouldn't you use  `_rotationHelper.GetCameraPreviewOrientation` in CameraFaceDetection.GetCameraPreviewOrientation() as well?

**Comment by oldnewthing** [comment]
I checked with the feature team, and you are correct. The other samples haven't yet been updated to use CameraRotationHelper. This is now on their backlog. Thanks for reporting it.

**Comment by Liero** [comment]
One more thing. I've refactored this sample using TransformGroup. I have created helper class that calculates GeneralTransform (simmilar to FrameworkElement.TransformToAncestor) which is then used to transform DetectedFaces bounds into bounds relative to UI element. I can share it. Imho, it makes it much easier to read and to use

**Comment by TrevorDev** [comment]
Thanks Liero. Please do share it so it can be looked at when updating this sample.

**Comment by Liero** [comment]
private async void FaceDetectionEffect_FaceDetected(FaceDetectionEffect sender, FaceDetectedEventArgs args)
    {
        await Dispatcher.RunAsync(CoreDispatcherPriority.High, () =>
        {

            var transform = _faceHighlightingHelper.TransformCameraToPreviewElement(
                previewResolution: new Size(_videoPreviewProps.Width, _videoPreviewProps.Height),
                renderSize: PART_CaptureElement.RenderSize,
                isMirroringPreview: _rotationHelper.ShouldMirrorPreview(),
                cameraRotation: _rotationHelper.GetCameraPreviewOrientation());

            _faceHighlightingHelper.HighlightDetectedFaces(args.ResultFrame.DetectedFaces, PART_FacesCanvas, transform);
        });
    }

**Comment by Liero** [comment]
public class FaceHighlightingHelper
    {
        public DataTemplate BoundingBoxTemplate { get; set; }

        /// <summary>
        /// Iterates over all detected faces and draw bounds on the canvas
        /// </summary>
        /// <param name="detectedFaces"></param>
        /// <param name="facesCanvas"></param>
        /// <param name="cameraToPreviewElementTransform"></param>
        /// <returns></returns>
        public void HighlightDetectedFaces(IReadOnlyList<DetectedFace> detectedFaces, Canvas facesCanvas, GeneralTransform cameraToPreviewElementTransform)
        {
            // For each detected face
            for (int i = 0; i < detectedFaces.Count; i++)
            {
                var detectedFace = detectedFaces[i].FaceBox;
                Rect detectedFaceRect = new Rect(detectedFace.X, detectedFace.Y, detectedFace.Width, detectedFace.Height);

                //calculate position in UI
                Rect uiFaceRect = cameraToPreviewElementTransform.TransformBounds(detectedFaceRect);

                //create the UI element
                FrameworkElement faceBoundingBox;
                if (facesCanvas.Children.Count > i)
                {
                    faceBoundingBox = (FrameworkElement)facesCanvas.Children[i];
                }
                else
                {
                    faceBoundingBox = CreateBoundingBoxElement(detectedFace, uiFaceRect, i);
                    facesCanvas.Children.Add(faceBoundingBox);
                }
                UpdateBoundingBox(faceBoundingBox, detectedFace, uiFaceRect, i);
               
            }
            
            while(facesCanvas.Children.Count > detectedFaces.Count)
            {
                facesCanvas.Children.RemoveAt(facesCanvas.Children.Count - 1);
            }
        }

        /// <summary>Size and position will be overrided</summary>
        /// <param name="detectedFace">Detected face ui video stream</param>
        /// <param name="boundingBox">Bounds with transformations like rotation and scale applied</param>
        protected virtual FrameworkElement CreateBoundingBoxElement(BitmapBounds detectedFace, Rect boundingBox, int i)
        {
            FrameworkElement boundingBoxElement;
            if (BoundingBoxTemplate != null)
            {
                boundingBoxElement = (FrameworkElement)BoundingBoxTemplate.LoadContent();
            }
            boundingBoxElement = new Rectangle
            {
                StrokeThickness = 2,
                Stroke = new SolidColorBrush(Colors.DeepSkyBlue)
            };
            boundingBoxElement.DataContext = detectedFace;


            return boundingBoxElement;
        }

        protected virtual void UpdateBoundingBox(FrameworkElement boundingBoxElement, BitmapBounds detectedFace, Rect boundingBox, int i)
        {
            //update position and size
            boundingBoxElement.Height = boundingBox.Height;
            boundingBoxElement.Width = boundingBox.Width;
            Canvas.SetLeft(boundingBoxElement, boundingBox.X);
            Canvas.SetTop(boundingBoxElement, boundingBox.Y);

            if (boundingBoxElement is Rectangle)
            {
                ((Rectangle)boundingBoxElement).Stroke = i == 0 ? new SolidColorBrush(Colors.DeepSkyBlue) : new SolidColorBrush(Colors.LightSkyBlue);
            }
        }



        /// <summary>
        /// Applies rotation, mirroring and scale (letterboxing) so you can transform detected faces' bounds into coordinates relative to UI element
        /// </summary>
        /// <param name="previewResolution">see VideoEncodingProperties</param>
        /// <param name="renderSize">RenderSize of the CaptureElement</param>
        /// <param name="isMirroringPreview">Front camera is mirroring by default</param>
        /// <param name="cameraRotation">orientation of the display relative to camera</param>
        /// <param name="isExternalCamera">Rotation is not applied to external camera</param>
        public GeneralTransform TransformCameraToPreviewElement(Size previewResolution, Size renderSize, bool isMirroringPreview, SimpleOrientation cameraRotation)
        {
            var rotationDegrees = CameraRotationHelper.ConvertSimpleOrientationToClockwiseDegrees(cameraRotation);

            //source size with respect to display orientation
            var rotatedResolution = rotationDegrees % 180 == 0 ? previewResolution : new Size(previewResolution.Height, previewResolution.Width);

            // Get the rectangle that is occupied by the actual video feed (if aspect ratio of video is different from aspect ration of CaptureElement)
            var innerRect = GetInscribedRect(rotatedResolution, renderSize);

            var transform = new TransformGroup();
            if (isMirroringPreview)
            {
                transform.Children.Add(new ScaleTransform
                {
                    CenterX = previewResolution.Width / 2,
                    CenterY = previewResolution.Height / 2,
                    ScaleX = -1,
                });
                
                // The rotation direction needs to be inverted if the preview is being mirrored
                rotationDegrees = (360 - rotationDegrees) % 360;
            }
            if (rotationDegrees != 0)
            {
                //rotate
                double translateX = rotationDegrees % 180 == 0 ? 0 : rotatedResolution.Width - rotatedResolution.Height / 2;
                double translateY = translateX;
                var rotate = new CompositeTransform
                {
                    Rotation = rotationDegrees,
                    CenterX = rotatedResolution.Width / 2,
                    CenterY = rotatedResolution.Height / 2,
                };
                transform.Children.Add(rotate);
                
                //and move TopLeft edge to (0; 0).
                var adjustPostition = transform.TransformBounds(new Rect(0, 0, previewResolution.Width, previewResolution.Height));
                rotate.TranslateX = -adjustPostition.X;
                rotate.TranslateY = -adjustPostition.Y;
            }

            //fit into the preview rect
            transform.Children.Add(new CompositeTransform
            {
                ScaleX = innerRect.Width / rotatedResolution.Width,
                ScaleY = innerRect.Height / rotatedResolution.Height,
                TranslateX = innerRect.X,
                TranslateY = innerRect.Y,
            });



            return transform;
        }

        /// <summary>
        /// calculates area of the inscribed rectangle with the same aspect ratio as originalSize (see letterboxing)
        /// see http://i.imgur.com/kAbRKvl.png
        /// </summary>
        /// <param name="originalSize">determines aspect ratio of the inscribed rectangle</param>
        /// <param name="sizeToFit">determines size of the rectangle in which the result should be inscribed</param>
        public Rect GetInscribedRect(Size originalSize, Size sizeToFit)
        {
            var result = new Rect();

            // Start by assuming the preview display area in the control spans the entire width and height both (this is corrected in the next if for the necessary dimension)
            result.Width = sizeToFit.Width;
            result.Height = sizeToFit.Height;

            var originalAspectRatio = originalSize.Width / originalSize.Height;
            var newAspectRatio = sizeToFit.Width / sizeToFit.Height;

            // If UI is "wider" than preview, letterboxing will be on the sides
            if ((newAspectRatio > originalAspectRatio))
            {
                var scale = sizeToFit.Height / originalSize.Height;
                var scaledWidth = originalSize.Width * scale;

                result.X = (sizeToFit.Width - scaledWidth) / 2.0;
                result.Width = scaledWidth;
            }
            else // Preview stream is "wider" than UI, so letterboxing will be on the top+bottom
            {
                var scale = sizeToFit.Width / originalSize.Width;
                var scaledHeight = originalSize.Height * scale;

                result.Y = (sizeToFit.Height - scaledHeight) / 2.0;
                result.Height = scaledHeight;
            }

            return result;
        }

    }

**Comment by Liero** [comment]
Also, I noticed, that CameraRotationHelper probably causes memory leak by subscribing to      `_orientationSensor.OrientationChanged` and `_displayInformation.OrientationChanged`. However, it depends on details that are hidden from me, for example, whether `SimpleOrientationSensor.GetDefault()` returns the same instance when calling multiple time, or whether the events are weak or no.
