### ISSUE TITLE
MobileBroadband, SmsSendAndReceive  in Windows IoT

### ISSUE THREAD

**Issue by Seriga** [Microsoft/Windows-universal-samples#585]
Hello.

Windows IoT 15026; 
Raspberry Pi 3;
4G Modem: Vodafone (Huawei) K5150 (https://developer.microsoft.com/ru- ru/windows/iot/docs/hardwarecompatlist);
Visual Studio 2015;

**“MobileBroadband”**
1) Mobile Broadband Device 	- works.
2) Network Account Watcher 	- works.
3) Connection UI 			- not working. And understandably so.
4) Get Connection Profiles	- not working. "Error:Element not found. Exception from HRESULT: 0x80070490"
var ConnectionProfiles = mobileBroadbandAccount.GetConnectionProfiles(); - exception

5) Modem information (New)	- works.
6) Device Services (New)	- works.
7) SIM Card (New) 			- not working. "Error: The request is not supported. (Exception from HRESULT: 0x80070032)"

**“SmsSendAndReceive”**
SMS sending works fine, but does not accept SMS.
Register a background task is successful: "Registered SMS background task"

**Comment by oldnewthing** [comment]
I've asked the feature team to investigate.

**Comment by oldnewthing** [comment]
Feature team has responded:

please collect wwan_dbg logs, to help have a quick look. 

netsh trace start wwan_dbg persist=yes
repro scenario
netsh trace stop  

To investigate any further we will need the device, and image details.

**Comment by oldnewthing** [comment]
Let us know when you have the log files.
