### ISSUE TITLE
MapTapped is always returning a positive Longitude

### ISSUE THREAD

**Issue by BrettEzra** [Microsoft/Windows-universal-samples#586]
This is the sample code:        

private void MyMap_MapTapped(Windows.UI.Xaml.Controls.Maps.MapControl sender, Windows.UI.Xaml.Controls.Maps.MapInputEventArgs args)
        {
            var tappedGeoPosition = args.Location.Position;
            string status = "MapTapped at \nLatitude:" + tappedGeoPosition.Latitude + "\nLongitude: " + tappedGeoPosition.Longitude;
            rootPage.NotifyUser( status, NotifyType.StatusMessage);
        }

This is my code:

        private void TargetMap_MapTapped(MapControl sender, MapInputEventArgs args)
        {
            TargetMap.MapElements.Remove(TargetMapIcon);
            
            TargetMap.MapElements.Add(TargetMapIcon);
            var Lat = args.Location.Position.Latitude;
            var Lon = args.Location.Position.Longitude;

            TargetMapIcon.Title = Lat + ", " + Lon;
            BasicGeoposition TargetPosition = new BasicGeoposition() { Latitude = Lat, Longitude = Lon };
            Geopoint TargetPoint = new Geopoint(TargetPosition);
            //TargetMap.Center = TargetPoint;
            TargetMapIcon.Location = TargetPoint;
        }

Both scenarios are only returning positive values for Lat and Long no matter where I tap.. This has got to be a bug. Anyone?

**Comment by oldnewthing** [comment]
I cannot repro. I clicked on Brasilia, Brazil, and the output is
![capture](https://user-images.githubusercontent.com/12550607/32253434-2ecc1b9e-be58-11e7-9cd3-c939be8ce788.JPG)

Both latitude and longitude are negative.
