### ISSUE TITLE
Sound not playing in uwp Desktop

### ISSUE THREAD

**Issue by tonyyyrocks39** [Microsoft/Windows-universal-samples#587]
I am using insider build 15031.Mediaelement Sound plays in emulators but not in desktop.
As per suggestions ,If I change package name more than 20 characters it works for first time,but second time it doesnot work.Please help....

**Comment by tonyyyrocks39** [comment]
is there somebody who is looking into this issue??

**Comment by aarononeal** [comment]
Yes, I've inquired with the team, but it was a weekend and a holiday here.

**Comment by aarononeal** [comment]
Also, this support channel is for sample issues only, and the issue you reported would be an OS bug. My team handles background audio so I'll take it from here, but in the future you can open a support case directly with our Developer Support team.

- Visit http://aka.ms/storesupport and sign-in with your Microsoft account
- Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.

**Comment by aarononeal** [comment]
Can you elaborate, are you able to reproduce this with one of our unmodified samples? I'll pass that info along if so.

**Comment by tonyyyrocks39** [comment]
Thanks for replying.What I need to reproduce?Its very simple,If you use the media element in the latest insider build 15031,Mediaelement will play but sound will not come specifically in desktop,It works in emulator.Also I have seen your reply to one in one of the issue..you suggested to increase package size to more than 20 characters.I did so,Surprisingly it worked ,but when I open the app second time,Same thing it does not work.Please help urgently..My app is in live.If you want to test you can download also-
https://www.microsoft.com/en-us/store/p/yplayer/9n2j6s86znnr


If you open the app for first time,It will work as usual,but second time,it will not work(Please make sure you are using 15031 build as I have not tested with other build).


Thanks & Regards,
Tony

**Comment by tonyyyrocks39** [comment]
Hi @aarononeal -Did you get time to look into this or do you need any other thing from my side

**Comment by aarononeal** [comment]
Thank you, but I still need more information.

Are you not hearing audio in the foreground or just when you send the app to the background?

MediaElement does not fully support background audio and you should be using MediaPlayerElement per the [BackgroundMediaPlayback ](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/BackgroundMediaPlayback) sample.

**Comment by aarononeal** [comment]
Also, have you specified any AudioCategory?

**Comment by aarononeal** [comment]
The team has investigated with newer builds and the app is playing audio correctly in the foreground. The issue you experienced may have been a temporary regression in 15031 or something specific to your installation. If you continue to experience an issue with newer builds, previously released OS versions, or other devices, you can open a support case directly with our Developer Support team.

- Visit http://aka.ms/storesupport and sign-in with your Microsoft account
- Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.

**Comment by tonyyyrocks39** [comment]
Ok..I will try in other builds as well.Have you tried to play in your system  the above app I have provided.
Could you please tell whether sound is playing in your system(please open 3,4 times and play)
