### ISSUE TITLE
POSPrinter.FromIdAsync Not finding USB Epson Printer

### ISSUE THREAD

**Issue by J-Graham** [Microsoft/Windows-universal-samples#588]
I wrote up a detailed post on SO which can be found here:  [http://stackoverflow.com/questions/42381032/uwp-net-posprinter-not-identifying-epson-usb-receipt-printer](http://stackoverflow.com/questions/42381032/uwp-net-posprinter-not-identifying-epson-usb-receipt-printer)  I'm hoping that someone on this repo could possibly help troubleshoot my issue further.

**Comment by oldnewthing** [comment]
As noted in [the answer to your question](http://stackoverflow.com/a/42511434/902497), USB printers are not on [the list of supported devices](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/pos-printer#device-support).
