### ISSUE TITLE
CameraStreamCorrelation sample README incorrectly suggests Hololens

### ISSUE THREAD

**Issue by doublerebel** [Microsoft/Windows-universal-samples#589]
Hello,

The CameraStreamCorrelation README suggests using the Hololens:

> To debug the sample and then run it, follow the steps listed above to connect your developer-unlocked Microsoft HoloLens

I compiled and ran this app on my Hololens in hopes it could magically produce a DepthFrame, but no  depth camera is found.  Would be rad if I am wrong!

Thanks for your work!

**Comment by oldnewthing** [comment]
The feature team informs me that HoloLens currently does not expose the depth camera to UWP apps, so this is expected.

**Comment by Nick287** [comment]
mute the thread

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
