### ISSUE TITLE
Where is the background StreamSocketListener sample?

### ISSUE THREAD

**Issue by Jaedson33** [Microsoft/Windows-universal-samples#590]
I can't find a sample that show how can I use a StreamSocketListener in a background task.

**Comment by DavidGoll** [comment]
Having a StreamSocketListener running in a background task is not a supported scenario. While you can author such a background task, you cannot reliably trigger that task and keep it running. Even if you do manage to get the task triggered, the Background Infrastructure will enforce quotas for CPU and network usage and terminate the task when the quota has been reached.

On the other hand, you can keep a client socket open and listening, even when the app is suspended or terminated. See the [SocketActiviteStreamSocket](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/SocketActivityStreamSocket) sample.

**Comment by Jaedson33** [comment]
So, if the StreamSocketListener dont't works in background, why that implement TransferOwnership?

**Comment by DavidGoll** [comment]
Sorry about that, I forgot it was supported for the listener as well. I'll pass this request on to the team that owns the Socket Broker sample and ask them to add a scenario for StreamSocketListener.

**Comment by Jaedson33** [comment]
Thanks a lot 👍 I really need that to finish my app 😊

**Comment by Jaedson33** [comment]
@DavidGoll : Do you have any idea when this example will be ready?

**Comment by DavidGoll** [comment]
I can't comment on an availability date. You should try to move forward without a sample.

**Comment by Jaedson33** [comment]
So... When you are going to create the example?
