### ISSUE TITLE
Clipboard copy example loses png transparency

### ISSUE THREAD

**Issue by juanpaexpedite** [Microsoft/Windows-universal-samples#591]
In the example of the Clipboard CS
     public sealed partial class CopyImage : Page

When I copy an image with transparency

![example2](https://cloud.githubusercontent.com/assets/5947026/23329787/57c535f6-fb37-11e6-880d-8f2fbf4df8ca.png)

After wherever I paste the png, the image background is black everywhere (Word, gimp, paint).
Why it loses the transparency?

**Comment by oldnewthing** [comment]
The classic desktop clipboard CF_BITMAP format doesn't support alpha, so when the clipboard data moves from UWP to Win32, it loses the alpha channel.
