### ISSUE TITLE
Simple communication example - crashes after few minutes

### ISSUE THREAD

**Issue by navrkald** [Microsoft/Windows-universal-samples#593]
Description:
When transferring video from one device to another app crashes.
When running on Win. Phone, crash happens in few minutes, when running on PC, crash happens approximately after 10 - 15 minutes.

Patch is here:
[fix_empty_poster.zip](https://github.com/Microsoft/Windows-universal-samples/files/803632/fix_empty_poster.zip)

**Comment by navrkald** [comment]
Some feedback:
It will be nice if in this repository will be enabled to push branches, create merge requests and add labels to issues (like mark issue as bug).

**Comment by mcosmin222** [comment]
This is because the sample leaks memory.

**Comment by oldnewthing** [comment]
Thanks for the fix. A simpler version of it will be in the next update.
