### ISSUE TITLE
images to video

### ISSUE THREAD

**Issue by sharathvignesh** [Microsoft/Windows-universal-samples#595]
Hey guys, Kudos to your great work first of all.
I have a small doubt with MediaFoundation,
Is there a way to create a video of pre defined duration from a set of images ? 

For example. say I have 50 images,
can i use those 50 images and create a video of duration 100 seconds ?

**Comment by oldnewthing** [comment]
The issue you are running into is not a problem with a specific sample. You can open a support case with our Developer Support team who can further help with your issue. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
