### ISSUE TITLE
SuspensionManager.SessionStateForFrame()  method explaination 

### ISSUE THREAD

**Issue by shakir820** [Microsoft/Windows-universal-samples#596]
I  am deeply going through all the codes in Cortana  Voice Command sample "Adventure Works". I have a question why u are creating a new Dictionary<String, Object> as an Object of a Dictionary. If u can make me understood that I will be very pleased. 

 `public static Dictionary<String, Object> SessionStateForFrame(Frame frame)
        {
            var frameState = (Dictionary<String, Object>)frame.GetValue(FrameSessionStateProperty);

            if (frameState == null)
            {
                var frameSessionKey = (String)frame.GetValue(FrameSessionStateKeyProperty);
                if (frameSessionKey != null)
                {
                    // Registered frames reflect the corresponding session state
                    if (!_sessionState.ContainsKey(frameSessionKey))
                    {
                        _sessionState[frameSessionKey] = new  Dictionary<String, Object>();
                    }
                    frameState = (Dictionary<String, Object>)_sessionState[frameSessionKey];
                }
                else
                {
                    // Frames that aren't registered have transient state
                    frameState = new Dictionary<String, Object>();
                }
                frame.SetValue(FrameSessionStateProperty, frameState);
            }
            return frameState;
        }`

**Comment by oldnewthing** [comment]
Not sure what your question is. What's wrong with having a dictionary as an object in a dictionary? (You don't want to use the main dictionary directly because it is shared with other clients of the frame.)

**Comment by shakir820** [comment]
Thanks for your answer.
