### ISSUE TITLE
SuspensionManager.SaveFrameNavigationState(Frame frame) method explaination

### ISSUE THREAD

**Issue by shakir820** [Microsoft/Windows-universal-samples#597]
`private static void SaveFrameNavigationState(Frame frame)
        {
            var frameState = SessionStateForFrame(frame);
            frameState["Navigation"] = frame.GetNavigationState();
        }`

Hi, I am confused that in this above method u have declared a local variable which's lifetime is within this method only and this method doesn't return anything.  So, when calling this method in the   `public static async Task SaveAsync()`   method what will it accomplish ? Also what's the reason for saving value into  frameState["Navigation"] ?

**Comment by oldnewthing** [comment]
The local variable is used inside the method. What you're seeing is [standard use of GetNavigationState](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.Frame#Windows_UI_Xaml_Controls_Frame_GetNavigationState). See the [BasicSuspension](http://go.microsoft.com/fwlink/?LinkID=761251) sample for details.
