### ISSUE TITLE
BasicSuspension Sample Debugging Error

### ISSUE THREAD

**Issue by shakir820** [Microsoft/Windows-universal-samples#598]
I was trying to build the sample of Basic Suspension . And I get this debugging error. What should I do now ? And how to do that ? 
![debugging error](https://cloud.githubusercontent.com/assets/20181621/23577273/f470f798-00e4-11e7-85dc-2e983be6589d.PNG)

**Comment by oldnewthing** [comment]
Please provide more information. Which version of the BasicSuspension sample (from which branch?). What version of Visual Studio are you using? What build of the OS are you running it on?

**Comment by shakir820** [comment]
Here you go..............
I am using Windows Insider Preview build 14986. 
Here is the link from where I downloaded the samples.........
[https://github.com/Microsoft/Windows-universal-samples](url)

Here are some photos u may need .......................
![aboutwindows](https://cloud.githubusercontent.com/assets/20181621/23616254/630a74e8-02b3-11e7-853a-4e0083a667a2.PNG)
![debugging error](https://cloud.githubusercontent.com/assets/20181621/23616253/62ac0f70-02b3-11e7-94c1-d6bcd1e05d45.PNG)


And I am using Visual Studio 2015 with latest updates

**Comment by oldnewthing** [comment]
That is a very old Insider build. If you're going to use an Insider build, then please use a current one.
