### ISSUE TITLE
XamlUIBasics : GridView controlpage- text displayed when item is selected is written over "Example 1"

### ISSUE THREAD

**Issue by davefxy** [Microsoft/Windows-universal-samples#599]
XamlUIBasics : GridView controlpage - text displayed when an item is selected is written over "Example 1" code display.
If I follow the example in the ListView controlPage and add Height="400" to the GridView control in the ControlExample "Example1", the text appears below the example code and is readable.
Question: Is there another way to accomplish this without having to set a fixed Height?

**Comment by oldnewthing** [comment]
This is fixed in the new XamlUIBasics sample. For the old sample, the RelativePanel.Below is set incorrectly. It should be below the ExampleAccessories control, not the Example1 control.
