### ISSUE TITLE
Failed to deploy after built with VS2015 CTP 6 & Win10 Preview

### ISSUE THREAD

**Issue by GotCode** [Microsoft/Windows-universal-samples#6]
The alljoynsecureserver sample solution built with VS2015 latest CTP6 running on the latest  win10 Preview (10041) for x86 or Any CPU  - fixing multiples compiler error - missing png (delete reference), App.XAML (change to Application Definition).
when deploy the solution, got 19 errors:
----
Severity	Code	Description	Project	File	Line
Error		Error : DEP0700 : Registration of the app failed. C:\Windows-universal-samples-master\alljoynsecureserver\cs\bin\x86\Debug\AppX\AppxManifest.xml(26,27): error 0x80070003: Cannot install or update package Microsoft.SDKSamples.AllJoynSecureServer.CS_8wekyb3d8bbwe because the splash screen image [C:\Windows-universal-samples-master\alljoynsecureserver\cs\bin\x86\Debug\AppX\Assets\Splash-sdk.png] cannot be located. Verify that the package contains an image that can be used as a splash screen for the application, and that the package manifest points to the correct location in the package where this splash screen image can be found. (0x80073cf6)	AllJoynSecureServer	

Severity	Code	Description	Project	File	Line
Error	CS0103	The name 'StatusBorder' does not exist in the current context	AllJoynSecureServer	C:\Windows-universal-samples-master\alljoynsecureserver\cs\MainPage.xaml.cs	74

**Comment by AdamBraden** [comment]
This has recently been updated to the tools matching VS2015RC.
