### ISSUE TITLE
Can't Get Cortana Samples to Work

### ISSUE THREAD

**Issue by ShiningKnightLight** [Microsoft/Windows-universal-samples#601]
I'm having a difficult time getting the Cortana Universal Windows sample apps to work for AdventureWorks, and also the other examples from docs.microsoft.com like HueLight and FamilyNotes. 

After wrestling with the apps some in Visual Studio 2015 Community I got them to compile finally, the first go round it wanted to give me a lot of "Nuget: Project Not Found" errors when trying to go from Debug to Release/x64. I re-cloned from Git and went straight to building Release/x64 and it worked.

However, with the AdventureWorks app running, Cortana should allow me to say, "Hey Cortana, show my trip to London." It doesn't pull it up though. Is there some other step other than just building and running to get it going with Cortana?

Here's what I want to do, in a nutshell.

I have a lot of receipts from expenses from shopping to track. I want to proactively manage both my own receipt tracking and calories consumed tracking via voice control. 

Why not use Mint or just my bank? The delays in processing transactions won't give me a truly accurate view of my accounts in real-time.

So I should be able to speak verbally, "Hey Cortana, I spent $12.75 on food at a restaurant." Cortana should put that in a database. Later on if I can tap into the same APIs that Mint is using, I'll use that to try and reconcile my bank transactions, so I have a better proactively managed real-time view of my finances.

I should be able to say, "Hey Cortana, I ate a 3 egg omelette" or "Hey Cortana, I just ate a 900 calorie meal" and have it track my calories consumed so that I can get trending on my calorie consumption without going full pencil and paper.

Why not just use existing calorie trackers? Well they're good at tracking calories that you expend on walking or running, but not on calories consumed from the apps I've seen, and none are voice-activated, and I want to do this as a voice activated application because my fingers are starting to get a little bigger and slower for normal typing the more I workout it seems, I'm also spending much more time outdoors and less time indoors these days, so I need solutions that will help better adapt to my needs. How about reps and sets for weightlifting and calisthenics training?

So what I'll need for this is a way to get integers into my Vocal Command Definitions files. However, it looks like it only does enumerated lists. Can Cortana also handle integer or decimal parameters in speech?

**Comment by oldnewthing** [comment]
It looks like you have two questions. One is about getting the sample to work. The other is about expanding the sample into a custom app.

For the second question, you can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.

**Comment by ShiningKnightLight** [comment]
Thank you oldnewthing, I'll get that support case opened as soon as I can.

As to the other question about how to get the voice activation working, are there additional steps that I need to run? 

This attached screenshot is what happens when I run the project and then say, "Hey Cortana, show my trip to London." It looks in the Calendar and doesn't look like it's picking up the VoiceCommandService. I tried both doing a Deploy Solution and just running the app per the instructions on the read me.

![triptolondon](https://cloud.githubusercontent.com/assets/25945156/23672183/71984334-0333-11e7-9315-6b0c6c1d8abd.png)

**Comment by oldnewthing** [comment]
I'll ask a speech person to look into the first problem.

**Comment by ShiningKnightLight** [comment]
Thank you oldnewthing I appreciate your help.

**Comment by ShiningKnightLight** [comment]
You know what? I'm such a goober. I didn't say, "Hey Cortana, show my trip to London in Adventure Works."

Now if I could figure out how to short hand that to not having to say Adventure Works and treating it as a default handler that would be great, but that's a whole separate issue.

**Comment by anpilley** [comment]
Hi,

I'm sorry you're having trouble with the sample. I'll see if i can offer some advice.

First up, saying “Hey Cortana, show my trip to London” isn’t going to match the “Adventure Works” keyword, and isn’t going to launch the app’s code, it’s only going to try a calendar query. Something like saying "Hey Cortana ... <pause for a second or two> "Adventure works show my trip to london" should work better. (The collision between the sample and existing Cortana functionality was a little unfortunate in hindsight when we built the sample)

If it's still not working, and you haven't modified the github sample, check the following:

•	Open Cortana, and type “What can I say?” and check that Adventure Works shows up in the list of apps that have Cortana integration. If it doesn't, ensure that the code that runs "InstallCommandDefinitionsFromStorageFileAsync" in App.xaml.cs completes successfully.
•	Try a text query “Adventure Works show my trip to london” (don’t include punctuation like commas, etc). This will eliminate possible problems with speech input and verify that things are hooked up okay.

If it’s still not working, I can follow up with the feature team.

**Comment by ShiningKnightLight** [comment]
That's funny we said it about the same time. :)

It seems to be working well now, I'll go ahead and close the issue.

**Comment by amaster4000** [comment]
Hello,

I cannot get the Adventure Works sample to work either... the app works just fine when run, but Cortana does not receive any utterances that relate to the program, she simply bing searches queries like: "adventure works show my trip to london" and other examples given in the step-by-step.

Any advice? Using Windows 10 creator edition x64, Visual Studio 2017.
