### ISSUE TITLE
UssdProtocol sample DEP0001: Unexpected Error: -2147009283

### ISSUE THREAD

**Issue by xperiandri** [Microsoft/Windows-universal-samples#604]
When I try to deploy UssdProtocol sample from VS 2017 to my Lumia 929 10.0.14393.726 I receive such error `DEP0001: Unexpected Error: -2147009283`.

Local Device x86 deployment succeeds.

Other samples work fine.

**Comment by xperiandri** [comment]
VS 2015:
```
DEP6400 : Failed to deploy. Make sure another deployment or debugging session is not in progress for the same emulator or device from a different instance of Visual Studio. 0x80131500: DEP6400 : Failed to deploy. Make sure another deployment or debugging session is not in progress for the same emulator or device from a different instance of Visual Studio. 0x8973190E: Error writing file '%FOLDERID_SharedData%\PhoneTools\11.0\CoreCon\bin\edm3.exe'. Error 0x80070020: The process cannot access the file because it is being used by another process.
```

**Comment by oldnewthing** [comment]
This is a problem with Visual Studio, not with the sample. You can open a support case with our Developer Support team:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
