### ISSUE TITLE
NFC Build Issues, VS 2017 (Community)

### ISSUE THREAD

**Issue by Clockwork-Muse** [Microsoft/Windows-universal-samples#605]
Attempting to build the NFC samples fails to compile.
During the first build, it complains:

 > Metadata file 'G:\Windows-universal-samples\Samples\Nfc\ARM\Debug\NfcHceBackgroundTask\NfcHceBackgroundTask.winmd' could not be found

During the second build, it adds a second error:

 > Error	MSB8020	The build tools for v140 (Platform Toolset = 'v140') cannot be found. To build using the v140 build tools, please install v140 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".	

Okay.... (which is strange, since I added the 2015.3 v140 toolset... I assumed that was the same thing?).

Anyways, retargeting like it suggests yields 100+ errors about missing types, stopping the compile.  Plus still the original error.

**Comment by Clockwork-Muse** [comment]
Hmm... Adding the Mobile Extensions for UWP as a reference to the C++ project allows the build to complete successfully.  The underlying cause seems to be a couple of missing assemblies there:

 - Could not locate the assembly "Windows.Devices.SmartCards.SmartCardBackgroundTriggerContract". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	NfcHceBackgroundTask	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets
- Could not locate the assembly "Windows.Devices.SmartCards.SmartCardEmulatorContract". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	NfcHceBackgroundTask	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets

**Comment by oldnewthing** [comment]
Which branch are you building from? Which SDKs do you have installed? (I think this sample uses the 10240 SDK.)

**Comment by Clockwork-Muse** [comment]
I was building from master, of b085a99.
For 10 I only have the 14393 SDK installed, which might be the answer there.

(why can't I get a text copyable list of installed components?  That would be nice...)

**Comment by oldnewthing** [comment]
Yup, that's the reason. The NFC sample hasn't changed since 10240, so it still builds from 10240 SDK. I'm going to be updating all the samples to bring forward all samples to use the SDK that matches their branch (even if they don't use any features from that current branch). That way people don't have to carry old SDKs around just to build old samples.

**Comment by georgeslegros** [comment]
@oldnewthing do you have any ETA for this?
Anyway, thank for willing to do it at all

**Comment by oldnewthing** [comment]
If you have only the 14393 SDK then use the version of the sample from the win10-1607 branch. That one targets 14393. (There might be a bug that it also requires 10240. I'll check it later.)

**Comment by georgeslegros** [comment]
I confirm that is is working fine! Thanks!

**Comment by xinwang1983** [comment]
@oldnewthing I am building the NFC sample with x64 configuration using win10-1607 branch which you suggest to Georgeslegros to deploy to Windows 10 Desktop. 
With SDK version 14393, compilation failed for NfcHceBackgroundTask.
After install additional SDK version 10586(build 10240), compilation is successful.
However, when I try to debug on local machine, it shows error "DEP3321 : To deploy this application, your deployment target should be running Windows Universal Runtime version 10.0.14393.0 or higher. You currently are running version 10.0.10586.839. Please update your OS, or change your deployment target to a device with the appropriate version."
How could I change SDK version on my local machine? Also, for VS2015, will it look for the lowest SDK version used in the project? Thanks!
