### ISSUE TITLE
Samples for KinectV2 audio in UWP

### ISSUE THREAD

**Issue by bigdimboom** [Microsoft/Windows-universal-samples#606]
API examples for the microphones on Kinect?

**Comment by TrevorDev** [comment]
Currently, from UWP's point of view, the Kinect is just a simple microphone. There's no advanced audio support for Kinect in UWP.

You can take a look at the existing microphone related samples here:
[https://github.com/Microsoft/Windows-universal-samples#audio-video-and-camera](https://github.com/Microsoft/Windows-universal-samples#audio-video-and-camera)
