### ISSUE TITLE
ProjectionManager Sample - Resetting Window State on StopProjectingAsync

### ISSUE THREAD

**Issue by hinterlandsupplyco** [Microsoft/Windows-universal-samples#608]
The window state will revert to whatever it was when projection started, when projection ends after a window restore from the task bar.

Repro steps:

1. Run the app and maximize the window.
2. Start Projection from Scenario 1
3. Manually resize the main window.
4. Minimize the main window.
5. Right-click on the minimized main window in the taskbar and choose restore.
6. End projection.
7. The main window will automatically resize back to full screen.

Also posted in MSDN: https://social.msdn.microsoft.com/Forums/windowsapps/en-US/1c5f40fa-20f2-412d-9d50-e5886457f11d/uwpcbug-projectionmanager-stopprojectingasync-resets-windowstate?forum=wpdevelop

**Comment by oldnewthing** [comment]
It appears that you are reporting a problem with Windows itself, not with the sample. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
