### ISSUE TITLE
DatagramSocket can send broadcast packets from a phone, but not from a PC

### ISSUE THREAD

**Issue by RafaelYousuf** [Microsoft/Windows-universal-samples#610]
I have this weird problem with a datagram socket. Basically what I am doing is building a class that allows my app to announce the services it implements and discover other instances on the same network and their services. I use the DatagramSocket class to broadcast a packet to 255.255.255.255 and other apps on the network would respond to it. This works perfectly when the app on the phone is trying to discover the one on desktop. But the app on desktop can't discover the one on my phone. I ran wireshark to monitor the packets and the phone is sending the packets as expected, but the desktop app doesn't send any packets. I am trying to find out if there is a reason why the app fails to send broadcast packets from my desktop but is capable of doing so when it is running from my phone?
I have tested my code with Windows Firewall turned on and off (only firewall I am using).
Devices I have tested this on are:
- Lumia 950XL (Win10 V1607 Build 14393) - can broadcast
- Surface Book (Win10 1607 Build 14393) - can't broadcast
- HP AIO (Win10 1607 Build 14393) - can't broadcast   

Here is the code I am using to broadcast packets:

`            if (this.datagramSocket == null)
            {
                //initialize the datagram object
                this.datagramSocket = new DatagramSocket();

                //handle the message received event
                this.datagramSocket.MessageReceived += DatagramSocket_MessageReceived;

                //bind the datagram to a service name (IE port)
                await this.datagramSocket.BindServiceNameAsync(this.finderPort.ToString());
            }

            //get an output stream to write the ping message to
            using (var outputStream = await this.datagramSocket.GetOutputStreamAsync(new HostName(BroadcastSubnetMask), this.advertiserPort.ToString()))
            {
                using (var writer = new DataWriter(outputStream))
                {
                    writer.WriteString("message");

                    //commit everything to the stream
                    await writer.StoreAsync();
                }
            }`

the 'advertiserPort' and 'finderPort' are predefined as '1994' and '2206' respectively. the 'BroadcastAddress' is 255.255.255.255

the code I wrote above is somewhat based on the DatagramSocket sample provided here which by the way also has the same issue. the sample works as expected when broadcasting from the phone, but fails to broadcast when ran from a PC.

Appreciate any help or guidance you guys can provide. Been trying to solve this problem for a few days now.

Please take a look at the discussions here:

[StackoverFlow](http://stackoverflow.com/questions/42979844/datagramsocket-can-send-broadcast-packets-on-phone-but-not-on-pc?noredirect=1#comment73089320_42979844)

[MSDN Forums](https://social.msdn.microsoft.com/Forums/en-US/6447970e-d70e-4dc0-8d3a-4c0308520f0a/uwpc-datagramsocket-can-send-broadcast-packets-on-phone-but-not-on-pc?forum=wpdevelop)

**Comment by oldnewthing** [comment]
This appears to be a question about the platform, not a question about a sample. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.

**Comment by RafaelYousuf** [comment]
I don't see how paying 499USD to investigate this problem is fair on MS side. Your sample also fails to work on both desktop devices I used, shouldn't this mean you also need to investigate this issue on your side?

**Comment by oldnewthing** [comment]
If the sample doesn't work, then we can address it here. But from my initial reading, it appeared that you were having a problem with your own program, not with the sample. And if the problem turns out to be a problem with the platform, rather than a bug in the sample, then that is also out of scope for the samples repo.

**Comment by RafaelYousuf** [comment]
Turns out that broadcasting to 255.255.255.255 only works on mobile for some reason, but using directed broadcast address such as (192.168.1.255) works on both device families (mobile and pc). weird, needs some explanation.

**Comment by DavidGoll** [comment]
We're tracking this issue now in our internal bug DB. I'll reply again when we have had a chance to investigate.

**Comment by DavidGoll** [comment]
Broadcast packets are at the mercy of router configurations. Your router apparently is blocking broadcast to 255.255.255.255, but not the local IP broadcast address. Multicast is preferred when possible. We will update the sample scenario to include text to warn about this router limitation.

**Comment by RafaelYousuf** [comment]
Hi @DavidGoll, thank you for getting back to us on this issue.
I can confirm that using a local broadcast IP does work on both the PC and mobile. However, broadcasting to 255.255.255.255 was working as expected before an update to Windows 10 which caused the UWP app on PC to fail sending packets to that address on the same router that used to work before.

**Comment by DavidGoll** [comment]
Thanks. I added this note to our internal issue.
