### ISSUE TITLE
Question on Pressure vs InkStroke size

### ISSUE THREAD

**Issue by Ponant** [Microsoft/Windows-universal-samples#611]
I am trying to export some` InkCanvas ` `Strokes` to SVG files and it works fairly ok albeit not being able to account for `Pressure`. Where can I find the function that defines how a stroke varies as a function of pressure, if available in open source?

**Comment by oldnewthing** [comment]
This doesn't appear to be an issue with the samples repo. You can open a support case with our Developer Support team who can further help with your scenario. 
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
