### ISSUE TITLE
Camera Frames Sample Crashes on Windows 10 mobile (slow ring and fast ring).

### ISSUE THREAD

**Issue by dmarjoram** [Microsoft/Windows-universal-samples#612]
MediaFrameSourceGroup.FindAllAsync() returns no results and also MediaCapture.FrameSources has no items.

This was working fine in the Anniversary build. I've updated to VS2017 and also to the latest SDK version with no success.

My UWP apps are now broken for insiders.

**Comment by dmarjoram** [comment]
This is not reproducible on the latest SDK emulator, but on Lumia 950 XL build 15063.

**Comment by TrevorDev** [comment]
I installed build 15063 on a Lumia 950 XL and was not able to reproduce your issue. You can provide additional data to help reproduce this by doing the following on your phone:

1. Open the Feedback Hub app and sign in
2. Create a new feedback item
3. Set feedback type to problem
4. Set category to Hardware, Devices, and Drivers
5. Set subcategory to Device Camera or Webcam
6. At the bottom hit begin monitoring
7. Run the crashing app to reproduce your issue
8. Come back to the feedback app and hit stop monitoring
9. Submit the feedback
10. Post the link to your feedback

Thanks

**Comment by dmarjoram** [comment]
Here are links to the sample application failing in Feedback Hub.

https://aka.ms/Gnmph6
https://aka.ms/Yvw9xr

It is running on a Lumia 950XL (UK) which has been upgraded to 15063.

The sample application was built using the Windows 10 SDK preview from here, downloaded yesterday:
https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewSDK

**Comment by TrevorDev** [comment]
I am not seeing sufficient logs in feedback items you linked to. To be able to retrieve actionable logs on this issue, the feedback needs to be created with the specified category/subcategory and collected monitoring logs as described above.

**Comment by dmarjoram** [comment]
https://aka.ms/jms6vo
https://aka.ms/E8p1cs

**Comment by dmarjoram** [comment]
Created new Windows 10 Anniversary VM
Upgraded OS
Installed VS2017
Installed Preview SDK
Got latest UWP sample Camera Frames from github
Attached 950XL and and started debugging
Clicked "Find and Display all media frame sources"

Exception thrown when calling:
var group = await MediaFrameSourceGroup.FromIdAsync(id);

![unhandledexception](https://cloud.githubusercontent.com/assets/12830675/24429716/23d743a0-140b-11e7-829b-8c25576caca6.PNG)

**Comment by TrevorDev** [comment]
Thanks, I promoted this feedback to an internal bug.

**Comment by dmarjoram** [comment]
Still an issue on 10.0.15063.2

**Comment by oldnewthing** [comment]
This appears to be an OS issue, not a samples issue. As Trevor noted, it is being tracked on the platform side.

**Comment by dmarjoram** [comment]
Is there any link to the platform bug so both my customers and I have visibility of progress?

With the creators update looming for the public I am concerned.

**Comment by TrevorDev** [comment]
I don't have an external link I can share but this is being investigated now. This issue still hasn't been able to be reproduced locally but through investigation it may be related to the DeviceInformation Api.

Could you try running the following code and let me know if it succeeds?
`var infos = await DeviceInformation.FindAllAsync(MediaFrameSourceGroup.GetDeviceSelector());
foreach(var info in infos)
{
    Debug.WriteLine(info.Name);
}`

Thanks

**Comment by dmarjoram** [comment]
Yeah, that seems to be working OK running on the same device. Both cameras are detected. 
![wp_ss_20170404_0001](https://cloud.githubusercontent.com/assets/12830675/24635924/94d8a8c4-18ce-11e7-845b-0afa42c20a78.png)

This also works in the sample and my apps where I enumerate the cameras with:
var allVideoDevices = await DeviceInformation.FindAllAsync(DeviceClass.VideoCapture);

The problem is later on, when trying to find MediaFrameSourceGroups with a call to:
var frameSourceGroups = await MediaFrameSourceGroup.FindAllAsync();

This always returns no items on the 950XL upgraded to the latest fast ring build. I then can't initialize the MediaCapture via SourceGroup.

**Comment by dmarjoram** [comment]
Still an issue on 15204.

Send me more code and I'll run it on the 950XL where it fails for you.

**Comment by dmarjoram** [comment]
Ok, a soft reset on the device has resolved this issue!! I suspect this is due to an upgrade path from Anniversary via a dodgy fast ring build?

Hopefully this will not be an issue for the majority going direct from Anniversary -> Production Creators.
