### ISSUE TITLE
webauthenticatiobroker example.

### ISSUE THREAD

**Issue by tattries** [Microsoft/Windows-universal-samples#618]
Example not does work. Neither Facebook,google or twitter would work with correct values inputed.

**Comment by rgodugu** [comment]
Here are the steps for Twitter scenario
Twitter : 
1 . register your test app at https://apps.twitter.com/ . select create new app .
2. Add app name , description , website (if you don't have it yet , give a place holder eg:   https://placeholder.com ) , call url (this can be any valid url eg: https://placeholder.com . You don't have to  
worry about this if you are only using OAuth authentication . and getting the token ) 
3. once created , go to keys and access tokens tab . copy consumer key and consumer secret .
4. Run the App and select Twitter services . Input key , secret and call back url which you have given while registering the app .

**Comment by rgodugu** [comment]
facebook scenario : 
1  :register the app on developers.facebook.com  . go to the setting page for the app . add the windows phone sid of the app (you can find this in appx manifest file) and the windows store SID (s-1-15-2-2172726392-2931418884-1621631849-1747378197-3111836132-1491618564-589829504) . You can get this by running 

2:  In facebook login tab . select yes for client oauth , web oauth, embedded oauth login . 
3:  Add " https://www.facebook.com/connect/login_success.html"  as valid oauth redirect uris

4: run the sample using the App id and the redirect uri as mentioned above
