### ISSUE TITLE
MapControl children behaviours different in Creators update

### ISSUE THREAD

**Issue by Wietse-0803** [Microsoft/Windows-universal-samples#620]
Please investigate this: https://social.msdn.microsoft.com/Forums/en-US/ab97e870-346c-4e82-8966-4f0c1b952338/uwp-mapcontrol-children-not-fixed-positioned-anymore-after-w10-creators-update?forum=wpdevelop

**Comment by oldnewthing** [comment]
This doesn't appear to be an issue with the sample, but rather an issue with the platform. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
