### ISSUE TITLE
Basic Media Casting

### ISSUE THREAD

**Issue by biosgithub** [Microsoft/Windows-universal-samples#621]
I have a problem. everything works great when the device language is English but when I change language and imposed the Italian language I get an error: Value does not fall within the expected range. any ideas to solve the problem?
I set a try catch to display the error.

scenario3

try
          {
                 
       CastingDevice addedDevice = await CastingDevice.FromIdAsync (args.Id);
         castingDevicesList.Items.Add (addedDevice);
                 }
                 catch
                 {
                    // return me this error: Value does not fall Within the expected range
                 }

**Comment by aarononeal** [comment]
I've filed an internal bug to investigate whether this is a platform or sample issue.

**Comment by aarononeal** [comment]
The team was not able to reproduce this. I am going to mark closed, but if you continue to encounter this error, please file a report through the Feedback Hub app and reference this issue.

Please select the Wireless Display and Casting category and use the monitoring option. This will allow you to reproduce the problem and send a log to us that may help to further diagnose.
