### ISSUE TITLE
wifi scan exception can not be fixed except reboot device

### ISSUE THREAD

**Issue by IvanJLZhang** [Microsoft/Windows-universal-samples#622]
Hi, 
below is my wifi initialize and scan methods:
       //initial adapter method.
        private async Task<bool> _InitializeAdapterAsync()
        {
            var access = await WiFiAdapter.RequestAccessAsync();
            if (access != WiFiAccessStatus.Allowed)
            {
                DoCoMoSystem.WriteLog("Wifi access denied!");
                return false;
            }
            var result = await Windows.Devices.Enumeration.DeviceInformation.FindAllAsync(WiFiAdapter.GetDeviceSelector());
            if (result.Count >= 1)
            {
                _firstAdapter = await WiFiAdapter.FromIdAsync(result[0].Id);
                return true;
            }
            else
            {
                DoCoMoSystem.WriteLog("no wifi adapter!");
                return false;
            }
        }
      //scan method.
        private async Task _WifiScanAsync()
        {
            if (_firstAdapter == null) return;
            try
            {
                _firstAdapter.AvailableNetworksChanged -= _firstAdapter_AvailableNetworksChanged;
                _firstAdapter.AvailableNetworksChanged += _firstAdapter_AvailableNetworksChanged;
                await _firstAdapter.ScanAsync();
            }
            catch (Exception ex)
            {
                DoCoMoSystem.WriteLog("wifi scan exception..." + ex);
            }
        }

my DoCoMosystem app is running on a tablet device, when I turn on the device and idle for nearly 12 hrs, then navigate to wifi scan page, it'll throw exception like below, no matter how many times I retry, exception can not be avoid(reboot device can fix the issue.): 

System.Exception: Operation aborted (Exception from HRESULT: 0x80004004 (E_ABORT))
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at DCMModule.DCMWiFi.<_WifiScanAsync>d__14.MoveNext()'

**Comment by oldnewthing** [comment]
This is not a samples issue. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
