### ISSUE TITLE
C# "Projection" sample is non-working

### ISSUE THREAD

**Issue by sensboston** [Microsoft/Windows-universal-samples#624]
C# "Projection" sample is non-working; can't get projection page on my TV via Microsoft Wireless Adapter. No error or exception thrown but nothing on the TV screen.
BTW, C++ sample is working as expected (and as supposed to be). 

Tested on Microsoft Lumia 950, OS 10.0.14393.1056; app built on Visual Studio 2015, Windows 10 "Creators Update" (PC OS version 10.0.15063.138)

**Comment by oldnewthing** [comment]
I've asked the feature team to investigate.

**Comment by oldnewthing** [comment]
The feature team is unable to reproduce the problem. They've requested that you capture additional traces to help them figure out what is going on.

1. Attach the Phone to the PC via a USB cable and browse to the “Phone\Documents\FieldMedic\CustomProfiles” folder via Explorer (create FieldMedic\CustomProfiles if doesn't exist).
2. Copy the attached Custom-FieldMedic-WFD.etl to the CustomProfiles folder. [FieldMedic-WFD.zip](https://github.com/Microsoft/Windows-universal-samples/files/1598351/FieldMedic-WFD.zip)

3. Start the FieldMedic app
4. Go to the “Advanced” option in FieldMedic and click on “Choose which ETW providers to use” drop-down box.
5. Uncheck everything in the Default Group and select Custom-FieldMedic-WFD.etl in the Custom Group.
6. Start logging by clicking on “Start Logging”, repro the issue and stop logging.
7. Cutom-FieldMedic-WFD.etl will be generated at Phone\Documents\FieldMedic\reports folder. You might have to reconnect the Phone to the PC for Explorer to refresh. Send this back for investigation.

Thanks. I will monitor this thread for activity even though it is closed.
