### ISSUE TITLE
RequestAddFolderAsync() without DirectoryPicker

### ISSUE THREAD

**Issue by NorDroN** [Microsoft/Windows-universal-samples#625]
Hello!
Is it possible to add directory to Windows Libraries without picker?
I've try to use this method RequestAddFolderAsync(), but I see DirectoryPicker.

**Comment by oldnewthing** [comment]
This is a question about the platform, not about the sample. You can open a support case with our Developer Support team who can further help with your question. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
