### ISSUE TITLE
MasterDetailsView Crashes the app when Visibility is set to Collapsed

### ISSUE THREAD

**Issue by ducttape36** [Microsoft/Windows-universal-samples#626]
The MasterDetailsView control crashes the app when Visibility is initially set to Collapsed in XAML or code-behind. If set to Visible you can toggle visibility programmatically once the app is loaded, but you can not have it initially set to Collapsed either in XAML or starting methods like OnNavigatedTo().

**Comment by oldnewthing** [comment]
No sample in this repo has a control called [MasterDetailsView](https://github.com/Microsoft/Windows-universal-samples/search?utf8=%E2%9C%93&q=MasterDetailsView&type=) or Mast[erDetailView](https://github.com/Microsoft/Windows-universal-samples/search?utf8=%E2%9C%93&q=MasterDetailView&type=), so I can't figure out which sample and control you're talking about. Please clarify which sample you're referring to and which line in which XAML file is the one in question where setting Visiblity=Collapsed results in a crash.
