### ISSUE TITLE
stream m3u8 cannt play IP port

### ISSUE THREAD

**Issue by iamstudentVN** [Microsoft/Windows-universal-samples#627]
format links: b.b.b.b:xxxx/ cannot play

**Comment by aarononeal** [comment]
You must provide a scheme. For example:
http://b.b.b.b:xxxx/

**Comment by iamstudentVN** [comment]
I can't play links: http://b.b.b.b:xxxx/ but http://c.c.c.c is work

**Comment by aarononeal** [comment]
It's working fine with a local server here. You haven't provided enough information to troubleshoot. Please explain the details of your test or provide a sample app, link, and error message if you receive one.

**Comment by aarononeal** [comment]
Do you mean you are trying to play a .ts file directly or a .ts is linked inside your .m3u8?

**Comment by iamstudentVN** [comment]
yeah I trying to play a .ts file directly

**Comment by iamstudentVN** [comment]
@aarononeal I also have video related issues here https://github.com/Microsoft/Windows-universal-samples/issues/546

**Comment by aarononeal** [comment]
Can you describe your scenario? In the other issue you mentioned you are using MediaStreamSource. Why are you using that instead of our AdaptiveMediaSource? Do you see the same problem on phone with other sources?

**Comment by iamstudentVN** [comment]
@aarononeal beaucase AdaptiveMediaSource stream this file, so I use ffmpeg stream it but not smooth on phone (on PC is fine)
![image](https://cloud.githubusercontent.com/assets/12800744/25234804/656d9c74-260d-11e7-9fad-80f2380ec1e7.png)

**Comment by iamstudentVN** [comment]
I can send link to your email?
