### ISSUE TITLE
TitleBar Sample Issues

### ISSUE THREAD

**Issue by anup-das** [Microsoft/Windows-universal-samples#630]
#1 For Scenario 2 when Enable controls in title bar is selected it is difficult to resize the app window from top of the control region.  The mouse pointer does not often change to dual headed shape. It does sometimes.  If the mouse pointer is moved from outside the window towards the control then most likely the mouse pointer does not change shape and so we cannot resize window from that portion of the frame window. 

#2. UI state is inconsistent with application state for "Extend view into title bar"
Repro Steps
1. Launch the app and go to scenario 2. Select Extend view into title bar
2. close the app
3. Re-Launch the app. Notice the view is extended into the title bar. Go to Scenario 2 and inspect the state of checkbox for "extend view into title bar". It should be checked but it is unchecked.

**Comment by anup-das** [comment]
#2 - I am using VS 2017 26403.7 on Windows 10 Creator's Update 15063.138 build (64 bit)
![inconsistent state](https://cloud.githubusercontent.com/assets/26622362/25154866/082f58bc-24b0-11e7-907e-772ebbefc79c.png)

**Comment by oldnewthing** [comment]
#1 is a platform issue, not a sample issue. #2 is a sample bug. I'll see if I can get a fix in.

**Comment by oldnewthing** [comment]
Upon closer inspection #2 is also a platform issue. The sample is report the value of `ExtendViewIntoTitleBar` and the value is being reported by the platform as `false`, which is why the box is unchecked. I will file a platform bug.
