### ISSUE TITLE
How to play link video with request header ?

### ISSUE THREAD

**Issue by iamstudentVN** [Microsoft/Windows-universal-samples#631]
I have a link video need add header to play. How does it work on my app?
Thanks

**Comment by oldnewthing** [comment]
This appears to be a question about the platform, not a question about a sample. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.

**Comment by aarononeal** [comment]
It depends on the API you are using to play your video. If you use an AdaptiveMediaSource you can psss in HttpClient with headers or I believe there's an API on the source that accepts headers. We don't have an option yet for other sources other than to implement your own source with MediaStreamSource or MseStreamSource.
