### ISSUE TITLE
Latest VS 2017 required ?

### ISSUE THREAD

**Issue by merojo** [Microsoft/Windows-universal-samples#633]
I downloaded the latest code , from recent commit   f4e92d4 

VS 2015 Update 3 no longer works for e.g., "Camera Starter Kit " . The CSPROJ says "update required".
I reverted back to a previous commit , no problems with VS 2015 Update 3.

Is VS 2017 required ? if so , please update the readme , or create a separate branch.
I've not been successful in updating to VS 2017 and so will keep VS 2015 for legacy projects.

**Comment by oldnewthing** [comment]
Yes, starting with version 1703, the samples use VS 2017. I haven't had a chance to update the README or write the changelog yet. Sorry. Will update the READMEs at the next update.

**Comment by merojo** [comment]
Wonderful, thanks, mark as resolved.
