### ISSUE TITLE
Personalization Sample (C#) Returns error and fails when attempting to set Lockscreen Image

### ISSUE THREAD

**Issue by killerrin** [Microsoft/Windows-universal-samples#634]
The personalization sample is throwing an exception with error message: "Invalid image selected or error opening stream." when selecting an image from the FilePicker.

**Attempted File**
Image File: http://i.imgur.com/cLhoNuY.jpg
File Location*: Pictures Folder(Root)
*Image was on Hard Drive initially and it didn't work. I attempted uploading to imgur and redownloading then attempted selecting again and it continued to not work. I also attempted from subfolders, the Downloads Folder and even putting it within the apps Local Storage and with several other images as well

**Visual Studio** (Attempted running under Admin to force the spawned off Debug Process to run in Admin as well)
Edition: Visual Studio Enterprise 2017
Version 15.1 (26403.0) Release
Microsoft .NET Framework Version: 4.7.02046

**Operating System**
Edition: Windows 10 Pro
Version: 1703
OS Build: 15063.138

**Exception Details**
Exception is thrown at Line 62 `await LockScreen.SetImageFileAsync(imageFile);`in SetLockScreenImage.xaml.cs

```
Exception thrown: 'System.Exception' in System.Private.CoreLib.ni.dll

'Personalization.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\andre\Downloads\Windows-universal-samples-master\Windows-universal-samples-master\Samples\Personalization\cs\bin\x86\Debug\AppX\System.Diagnostics.StackTrace.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.

Source: System.Private.CoreLib
 Help Link: 
 HResult: -2147024156
 Message: The requested operation requires elevation. (Exception from HRESULT: 0x800702E4)
 StackTrace:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at SDKTemplate.SetLockScreenImage.<PickAndSetButton_Click>d__3.MoveNext()
```

**Comment by oldnewthing** [comment]
I cannot reproduce this problem on build 16299. SetImageFileAsync succeeds and changes my wallpaper.
