### ISSUE TITLE
Microsoft.Windows.UI.Xaml.Common.targets was not found

### ISSUE THREAD

**Issue by Warwick858** [Microsoft/Windows-universal-samples#635]
I downloaded the master zip file, unzipped the entire folder, and followed the instructions on the readme.  Attempted to open the following:
"D:\Downloads\Windows-universal-samples-master\Windows-universal-samples-master\Samples\XamlNavigation\cs\NavigationMenu.sln"
When I received the following error:

D:\Downloads\Windows-universal-samples-master\Windows-universal-samples-master\Samples\XamlNavigation\cs\NavigationMenu.csproj : error  : 
The imported project "C:\Program Files (x86)\Windows Kits\10\bin\10.0.15063.0\XamlCompiler\Microsoft.Windows.UI.Xaml.Common.targets" was not found. 
Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  
C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v14.0\8.21\Microsoft.Windows.UI.Xaml.Common.targets

(I am running VS2015 Enterprise on a Windows 10 Education machine).
When I follow the first file path related to the error, the highest SDK I have under Windows Kits\10\bin is 10.0.14393.0.  How do I get 10.0.15063.0?

After a little research, I tried the commonly mentioned workaround of creating a new project and navigating to Windows 8.1, where it prompted me to install additional SDKs.  But still, same error.

Is this a result of the samples being updated to coincide with changes from the Creators Update?
I have not pulled this update yet as there's lots of buzz about potential issues.

Thanks for your help.
I'm craving a solution as I am currently working on my first UWP app, and this stuff is incredible!! :)

**Comment by oldnewthing** [comment]
All samples in the master branch now require VS2017. I haven't updated the READMEs yet. Sorry for leading you astray.

**Comment by oldnewthing** [comment]
README files have been updated to make it clearer that the samples require VS 2017.

**Comment by shineyruan** [comment]
I used VS2017 and the same error occurred. Then what's wrong with my VS2017? Should I install some C# development kit in advance?

**Comment by vuhuy** [comment]
Run the Visual Studio Installer to update your VS2017 installation. You can find the shortcut in the start menu). Had to do the same for my VS2017 installation. The update installed the 10.0.15063.0 SDK on my system.

**Comment by harrypotter06** [comment]
And now? I have the same issue with VS 2017

**Comment by vuhuy** [comment]
Not sure, but the samples were updated to support the Fall Creators update (build 16299). If you want to target 16299, please install the Fall Creators update on your Windows 10 machine and run the VS2017 installer to install the latest Windows SDK.

**Comment by oldnewthing** [comment]
The `master` branch operates against the current in-market version (as of this writing, the Fall Creators Update, build 16299). If you want samples that run against older versions of Windows, use one of the other branches, each named after the version is supports.
