### ISSUE TITLE
MultipleViews Reworked

### ISSUE THREAD

**Issue by shakir820** [Microsoft/Windows-universal-samples#636]
Hi, Raymond Chen, I am learning to develop UWP apps. I have checked your Multiple Views sample. 
You used Multi Threading keyword "lock". So, I also learned MultiThreading. 
After that I have reworked your sample. In my sample I have cut off the animation and the protocol activation. 
I need you to check my sample if you really think that I need to apply lock keyword in "ViewLifetimeControl" 
class  then please let me know why I need !!  I have run that and found no error. 
Its perfectly ok except animation and protocol activation. 

link:   [https://github.com/shakir820/UWP-Apps-Sample]

**Comment by oldnewthing** [comment]
This is not a question about the samples in this repo. It sounds like you're asking for somebody to review your code.
