### ISSUE TITLE
UWP MIDI SysEx request hangs App and entire MIDI stack.

### ISSUE THREAD

**Issue by Noemata** [Microsoft/Windows-universal-samples#639]
Using the following code:

                    var data = new byte[] { 0xF0, 0x7E, 0x7F, 0x06, 0x01, 0xF7 };

                    midiOutputDevice.SendMessage(new MidiSystemExclusiveMessage(data.AsBuffer()));

This code causes the Win10 Store App to lock up and hang the MIDI stack when executed against any of the Roland gear I have (the entire Roland Boutique line, the entire Roland Aira line, and the Roland A-49 keyboard controller, etc.).

The same request works as expected from a Win 10 Win32 application with the same set of Roland gear.

The same code works as expected for both Win 10 Store and Win32 Apps when using non-Roland gear, such as the Novation Launchpad.  You can try this with the MIDI sample.  I'm guessing the code hangs with any Roland gear that has a native Windows 10 driver.

There appears to be something wrong under the hood with Roland gear and the Win10 Store MIDI API.  I've noticed that for all the Roland gear I have (entire Boutique line and Aira line), a driver is pushed onto the system when the USB device is plugged in.

This problem has completely stalled my ability to release a Windows Store App that is a patch editor / control surface for the above Roland products.

**Comment by oldnewthing** [comment]
This is an issue with the platform, not with the MIDI sample.

**Comment by Noemata** [comment]
You are correct, this is a platform issue, though in this case it does end up affecting the sample because of the degree of platform failure.

If posting this sort of platform issue is inappropriate here, I apologize.  I have noticed other "platform" problems identified in other postings (search for Kinect for examples of these), so I assumed that was ok here.

Once again, I apologize if this is not what is expected here.

**Comment by oldnewthing** [comment]
I tend to leave each feature team to decide whether an issue is a samples issue or a platform issue, because sometimes it's not obvious. (Is there a bug in the sample that prevents it from showing Kinect devices?)

**Comment by Noemata** [comment]
That was the point I was trying to make, the issue raised in other postings were not Kinect sample bugs, but platform bugs, hence why I had the impression that it was ok to post such bugs here and those postings were replied to.

I do understand your focus and will not pester you further with this.  I would appreciate the folks that work on the MIDI stack being made aware of this problem.  It's resolution should have a somewhat urgent status given the significance of the problem.  Crippled MIDI functionality, I would think, would be of critical concern to the folks that work on the MIDI stack.

Thank you for your attention.

**Comment by Noemata** [comment]
I feel it is important to add one more qualifier here for anyone that hits these postings at a later date; the SysEx issue turns out to be entirely a Windows 10 platform problem and has nothing to do with Roland drivers.  In fact, Roland's Windows 10 drivers are some of the best, most stable, most conformant drivers available based on some fairly extensive testing.
