### ISSUE TITLE
WinRT MIDI stack name handling flaw. WinRT MIDI stack is presently unusable.

### ISSUE THREAD

**Issue by Noemata** [Microsoft/Windows-universal-samples#640]
The WinRT MIDI stack appears to have a serious name handling flaw that manifests a number of issues.
Here are a few examples of enumerated device names:

Oxygen 25 [0]
Oxygen 25 [1]
A-01 [0]
A-01 [1]
Launchpad S [0]
Launchpad S [1]
QUAD-CAPTURE (1)
Boutique (1)

The device names that end in [0] are for output, and the device names that end in [1] are for input.

The device names above that end in (1) are for input and output, yes, that little detail is also problematic.

But it gets worse.  Any device that has a consolidated name for input and output, that is, it does not have a [0]/[1] ending to its name, those ending in (1) above, hang the MIDI stack when any given SysEx message is sent to its output port.  The GUI of the associated App also becomes frozen.

I'm speculating; the lock up is probably due to the fact that the MIDI stack has confused itself as to where to send the output due to this naming inconsistency.  So devices that have a consolidated name for input and output hang the MIDI stack when a SysEx message is sent, and the only method of recovery is to sign out or restart.  Closing the UWP apps process does not clear the problem.  Closing an app should always clear up any such problems and not result in a hung IO stack.

Device names should either always be consolidated, that is, there should never be a [0]/[1] ending to the name, or they should always have the separation.

So at present, the WinRT MIDI stack is unusable because of the lock up when sending SysEx messages to devices that have a consolidated name.

Looks like Microsoft needs to have a better testing regiment here.  If Microsoft chooses not to fix the naming issue, that's fine, we can work around the inconsistency.  But the MIDI driver layer has to work with the naming variations correctly.

This problem needs to be resolved ASAP!!!

**Comment by balasiv** [comment]
Thanks. Can you file a bug and collect logs using the Feedback Hub as described in [this post](https://blogs.msdn.microsoft.com/matthew_van_eerde/2016/09/26/report-problems-with-logs-and-suggest-features-with-the-feedback-hub/) and paste the direct link to the item here?

**Comment by Noemata** [comment]
The suggested method of reporting this issue is inappropriate for this particular problem.  I've been down this path before and waited months for resolution using connect.microsoft.com.  I will not be revisiting a bug reporting mechanism measured in weeks and months for a problem that effectively cripples an important aspect of OS functionality.

WinRT MIDI support is effectively broken at present.  You folks need to fix it pronto.  Windows Store is about consumers, not corporate level clients.  Music is a big deal to consumers.  MIDI is a big deal to musicians so I guess Microsoft needs to decide whether they want to be a big deal to both those categories of users in the context of UWP/WinRT/Windows Store.

**Comment by oldnewthing** [comment]
Diagnostic info will be auto-collected by the Feedback Hub, which will help the feature team diagnose the problem. Without that information, it is much more difficult to figure out what is going wrong. I'm closing this issue since it is doesn't appear to be a samples issue. It's a platform issue.

**Comment by Noemata** [comment]
The turn around time for the Feedback Hub is inappropriate in this case because of the severity of the problem.

Perhaps things have changed, my past experiences with Feedback Hub and connect.microsoft.com were rather lack luster in terms of turnaround time.  I simply am not in a position to wait months for this.  It would be faster to just switch to IOS.  And that's the sort of math other developers will do with respect to their MIDI software endeavours hence my attempt at being more emphatic.

UWP MIDI is already in a week position, pushing back on this issue will make it weaker.  This problem needs urgent attention.

I do acknowledge your perspective with respect to sample issues and will not post hear again unless it is directly related to a sample problem.
