### ISSUE TITLE
WebAuthenticationBroker missing something by Google Auth reason.

### ISSUE THREAD

**Issue by dengere** [Microsoft/Windows-universal-samples#643]
https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/WebAuthenticationBroker.

User fill login information but login not completed. This page given. 
Information Turkish. Translated. "Please copy code below, and paste of your app." 

![image](https://cloud.githubusercontent.com/assets/5771761/25661274/a8362674-3018-11e7-8b3a-2d970a0aa182.png)

**Comment by poumason** [comment]
I have the same issue.
I reference the link: [https://github.com/googlesamples/oauth-apps-for-windows/tree/master/OAuthUniversalApp](https://github.com/googlesamples/oauth-apps-for-windows/tree/master/OAuthUniversalApp) .
It was use Protocol and OnActived to handle OAuth flow.

**Comment by dengere** [comment]
I'm really wondering that someone care about issues?
I changed all logic for google login. Open new browse window and redirect my azure service by secret, User login, and redirect service again. And registered... 
App try to get auth code from own servcie... Tragedy!

**Comment by oldnewthing** [comment]
I've asked the team to look at the issue and report back.

**Comment by alexshakurin** [comment]
Any news on Google issue? I started to experience this issue as well.

**Comment by chotikarn** [comment]
i've change this line: 
var endURI = new Windows.Foundation.Uri("https://accounts.google.com/o/oauth2/approval?");
to: 
var endURI = new Windows.Foundation.Uri("https://accounts.google.com/o/oauth2/approval");

**Comment by RafalSkorka** [comment]
I confirm the solution provided by @chotikarn works. Thank you!

**Comment by oneclouddrive** [comment]
@chotikarn solution does work.

**Comment by oldnewthing** [comment]
Thanks for finding the fix. I'll update the sample.
