### ISSUE TITLE
XamlCommanding Scenario 8 is broken on RS2

### ISSUE THREAD

**Issue by chuckries** [Microsoft/Windows-universal-samples#644]
OS Version	10.0.15063 Build 15063

1. Open `Samples\XamlCommanding\cs\Commanding.sln` in VS 2017.
2. Start Debugging
3. Navigate to Scenario 8 (Command Reflow)

App hangs.

**Comment by oldnewthing** [comment]
I've asked the feature team to investigate.

**Comment by oldnewthing** [comment]
Duplicate of #250.
