### ISSUE TITLE
Display orientation sample on PC

### ISSUE THREAD

**Issue by Roozi489** [Microsoft/Windows-universal-samples#645]
The display orientation lock only work on mobile devices.
On PC (in tablet mode) there is no difference when any of the checkboxes are checked, the app still rotates as the device does. In [#385](https://github.com/Microsoft/Windows-universal-samples/issues/385) you said that it should work in tablet mode but it doesn't. It doesn't even work in Assigned Access.

**Comment by oldnewthing** [comment]
Works for me on my Surface 3 running Windows 10 version 1703.

* Go into tablet mode.
* Launch the app.
* Make sure it is the only app on the screen. (Fills the screen.)
* Check "Landscape" and "Landscape flipped" but leave the two Portrait boxes unchecked.
* Click "Apply preferences".
* Rotate the PC. Result: The app will run in landscape and landscape flipped mode only. Turning the PC 90 degrees has no effect.

**Comment by Roozi489** [comment]
I'm not sure what's wrong but it doesn't work on my device (HP x2 210 G2) running Windows 10 v1607.
[Here](https://1drv.ms/v/s!AlrX4qu_vYSjjt50CKumx4lMQOQePg) is a recorded video hopefully showing the exact same process but with a different result (the screen rotates).
