### ISSUE TITLE
render a cube without his surafaces

### ISSUE THREAD

**Issue by fefespn** [Microsoft/Windows-universal-samples#646]
Hello, 
can anyone hep me here:
https://github.com/Microsoft/Windows-universal-samples/blob/master/Samples/HolographicFaceTracking/cpp/Content/SpinningCubeRenderer.cpp
so I can render this cube without colors in his surfaces ? 
like this picture: 
![image](https://cloud.githubusercontent.com/assets/21076243/25935830/a31f2710-362d-11e7-8255-ab1ba83864f4.png)
(insread of black, I see the real background)
where in the code I need to change to do this.
thanks

**Comment by oldnewthing** [comment]
This is not a question about the sample itself. It's a question about how to add a feature to the sample. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
