### ISSUE TITLE
Cortana Voice Command not working on Phone

### ISSUE THREAD

**Issue by Matze5590** [Microsoft/Windows-universal-samples#647]
Anyone tried to use it on a phone? My lumia 650 and my lumia 950 were not able to execute the background task. Both devices have Windows 10 Version 1703 installed. With the previous Version everything was fine.
Same result to my self made Universal Platform app. There i get the cancellation reason "systempolicy". 
What happend in 1703 on mobile here?

**Comment by philvessey** [comment]
Did you find a solution to this - getting the exact same behaviour both on the sample app and my own app. Works fine on desktop - not on mobile.

**Comment by philvessey** [comment]
@oldnewthing is anyone looking at this as its the same problem on the mobile fall creators update.

**Comment by oldnewthing** [comment]
The feature team is investigating now.

**Comment by johngallardo** [comment]
@Matze5590  or @philvessey , can you let me know the build that you are seeing this on? I just tried this on 1703 - 10.0.015063.726.rs2_release_svc.20171101-1826 and the issue does not repro.

**Comment by philvessey** [comment]
Works fine on desktop. On my Lumia 950xl running the below it crashes every time.

![wp_ss_20171130_0001](https://user-images.githubusercontent.com/814882/33422945-49c318da-d5af-11e7-8489-43c9aaf2dab3.png)

**Comment by oldnewthing** [comment]
Version 1709 / build 15254 is not a supported build for Windows Phone. Supported builds are Version 1703 / build 15063.
