### ISSUE TITLE
XAMLNavigation Sample - Target Application 10.0.15063.0

### ISSUE THREAD

**Issue by Warwick858** [Microsoft/Windows-universal-samples#649]
When attempting to deploy the XAMLNavigationMenu application, I receive the below error (hopefully the image uploaded correctly).  

I am able to build the application just fine, but upon deployment, I receive an error telling me that SDK 10.0.15063.0 or higher is required, and that I am using 10.0.14393.1066.  I am targeting x86 local machine.

I certainly have 10.0.15063.0 on my machine.  Is there an additional step to put it into effect?
I recently updated to VS Enterprise 2017, and my OS is up to date, with the exception of the Creators Update.  Is the Windows Creator's Update required to execute these samples?

Upon investigating the samples project files, I noticed that the Package.appxmanifest states that the MinVersion="10.0.14393.0", and the MaxVersionTested="10.0.15063.0".

Also, despite the MinVersion specified in the appxmanifest, the NavigationMenu.csproj file TargetPlatformMinVersion States, "10.0.15063.0".

Again, I have this 10.0.15063.0 SDK on my machine. :(
Please help me.  Trying to get my first UWP app off the ground and these examples would really be helpful.

![2](https://cloud.githubusercontent.com/assets/16968400/26037697/2b9bbbaa-38b6-11e7-812e-ee1302b972c0.PNG)

**Comment by Warwick858** [comment]
Disregard.  Consider this solved.

Creator's Update was finally offered to my machine, and after performing the update, I am now able to deploy the samples.

Thank you.

**Comment by oldnewthing** [comment]
The `master` branch targets the latest released version of Windows 10 (currently Creators Update). If you want to target older versions, use one of the `win10-xxxx` branches.
