### ISSUE TITLE
redirect url for LinkedIn OAuth 2.0 authentication

### ISSUE THREAD

**Issue by shakir820** [Microsoft/Windows-universal-samples#650]
I am creating an app for LinkedIn. For OAuth 2 authentication I have to provide redirect url if I send a request. My question is I have no website. What should I type in redirect url parameter ?? I have searched on google but I did't find any solution for this. I need your help badly.

**Comment by oldnewthing** [comment]
The issue you are running into is not about the sample itself. It's about how to incorporate the sample into your own app. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
