### ISSUE TITLE
Web Authentication Broker Twitter OAuth 2 Authentication

### ISSUE THREAD

**Issue by shakir820** [Microsoft/Windows-universal-samples#651]
I am testing WebAuthenticationBroker sample app. I cannot understand what should I type in "Callback URL" in Twitter Scenario. I have created a developer account in Twitter and got my Consumer Key and Consumer Secret.  But I cannot full fill the Callback URL . What should I type ? What is my redirect URL ? How can I get it ? Please teach me.

**Comment by JimmyRespawn** [comment]
Same here. Twitter api is extremely confusing. And web broker sample seems use oauth 1 authenticate. And everytime I call for 1.1 home_timeline api, it just shows invalid authenticate.

**Comment by oldnewthing** [comment]
I've asked someone from the WebAuthenticationBroker team to investigate. Thanks for your patience.

**Comment by rgodugu** [comment]
Before using the WebAuthenticationBroker sample (twitter scenario ) you must register the application in https://apps.twitter.com/ .   for eg  
 name - WAB_test

 desc   -  sample WAB test

 website url -  http://127.0.0.1  (this is just a place holder for testing . you can use your applications url if   you want .  )

 callback uri -  http://placeholder.com/   (this must be a valid url . Twitter needs to send a oauth_callback value when we try to request a token . you don't really have to create one if you are just using OAuth for authentication . You can even use https://google.com  if you want )

**Comment by shakir820** [comment]
Can I really use  https://google.com for redirect_url  for OAuth 2.0 Authentication ? I don't  have any website of my own.

**Comment by rgodugu** [comment]
According to the twitter api if we are just using our test sample to get a success token , we can use a placeholder like  http://placeholder.com/ , the api returns a response like http://placeholder.com?oauth_token="our token"...

this token can now be extracted from the response string

**Comment by shakir820** [comment]
ok. thanks.
