### ISSUE TITLE
Use PackageReference instead of deprecated project.json for NuGet packages

### ISSUE THREAD

**Issue by martinsuchan** [Microsoft/Windows-universal-samples#654]
With Visual Studio 2017 the project.json system for managing NuGet packages has been deprecated. Visual Studio uses by default [new PackageReference system where information about NuGet packages is stored inside the csproj file.](http://blog.nuget.org/20170316/NuGet-now-fully-integrated-into-MSBuild.html)  

I think the current samples in master branch should be updated to use this new system. Separate branch could be preserved for VS2015 users.  

Note as a part of this migration, the [Microsoft.NETCore.UniversalWindowsPlatform NuGet](https://www.nuget.org/packages/Microsoft.NETCore.UniversalWindowsPlatform/) should be also updated to the lastest one, currently version **6.0.6**.

**Comment by oldnewthing** [comment]
Looks like it's not enabled for UWP yet. Web page says it requires Visual Studio 2017 Update 1 Preview 2.

**Comment by martinsuchan** [comment]
It is enabled for UWP already. It's the default format when creating new UWP apps targeting Creators Update as TargetVersion, but it works when targeting older SDK version too.

**Comment by martinsuchan** [comment]
Visual Studio 2017 15.4 is here with full support for PackageReferences in UWP projects.  Now is the right time to switch all samples to this NuGet pacakge format.

**Comment by oldnewthing** [comment]
Great. If you create a pull request that converts one sample, I can propagate the change to the other samples. This is not my area of expertise, so I need somebody to show me what to do,

**Comment by EmilAlipiev** [comment]
@martinsuchan  how can you tell UWP or nuget to use csproj instead of project.json? where is this information stored?

**Comment by martinsuchan** [comment]
Hi, I've created sample pull request how to change project.json NuGet format to PackageReference NuGet format.
It's possible the Visual Studio team already has some kind of tool for batch updating projects to the new NuGet format.
cc @oldnewthing @EmilAlipiev

**Comment by oldnewthing** [comment]
Thanks. I used your PR as a template and applied it to the other samples. Fix will go out at next refresh.
