### ISSUE TITLE
device.GattServices returns an empty set for BLE devices on a Windows universal app

### ISSUE THREAD

**Issue by abinop** [Microsoft/Windows-universal-samples#655]
I am using this [sample](https://github.com/Microsoft/Windows-universal-samples/blob/6370138b150ca8a34ff86de376ab6408c5587f5d/Samples/BluetoothAdvertisement/cs/Scenario1_Watcher.xaml.cs) and when an advertisement is received I am calling

`device.GattServices()
`
but that always returns an empty list. Why is this happening? I have found no answer no matter where I have looked.

**Comment by hewenmsft** [comment]
The GattServices property on BluetoothLEDevice is a cached property that only gets automatically populated when the device is paired. When accessing device that are not paired, you have use the asynchronous method GetGattServicesAsync which will connect and perform a over-the-air query to the device.

However, if your intent is not to connect to the service but get the supported service UUID, some devices already advertises the service UUID in their advertisement. To access that, use the ServiceUuids on the BluetoothLEAdvertisement object. It is only populated if the advertisement payload actually contains the service UUIDs.

**Comment by oldnewthing** [comment]
I can't find the place in the sample where it does `device.GattServices`. It sounds like you are making changes to the sample and are having trouble with the changes you made. The `GattServices` property is marked `deprecated`, so you should have gotten a compiler warning when you tried to use it.

**Comment by abinop** [comment]
@hewenmsft thanks, that is useful to know but @oldnewthing I don't see the `GetGattServicesAsync ` method anywhere 

![gatt](https://cloud.githubusercontent.com/assets/1769597/26268581/8d45bdec-3cf8-11e7-9930-21c8470ad65a.jpg)

I am on Windows 10 and I am refering `WindowsBase` from `C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\WindowsBase.dll`

**Comment by oldnewthing** [comment]
The GetGattServicesAsync method is new for Windows 10 version 15063. (The WindowsBase in the .NETFramework directory is not related to the UWP SDK.)

**Comment by abinop** [comment]
I don't get it. I upgraded to 15063 but still `GetGattServicesAsync `is not available... 

![gatt2](https://cloud.githubusercontent.com/assets/1769597/26274198/be57595a-3d4c-11e7-828d-506e637f23a3.jpg)

**Comment by oldnewthing** [comment]
You have to [install the 15063 SDK](https://developer.microsoft.com/en-US/windows/downloads/windows-10-sdk) in order to build, and OS version 15063 or higher in order to run.

**Comment by abinop** [comment]
Ok the method is there now, however the execution never gets past the point where I call `BluetoothLEDevice.FromBluetoothAddressAsync`

**Comment by abinop** [comment]
Closed the issue, new problem posted as issue [#661](https://github.com/Microsoft/Windows-universal-samples/issues/661)

**Comment by shikhartandon1993** [comment]
Hi
I am trying to use 
private ObservableCollection<BluetoothLEDeviceDisplay> KnownDevices = new ObservableCollection<BluetoothLEDeviceDisplay>();
but studio is not identifying "'BluetoothLEDeviceDisplay" ,it says type or namespace BluetoothLEDeviceDisplay could not be found(missing assembly reference or directive)

**Comment by shikhartandon1993** [comment]
Hi
I have attached the above file in my project

It is giving me errors in
await DeviceInformation.GetGlyphThumbnailAsync()
await glyphBitmapImage.SetSourceAsync(deviceThumbnail);

 DeviceThumbnail deviceThumbnail = await DeviceInformation.GetGlyphThumbnailAsync();
            var glyphBitmapImage = new BitmapImage();
            await glyphBitmapImage.SetSourceAsync(deviceThumbnail);

**Comment by oldnewthing** [comment]
These don't appear to be questions about the sample in this repo. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.

**Comment by shikhartandon1993** [comment]
Hi
I opened the BluetoothLE.sln in my visual studio 2017 
I opened scenario1_Discovery.xaml.cs and on opening it has many errors. It is not identifying many words.
Do we have to add any references?

**Comment by shikhartandon1993** [comment]
Sorry to bother you again but I am new to C#.
Can the functionality of Bluetooth LE be written for WInForms as well?
I need to make a form that displays all device names connected in  a bluetooth mesh network.
Thanks

**Comment by shikhartandon1993** [comment]
Hi

Which Bluetooth Code sample should I use to read values from external BLE
devices GATT profile?
Thanks

**Comment by shikhartandon1993** [comment]
Hi
BluetoothLE file
In the Scenario2_Client.xaml file in Servicelist and Characterstic list i am doing Visibility="Visible" but those combo boxes dont appear in the UI
Thanks
