### ISSUE TITLE
[XamlUIBasics] AutoSuggestBox loses focus when letter "e" is entered

### ISSUE THREAD

**Issue by asimonov-msft** [Microsoft/Windows-universal-samples#656]
![image](https://cloud.githubusercontent.com/assets/13038304/26259249/03fb767e-3c7d-11e7-9ffd-2b93925fc80e.png)

**Steps to reproduce**
1. Check out the dev branch (2867cc13c46abcc3ba63267ba1a7db5beeca4db8)
2. Build and launch the AppUIBasics sample (Samples\XamlUIBasics\cs\AppUIBasics)
3. Navigate to the AutoSuggestBox demo
4. Try to type the word "meow" into the suggestion box field.

**Expected results**
The word is entered into the field.

**Actual results**
The suggestion box field loses focus when the letter "e" is entered, and the focus is automatically switched to the search field in the top right of the app.

**Comment by oldnewthing** [comment]
I've asked the feature team to investigate.

**Comment by oldnewthing** [comment]
Fixed in [v5.0.6](https://github.com/Microsoft/Windows-universal-samples/tree/v5.0.6).
