### ISSUE TITLE
[XamlUIBasics] Button becomes invisible when switching themes

### ISSUE THREAD

**Issue by asimonov-msft** [Microsoft/Windows-universal-samples#657]
![image](https://cloud.githubusercontent.com/assets/13038304/26260849/c8974ca0-3c83-11e7-9f46-1edff9f61556.png)
![image](https://cloud.githubusercontent.com/assets/13038304/26260874/e2af23c4-3c83-11e7-8d75-ee86e9dd0918.png)

**Steps to reproduce**
1. Check out the dev branch (2867cc13c46abcc3ba63267ba1a7db5beeca4db8)
2. Build and launch the AppUIBasics sample (Samples\XamlUIBasics\cs\AppUIBasics)
3. Navigate to the Button demo. Keep the default Light theme.
4. Click on Button4 (Refresh)
5. Switch to the Dark theme from the dropdown

**Expected results**
The button remains visible.

**Actual results**
The button becomes invisible, unless you hover over it.

**Comment by oldnewthing** [comment]
I've asked the feature team to investigate.

**Comment by oldnewthing** [comment]
Feature team reports that this was fixed - check the [new repo](https://github.com/Microsoft/Xaml-Controls-Gallery.
)
