### ISSUE TITLE
[XamlUIBasics] CalendarDatePicker documentation link is incorrect

### ISSUE THREAD

**Issue by asimonov-msft** [Microsoft/Windows-universal-samples#658]
**Steps to reproduce**
1. Check out the dev branch (2867cc13c46abcc3ba63267ba1a7db5beeca4db8)
2. Build and launch the AppUIBasics sample (Samples\XamlUIBasics\cs\AppUIBasics)
3. Navigate to the CalendarDatePicker demo
4. Click on the documentation link at the bottom

**Expected results**
The link points to https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.calendardatepicker

**Actual results**
The link points to https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.CalendarView

**Comment by oldnewthing** [comment]
Fix will appear in next release.
