### ISSUE TITLE
WifiDirect Legacy Mode Wifi SSID not visible

### ISSUE THREAD

**Issue by Wamor** [Microsoft/Windows-universal-samples#660]
Hello,

Just a question about WifiDirect Legacy mode.
I started the Advertiser with Group Owner and Enable legacy mode GO enabled.
Filled in a Passphrase and a SSID. Started Advertisement but the SSID will not be visible as an available Wifi network. Is there a problem using the Legacy mode? 
I believe that the Advertiser works like a DHCP-server and supplies IP-addresses to devices connecting to this Wifi network. Is this correct ?

Kind regards,

Wamor

**Comment by oldnewthing** [comment]
This appears to be a question about the platform, not a sample. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
