### ISSUE TITLE
BluetoothLEDevice.FromBluetoothAddressAsync never gets executed on 15063 SDK 

### ISSUE THREAD

**Issue by abinop** [Microsoft/Windows-universal-samples#661]
After installing [Windows 10 15063 SDK ](https://developer.microsoft.com/en-US/windows/downloads/windows-10-sdk) the  call to BluetoothLEDevice.FromBluetoothAddressAsync is never executed.

**Comment by oldnewthing** [comment]
I don't see any samples which call BluetoothLEDevice.FromBluetoothAddressAsync. This question doesn't appear to be about the samples repo. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
