### ISSUE TITLE
CameraGetPreviewFrame is not compling

### ISSUE THREAD

**Issue by sarathdnv** [Microsoft/Windows-universal-samples#662]
i am using win10 14393 build with vs2015 to build CameraGetPreviewFrame. But, i see two errors related to UWP. Could you let me know how to resolve this.

Error	WMC1006	Cannot resolve Assembly or Windows Metadata file 'Windows.Foundation.UniversalApiContract.winmd'	CameraGetPreviewFrame	

Error	WMC9999	Type universe cannot resolve assembly: Windows.Foundation.UniversalApiContract, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime.	CameraGetPreviewFrame		

other settings i made for this project : 

platform toolset : vs2015 (v140)
target platform ver : 15063
target min platform ver : 15063

**Comment by oldnewthing** [comment]
This is a problem with your Visual Studio configuration, not with the sample. Note that if you set your target platform to 15063, then you must be using Visual Studio 2017. (Visual Studio 2015 does not support target platforms above 14393.) You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
