### ISSUE TITLE
sample using MediaPlayer.CopyFrameToStereoscopicVideoSurfaces

### ISSUE THREAD

**Issue by lostinyoureyes** [Microsoft/Windows-universal-samples#663]
Hi,

I can't get [CopyFrameToStereoscopicVideoSurfaces ](https://docs.microsoft.com/en-us/uwp/api/windows.media.playback.mediaplayer#Windows_Media_Playback_MediaPlayer_CopyFrameToStereoscopicVideoSurfaces_Windows_Graphics_DirectX_Direct3D11_IDirect3DSurface_Windows_Graphics_DirectX_Direct3D11_IDirect3DSurface_) work correctly, can't get the right eye surface when playing stereoscopic 3D video.

I asked a question [here](https://social.msdn.microsoft.com/Forums/windowsapps/en-US/a57a51b0-11d5-43b5-8aa9-aba8e056b96c/uwp-bug-mediaplayer-not-handle-3d-stereoscopic-video-correctly?forum=wpdevelop#65db3f2b-8d93-480a-b271-f3e13da10b5d), but can't get answer. 

Need a sample on how to use CopyFrameToStereoscopicVideoSurfaces.

Thanks!

**Comment by oldnewthing** [comment]
This does not appear to be a question about any of the samples in this repo. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
