### ISSUE TITLE
SmarCard | Device compatibility 

### ISSUE THREAD

**Issue by andreujuanc** [Microsoft/Windows-universal-samples#664]
Hello,

Recently, in my company we started to work with Honeywell's CT50, which we recommend to our customers as one of the best Win10 devices out there. Laser reading capabilities works with no special SDK whatsoever, just using PointOfService library.

Now, we have a new requirement where we need to read the Tag's unique identifier. This is done in the NFC example with PCSC, and it works perfectly on my Lumia 950.

Few days ago I tried with my CT50, and it did not work. Tried updating to Anniversary Update, because there is a WinJS bug in November Update, so i thought it might have something to do with this. But no luck. Even tried to redo the example in a different way and found that findAllCardsAsync returns empty array. 

`SmartCardReader.getDeviceSelector` returns one device, and then `findAllCardsAsync `returns empty array.

Is there anything I should do to allow app to these capabilities?

I've tried the following with no success:

``` 
    <Capability Name="internetClient" />
    <uap:Capability Name="sharedUserCertificates" />
    <DeviceCapability Name="proximity" />
    <DeviceCapability Name="pointOfService" />
```

FInal Notes:

- Normal `ProximityDevice `functionality works in all devices.
- I have already contacted Honeywell, but no answer yet.
- My laptop has NFC, but it does not work either. Is this something just for Lumias?
- What are the requirements to use SmartCard library?

Thanks

**Comment by oldnewthing** [comment]
This appears to be an issue with your app, not with the sample. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
