### ISSUE TITLE
OCR sample is not support chinese simplified?

### ISSUE THREAD

**Issue by dlynine** [Microsoft/Windows-universal-samples#667]
OcrEngine.AvailableRecognizerLanguages.Count is return 0, is not support chinese simplified at win10 1703 ?

**Comment by oldnewthing** [comment]
This is a question about the platform, not the sample. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
