### ISSUE TITLE
SpeechRecognitionAndSynthesis - speechRecognizer performance

### ISSUE THREAD

**Issue by MfCAYO** [Microsoft/Windows-universal-samples#668]
SpeechRecognitionAndSynthesis
Continuous recognition using a custom SRGS/GRXML grammar

I noticed that when the Windows 10 CU device (from PC to Raspberry) is not connected to any network, the ContinuousRecognitionSession voice recognition performance is remarkable (less than 10 milliseconds), but **when the device is connected to a Wi-Fi network performance drops by about 10 times! And if the Wi-Fi network does not have access to the Internet, performance is reduced by more than 2 times.**

More in detail the time it expands is between the beginning of the speechRecognizer “SoundEnded” state and when the speechRecognizer.ContinuousRecognitionSession.ResultGenerated event is invoked.

[https://github.com/Microsoft/Windows-universal-samples/blob/master/Samples/SpeechRecognitionAndSynthesis/cs/Scenario_ContinuousRecognitionSRGSGrammar.xaml.cs](https://github.com/Microsoft/Windows-universal-samples/blob/master/Samples/SpeechRecognitionAndSynthesis/cs/Scenario_ContinuousRecognitionSRGSGrammar.xaml.cs)

Kind regards,
Claudio

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for the feedback, Claudio! I've forwarded your observations on to the feature team for analysis and confirmation.

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for the feedback, Claudio! I've forwarded your observations on to the feature team for analysis and confirmation.

**Comment by oldnewthing** [comment]
Note that this is not a samples issue; it's a platform issue. In the future, you can open a support case with our Developer Support team:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
