### ISSUE TITLE
HttpClient example

### ISSUE THREAD

**Issue by oliver9523** [Microsoft/Windows-universal-samples#671]
With a fresh install of VS2017 Community trying to build and run the example "HttpClient" I get the following error

Error	C1192	#using failed on ...\Windows-universal-samples-master\Samples\HttpClient\cpp\x64\Release\HttpFilters\HttpFilters.winmd'
HttpClient
...\Windows-universal-samples-master\Samples\HttpClient\cpp\pch.cpp

**Comment by DavidGoll** [comment]
Thanks for the report. We'll take a look and report back.

**Comment by oldnewthing** [comment]
The HttpClient project is dependent on HttpFilters. You need to build HttpFilters first. (Right-click it and say "Build"). I will add a project dependency to the solution so this will be automatic in the future. Thanks for the report.
