### ISSUE TITLE
Multiple Views Sample With Blades

### ISSUE THREAD

**Issue by kuharrw** [Microsoft/Windows-universal-samples#672]
Blades are not working properly with the multiple views sample.

If an open blade is in the view that is opened it will work fine until all of that view is closed and then a new one is created.

Similarly if a closed blade is opened in a view in the same way above it will crash.

To replicate I've included a modified version of the sample. Perform the following steps:
1. Create a new view
2. Show the view
3. Close the view
4. Create a new view

Exception:
System.Runtime.InteropServices.COMException: Error HRESULT E_FAIL has been returned from a call to a COM component.
   at Windows.UI.Xaml.FrameworkElement.MeasureOverride(Size availableSize)
[MultipleViews Blade Bug.zip](https://github.com/Microsoft/Windows-universal-samples/files/1062222/MultipleViews.Blade.Bug.zip)

**Comment by oldnewthing** [comment]
This is not a problem with the sample. This is a problem with your modification to the sample. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
