### ISSUE TITLE
Javascript CustomHIDDeviceAccess

### ISSUE THREAD

**Issue by Beberrrr3** [microsoft/Windows-universal-samples#673]
Hi,

Would that be possible to provide equivalent sample in Javascript?
I don't know if the equivalent API exist.

Thanks in advance

**Comment by oldnewthing** [comment]
I don't think there's anything preventing this sample from being ported to JavaScript. Should be a straightforward conversion from C# and C++. Did you encounter any problems?

**Comment by oldnewthing** [comment]
I put this on the feature team's backlog.

**Comment by Beberrrr3** [comment]
Thanks you raymond

**Comment by oldnewthing** [comment]
VS2019 no longer supports JavaScript UWP apps, sorry.
