### ISSUE TITLE
Record Voting Criteria

### ISSUE THREAD

**Issue by denusingh** [Microsoft/Windows-universal-samples#674]
I want to develop an app which records voting criteria for someone like If a person wants to vote for some parties and another member can I get a code for the same. I have finalised my app till register-login-home page but main hurdle is still pending like how I am going to record the vote for those guys and with exact date and time that it should be displayed in UWP SQLite that the person has voted on this and this date and how i am going retrieve it ?

**Comment by oldnewthing** [comment]
This is not an issue with a sample in this repo. You can open a support case with our Developer Support team who may be able to help with the specific question you have. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
