### ISSUE TITLE
unresolved external symbol winrt::Windows::Globalization::impl_ILanguage

### ISSUE THREAD

**Issue by peter8179** [Microsoft/Windows-universal-samples#675]
Hi cppwinrt expert,

i use cppwinrt\10.0.14393.0 in VS2015, and in the source code try to print the info with following code:

winrt::Windows::Globalization::Language& lang = vl.GetAt(i);
printf("i=%d, tag=%ws, disp=%ws, native=%ws\n",
			i, lang.LanguageTag().c_str(), lang.DisplayName().c_str(), lang.NativeName().c_str());

The compile is ok, but when link i got the errors:

error LNK2001: unresolved external symbol "public: struct winrt::hstring __cdecl winrt::Windows::Globalization::impl_ILanguage<struct winrt::Windows::Globalization::ILanguage>::NativeName(void)const " 
error LNK2001: unresolved external symbol "public: struct winrt::hstring __cdecl winrt::Windows::Globalization::impl_ILanguage<struct winrt::Windows::Globalization::ILanguage>::DisplayName(void)const " 
error LNK2001: unresolved external symbol "public: struct winrt::hstring __cdecl winrt::Windows::Globalization::impl_ILanguage<struct winrt::Windows::Globalization::ILanguage>::LanguageTag(void)const "

please help, i link with the windowsapp.lib, but these symbols not in this lib?

**Comment by anpilley** [comment]
I wouldn't go so far as to call myself an expert, but NativeName, DisplayName and LanguageTag are [Properties](https://docs.microsoft.com/en-us/uwp/api/Windows.Globalization.Language#properties_). Call them like

`lang.NativeName.c_str()`

and see if that helps?

**Comment by oldnewthing** [comment]
This is not an issue with a sample in this repo. You can try opening a support case with our Developer Support team who may be able to help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.

**Comment by BrentRe** [comment]
You need to #include "winrt/WIndows.Globalization.h" as you are using properties from the Windows.Globalization namespace.
