### ISSUE TITLE
how to test WiFiScan in VM with windows 10

### ISSUE THREAD

**Issue by tonysos507** [Microsoft/Windows-universal-samples#676]
after succeeding to build WiFiScan sample code, i copied WiFiScan.exe to VM which is installed windows 10,  and i simply run the WiFiScan.exe by double clicking it, or run it in CMD with administrator, but both can not work,  how can i test it in vm?

**Comment by oldnewthing** [comment]
This is explained [in the README](https://github.com/Microsoft/Windows-universal-samples/blob/master/Samples/WiFiScan/README.md):
## Run the sample

The next steps depend on whether you just want to deploy the sample or you want to both deploy and run it.

### Deploying the sample

- Select **Build** \> **Deploy Solution**. 

### Deploying and running the sample

- To debug the sample and then run it, press F5 or select **Debug** \> **Start Debugging**. To run the sample without debugging, press Ctrl+F5 or select **Debug** \> **Start Without Debugging**.
