### ISSUE TITLE
Rfcomm Chat sample scenario2 server not working with Raspberry PI Windows 10 IoT core

### ISSUE THREAD

**Issue by matealex** [Microsoft/Windows-universal-samples#677]
Hello,

I'm trying to establish Bluetooth Classic communication between a Raspberry Pi 3 (running Win 10 IoT core 16193) using the RFCOMM sevice and my laptop. I am testing the sample code RfCommChat provided for UWP.

So far I manged to establish communication between one PI (client, scenario1) and my laptop (server, scenario2).

However, no success using the PI as Server. The sample app crashes.

After I bit of debugging I found out that the problem is after the line:

`rfcommProvider.StartAdvertising(socketListener);`

which returns the "Error 0x800700b7 Cannot create a file when that file already exists"

Any idea about how to solve it? Is this a known issue?

I am using VS 2017 and Win IoT core 16193. Tried to flash the SD card again but with no success.
Edit: Tried with Win IoT 15063 and I get the same behavior.
Thanks a lot

**Comment by dkosyak** [comment]
Turn off bluetooth in IoTCoreDefaultApp (Settings-Bluetooth-Off) or disable auto startup IoTCoreDefaultApp

**Comment by royben** [comment]
Same thing here even after Settings-Bluetooth-Off. Any suggestions ?

**Comment by royben** [comment]
Resolved after playing around a little bit. Also, it appears my SD card although shipped as a IOT starter kit.. was corrupted.

**Comment by oldnewthing** [comment]
Closing since @royben says it's resolved.
