### ISSUE TITLE
BackgroundTransfer with FTP source doesn't work on ARM

### ISSUE THREAD

**Issue by ausdev16** [Microsoft/Windows-universal-samples#678]
When running the BackgroundTransfer > CS> Scenario1_Download sample with an external FTP source address, the following error is received when debugging on ARM:

Execution error: Error HRESULT E_FAIL has been returned from a call to a COM component.

The exact same code works fine when compiled for x86 / x64.

**Comment by DavidGoll** [comment]
Thanks for the report. We'll investigate to determine whether this is a product bug or a platform limitation.
