### ISSUE TITLE
[AppUIBasics] [dev branch] unhandled exception:NavigationMenuItem is not registered

### ISSUE THREAD

**Issue by andrejo-msft** [Microsoft/Windows-universal-samples#681]
OS: rs_prerelease 16215 (Windows Insider Fast build)
VS: 15.2 (26430.13) - public release of Visual Studio
SDK: 16590 - public insider pre-release of FCU SDK

Open the AppUIBasics.sln in the dev branch (has samples of Fluent controls).
Build and deploy the project (Debug/x64).

Expected:
App runs

Actual:
**Unhandled user exception:**
Exception details follow. 

This code did function as of //build - considering that there has been no shift in code or SDK, one would assume that there is a regression with either Visual Studio or Windows as we've moved on from May.

System.TypeLoadException occurred
  HResult=0x80131522
  Message=Requested Windows Runtime type 'Windows.UI.Xaml.Controls.NavigationMenuItem' is not registered.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at System.StubHelpers.StubHelpers.GetWinRTFactoryObject(IntPtr pCPCMD)
   at Windows.UI.Xaml.Controls.NavigationMenuItem..ctor()
   at AppUIBasics.NavigationRootPage.AddNavigationMenuItems() in E:\github\Windows-universal-samples\Samples\XamlUIBasics\cs\AppUIBasics\Navigation\NavigationRootPage.xaml.cs:line 153
   at AppUIBasics.NavigationRootPage.<LoadGroups>d__35.MoveNext() in E:\github\Windows-universal-samples\Samples\XamlUIBasics\cs\AppUIBasics\Navigation\NavigationRootPage.xaml.cs:line 225

Inner Exception 1:
COMException: Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG))

**Comment by KasperHoldum** [comment]
I am experiencing the same error.

OS: rs_prerelease 16226 (Windows Insider Fast build)
VS: 15.3 Preview 2.1
SDK: Windows Insider Preview 16190

**Comment by Lukespacewalker** [comment]
Just Update to 16255 SDK, I find out that NavigationMenuItem has been changed to NavigationViewItem instead.

**Comment by oldnewthing** [comment]
Fix has been merged into dev.
