### ISSUE TITLE
CameraFrames not capturing some Infrared sources

### ISSUE THREAD

**Issue by ShikiGami** [Microsoft/Windows-universal-samples#685]
PerceptionInfraredFrameSource is now obsolete in the creators update, so it cannot be used now to get Infrared Frames, so I'm forced to use MediaFrameSource for it.
The problem is that some IR cameras do not get recognized by MediaFrameSource as IR cameras, while they are when using PerceptionInfraredFrameSource.

CameraFrames show me my RGB-IR camera as only a RGB camera.

**Comment by TrevorDev** [comment]
Could you share what camera you are trying to use?

**Comment by ShikiGami** [comment]
It is a "Computer Mouse CM-01"
https://www.amazon.com/Mouse-Facial-Recognition-Camera-Windows/dp/B01MSEJPJP

As far as I can tell it uses a Realtek sensor, which by device ID appears to be the same used in the Asus Tranfromer 3 Pro.

![1e5fd76c17b0c2cd2530e57c7c18c809](https://user-images.githubusercontent.com/3926168/27653218-614e41c8-5c79-11e7-9d7b-2d167668b409.png)

**Comment by TrevorDev** [comment]
Thank you, I've created an internal bug report so we can investigate this issue further.

**Comment by TrevorDev** [comment]
After investigating further, it looks like this camera doesn’t provide a Media Foundation compliant IR camera driver. To work around this issue you can:

- Switch to a Media Foundation compliant camera
- Request the camera vendor to provide a Media Foundation compliant IR camera driver for your device
- Attempt to continue to use the PerceptionInfraredFrameSource API and ignore obsolete warnings
