### ISSUE TITLE
Why Custom effect can't input two texture?

### ISSUE THREAD

**Issue by 404517981** [Microsoft/Windows-universal-samples#686]
I've tried  like this"   hr = pTransformGraph->ConnectToEffectInput(0, dftHorizontalTransform.Get(), 0);
		          hr = pTransformGraph->ConnectToEffectInput(0, dftHorizontalTransform.Get(), 1);  "
  and SetInpuEffect is a effect of bitmap，but it's does't work，thanks all  advising

**Comment by oldnewthing** [comment]
The issue you are running into is not about code in the D2DCustomEffects sample; it appears to be a question about how to modify the sample to add a new feature. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.

**Comment by dustpg** [comment]
@404517981 Did you find the way to accept two/variable inputs texture for single effect? thx

**Comment by 404517981** [comment]
@dustpg 没有啊 ,这个固定了接口，大多是为了处理图片的貌似，不过用D3D11 倒是没有限制

**Comment by dustpg** [comment]
@404517981  [Win2D-PixelShaderEffectImpl.cpp](https://github.com/Microsoft/Win2D/blob/master/winrt/lib/effects/shader/PixelShaderEffectImpl.cpp#L32)
找到了怎么支持动态数量了，原来要从xml入手, 找了半天都没找到文档居然在这里找到了
> minimum = '0' maximum = '8'
