### ISSUE TITLE
Websocket server running on UWP

### ISSUE THREAD

**Issue by zaidrashid** [Microsoft/Windows-universal-samples#688]
Looking at the WebSocket [section](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/WebSocket), it is mainly to integrate the client side of WebSocket to the app. Is there a way to create a WebSocket Server instead of the client on the UWP app?

**Comment by DavidGoll** [comment]
It is not currently possible to host a WebSocket server from within a UWP app, but is being considered for a future Windows release.
