### ISSUE TITLE
In Process Service Example Needed

### ISSUE THREAD

**Issue by hongtao-chen** [Microsoft/Windows-universal-samples#689]
This MSDN article describes the in-process app service new in the creator release https://docs.microsoft.com/en-us/windows/uwp/launch-resume/convert-app-service-in-process.

But cannot find any working example for that. Can we have an sample for this scenario?

**Comment by oldnewthing** [comment]
It is a straightforward translation of the two-process mode. Just do the work in the OnBackgroundActivated method rather than in a task. You can see an example of this in the BackgroundActivation sample.
