### ISSUE TITLE
Unable to play HLS stream

### ISSUE THREAD

**Issue by BoneGoat** [Microsoft/Windows-universal-samples#692]
Hi,

we're trying to play our HLS stream using MediaPlayer but are unable to do so. The AdaptiveStreaming sample produces the same behavior. We have no issues playing the stream in other players. Could it be a bug in the player?

https://live-cdn.sr.se/pool1/p3/p3.isml/p3.m3u8

Best

**Comment by aarononeal** [comment]
Thank you for reporting. This bug is fixed in the latest flights of Windows.

**Comment by BoneGoat** [comment]
Thanks for looking into this. Does this mean we have to wait until the "latest flights of Windows" are available on all devices (specific version)? Or will we get an update to Windows.Media.Playback.MediaPlayer in the UWP SDK?

**Comment by aarononeal** [comment]
It is an OS and not SDK issue. Therefore it requires an OS update to a newer build of Windows 10. You can download the current flight which includes the fix that will be available in the next official update.
