### ISSUE TITLE
MultipleViews:  Size preference has no effect

### ISSUE THREAD

**Issue by fman028** [Microsoft/Windows-universal-samples#693]
In scenario 1 of the MultipleViews sample, changing the size preference for the view to be shown and the main view seems to have no effect?

![multiple views sample](https://user-images.githubusercontent.com/2321378/27843883-5c555ebe-60ce-11e7-8370-661e1a314b00.png)

**Comment by oldnewthing** [comment]
This appears to be a platform issue, not a samples issue. You can open a support case with our Developer Support team who can further help with this issue. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
