### ISSUE TITLE
Is it possible to get the location of the hololens camera using CameraFrames sample

### ISSUE THREAD

**Issue by akilaVis** [Microsoft/Windows-universal-samples#694]
Hi and thank you for these samples, 
I want to ask about if it is possible to get the view and projection matrix of the hololens camera using CameraFrames sample, I tried with photocapture API of unity, but these doesn’t work when a stream is already playing, I am using webRTC for video transmission and I wonder if I can use your sample to get the intrinsic and extrinsic values of the hololens camera when the camera is used by another thread.
Look forward to your response and Thank you
Best

**Comment by TrevorDev** [comment]
Have you taken a look at the HolographicFaceTracking sample?
Take a look at [HolographicFaceTrackerMain.cpp](https://github.com/Microsoft/Windows-universal-samples/blob/master/Samples/HolographicFaceTracking/cpp/HolographicFaceTrackerMain.cpp)
In the ProcessFaces method it accesses

- The frame's CoordinateSystem which can be transformed to the world view.
- The video frame's CameraIntrinsics

Hope this helps.

**Comment by akilaVis** [comment]
Thank you TrevorDev, I'll have a look into it
