### ISSUE TITLE
Adaptive Streaming is not as good as default player

### ISSUE THREAD

**Issue by iamstudentVN** [Microsoft/Windows-universal-samples#698]
Hi!
I use build 14393, beause of my device can't update new version. At version 14393, i use Adaptive Streaming and it only play for 30s and then pause.
I use default Player play stream very good, but it cant custom request and get/set resolution.
Thanks for reading

**Comment by aarononeal** [comment]
I'm sorry, this is not a sample issue and will require further troubleshooting steps. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for additional help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
