### ISSUE TITLE
Is there VpnPlugin sample?

### ISSUE THREAD

**Issue by JamesMackerel** [Microsoft/Windows-universal-samples#699]
VPNs is necessary for users in China, and we have been thinking about developing a VPN plugin for a long time. I saw [a vpn plugin doc](https://docs.microsoft.com/en-us/uwp/api/windows.networking.vpn), but cannot find any sample from Microsoft or Internet. 

Would you please release an example of VPN APIs? We need it badly.

**Comment by oldnewthing** [comment]
This is a request for a new sample, not an issue with an existing sample. The web page you linked to explains that `networkingVpnProvider` is not available for general use, so this repo would not be a good fit. The web page you linked to also has an email address to contact for questions about the VPN API.
