### ISSUE TITLE
Incorrect instruction in Windows-Audio-Session Readme.md

### ISSUE THREAD

**Issue by johnsmith-programmer** [Microsoft/Windows-universal-samples#700]
https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/WindowsAudioSession#run-the-sample

"To run this sample after building it, press F5 (run with debugging enabled) or Ctrl-F5 (run without debugging enabled) from Visual Studio 2013 for Windows 8.1 (any SKU). (Or select the corresponding options from the Debug menu.)"

The requirements are vs2017 and win 10 - so this instruction is incorrect.

**Comment by aarononeal** [comment]
Thank you. Fixed in an upcoming version.
