### ISSUE TITLE
[StreamSocket] cUrl hangs when sending data.

### ISSUE THREAD

**Issue by WindfallProphet** [Microsoft/Windows-universal-samples#702]
Trying to transmit data to the server using curl, but curl ends up hanging leading to the error stringLength != actualStringLength (from  [this project](https://github.com/Microsoft/Windows-universal-samples/blob/master/Samples/StreamSocket/cs/Scenario1_Start.xaml.cs)). The state of listener.Control.KeepAlive does not seem to have any effect.

```
* About to connect() to 10.0.0.10 port 22112  (#0)
*   Trying 10.0.0.10...
* Connected to 10.0.0.10 (10.0.0.10) port 22112 (#0)
> POST / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 10.0.0.10:12345
> Accept: */*
> Content-Type: application/json
> Content-Length: 31
>
* upload completely sent off: 31 out of 31 bytes
```

**Comment by oldnewthing** [comment]
I've asked the feature team to investigate.

**Comment by DavidGoll** [comment]
If you are trying to use the server included with the StreamSocket sample, then this is expected. It's just a raw TCP socket that echoes whatever is sent to it. Curl is of course expecting an HTTP server and will not expect its request to simply be echoed.

**Comment by PeterSmithRedmond** [comment]
Note in particular that the first four bytes that the StreamServer sample gets is read as an integer.  But the first four byte that cUrl is sending seem to be the letters 'P', 'O', 'S' and 'T'.  The integer value of those bytes isn't going to be anything useful at all.
