### ISSUE TITLE
Failed to deploy WifiDirect on Win10 tablet

### ISSUE THREAD

**Issue by mosbaker** [Microsoft/Windows-universal-samples#705]
Hi,
I'm trying to deploy the WifiDirect sample on a Win10 tablet. It fails with:

Installing app...
Found dependency package(s):
C:\moshe\WiFiDirect_1.0.0.0_Debug_Test\Dependencies\x86\Microsoft.NET.CoreRuntime.1.1.appx
C:\moshe\WiFiDirect_1.0.0.0_Debug_Test\Dependencies\x86\Microsoft.VCLibs.x86.Debug.14.00.appx
Add-AppxPackage : Deployment failed with HRESULT: 0x80073CFD, A Prerequisite for an install could not be satisfied.
Unspecified error
NOTE: For additional information, look for [ActivityId] cb3b833b-67d0-0000-5fad-3bcbd067d201 in the Event Log or use
the command line Get-AppxLog -ActivityID cb3b833b-67d0-0000-5fad-3bcbd067d201

At C:\moshe\WiFiDirect_1.0.0.0_Debug_Test\Add-AppDevPackage.ps1:388 char:13
+             Add-AppxPackage -Path $DeveloperPackagePath.FullName -Dep ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  + CategoryInfo          : NotSpecified: (C:\moshe\WiFiDi...ebug.appxbundle:String) [Add-AppxPackage], Exception
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

Error: Could not install the app.

**Comment by oldnewthing** [comment]
This appears to be a Visual Studio issue rather than a samples issue. The sample does deploy okay on my system.
