### ISSUE TITLE
Nfc Sample - Not Clear What it Does

### ISSUE THREAD

**Issue by rashadrivera** [Microsoft/Windows-universal-samples#706]
The Nfc sample does not have a "Specifically, this sample shows how to" section or go into what this sample actually dues.  I suppose that those who know what **Nfc** stands for will understand, but the novice and beginner needs more explanation.

**Comment by oldnewthing** [comment]
It does the two thing described in the README and in the sample scenarios.

* HCE NFC Tap+Pay
* NFC card reader

NFC stands for [Near-field communication](https://en.wikipedia.org/wiki/Near-field_communication). I'll add a definition to the README.
