### ISSUE TITLE
How to read data from DatagramSocket in the BackgroundTask

### ISSUE THREAD

**Issue by EricJCXu** [Microsoft/Windows-universal-samples#707]
DatagramSocket only has the OutputStream, so how to read data?Thanks.

**Comment by oldnewthing** [comment]
The DatagramSocket sample shows how to handle the [MessageReceived event](https://github.com/Microsoft/Windows-universal-samples/blob/v5.0.0/Samples/DatagramSocket/cs/Scenario2_Connect.xaml.cs#L103)
