### ISSUE TITLE
 Bluetooth Low Energy client sample: 100% CPU usage

### ISSUE THREAD

**Issue by EZZAHED** [Microsoft/Windows-universal-samples#708]
Hi everyone,

I am developping an app based on **Bluetooth Low Energy client sample**. I have a  number of bluetooth devices (10 devices) that are displayed on the list. The issue that I face is the huge usage of the **CPU**, see the attached picture.. 

![windows-universal-samples](https://user-images.githubusercontent.com/12432799/28748008-a5618d82-74a4-11e7-9732-e7ac497ca8c9.jpg)

**Comment by oldnewthing** [comment]
This appears to be a platform issue, not a samples issue. You can open a support case with our Developer Support team who can further help with this issue. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.

**Comment by EZZAHED** [comment]
OK thank you for your reply !

1. Sorry I didn't find the right place to post my issue. When I clicked the link in step 1. I redirected to this page [](https://developer.microsoft.com/en-us/windows/support ). Then I clik on "Professional Support for Windows 10 Universal app development" but I am redirected to Not found Page with 404 error.

2. Do you have the same sample in javascript language ?


Thanks

**Comment by oldnewthing** [comment]
Sorry I don't run that page. If there is no javascript version of the sample in the repo, then such a sample doesn't exist. But it shouldn't be that hard to translate it from the existing C# sample.

**Comment by EZZAHED** [comment]
Could you please post the right link to App Development Support.

**Comment by oldnewthing** [comment]
The only link I have is the one in my reply.
