### ISSUE TITLE
Bluetooth Low Energy client sample in javascript

### ISSUE THREAD

**Issue by EZZAHED** [Microsoft/Windows-universal-samples#710]
I would like to use the Bluetooth Low Energy client sample in a javascript app, but the sample is written only in c#, How can I find its javascript version?

**Comment by oldnewthing** [comment]
I've created a backlog item for the feature team.

**Comment by FrankGorgenyi** [comment]
Hi EZZAHED,

Unfortunately JavaScript version of the sample will not be in the next couple updates. We've prioritized our sample backlog by requests and we've had many for C++ and will focus on it next. If you have issues using our APIs from JavaScript please feel free to asks specific questions.
