### ISSUE TITLE
BackgroundDownloader not working on a headless app

### ISSUE THREAD

**Issue by Spawnkid** [Microsoft/Windows-universal-samples#711]
When using BackgroundDownloader on a background/headless UWP running on Windows 10 IoT Core. It just hang on this part:

**await download.StartAsync().AsTask(_cts.Token, progressCallback);**

The storage file is also 0 byte, but when you stop the app that is the time the file contents are dumped. Funny is that this was working several days ago. But after an Windows Update on Windows 10 IoT Core few days ago it stops working.

**Comment by DavidGoll** [comment]
What version of the OS was installed with that update?

**Comment by Spawnkid** [comment]
Hi, Thank You for the reply I am actually writing another post on MS site regarding this matter.


The version of IoT Core was v.10.0.15063.483


I also downloading an insider build to deploy and test the issue on my spare RPI3.



The problem lies on StartAsync method of BackgroundDownloader class. It just stalls forever there. To easily replicate this issue, just download official MS GitHub UWP samples and look for

So basically right now, all our IoT devices is useless because we need to download images from bunch of CCTV/IP Cameras to be send in MS Cognitive service for analysis.
When I mean bunch of cameras, I mean hundreds of them because its a entire village's cameras and tens of RPi's that was running W10 IoT Core.
Someone also posted this issue on StackOverFlow https://stackoverflow.com/questions/45472159/backgrounddownloader-on-windows-10-iot-core-does-not-complete-on-raspberry-pi



Hope it can be resolved as soon as possible. Thank you for the quick response by the way.


P.S: I'm excited for the Microsoft IoT Roadshow!


Michael

**Comment by DavidGoll** [comment]
One more question about versions. Was this an upgrade from 14393, or one of the monthly updates for 15063?

**Comment by Spawnkid** [comment]
Hmm.. It was just a monthly update I think. Because one of my cloned/developer board who also having an issue was just formatted and installed by IoT dashboard a few weeks ago (not more than a month) so I assumed that the OS on was latest stable build.

**Comment by Spawnkid** [comment]
Update: Doesn't work also with v.10.0.16247.1000 Insider Preview build.

**Comment by DavidGoll** [comment]
Thanks for the info. Since this is a product bug, and not a sample bug, I plan to close this issue and open a new issue in our internal issue database. Before I do that however...

> Hi, Thank You for the reply I am actually writing another post on MS site regarding this matter.

Did you write this post? Assuming so, please reply with a link.

**Comment by Spawnkid** [comment]
https://social.msdn.microsoft.com/Forums/en-US/ce9b7807-0bff-4881-932f-0f16e22f9a01/backgrounddownloader-doesnt-work-anymore-when-running-on-a-headless-app?forum=WindowsIoT

**Comment by DavidGoll** [comment]
Thanks. I'll look for the Feedback Hub issue (as was suggested in reply to your post). That's the preferred way to report issues because it ties directly into our internal issue database.
