### ISSUE TITLE
Ink strokes replay memory leak

### ISSUE THREAD

**Issue by cgiu** [Microsoft/Windows-universal-samples#712]
Hello, 

I like the replay feature, but unfortunately when you replay your inks, each seconds the memory increase drastically. The leak is here: "InkCanvasRef.InkPresenter.StrokeContainer" for each time in the loop when you make a new ink container, the StrokeContainer is not able to wipe.

Hope their is an alternative solution !

Bye!

**Comment by oldnewthing** [comment]
I've asked the feature team to investigate.

**Comment by oldnewthing** [comment]
The feature team confirms that this is a platform issue. A workaround in the sample will be in the next refresh.
