### ISSUE TITLE
XamlTreeView C++ fails to compile (C# okay)

### ISSUE THREAD

**Issue by therealkenc** [Microsoft/Windows-universal-samples#713]
I am having (possibly) the same problem as the person over in issue #557, but random tweaking the project settings this way and that doesn't seem to help. I am using Visual Studio 15.3.0 Preview 7.0, and have also installed SDK 16232 with all the trimmings. Other UWP C++/CX samples build okay, so I think my general MSVS install is probably sound. The C# version of XamlTreeView project builds and runs okay. Any insight appreciated. 

```
1>------ Rebuild All started: Project: TreeViewControl, Configuration: Debug x64 ------
2>------ Rebuild All started: Project: TreeView, Configuration: Debug x64 ------
1>pch.cpp
2>pch.cpp
2>c:\users\there\source\repos\windows-universal-samples\samples\xamltreeview\cpp\pch.cpp : fatal error C1192: #using failed on 'C:\Users\there\source\repos\Windows-universal-samples\Samples\XamlTreeView\cpp\x64\Debug\TreeViewControl\TreeViewControl.winmd'
2>        'The system cannot find the file specified.'
2>Done building project "TreeView.vcxproj" -- FAILED.
```

**Comment by therealkenc** [comment]
With some more clicking I have found that building the C# solution targeting 16232, and then re-opening the C++ solution, it picks up the winmd correctly. It is "rebuild all" in the C++ solution (which I was always selecting without much thought about it) that results in the fail.

**Comment by oldnewthing** [comment]
Ah, there is a missing dependency in the C++ sample. The TreeView project needs to be marked as dependent on the TreeViewControl project. I'll include that in the next update, thanks.
