### ISSUE TITLE
The wrong conversation about TimeSpan.

### ISSUE THREAD

**Issue by cloudmonkeypeng** [Microsoft/Windows-universal-samples#716]
TimeSpan Helpers::TimeSpanFromSeconds(int seconds)
{
    TimeSpan timeSpan;
    timeSpan.Duration = seconds * 1000LL * 10000LL; // convert seconds to TimeSpan units
    return timeSpan;
}

In msdn tell, a time period expressed in 100-nanosecond units.

So in my opinion, timeSpan.Duration = seconds * 10LL * 10000LL; // convert seconds to TimeSpan units

**Comment by oldnewthing** [comment]
[1 second = 10⁹ nanoseconds](https://en.wikipedia.org/wiki/Nanosecond)

10² nanoseconds = 1 timespan unit

therefore

1 second = 10⁷ timespan units
