### ISSUE TITLE
DatePicker and TimePicker FlipView

### ISSUE THREAD

**Issue by SamuelLioult** [Microsoft/Windows-universal-samples#717]
Hi,
It is not an issue but I don't see where to place this request.
I would like to know how to do a control like this one used in the Alarm and Clock application for hour and minute selection or in the DatePicker (and TimePicker) flyout.

I tried to customize the FlipView control replacing the changing the VirtualizingStackPanel orientation to Vertical and height property to 36 (for example). But there is a problem when it appears when I scroll to the end. So I tried a library to have an attached property "IsLooping" but this creates also a bad display of the last and first items.

**Comment by oldnewthing** [comment]
This is not a question about a sample in this repo. You can open a support case with our Developer Support team:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
