### ISSUE TITLE
Exception when Deploying a Universal Windows Platform Game In Master Mode

### ISSUE THREAD

**Issue by AkhilBhaskar** [Microsoft/Windows-universal-samples#719]
Attempting to deploy a Universal Windows Game in Master Configuration which is compiled from Unity throws an unhandled exception as follows:
Unhandled exception at 0x603FF073 (Windows.UI.Xaml.dll) in HopTheBall.exe: 0xC000027B: An application-internal exception has occurred (parameters: 0x038C1FB0, 0x00000002).

can anyone give the rectification for this error?

**Comment by oldnewthing** [comment]
The issue you are running into is not about a sample that is not working. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
