### ISSUE TITLE
CameraManualControls - Unable to control a PTZ camera (Aver - CAM520)

### ISSUE THREAD

**Issue by ahsanmkhan** [Microsoft/Windows-universal-samples#720]
Hi,

I have been trying to control Aver - CAM520 which is a PTZ camera. However, the VideoDeviceController.Pan.Capabilities.Supported is false. The same is with Tilt.

ZoomControl.Supported is also false however VideoDeviceController.Zoom.Capabilities.Supported is true and I am able to set the zoom with VidoDeviceController.Zoom.TrySetValue(). The same technique does not work with Pan and Tilt.

Aver - CAM520 supports USB UVC as well as VISCA. Currently, I am trying with UVC as I don't have a serial port in my laptop. To test the camera setup I used Vendor's PTZ app and it worked.

Any idea how to solve this issue? 

Thanks.

**Comment by oldnewthing** [comment]
This appears to be a question about hardware support for specific cameras, not about the sample itself. You can open a support case with our Developer Support team. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
