### ISSUE TITLE
FileAccess - The resource "ScenarioConverter" could not be resolved.

### ISSUE THREAD

**Issue by c00012** [Microsoft/Windows-universal-samples#721]
Hello, 
I downloaded this sample and selected "File Access Sample".  
Though there's no problem in building and run the sample but I've got this message in XAML for the sample
"The resource "ScenarioConverter" could not be resolved.
If anyone explain why, I'd be very appreciated.

Thanks,
c00012

**Comment by oldnewthing** [comment]
I cannot reproduce this problem with the current `master` branch and the Fall Creators Update SDK in either the C# or C++ sample. Please provide more details if you're still encountering this problem.
