### ISSUE TITLE
BLE on Windows python

### ISSUE THREAD

**Issue by manikandan-enability** [Microsoft/Windows-universal-samples#722]
is it possible to scan/connect/receive BLE data on windows **python** environment at any way (direct or indirect)??

**Comment by oldnewthing** [comment]
This isn't a question about the samples in this repo. You can open a support case with our Developer Support team. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
