### ISSUE TITLE
CameraStreamCorrelation.sln is missing dependency configuration

### ISSUE THREAD

**Issue by aki-kanerva** [Microsoft/Windows-universal-samples#723]
The solution file Samples\CameraStreamCorrelation\cpp\CameraStreamCorrelation.sln doesn't have project depencies defined. Trying to build the full solution results in an error. Setting CameraStreamCorrelation.vcxproj to depend on PoseTrackingPreview.vcxproj resolves the issue.

**Comment by ChrisGuzak** [comment]
thanks for reporting, if you can provide a PR with the fix.

**Comment by aki-kanerva** [comment]
Uh, sorry, not really sure how to work with pull requests, if that's what you mean by "PR". I'm not a regular around here. :) It's just a minor edit to Samples/CameraStreamCorrelation/cpp/CameraStreamCorrelation.sln:

```
Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "CameraStreamCorrelation", "CameraStreamCorrelation.vcxproj", "{5D0B26EA-0EAA-5F30-B4D5-2C7516C66FFB}"
+	ProjectSection(ProjectDependencies) = postProject
+		{C29F3FFA-12B0-5FAD-9763-D460E91A5E7A} = {C29F3FFA-12B0-5FAD-9763-D460E91A5E7A}
+	EndProjectSection
EndProject
```

**Comment by oldnewthing** [comment]
I'll apply these to the active branches, thanks.
