### ISSUE TITLE
UWP Virtual Smart Card sample c# - exception

### ISSUE THREAD

**Issue by Enzosbruder** [microsoft/Windows-universal-samples#724]
Hi All,

I am currently trying to get the Smart Card C# example running on my Win10 client (user is in local admin group), but unfortunately it is not working....

Example:
Creating a TPM Virtual Smartcard works perfectly with the cmd line (as administrator):
**TpmVscMgr create /name MyVSC /pin default /adminkey random /generate**

Creating a TPM Virtual Smartcard DOES NOT work when running cmd line NOT as administrator:
UAC opens--> "Requested operation requires elevation"

Running the provided Smart Card C# sample which contains in fact the code from here (https://docs.microsoft.com/en-us/windows/uwp/security/smart-cards) is not working....the error message/exception shows: "The requested operation requires elevation" when trying to create a TPM Virtual Smart Card. 

As far as I know it is not possible to start a UWP as an administrator....please correct me if I am wrong...

Questions:
What am I missing here?
Is it possible to create a Virtual Smart Card without administrator privileges (if yes how, because it seems it is not working with the provided Smartcard API)? 

![smartcardsample](https://user-images.githubusercontent.com/31693685/30118888-7036dc2c-9324-11e7-883b-01e24778df16.png)

**Comment by Enzosbruder** [comment]
Any updates on this case?

**Comment by oldnewthing** [comment]
The issue is still open against the feature team.

**Comment by slinweb** [comment]
Did you get any feedback? How has been the sample tested then if not possible to run it ?

**Comment by Enzosbruder** [comment]
@slinweb - No, I didn´t get any feedback yet...regarding your second question: I am not quite sure what you mean but (maybe you could be a more precise!?)...it is possible to start the sample application. But the creation of the virtual smartcard fails...I know that for creating a virtual smartcard admin permissions are needed but with the provided example it simply won´t work.

**Comment by slinweb** [comment]
Ok succeeded to have it working by being Administrator and setting UAC level to Low.

**Comment by oldnewthing** [comment]
I'm still trying to figure out from the feature team how this ever worked.

**Comment by oldnewthing** [comment]
[The documentation has been updated](https://docs.microsoft.com/en-us/windows/uwp/security/smart-cards#create-a-virtual-smart-card):

> In order to create a virtual smart card using a UWP app, the user running the app must be a member of the administrators group. If the user is not a member of the administrators group, virtual smart card creation will fail.

Will add a note the sample README as well.
