### ISSUE TITLE
Add sample for Windows.ApplicationModel.Lockscreen APIs (Lock Screen App)

### ISSUE THREAD

**Issue by colinkiama** [Microsoft/Windows-universal-samples#726]
The documentation for this API doesn't explain how we get our app to show up in the lock screen, replacing the default lock screen app. A sample would really help us understand how to make a lock screen app of our own.

**Comment by oldnewthing** [comment]
That's not what this API is for. Like it says in the README, this API is for letting your app show an indicator on the lock screen, not for taking over the lock screen.

**Comment by colinkiama** [comment]
Well then the description for this namespace is VERY misleading then: https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.lockscreen

"You can create an app that acts as the lock screen, allowing greater user personalization. You can develop novel unlock gestures and animations, and also display custom information or appearances for people."

There is a slight possibility that there is confusion between this API and the API used in the "LockScreenApps" sample.

**Comment by oldnewthing** [comment]
Oh, wait, you're right. I got confused. The lock screen sample deals with badging. But the LockScreen namespace is for replacing the lock screen. However, this namespace is protected by a Windows capability, so it is not available to third parties. I will ask for this to be clarified in the documentation.

**Comment by colinkiama** [comment]
Okay, thanks for clearing this up.
