### ISSUE TITLE
Remote debugging fails on a remote computer in a local network

### ISSUE THREAD

**Issue by K-YSoftware** [Microsoft/Windows-universal-samples#728]
Error Unforeseen event in activity "WireUpCoreRuntime".
System.IO.FileNotFoundException: file not found 'E:\Users\Fucking\Documents\Visual Studio 2015\Repos\Windows-universal-samples\Samples\StreamSocket\cs\bin\x86\Debug\Core$targetnametoken$.exe'.
Nome file: 'E:\Users\Fucking\Documents\Visual Studio 2015\Repos\Windows-universal-samples\Samples\StreamSocket\cs\bin\x86\Debug\Core$targetnametoken$.exe'
in System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
in System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
in System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
in Microsoft.Build.Net.CoreRuntimeTask.WireUpCoreRuntime.InternalExecute()
in Microsoft.Build.Net.CoreRuntimeTask.WireUpCoreRuntime.Execute()
in Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
in Microsoft.Build.BackEnd.TaskBuilder.d__26.MoveNext() StreamSocket Compilazione

**Comment by checkdigits** [comment]
"K Y" and a Windows user name of "f*cking" - really?

Come on.  :(

**Comment by oldnewthing** [comment]
This is not a samples issue. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
