### ISSUE TITLE
Bluetooth Low Energy sample - Shared.csproj does not exist

### ISSUE THREAD

**Issue by agomes100** [Microsoft/Windows-universal-samples#731]
Hi!

When building the Bluetooth Low Energy sample, the build process does not complete. 
It seems a file is missing from the repository.

Here is the message:
 "The referenced project '..\Shared\Shared.cspoj' does not exist."

Appreciated, 
Alex

**Comment by oldnewthing** [comment]
There shouldn't be a Shared project any more. I assume you're building the C# version from master?

**Comment by oldnewthing** [comment]
Okay, I see it now. Just delete the reference to the nonexistent project. I'll add this fix to the next update. Thanks for reporting it.
