### ISSUE TITLE
Camera preview frame sample App crash / Exception thrown after latest Windows Update 10.0.15063.608

### ISSUE THREAD

**Issue by manateeworks** [Microsoft/Windows-universal-samples#733]
Using this sample https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/CameraGetPreviewFrame/js
results in an app crash with the following exception when trying to debug:

Unhandled exception at 0x00007FFA3394FA2F (Windows.Media.dll) in WWAHost.exe: 0xC0000005: Access violation reading location 0x0000000000000000

![access_exception](https://user-images.githubusercontent.com/5564013/30548907-b038b6f6-9c93-11e7-8708-4ad01fe38957.png)

This also happens with a camera preview app in JavaScript based on mediaCapture.

Mobile devices and PCs with previous OS versions don't have that problem, only devices/PCs with the latest OS version 10.0.15063.608

**Comment by convey-gilbert** [comment]
This crash happens on all Windows 10 and Windows 10 Mobile devices after update to 10.0.15063.608 when a UWP app written in JavaScript uses a HTML5 Video element after calling the play() function to start streaming the video preview on the page. Currently all JavaScript apps using camera video/photo preview will no longer work anymore!

**Comment by jangaehler** [comment]
@oldnewthing Can you please fix the Camera samples?

**Comment by convey-gilbert** [comment]
It's not a bug in the samples. It's a Windows bug since version 15063.608

**Comment by convey-gilbert** [comment]
See this thread:
https://social.msdn.microsoft.com/Forums/windowsapps/en-US/601d9974-b184-4a36-a877-8a07d6787a94/uwpjs-all-javascript-apps-using-camera-preview-will-crash-after-latest-windows-update?forum=wpdevelop
