### ISSUE TITLE
Unable to open appointment created with Appointments sample in Outlook 2016

### ISSUE THREAD

**Issue by filipliwinski** [Microsoft/Windows-universal-samples#735]
I'm unable to open an appointment created with [Appointments](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/Appointments) sample in Outlook 2016. If I try to do this I get an error: _Sorry, we're having trouble opening this item. This could be temporary, but if you see it again you might want to restart Outlook_. Error code is 0x80070057. This issue applies to Office Outlook for PC only. Tested with VS2015 and VS2017.

I'm able to:
-  create appointment with **Appointments sample** and open it in Calendar app/Outlook Web/Outlook on mobile,
-  create appointment with **Calendar app** and open it in Outlook 2016/Calendar app/Outlook Web/Outlook on mobile,

but I'm not able to create an appointment with Appointments sample and open it in Outlook 2016.

**Comment by armorga** [comment]
Hey Filip,

Does this happen for all appointments you create with the sample? If it's only failing for specific appointments can you provide the details (dates, recurrence info, etc.) that you are using?

**Comment by happy-baby-small** [comment]
要我的信息有什么事情吗？





------------------ 原始邮件 ------------------
发件人: "armorga";<notifications@github.com>;
发送时间: 2017年9月20日(星期三) 凌晨2:59
收件人: "Microsoft/Windows-universal-samples"<Windows-universal-samples@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [Microsoft/Windows-universal-samples] Unable to open appointmentcreated with Appointments sample in Outlook 2016 (#735)




Hey Filip,
 
Does this happen for all appointments you create with the sample? If it's only failing for specific appointments can you provide the details (dates, recurrence info, etc.) that you are using?

**Comment by filipliwinski** [comment]
@armorga
I made some further investigation and found what's follows:
- yes, all appointments created with the sample fails if I try to open them in Outlook 2016 (even very basic one, with just a subject _test_)
- the issue does not depend on the Windows version (same result with appointments created with previous version of the SDK on Windows 10.0.14393 - it worked until September 6th)
- I am able to open all appointments created before September 6th (regardless of the version of Windows or Outlook); appointments created after this date fails to open (checked on multiple PCs and calendars even on different Office365 tenants, fails even in Outlook 2016 on Windows 8.1)
- checked on different versions of Office 2016 (1708, 1707, 1611) - same results for appointments created before and after September 5th

I'm confused. Any ideas?

**Comment by filipliwinski** [comment]
The issue seems to be resolved after installing November updates.

**Comment by oldnewthing** [comment]
Thanks for the update.
