### ISSUE TITLE
BLE Server/ Client 

### ISSUE THREAD

**Issue by Hobl1990** [Microsoft/Windows-universal-samples#736]
Hy guys, 
Could it be that there is a issue in the "BLE" Sample ?
When I try to run the server service on 1 PC and the client on my Surface, no devices are enurated. 
Is there a bug or do I have forgotten something?

**Comment by oldnewthing** [comment]
You didn't say which model of Surface you have. Do you get the message "Peripheral Role not supported - local device will not be connectable." when you run the server scenario?

**Comment by Hobl1990** [comment]
I use the Surface Pro 3 with Visual Studio 2017 Community and the lastet SDK updates. No its only mentioned 0 devices found. Enumeration completed.
The advertisement example works.

**Comment by Hobl1990** [comment]
I only got these before I run the server: 
![grafik](https://user-images.githubusercontent.com/32168859/30707979-70a8c884-9efd-11e7-8352-bec861d608f7.png)

Do you mean that last sentence?

**Comment by oldnewthing** [comment]
Yes, the message "Peripheral Role not supported - local device will not be connectable" is telling you that your Bluetooth radio does not support acting as a server. I will make the error message more prominent. It's easy to miss.

**Comment by Hobl1990** [comment]
Thank you for the information ;) 
So for which kind of device (pc, laptop,..) or OS (Windows 10 Professional, Windows 10 Education,..) work the server function?

**Comment by oldnewthing** [comment]
See [this thread](https://blogs.windows.com/buildingapps/2017/01/13/new-bluetooth-features-in-creators-update-gatt-server-bluetooth-le/#div-comment-25583) which asks the same question.

**Comment by Hobl1990** [comment]
thanks for the info ;) 
I have a last question which focuses on BLE Advertisement:

I want to transmit data (numerical values, Uint16) from Hololens to µController board with ble communication. Every time when a new frame will be generated, a numerical value should be transmitted via BLE.

My thoughts were, every time when a new frame will be gernerated also a new publisher with new numerical values will be generated. But my tests showed that not all data will be received.

Might it be better to only update the payload of the publisher, if it is possible, or to use GATT server and GATT client?

**Comment by oldnewthing** [comment]
This isn't really a question about the sample. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.

**Comment by Hobl1990** [comment]
You are right but as a preparation for the project I want to send data as advertisement from my Surface to the PC. Based on your advertisement example I wrote a program which stops and closes the publisher afte a defined time interval. Afterwards I created a new publisher with new payload. 
Now I'm interested if it is possible to update the payload without stopping and creating a new publisher?

**Comment by oldnewthing** [comment]
This is not an issue with the sample. The sample is working correctly. You're asking about how to add features to the sample, which is beyond the scope of this repo.

**Comment by Hobl1990** [comment]
Of course do you have any hint for me?

**Comment by oldnewthing** [comment]
What I say three times is true. This is not the proper venue for that question.
