### ISSUE TITLE
Equations for mapping depth data to display don't actually work.

### ISSUE THREAD

**Issue by fowie** [Microsoft/Windows-universal-samples#737]
Most of the equations used in PseudoColorForDepth appear to be incorrect because they simply clamp all depth output to 0 or 1.
FrameRenderer.cpp lines 129 to 132 should be changed from
````
    float minInMeters = minReliableDepth * depthScale;
    float maxInMeters = maxReliableDepth * depthScale;
	float one_min = 1.0f / minInMeters;
	float range = 1.0f / maxInMeters - one_min;
````
to
````
    float minInMeters = minReliableDepth * depthScale;
    float maxInMeters = maxReliableDepth * depthScale;
	float one_min = minInMeters;
	float range = maxInMeters - one_min;
````

which then allows line 150 to be changed from
````
float alpha = (1.0f / depth - one_min) / range;
````
to
````
float alpha = (depth / range); 
````

and line 159 from
````
outputRow[x] = PseudoColor(alpha*alpha);
````
to
````
outputRow[x] = PseudoColor(alpha);
````

Also note that this code requires inputFrame->DepthMediaFrame->MaxReliableDepth to return a valid value.  On the Intel sensor I tested, this returned max unsigned int.

**Comment by oldnewthing** [comment]
I've asked the feature team to respond to your suggestion.

**Comment by ms-yl** [comment]
We were using "inverse depth" to visualize the depth using the same pseudo color palette that's also used to visualize infrared.      Here, the alpha is computed with (1/d - 1/dmin) / (1/dmax - 1/dmin) and its value is always between 0 to 1.
This inversed depth and the gamma correct (alpha * alpha) is to achieve a more uniform color scale across the depth range in desktop range (0.5-5meters).    Feel free to change this visualization to whatever suit your application and/or sensors.
We do rely on camera driver to provide good min/max values.  Please feel free to contact intel to report their camera driver's defect on the model you are using.   Or consider to use a cameras fully supporting this API, such as Kinect camera for windows, or newer version of intel realsense cameras.
