### ISSUE TITLE
Barcode Scanner Compatible Hardware web URL is broken.

### ISSUE THREAD

**Issue by deepak-rathi** [Microsoft/Windows-universal-samples#738]
Barcode Scanner Compatible Hardware web URL (https://docs.microsoft.com/en-gb/windows/uwp/devices-sensors/barcode-scanner#compatible-hardware) is broken and return 404 with message 
"The page that you requested could not be found. The URL might be misspelled, or the page you are looking for is no longer available."

**Comment by oldnewthing** [comment]
Try changing en-gb to en-us.
