### ISSUE TITLE
Error MSB3030: All of these samples are broken and don't work with the new version of Visual Studio 2017

### ISSUE THREAD

**Issue by xtianus79** [Microsoft/Windows-universal-samples#740]
This is not well kept and is probably better not released than to release broken samples.  

How do I fix this and what can be done

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3030	Could not copy the file "C:\repos\Windows-universal-samples\Samples\WebView\js\Debug\StreamUriResolverCPP\SDK.WebViewSampleCpp.winmd" because it was not found.	WebView	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	4222	

```

**Comment by oldnewthing** [comment]
Each sample was verified to work when it was published. I don't have the time to re-test all 500+ samples whenever a new version of Visual Studio comes out.

The issue you found appears to be a missing dependency. Rebuild again and it should work.

**Comment by oldnewthing** [comment]
Okay, somehow they got unchecked from the "Any CPU" configuration. Switch to some other configuration (x64, x86, or ARM). "Any CPU" isn't really meaningful any more.

**Comment by xtianus79** [comment]
@oldnewthing thank you.  I would love to help but am not to familiar with all of the inner workins just yet.

**Comment by xtianus79** [comment]
@oldnewthing Just to advise.... Issues aren't usually closed until the update has been officially deployed.  Would you mind reopening the issue?

**Comment by oldnewthing** [comment]
It's already in staging.
