### ISSUE TITLE
System.ArgumentException when trying to get items from IStorageFolder (from clipboard)

### ISSUE THREAD

**Issue by arkoc** [Microsoft/Windows-universal-samples#742]
When trying to get items from folder, that is retrieved from Clipboard content `System.ArgumentException: Value does not fall within the expected range.` exception is thrown. 

Here is sample code to reproduce issue:

```
var cb = Clipboard.GetContent();
var storageItems = await cb.GetStorageItemsAsync();
foreach (var item in storageItems)
{
    if (item is IStorageFolder)
    {
        var pastedFolderItems = await (item as IStorageFolder).GetItemsAsync() // <= Exception
    }
    else if (item is IStorageFile)
    {
        // With storage item everyting works.
    }
}
```

Exception Details

> System.ArgumentException occurred
>   HResult=0x80070057
>   Message=Value does not fall within the expected range.
>   Source=System.Private.CoreLib

**Comment by oldnewthing** [comment]
This does not appear to be reporting an issue with a sample, but rather with your own code. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.

**Comment by arkoc** [comment]
Issue is related to samples too, because there is no example of using that IStorageFolder.

https://github.com/Microsoft/Windows-universal-samples/blob/5f0d0912214afc1c2a7c7470203933ddb46f7c89/Samples/Clipboard/cs/CopyFiles.xaml.cs#L133

**Comment by oldnewthing** [comment]
Whether it's bug in your code or a bug in the UWP clipboard service, it's not a bug in the sample.

**Comment by arkoc** [comment]
I agree, but is there any way for reporting issue for uwp? (except one with *support subscription* in your provided link)

**Comment by oldnewthing** [comment]
Feedback Hub has a "Developer Platform" category.

**Comment by oldnewthing** [comment]
I just confirmed with the feature team that this is a bug and it is being tracked on the product side. It occurs if the folder was placed on the clipboard by a non-UWP app.

**Comment by oldnewthing** [comment]
This turns out to be on purpose, for security reasons. Otherwise, UWP apps could "steal" any file copied to the clipboard. The code in this repo handles the issue correctly: By catching the exception and reporting that clipboard contents are not available.
