### ISSUE TITLE
UWP Pedometer.GetDefaultAsync()

### ISSUE THREAD

**Issue by OlegKlym** [Microsoft/Windows-universal-samples#743]
On Nokia lumia 929 Pedometer.GetDefaultAsync() always returns null. Is this device unsupported ? Cause i can use pedometers from store, so device can check steps

**Comment by oldnewthing** [comment]
This is a question about device platform support, not a question about the sample. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
