### ISSUE TITLE
[JumpList] Custom item icon size

### ISSUE THREAD

**Issue by msjogren** [Microsoft/Windows-universal-samples#744]
The JumpList sample (scenario 3 - custom items) sets the custom JumpListItem's logo to ms-appx:///Assets/smalltile-sdk.png, which is a 44x44 image.

But as far as I can tell, the image is rendered as 32x32 or 16x16 depending on system scale factor (there might be other possible sizes but these are the ones I've seen during testing). So it would be more accurate to provide a custom image with 16x16 at scale-100 and 32x32 at scale-200, to really show off the expected behaviour of the API.

**Comment by oldnewthing** [comment]
I've forwarded your question to the feature team.

**Comment by oldnewthing** [comment]
The feature team replied with an answer I didn't understand. Maybe it will make sense to you:

> As I recall, the 44x44 size originated from unifying the Windows Phone 8 and Windows 8 manifest logos. Mobile used a 62x62 logo, but the desktop used 32x32. Phone's standard resolution of 480x800 seemed to align most closely with the desktop's 140% scale factor, so that was reverse-engineered to arrive at a 44x44 logo. Authoring at 44x44 lets you use a single set of assets for both platforms, with desktop downscaling to 32x32. You can add the -targetsize adornment to avoid rescaling at a cost of increasing the size of your package.

**Comment by msjogren** [comment]
I can't say I understand their reasoning either. Jump lists are only supported on desktop. But I still very much appreciate you and the team taking the time to answer, thanks!
