### ISSUE TITLE
Xalm listview sample crashes

### ISSUE THREAD

**Issue by pierresa** [Microsoft/Windows-universal-samples#745]
if ((this.obj10.Target as global::Windows.UI.Xaml.Controls.TextBlock) != null)
                    {
                        XamlBindingSetters.Set_Windows_UI_Xaml_Controls_TextBlock_Text((this.obj10.Target as global::Windows.UI.Xaml.Controls.TextBlock), (global::System.String)obj, null);
                    }

System.InvalidCastException: 'Unable to cast object of type 'System.Char' to type 'System.String'.'

on trying listview or gridview

**Comment by oldnewthing** [comment]
Which branch are you building from?

**Comment by pierresa** [comment]
I downloaded this stuff on October 3rd

I see there is an October version now; I will try and see if it is any better

De : Raymond Chen [mailto:notifications@github.com]
Envoyé : 06 October 2017 20:16
À : Microsoft/Windows-universal-samples <Windows-universal-samples@noreply.github.com>
Cc : pierresa <pierresa@outlook.com>; Author <author@noreply.github.com>
Objet : Re: [Microsoft/Windows-universal-samples] Xalm listview sample crashes (#745)


Which branch are you building from?

**Comment by pierresa** [comment]
Before asking this question you should have checked … I think

Anyway current version (October 2017) downloaded and just gives the same error

De : Pierre Saintoyant [mailto:pierresa@outlook.com]
Envoyé : 07 October 2017 13:03
À : Microsoft/Windows-universal-samples <reply@reply.github.com>; Microsoft/Windows-universal-samples <Windows-universal-samples@noreply.github.com>
Cc : Author <author@noreply.github.com>
Objet : RE: [Microsoft/Windows-universal-samples] Xalm listview sample crashes (#745)

I downloaded this stuff on October 3rd

I see there is an October version now; I will try and see if it is any better

De : Raymond Chen [mailto:notifications@github.com]
Envoyé : 06 October 2017 20:16
À : Microsoft/Windows-universal-samples <Windows-universal-samples@noreply.github.com<mailto:Windows-universal-samples@noreply.github.com>>
Cc : pierresa <pierresa@outlook.com<mailto:pierresa@outlook.com>>; Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Objet : Re: [Microsoft/Windows-universal-samples] Xalm listview sample crashes (#745)


Which branch are you building from?

**Comment by oldnewthing** [comment]
Which branch? Master or dev? (Or one of the older branches?)
