### ISSUE TITLE
LiveTitle solution required

### ISSUE THREAD

**Issue by harrypotter06** [Microsoft/Windows-universal-samples#746]
Hello,

we search about a solution, that allow me to look, what Time/Date a Live Title will be update.

Background: Customer App and Customer will make a Notification(Toast) to his Users, if LiveTitle Update to old. My idea: I use a background Task to check the LiveTitle last Update time.

**Comment by oldnewthing** [comment]
This is not an issue with a sample. You can open a support case with our Developer Support team who can further help with your issue. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.

**Comment by harrypotter06** [comment]
I always thought GitHub isd to help each other. My mistake, which is obviously not so.

**Comment by harrypotter06** [comment]
I always thought GitHub isd to help each other. My mistake, which is obviously not so.

**Comment by harrypotter06** [comment]
https://github.com/oldnewthing - this answers do not throw a good light on Microsoft. Is your Answer conform with Microsoft CEO Statement?

**Comment by oldnewthing** [comment]
I helped you by telling you where the question would be on topic. It is not on topic for this repo, sorry.

**Comment by harrypotter06** [comment]
Sorry, but open a Support Request, isn't help. You have give me a link, how i must open a support request by Microsoft.  
Not good solution and this is no help from you/Microsoft.
