### ISSUE TITLE
Is there a performance difference between the JS versions and C++ / C# versions of coding of sdk's such as ink?

### ISSUE THREAD

**Issue by xtianus79** [Microsoft/Windows-universal-samples#748]
I noticed that the js sample for ink had a different performance than the c++ version.  The c++ version was smooth and glided naturally... where the js version was rough until it fully rendered as if it were smoothing over after it was fully rendered

wanted to temper the expectation

**Comment by oldnewthing** [comment]
I've forwarded your question to the feature team.

**Comment by tigersha** [comment]
Great question, and there is a big difference. The "SimpleInk" sample demonstrating Windows Ink in C++ leverages DirectInk and Direct2D to render smooth strokes in Windows natively. These libraries are highly optimized for ink stroke modeling and rendering, and include ink acceleration features that provide very low latency for end-users. 

The "Ink" sample is a separate sample that demonstrates basic DirectInk usage in js (InkManager). We don't yet expose our native Direct2D stroke rendering to js; instead this sample is using the web standard CanvasRenderingContext2D methods to render the ink strokes, which accounts for the difference you're seeing. In particular, you'll notice that on pointer updates we simply use moveTo for "wet ink", and on pointer up we use bezierCurveTo for "dry ink" which results in a better looking stroke on lift.

Are you looking to build an inking web application? Please reach out to directink at microsoft dot com and we can provide advice on how you can best render ink today in a web context.
