### ISSUE TITLE
Question about UWP Web Apps: Can you only access the full windows api's via the converted hybrid webapp to UWP

### ISSUE THREAD

**Issue by xtianus79** [Microsoft/Windows-universal-samples#749]
Just wanted to confirm that. 

So for example, would I want to develop the webapp first and then convert over to UWP for added functionality.... i.e. inking

Also, what about the reverse... per se.  What if I wanted to develop a webapp in UWP first and then make that into a web site PWA' for certain or additional aspects?

**Comment by michael-hawker** [comment]
@xtianus79 as long as the webpage is being hosted in the UWP container and has the proper content uris set in the package manifest, you can access the Windows APIs.  You can check if the 'Windows' object exists on the window to see if you have access to the APIs.  Thus, by guarding your Windows specific code, you can have your web app target multiple platforms.

https://www.pwabuilder.com/ has more info about the reverse process as well.

Both approaches are viable as long as you're thinking about how your going to encapsulate and isolate platform specific functionality and incorporate it into your UX.

**Comment by oldnewthing** [comment]
This isn't an issue with the samples in this repo. You can open a support case with our Developer Support team. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
