### ISSUE TITLE
RadialController - Is it possible to uniquely identify and use multiple surface dials?

### ISSUE THREAD

**Issue by agomes100** [Microsoft/Windows-universal-samples#751]
Hi!
Is it possible to use multiple surface dials and uniquely identify inputs from each of them?

The API does not seem to provide methods for that. 

Appreciated, 
Alexandre Siqueira.

**Comment by oldnewthing** [comment]
I asked the feature team but they never responded. The current RadialController API does not provide a way to identify multiple controllers.
