### ISSUE TITLE
I don't understand this Samples - Nothing work

### ISSUE THREAD

**Issue by harrypotter06** [Microsoft/Windows-universal-samples#752]
I use Visual Studio 2017.
No Sample will work and i don't understand why. Error-Message: "using System;" - Not found ....

**Comment by oldnewthing** [comment]
This can happen if your NuGet cache is corrupted. Try purging your NuGet cache and rebuilding. Those references come in from the .NET Framework reference, which is populated by NuGet.

**Comment by harrypotter06** [comment]
No, the NutGet cache isn't corrupted. On other VS2017 Installations, same issue.
All other VS2017 Projects work fine.

**Comment by harrypotter06** [comment]
Oh, Issue closed, but isn't solved? New way to solve issues by Microsoft?

**Comment by oldnewthing** [comment]
This is not really a samples issue. It's a VS issue.

**Comment by harrypotter06** [comment]
And why other Samples work? Only this Sample didn't work?

**Comment by harrypotter06** [comment]
You are from Microsoft an you publish Samples that are not compatible with Microsoft Produkts?

**Comment by oldnewthing** [comment]
They work for me.

**Comment by oldnewthing** [comment]
See also issue #300 which is pretty much identical.
