### ISSUE TITLE
Support InMemoryRandomAccessStream for rendering SVG

### ISSUE THREAD

**Issue by anhoavu** [Microsoft/Windows-universal-samples#753]
Per my question on https://stackoverflow.com/questions/46701251/direct-2d-svg-rendering-in-uwp
It would be desirable to be able to render SVG from a string; not just Assets files.

**Comment by oldnewthing** [comment]
This isn't a question about the sample, but rather a question about the platform. You can open a support case with our Developer Support team:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.

(That said, SvgImageSource.SetSourceAsync takes an IRandomAccessStream.)
