### ISSUE TITLE
Possible error in ContiguousOrOverlaps extension method in XamlDataVirtualization sample

### ISSUE THREAD

**Issue by bgulrich** [Microsoft/Windows-universal-samples#754]
Thanks for this sample.  It gave me a great starting point for a more generic virtualized list to use with my ListViews.  After I modified the sample code for my own use, I noticed some normalized ranges were not completely normalized and I believe the culprit is the ContiguousOrOverlaps method.  

Consider the supplied method with the input of This: (3,3), range: (0,50).  This would return false, but I believe the intention is to return true as the ranges overlap.

````
public static bool ContiguousOrOverlaps(this ItemIndexRange This, ItemIndexRange range)
        {
            return (range.FirstIndex >= This.FirstIndex && range.FirstIndex <= This.LastIndex + 1) || (range.LastIndex + 1 >= This.FirstIndex && range.LastIndex <= This.LastIndex);
        }
````

If that's the desired result, this may do better:

````
public static bool ContiguousOrOverlaps(this ItemIndexRange This, ItemIndexRange range)
        {
            // This is left
            if(This.FirstIndex < range.FirstIndex)
                return (range.FirstIndex <= This.LastIndex + 1);
            // This is right
            else if (This.FirstIndex > range.FirstIndex)
                return (This.FirstIndex <= range.LastIndex + 1);
            // Aligned
            return true;
        }
````

**Comment by oldnewthing** [comment]
I've asked the feature team to look into this. Thanks for the report.

**Comment by oldnewthing** [comment]
The feature team has accepted your fix. It will appear in the next refresh.
