### ISSUE TITLE
cs  How can BluetoothLE be disconnected?is .Dispose();？

### ISSUE THREAD

**Issue by dtt-xss** [Microsoft/Windows-universal-samples#755]
How can is disconnected with BluetoothLE ?
BluetoothLE gets a notification.Disconnect, and then connect, also need to get notice?

**Comment by oldnewthing** [comment]
This doesn't seem to be a question about the sample. You can open a support case with our Developer Support team who can further help with the question you have. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.

**Comment by flier268** [comment]
use ```GC.Collect(); ``` after dispose
