### ISSUE TITLE
WinRT originate error on accessing skeleton data

### ISSUE THREAD

**Issue by ashikns** [Microsoft/Windows-universal-samples#756]
In the CameraStreamCorrelation sample, as soon as you enable skeleton overlay, the log gets spammed with WinRT originate error:

Exception thrown at 0x00007FFE05C29E08 (KernelBase.dll) in CameraStreamCorrelation.exe: 0x40080201: WinRT originate error (parameters: 0x0000000080000013, 0x000000000000001D, 0x0000009BFDAFEE80).
It doesn't cause any real issues, but it's still annoying for logging and diagnosing purposes. Is there any proper way to prevent this? I've noticed that the error happens when accessing the byte buffer of the skeleton frame.

Running Windows 10 Creator's Update, VS2017 latest, Kinect V2 for WIndows

**Comment by oldnewthing** [comment]
I've asked the feature team to investigate.

**Comment by oldnewthing** [comment]
The feature team is unable to reproduce the problem with Fall Creators Update.
