### ISSUE TITLE
GeGattServicesAsync() reports GattCommunicationStatus.Unreachable for Win 10 IoT Insiders Preview v 10.0.16267.1001

### ISSUE THREAD

**Issue by PTmv** [Microsoft/Windows-universal-samples#758]
Suddenly my Win 10 IoT application started to report services.Status Ureachable when calling 

GetGattServicesAsync() after updating to Win 10 Insiders Preview v 10.0.16267.1001. My VS 2017 is v 15.2 (26430) and .NET Framework is v 4.7.02053 for my UWP application which runs on Raspberry Pi 3. Please advise me how to solve this problem since I have a project deadline.

Thanks,

   Paul

**Comment by oldnewthing** [comment]
This doesn't appear to be a question about the samples in this repo. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.

**Comment by PTmv** [comment]
Thank you Raymond.

Certainly, I will open a support case with the Win 10 IoT Development Team.

Best Regards,

   Paul
