### ISSUE TITLE
Alarm & Reminder samples needed

### ISSUE THREAD

**Issue by JustinXinLiu** [Microsoft/Windows-universal-samples#76]
Please provide samples on how to create Alarms and Reminders with Windows 10 API. Nothing can be found on the Internet.

**Comment by leixu2046** [comment]
Hi Justin, 

Alarm and reminder can be created with toast notification framework in Windows 10. 

Apologize that the official sample for Windows 10 notifications are not ready and up yet, but here are several links that can unblock you for now.

https://msdn.microsoft.com/en-us/library/windows/apps/xaml/hh868254.aspx
https://msdn.microsoft.com/en-us/library/windows/apps/xaml/hh868224.aspx

You need to use the link above to send toast notifications, but when constructing the notification xml payload, using the below payload to get the new alarm/reminder behaviors. The guidance of constructing payloads for new flexible and interactive toast notificaiton will also be published very soon.

<toast launch="arguments your app wants to receive when the alarm/reminder is tapped on">
  <visual>
    <binding template="ToastGeneric">
	<text>Insert your title here</text>
        <text>Insert content here</text>
        <image src="provide a source to an optional image here, no larger than 200k" 
placement="inline" />
    </binding>
  </visual>
  <actions hint-ssytemCommand="SnoozeAndDismiss" />
</toast>

**Comment by leixu2046** [comment]
![sample payload](https://cloud.githubusercontent.com/assets/13003574/8289345/c45fa368-18d0-11e5-9e08-b8c866efe590.png)

**Comment by leixu2046** [comment]
The comment area is trying to interpret the payload I typed in so I attached an image. Also please reach out for any questions or problems you run into.

**Comment by JustinXinLiu** [comment]
Thanks @leixu2046 this will get me started.
