### ISSUE TITLE
[UWP] backgroundMediaPlayback Capability BROKEN in Fall Creators Update.

### ISSUE THREAD

**Issue by dmarjoram** [Microsoft/Windows-universal-samples#761]
Customers with Fall Creators Update have reported (and I have also confirmed) that the backgroundMediaPlayback package manifest capability no longer works.

Audio is muted when the app is minimized to the taskbar and processing is stopped.

Please fix ASAP.

**Comment by aarononeal** [comment]
Please provide detailed OS, tools, and SDK numbers with steps to reproduce.

I just tested the BackgroundMediaPlayback sample and Groove. Both played audio in the background.

**Comment by dmarjoram** [comment]
Hi aarononeal.

I've investigated further and the breaking change actually refers to audio recording, both with AudioGraph and also WASAPI. I have apps in the Windows Store that worked fine in both Anniversary and Creators as long as the background MediaPlayer was used periodically.

Now when the app enters background, extended execution continues but the audio buffers are now full of zero values.

My app, used by thousands, synchronizes Hue lights with music and this scenario is now broken when the user minimizes the app.

Visual Studio 2017 Professional, Fall Creators SDK, OS 16299.19
Targeting Fall Creators, Min Version Anniversary.

**Comment by aarononeal** [comment]
I'm sorry to inform you that background recording is not a supported feature for 3rd party UWP apps outside of VoIP. Certain recording scenarios were hardened with the update, and this sounds like one of them. In the future we would like to enable background recording through a similar capability as playback once we make it easier for users to understand which apps are recording.
