### ISSUE TITLE
Touch keyboard for custom controls no longer triggers (broke your official sample too)

### ISSUE THREAD

**Issue by BillHenning** [Microsoft/Windows-universal-samples#762]
You guys had a feature that our custom controls used where when a XAML custom control got focus, it would trigger the touch keyboard to show.  I just noticed that this no longer works.  I'm not sure if Fall Creators Update broke it or if it was before.

Please see your official Touch Keyboard sample here, since it's broken there now too whereas it used to work:

https://github.com/Microsoft/Windows-universal-samples/tree/93bdfb92b3da76f2e49c959807fc5643bf0940c9/Samples/TouchKeyboard

When you run that sample on a Surface without hardware keyboard attached, if you would tap in the first pill-looking control on the first page, it used to trigger the touch keyboard to show.  That no longer works.

Can you please tell us if there is new functionality that is needed to get this working, or if it is a confirmed bug that will be corrected soon?  This functionality is pretty critical for touch users of our UI controls.  

Either way, your official sample needs to be updated to work properly.

**Comment by oldnewthing** [comment]
I've asked the text input team to investigate.

**Comment by oldnewthing** [comment]
A revised sample will be in the next update. Thanks for reporting the issue.

**Comment by oldnewthing** [comment]
The TouchKeyboard sample has been updated for Windows 10. Thanks for your patience.
