### ISSUE TITLE
CameraOpenCV doesn't find cameras

### ISSUE THREAD

**Issue by MikeyWetzel** [Microsoft/Windows-universal-samples#766]
This has a been a saga to build/run this simple sample, but in the end, it simply can't find any cameras. Meanwhile, the default Windows 10 Camera app finds my Lifecam HD-3000 webcam just fine.

I'm on the latest Windows 10 Pro Insider build, with the latest SDK. (Can't build nor run the sample without being on the latest versions.) I'm working in VS 2017 Community.

The code can't get past line 126 of Scenario1_ExampleOperations.xaml.cs:
            var allGroups = await MediaFrameSourceGroup.FindAllAsync();

While it's not apparent how I could debug my situation at this point, it is clear that the Windows 10 Camera app works just fine, so I have justification to blame the code in this sample.

My suspect is that the code did work at one point in time, but some recent change in the latest update broke it.

(BTW, Microsoft forces me to be on Insider Builds because I'm a Hololens developer. Trust me, it's not by my choice. I'm really hoping the "solution" is not to be on an insider build.)

**Comment by oldnewthing** [comment]
I've asked the feature team to investigate.

**Comment by MikeyWetzel** [comment]
I tried this on a different PC (with a different webcam) which had the Creators Fall update and the sample worked. So, I brought that webcam home to try on the non-working computer.

At home, I first tried the webcam with the Windows 10 built-in Camera app. The webcam works. So i tried the sample and it run, but no webcam :(. Same issue as before, it can't find the camera at line 126.

Now I go back to the Camera app and it no longer finds my webcam. The UWP sample code appears to have put my camera in a bad state. I'll try rebooting and whatnot, but my patience is quickly evaporating. (I'm trying to write an app that uses the webcam, and there are simpler solutions/libraries that have worked for years.)

**Comment by BenPYeh** [comment]
Sorry to hear about that Mike. I can't seem to repro the problem, but I can recall at least a few other cases of visual studio and UWP app issues. They all seem to have gone away with an update, however. Could you reply with the build number you're on that isn't working, and try an update?

**Comment by BenPYeh** [comment]
Also, does the CameraFrames app (https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/CameraFrames) work for you?

**Comment by MikeyWetzel** [comment]
Alas, no. Not on the computer with the latest Windows preview.

 

Unfortunately, in my project I have moved on. I’m no longer trying to use UWP, and instead am using the much simpler OpenCV with c# winforms.

 

I hope it was just a fluke that only affects me. I hate to report a bug that can’t repro on your end.

 

Thanks,

Mikey Wetzel

Go Fast. Go Fresh. Go Burrito!

**Comment by BenPYeh** [comment]
Hi Mike, if you would like to help us out, you can file a feedback with a trace via the Feedback Hub, which might give us more of an idea of what's wrong, because I can't repro it still with the latest insider build. Or if you aren't relying on the sample anymore, would you close the bug?

**Comment by MikeyWetzel** [comment]
I'll close the bug and chalk it up to being on a preview version of Windows.
