### ISSUE TITLE
Is there a way to display/convert a bluetooth device glyph icon (BitmapImage) to use in a WPF application?

### ISSUE THREAD

**Issue by kirk-quinbar** [Microsoft/Windows-universal-samples#767]
In your bluetooth sample, you are displaying the glyph icon for enumerated devices in the UWP UI. I have a similar need but want to display the icon in a WPF app. is there some way to convert that glyph icon (which i believe is in a UWP format BitmapImage) into something like a bitmap that could be displayed in a WPF app?

**Comment by oldnewthing** [comment]
This doesn't appear to be a question about the sample itself but rather a question about how to consume a BitmapImage in a WPF app. You can open a support case with our Developer Support team. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
