### ISSUE TITLE
C# Examples using Mixed Reality

### ISSUE THREAD

**Issue by zakkar1** [Microsoft/Windows-universal-samples#768]
Hi ,
So far all the examples for the Holographic solutions are made using CPP.
Can we have those examples using C# ?

thank you

**Comment by demonixis** [comment]
Hello,

I'm in the same situation, I tried the Template of [this repo](https://github.com/EmergingExperiencesMVP/MixedRealityProjectTemplates) but it's also for HoloLens only.

A simple example Inside a cube may be great. The idea is to use this work with the MonoGame Framework.

Please keep up posted.

**Comment by oldnewthing** [comment]
It looks like one is in the pipeline.

**Comment by oldnewthing** [comment]
See the new BasicHologram sample in [v5.0.5](https://github.com/Microsoft/Windows-universal-samples/releases/tag/v5.0.5).
