### ISSUE TITLE
how to deploy to xbox?

### ISSUE THREAD

**Issue by joshuastray** [Microsoft/Windows-universal-samples#77]
Hi, I'm using win10 insider preview and visual studio 2015 RC to develop the uwp app. How can I deploy my apps to my xbox one? Is there any information about this? Thanks a lot!

**Comment by AdamBraden** [comment]
Thank you for your interest in the Windows 10 platform.  Unfortunately, this is no the correct forum for this discussion.  I recommend you follow the xbox site for more information - http://www.xbox.com/en-US/developers
