### ISSUE TITLE
AdventureWorks - how does it work

### ISSUE THREAD

**Issue by mcosmin222** [Microsoft/Windows-universal-samples#772]
Hello,

I took a look at the AdventureWorks sample for Cortana integration, and I cannot for the life of me understand how a normal user is supposed to interact with this sample. There are no visual cues like in other samples, no obvious buttons to press.

Is there something I am missing?

**Comment by oldnewthing** [comment]
You click on a trip to edit its details, or click Add Trip to add a new trip. There's not much to the app. The sample is really about Cortana integration.
