### ISSUE TITLE
<CollectionViewSource d:source> in SemanticZoomPage.xaml 

### ISSUE THREAD

**Issue by shakir820** [Microsoft/Windows-universal-samples#774]
Hi, I am learning about SemanticZoom control. In     SemanticZoomPage.xaml    u have used "d:source" for the CollectionViewSource. I cannot understand the purpose of using "d:source". And you have also defined another source of source. I am just confused. And what is "d:DesignData" ? 

The sample that I have been studying is "XAML Controls Gallery".

**Comment by shakir820** [comment]
here is the code : 

`<CollectionViewSource x:Name="cvsGroups" Source="{x:Bind Groups}" IsSourceGrouped="True" ItemsPath="Items"
                              d:Source="{Binding Groups, Source={d:DesignData Source=/DataModel/ControlInfoData.json, Type=data:ControlInfoDataSource}}"/>`

**Comment by oldnewthing** [comment]
This is [documented on MSDN](https://msdn.microsoft.com/en-us/library/cc189061%28v=vs.95%29.aspx?f=255&MSPPError=-2147217396).

> d: (http://schemas.microsoft.com/expression/blend/2008) 
> The d: XAML namespace is intended for designer support, specifically designer support in the XAML design surfaces of Microsoft Visual Studio and Microsoft Expression Blend. The d: XAML namespace enables designer attributes on XAML elements. These designer attributes only affect the design aspects of how XAML behaves. The designer attributes are ignored when the same XAML is loaded by the XAML parser, and the application runs.
