### ISSUE TITLE
CameraStartKit cpp build error: Application is not supported in a WPF project

### ISSUE THREAD

**Issue by jialiuBellus3d** [Microsoft/Windows-universal-samples#775]
Using Win10 with VS2015
When I try to build the project got a bunch of this error 
"Application/Page/SolidColorBrush is not supported in a WPF project"
Then I tried to install some Reference like "WindowsBase" or "PresentationFramework", still won't build

Also tried js project, this error showed up.
""10.0.16299.0" is not a supported value for TargetPlatformVersion. Please change it on the Project Property page."
After I changed it to my laptop default version 10.0.14393.0
It runs, but everytime I press the capture button, an exception crashed the app
"an unhandled win32 exception occurred in WWAHost.exe"

**Comment by oldnewthing** [comment]
You need to install the [Fall Creators Update SDK](https://blogs.windows.com/buildingapps/2017/10/10/windows-developer-day-london-windows-10-fall-creators-update-sdk-availability/#53b5bBPRGjWzhha0.97) to build from master.
