### ISSUE TITLE
Invalid window handle. (Exception from HRESULT: 0x80070578)

### ISSUE THREAD

**Issue by ajos6183** [Microsoft/Windows-universal-samples#777]
I get the system exception "Invalid window handle. (Exception from HRESULT: 0x80070578)" when using the following code in a VB.NET Winform Application:
> 
        'Dim savePicker As New FileSavePicker With {.DefaultFileExtension = ".3mf", .SuggestedStartLocation = PickerLocationId.Desktop, .SuggestedFileName = "3D Model"}
        'savePicker.FileTypeChoices.Add("3MF File", New List(Of String) From {".3mf"})
        'Dim StorageFile = Await savePicker.PickSaveFileAsync`

I have imported the correct references from this [guide ](https://blogs.windows.com/buildingapps/2017/01/25/calling-windows-10-apis-desktop-application/#82zbCMUyDCrAAUEi.97) and i am able to use other UWP libraries such as `Windows.Graphics.Printing3D`.

Your help is appreciated!

**Comment by anpilley** [comment]
FileSavePicker doesn't have the DualApiPartition attribute set, so it can only be used from within a UWP Packaged app, or a win32 app that's been wrapped in the Desktop to UWP Bridge (to be uploaded to the store). 

Printing3D APIs have the DualApiPartition attribute, which is why they work.

**Comment by ajos6183** [comment]
Thanks Andrew, the reason why i was using this was to create a `StorageFile` which is required by the `Windows.Graphics.Printing3D` for saving the 3mf package.

I found a way around `FileSavePicker` not working by using:
`Dim StorageFile = Await Windows.Storage.StorageFile.GetFileFromPathAsync("...directory of a random 3mf file...")`

Is there a better way of doing it?

**Comment by oldnewthing** [comment]
Since you are a desktop app, you can just use the regular `GetOpenFileName` function to get a file from the user. Convert it to a `StorageFile` with `StorageFile.GetFromPathAsync`.
