### ISSUE TITLE
Sms Example did not work !!

### ISSUE THREAD

**Issue by harrypotter06** [Microsoft/Windows-universal-samples#778]
I testet the SMS Example, but "Device" everytime "null".
Also on Windows Mobile 10 - 

On device = SmsDevice2.GetDefault() - it will be crashed

**Comment by oldnewthing** [comment]
I've asked the feature team to investigate.

**Comment by sohirani** [comment]
Please use fieldmedic to submit the issue with logs as described here: https://docs.microsoft.com/en-us/windows-hardware/test/mobile-tracing/use-field-medic-to-generate-a-report

**Comment by harrypotter06** [comment]
Thank you @sohirani - There is a old Problem with Microsoft. 
Send issues - no reaction. For 2 years i send Microsoft a Issue with the Media Player. Now, no suolution. The issue exist again. 

Okay, in next stepps i send the Report to Microsoft.

**Comment by oldnewthing** [comment]
Let us know when you have the logs.
