### ISSUE TITLE
XamlCommanding sample - Scenario8 - DynamicCommandBar - forever in MeasureOverride method

### ISSUE THREAD

**Issue by Klepeto** [Microsoft/Windows-universal-samples#779]
When I run Scenario 8 in XamlCommanding sample (C#), app freezes. It calls the `MeasureOverride `method over and over.

**Comment by oldnewthing** [comment]
Duplicate of issue #250.

**Comment by cwey** [comment]
Any progress on this? I am running into the same issue.
