### ISSUE TITLE
[SpeechAndTTS][Scenario_ContinuousDictation]-SpeechRecognition

### ISSUE THREAD

**Issue by Ramseem** [Microsoft/Windows-universal-samples#781]
Please help,
SpeechRecognition only support "en-US" as SupportedTopicLanguages. I tested on Japanies working with kortana successfully but does not support for SpeechRecognition in Dictation mode. I need a SpeechRecognition dictation mode for languages that are supported by Kortana. 
Thanks and Regards
Ramseem.A

**Comment by oldnewthing** [comment]
This doesn't appear to be an issue with the sample. The sample correctly reports that English is the only available language. If you are asking about how to add support for other languages, you can open a support case with our Developer Support team:

1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
