### ISSUE TITLE
Semantic Zoom like Start Menu

### ISSUE THREAD

**Issue by shakir820** [Microsoft/Windows-universal-samples#782]
I have read the sample for the Semantic Zoom in XAML UI BASICS. I can create now. But I cannot implement like the Start Menu. I have searched the internet for this. But there is no solution or sample for this type of Semantic Zoom. I need your help. I am requesting Microsoft to provide me such solution.    

![startmenusemanticzoom](https://user-images.githubusercontent.com/20181621/32657521-42718964-c640-11e7-881b-f2c46c88fe1b.jpg)

**Comment by oldnewthing** [comment]
This is not a question about the sample. You can open a support case with our Developer Support team:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
