### ISSUE TITLE
Not being able to manipulate the Resolution or FrameRate in UWP/Win IOT Application. 

### ISSUE THREAD

**Issue by LPAMNijoel** [Microsoft/Windows-universal-samples#783]
I'm working on a win IOT application using the Camera Resolution Sample to try to configure my Microsoft Life Cam-3000 to a custom Res/FPS for my win IOT application on the raspberry pi 3. Simply. the current FPS/Resolution that my raspberry pi 3 is set to when i plug the camera in to the pi and initiate the camera to preview the fed lags really bad and it glitches. Any suggestions or ideas? I tried to initially set the FPS and calculate it on my own but i get this exception -> " An unhandled exception of type 'System.AccessViolationException' occurred in System.Private.CoreLib.ni.dll
Attempted to read or write protected memory. This is often an indication that other memory is corrupt." Any suggestions or ideas? I'm kind of at my wits end trying to configure this camera programically.

**Comment by oldnewthing** [comment]
This isn't a question about the sample in this repo. You can open a support case with our Developer Support team:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.

**Comment by LPAMNijoel** [comment]
Thank you very much @oldnewthing!
