### ISSUE TITLE
SDK Build 16299 - Apps crashed Windows.UI.Xaml.dll

### ISSUE THREAD

**Issue by harrypotter06** [Microsoft/Windows-universal-samples#784]
Hello,
we have a issue only on Build 16299. Tha Apps, (Acrylic Fluent!) crashed after 1-6 hours.
Debug from Visual Studio also crashed!.

Event Log:
Name des fehlerhaften Moduls: Windows.UI.Xaml.dll, Version: 10.0.16299.15, Zeitstempel: 0x4e05d078
Ausnahmecode: 0xc000027b
Fehleroffset: 0x00893c9a
ID des fehlerhaften Prozesses: 0x76f8
Startzeit der fehlerhaften Anwendung: 0x01d35a2ba8007133

We use Acrylic Background like this c# Code:
  Windows.UI.Xaml.Media.AcrylicBrush myBrush = new Windows.UI.Xaml.Media.AcrylicBrush();
  myBrush.BackgroundSource = Windows.UI.Xaml.Media.AcrylicBackgroundSource.HostBackdrop;
  myBrush.TintColor = Color.FromArgb(255, 255, 255, 255);
  myBrush.FallbackColor = Color.FromArgb(255, 255, 255, 255);
  myBrush.TintOpacity = 0.26999999396503;
  Grid1.Background = myBrush;

On older Devices, the App didn't Crash. I think: On older OS, we use the Default Theme Background.

**Comment by oldnewthing** [comment]
This doesn't appear to be an issue with the samples in this repo, but rather a platform issue. You can open a support case with our Developer Support team:

1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.

**Comment by harrypotter06** [comment]
Hello @oldnewthing , i have open a Service Request. But for customers is it not a correct solution, if customers found a bug.

**Comment by oldnewthing** [comment]
This is the samples repo, not the OS repo. We cannot fix OS bugs here.
