### ISSUE TITLE
multiple BLE device connection issue Windows 10

### ISSUE THREAD

**Issue by jigipatel** [Microsoft/Windows-universal-samples#785]
Hello,
My requirement is to "connect and send signal to 11 BLE device" at the same time i developed my whole UWP application but now i'm facing issue.my app is not able to communicate with 11 BLE device at a time i don't understand whats wrong i checked all scenario with multiple changes in my app but still i'm not satisfied. is there windows device problem ?
i'm using feather bluefruit 32u4 BLE slave device and windows 10 compbook as a master.please help me.

**Comment by oldnewthing** [comment]
This does not appear to be an issue with a sample in this repo. You can open a support case with our Developer Support team:

1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
