### ISSUE TITLE
Question about Custom Capability sample

### ISSUE THREAD

**Issue by aquadra** [Microsoft/Windows-universal-samples#787]
I don´t know if it is the right forum for this question...
I am trying to understand HSA Requirements and limitations... so one of my questions about that is: 
Is it possible and allowed to  UWP App to RPC communicate with a .Net Windows Service?

**Comment by oldnewthing** [comment]
Sorry, this isn't a question about the sample in this repo. You can open a support case with our Developer Support team:

1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.

**Comment by cc-cortes** [comment]
As oldnewthing said, this isn't the correct forum for that question. The UWP App can be an RPC client and communicate to a .Net Windows Service. If the service has not ACL'ed the RPC endpoint than any app can communicate with it. However if it is ACL'ed using a Custom Capability, then the UWP App needs the right custom capability defined. Here is a link to [documentation](https://docs.microsoft.com/en-us/windows-hardware/drivers/devapps/creating-a-custom-capability-to-pair-driver-with-hsa) to go with the [sample](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/CustomCapability).
