### ISSUE TITLE
Can not initialize Camera on Windows IoT Core 17035

### ISSUE THREAD

**Issue by v-liujxu** [Microsoft/Windows-universal-samples#788]
When i tested the Camera resolution sample on windows iot core 17035, there was an exception so that can not initialize the camera device. But it works on 15063 and 16299.

> Exception thrown: 'System.Runtime.InteropServices.COMException' in System.Private.CoreLib.ni.dll
WinRT information: A specified logon session does not exist. It may already have been terminated.

**Comment by oldnewthing** [comment]
I've asked the feature team to investigate.

**Comment by oldnewthing** [comment]
Thanks for reporting the problem. The feature team believes this is a duplicate of an issue that they have been tracking internally, and the fix will be in build 17041.

**Comment by jschweda** [comment]
Is there already a date for 17041? Cognitive Samples Intelligent Kiosk is also not working.

**Comment by oldnewthing** [comment]
Looks like [17063 went out in mid-December](https://blogs.windows.com/windowsexperience/2017/12/19/announcing-windows-10-insider-preview-build-17063-pc/).
