### ISSUE TITLE
JS Ink example unusable with a pen

### ISSUE THREAD

**Issue by Rhywden** [Microsoft/Windows-universal-samples#792]
Just an FYI: If you build the Javascript Ink sample you will run into some issues making the example unusable. At least if you use a pen and not the mouse.

Basically, your canvas is too big for the screen (at least on a Surface Book) and this makes the canvas scrollable in the x- and y-direction. And when you try to draw on the canvas with a pen, the *scrolling* gesture recognizer captures the movement of the pen (if you try to draw something longer than 3 mm) and the function `handlePointerMove(evt)` is never called.

If I instead use the mouse and left click then everything works as it should.

Same thing happens with the pen in eraser mode - `handlePointerDown(evt)` recognizes the event but everything else after that is swallowed by the scrolling gesture of the canvas.

If I press and hold the button (i.e. the right mouse) on the pen then it begins to paint as well.

**Comment by oldnewthing** [comment]
I've asked the feature team to investigate.

**Comment by bezdev** [comment]
One needs to set pen-action to none on the scrollable #canvasGroup to prevent pen from scrolling the page:

```
#canvasGroup
{
    display: block;
    position: relative;
    left: 0px;
    right: 0px;
    top: 0px;
    bottom: 0px;
    width: 100%;
    height: 100%;
    overflow: scroll;
    z-index: 0;
    pen-action: none;
}
```

**Comment by oldnewthing** [comment]
We'll incorporate this fix into the next update. Thanks for reporting the issue.
