### ISSUE TITLE
Microsoft.NETCore.UniversalWindows is Missing from References in C# Based Projects

### ISSUE THREAD

**Issue by laultman** [Microsoft/Windows-universal-samples#793]
Downloaded the samples and followed the Notes section explicitly. Multiple projects fail in C# because the Microsoft.NETCore.UniversalWindows reference is missing. These same samples work for JS and CPP. Once the missing reference is added the C# version compiles and runs.
The error is: The type or namespace 'System' is missing. This is easy to spot just open a xxxxCS project and open Properties/AssemblyInfo.cs.
If you build in this condition you get multiple errors: Predefined type 'System.xxxx' is not defined or imported. 
Adding the missing NuGet reference to the project reference fixes the issues.

**Comment by oldnewthing** [comment]
Can you be specific which samples are affected? Many samples use `project.json` to create the automatic references to .NET; they shouldn't need to be added explicitly.
