### ISSUE TITLE
no DirectShow samples

### ISSUE THREAD

**Issue by iontodirel** [Microsoft/Windows-universal-samples#795]
I'm not interested in the Windows Universal samples, but in the old "multimedia" samples that were part of Windows SDK 7, where can I find those? The Windows 7 SDK does not install on Windows 10. There are perfectly good DirectShow APIs that the universal platform is built on to, that the Windows 8 and 10 SDKs does not acknowledge that it exists.

**Comment by oldnewthing** [comment]
I think you're looking for the [Windows classic samples](https://github.com/Microsoft/Windows-classic-samples/) repo.

**Comment by iontodirel** [comment]
That did not contain the DirectShow samples I were looking for, I had to go to an old Windows 7 machine, download and install the full Windows 7 SDK, and get the sample from there.

**Comment by oldnewthing** [comment]
Which sample are you specifically looking for? All of the old Windows 7 samples should be in [the Samples\Win7Samples directory](https://github.com/Microsoft/Windows-classic-samples/tree/master/Samples/Win7Samples). If any are missing let me know and I'll try to hunt them down.
