### ISSUE TITLE
Camera Face Detection Sample - camera rotation on mobile

### ISSUE THREAD

**Issue by hupo376787** [Microsoft/Windows-universal-samples#796]
Hi, I'm using CameraFaceDetection.sln. I only have external camera, the internal one is broken. The camera preview rotate is normal on my pc (Letter **ABCDEFG** rotate normal). But when I run on the emulator, the preview image rotate 90°(Emulator can't use external camera).

![image](https://user-images.githubusercontent.com/14960168/33230572-fd0709ac-d220-11e7-83b9-bd42b2398f59.png)

![image](https://user-images.githubusercontent.com/14960168/33230577-2035d732-d221-11e7-894b-99d9a87dfbb9.png)

At the same time, system camera app rotate ok.

![image](https://user-images.githubusercontent.com/14960168/33230620-ec66151a-d221-11e7-8ee0-b5293665bacb.png)

I have disabled all the rotation code, but still rotate 90°. I want to know why.

**Comment by oldnewthing** [comment]
I've asked the feature team to investigate.

**Comment by hupo376787** [comment]
@oldnewthing Great, thanks, man.

**Comment by hupo376787** [comment]
Hi, how is everything going on?

**Comment by oldnewthing** [comment]
The feature team says that the sample defaults to landscape. The system camera app used to default to landscape, but it changed and now defaults to portrait. Both the sample and the system camera app support rotation. You can simulate this in the emulator by using the rotation buttons, and you can get both apps to have the same orientation by using the rotation buttons.

**Comment by hupo376787** [comment]
Hi, I can't see any update in the sample code. The last update was 3 months ago.
