### ISSUE TITLE
SplitView sample needs to be updated to point to NavigationView in AppUIBasics

### ISSUE THREAD

**Issue by hawkerm** [Microsoft/Windows-universal-samples#797]
The SplitView's Documentation and Related Controls in the AppUIBasics sample needs to be updated:

![image](https://user-images.githubusercontent.com/8959496/33249729-f576babe-d2e0-11e7-8f8d-b4fdcd0fefd6.png)

It should point to the NavigationView now as well.

Auxiliarly, is the XamlNavigation sample still needed?  Or should it be updated to just show the NavigationView?

**Comment by oldnewthing** [comment]
I've asked the feature team to investigate.

**Comment by oldnewthing** [comment]
The NavigationView sample has been folded into the AppUIBasics sample, so the links are correct (now).
