### ISSUE TITLE
BackgroundTask sample crash

### ISSUE THREAD

**Issue by mjsabin01** [Microsoft/Windows-universal-samples#8]
Hello, I have noticed some crashes in the BackgroundTask sample.  It seems that with scenario 3 & 5 if you register, unregister, and then re-register, the app will crash with the following details:

System.Exception was unhandled by user code
  HResult=-2147023080
  Message=Not enough quota is available to process this command. (Exception from HRESULT: 0x80070718)
  Source=Windows
  StackTrace:
       at Windows.ApplicationModel.Background.BackgroundTaskBuilder.Register()
       at BackgroundTask.BackgroundTaskSample.<RegisterBackgroundTask>d__18.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
       at BackgroundTask.ServicingCompleteTask.<RegisterBackgroundTask>d__3.MoveNext()
  InnerException:

**Comment by jefinch20** [comment]
We discovered an OS bug that could result in this error being returned by BackgroundTaskBuilder.Register. It should be fixed in Windows 10 build 10240.

Please let us know if you still see this!

**Comment by Viachaslau-Zinkevich** [comment]
Hi. I get this kind of error occasionally when trying to register ApplicationTrigger background task. OS version is 10240.

**Comment by euteneue** [comment]
I am currently seeing this with build 10586 on iot. After the background task crashes, the app cannot register the background task upon startup again. Every time BackgroundTaskBuilder.Register is called, the above exception is thrown.

**Comment by MMalikKhan** [comment]
i am also getting the same error on the UAP,Version=10.0.10240.0. I get this error while registering the task, i am not sure why it works for few times when you freshly install the app and then just stop working.. i am registering this from another BackgroundTask.. do you think is this got to do anything with it? any help will be appreciated

BackgroundTransferCompletionGroup completionGroup = new BackgroundTransferCompletionGroup();

                BackgroundTaskBuilder builder = new BackgroundTaskBuilder();
                builder.TaskEntryPoint = "xyz";
                builder.SetTrigger(completionGroup.Trigger);

                BackgroundTaskRegistration taskRegistration = builder.Register();

**Comment by guidodocter** [comment]
In case you want to re-register the task, don't forget to unregister previously registered instances first. There is a quotum on the number of registrations, that's where this error comes from. You can check if a task was previously registered by checking
`var isAlreadyRegistered = Windows.ApplicationModel.Background.BackgroundTaskRegistration.AllTasks.Any(t => t.Value?.Name == yourtaskname);`

**Comment by mnikonov** [comment]
This issue started reproduce again on Windows 1903 build 18362.175
