### ISSUE TITLE
Manifest file settings not recognized when deploying the bluetoothadvertismentsample

### ISSUE THREAD

**Issue by Injac** [Microsoft/Windows-universal-samples#80]
Hi,

I have updated my phone to the latest WIndow 10 build for Windows Phone. When I build the "bluetoothadvertismentsample" I get the following exception:

{System.UnauthorizedAccessException: Access is denied.

Your App does not have permission to use Bluetooth in the background. Make sure you have declared the Task Type 'bluetooth' in your manifest.
   at Windows.ApplicationModel.Background.BackgroundTaskBuilder.Register()
   at BluetoothAdvertisement.Scenario4_BackgroundPublisher.<RunButton_Click>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__3(Object state)
   at System.Threading.WinRTSynchronizationContext.Invoker.InvokeCore()}

I have attached a screenshot that clearly shows that the Task-Type was added by the creator of the sample.

Any ideas how to fix this?

![appmanifest](https://cloud.githubusercontent.com/assets/1821384/8416949/13b03a94-1e5e-11e5-95e2-5317a57c0501.png)

**Comment by RuslanSCH** [comment]
Hello,

I have same problem! 
Know anybody how to fix this now?

**Comment by kpathakota** [comment]
Hey @RuslanSCH @Injac! The issue no longer repros with the RTM push of the samples.  To test on mobile device, you may need to wait until the next mobile flight update of 10240 or higher.  This sample also won't work on the emulator (the sample will complain that there's no Bluetooth radio).

**Comment by lisaong** [comment]
The sample's readme.md has been updated to state the requirement on having a real Bluetooth radio.

**Comment by Injac** [comment]
@lisaong, @kpathakota Thanks for the update. Hope to see 10240 soon on my device.

**Comment by Pawel2420** [comment]
Hi, 
I cannot get work properly on Lumia 435 Windows 10 Mobile  10.10512.1000  this sample https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/BluetoothAdvertisement in Scenario 3 & 4. The error message is: 
"WinRT information: Your App does not have permission to use Bluetooth in the background. Make sure you have declared the Task Type 'bluetooth' in your manifest."

I have checked and  the Task Type 'bluetooth' in manifest is declared.  Do you know where is the problem?

**Comment by tendimsol** [comment]
same for 10512 here
