### ISSUE TITLE
SpeechRecognizer crashes UWP in example app.

### ISSUE THREAD

**Issue by cchannon** [Microsoft/Windows-universal-samples#802]
When executing the Speech Synthesis sample app and another app I created based on this one, the SpeechRecognizer.RecognizeAsync and RecognizeAsyncWithUI methods cause the app to crash or to return an empty result with 0 seconds duration. 

Using: Raspberry Pi 2 with Sabrent USB audio input (only usb audio input on Win 10 IOT Core compatibility list).

**Comment by oldnewthing** [comment]
I've asked the feature team to investigate.

**Comment by oldnewthing** [comment]
The feature team reports that they are unable to reproduce the problem on a Dragonboard running the latest Inside build.
