### ISSUE TITLE
Grouped ListView with Virtualization

### ISSUE THREAD

**Issue by bgulrich** [Microsoft/Windows-universal-samples#803]
I'm looking for a away to use a ListView to display a large data set with random access data virtualization, but I also want the ListView to be grouped.  Is there a recommended way to accomplish this?

My understanding is that CollectionViewSource's View does not impement IItemsRangeInfo, so data virtualization is not supported.  My research has led me to believe that my best bet is to source my ListView with a custom class that implements both IItemsRangeInfo and ICollectionView.  Will this accomplish what I want and is it the preferred (easiest) method?  Is ICollectionView the only mechanism for getting a ListView to group its items?

Thanks!

**Comment by oldnewthing** [comment]
This is not an issue with a sample in this repo. You can open a support case with our Developer Support team. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
