### ISSUE TITLE
ComplexInk run on local machine error DEP0700

### ISSUE THREAD

**Issue by tinysniper** [Microsoft/Windows-universal-samples#804]
After building and deployting complexink project with vs2017, there is DEP0700 error when running it on local machine.
Anyone please help to tell me the reason?

> DEP0700: Registration of the app failed. [0x80073CF9] Failed to initialize a MRT resource manager for the package: Microsoft.SDKSamples.ComplexInk.CPP_1.0.0.0_x64__8wekyb3d8bbwe and file path: resources.pri

**Comment by oldnewthing** [comment]
I cannot reproduce the problem. The current sample on the master branch (16299) builds, deploys, and runs on my machine. This sounds like some sort of configuration problem on your system.
