### ISSUE TITLE
Geolocation Unautoirized Access in Background Task

### ISSUE THREAD

**Issue by rg-burton** [Microsoft/Windows-universal-samples#807]
Downloaded the November Update of samples and ran the Geolocation Sample.  Using the Background task always gives a disabled (Unauthorized Access) with Windows Insider Build 17046.  Has been doing this on the last several Insider Builds.  I also have another UWP app I have been using for over a year that gives the same error on these builds.  Both the Geolocation Sample and my program work fine on Build 16299.

The Sample app shows Disabled in the background location sample and setting a breakpoint in the background application in Visual Studio shows it getting the Unauthorized access exception.

![capture](https://user-images.githubusercontent.com/29922868/33799959-13c0a37a-dcfc-11e7-9334-c49c91283d4c.PNG)
![capture1](https://user-images.githubusercontent.com/29922868/33799960-13d64f40-dcfc-11e7-8c65-b9362c779cf6.PNG)

Using November Sample Update C# version of Geolocation
Using Insider Build 17046
Visual Studio 15.4.5
Location Permission is given to sample app when run and verified in Location settings.
PC has default location set in settings as well.

**Comment by Jet-Chan** [comment]
Sounds Good!

**Comment by oldnewthing** [comment]
I've asked the feature team to investigate.

**Comment by Cheoljin** [comment]
This is from the feature team.

@rg-burton are you still having this issue?

I have tested this with a recent Insider build, i.e., 17080. rs_onecore_sigma_dplat (as of 01/17/2018), but it does not have the issue. It successfully registers the background task in the sample app.

On the other hand, there was a similar report before around this build number, and it has been resolved afterwards: https://github.com/Microsoft/Windows-universal-samples/issues/786

If you have this issue now, please add your comment and contact info (email etc) with build edition (e.g. Enterprise), number, and branch (rs_prerelease).

**Comment by rg-burton** [comment]
It does appear to be resolved with the current insider build I have which is 17074.

Thanks for looking into it.
