### ISSUE TITLE
cameragetpreviewframe throws COMException

### ISSUE THREAD

**Issue by sam9116** [Microsoft/Windows-universal-samples#808]
Hi,
I'm running Windows 10 16299.125 and using the 16299 SDK, compiled with visual studio 2017 15.5.1

when I run this app(c# version) in tablet mode, switch between UWP apps (like edge), then come back to the sample app(on the second time). the app fails on await InitializeCameraAsync(); (line 158)

here's the error message
Exception thrown: 'System.Runtime.InteropServices.COMException' in CameraGetPreviewFrame.exe
WinRT information: PreviewState
Exception thrown: 'System.Runtime.InteropServices.COMException' in System.Private.CoreLib.ni.dll
WinRT information: PreviewState
Exception thrown: 'System.Runtime.InteropServices.COMException' in System.Private.CoreLib.ni.dll
WinRT information: PreviewState
Exception thrown: 'System.Runtime.InteropServices.COMException' in System.Private.CoreLib.ni.dll
WinRT information: PreviewState
An exception of type 'System.Runtime.InteropServices.COMException' occurred in System.Private.CoreLib.ni.dll but was not handled in user code
WinRT information: PreviewState
The stream number provided was invalid.
PreviewState

Is this intended? And is there something I can do to fix this?

I will also include a link to a crashdump of the preview app
[https://1drv.ms/u/s!AvUjbDh0Kcasp8EzqTn6RCEYojf3Zg](https://1drv.ms/u/s!AvUjbDh0Kcasp8EzqTn6RCEYojf3Zg)

**Comment by sam9116** [comment]
This seems to be a symptom for other camera sample apps that also does camera initialization automatically. for example: camera starter kit.

**Comment by oldnewthing** [comment]
I've asked the feature team to investigate. The failure is 0xc00d36b2 = `MF_E_INVALIDREQUEST`.

**Comment by oldnewthing** [comment]
Thanks for reporting the issue. A fix will be in the next update. There's a race condition between shutting down the old camera and initializing the new one.
