### ISSUE TITLE
GestureRecognizer not support multi styluses?

### ISSUE THREAD

**Issue by HoDuyQuang** [Microsoft/Windows-universal-samples#812]
I run **Basic Input example**. It working with hand to manipulate block shape. But if I using 2 stylus, I can't rotate it.
My device is running Win 10 Fall Creator, Visual Studio 2017 Community and supports 2 stylus at same time. Both pens are working when draw on canvas. I think **`GestureRecognizer`** was ignore this.

**Comment by oldnewthing** [comment]
This sounds like a platform issue, not a sample issue. I've asked the samples team to investigate if it's a bug in the sample, but I suspect it isn't. For platform issues, you can open a support case with our Developer Support team:

1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.

**Comment by oldnewthing** [comment]
The feature team says that this is a known limitation of the `GestureRecognizer`. It does not support using two pens to zoom or rotate. It's not a scenario that has come up yet.
