### ISSUE TITLE
Clipboard with multiple formats

### ISSUE THREAD

**Issue by sjb-sjb** [Microsoft/Windows-universal-samples#814]
The Clipboard example does not show how to put multiple formats onto the clipboard at the same time. For example, the bitmap example shows how to either put the image onto the clipboard or to provide a delayed renderer, but not how to both put the image onto the clipboard in one format and also put a delayed renderer for another format. 

How do you do it?

**Comment by oldnewthing** [comment]
This is not really a question about the sample, but rather a question about how to use the feature. You can open a support case with our Developer Support team:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
