### ISSUE TITLE
The Sample Application is unwieldy.

### ISSUE THREAD

**Issue by Joebeazelman** [Microsoft/Windows-universal-samples#815]
I absolutely dread using the Windows Universal Samples application as a reference.  It is painful to find sample code.  I am surprised this application doesn't have a precompiled library I can just download and run from either Github or the AppStore.  Currently, I have to build and download this gigantic solution just to find what I need.  Also, when you go to the documentation, it sends you to this GitHub repo where you have to face thousands of folders and files instead of a direct link to the project.   Why?  

What is wrong with Microsoft!!!!  Why can't you guys get your act together?!  It terrifies me how a multi-billion dollar corporation can operate with such mediocrity and dysfunction. For the love of humanity, please do not go into the self-driving car market.

**Comment by oldnewthing** [comment]
Sorry you are finding the experience cumbersome. You don't have to build all the samples (there are over 200 of them); just build the one you are interested in.

The documentation pages are supposed to send you directly to the specific sample. For example, the [Custom capabilities](https://docs.microsoft.com/en-us/windows-hardware/drivers/devapps/creating-a-custom-capability-to-pair-driver-with-hsa) documentation contains a direct deep link to the [Custom capabilities sample](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/CustomCapability). If there is a documentation page that points to the root of the samples repo when a deep link would be more appropriate, let me know and I'll have it updated with a deep link.

**Comment by Joebeazelman** [comment]
Yes, there are deep links, but it's not the issue.  Often when I am looking for a solution, I want to run the code to see if it is pertinent.  This is especially true when you're looking for a specific UI implementation.  Requiring developers to hunt through a giant folder, or waiting for slow ass molasses Windows to search for it, is painful. At the very least, a prebuilt executable would suffice.
