### ISSUE TITLE
CustomHidDeviceAccess Sample Doesn't Work

### ISSUE THREAD

**Issue by MelbourneDeveloper** [microsoft/Windows-universal-samples#818]
I cloned the repo, and opened this project:
Windows-universal-samples/Samples/CustomHidDeviceAccess/

I knocked the UWP version down to 15063

I changed the vidpid in the DeviceCapability of the Package.appxmanifest to hex numbers that match the Vendor ID and Product ID of the device that is attached to my computer. I know the device is attached and the vid and pid are correct because I can see them in .NET Core. 

Yet, when I run the app, no devices appear in the listbox.

**Comment by oldnewthing** [comment]
Did you also update the usage page? I've asked the feature team to investigate, but since you modified the sample, this may not technically be a samples issue.

**Comment by MelbourneDeveloper** [comment]
Since then, I've tried upgrading to the latest version of UWP, and upgrading all the NuGet packages. It still doesn't work. I believe that the DeviceWatcher class doesn't work. Since I started trying to use this sample I have gotten USB connectivity working in another project. I can read and write from the device. But, the DeviceWatcher does not work.

**Comment by siegeJ** [comment]
Seeing this same issue. No devices showing in sample project, however confirmed that I can still connect to the device in my own project using `HidDevice.FromIdAsync`

**Comment by smadasam** [comment]
In the RS5 release, the way device access was evaluated was significantly changed.  For HID specifically, we don't use the VID PID in device access policy checks as of RS5.

**Comment by jefffhaynes** [comment]
Is there any more information on this? I'm having no luck getting that sample or anything else that uses HidDevice.FromIdAsync to return a device.

**Comment by MelbourneDeveloper** [comment]
Hi @jeffhaynes. I abandoned trying to get this to work a long time ago. But, the API does work. I suggest looking at [Device.Net](https://github.com/MelbourneDeveloper/Device.Net)

It wraps the APIs for Windows, UWP, and Android. You can see how it uses FromIdAsync [here](https://github.com/MelbourneDeveloper/Device.Net/blob/90aa91e584ec2f7e25002c157ad6bd42e87aa618/src/Hid.Net.UWP/UWPHidDeviceHandler.cs#L73).

```cs
public static IAsyncOperation<hidDevice> GetHidDevice(string id) => hidDevice.FromIdAsync(id, FileAccessMode.ReadWrite);
```

These [integration tests](https://github.com/MelbourneDeveloper/Device.Net/blob/90aa91e584ec2f7e25002c157ad6bd42e87aa618/src/Device.Net.UnitTests/IntegrationTests.cs#L27) work on Windows and UWP, but I think a couple fail on UWP:

**Comment by jefffhaynes** [comment]
Thanks, I'll give it a try!

**Comment by MelbourneDeveloper** [comment]
@jefffhaynes is simply not fun on .NET/UWP. However, at least if you use Device.Net there is a decent, uniform API and it can be used across platforms.

**Comment by jefffhaynes** [comment]
That seems to have done the trick!  There does seem to be an issue where read buffers of size zero throw an exception [here](https://github.com/MelbourneDeveloper/Device.Net/blob/5e65ed6b4b1661ab651040f20ad9ed5f4940ec8a/src/Hid.Net/Windows/WindowsHidApiService.cs#L140) but I can work around that and I'll file a bug.

@oldnewthing: As for the UWP Sample, strongly recommend taking it down or making a note until you can get it working!

**Comment by MelbourneDeveloper** [comment]
@jefffhaynes would love it if you could log the details on the device .net repo and/or join the discord server over there. Posting the code and the log would be a good start

**Comment by oldnewthing** [comment]
The feature team says that the existing README for the sample covers the scenario and troubleshooting.

**Comment by paphilli** [comment]
To clarify, you can use `MuttUtil.exe -list` to check if your SuperMUTT is set to HidUsb mode or if it is still in WinUSB mode. You should not need to change the Vendor ID and Product ID in the sample for it to find the device. The MuttUtil commands towards the bottom of the README should help with proper configuration.
