### ISSUE TITLE
View The ETL File

### ISSUE THREAD

**Issue by mj430** [Microsoft/Windows-universal-samples#819]
I am not able to view the The ETL log file generated by the Logging sample in Traceview.

when i use tracerpt, it generates a big xml file, withe data which is not very readable. Is there a tool which can be used to view the trace messages line by line. 

Where I can apply some filters

**Comment by oldnewthing** [comment]
This isn't really a question about the sample any more. You can open a support case with our Developer Support team:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.

**Comment by mj430** [comment]
Thanks

**Comment by mj430** [comment]
WPA does not shows the exact logged message . Though in the xml file generated by tracerpt, I see the logged message

- To view with Windows Performance Toolkit (WPT): wpa.exe "C:\Users\mohit\AppData\Local\Packages\Microsoft.SDKSamples.Logging.CS_8wekyb3d8bbwe\LocalState\FileLoggingSessionScenario_LogFiles\Log-180110-095905932.etl"

**Comment by oldnewthing** [comment]
> Note that decoding TraceLogging events requires Windows 10. Earlier versions
> of Windows can only reliably decode the simple (manifest-based) events.

Are you running the Windows 10 version of tracerpt?

**Comment by RongshengXu** [comment]
Hi, @mj430 

In order to view etl in WPA, the  etl needs to go through merge stage to add meta-data from xml. for your case, you can use the following command:

xperf.exe -merge "C:\Users\mohit\AppData\Local\Packages\Microsoft.SDKSamples.Logging.CS_8wekyb3d8bbwe\LocalState\FileLoggingSessionScenario_LogFiles\Log-180110-095905932.etl"  merged.etl

wpa.exe merged.etl

**Comment by RongshengXu** [comment]
@mj430 
In general, after creating a trace, you can use
“
xperf -stop MySession 
xperf -merge MyFile.etl merged.etl
wpa merged.etl
”
Or 
“
xperf -stop MySession -d merged.etl
wpa merged.etl
”

**Comment by oldnewthing** [comment]
I will update the sample to include these steps.
