### ISSUE TITLE
Unable to deploy OCR Sample to HoloLens

### ISSUE THREAD

**Issue by Caltato** [Microsoft/Windows-universal-samples#821]
I am unable to deploy the application to HoloLens because the Windows Universal Runtime version is not the same. I've tried updating the HoloLens but it made no difference. Is there anything I can do to get it working on the HoloLens?

**Comment by TheGuardianWolf** [comment]
If you set the backwards compatibility to Windows Anniversary edition from the project's property pages, does that work?

**Comment by Rusianka** [comment]
@Caltato, what is the current status of the issue? Were you able to resolve it?

**Comment by oldnewthing** [comment]
The feature team cannot reproduce the problem:

> Verified deploying OCR sample app to HoloLens with no problem. Also verified OCR functionality test with sample image and captured image on HoloLens works ok. 
>
> Here is the app build and os build used for test:
> OCR app target version: Windows 10, version 1809(build 17763)
> HoloLens OS version: Windows 10.0.17763.134, the [October 2018 release build for HoloLens](https://docs.microsoft.com/en-us/windows/mixed-reality/release-notes-october-2018)
