### ISSUE TITLE
the WebSocket couldn't connect to LAN server

### ISSUE THREAD

**Issue by fatfatson** [Microsoft/Windows-universal-samples#824]
I have tried the websocket demo , it could only connect to "localhost",  and couldnot connect to  any IP , even the same machine.

OS&SDK ver: 16299

**Comment by DavidGoll** [comment]
Please try connecting to ws://echo.websocket.org and let me know whether or not that works.

**Comment by fatfatson** [comment]
@DavidGoll yes it can connect to echo.websocket.org, but couldn't connect to my LAN server with IP.

the server is writen by nodejs, and anyother websocket client could connect, except the UWP, but if replacing the IP to localhost, it could. that's very strange.
```
var http = require('http');
var WebSocketServer = require('websocket').server;
var server = http.createServer(function(request, response){ });

server.listen(19842, function(){ });

wsServer = new WebSocketServer({
        httpServer: server
});

wsServer.on('request', function(request) {
    var connection = request.accept(null, request.origin);
    console.log("come connection", request.origin);

    connection.on('message', async function(message) {
        if (message.type === 'utf8') {
            console.log("recv: %s", message.utf8Data);
        }
    });

    connection.on('close', function(connection) {
        console.log("close connection");
    });
});


var WebSocketClient = require('websocket').client;
var client = new WebSocketClient();

client.on('connectFailed', function(error) {
    console.log('Connect Error: ' + error.toString());
});

client.on('connect', function(connection) {
    console.log('WebSocket Client Connected');
    connection.on('error', function(error) {
        console.log("Connection Error: " + error.toString());
    });
    connection.on('close', function() {
        console.log('echo-protocol Connection Closed');
    });
    connection.on('message', function(message) {
        if (message.type === 'utf8') {
            console.log("Received: '" + message.utf8Data + "'");
        }
    });

    function sendNumber() {
        if (connection.connected) {
            var number = Math.round(Math.random() * 0xFFFFFF);
            connection.sendUTF(number.toString());
            setTimeout(sendNumber, 1000);
        }
    }
    sendNumber();
});

client.connect('ws://192.168.1.101:19842/');

```

![image](https://user-images.githubusercontent.com/5842874/35137244-59c740d0-fd23-11e7-9a8a-51e04ec708e5.png)
![image](https://user-images.githubusercontent.com/5842874/35137273-7ec3f5e0-fd23-11e7-9cb5-f92814a754ba.png)

**Comment by DavidGoll** [comment]
Thanks for confirming. Can you clarify whether 192.168.1.101 is a different machine than localhost? Also, have you modified any of the capabilities in the application manifest? The sample by default should be able to access the local subnet. And finally, have you enabled Sharing on the local computer? That can impact the treatment of the LAN addresses.

**Comment by DavidGoll** [comment]
I should add that this is related to UWP Network Isolation. See [How to enable loopback and troubleshoot network isolation](https://msdn.microsoft.com/en-us/library/windows/apps/hh780593.aspx) for a tool that can help diagnose the issue you are seeing.

**Comment by fatfatson** [comment]
server/client/UWP all runs in the same machine whose IP is 192.168.1.101
all other clients could connect to server with either 'localhost' or '192.168.1.101'
but UWP could only connect with 'localhost'
i don't think it's a external config problem because other clients works correctly in the same env.

**Comment by DavidGoll** [comment]
> server/client/UWP all runs in the same machine whose IP is 192.168.1.101

Thanks. This sounds like an idiosyncrasy with Network Isolation. I will check with the Network Isolation team and update this issue with more information. In the meantime, because this is not an issue with the sample, and you are able to use 'localhost', I am closing this issue.

> other clients works correctly in the same env

I'll reiterate that UWP Network Isolation does not apply to non-UWP clients, thus the difference in behavior.

**Comment by fatfatson** [comment]
thanks @DavidGoll 
but what should I do to make it availabe?
all the network capabilities are enabled for the app
