### ISSUE TITLE
Bottom controls do not stretch in full screen on XBox One

### ISSUE THREAD

**Issue by RexfelisLOC** [Microsoft/Windows-universal-samples#825]
When the player is set to FullWindow mode, the controls do not stretch to fill the bottom of the screen like they do on the PC.

**Comment by oldnewthing** [comment]
Which sample are you referring to?

**Comment by RexfelisLOC** [comment]
My apologies, it's the XamlCustomMediaTransportControls sample.

**Comment by oldnewthing** [comment]
Thanks. I'll ask the feature team for that sample to investigate.

**Comment by oldnewthing** [comment]
The feature team explains that this is by design. The controls do not go all the way to edge in order to stay within the [TV-safe area](https://docs.microsoft.com/en-us/windows/uwp/design/devices/designing-for-tv#tv-safe-area).

**Comment by RexfelisLOC** [comment]
We have turned off the TV safe area so our apps can stretch to the bounds for most modern TVs using the following line of code:

ApplicationView.GetForCurrentView().SetDesiredBoundsMode(ApplicationViewBoundsMode.UseCoreWindow);

We obtained this info from the following Microsoft website:

https://docs.microsoft.com/en-us/windows/uwp/xbox-apps/turn-off-overscan

Shouldn't the player detect this and adjust accordingly?

**Comment by oldnewthing** [comment]
This is not a question about the sample any more. This is a question about the platform. You can open a support case with our Developer Support team.
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
