### ISSUE TITLE
CustomCapability - C# - Invalid parameter passed to C runtime function.

### ISSUE THREAD

**Issue by pacolanciano** [Microsoft/Windows-universal-samples#826]
Hi,

Regarding the RPC communication with the NT Service, C# version:
This is not a big issue, in the sense that the sample UWP app seems to be working correctly with the NT service through static dll.
However, every time I start the app, in DebugView I see this message prompted two times by the UWP app process:
> Invalid parameter passed to C runtime function.

Any idea about what does cause it? Should I worry about it at all?

[ OS Win10 1709 (16299.192), Visual Studio 2017, provided solution and Debug - x64 configuration only]

**Comment by oldnewthing** [comment]
Haven't heard from the feature team, but I cannot reproduce this. My DebugView doesn't display anything other than "Failed to initialize."

**Comment by oldnewthing** [comment]
Feature team cannot reproduce it either.
