### ISSUE TITLE
Does NavigationView qualify as "commanding"?

### ISSUE THREAD

**Issue by SimpleSamples** [Microsoft/Windows-universal-samples#828]
The NavigationView supports menu items for navigating (commands), right? So should it be in the "Commanding" section? I think so; certainly more than the ContentDialog control should be. But I don't understand the difference between Commanding and Navigation (Navigating?); I think that many of the commanding controls can be used for navigating. Perhaps the difference is more subjective than objective, just as it is difficult to categorize a control as a container or layout control.

**Comment by oldnewthing** [comment]
The feature team says that navigation and commanding are closely tied concepts. Commanding can include things like invoking dialogs or external links, cut/copy/paste commands, etc. Navigation usually means journeying to a new section of the app. Also, NavigationView doesn't support commands, so it doesn't quite belong in commanding.
