### ISSUE TITLE
VideoPlaybak CleanUpMediaPlayerSource is incorrect

### ISSUE THREAD

**Issue by pierresa** [Microsoft/Windows-universal-samples#829]
although it is masked by syntax used:
var item = mp.Source as Windows.Media.Playback.MediaPlaybackItem;
                item?.Source?.Dispose();

item is always null and MediaPlaybackItem is not released

I am looking for the right syntax to stop media playing in background when I leave the page

**Comment by aarononeal** [comment]
That line is null because the Source was a MediaSource and not a MediaPlaybackItem so was disposed on the previous line.

If you want to stop Playback call MediaPlayer.Stop().

**Comment by pierresa** [comment]
OK, thank you
