### ISSUE TITLE
"Basic Face Tracking C# Sample" does not work (System.ArgumentException: The parameter is incorrect.)

### ISSUE THREAD

**Issue by yury-rudenko** [microsoft/Windows-universal-samples#830]
Steps to reproduce:
1. Build solution
2. Run "x86" configuration - "Debug" on Local Machine
3. "start streaming"

Video stream shows stream fine

Unexpected behaviour:
Status:
- System.ArgumentException: The parameter is incorrect.
Invalid subtype
....
![image](https://user-images.githubusercontent.com/23498430/35332305-a1101e2a-011b-11e8-9895-53f7cd724631.png)

**Comment by wsywsya119** [comment]
I have same problem. Do you fix it?

**Comment by yury-rudenko** [comment]
No, Do not fix it.

**Comment by wsywsya119** [comment]
I tried another laptop with build-in camera, I works fine.

**Comment by yury-rudenko** [comment]
Strange, but have the same error (The parameter is incorrect) for "AppService" example clicking on "Launch Background Process".

**Comment by oldnewthing** [comment]
Closing due to lack of reply. I will reopen when there is a response.

**Comment by armstrong-charles** [comment]
The issue is repro on certain webcam drivers. It is happening from await this.mediaCapture.GetPreviewFrameAsync(previewFrame).
