### ISSUE TITLE
[UWP][IoT] - Drap and Drop no longer working since Build 16299 onward...

### ISSUE THREAD

**Issue by robppug** [Microsoft/Windows-universal-samples#833]
Since the 16299 update, the sample drag-drop code has stopped working on Windows 10 IoT Core.

Same code works fine if run on my Windows 10 (x64) machine.

Also see: [https://social.msdn.microsoft.com/Forums/en-US/2df672ed-865c-42a9-a77e-ad8bdfa518fe/uwpfall-creators-update-drag-and-drop?forum=WindowsIoT#1515c916-1b60-4559-87fc-268877dc2ea7](url)

**Comment by oldnewthing** [comment]
From the forum thread, this appears to be a platform issue, not a samples issue.
