### ISSUE TITLE
How to disable Drag and Drop of Nodes in UWP TreeView?

### ISSUE THREAD

**Issue by TonyHenrique** [Microsoft/Windows-universal-samples#835]
I am running the sample Project, but noticed that if user move a node, it will go to where user dropped it.
I would like to disable this TreeNode Draggable ability.
Also is there na event to detect Drag Start, and Drop, so I may accept or cancel the action?

![image](https://user-images.githubusercontent.com/6307623/35483954-32872eee-0427-11e8-8654-771fa1276142.png)

**Comment by oldnewthing** [comment]
The control's source code is [in the repo](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/XamlTreeView/cpp/Control). You can add whatever features you like.
