### ISSUE TITLE
CustomEditControl focus

### ISSUE THREAD

**Issue by Gnitry** [Microsoft/Windows-universal-samples#836]
When I use CustomEditControl inside ContentDialog, I can't set it focused neither using keyboard tabbing nor tapping.

```xml
<ContentDialog
    x:Class="SDKTemplate.ContentDialog1"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:local="using:SDKTemplate"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    Title="TITLE"
    PrimaryButtonClick="ContentDialog_PrimaryButtonClick"
    PrimaryButtonText="Button1"
    SecondaryButtonClick="ContentDialog_SecondaryButtonClick"
    SecondaryButtonText="Button2"
    mc:Ignorable="d">

    <Grid>
        <StackPanel>
            <TextBox Text="textbox1" />
            <TextBox Text="textbox2" />
            <TextBox Text="textbox3" />
            <local:CustomEditControl IsTabStop="True"/>
        </StackPanel>
    </Grid>
</ContentDialog>

```

**Comment by oldnewthing** [comment]
This is not surprising. The custom edit control sample is only a sketch of a full edit control.

**Comment by Gnitry** [comment]
But wait. It is a sample that should show us how to make a custom control. Please, make it workable or just explain how to do it.

**Comment by oldnewthing** [comment]
The sample explicitly states

    // This class implements a custom edit control that is entirely 
    // standalone. It does not integrate with XAML focus. Instead, 
    // it manages focus explicitly by tracking pointer activity. 

The purpose of the sample is not to show a custom XAML control. It's for showing how to create a control independent of any framework. For example, you could use this to write an edit control in Direct3D.
