### ISSUE TITLE
WebAuthenticator CS Scenario 5 missing?

### ISSUE THREAD

**Issue by jaydeflix** [microsoft/Windows-universal-samples#837]
In multiple locations in the WebAuthenticator samples there is mention of "Scenario 5", but the scenarios only seem to go to 4.

From (https://github.com/Microsoft/Windows-universal-samples/blob/master/Samples/WebAuthenticationBroker/cs/Scenario2_Twitter.xaml.cs)
```
            if (access_token != null)
            {
                // Store access_token for futher use. See Scenario 5 (Account Management).
            }

            if (oauth_token_secret != null)
            {
                // Store oauth_token_secret for further use. See Scenario 5 (Account Management).
            }
```

Files: https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/WebAuthenticationBroker/cs

**Comment by oldnewthing** [comment]
Fixed in next refresh.
