### ISSUE TITLE
First NavigationViewItem overlaps with the hamburger menu button. 

### ISSUE THREAD

**Issue by oneclouddrive** [Microsoft/Windows-universal-samples#838]
The first element overlaps with the hamburger menu button.
![image](https://user-images.githubusercontent.com/14813188/35787655-95440bd4-09e4-11e8-9be0-dc820b53ccab.png)

**Comment by oneclouddrive** [comment]
It seems to an issue only on preview builds.

**Comment by oldnewthing** [comment]
I checked with the XAML team. This is a known issue with the NavigationView control. A fix on its way to the Insider branch, but it's taking a while to get there.
