### ISSUE TITLE
windows ce 6.0

### ISSUE THREAD

**Issue by sevimtel** [Microsoft/Windows-universal-samples#841]
How can I write usb driver for windows ce 6.0

**Comment by oldnewthing** [comment]
This is not a question about a sample in this repo. You can open a support case with Developer Support team. This sounds like a hardware question, so you can start at [Windows hardware engineering support](https://developer.microsoft.com/en-us/windows/hardware/support).

**Comment by sevimtel** [comment]
Hi

This is not hardware ı think this is barcode reader software drvier?

thnks

 

Sevim Tel | Genel Koordinatör, Excecutive Director
