### ISSUE TITLE
FilePickerContracts - OnCachedFileUpdaterActivated  does not fire on Before Access.

### ISSUE THREAD

**Issue by Lazzarus** [Microsoft/Windows-universal-samples#842]
OnCachedFileUpdaterActivated  never fires on the BeforeAccess Example.  (Open Picker -> Pick cached file)

To replicate. 
Stick a break point on OnCachedFileUpdaterActivated in App.xaml.custom.cs and CachedFileUpdaterUI_FileUpdateRequested in CachedFileUpdaterPage.xaml.cs
Select Open from a any Text app and select the file picker contracts app for the source
Select option 3 Pick cached file 
Add file to basket.
Select open. The breakpoints are never hit

Looking at the code, there's a method AddFileButton_Click in FileOpenPicker_CachedFile.xaml.cs
This looks to be incorrect and hiding the problem.
It creates a new file and then populates the file with some text.

For this example I would expect the CachedFileUpdate to either populate the text or update the text when 
 ReadActivationMode.BeforeAccess fires the OnCachedFileUpdaterActivated  event. 

The result is the file opens in the third party app with content but at no time is the cachedFileUpdater used.

**Comment by oldnewthing** [comment]
This looks like it's a platform issue, but I've asked the samples team to look at it anyway. You'll probably have better luck (and responsiveness) contacting Developer Support:

1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.

**Comment by iagrav** [comment]
BeforeAccess CFU trigger only covers MostRecentlyUsed List and FutureAccess List accesses and not any type of access. CFU won't trigger for this type of access. I'm updating the sample to have a proper BeforeAccess example.

**Comment by oldnewthing** [comment]
One language was updated, but the others haven't been done yet.

**Comment by oldnewthing** [comment]
Fix is published in release [v7.0.2](https://github.com/Microsoft/Windows-universal-samples/releases/tag/v7.0.2).
