### ISSUE TITLE
FilePickerContracts - 'Your using File Picker Contracts #C in another app to save a file' when saving via cached file

### ISSUE THREAD

**Issue by Lazzarus** [Microsoft/Windows-universal-samples#843]
To Replicate

Start the FilePickerContract app and make sure the GUI is showing. 
Now start the paint 3D app, create a picture and save it. 
Pick the FileContractPicker app -> Option 3 Saved to Cached file. Now Save. 
Wait a few seconds until the OnCachedFileUpdaterActivated method in App.xaml.custom.cs executes/fires
After Saving Attempt the close the FilePickerContract app and you will be presented with a dialog stating 'Your using File Picker Contracts #C in another app to save a file'

I am seeing this in my own app as well as your example my guess is deferral.Complete(); isn't releasing the deferral.

**Comment by oldnewthing** [comment]
This looks like it's a platform issue, but I've asked the samples team to look at it anyway. You'll probably have better luck (and responsiveness) contacting Developer Support:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.

**Comment by oldnewthing** [comment]
The feature team confirms that this is a platform issue and responded that they are not addressing this issue at this time. "We'll reconsider if it gets identified as an adoption blocker for a key customer scenario."
