### ISSUE TITLE
FilePickerContracts - Incorrect page size / rendering issues

### ISSUE THREAD

**Issue by Lazzarus** [Microsoft/Windows-universal-samples#844]
This can be a bit tricky to replicate but basically the page size is reported as the whole Screen size and not the dialog size some times causing layout issues. This appears to be a race condition. If you display the page quickly everything works but if you do anything during the page creation the size is reported wrong in both the Xaml and Page size events report the size as the screen size as the complete display size and not the dialog. Sometimes this manifests as in incorrectly sized page render or mouse positioning misaligned.

The example works because it doesn't do much when displaying the page and creates in up front with             

`var FileOpenPickerPage = new SDKTemplate.FileOpenPickerPage();            FileOpenPickerPage.Activate(args);`

and then 
```
         public void Activate(FileOpenPickerActivatedEventArgs args)
        {
            // cache FileOpenPickerUI
            fileOpenPickerUI = args.FileOpenPickerUI;
            Window.Current.Content = this;
            this.OnNavigatedTo(null);
            Window.Current.Activate();
        }
```

The problem occurred for me when creating a frame and then `frame.Navigate(typeof(myPage));` with a setup for the page in the OnNavigatedTo. In my case I am calling a web API for some data. The slight increase in the time to display the pages causes the size to be reported incorrectly

I've been able to work around the issue by creating the page as per the example and then add altering the activation to 
```
        public void Activate(FileOpenPickerActivatedEventArgs args)
        {
            _fileOpenPickerActivatedEventArgs = args;
            Window.Current.Content = this;
            Window.Current.Activate();
            OnNavigatedTo(null);
            DeferedInit();
        }
```
and for the extra DeferedInit();

```
        public async void DeferedInit()
        {
                // DO NOT REMOVE. REQUIRED TO MAKE DEFER FIX WORK.
                await Task.Delay(100);
               DO SOME LONG RUNNING TASK LIKE CALL WEB API
        }
```

Apart from the dirty Task.Delay there's also a disadvantage of the the OnNavigatedTo and OnNavigatedFrom events not firing when initializing the page in this manner which makes cleaning up events registered to be problematic.

**Comment by oldnewthing** [comment]
I filed a samples issue on the feature team. Note that if you believe that this is a platform issue, then you should use the developer support channel rather than the samples channel.

**Comment by oldnewthing** [comment]
The feature team responded that they are not addressing this issue at this time. "We'll reconsider if it gets identified as an adoption blocker for a key customer scenario."

**Comment by Lazzarus** [comment]
@oldnewthing have you got a link for the features team where you've filed the issue?

**Comment by oldnewthing** [comment]
It's an internal database not accessible to the public, sorry.
