### ISSUE TITLE
"BasicSuspension" sample navigation parameter Object pass serialization error

### ISSUE THREAD

**Issue by shakir820** [Microsoft/Windows-universal-samples#847]
I cannot pass any object except string in the Navigation method as parameter. Whenever I try to pass any object I get error in the OnSuspending Method

at this line:  await SuspensionManager.SaveAsync();

![capture](https://user-images.githubusercontent.com/20181621/36250462-140e241e-1268-11e8-80c0-455ddaa50a55.PNG)

I want to pass any object  whatever I like without any error. Please fix it.

**Comment by JohnnyWestlake** [comment]
This is working as intended - see the notes here for the "parameter" arguement: https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.frame#Windows_UI_Xaml_Controls_Frame_Navigate_Windows_UI_Xaml_Interop_TypeName_System_Object_Windows_UI_Xaml_Media_Animation_NavigationTransitionInfo_

If wish to pass other types between pages, either serialise them to a string first, or pass them some other way. But the sample itself is working as intended.

**Comment by shakir820** [comment]
Ok. I'll pass any kind of object without any error. I'll take it as challenge
