### ISSUE TITLE
C++/WinRT variant of each sample app to show C# to C++/CX to C++/WinRT cycles of learning

### ISSUE THREAD

**Issue by optikos** [Microsoft/Windows-universal-samples#851]
For each of the C++/CX cpp versions of these sample apps, please •add• a [C++/WinRT](https://moderncpp.com/2017/11/15/cppwinrt-exe-in-the-windows-sdk/) version too.  Please don't •replace• the C++/CX version in the cpp subdirectories with C++/WinRT as time marches onward.  In addition to the existing cpp subdirectories, please add a cppwinrt subdirectory, so that developers can see a before & after version in C++/CX versus C++/WinRT (as well as compare to C# so that developers can see the incremental/smaller mental leaps from C# to C++/CX to C++/WinRT).  The C# and C++/CX variants of each app will resemble each other more than the C++/CX and C++/WinRT variants will resemble each other.  Comparing the C# and C++/WinRT without preserving the C++/CX incremental step would excessively complicate cycles of learning; people learn better deeper faster when traversing multiple smaller incremental cycles of learning than one big larger one-big-gulp cycle of learning.

As much as one would like conversion to C++/WinRT to be only minor mechanical edits, the fact that C++/WinRT represents what would otherwise seem (historically) like strongly-typed types (in the C++ sense of types) to instead be object instances with value semantics that encapsulate operations that represent an ATL/COM type in a WinRT component (.DLL & .winMD file-pair).  Because of this splitting of true C++ types versus COM-typish objects in C++/WinRT, sometimes the transformation from C++/CX to C++/WinRT is substantially different, as C++/CX ^ actual-type operations/casting/polymorphism/template-parameters get reworked in C++/WinRT to be value-semantics operations on object instances that merely conceptually represent types.  Sometimes when converting from C++/CX to C++/WinRT, it is merely the matter of a quick-&-dirty little editing trick of putting () here or replacing -> with . there.  But other times what was a terse [type-cast from one ^ type to another ^ type in C++/CX](https://github.com/Microsoft/cppwinrt/issues/314) gets transformed into at least a [.as or .try_as](https://github.com/Microsoft/cppwinrt/issues/253), and perhaps greater multi-line overhaul than that.  Analyzing the various categories of greater overhaul that is occasionally necessary is the true substantial learning opportunity in comparing the C++/CX cpp variant with a C++/WinRT variant.

Btw, this applies to the XAML samples only as C++/WinRT's support for code-behind the XAML compiler emerges.

**Comment by oldnewthing** [comment]
Yes, we already have work items tracking the addition of C++/WinRT samples.

**Comment by oldnewthing** [comment]
The conversion to C++/WinRT has begun - if there are specific samples you would like to prioritize over others let me know.
