### ISSUE TITLE
Link in README.md on line 63 does not work

### ISSUE THREAD

**Issue by mbalous** [Microsoft/Windows-universal-samples#852]
When trying to access `https://docs.microsoft.com/windows/uwp/devices-sensors/barcode-scanner#compatible-hardware` server returns 404.

**Comment by oldnewthing** [comment]
Thanks. Looks like the new link is https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/pos-device-support. Will update the README.

**Comment by oldnewthing** [comment]
The link earlier in the README (line 50) is correct.
