### ISSUE TITLE
ZipFile.ExtractToDirectory broken in recent UniversalWindowsPlatform releases.

### ISSUE THREAD

**Issue by Noemata** [Microsoft/Windows-universal-samples#853]
When using version 6.0.7 of the Microsoft.NETCore.UniversalWindowsPlatform the following code no longer works when a file folder is referenced from a FutureAccessList.

                        await Task.Run(() => ZipFile.ExtractToDirectory(ZipFileFolder.Path, ZipFileExtractPath));

A System.UnauthorizedAccessException: 'Access to the path 'C:\xxx' is denied.' error is mistakenly reported.  ZipFileExtractPath above refers to a folder that has been added to the FutureAccessList.

Other IO against the FutureAccessList folder works as expected.

ExtractToDirectory also works as expected with version 5.4.2 of Microsoft.NETCore.UniversalWindowsPlatform or below.

How was this missed during regression testing?

**Comment by Noemata** [comment]
After doing further testing, it turns out that it's the setting of TargetPlatformMinVersion that reveals the above bug, not the Microsoft.NETCore.UniversalWindowsPlatform.  16299 and above appear to have the bug.

**Comment by oldnewthing** [comment]
This does not appear to be a question about a sample in this repo. You can open a support case with our Developer Support team for platform support:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
