### ISSUE TITLE
XamlListView app misspells ShowSliptView

### ISSUE THREAD

**Issue by optikos** [Microsoft/Windows-universal-samples#854]
In the Microsoft/Windows-universal-samples repository, the XamlListView app consistently mispells ShowSliptView.  Perhaps a global search-&-replace in all source-code files in XamlListView should transform the misspelled ShowSliptView to the intended ShowSplitView.

**Comment by oldnewthing** [comment]
Thanks. Will appear in the next refresh (the one after today's).
