### ISSUE TITLE
360 Video still play sound after shutting down Mixed Reality Portal

### ISSUE THREAD

**Issue by quynhnguyen68** [Microsoft/Windows-universal-samples#855]
I use 360 video play back samples. When I turn off the Mixed Reality Portal to turn off 360 video, the music off the video still play. I have debugged and figured out that when I shut down Mixed Reality Portal, it seems close window event doesn't work
 
        private void AppView_Consolidated(ApplicationView sender, ApplicationViewConsolidatedEventArgs args)
        {
            appViewConsolidated = true;
            windowClosed = true;
            TryCloseWindow();
            Dispose();
        }

        private void TryCloseWindow()
        {
            CoreWindow window = CoreWindow.GetForCurrentThread();
            window?.Close();
        }`

**Comment by quynhnguyen68** [comment]
I solved this problem, I deactivated CoreApplication.Suspending += this.OnSuspending; in AppView.cs. It worked well but not stable

**Comment by derzorngottes** [comment]
I found a more stable work-around for this bug:

If you keep a reference to the view when it is opened, by replacing this line:<br>
`var appView = CoreApplication.CreateNewView(appViewSource);` <br>
with something like this:
<br><br>
```
// in the VideoGallery definition under mainviewId declaration
```
<br>
```
public CoreApplicationView mixedAppView
```
<br><br>
```
// in the GalleryGridView_ItemClick 
```
<br>
```
mixedAppView = CoreApplication.CreateNewView(appViewSource);
```
<br><br>
then you can manage closing the mixed reality portal manually from the main app window like so, whenever you get an event notification that the user has tried to close the window:
<br>
`await mixedAppView.Dispatcher.RunAsync(CoreDispatcherPriority.High, () =>`<br>
                `{`<br>
                    `CoreWindow.GetForCurrentThread().Close();`<br>
                `});`

**Comment by oldnewthing** [comment]
The feature team reports that the problem has been fixed in the Mixed Reality Portal. They didn't give me a build number, though, but it's presumably on its way to an Insider build.
