### ISSUE TITLE
How to replicate Windows/Phone splash screen

### ISSUE THREAD

**Issue by matelich** [Microsoft/Windows-universal-samples#856]
I've tried renaming my splash to include -Windows and -Phone in the filename, but I can't get it to work. What's the key to gettinig separate splash screens looked up?

**Comment by oldnewthing** [comment]
This doesn't appear to be a question about a sample in this repo. You can open a support case with our Developer Support team for general platform support questions:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.

**Comment by matelich** [comment]
I am referring to https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/SplashScreen/

In https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/SplashScreen/cs/Assets, we see splash-*-sdk.png

In https://github.com/Microsoft/Windows-universal-samples/blob/master/Samples/SplashScreen/cs/Package.appxmanifest#L19, only splash-sdk.png is referred to. I'm curious how that was triggered. I can't find any documentation of it.

**Comment by oldnewthing** [comment]
It may just be junk left over from test versions of the sample.

**Comment by matelich** [comment]
It works on desktop, at least. The filenames don't seem to be getting transformed during the build process (I see the two variants in the Appx directory). I'm hoping to use this to get a portrait splash screen on IoT Core.

**Comment by oldnewthing** [comment]
From what I can tell, it's just a leftover from the Windows 8 samples. The desktop version of the sample says in its Package.appxmanifest 

    <m2:SplashScreen Image="Assets\splash-Windows-sdk.png" ...

and the Phone version says

    <m3:SplashScreen Image="Assets\splash-Phone-sdk.png"

so it's a compile-time thing not a runtime thing.

**Comment by matelich** [comment]
Weird. I can't find any of that. Do you mind telling me where to find it?

I packaged up the sample and then dove into the appx files, and I see
   <uap:SplashScreen Image="Assets\Splash-sdk.png" BackgroundColor="#00B2F0"/>
inside AppxManifest.xml for both x86 and arm.

Thanks!

**Comment by oldnewthing** [comment]
I'm referring to [the old Windows 8 sample](https://code.msdn.microsoft.com/windowsapps/Splash-screen-sample-89c1dc78), which the Windows 10 sample was copied from.

**Comment by matelich** [comment]
Ok, I've now deployed to IoT Core, and verified the Windows splash is used, not the Phone splash, so this is not the secret tool I was hoping for. Thanks for the help.
