### ISSUE TITLE
Is there a nice sort/order by option for the XAML Treeview?

### ISSUE THREAD

**Issue by jphellemons** [Microsoft/Windows-universal-samples#858]
https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/XamlTreeView
Would be nice if you could just use the x:Name="treeview" and then in the code behind: treeview.Sort<sourceObjectType>("propname")
Something like this.

**Comment by oldnewthing** [comment]
This isn't a question about the sample. It's a feature request. You can use the Feedback Hub to submit suggestions.

**Comment by jphellemons** [comment]
Would be nice if it is a pre-build native control though. It's a common thing to have treeview navigation.

**Comment by oldnewthing** [comment]
If you want to make suggestions for the product team, you can use the Feedback Hub app.
