### ISSUE TITLE
Accessibility-related Sample

### ISSUE THREAD

**Issue by Menelion** [Microsoft/Windows-universal-samples#859]
This is somewhat related to #317.

Most developers do not implement accessibility for screen readers in their UWP apps or do it poorly. As Microsoft claims to be accessibility-driven those days, it would be extremely useful to have a sample app that be completely accessible from a screen-reader perspective, i.e., not only keyboard-navigable, but completely operational without a mouse.

**Comment by oldnewthing** [comment]
I'm not sure a "Best practices for accessibility" sample falls under the remit of this repo, which is primarily for demonstrating platform features, not providing guidance. There are talks on Channel9 that cover the topic, such as [this one from Mariah Dunn](https://channel9.msdn.com/Events/Build/2016/P541). I thought one of the talks even included a link to a sample app, but I can't find it right now.

**Comment by oldnewthing** [comment]
I found it: [Introduction to Building Accessible UWP Apps](https://channel9.msdn.com/Events/Build/2016/P497). Under the video, click "Source Code" to download the app.
