### ISSUE TITLE
Css prefix for other browsers and support of preprocessors

### ISSUE THREAD

**Issue by ulaharbmg** [Microsoft/Windows-universal-samples#86]
Hi team,

1. After review notice that code contain -webkit -moz prefixes. I don't understand why it needed for win applications.

2. If it for reuse same code for web may be will be useful to do tool for build app oriented for web and app oriented for win app. It can be i don't know similar to postcss with extensions or plugins for it.

PS: if it possible can show where i can ask question like "How it can be ... la la la ?". Because after some hours i didn't understand where place where can i ask it.

Sorry for strange question but it really not useful.

Thank you.

**Comment by oldnewthing** [comment]
As far as I can tell, the -moz and -webkit prefixes are confined to WinJS. WinJS is a cross-platform library, not just for Windows apps.

**Comment by ulaharbmg** [comment]
yep, thank you. Now i understand that can work with react and angular. Awesome. I found some about it.

Q in PS really actual. Need forum for those questions, but i can't found it. Next issue is also question.
Link must be in head of readme.md in my opinion.

Thank you.

**Comment by AdamBraden** [comment]
General Q&A should go to the Windows apps forums - 

https://social.msdn.microsoft.com/Forums/windowsapps/en-US/home?forum=wpdevelop
