### ISSUE TITLE
Don't these positions need to be translated to a right-handed coordinate system?

### ISSUE THREAD

**Issue by scott-plutovr** [Microsoft/Windows-universal-samples#862]
https://github.com/Microsoft/Windows-universal-samples/blob/f6ad9bc1b5d85660b4544adebbc9a6d9db9a2246/Samples/SpatialSound/cpp/CardioidSound.cpp#L130

**Comment by scott-plutovr** [comment]
According to [1], "Represents a position in 3D space, using a right-handed coordinate system."


[1] https://msdn.microsoft.com/en-us/library/windows/desktop/mt186606(v=vs.85).aspx

**Comment by oldnewthing** [comment]
I've asked the feature team to investigate.

**Comment by oldnewthing** [comment]
Actually, the sample says right above the lines you quoted that the coordinates are already right-handed.

https://github.com/Microsoft/Windows-universal-samples/blob/f6ad9bc1b5d85660b4544adebbc9a6d9db9a2246/Samples/SpatialSound/cpp/CardioidSound.cpp#L118-L123
