### ISSUE TITLE
ShareTarget sample: OnNavigatedTo handler is unclear and potentially dangerous

### ISSUE THREAD

**Issue by rigdern** [microsoft/Windows-universal-samples#865]
The ShareTarget sample's `OnNavigatedTo` handler dispatches its work using `Task.Factory.StartNew` as can be seen [here](https://github.com/Microsoft/Windows-universal-samples/blob/f6ad9bc1b5d85660b4544adebbc9a6d9db9a2246/Samples/ShareTarget/cs/ShareTarget.xaml.cs#L68).

I have two pieces of feedback about this:
  1. Why does this work need to be dispatched? It's not clear to me. If this really needs to happen, there should be a comment describing why.
  2. If we really need to dispatch the work, is there a good reason for using `Task.Factory.StartNew` instead of an alternative like `Task.Run`? If not, the sample should move away from `Task.Factory.StartNew` due to its gotchas: https://blog.stephencleary.com/2013/08/startnew-is-dangerous.html. Even if it works okay in this case, we probably don't want to encourage developers to use `Task.Factory.StartNew` more generally.

Random note. Look how confused this engineer is about how to properly use the sharing API: https://mtaulty.com/2015/08/13/m_15905/. He was getting exceptions using the sharing API so he tried things like spawning tasks, adding timeouts, and waiting for the window to be visible. Eventually, he found something that worked but doesn't understand why it worked. We should make it clearer when and how these APIs expect to be called and why. 

Adam Comella
Microsoft Corp.

**Comment by oldnewthing** [comment]
There is a comment that explains why:

    // It is recommended to only retrieve the ShareOperation object in the activation handler,
    // return as quickly as possible, and retrieve all data from the share target asynchronously

The code implements the recommendation. It kicks work to a background thread to extract information from the ShareOperation, allowing the main thread to return as quickly as possible.
