### ISSUE TITLE
How to make the "App.xaml" file in a shared content folder?

### ISSUE THREAD

**Issue by xiedongweo** [Microsoft/Windows-universal-samples#866]
I want to know how to put the "App.xaml" file in a shared folder like the UWP [samples](https://github.com/Microsoft/Windows-universal-samples/tree/master/SharedContent/cpp). 

I tried to move my "App.xaml" file into my sub folder in my UWP project, but after that, I cannot compile my project.

Do anyone know how to get it work?

**Comment by oldnewthing** [comment]
This is not a question about a sample in this repo. You can open a support case with our Developer Support team:

1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.

**Comment by avakhrushev** [comment]
Doesn't appear so. Some projects do reference App.xaml in external directories, like https://github.com/microsoft/Windows-universal-samples/blob/master/Samples/360VideoPlayback/cpp/360VideoPlayback.vcxproj
and there are no relevant Links that I can see.

This has been asked on support forum, but no one has come up with an answer. @oldnewthing join in and help us out https://social.msdn.microsoft.com/Forums/Windowsapps/en-US/a68e70ee-0ccf-4669-85fe-4fc7cb216b7e/uwp-how-to-change-location-of-appxaml

**Comment by oldnewthing** [comment]
@avakhrushev The C# projects use `<Link>`. The C++ projects just reach for the files directly. The only trick is that I don't think there's a way to create these reach-outs directly in the VS UI. I edited the proj files directly.

**Comment by avakhrushev** [comment]
Yes, so I did.
It just doesn't seem to be working for paths in a project subfolder, I get _XamlCompiler error WMC1008: Application main file must be named App.xaml_ if I try.

**Comment by oldnewthing** [comment]
I've never used it for a path in a project subfolder, only for a project ancestor.
