### ISSUE TITLE
What is the Hash Function Used to Generate the Id from the String?

### ISSUE THREAD

**Issue by scout208** [Microsoft/Windows-universal-samples#867]
I know if you use a 2-parameter constructor the Id is generated by hashing the string name provided, however I can't find how to know what the id generated is because I don't know what function to use to hash the string.

**Comment by oldnewthing** [comment]
Which sample are you referring to?

**Comment by scout208** [comment]
I'm sorry I'm referring to the cs Logging sample. Basically this section of code here:

````
// The 2-parameter constructor creates a channel with Windows 10 semantics.
using (var channel = new LoggingChannel(
    "SampleProvider",
    null)) // null means use default options.
{
    // The Id is generated by hashing the string "SampleProvider".
    // channel.Id == eff1e128-4903-5093-096a-bdc29b38456f

    this.DemonstrateLogging(channel);
}
````

It tells me what the id would be, but I'm wondering how that id is actually generated. I can't find any specific on it.

**Comment by oldnewthing** [comment]
It's explained in the README:

> * The channel's ETW Id is specified by the third constructor parameter, if present; otherwise it is generated from the Channel Name **by the same hashing algorithm as the .NET EventSource class**.
