### ISSUE TITLE
ScannerExample_UWP Exception on SetActiveSymbologiesAsync

### ISSUE THREAD

**Issue by BogiG** [Microsoft/Windows-universal-samples#868]
in the uwp sample the ClaimedScanner.SetActiveSymbologiesAsync throws exception....
{System.ArgumentException: Value does not fall within the expected range.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at SDKTemplate.Scenario3_ActiveSymbologies.<SetActiveSymbologies_Click>d__12.MoveNext()}

scanner is honeywell 1900ghd-2

anyone in the same situation?

**Comment by TerryWarwick** [comment]
@BogiG,

What version of Windows 10 are you using?  The inbox driver for HID POS Scanner was updated in build 15063 released in spring of 2017 to support SetActiveSymbologiesAsync.  Please provide the actual code where you are calling SetActiveSymbologiesAsync, including the symbologies that you are setting active.  Have you called GetSupportedSymbologies to confirm that the scanner supports the symbologies that you are attempting to set?  Please know that the HID POS Scanner protocol may not support all of the symbologies that the scanner manual claims that the scanner supports.  This means that you can only set active those that HID POS Scanner protocol supports, yet the scanner will still recognize the additional symbologies.

Terry Warwick
Microsoft
