### ISSUE TITLE
Javascript sample for Win 10 map control

### ISSUE THREAD

**Issue by joshberry** [Microsoft/Windows-universal-samples#87]
Will there be javascript samples for the new Win 10 map control? Everything I've seen in the samples and elsewhere is specific to C#/XAML. Will the updated map control be supported in javascript apps?

**Comment by thakkar** [comment]
Hey Josh - 

There is no Javascript MapControl yet. This document outlines all the MapControl options that Microsoft Bing Maps has to offer https://www.microsoft.com/maps/choose-your-bing-maps-API.aspx.
There is a Bing Maps AJAX control for Web - https://msdn.microsoft.com/en-us/library/gg427610.aspx

Hope that helps.

Thanks
Rohan
