### ISSUE TITLE
Simple Communication Sample

### ISSUE THREAD

**Issue by koze85** [Microsoft/Windows-universal-samples#870]
Hi I am trying to reproduce your sample but I ve stuck...
Things I did 
Create new C project
Add existing project Microsoft.Samples.SimpleCommunication
Reference Microsoft.Samples.SimpleCommunication
Write c code
My project can now stream audio data in the stps format but the media element cannot play the format in my sample i can hear it from yours
specifically I cant get this line to work  mediaExtensionMgr.RegisterSchemeHandler("Microsoft.Samples.SimpleCommunication.StspSchemeHandler", "stsp:"); in my project where apparently in yours it works
any help will be appreciated thanks very much

**Comment by oldnewthing** [comment]
This doesn't appear to be an issue with the sample itself. As you noted, the sample in this repo does work. This is an issue with adapting the sample to be used in your program. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:

1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
