### ISSUE TITLE
SpatialInteractionSource sample crash

### ISSUE THREAD

**Issue by Kranck** [Microsoft/Windows-universal-samples#871]
Hey,

I'm actually trying to understand gestures with the Hololens thanks to the SpatialInteractionSource sample,
sadly, when I try to make a gesture (just a tap or trying to hold and moving) in the application, this one crash with a "Platform::InvalidCastException".
This occurs in the "OnInteractionDetected" in the HolographicPaintMain source.

I'm using Visual Studio Community 2017 on Windows 10 and I'm debugging on a Hololens (OS Build : 10.0.14393.2189).

I don't know if i missed something obvious, if it's the case i'm really sorry.

Thansk by advance for your help.

PS : Here is the full output when the crash occurs : 
```
Exception thrown at 0x77252552 (KernelBase.dll) in HolographicPaint.exe: 0x40080201: WinRT originate error (parameters: 0x80004002, 0x0000001D, 0x0230D96C).
Exception thrown at 0x77252552 in HolographicPaint.exe: Microsoft C++ exception: Platform::InvalidCastException ^ at memory location 0x0230DE0C. HRESULT:0x80004002 No such interface supported
WinRT information: No such interface supported
```

Kranck.

**Comment by alainza** [comment]
Hi,

the [.vcxproj](https://github.com/Microsoft/Windows-universal-samples/blob/master/Samples/SpatialInteractionSource/cpp/SpatialInteractionSource.vcxproj) requires 10.0.16299 as the minimum version to run this sample. I am even surprised that VS deployed this project on a 14393 HoloLens: this project uses updated API which were not available on this version of HoloLens.

Note that a previous of HoloLens is now available (see https://docs.microsoft.com/en-us/windows/mixed-reality/hololens-rs4-preview) on which this sample should run correctly.

-Alain

**Comment by Kranck** [comment]
Hi,

Thanks a lot Alin for your answer, I installed the preview this morning and the sample work just perfect. Thank you for your quick hepl, and sorry for the obvious thing I missed.

Have a great day,

Kranck.
