### ISSUE TITLE
"unable to attach to coreclr" when the min version is set to 16299

### ISSUE THREAD

**Issue by kevin-jing** [Microsoft/Windows-universal-samples#872]
Repo:
-- New project, Windows Universal \ Blank App
-- Set Minimum version from 10586 to 16299
-- After the project is created, press F5, then the error occurs, "unable to attach to coreclr"
![image](https://user-images.githubusercontent.com/29517189/39025204-3a7239fa-4478-11e8-8ed3-159c6b45a8d5.png)

If the Minimum version is set to a lower one, such as 15063, the error doesn't occur.

I'm using the latest VS2017:
![image](https://user-images.githubusercontent.com/29517189/39025266-984ffab2-4478-11e8-854a-5d4d0645af0b.png)

**Comment by oldnewthing** [comment]
This doesn't appear to be a question about a sample in this repo. It looks like a question about Visual Studio. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:

1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.

**Comment by kevin-jing** [comment]
@Buzzker Thank you! It fixed my issue.
