### ISSUE TITLE
Moving Items in ListView results in complete List Refresh

### ISSUE THREAD

**Issue by jasonwurzel** [Microsoft/Windows-universal-samples#876]
please see also [this stackoverflow question](https://stackoverflow.com/questions/50132820/programmatically-move-items-in-uwp-listview-without-refresh)

I'm having a problem getting this simple task to work: 
- ListView bound to some suitable List in the backend (ObservableCollection, ReactiveList, etc.)
- Items get moved around in the bound list (by obsCollection.Move or by sorting)
- Every time one Item gets moved the whole list is refreshed, i.e. all items disappear and appear again in the correct order.

This is something that looks like it should work out of the box, the ListView should just handle updates/moves/refreshes correctly, but I'm having no luck getting it to work.

**Comment by oldnewthing** [comment]
This is not a question about the samples in this repo. You can open a support case with our Developer Support team who can help with your problem. Please use these steps below for further help:

1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account.

2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
