### ISSUE TITLE
AnimationBehavior.SetSourceUri does not work with relative path

### ISSUE THREAD

**Issue by fpskcd** [Microsoft/Windows-universal-samples#877]
When you call AnimationBehavior.SetSourceUri with a relative GIF file URI (i.e. file name only), the image appears blank, even if UriKind.Relative or UriKind.RelativeOrAbsolute is specified in the Uri instance.

**Comment by oldnewthing** [comment]
This is not a question about the samples in this repo. You can open a support case with our Developer Support team who can help with the problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
