### ISSUE TITLE
Grafik Bug in NavigationMenuSample on Mobile-Device

### ISSUE THREAD

**Issue by MysticEmpires** [Microsoft/Windows-universal-samples#88]
The Hamburger-Button overlay the title. After a toggle of the button the bug is gone.

![navigationmenusample](https://cloud.githubusercontent.com/assets/5948144/8711002/4e589770-2b4e-11e5-9742-624f811eb9a2.png)

**Comment by MysticEmpires** [comment]
Found the Bug by my self. Put "CheckTogglePaneButtonSizeChanged();" in the Loaded Event of the AppShell to Initialize the Values and all is fine.

**Comment by mikehenderlight** [comment]
Yep, that is the fix.  Sample has been updated

**Comment by oldnewthing** [comment]
(You'll see the fix in the next samples refresh.)

**Comment by nasa1992** [comment]
@oldnewthing I can't run ResizeAppView project, some XAML file deleted. Can you check and fix it?!! Thank!!

**Comment by oldnewthing** [comment]
Please open a separate issue for each problem. Note that the ResizeAppView problem is already being tracked as issue #115. That issue also includes a workaround that should tide you over until the next refresh later this week.
