### ISSUE TITLE
plans for PWA examples on Universal Windows Platform?

### ISSUE THREAD

**Issue by sam9116** [Microsoft/Windows-universal-samples#880]
Are there any plans for PWA examples on here? or is it out of scope for your team? If it is out of scope, which team do you suggest I ask?

**Comment by hiepxanh** [comment]
same question

**Comment by oldnewthing** [comment]
You can refer to the JS samples to see how to use the features from a PWA. If there is a specific feature you need, and it lacks a JS samples, let me know so I can prioritize.
