### ISSUE TITLE
DeviceEnumerationAndPairing does not treat DevicePairingKinds as flags

### ISSUE THREAD

**Issue by xmedeko** [Microsoft/Windows-universal-samples#881]
The [DevicePairingKinds enum has flags](https://docs.microsoft.com/en-us/uwp/api/windows.devices.enumeration.devicepairingkinds) so "It is possible to have multiple values set for a single pairing action." (doc citation).

But the DeviceEnumerationAndPairing , Scenario 9 treat is as non-flags enum, e.g. see the code [Scenario9_CustomPairDevice.xaml.cs](https://github.com/Microsoft/Windows-universal-samples/blob/master/Samples/DeviceEnumerationAndPairing/cs/Scenario9_CustomPairDevice.xaml.cs.) Either fix the code. Or, if the code is good, provide documentation, why the `DevicePairingKinds` may be treated as non-flags.

**Comment by oldnewthing** [comment]
It is flags when asking for supported ceremonies, but when a ceremony is under way, then there is only one ceremony. This is noted [in the documentation for DevicePairingRequestedEventArgs.PairingKind](https://docs.microsoft.com/en-us/uwp/api/windows.devices.enumeration.devicepairingrequestedeventargs.pairingkind):

> The kind of pairing used for this pairing request.

Note that documentation uses the singular "kind".

This is reinforced by the fact that the property name is singular (PairingKind, not PairingKinds).
