### ISSUE TITLE
backbutton is under the titlebar

### ISSUE THREAD

**Issue by touseefbsb** [Microsoft/Windows-universal-samples#882]
it is actually a very obvious bug, the title bar doesnt allow any interaction apart from draging the app around, so the new back button in the navigationview with this update causes this problem as you can see in this sample app as well that the top 70 percent of the backbutton of navigationview cannot be clicked or interacted with as it is under the titlebar.

**Comment by touseefbsb** [comment]
or also we can add padding to top of navigationview.

**Comment by oldnewthing** [comment]
This is a platform issue, not a sample issue.

**Comment by oldnewthing** [comment]
The feature team tells me they are already aware of this issue.
