### ISSUE TITLE
basic face tracking: What is the principle of face detection?

### ISSUE THREAD

**Issue by TT7105** [Microsoft/Windows-universal-samples#883]
Who can tell me the principle?

**Comment by oldnewthing** [comment]
This appears to be a question about the feature itself, not about the sample in this repo. You can open a support case with our Developer Support team:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
