### ISSUE TITLE
[XAML UI Basics] Syntax Highlighting

### ISSUE THREAD

**Issue by WilliamABradley** [Microsoft/Windows-universal-samples#884]
Hi @oldnewthing,
I am the developer of [ColorCode-Universal](https://github.com/WilliamABradley/ColorCode-Universal), which is a port of an Old Microsoft Syntax Highlighter that would output HTML.

I modified it so that it could also produce other outputs, such as rendering to a RichTextBlock, so that no WebView is required.

I used this [(ColorCode.UWP)](https://www.nuget.org/packages/ColorCode.UWP) to add Syntax Highlighting to the Windows Community Toolkit Sample App, and the Code Blocks for the MarkdownTextBlock.

I think that this library would be great for highlighting the Sample Code in Samples, in the XAML Controls Gallery, although it would require some significant re-writes to the Sample Pages, single the Sample Code is directly in the XAML.

If you are willing to take a PR, I can integrate this.

**Comment by oldnewthing** [comment]
I forwarded your suggestion to the feature team.
