### ISSUE TITLE
App crashing on CalendarIdentifier changing

### ISSUE THREAD

**Issue by ilsergente1993** [Microsoft/Windows-universal-samples#885]
Hello. I was trying the app and suddenly it crashed. 
It happened because I set a different calendar in _Data Input -> CalendarView -> CalendarIdentifier_ on the right box where you can change calendar settings.
The crash happens only with the **VietnameseLunar** and **TaiwanLunar** calendars.
I tried several times like first thing after the opening of the app.

Ciao

**Comment by oldnewthing** [comment]
I thought we already had an issue tracking this, but I guess not. Will inform the feature team.

**Comment by oldnewthing** [comment]
Aha, there it is. Issue #659.

**Comment by ilsergente1993** [comment]
Alright. In my first search I didn't find it. My apologies.
BTW I got the crash only with VietnameseLunar and TaiwanLunar calendars.
Cheers
