### ISSUE TITLE
Slip printing using OPOS

### ISSUE THREAD

**Issue by nsandeep87** [Microsoft/Windows-universal-samples#886]
Hi,

Is there any sample app for  Slip printing. I did not find here. However I am trying o perform the below operations:
1. Find and claim POSPrinter
2. From the claimed printer, retrieve Slip printer ( claimedPrinter.Slip)
3. Create SlipPrintJob, i.e.  SlipPrintJob = claimedPrinter.Slip.CreateJob()
4. Add printLine using SlipPrintJob.PrintLine()
5. Execute the job using  SlipPrintJob.executeAsync()

Please let me know if this fine. Share the sample code if there is any.

**Comment by TerryWarwick** [comment]
@nsandeep87, 

We do not have a sample for slip printer.  It should behave very similar to receipt printer with the primary difference being the use of ClaimedSlipPrinter vs ClaimedReceiptPrinter.

Terry Warwick
Microsoft

**Comment by TerryWarwick** [comment]
@nsandeep87,

I am happy to hear that you got it working.  May I ask which slip printer you are using?

Terry Warwick
Microsoft
