### ISSUE TITLE
I pasted the xaml and xaml.cs in visual studio 2017 but there appears to be errors before building the code?

### ISSUE THREAD

**Issue by shikhartandon1993** [Microsoft/Windows-universal-samples#887]
Hi

I pasted the xaml and xaml.cs files of BluetoothLE sample Scenario1_Discovery in visual studio 2017 but there appears to be errors before building the code?
Do i  need to add something else or change something.
Please help
Thanks
Shikhar

**Comment by oldnewthing** [comment]
Don't paste it into Visual Studio. Just open the solution and build it.
