### ISSUE TITLE
.xaml file in BluetoothLE project Scenario1_discovery does not identify page,height,width,grid etc.

### ISSUE THREAD

**Issue by shikhartandon1993** [Microsoft/Windows-universal-samples#888]
Hi

.xaml file in BluetoothLE project Scenario1_discovery does not identify page,height,width,grid etc.

**Comment by oldnewthing** [comment]
Not sure what you're getting at. It doesn't need to define a height or width because its height and width are obtained from the containing frame. There is a grid element on the page. The sample seems to run fine. Can you be more specific what the problem is and how it impairs the sample?
