### ISSUE TITLE
File Picker Contracts With Cached File Update broken in 1803 update

### ISSUE THREAD

**Issue by Lazzarus** [Microsoft/Windows-universal-samples#889]
The cached file functions in FilePickerContracts seem to have completely broken under 1803.
The CachedFileUpdaterUI_FileUpdateRequested event never fires. I believe it's related to the the Window.Current.Activate();  workaround

I think this is most likely a frame work issue as a number of apps in the store as well as our own have stopped work. 

I've post the issue on the forum [here](https://social.msdn.microsoft.com/Forums/en-US/1fe4ef53-6a6a-432d-a586-5ef11fb4cc69/file-picker-contracts-with-cached-file-update-broken-in-1803-update?forum=wpdevelop)

**Comment by oldnewthing** [comment]
Sample updated to clarify when activation occurs. Release [v7.0.2](https://github.com/Microsoft/Windows-universal-samples/releases/tag/v7.0.2). If this doesn't address the problem, let me know.

**Comment by Lazzarus** [comment]
Hi Raymond,

Just tried the updated samples but am still seeing the original behaviour. I.e the cached file update events not firing. (Both Open and Save)

In the FilePickerContractsTask the first thing it does is show a toast. The toast never shows and sticking a breakpoint confirms it never runs.

Also in CachedFileUpdaterPage.xaml line 74 a cachedFileUpdaterUI.FileUpdateRequested event is set up.
This event never fires for me. I’ve confirmed via breakpoint the event is setup (i.e isForegroundActivated == false)

Are you may be running a future version of Windows?

Also can I make a suggest? On the cached file open add the following in the before access handling as the sample doesn’t seem to do anything to the sample file before access so if it doesn’t work you can’t tell.
await Windows.Storage.FileIO.WriteTextAsync(file, @"Cached file updated before access");

Thanks

Gary

**Comment by oldnewthing** [comment]
This was the update I got from the feature team. I'll forward your feedback to them.
