### ISSUE TITLE
WebView sample missing winrtsharedobject.cpp, etc files

### ISSUE THREAD

**Issue by spagad** [Microsoft/Windows-universal-samples#89]
The following files are missing in the WebView sample (though they show up on the project)
winrttoastnotificationwrapper.cpp
winrttoastnotificationwrapper.h
winrtsharedobject.h
winrtsharedobject.cpp

**Comment by AdamBraden** [comment]
This will be fixed in our refresh on 7/29 when we update all samples for Windows 10 RTM.
