### ISSUE TITLE
Windows.Media.Devices.VideoDeviceController-compatible devices

### ISSUE THREAD

**Issue by NickDarvey** [Microsoft/Windows-universal-samples#890]
Is there a list of devices that are compatible with the `Windows.Media.Devices.VideoDeviceController` manual control APIs?

My Surface Book 2's camera is compatible with focus, zoom, and EV, but I can't find any other webcam that has those capabilities. e.g. Microsoft LifeCam Studio is not, Logitech V-U0027 is not.

I am guessing this is for the same reason as mentioned in #799.
>For USB based cameras, since there’s typically only one pin, profiles are not needed. And in the Fall Creators Update and earlier, profiles were not available for USB Video Class based cameras (no way for IHV/OEMs to publish profiles for UVC based cameras).

Is this still not possible in 1803? Are there any external webcams on the market that are compatible with this API?

## Sample
\Samples\CameraManualControls\cs\CameraManualControls

## System Info
OS: Windows 10 Pro 1803 17134.48
SDK: Windows 10 SDK 10.0.17134.0

**Comment by NickDarvey** [comment]
I notice that the Windows Camera app supports focus and EV control on all of the cameras I tried it with. What API is that app using?

**Comment by oldnewthing** [comment]
This is not an issue with the sample, but rather with the platform. You can open a support case with our Developer Support team:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
