### ISSUE TITLE
CameraOpenCV sample c++ version?

### ISSUE THREAD

**Issue by jialiuBellus3d** [Microsoft/Windows-universal-samples#891]
Is there an C++ version of CameraOpenCV sample?

**Comment by BenPYeh** [comment]
No, but the current sample shares much of the same code as the CameraFrames sample for grabbing frames. You might start with that sample, and add a reference to the OpenCVBridge project. Then declare and instantiate a OpenCVHelper object, and use it much in the same way as the C# code.

**Comment by jialiuBellus3d** [comment]
Thanks. Just to clarify, this sample is just using openCV to do post processing of the image frame, right? Not really using OpenCV video capture API to do the capture?

**Comment by BenPYeh** [comment]
Correct.

**Comment by jialiuBellus3d** [comment]
Also is there a reason why you are using Nuget to use the OpenCV package? Does this mean I can't use normal opencv .lib inside windows runtime component? I am trying to do so and it always crash on runtime.

**Comment by jialiuBellus3d** [comment]
Thanks. But still didn't get the answer to this question: is normal openCV .lib going to work in windows run time component? I tried, but every time I included the opencv .lib, it would cause the app to crash on run time. 

Here are all the tests I have run and the results to make sure that the issue is with OpenCV.

1. Create a windows run time component project with UWP app. Create simple Math calculation header file and cpp file inside the run time component project. Compile and runs perfectly.

2. Separate out the Math calculation header and cpp, compile them into static library, use it inside WRT component project with UWP app. Compiles and runs perfectly.

3. Include openCV library (just the opencvcore.lib). Not even creating a new Mat. App crashes with this error: unable to activate Windows Store app '1c51.....!App'. The activation request failed with error 'Operation not supported. Unknown error: 0x80040904' When I set a break point, the output shows .dll for runtime component loaded then unloaded. Module not found. Which I think is caused by dll unloaded

![unabletoactivewindowsstoreapp 1](https://user-images.githubusercontent.com/15353783/40934940-588e1a76-67eb-11e8-9c03-824a221b44c1.PNG)
![dllweirdunload](https://user-images.githubusercontent.com/15353783/40935032-ad4ced62-67eb-11e8-99b6-742e5939d3bc.PNG)

**Comment by oldnewthing** [comment]
I don't know whether the normal OpenCV.lib will work. The sample uses the NuGet package. If you're asking a question about something not in the sample, you can open a support case with our Developer Support team:

1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
