### ISSUE TITLE
Miracast - Desktop Casting

### ISSUE THREAD

**Issue by zakrzus** [Microsoft/Windows-universal-samples#892]
Hello, is there any way to set desktop as source to 
RequestStartCastingAsync(); 
In Miracast method ?

**Comment by oldnewthing** [comment]
This appears to be a question about the platform, not about the casting sample. You can open a support case with our Developer Support team:

1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
