### ISSUE TITLE
POS printer not discovered

### ISSUE THREAD

**Issue by rutvij43** [Microsoft/Windows-universal-samples#893]
Hi, I am trying to discover and connect TM-T88V Epson printer, but Printer is not discovered. I even tried filter with PosConnectionTypes.IP as my printer is connected in LAN but even that is not working.
I have printer IP and port setup. Is there is any way I could discover and connect using IP and port number?

Thanks,
RP

**Comment by TerryWarwick** [comment]
@rutvij43,
 
What version of Windows 10 are you using?

Please confirm that the TM-T88V and your computer are on the same subnet by confirming that the first 3 sets of numbers in their IPv4 address match and have a matching gateway address.   

Terry Warwick
Microsoft

**Comment by rutvij43** [comment]
Hi Terry, I am using Windows 10 Pro version 1803 (OS build 17134.1).
I checked the IPs and gateway, and found that my PC and Printer has same first 3 sets in IPv4 and gateway is same.

**Comment by TerryWarwick** [comment]
@rutvij43,

When you say that you can access using direct connect, are you connecting the printer directly to your PC's network jack as opposed to USB? 

If you are using an Epson tool to configure the printer, make sure that it is not in the way of accessing the printer through PointOfService.

Terry Warwick
Microsoft

**Comment by rutvij43** [comment]
Hi Terry,
I am currently using c# socket-program to connect receipt printer. But is not very convenient way to manage connection as I need to know IP and port for printer before this.
What I am trying to achieve is, I want to discover printer using my App and connect it. and then print receipt. In this way, I would have option to select Printer from available options, and also don't have to worry about what IP or Port they are using at a time.
Also, using PosPrinter gives more options available as compared to socket-connection.

Thanks,
Rutvij

**Comment by TerryWarwick** [comment]
@rutvij43,
Please connect the network cable from the Epson TM-T88V directly to the network port on the computer then try to discover the printer using the UWP application.  

If this is successful and discovery is still not successful when the printer is attached to the network there is likely a network issue causing the problem you are experiencing.  

Next step would be to plug both the computer and the printer into the same network hub.

Please let us know the status of both tests.

Terry Warwick
Microsoft

**Comment by TerryWarwick** [comment]
@rutvij43,

I have a couple questions to understnad more about your implementation and environment.

1. Are you using FindAllAsync or DeviceWatcher to enumerate your network POSPrinters?  I believe the search algorithm for FindAllAsync gives the printer 5 seconds to respond.  Device Watcher will continue to monitor for changes.  

2. Are you connecting the printer or PC to Wi-Fi?  Please let me know if the printer is connected to the wired ethernet or wireless and describe your local network topology so that we can attempt to reproduce the probem that you are encountering.

Terry Warwick
Microsoft

**Comment by rutvij43** [comment]
Hi, 
1.) I tried both DeviceWatcher, and FindAllAsync, but couldn't find my printer. In both cases, search is complete in just 2-3 seconds. In DeviceWatcher, it generates EnumerationCompleted in 2-3 seconds. This seems very less, as you say FindAllAsync takes 5 seconds and DeviceWatcher may take more time.
2.) I am connecting printer to router via Ethernet. and PC to Wi-Fi. Both routers connected to a server. Not sure about topology, as I don't know much about it. But both PC and Printer has first three parts of IPv4 address same. Thing is I can find via socket Printer by IP:Port as I already know it. I hope this gives some idea about how they are connected.
