### ISSUE TITLE
RadioManager: Cannot disable Bluetooth when running on Raspberry Pi

### ISSUE THREAD

**Issue by greyghostbrewery** [Microsoft/Windows-universal-samples#894]
When running the RadioManager project on a Raspberry Pi, the on-board Bluetooth device cannot be disabled.

After toggling the Bluetooth status, the radio UI control becomes disabled and does not return to an enabled state to "re-enable" the Bluetooth device.

Restarting the app then fails to enumerate any radios on the device. The call to "GetRadiosAsync" never returns.

RadioManagerSample.Scenario1.InitializeRadios() ->
var radios = await Radio.GetRadiosAsync();

The Raspberry Pi needs to be power cycled to re-enable the Bluetooth device / allow the app to successfully enumerate Radio devices using the "GetRadiosAsync" call.

**Comment by oldnewthing** [comment]
This sounds like a platform issue, not an issue with the sample. You can open a support case with our Developer Support team.
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
