### ISSUE TITLE
BluetoothLE app is working when I use BluetoothCacheMode.Cached

### ISSUE THREAD

**Issue by shikhartandon1993** [Microsoft/Windows-universal-samples#897]
Hi

BluetoothLE app is working when I use BluetoothCacheMode.Cached and it shows "Device unreachable" when I use  BluetoothCacheMode.Uncached.

Please Help
Thanks

**Comment by oldnewthing** [comment]
This doesn't sound like an issue with the BluetoothLE sample in this repo. You can open a support case with our Developer Support team.
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
