### ISSUE TITLE
VOIP application example is still missing after //Build 2015

### ISSUE THREAD

**Issue by mstyura** [Microsoft/Windows-universal-samples#9]
It would be nice to have an example of VOIP application for Windows Universal App Platform. I expect it has some differences from regular apps (like in WP8). So it would be nice to have a dedicated example of VOIP app.
UPD: **Is it even possible to create VOIP app using universal app platform which have comparable functionality to WP8 Silverlight?**

**Comment by sphenry** [comment]
Hi mstyura, the UWP VOIP APIs are not in the Windows 10 build yet, but they're coming soon. We'll have a example VOIP app shortly after.

**Comment by rmisiak** [comment]
do you have a timeline for this?

**Comment by dinofizz** [comment]
Looking forward to an update on VoIP applications in Windows 10.

**Comment by meisenring** [comment]
Looking forward to an update on VoIP applications in Windows 10.

**Comment by jarivas** [comment]
Waiting voip since windows 8.1 update

**Comment by oldnewthing** [comment]
See sphenry's reply earlier in the thread.

**Comment by suilevap** [comment]
@sphenry , @oldnewthing  Any estimation?

**Comment by sphenry** [comment]
The update from today, July 29, now has a VOIP sample:
https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/VoIP

**Comment by jarivas** [comment]
I could make voip in unversal, but not with video, not even video at the same time
