### ISSUE TITLE
Windows namespace not recognised anymore

### ISSUE THREAD

**Issue by JBX028** [Microsoft/Windows-universal-samples#90]
Hi,

For a week or two now, namespace "Windows" is not recognised with my universal windows hosted apps.
Please find the screenshot of what's going on when i press F12:

![console](https://cloud.githubusercontent.com/assets/88729/8799777/c3c8df08-2f7a-11e5-97fa-649375276468.png)

Was perfectly working before and as you can see, next to "undefined" the rest is recognised but I cannot use the windows API within my hosted app because (typeof Windows) always returns "undefined".

Do you know why suddenly, all calls to "Windows" return first "undefined"?

Thanks

**Comment by AdamBraden** [comment]
This question is not pertinent to the Samples discussion.  You should post general development questions in the Windows Apps forums
https://social.msdn.microsoft.com/Forums/windowsapps/en-US/home?forum=wpdevelop
