### ISSUE TITLE
Does it support play 3D_360 video ?

### ISSUE THREAD

**Issue by thanhlt801** [Microsoft/Windows-universal-samples#901]
I have tried to play a 3D_360 video with Samsung Odyssey but it's fail.
So this sample is support or not ? 
If you have any suggestion (with 3DUnity, another DirectX sample ...), please help me.
Thank you !

**Comment by oldnewthing** [comment]
This is a question about the platform, not the sample. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:

1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
