### ISSUE TITLE
POS Printing Windows IoT

### ISSUE THREAD

**Issue by funselaar** [Microsoft/Windows-universal-samples#903]
Hi,

I have been trying to use the POS Printing sample on Windows IoT running on a Raspberry Pi 2B. It is not clear for me if it is actually supported. I have been using a TM-T20II with ethernet to test this.
I am able to find the printer Id using a device watcher. I also got a message on the raspberry pi that the printer wanted to 'pair'. But when I create a POSPrinter from the printer Id, it returns null. There are no exceptions thrown.

Is there someone who can point me in the right direction?

Thanks in advance!

**Comment by oldnewthing** [comment]
I've asked the POS Printing team to investigate.

**Comment by mchen-msft** [comment]
I've tried running the latest checkout of the PosPrinter sample on a Raspberry Pi 2 running Windows 10 IoT 1803 (10.0.17134.1), and the sample works with an Epson receipt printer.  If this is different from your set up, please share so I can update my configuration. 

Can you clarify the following:
> But when I create a POSPrinter from the printer Id, it returns null.

Does this mean the call to `Windows.Devices.PointOfService.PosPrinter.FromIdAsync()` returned null or does it mean that the call to `DeviceHelpers.GetFirstDeviceAsync()` returned null?

After the pairing UI for your printer displayed and you consented to pairing, if you were to try the sample again immediately, does the PosPrinter sample work?
