### ISSUE TITLE
'FullScreenMode' Sample has an issue when minimising from fullscreen

### ISSUE THREAD

**Issue by EliteSpartan** [Microsoft/Windows-universal-samples#904]
When using the 'exit fullscreen' button (middle), it doesn't update the status at the bottom of the page

![image](https://user-images.githubusercontent.com/6450057/40885091-faca48ec-675e-11e8-9ec6-cc55293260ec.png)

After clicking the button above, this is what's shown:

![image](https://user-images.githubusercontent.com/6450057/40885111-31108bb4-675f-11e8-8d9c-3d272553a493.png)

**Comment by oldnewthing** [comment]
This is just the sample not clearing the message. The message is left over from when you originally entered full screen.

**Comment by oldnewthing** [comment]
Okay, fix coming in next refresh. Thanks for your patience.

**Comment by oldnewthing** [comment]
Fixed in [v6.0.5](https://github.com/Microsoft/Windows-universal-samples/releases/tag/v6.0.5).
