### ISSUE TITLE
Request: Example of settings UI replication (See Dynamic Theme)

### ISSUE THREAD

**Issue by jrkd** [Microsoft/Windows-universal-samples#906]
Was recently impressed with the Dynamic theme app (https://www.microsoft.com/en-gb/p/dynamic-theme/9nblggh1zbkw) and as a developer didnt realize you could match so closely the settings UI setup with left nav menu, main content/form, right col extra info. 

Wondering if MS could set up an example that shows how to replicate this? 

I also wonder whether the developer just put a lot of time and effort to mimic the windows settings UI, or that windows enables these as defaults. 

![image](https://user-images.githubusercontent.com/15888839/41151697-7405ab36-6b09-11e8-886e-5976a946b370.png)

Thanks
J

**Comment by oldnewthing** [comment]
There is already a sample for this. See Xaml UI Basics, NavigationView.

**Comment by jrkd** [comment]
Brilliant, thanks for that @oldnewthing
