### ISSUE TITLE
There is no sample how to create a custom WebAccountProvider, only how to use it?

### ISSUE THREAD

**Issue by hansmbakker** [Microsoft/Windows-universal-samples#911]
There seems to be no sample how to create and register a custom `WebAccountProvider`.

There is a [presentation from Microsoft Build 2015](https://channel9.msdn.com/Events/Build/2015/2-709) that shows the concepts, but

- the code in the appendix is not complete
- the "tokenbroker" sample referenced from the presentation is not available anymore.

I found https://github.com/jaimerodriguez/WebAccountProvider/ but it would be good if that would be polished and maintained in the official Microsoft documentation as there is no other documentation about it.

**Comment by oldnewthing** [comment]
I created an item on the feature team's backlog.

**Comment by hansmbakker** [comment]
@oldnewthing could you please give an update its status?

**Comment by oldnewthing** [comment]
Still active on the backlog.

**Comment by hansmbakker** [comment]
Ok, thank you for the quick response! Is there any chance you could indicate an expected timeframe? (Weeks? Months? Half year? Year?)

**Comment by oldnewthing** [comment]
The feature team didn't say. The item is still active on their backlog, and they marked it as a priority for the next major release of Windows after 1903, but they didn't give a specific timeframe.

**Comment by hansmbakker** [comment]
Thank you for asking!

**Comment by hansmbakker** [comment]
The same sample is asked for in
- https://github.com/Microsoft/msdn-content/issues/1
- https://github.com/Microsoft/Windows-universal-samples/issues/577
- https://github.com/Microsoft/Windows-universal-samples/issues/377

**Comment by hansmbakker** [comment]
@oldnewthing could you let us know what the status of the backlog item is?

**Comment by oldnewthing** [comment]
Still on the backlog.

**Comment by hansmbakker** [comment]
@oldnewthing is there any update on this?

**Comment by oldnewthing** [comment]
Still on the backlog. I will update this issue if the status of the backlog item changes.

**Comment by michael-hawker** [comment]
Isn't that this sample? https://github.com/Microsoft/Windows-universal-samples/tree/main/Samples/WebAccountManagement

**Comment by hansmbakker** [comment]
No, because that sample does not properly implement the manifest, activation events, backgroundtask etc as explained in this repository: https://github.com/jaimerodriguez/WebAccountProvider.
