### ISSUE TITLE
How to build CustomCapability for ARM.

### ISSUE THREAD

**Issue by syhuang75** [Microsoft/Windows-universal-samples#914]
I want to build CustomCapability for ARM, but in Solution Properties -> Configuration Properties , only CustomCapability Build is checked. After I check RpcClient , RpcInterface and RpcServer, I get some error.

Error message :
---------------------------------------------
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Platforms\ARM\PlatformToolsets\v141\Toolset.targets(53,5): error MSB8022: Building Desktop applications for the {0} platform is not supported.
1>Done building project "RpcInterface.vcxproj" -- FAILED.
2>------ Rebuild All started: Project: RpcClient, Configuration: Debug ARM ------
2>pch.cpp
2>RpcInterface_c.c
2>c1 : fatal error C1083: Cannot open source file: 'C:\Users\aaa\Downloads\Windows-universal-samples-master (1)\Windows-universal-samples-master\Samples\CustomCapability\cpp\ARM\Debug\RpcInterface_c.c': No such file or directory
2>Done building project "RpcClient.vcxproj" -- FAILED.
3>------ Rebuild All started: Project: CustomCapability, Configuration: Debug ARM ------
---------------------------------------------

Question : 
Is this project support ARM?
Is RPC connection support ARM?

Thanks a lot.

**Comment by oldnewthing** [comment]
Custom Capabilities are supported on ARM, but only for devices.
