### ISSUE TITLE
Connection terminated due connection parameters update failed

### ISSUE THREAD

**Issue by YUSMLE** [Microsoft/Windows-universal-samples#916]
While pairing Windows 10 with my advertising Android app, BLE connection parameters update failed and connection terminated. 

**Steps to produce:** 
  - Scan for BLE devices through Windows 10 Bluetooth manager, 
  - Find the advertising Android app (Peripheral) and pair to it, 
  - Device bonded, but connection state will change from **Connected** to **Paired** immediately in both sides, or 
  - Pairing failed. 

**Reason:** 
  When I check the Bluetooth log in Android device, I can see the failure to update connection parameters. 

I think it's because of `Supervision Timeout parameter`, because when I check the log for successful pairing and connection between two Android devices, I see they have agreed for `timeout = 20000 ms`, but Windows 10 and Android have not agreed for `timeout = 9600 ms`!

**Note:** BLE Supervision Timeout parameter is hard-coded in Android (`=20000 ms`)!

**Note:** I use the [nRF Connect Android app](https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp&hl=en) for create a sample Peripheral, but I have same behavior with my main Android app.

I attached both logs for _Windows-Android_ and _Android-Android_.

[Log - Pair via Windows.txt](https://github.com/Microsoft/Windows-universal-samples/files/2094516/Log.-.Pair.via.Windows.txt)
[Log - Pair via Android.txt](https://github.com/Microsoft/Windows-universal-samples/files/2094519/Log.-.Pair.via.Android.txt)

**Comment by oldnewthing** [comment]
This is not an issue with a sample in this repo. You can open a support case with our Developer Support team:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
