### ISSUE TITLE
UWP App Samples Issue

### ISSUE THREAD

**Issue by kevinb67** [Microsoft/Windows-universal-samples#918]
I downloaded the samples ZIP folder, unblocked it in the properties menu, then extracted to the repos folder. I tried to open one of the sample solutions in Visual Studio and got this message in the output window:

Hi. I downloaded the UWP app samples ZIP file, then unblocked the file in the properties menu like the instructions said. I then extracted the ZIP file to a folder. I tried to open one of the sample solutions in Visual Studio 2017, but I got this message in the output window:
 
[Failure] Could not find file 'C:\Users\kevin\source\repos\Windows-universal-samples-master\Samples\BackButton\cs\obj\x86\Debug\App.g.i.cs'.
[Failure] Could not find file 'C:\Users\kevin\source\repos\Windows-universal-samples-master\Samples\BackButton\cs\obj\x86\Debug\MainPage.g.i.cs'.

I found a file named "MainPage.g.cs" and a file named "App.g.cs" in the DeBug folder. Neither file had an "I" in it.

Please help. Thanks.

**Comment by oldnewthing** [comment]
I cannot reproduce this error. Please be more specific: What version of Visual Studio? Which version of the BackButton sample? Did you get this message when opening the solution, or when trying to build it?
