### ISSUE TITLE
[Question] How MediaPlayer & MediaBinder API work with FFmpegInterop?

### ISSUE THREAD

**Issue by HppZ** [Microsoft/Windows-universal-samples#919]
I want to play media files in the background using MediaPlayer and FFmpegInterop, but the args of MediaBinder's Binding event does not support MediaStreamSource.
Please HELP. Thanks.

**Comment by oldnewthing** [comment]
This doesn't appear to be an issue with a sample in this repo. You can open a support case with our Developer Support team who can help with your problem.

1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
