### ISSUE TITLE
Problem running the accountpicturename sample

### ISSUE THREAD

**Issue by sebagomez** [Microsoft/Windows-universal-samples#92]
I want to run the sample from above and get a `Access to name disabled by Privacy Settings or Group Policy`. 
How can I check them both? I have enabled Account Info under privacy settings

**Comment by oldnewthing** [comment]
Thanks for reporting the problem. We are investigating.

**Comment by oldnewthing** [comment]
So it appears that the UserInformation class is deprecated in Windows 10; that's why it doesn't work any more. I'll get the sample updated to use the new Windows.System.User class instead.

**Comment by sebagomez** [comment]
I'll work on it and create a PR

**Comment by oldnewthing** [comment]
No need. I already fixed it. Will arrive at the next refresh.

**Comment by sebagomez** [comment]
Cool thanks

**Comment by oldnewthing** [comment]
The new UserInfo sample (which replaces AccountPictureName) is in 4968d97b7ecc92a8772796ae79e703c78012ac68 thanks for your patience.
