### ISSUE TITLE
RadioManager: Cannot set radio state of Mobile Broadband device.

### ISSUE THREAD

**Issue by kz-osaka** [Microsoft/Windows-universal-samples#924]
The Mobile Broadband radio status cannot be changed.

The toggle button is returned to original state immediately after toggling.

If I change the status from OS UI, app UI is sync with it correctly.

**Comment by oldnewthing** [comment]
I've asked the team to investigate.

**Comment by oldnewthing** [comment]
This is a flaw in the sample. Turning the mobile broadband radio on/off requires a restricted capability, which the sample does not have. I'll fix the sample to disable the toggle button for mobile broadband radios (since the sample does not possess the restricted capability).

**Comment by PRIMETSS** [comment]
Hmm having same issue with 
`var access = await WiFiAdapter.RequestAccessAsync();`
access = deniedBySystem

Is there no way to turn of Bluetooth and WiFI on RPi? As I need to stop it broadcasting and inducing signals into an AtoD application that is sensitive to induced noise from the radios....
