### ISSUE TITLE
MultipleViews - Incorrect background color for secondary view (CoreWindow)

### ISSUE THREAD

**Issue by anup-das** [Microsoft/Windows-universal-samples#928]
Hi,
I am developing an app that uses XAML for its primary view for presenting UI. 
I need to have a secondary view without XAML that is not shown as stand alone and switched using ApplicationViewSwitcher::SwitchAsync() 

I successfully created a secondary view using the IFrameworkViewSource overload of  CoreApplication::CreateNewView() method. I provided a separate implementation of IFrameworkViewSource 

Everything works fine except that the entire window (title bar and window client area) gets the same color of the title bar accent color and there is no way to change that color.  Actually I do not need to change the color as long as the correct CoreWindow background color gets used (same as for apps that do not use XAML). 

I tried placing a SpriteVisual with black solid color as the root of visual tree as a workaround but when resizing the window it is obvious that the window body is showing the accent color and later it is covered with black on top. I hope there are no issues in an app having an XAML primary view and just CoreWindow as the secondary view.

Kindly let me know what I am doing wrong or provide a way to change the background color of secondary view's CoreWindow.

Thanks,
Anup

**Comment by oldnewthing** [comment]
This is not an issue with a sample in this repo. You can open a support case with our Developer Support team who can help with the specific problem you are experiencing:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
