### ISSUE TITLE
Using Windows.Media.FaceAnalysis.FaceDetector throws an error

### ISSUE THREAD

**Issue by Garcia2123** [Microsoft/Windows-universal-samples#929]
When I try to use ` Windows.Media.FaceAnalysis.FaceDetector`,  DevTools throws an error:
0x80040155 - JavaScript runtime error: Interface not registered.
My code:
![image](https://user-images.githubusercontent.com/15050528/41847365-52240570-78ac-11e8-9540-3810ee338f08.png)

**Comment by oldnewthing** [comment]
This is not a question about a sample in this repo. You can open a support case with our Developer Support team:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
