### ISSUE TITLE
Sample Printing

### ISSUE THREAD

**Issue by ArchieCoder** [Microsoft/Windows-universal-samples#935]
Hello,

When running the sample, the Height is not high enough in the top, the word "PrintSample" is clipped.

![printsample](https://user-images.githubusercontent.com/1608424/42245877-7c2a0ca6-7ee8-11e8-9601-65b8a903256d.png)

**Comment by oldnewthing** [comment]
I've asked the feature team to investigate.

**Comment by Ganeshcoep** [comment]
Pushed a PR is, its under review.

**Comment by oldnewthing** [comment]
Fix has been ingested into staging repo. Will go out at next public refresh. Thanks for reporting.
