### ISSUE TITLE
XAML Controls Gallery app's icons disappeared in NavigationView

### ISSUE THREAD

**Issue by jfranki** [Microsoft/Windows-universal-samples#937]
For the second time some icons in the NavigationView have disappeared. Closing and reopening the app does not solve the problem, the only workaround I found is to reinstall.

![icons_missing](https://user-images.githubusercontent.com/6547157/42373776-37962b76-8116-11e8-93fa-ebbdfe99c48e.jpg)
![icons_missing_compact](https://user-images.githubusercontent.com/6547157/42373777-37b599fc-8116-11e8-8c02-b267c41f6ae8.jpg)

**Comment by oldnewthing** [comment]
I've asked the feature team to investigate.

**Comment by vsriram11** [comment]
Do you have any more specifics on how to repro this?

**Comment by vsriram11** [comment]
And also give us details on the app version and OS version you're on when this happens? Thanks!

**Comment by jfranki** [comment]
I could not say how to reproduce the issue… I know that I had opened it multiple days without issues until suddenly the icons disappear. I will reinstall and keep an eye, but it must be a tough one to identify…

App version 1.1.1.0
OS version Windows 10 Pro 1803 (17134.112)

**Comment by stmoy** [comment]
Thank you for reporting this issue. We updated the icons in the NavigationView from .pngs to font icons which should solve this issue.
