### ISSUE TITLE
Call blocking API question

### ISSUE THREAD

**Issue by darkfires** [Microsoft/Windows-universal-samples#938]
I'm trying to make a call blocking application that can dynamically block incoming calls based on a pattern match.  Having major issues with one ring call scams will get like 40+ calls a day from say +252 6 4648020 but each call the last part of the number is slightly different so the next one isn't blocked.

I've basically added the CallOriginDataRequest to the sample CommunicationBlockAndFilter, and call PhoneCallBlocking.SetCallBlockingListAsync() if it matches.  This part works, but the first call still comes thru, it's only automatically blocking subsequent calls. 

The API docs also detail these properties:
            PhoneCallBlocking.BlockUnknownNumbers = true;
            PhoneCallBlocking.BlockPrivateNumbers = true;

I thought possibly I could use the origin results to help it decide whether a number is actually unknown or not, but while it lets me set those to true it doesn't actually affect the behavior.

I'm assuming that the CallOriginDataRequest for Caller ID is occurring after the internal call PhoneIsPhoneNumberInBlockList() which seems to be an RPC call that checks the list set by SetCallBlockingListAsync().  So I need some way of grabbing the phone number of an incoming call sooner so I can add it to the block list before the block list gets processed for the call...

Ideally if I could have SetCallBlockingListAsync somehow call a function instead of an array list or maybe somehow have control over triggering Ignore on an incoming call...  I see there's also an internal function PhoneRejectIncoming() but It doesn't look like that's a public accessible function either.  Hoping you guys might have an idea.

Thanks

**Comment by oldnewthing** [comment]
This isn't a question about the CommunicationBlockAndFilter sample but rather a question about writing your own call blocking application. You can open a support case with our Developer Support team:

1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
