### ISSUE TITLE
socketactivitystreamsocket sample stop receive messages after some time.

### ISSUE THREAD

**Issue by artall64** [microsoft/Windows-universal-samples#94]
I launch sample:
- socketactivitystreamsocket on desktop
- socketactivitystreamsocket on my Lumia with windows 10

Initially, all works fine.
Then I lock screen and wait for 8 minutes and send a message - nothing happened.
I send a message again. And see the message on server side "An existing connection was forcibly closed by remote host. (Exception from HRESULT: 0x80072746)"

Log of my actions:

9.44 - send messages all works fine even on lock screen
9.44 - lock screen
9.52 - send message nothing
9.52 - send message nothing
9.52 - An existing connection was forcibly closed by the remote host.
9.53 - Client connected message in server app
9.54 - Send message nothing
9.54 - Send message 
9.54 - An existing connection was forcibly closed by the remote host. (Exception from HRESULT: 0x80072746)
9.56 - unlock the phone - no any message after 9.44

**Comment by DavidGoll** [comment]
We're about to refresh the samples and tools with the final versions coinciding with the release of Windows 10. I don't think this is a known issue with this version, but we will take a look.

**Comment by DavidGoll** [comment]
Confirmed that there is a problem. Continuing the investigation.

**Comment by lanatmwan** [comment]
This sounds like expected behavior when a connection gets cut for any reason, except that it should have returned the 0x80072746 after the first failed message on either end right?

**Comment by artall64** [comment]
Actually I expect that with this background stream socket activity I can implement some kind of push notification ( I take this idea from one of the presentations at Build 2015).

For my app, it's very important to receive incoming notifications from a server in 1 - 3 seconds.
With this sample, I expect to saw that. But I faced with the fact that connection gets cut every ~8 seconds and client side initiate reconnection every 10 seconds.

Could I somehow tune this sample to have guarantee message delivery in 1-3 seconds?
(Assume we have local network that work fine)

The second issue if the connection is lost I want to be able to reconnect to a server as soon as possible. For example, if I come back from the place without network connection I want to reconnect to the server in 15 seconds.
Could I achieve that using background stream socket activity or that possible only with WNS?

**Comment by pravb** [comment]
@artall64 please use WNS APIs which is the recommended way to achieve background stream socket activity. Closing out this old thread.
