### ISSUE TITLE
CameraFrames not working with samsung odyssey 

### ISSUE THREAD

**Issue by diegohdezr** [Microsoft/Windows-universal-samples#940]
We are trying to run the CameraFrames demo with the Samsung odyssey to get access to the device cameras but we are unable since the app does not find a source group that may apply, Am I missing some sort of configuration? or step for the device? it works normally on any other webcam.

**Comment by oldnewthing** [comment]
This doesn't appear to be a problem with the sample, but rather with the hardware. You can open a support case with our Developer Support team:

1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
