### ISSUE TITLE
exposure time

### ISSUE THREAD

**Issue by dntrinca** [Microsoft/Windows-universal-samples#941]
Hello,

  I am writing with 2 questions I have about this application:

  Can it be used with hyperspectral camera also ?

  Is it possible to take image with camera at a certain exposure time ?

  Have a Nice Day,
  Dragos Trinca

**Comment by oldnewthing** [comment]
This does not appear to be an issue with a specific sample in this repo. You can open a support case with our Developer Support team:

1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
