### ISSUE TITLE
OCR Sample Error - 'Invalid subtype'

### ISSUE THREAD

**Issue by RichardThor** [Microsoft/Windows-universal-samples#943]
I get this error when testing the code on my Desktop computer with  a webcam.

Error In the C# code, line 185
using (var currentFrame = await mediaCapture.GetPreviewFrameAsync(videoFrame))
The Error is: System.ArgumentException: 'The parameter is incorrect. Invalid subtype.

Procedure: 
1. start program
2. Select #2 - capture from camera
3. position text in front of web cam
4. click on the "translate" button.
** Error**

**Comment by oldnewthing** [comment]
I've asked the media capture team to investigate. Can you provide details about what kind of webcam you have and what driver it uses?

**Comment by saredd** [comment]
Hi Richard,

Can you file a feedback in the Feedback Hub with the Category: Devices and Drivers - Device Camera or Webcams.

You can use "Recreate my problem" there and repro the issue to collect logs for us to investigate.

After you have filed the feedback, there should be a link you can share here that will directly link to your feedback. This will also include information about the webcam being used and the driver version.

**Comment by oldnewthing** [comment]
This appears to be a device-specific issue. If it turns out to be a problem with the sample, we can reopen.
