### ISSUE TITLE
IsRandomAccessRequired

### ISSUE THREAD

**Issue by omansak** [Microsoft/Windows-universal-samples#944]
5.0.0 hav IsRandomAccessRequired but 6.1.5 doesnt. How IsRandomAccessRequired  to use in 6.1.5 ?

**Comment by DavidGoll** [comment]
Do you mean v7.0.0? In any case, what really matters is which Windows versions support the API. This property is supported for Windows versions 10.0.16299.0 and higher. The samples were updated to illustrate the use of the property in the Windows 10 Version 1709 - January 2018 Update (v7.0.0) update in github.

**Comment by oldnewthing** [comment]
I think OP is asking about the .NET Framework version, not the UAP version. As such, this is not a samples issue.

**Comment by DavidGoll** [comment]
I realize now that you are referring to .NET Core UWP version 6.1.5. The IsRandomAccessRequired property is in the Windows.Networking.BackgroundTransfer namespace which is one of the [Windows UWP namespaces](https://docs.microsoft.com/en-us/uwp/api/). It is not part of .NET Core UWP.

**Comment by omansak** [comment]
This is no available in Microsoft.NETCore.UniversalWindowsPlatform 6.1.5

https://github.com/Microsoft/Windows-universal-samples/blob/157c9eb6127947e71458e473eb796f9585bc248e/Samples/BackgroundTransfer/cs/BackgroundTransfer/Scenario5_RandomAccess.xaml.cs#L260
