### ISSUE TITLE
Pull To Refresh Sample

### ISSUE THREAD

**Issue by mjsabin01** [Microsoft/Windows-universal-samples#95]
I was looking over the Pull To Refresh sample and had a couple of questions:

1.) I noticed that you put the ListView inside a ScrollViewer.  I was under the impression that it shouldn't be done, because it would prevent virtualization.  Is that not the case?

2.) I am able to get the pull to refresh to work with my touch screen, but is there any way to get it to work with a mouse?

**Comment by mikehenderlight** [comment]
1) In this case virtualization will still work because we have provided a constraint with the MyPanel object.
2) This gesture is only intended to work for touch and not mouse.
