### ISSUE TITLE
UserInformation - how to get principal name for an AAD joined machine

### ISSUE THREAD

**Issue by bgavrilMS** [Microsoft/Windows-universal-samples#952]
If a machine is AD joined, I can get the user principal name as demonstrated in the sample. If the machine is AAD joined instead, I cannot get the user principal name, even though the machine has access to the corporate network and the "Access Work or School" account has this detail. I am able to get other properties such as the FirstName, LastName and picture, which are associated with the MSA account.

Is there a way to get the user principal name of the Work or School account, if any ?

**Comment by oldnewthing** [comment]
This isn't an issue with a sample in this repo. You can open a support case with our Developer Support team:

1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.

(Limitations on what properties are available for different types of accounts is documented [here](https://docs.microsoft.com/en-us/uwp/api/windows.system.user.getpropertiesasync#remarks).)
