### ISSUE TITLE
UserInformation - filtering the AD joined user

### ISSUE THREAD

**Issue by bgavrilMS** [Microsoft/Windows-universal-samples#953]
In order to use Windows Integrated Auth, I need to get the user principal name of the domain user (assuming the machine is AD joined). 

Could you explain how to use the FindAllAsync API to find this user out ?

**Comment by oldnewthing** [comment]
This isn't an issue with a sample in this repo. You can open a support case with our Developer Support team:

1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.

(Limitations on what properties are available for different types of accounts is documented [here](https://docs.microsoft.com/en-us/uwp/api/windows.system.user.getpropertiesasync#remarks).)
