### ISSUE TITLE
DownloadOperation get 0x80072EF1 while minimize

### ISSUE THREAD

**Issue by omansak** [Microsoft/Windows-universal-samples#954]
I have a DownloadOperation in my UWP application , if it is minimize , get error 0x80072EF1(OperationCanceled)

**Comment by oldnewthing** [comment]
The issue you are running into is not about a sample in this repo. You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
