### ISSUE TITLE
Windows Hello for Kiosk-like apps?

### ISSUE THREAD

**Issue by georghinkel** [Microsoft/Windows-universal-samples#957]
Is it possible to use Windows Hello to authenticate users in a kiosk app? I would like to achieve something similar to the greeting kiosk [1], but using Windows Hello instead of the cognitive services: The app runs fullscreen and uses Windows Hello to identify users, very similar to the Windows logon screen. When a user of the camera comes within reach, I would like to access his identity and navigate to further UI.

For that, I can assume that all users that will use the kiosk have an account that is set up with Windows Hello. However, the passport sample from this repo [2] always tries to authenticate the current user that is running the kiosk app. If a different user is seen in front of the camera, the camera detects ther user, this user is greeted ("Hello <user name>"), but the Windows Hello popup only allows to click the cancel button. Did I miss something or is this a scenario that simply is not supported by the current API?

Thanks for the help in advance

[1] https://github.com/Microsoft/Cognitive-Samples-IntelligentKiosk/blob/master/Documentation/GreetingKiosk.md
[2] https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/MicrosoftPassport

**Comment by oldnewthing** [comment]
This is not an issue with a sample in this repo. You can open a support case with our Developer Support team:

1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
