### ISSUE TITLE
Reading DatagramSocket in the background

### ISSUE THREAD

**Issue by karthikveeramani** [Microsoft/Windows-universal-samples#958]
I am trying to read a DatagramSocket in the background.

Quoting from https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/DatagramSocket :

> If you are interested in developing an app that is always connected and always reachable using background network notifications in a UWP app, refer to the SocketActivityTrigger documentation. The SocketActivityTrigger StreamSocket Sample is a good starting point, since the programming pattern with DatagramSocket is essentially the same as with StreamSocket.

Starting with something like ...

```
case SocketActivityTriggerReason.SocketActivity:
    var socket = socketInformation.DatagramSocket;
    // socket.InputStream   => missing!
```

I would think that there is InputStream object in socket just like there is an OutputStream, but I don't find anything that seems to let me read. What am I missing and how do I read the socket in the background?

**Comment by Diego-Perez-Botero** [comment]
Hi @karthikveeramani,

The DatagramSocket class doesn't have an InputStream property; it follows an event-based model for incoming I/O (see [MessageReceived](https://docs.microsoft.com/en-us/uwp/api/windows.networking.sockets.datagramsocket.messagereceived)). Your background task should do something similar to what is being suggested in [this stackoverflow post](https://stackoverflow.com/questions/40744667/get-data-from-socketactivitytriggerdetails-with-datagramsocket):

`public async void Run(IBackgroundTaskInstance taskInstance)
{
    var deferral = taskInstance.GetDeferral();
    try
    {
        var details = taskInstance.TriggerDetails as SocketActivityTriggerDetails;
        var socketInformation = details.SocketInformation;
        switch (details.Reason)
        {
            case SocketActivityTriggerReason.SocketActivity:
                var socket = socketInformation.DatagramSocket;
                socket.MessageReceived += Socket_MessageReceived;

                // Wait for data to be read by MessageReceived handler (e.g., waiting on an event that is signaled by the handler).
                // Write some data.

                // Transfer socket ownership back to the broker.
                await socket.CancelIOAsync();
                socket.TransferOwnership(…);
                break;
            default:
                break;
        }
        deferral.Complete();
    }
    catch (Exception exception)
    {
        ShowToast(exception.Message);
        deferral.Complete();
    }
}

private void Socket_MessageReceived(DatagramSocket sender, DatagramSocketMessageReceivedEventArgs args)
{
    using (var reader = args.GetDataReader())
    {
        //TODO: read data here.
    }
}`

**Comment by karthikveeramani** [comment]
Thank you. It worked as you said.

**Comment by oldnewthing** [comment]
Note also that this is not a question about a sample in this repo. For general developer support, please use http://aka.ms/storesupport
