### ISSUE TITLE
Logs When Application Crash

### ISSUE THREAD

**Issue by mj430** [Microsoft/Windows-universal-samples#960]
If I am using the FileLoggingSession , how does i get access to logs if my application crash. As I will not have time to call CloseAndSaveToFileAsync.

**Comment by oldnewthing** [comment]
This is a platform question, not a samples issue. You can open a support case with our Developer Support team:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
