### ISSUE TITLE
CameraFrames sample supporting IR with Nv12

### ISSUE THREAD

**Issue by gtRfnkN** [Microsoft/Windows-universal-samples#963]
Hello everyone,

first of all thank you for these great samples!

I am currently working on an app for a check-in flow at a public kiosk: the app takes a color picture of the user standing in front of a Surface Pro and uses the IR camera to verify that the user is a real person (anti spoofing).

For that I wanted to access the IR camera of the Surface, but the CameraFrames sample didn't show the IR image. It turns out, that it expects the IR subtype to be L8 or L16 ([code](https://github.com/Microsoft/Windows-universal-samples/blob/master/Samples/CameraFrames/cs/FrameRenderer.cs#L109)), but the Surface Pro provides Nv12. After adding this to the list of supported subtypes, I do get an IR stream (sadly, the colors seem of, probably because `PseudoColorFor8BitInfrared` does not work well with Nv12). Can you add support for Nv12 IR streams?

One other thing regarding the flow I want to achieve: I also looked into the Windows Passport sample, but it did not seem fit for a public kiosk, because the user has to do a full enrolment with Windows Hello. But is there an easier way using the Windows Passport to only take a color picture of the user and use IR (like Windows Hello does) to make sure, the user is a real person?

Thanks!

**Comment by oldnewthing** [comment]
These don't appear to be issues with the samples, but rather questions on how to extend the samples. You can open a support case with our Developer Support team:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
