### ISSUE TITLE
XAMLUI Basics Exception Animation Interop

### ISSUE THREAD

**Issue by Batteredburrito** [Microsoft/Windows-universal-samples#966]
When building XAMLUIBasics and Selecting Animation Interop from the whats new panel, get the following exception occur:

System.InvalidCastException: 'Unable to cast object of type 'Windows.UI.Xaml.Shapes.Ellipse' to type 'Windows.UI.Xaml.IUIElement9'.'

**Comment by oldnewthing** [comment]
What build are you running on? I suspect you're running on an old Insider build that the sample doesn't support.

**Comment by Batteredburrito** [comment]
Im on Build 17738.100 i believe two versions newer than required? :/

**Comment by oldnewthing** [comment]
Okay, I'm not seeing any breaking changes in that interface between 17715 and 17738. Let me ask the feature team.

**Comment by oldnewthing** [comment]
Upgrade to 17763 and all should be forgiven.
