### ISSUE TITLE
AppUIBasics XAML Page Transitions do not function

### ISSUE THREAD

**Issue by Batteredburrito** [Microsoft/Windows-universal-samples#967]
The page transitions do not function. When using the "Navigate Forward" and "Navigate Backward" buttons, not animations play

**Comment by oldnewthing** [comment]
I've asked the feature team to investigate.

**Comment by oldnewthing** [comment]
The "Default" animation is to play no animation on Windows 10 version 1709, so if you are running on version 1709, then no animation is expected. The "default" animation does animate in newer builds, so please try again with the v7.0.2 version (or later) of the AppUIBasics sample, running on Windows Insider build 17763 or later.
