### ISSUE TITLE
AppUIBasics XAML Navigation View "API in Action" fails to update

### ISSUE THREAD

**Issue by Batteredburrito** [Microsoft/Windows-universal-samples#968]
The API in Action XAML script fails to update when selecting various options. 
This is under NavigationView right at the very bottom

**Comment by oldnewthing** [comment]
I've asked the feature team to investigate.

**Comment by oldnewthing** [comment]
This issue has been [migrated to the Xaml Controls Gallery issues database](https://github.com/Microsoft/Xaml-Controls-Gallery/issues/7).
