### ISSUE TITLE
AppUIBasics NavigationView back button hitbox partially covered before window resize

### ISSUE THREAD

**Issue by Silic0nS0ldier** [Microsoft/Windows-universal-samples#969]
In the AppUIBasics sample (aka XAML Controls Gallery), when the app first starts a large portion of the back button is covered by the title bars draggable region. This could be a z-order issue or the draggable region not being redefined as mentioned at https://docs.microsoft.com/en-us/windows/uwp/design/shell/title-bar#interactive-content. Stranger though is that once the window is resized the NavigationView component seems to self correct this issue by shifting the pane content down.

The issue has been observed on Windows builds 17134.165 (stable) and 17738.1000 (fast ring).

Before resize: 
![image](https://user-images.githubusercontent.com/17376090/44246896-0b7c0680-a224-11e8-9bb6-e69eb94869c3.png)

After resize: 
![image](https://user-images.githubusercontent.com/17376090/44246906-1afb4f80-a224-11e8-8c87-247d948c2ef4.png)

**Comment by oldnewthing** [comment]
I've asked the feature team to investigate whether this is a sample bug or a bug in NavigationView.

**Comment by Silic0nS0ldier** [comment]
Issue seems to have since been resolved (on Insider builds and production) in the sense of that the self-correction occurs during app start (you can see components jump around for a second).
Sample app still draws into the title bar (https://github.com/Microsoft/Windows-universal-samples/blob/master/Samples/XamlUIBasics/cs/AppUIBasics/App.xaml.cs#L147) which explains why its not a perfectly smooth transition. Documentation at https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/navigationview has also removed all mention of how to draw into the toolbar.

Issue is resolved. Resolution means its harder to adhere to fluent design recommendations (we'd have to make the `NavigationView` background transparent and place a control painted with the fluent material that adapts to match the state of the `NavigationView`, not impossible but more work).
