### ISSUE TITLE
UWP NavigationView.PaneFooter Rollover Issues

### ISSUE THREAD

**Issue by Batteredburrito** [Microsoft/Windows-universal-samples#970]
Hi, 
Im not sure if this is an issue OR a limitation with NavigationView itself. Essentailly, the PaneFooter is having issues with the Rollover effects within the latest update. I believe this also affects earlier versions.

I have linked my StackOverflow discussion to further clarify the issue at hand:

[](https://stackoverflow.com/questions/51879641/uwp-navigationview-panefooter-rollover-issues/51881374?noredirect=1#comment90724723_51881374)

As the image/post suggest, I cannot seem to find a way to make the rollover effects stretch across the entire span of the Navigation View when bound to the Footer. Theres no issues with standard NavViewItems except when they are placed inside the PaneFooter.

Is there any way to correct this. My current workaround is to use a Textblock within a stack panel and a Button. Its a horrible workaround that just doesnt look nice.
Ideally the PaneFooter should copy the same rollover effect/formatting as the settings option at the bottom of NavView.

**Comment by oldnewthing** [comment]
This appears to be a platform issue rather than an issue with the sample itself. I've asked the feature team to investigate, but it is not a sample issue. I'll update this issue with any response from the feature team, but the issue itself is closed as "not a sample issue".
