### ISSUE TITLE
Maybe a dumb question?

### ISSUE THREAD

**Issue by kbmuri** [Microsoft/Windows-universal-samples#971]
Hi everyone. I'm not new to this forum but I've been very quiet. I've only spoken up a couple of times. I see a lot of @#$@#ing and complaining in a lot of issue reports and I've gathered the technical support here is often iffy at best. I don't want to have this post misconstrued as such. I am not complaining nor chewing anybody out. I realize people can only do their best.

I am a 35-year veteran Windows programmer. I've worked in Defense, Aerospace, and commercial environments. I have to be utterly professional in my work. On rare occasion I download your samples to start a brainstorming session by looking at some of your clever solutions. Every time, I download the entire repository (not just parts of it) as a colossal Zip file. I unzip it into my C: drive (to avoid causing any path names to be "too long"). I open a fresh Visual Studio session, I open a project of interest.

EVERY TIME I do so, the solution does not build. It's not the exception, it's the norm.

Today I did the same. I am quite interested in adding WiFiDirect capability to one of my existing professional UWP apps. Wanting to examine your sample, I downloaded the entire repository zip and opened the solution as described:

![a-few-errors](https://user-images.githubusercontent.com/17327534/44315632-3026d880-a3f4-11e8-9af2-6a357616c1e0.png)

![nothing-but-errors](https://user-images.githubusercontent.com/17327534/44315640-446ad580-a3f4-11e8-9ec3-cdd8c49e216b.png)

As you can see, the source code is nothing but errors.

I usually figure out what is missing/wrong after a few minutes to a few hours (or sometimes a few days) if I feel it's worth the trouble. It's been the standard routine every time I go here. I will do so again shortly to make this project build. Doing so may or may not result in the same project anymore. Often this turns into a wild goose chase that I eventually have to abandon in frustration.

The question is, Why should I have to go through this? Don't you think you should provide samples that compile? If I did something like this in any of my professional work engagements I would be taken aside by a project manager and sternly lectured. If I did it twice, I would lose my assignment. Three times, I'd be shown the parking lot.

You guys do it almost all the time. Does Microsoft not care?

I am intrigued by your "Project Rome" sample. I would have liked to have played with it. In this case I was not able to discern what was wrong with the sample solution. It does not build as-is. I have an error that several others on its issues page have brought up. There seems to be no real effort on your end to explain it. Feel free to look at my post there. I've just now thrown in the towel and abandoned that plan of attack as "futile".

Again, I'm not criticizing. I would ask why you don't hire someone to open every project in a fresh install of the appropriate version of Visual Studio and see if it compiles/builds, and if it doesn't, then don't release it to the public until it does.

There's nothing unorthodox about my PC, nor its environment. It's a completely up-to-date install of Windows 10, with a presumably appropriate installation of Visual Studio (Community 2017 15.5.6 in this case) that I have used to develop dozens of working and fielded apps. I also have every version of Visual Studio all the way back to 1997 and have written maybe 2000-3000 apps over the transpiring 20+ years, at the end of a 35-year career in same. I'm disinclined to believe I'm doing something stupid. Or expecting too much from customer support.

Wish you guys would try a little harder.

You would get a lot fewer complaints and a substantially better reputation.

Anyway I suppose I should as a specific question.

Why does the WiFiDirect sample solution not build, fresh out of the box?

Thanks.

**Comment by Batteredburrito** [comment]
Hi, Youre building for arm devices. At the top of the page where the Debug is, try setting this to either X86 or X64 and build on the local machine :)

**Comment by oldnewthing** [comment]
If you have any fixes, feel free to contribute them back. I do know that you get red squiggles immediately upon loading because the NuGet packages haven't been installed yet.
