### ISSUE TITLE
Connect a Wireless display without windows settings. 

### ISSUE THREAD

**Issue by liangming2003** [Microsoft/Windows-universal-samples#972]
Hi, Raymond

I want to devevlop a C# app that can search and connect to a wireless display without pressing "Win + K" or running "explorer.exe ms-settings-connectabledevices:devicediscovery",  Which example should I look at in Windows-universal-samples? Thanks.

**Comment by oldnewthing** [comment]
I don't know either. You can open a support case with our Developer Support team:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
