### ISSUE TITLE
Is it possible to use SystemMediaTransportControls to get currently playing song metadata?

### ISSUE THREAD

**Issue by BrianLima** [Microsoft/Windows-universal-samples#975]
I don't want to build an media player, i would like to query the currently playing song metadata and use it on preferably WPF app.

Anyway to use interop or the UWP bridge to use SystemMediaTransport? Is there even a SystemMediaTransport without the controls part? Or at least use it to query for data that Spotify or another media player is changing on the system?

**Comment by oldnewthing** [comment]
This is not an issue with a sample in this repo. You can open a support case with our Developer Support team who can help further.
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.

Note that not even the UWP SystemMediaTransportControls lets you access information about the current song, so even if you got access to it from WPF, it still wouldn't help you.
