### ISSUE TITLE
Microsoft.Midi.GmDls does not support ARM64

### ISSUE THREAD

**Issue by ianier** [Microsoft/Windows-universal-samples#976]
The title says it all. Compiling to target ARM64 results in the following error message:
error MSB3779: The processor architecture of the project being built "ARM64" is not supported by the referenced SDK "Microsoft.Midi.GmDls, Version=10.0.17134.0".

**Comment by oldnewthing** [comment]
Um, the sample doesn't support ARM64 as a target. I'm assuming you modified the sample and added ARM64? Well, that's not really an issue with the sample any more. You modified it to add something that it doesn't support.
