### ISSUE TITLE
XamlDragAndDrop: Catastrophic Failure 0x80000FFFF

### ISSUE THREAD

**Issue by TimLandskron** [Microsoft/Windows-universal-samples#977]
Issue is described detailed on Stackoverflow.

Link: https://stackoverflow.com/questions/52332573/uwp-listview-gridview-dragitems-results-to-catastrophic-failure

Greetings,

**Comment by oldnewthing** [comment]
It looks like this is a platform issue, not an issue with the sample, but I'll check with the feature team.

**Comment by reghrafa** [comment]
Hey @oldnewthing , do you have any feedback on that? We also do encounter that issue.

Best regards - Rafael

**Comment by oldnewthing** [comment]
Platform team confirms that it is an issue in the platform, not with the sample, fixed in the next Insider build.
