### ISSUE TITLE
Synchronization not allowed

### ISSUE THREAD

**Issue by jecalderon** [Microsoft/Windows-universal-samples#978]
Why I am not getting synchronized from Visual Studio 2017? Getting following error. open he REPO from visual studio and Sync..

Here is a print preview at http://prntscr.com/kuwyss

`Opening repositories:
C:\Users\user\Source\Repos\Windows-universal-samples
Remote: Counting objects: 225, done.        
Remote: Total 225 (delta 138), reused 138 (delta 138), pack-reused 87        
Remote: Permission to Microsoft/Windows-universal-samples.git denied to jecalderon.
Error encountered while pushing to the remote repository: Git failed with a fatal error.
unable to access 'https://github.com/Microsoft/Windows-universal-samples/': The requested URL returned error: 403
Pushing to https://github.com/Microsoft/Windows-universal-samples
`

**Comment by oldnewthing** [comment]
Why are you pushing changes into the repo? If you want to make changes, please use a pull request.

**Comment by jecalderon** [comment]
I am confused. I want to update all reent changes into my local repository. I do not want to push changes to the repo. What is the correct procedure?

**Comment by oldnewthing** [comment]
This is a git question, not a question about the UWP samples repo. You want to Fetch or Pull, not Sync. Sync will push your changes.
