### ISSUE TITLE
Hambuger pattern

### ISSUE THREAD

**Issue by juanpaexpedite** [Microsoft/Windows-universal-samples#98]
in the ControlInfoData.json about the Hambuger pattern the link is "Title": "Hamburger pattern", "Uri": "https://github.com/Microsoft/Windows-universal-samples" }. I do not think that explains anything about the Hamburger pattern, if there is a link about this, is interesting to update to the right link

**Comment by oldnewthing** [comment]
This will be fixed in our next refresh. Thanks for reporting it.
