### ISSUE TITLE
Microsoft::UI::Xaml not capable of CppWinRT

### ISSUE THREAD

**Issue by shithappens2016** [Microsoft/Windows-universal-samples#981]
![111](https://user-images.githubusercontent.com/13523412/45918355-4d9a0700-beb8-11e8-834d-3bfe1a93e31a.png)

**Comment by oldnewthing** [comment]
This doesn't appear to be a issue with a sample in this repo. (Also, I would advise not using an offensive user name.)

You can open a support case with our Developer Support team who can further help with the specific problem you are experiencing. Please use these steps below for further help:

1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
