### ISSUE TITLE
CameraFrames: Access denied exeception with hololens

### ISSUE THREAD

**Issue by jonywalker1998** [Microsoft/Windows-universal-samples#982]
The app was build and deployed into HoloLens successfully, and the HoloLens has been activated into research mode. The app instantiated and found two MediaFrameSourceGroup, one is Sensor Streaming, the other MN34150. The MN34150 group worked, but Sensor Streaming never. The _mediaCapture.InitializeAsync(settings) for "Sensor Streaming" failed always with "Access Denied Exception". Actually, I only need the "Sensor Streaming" for Depth Image. Does anyone know the reason???

**Comment by oldnewthing** [comment]
I've asked the feature team to investigate.

**Comment by oldnewthing** [comment]
What version of Windows are you testing on? The feature team says that this is a known issue in the platform on Windows 10 version 1803. Please upgrade to Insider build 17743 or higher. If you still experience the problem, you can file an issue with Developer Support.

1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.

**Comment by jonywalker1998** [comment]
Hi,
The answer is not correct. I am testing the uwp sample in hololens directly, which has been upgrated to OS RS4. The "access denied" issue was resulted from the wrong runtime linked to the CameraFrame C# project caused by wrong project configuration. Just modify the file CameraFrames.csproj by changing the value in the line 2 Project ToolsVersion="14.0" to "15.0", then the sample works! We have to edit the xml file, because this feature is not configurable over GUI.
Please leave the topic open, since more people would meet the same problem. I even have futher problem with this ToolVersion configuration. Since I am delevoping hololens App with unity, the project code exported by unity has all the ToolVersion = "14.0", thus results in the "access denied" problem again. Manually change the project configuration results in other symbol conflicts to the dlls that are pre-compiled by unity.

best regards

**Comment by jonywalker1998** [comment]
Sorry, my mistake. The exception was resulted from the missing 
<rescap:Capability Name="perceptionSensorsExperimental" />
in the Package.appxmanifest. 
Adding this property did solve the problem, not the ToolVersion.

best regards
