### ISSUE TITLE
WiFiDirect : a connection attempt failed because the connected party did not properly respond after a period

### ISSUE THREAD

**Issue by Tamer-Gamal** [Microsoft/Windows-universal-samples#986]
HI,
i'm deploying the WiFiDirect sample on Pi3 and trying to connect one to another in debug mode, but after the connection based on the status message i got error message in the connector Pi3

> a connection attempt failed because the connected party did not properly respond after a period of time.

I used the C# version from the sample
i'm using the latest version of VS2017 Ent.
the latest version of Win IoT with the Pi3
deploying using WiFi.

Thank you

**Comment by Eg-Virus** [comment]
Nothing ?

**Comment by Tamer-Gamal** [comment]
[Solution](https://github.com/MicrosoftDocs/windows-iotcore-docs/issues/698l)
