### ISSUE TITLE
IP over USB Transport service (IpOverUsbSvc) is not available

### ISSUE THREAD

**Issue by douglaskbell** [Microsoft/Windows-universal-samples#988]
I get this error when I try to run "camera frames" sample.
I downloaded all code examples from here:
https://developer.microsoft.com/en-us/windows/samples
I unzipped into my Windows 10 and opened solution "camera frames".
Builds ok but gets error when I run it.
I changed proj > props > Build > Platform from ARM to x64 and still get error.
Severity    Code    Description Project File    Line    Suppression State
Error       DEP0001: Unexpected Error: SmartDeviceException - The IP over USB Transport service (IpOverUsbSvc) is not available. Retry after installing the IP over USB Transport service (Windows IP Over USB) through the Windows SDK installer. [0x80131500] CameraFrames            
Cannot find solution to error or how to install … 
IP over USB Transport service (Windows IP Over USB)

**Comment by oldnewthing** [comment]
This is not an issue with the sample. This is an issue with your deployment configuration. As noted I the error message, you need to install the IP over USB Transport service in order to deploy to a device.

**Comment by AngelTs** [comment]
Replace "ARM" with "x86" or "x64" in "Active solution platforms" in "Configuration Manager" in VS2017

**Comment by Sunbreak** [comment]
https://social.msdn.microsoft.com/Forums/en-US/1dbc84e4-dcf4-49fb-b5c8-51fad392784c/uwpthe-ip-over-usb-transport-service-ipoverusbsvc-is-not-available
