### ISSUE TITLE
Did you guys create a new repo?

### ISSUE THREAD

**Issue by sebagomez** [Microsoft/Windows-universal-samples#99]
I see only one commit and my forked does not look anything like this one now... I'm no git expert so I don't know if there's anything I can do to catch up. My forked repo says I'm 118 commits ahead of Microsoft master... how is that even possible?

I'm lost here

**Comment by AdamBraden** [comment]
The repo had a breaking change to better manage the size and reduce duplication of files across all the samples.
Now you will find a SharedContent folder for image and common code & XAML files, and the samples leverage Visual Studio links to pull them in.  This reduces the ZIP file to 22MB, and expanded size on disk <50mb.  Previously it was around 170mb ZIP and over 600mb expanded.

If you have local changes, you will need to save them into a branch, and do a hard reset.

**Comment by sebagomez** [comment]
Ok, thanks

**Comment by sebagomez** [comment]
Quick question... after reseting my local changes to the latest version of your repo, what can I do to move those changes to my forked repo at Github? git push does not do it :(

**Comment by oldnewthing** [comment]
Since you made only one change, you can just cherry-pick it.

    git fetch origin master
    git checkout -b topic origin/master
    git branch -f master origin/master
    git cherry-pick e04df661e7bfd60548348a37a196c1d7b132548c
