### ISSUE TITLE
 Hto to get Xbox Wireless Adapter ?

### ISSUE THREAD

**Issue by kenwangyang** [Microsoft/Windows-universal-samples#990]
Does anyone know how to use "Windows.Devices.Enumeration" namespace to get "Xbox Wireless Adapter" on Windows 10 (1803 or 1809) ? If it can't, any namespace I can use ?

**Comment by oldnewthing** [comment]
This doesn't appear to be an issue with a sample in this repo. You can open a support case with our Developer Support team:
 
1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
