### ISSUE TITLE
Refusing connection in simple communication

### ISSUE THREAD

**Issue by CristianKica** [Microsoft/Windows-universal-samples#991]
When i refuse a connection from  node A to node B using `e.Refuse();` or by returning before `e.Accept()` in the `Device_IncomingConnectionArrived` handler, i cannot create a new connection later. I get `MF_MEDIA_ENGINE_ERR_SRC_NOT_SUPPORTED : HRESULT - 0x80072746` the first time the connection is rejected and `MF_MEDIA_ENGINE_ERR_SRC_NOT_SUPPORTED : HRESULT - 0x8007274C `after the next tries.

The `Device_IncomingConnectionArrived `event is not triggered at all.
Is this by design or not? If so, how could one create a connection after the first one is refused/not accepted?

**Comment by oldnewthing** [comment]
This doesn't appear to be an issue with a sample in this repo. (The SimpleCommunication sample never refuses connections.) It appears to be an issue with the platform. You can open a support case with the Developer Support team:

1. Visit http://aka.ms/storesupport and sign-in with your Microsoft account
2. Under the “App Development” section choose "Windows 10 universal app development", then choose the appropriate problem type and category to get engaged through a formal support channel.
