### ISSUE TITLE
Accessibility: Color Picker

### ISSUE THREAD

**Issue by JasonAment** [Microsoft/Windows-universal-samples#993]
Accessibility Bugs: 
In the ColorPicker control, when the IsAlphaEnabled is set to true, this is not accessible or usable. 

1. The label for the RGB hex field when it accepts the alpha channel is incorrect. Currently it reads, "RGB hex...". it should read "Alpha RGB Hex" and also provide formatting requirements to prevent mistakes.
2. Auto formatting is incorrect for 8digits. If I enter a 6 digit Hex value (as the label would suggest). That 6 digit hex value is by default a 100% opacity. I would expect the auto formatting to respect this default opacity, but instead it incorrectly outputs 0% opacity. It's as simple as replacing the "0" with "F". For users with vision or cognitive disabilities this is confusing and causes unexpected outputs. It should validate and provide an error message. 
3. If a user enters an incorrect amount of characters, it does not provide validation or an error. It just replaces the empty characters with "0" and passes it through. This often has the incorrect affect of making the user believe they entered a correct value, but in fact they didn't and now it's way off of the original intent because of incorrect auto formatting. (e.g. entering 5 or 6 digits will autoformat to a transparent color; Entering 7 digits will autoformat to a different semi transparent color)

**Comment by oldnewthing** [comment]
This appears to be an issue with the control itself, not with the sample. I've informed the feature team, but closing this issue because it is not an issue with the sample.

**Comment by YuliKl** [comment]
Thank you, @JasonAment, for elevating these issues. The feature team has been notified of this and your message from [User Voice](https://wpdev.uservoice.com/forums/110705-universal-windows-platform/suggestions/35621884--accessibility-color-picker). We're working to correct these problems.
