### ISSUE TITLE
WindowsAudioSession sample does not do stream redirection if the default audio device changes

### ISSUE THREAD

**Issue by mvaneerde** [Microsoft/Windows-universal-samples#994]
Many audio APIs will automatically follow the default audio device, e.g. if you connect or disconnect an audio headset (3.5mm, USB, or Bluetooth).

WASAPI supports this via [passing DEVINTERFACE_AUDIO_RENDER or DEVINTERFACE_AUDIO_CAPTURE to ActivateAudioInterfaceAsync](https://docs.microsoft.com/en-us/windows/desktop/api/mmdeviceapi/nf-mmdeviceapi-activateaudiointerfaceasync)

It is also possible to listen for the [Windows.Media.Devices.MediaDevice.DefaultAudioRenderDeviceChanged](https://docs.microsoft.com/en-us/uwp/api/windows.media.devices.mediadevice.defaultaudiorenderdevicechanged) or [Windows.Media.Devices.MediaDevice.DefaultAudioCaptureDeviceChanged](https://docs.microsoft.com/en-us/uwp/api/windows.media.devices.mediadevice.defaultaudiocapturedevicechanged) events, and tear down and recreate the stream accordingly.

But the sample does neither of these things. So if you start playing on the speakers, and then plug in headphones, the sample continues to play to the speaker.

**Comment by oldnewthing** [comment]
I've asked the feature team to determine whether this is something they want the sample to demonstrate.

**Comment by firozd** [comment]
Thanks for your feedback & question.  This sample demonstrates the minimal work to provide offload and low latency. A future sample will show how to manage audio stream redirection on device changes.
