### ISSUE TITLE
RPCServer makes the COM+ unavailable

### ISSUE THREAD

**Issue by cjw1115** [Microsoft/Windows-universal-samples#996]
I download a sample code from this repos.
When I build it and deploy the service to my computer(RS4), It will make the COM+ unavailable.

Here are my steps:
1.	Open solution CustomCapability.sln (Windows-universal-samples\Samples\CustomCapability\cs\ CustomCapability.sln)
2.	Build project RpcServer. It will create a .exe (Windows-universal-samples\Samples\CustomCapability\cs\Win32\Debug\RpcServer.exe)
3.	Install windows service.(RpcServer.exe -install)
4.	Open Windows Services manager and find out “Hsa Sample Service(HsaService)”, Change the startup type of it to Automatic, save it.
5.	Restart the OS.
6.	Open Component Services and select Computers node. We will find that COM+ is disabled.

**Comment by guzhipeng** [comment]
This bug already effect lots of models in the market. All PCs can't use DCOM.

**Comment by cjw1115** [comment]
Here is solution.
pull request https://github.com/Microsoft/Windows-universal-samples/pull/1003
