### ISSUE TITLE
How to get the paramrters in the 'SingleAccountScenario' of 'WebAccountManagement' sample?

### ISSUE THREAD

**Issue by xiedongweo** [Microsoft/Windows-universal-samples#997]
I want to test the 'SingleAccountScenario' in 'WebAccountManagement' sample.

But there're some parameters that I do not know where to get.

For example,
`const string AppSpecificProviderId = "myproviderid";
        const string AppSpecificProviderName = "App specific provider";

        const string MicrosoftProviderId = "https://login.microsoft.com";
        const string MicrosoftAccountAuthority = "consumers";
        const string AzureActiveDirectoryAuthority = "organizations";

        const string StoredAccountIdKey = "accountid";
        const string StoredProviderIdKey = "providerid";
        const string StoredAuthorityKey = "authority";

        const string MicrosoftAccountClientId = "none";`

Could anyone help me or give me some guidelines how to get these parameters?

**Comment by oldnewthing** [comment]
The `MicrosoftProviderId`, `MicrosoftAccountAuthority` and `AzureActiveDirectoryAuthority` `MicrosoftAccountClientId` values are fixed. The others can be anything you want.
